### ISSUE TITLE
ert_tcp_server and ertshell are not installed

### ISSUE THREAD

**Issue by agchitu** [equinor/ert#10]
One of these applications are needed in order to start the ert server that will allow sending batch simulation requests to ert. These applications seem to be missing form the current deployment. 
Also it would be great if these will not be linked to ert_gui.
I was told that this might not have too large priority but  I want to create the issue just in case... so you know that there is at least somebody that thinks they are useful.

**Comment by joakim-hove** [comment]
We'll fix this.

**Comment by ManInFez** [comment]
Ert-tcp-server does not exist anymore, and ertshell is on the way out the door. Closing issue!
