### ISSUE TITLE
Black requirement

### ISSUE THREAD

**Issue by berland** [equinor/ert#1043]
` black`, pinned to version 19.10b0, is required in `requirements-dev.txt`, but it is not used (?) in CI,  neither do the `*.py` source files comply with it. Suggest to either remove it from requirements, or blacken all files (probably to newest black version).

**Comment by markusdregi** [comment]
It is used in the test suite, but only for new and heavily changed files to avoid messing up all of our git history...

It was pinned to get open pull requests in. There is also the never ending discussion on pinning or not pinning dependencies for CI and development 🤷

**Comment by markusdregi** [comment]
Resolved in https://github.com/equinor/ert/commit/0dc4f1c27dca7d075316d3d66db243d95eeeef00#diff-913fedaed3cb05fe362c0ceb35e2d827
