### ISSUE TITLE
A new test data set

### ISSUE THREAD

**Issue by jepebe** [equinor/ert#1045]
I believe that we need a need test data set that is more complete with respect to the possibilities of ERT. It should be fast running and provide output that includes:

* Failed realizations
* Multiple observations and toggling of these 
* Multiple response sets
* Multiple groups of priors/parameters
* Branching of ensembles
* An Ensemble that has not been run after update
* ...?

One of the reasons for this is to simplify testing of the storage API wrt. completeness of features.

**Comment by markusdregi** [comment]
Sounds like a good idea 👍 Related to #833
