### ISSUE TITLE
Workflow hooks and manual update

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1050]
Currently the workflows hooks are not triggered when doing a manual run. Should we expose that possibility in the future?

**Comment by jondequinor** [comment]
What's a manual run?

**Comment by oyvindeide** [comment]
Running the required steps outside of the pre-defined models that has hooks, by using `Run Analysis` and `Ensemble Experiment` (which only has simulation hooks). I am not sure how common that is to do though.

https://github.com/equinor/ert/blob/24805f3d61648ff05de5db61185f4035c9b6962f/ert_gui/tools/run_analysis/run_analysis_tool.py

**Comment by markusdregi** [comment]
Users are advised to evaluate their priors before running the entire setup, so I'm suspecting it is getting more and more usual... :)

**Comment by oyvindeide** [comment]
Should add an option to run PRE_ANALYSIS, PRE_FIRST_ANALYSIS and POST_ANALYSIS worfklows to the manual update tool.
