### ISSUE TITLE
Generating kw data very slow

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/ert#1052]
I am using a custom keyword option GEN_KW:

```
# conf.ert

GEN_KW MYKW DATA/KW_TMPL.TMPL KW_GEN.DAT DATA/KW_DIST.DIST INIT_FILES:REALIZATIONS/KW_REAL.DAT
```

My GEN_KW object is of size of 24000:

```
# KW_DIST.DIST

PARAMETER_0 RAW
PARAMETER_1 RAW
PARAMETER_2 RAW
...
PARAMETER_23805 RAW
```

```
# KW_TMPL.TMPL

PARAMETER_0 <PARAMETER_0>
PARAMETER_1 <PARAMETER_1>
PARAMETER_2 <PARAMETER_2>
...
PARAMETER_23805 <PARAMETER_23805 >
```

Having 100 realizations it takes about 2h to generate simulation directories for one iteration before forward models execute. I also noticed it is not done in parallel. I am not copying any large files, I only have:

- MODEL.DATA
- KW_GEN.DAT
- parameters.json
- parameters.txt 
- jobs.json

My question is, am I  setting up something in an inefficient way or is this behavior expected for this amount of data?
Perhaps using matrix instead of a vector with GEN_KW if this is possible? 

@edubarrosTNO

**Comment by markusdregi** [comment]
Dear @edubarrosTNO!

Thank you for reaching out. You are correct in that the runpath is not created in parallel, as it in addition to a speed up, came with a significant number of problems. A possibility right now is to try using the `GEN_PARAM` keyword instead, this will give you a vector of parameters and should be much faster.

We are also working on new data types for input and output, but this will take some time... :)

**Comment by markusdregi** [comment]
Ah, good point :) I did indeed read it as your signature. Please do, and let me know if it did not get any better.
