### ISSUE TITLE
Recategorize and sort forward models in documentation

### ISSUE THREAD

**Issue by berland** [equinor/ert#1072]
Forward models are filling up in the documentation. Some of them should possibly be recategorized and there should be sorting within each category.  Categories are set in multiple repositories out of control of ERT itself, and should be a coordinated effort.

![image](https://user-images.githubusercontent.com/306834/96087547-4f322f80-0ec4-11eb-9c4d-bc900a7930d5.png)

**Comment by markusdregi** [comment]
Good point :+1:

**Comment by sondreso** [comment]
Most forward models submit more detailed categories (category.sub_category) than what is rendered in the documentation today. Should be fairly easy to at least include that extra layer :slightly_smiling_face:

**Comment by berland** [comment]
Yes, revisiting all categories can be put on hold until we see the effects of just using the sub-categories and sorting.
