### ISSUE TITLE
Write a getting started section

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1111]
I suggest we write a `Getting started` section almost at the top in the README with the minimum amount of steps to `pip`-install ERT and run the poly-case. This should help people get easily started 👏

**Comment by sondreso** [comment]
Great idea! I would probably also remove the current [example usage](https://github.com/equinor/ert#example-usage) section as well, or at least rewrite it a little.

**Comment by dafeda** [comment]
The README has been updated since and now contains instructions on how to get started.
