### ISSUE TITLE
history and refcase plotting in new storage

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1120]
A few dummy functions were added to `ert_shared.storage.client` in https://github.com/equinor/ert/pull/921 that needs to be implemented for increased compatibility with old storage plotting.

When running snake_oil case, eg.` FOPR`'s Ensemble plot will have 3 items in its legend with old storage, but only 1 with new storage. This is because of https://github.com/equinor/ert/blob/35395372e6cbde1df59020d51bab4752d1952810/ert_shared/storage/client.py#L189-L197

This evaluates to false:
https://github.com/equinor/ert/blob/35395372e6cbde1df59020d51bab4752d1952810/ert_gui/tools/plot/plot_window.py#L114-L115

This too:
https://github.com/equinor/ert/blob/35395372e6cbde1df59020d51bab4752d1952810/ert_gui/plottery/plots/refcase.py#L4-L9

**Comment by oysteoh** [comment]
Should not be implemented in new storage - we are moving away from refcase.
