### ISSUE TITLE
Pass forward model ID to job_dispatch

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1128]
Look into passing a unique ID to `job_dispatch` for each of the forward models that later can be used to fetch the necessary data.

**Comment by sondreso** [comment]
See also: https://github.com/equinor/ert/issues/1069

**Comment by markusdregi** [comment]
Might not be necessary due to Sondre's comment. Maybe we can use the ID they are passing...

**Comment by markusdregi** [comment]
I suggest we move with the functions for now
