### ISSUE TITLE
Look into how observations are persisted wrt Active / Not active

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1133]
Currently the observations belongs to the ensemble currently dumped to db. They should probably belong to the update step.

**Comment by oysteoh** [comment]
Should possible be coordinated with the owls's configurationwork

**Comment by sondreso** [comment]
The observations are not linked to the ensemble: '

https://github.com/equinor/ert/blob/ee-api/ert_shared/storage/entities_model.py#L298-L314

However, the extraction module checks if the observation is already added to the database, and skips if it is: 

https://github.com/equinor/ert/blob/ee-api/ert_shared/storage/extraction_api.py#L51-L52

But there should probably be a link between observations and update steps yes :slightly_smiling_face:

**Comment by dotfloat** [comment]
Our suggestion is that we have a new model called `ObsTransform` or the like (`ObservationTransform`?) This model references an existing `Observation`. The `Update` model references zero or more of `ObsTransform`s. Each `ObsTransform` object changes one or more values for a single `Observation`, either by scaling, activating or deactivating them. To obtain the fully transformed observations, one would need to apply each `ObsTransform` to `Observation` in order.

I am uncertain whether transforms need to be propagated to future `Update`s. Eg, the following scenario:
1. Update 1: scales all values by 2
2. Update 2: scales all values by 3

In the end, the observations should be scaled by 6. Should Update 2 contain the transforms of Update 1 (ie, `[scale by 2, scale by 3]`), or should the observations after Update 2 be obtained by taking the original data, applying transforms of Update 1 followed by transforms of Update 2?
