### ISSUE TITLE
Run ERT in Azure and document how to do so

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1150]
Verifies that `ert3` runs on the PBS cluster and document all the necessary steps to get this running.

**Comment by markusdregi** [comment]
It now seems to work. I did at least succeed at the following:

```
python3 -m env env
source env/bin/activate
pip install --upgrade pip
pip install ert
ert --help
```

Perhaps next step would be to fetch the `ert3` branch and see if we can get the `ert3` binary to run. Afterwards, let us try to change the driver in the function evaluator to `psb` and see how that goes :)

**Comment by lars-petter-hauge** [comment]
Can at least verify that I get the same behaviour. Also installed the ert3 branch and ran the `ert3 init`-> `ert3 run evaluation` successfully.

**Comment by sondreso** [comment]
I have updated the `ee-function-ensemble` branch and I'm now able to run the `showcase_function_ensemble.py` using the PBS cluster. You should be able to do the same by setting `executor="pbs"` in the evaluate function (yes, I fixed the uppercase vs. lowercase inconsistencies :sweat_smile:).

**Comment by oyvindeide** [comment]
Steps to run locally: 
```bash
python3 -m venv ert_env
source ert_env/bin/activate
pip install --upgrade pip
pip install git+https://github.com/equinor/ert.git@ert3 (can be omitted if installing local copy in step 5)
git clone https://github.com/equinor/ert.git
cd ert/examples/polynomial
ert3 init
ert3 run evaluate
```

Steps to run `pbs`:
 Assuming steps for local have been completed (`pip install` can be omitted) and standing in `ert` root:
```bash
`vim ert/ert3/evaluator/_evaluator.py
```
Change `"local"` to: `"pbs"`  in `def evaluate`
``` bash
pip install -e .
cd examples/polynomial
ert3 init
ert3 run evaluation
```
Have to `git clean -xdf` if an experiment of the same name has completed earlier (for example with `local`)
