### ISSUE TITLE
Have job_dispatch report status over the network

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1156]
There is currently an NFS-adaptor implemented for pushing events back to the ERT client from job_dispatch. Implement a similar adaptor that transfers the events over the network instead.

**Comment by sondreso** [comment]
Probably not an adaptor, but rather a modified version of the event reporter that we have made here: https://github.com/equinor/libres/blob/master/python/job_runner/reporting/event.py

Just instead of dumping data to disk, it sends the event over the network.

**Comment by jondequinor** [comment]
Yes, the modification could be to _tee_ the events to disk and network (ws).

**Comment by markusdregi** [comment]
I suggest we move with the functions for now
