### ISSUE TITLE
Replace the dummy evaluator

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1172]
After resolving #1164 we should look into replacing it with the new ensemble evaluator of the owls. If it is not ready for usage, document why, what it would take and look into using prefect directly for now.

**Comment by sondreso** [comment]
It's probably not ready :grimacing:  But I think it would be nice to have a discussion about what you are trying to do and how, so that we could align a little bit and maybe produce something you can tests out.

**Comment by markusdregi** [comment]
Goal: Evaluate a second degree polynomial (specified as a forward model job) on the current torque cluster in Azure without any shared disk communication. It could be that we have to implement some of this ourself, especially due to our `unix_script` step type that we need, but that is not exactly a native type of any modern workflow manager. But, it would be good to identify where for instance `prefect` stops and our responsibility would start... I'm thinking that we can do this by either tooling on top of the ensemble evaluator, or by a very limited direct `prefect` consumption, for which later can be replaced by the ensemble evaluator.

I would love your input on this; either here or at 12:30 on teams ;)

**Comment by sondreso** [comment]
> Evaluate a second degree polynomial (specified as a forward model job) on the current torque cluster in Azure without any shared disk communication. 

This I believe you would be able to do in 15-ish lines of code with prefect. 

> due to our `unix_script` step type that we need, but that is not exactly a native type of any modern workflow manager.

Do we need this? If we are only running things that could be pure Python, then this is unnecessary. We can probably do this, but then the above estimate of 15 lines will be _much_ larger.

**Comment by markusdregi** [comment]
Whether we need `unix_script`? For sure... But, we can probably start of with the 15 lines of code :) That is why I'm thinking that it is justifiable to patch it on our side if EE is not ready yet. And then we should start consuming EE ASAP...

**Comment by sondreso** [comment]
> Whether we need unix_script? For sure...

I meant if you need it for evaluation of the polynomial; however, the second part answers that ;) But I really think we would benefit from a sync here before we sit down and start typing code on the keyboard! Should the owls (or at least parts of it) join the beginning of you workshop session?

**Comment by markusdregi** [comment]
That would be excellent! Do you have time at 12:30? You are all welcome :)

**Comment by markusdregi** [comment]
Done
