### ISSUE TITLE
Create function ensemble

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1176]
Create function ensemble that can evaluate realizations running only one function, that also integrates with the ensemble evaluator and produce events

**Comment by sondreso** [comment]
Function ensemble is created and awaiting feedback from the sloths

**Comment by markusdregi** [comment]
Thanks :) I wanted to review and complete the `ee-api` branch first. But let me know if that strategy does not make sense...

**Comment by jondequinor** [comment]
Any progress here? ee-api has landed, so that's outta the way

**Comment by sondreso** [comment]
I could rebase the current function ensemble branch on top of master and get i ready to be merged. But if this should be merged or not, I think depends on the feedback from the sloths (@markusdregi) :slightly_smiling_face:

**Comment by sondreso** [comment]
First iteration of function ensemble in use by the sloths
