### ISSUE TITLE
Create filtering / regex on the keys instead of having a huge dropdown

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1179]

**Comment by ManInFez** [comment]
There is already the functionality, while not true RegEx it handles <space> as a wild-card. For instance "GO H" yields "W**GO**R**H**:OP_1, "W**GO**R**H**:OP_2, "W**GO**R**H**:OP_3, ..."

**Comment by ManInFez** [comment]
exisiting solution good enough
