### ISSUE TITLE
Make function to be evaluated configurable

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1192]
As of now the evaluator is hard coded to evaluate a second degree polynomial. We should make it an arbitrary Python function configured in the setup.

This issue should probably start with a suggestion for how to configure it; before an implementation is made...

**Comment by oyvindeide** [comment]
I guess we want different options for doing this in the long run, with some functions internal like today, and the option of giving user defined functions. One option is to use the syntax from for example in `setup.py` of `"mod1.mod2:function"`

**Comment by oyvindeide** [comment]
After discussing with @markusdregi we came up with a few different ways of loading functions that should probably be available.

1) Loading a function from the environment, possibly in the form mod1.mod2:func
2) Registering a function with the plugin system, which can be added with an alias to make it easier to configure for the user
3) Possibly loading a function from a given file outside the environment

These methods should converge almost immediately in the code so we only have one implementation past the configuration.

**Comment by markusdregi** [comment]
Yes, and I think the first implementation can assume 1. 👍
