### ISSUE TITLE
Improve loading data from old storage

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1208]
The way `ert_data.MeasuredData` loads data is highly inefficient when there are many obs keys to fetch. This is especially true for `SUMMARY_OBS`, as for every key, it loads all summary data and all summary observations before it filters one a single key. This needs to be improved.

The MeasuredData links the observations to the responses by iterating over all of them and the fetching the data. A suggestion is would be to fetch all data and all observations separately before linking them together in one big swoop. 

Feel free to discuss.

**Comment by oyvindeide** [comment]
Depending on the time frame for getting this data directly from new storage, I think this would be a good improvement to make. It should not be very complicated, and if the time frame for getting this data from new storage is on the order of months, it would probably be worth it.

**Comment by oysteoh** [comment]
@oyvindeide should something be done here og just close the issue?

**Comment by oyvindeide** [comment]
Should at least be improved now, so safe to close this issue.
