### ISSUE TITLE
Explore database in Azure

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1230]
In addition to testing pulling data from the database in ERT (see #1158), we could explore fetching data on the compute side from an Azure hosted database. If we implement #1158 first we can look into backing the same API by an Azure instance. But we could also test pulling data from an Azure database before this. For instance, we could get a Blob Storage up and running and try to pull the data for the different realisations from that storage instead. If so, comparing stability, speed and cost with transferring directly via the Ensemble Evaluator would be interesting. Especially for a dataset of larger size then the current polynomial case. This can be achieved by blowing up both the number of coefficients as well as passing a larger sets of `x`-values directly.

**Comment by oyvindeide** [comment]
Have reached out to the infrastructure people, and they are currently looking into setting up a blob store.

**Comment by oyvindeide** [comment]
We have not heard back from infrastructure yet, and are not currently working on this issue. I will close it, and we can reopen when and if it becomes relevant.
