### ISSUE TITLE
Document polynomial

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1232]
Make `README` in the polynomial example that explains how to run it and why it is as it is.

**Comment by sondreso** [comment]
Do we mean the standard poly example here, or the new ert3 example?

**Comment by markusdregi** [comment]
As vaguely indicated by the milestone it is the `ert3` version ;)

**Comment by sondreso** [comment]
Just wanted to be sure, because I think we should do both :joy:

**Comment by eivindjahren** [comment]
The ert3 version of the example did have some documentation as I remember. For ert2 this is a subtask of #833

**Comment by oyvindeide** [comment]
Since the README of the poly_example is complete, I will close this issue as ert3 no longer exists.
