### ISSUE TITLE
Implement a testing ensemble

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1233]
We need ensembles (currently only prefect and legacy) to be a bit more sophisticated than merely implementing `evaluate` and `cancel`. They need to communicate to the evaluator as well.

We have a base `Ensemble` that "implements" the methods, but does not communicate. This makes some of our code awkward to ensure that tests pass.

Should a `TestEnsemble` be implemented that:
- appears to the `EnsembleEvaluator` to be a proper ensemble
- can be configured to 1) fail nominally, 2) fail unexpectedly (crash, network errors, split brain e.g.) 3) be extremely sluggish

❓

**Comment by sondreso** [comment]
Could be useful in connection with #1235
