### ISSUE TITLE
[ert3] increase data amount for test

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#1249]
Current poly test has a low amount of data samples for each realization.

Add a test in which we pass forward e.g. 5 MB to each realization and retrieve equally amount of data.

**Comment by markusdregi** [comment]
This could be achieved in a realistic manner by setting up a case where `x` is passed as a resource and hence not defaulted. I was actually thinking more like a 100 MB, but we can do 5 first 😂

**Comment by oyvindeide** [comment]
Ran this with a realization size of roughly 80 mbs with local and pbs. The run time is roughly 1200 s with the local driver and 2000 s with pbs. I did it by increasing the `x_range` for the polynomial.

**Comment by sondreso** [comment]
What is the normal runtime? @oyvindeide

**Comment by oyvindeide** [comment]
Depends on what you mean by normal (x_range=10?). I can run it with a few different x_ranges to plot out a trend if desired.

**Comment by sondreso** [comment]
Yes, was thinking about x_range=10 :smile: Not really important, was just curious of the overhead.

**Comment by oyvindeide** [comment]
The runtime is 12 s and 760 s for local and pbs respectably with 10 vs. 1000000 as the x_range.
