### ISSUE TITLE
Adopt to fresh pandas version in measured.py

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1262]
> py.warnings - WARNING - /prog/res/komodo/2020.11.00-py36-rhel7/root/lib/python3.6/site-packages/ert_data/measured.py:91: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
To accept the future behavior, pass 'sort=False'.
To retain the current behavior and silence the warning, pass 'sort=True'.
 measured_data = pd.concat([measured_data, data], axis=1)

**Comment by jondequinor** [comment]
(Packaging _related_)

**Comment by dafeda** [comment]
`pandas` version 1.0.0 was released Jan 30, 2020 where `concat` was changed to not sort by default, and will not (as far as I know) throw any FutureWarning.

Based on this, perhaps this issue can be closed?

**Comment by markusdregi** [comment]
I agree 👍🏻
