### ISSUE TITLE
created_at, updated_at columns in the new storage

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1273]
Currently, on Ensembles have `datetime` column for when it was created. Extend this to _all_ tables so that it is easy to know when a change was made.

**Comment by oysteoh** [comment]
But currently we are dumping each ensemble with all of its data ( realizations and such ) - thus they should have the same timestamp? I guess it will make perfect sense in the future when each realization maybe is posted individually - but do we need it now?

**Comment by dotfloat** [comment]
I think this is one of those weird instances where adding these columns makes the database simpler. Like having an `id` column even if you don't intend to refer to rows with an `id` immediately. Basically, imo the defaults should be `id`, `created_at` and `updated_at` for all tables unless it makes more sense to not have it.

The immediate use is in `ObservationAttribute`, which are created after observations are created.

**Comment by dotfloat** [comment]
I was considering using abstract `declarative_base` to automatically add these + `id` to all entities. The approach I considered was:
1. Use `declarative_base`'s `base=` (or something similar) to set an outer base.
2. Specify `__abstract__ = True` in a subclass of `Entity`, which specifies these fields.

**Comment by oysteoh** [comment]
yes, we discussed during standup. I think i just un-assign this from me - and you guys ( @dotfloat and @ManInFez ) adding this to the tables which needs it when doing your iteration now on the database with a lot of changes.
