### ISSUE TITLE
Use pytest-forked

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1280]
`pytest-forked` (https://pypi.org/project/pytest-forked/) is a pytest addon that runs every test as a separate subprocess. If a test crashes with a `SIGABRT` or `SIGSEGV`, it won't bring down the entire `pytest` process, rather it'll just become a single failed test. This is very useful in our codebase due to the underlying fragile C code.

Depending on how much slower this is, we could tag all tests relying on some C code as fragile, and only run them, while keeping the new Python-only stuff  (meaning it doesn't touch any libecl/libres code) `--forked`-less.

**Comment by oyvindeide** [comment]
Think I will close this as our tests are much more stable now, and there is much less fragile C code
