### ISSUE TITLE
Observation and parameter grouping in ERT Storage

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1289]
I think I have an okay way of doing custom groupings of data in ERT while also keeping it relatively easy to submit data.

**As I understand it**:
In the ensemble filter algorithm, both observations and parameters are represented as a huge _n_- and _m_-vectors, respectively. ERT lets the user labels subsets of these two vectors by observation keywords. Eg, if the user specifies observations:
* `OBS1` with _**a** = (a<sub>1</sub>, .., a<sub>5</sub>)_
* `OBS2` with _**b** = (b<sub>1</sub>, b<sub>2</sub>)_

The resulting observations used by the algorithms is the concatenated 7-vector _**ab** = (a<sub>1</sub>, .., a<sub>5</sub>, b<sub>1</sub>, b<sub>2</sub>)_. The keyword `OBS1` then is a label applied to the elements _1_ to _5_ in this vector and `OBS2` to _6_ and _7_. This ordering comes from user's `.ert` file.

We wish to not only support these groupings as they come from the user's files, but also other groupings that may come from sources such as clustering.

**Current implementation**:
Currently, the Storage has a table of observations and parameters, where each user group is a separate row and contains its values. Eg, if the above observations were stored, we'd have two separate rows in the table, where the first one has 5 elements and the second has 2. The ordering of groups is not persisted, but can be assumed to be the same as the order of `id`s.

**Proposal**:
We separate the values from the labels. Have a `observation` table and a `observation_label` table (replace "observation" with "parameter" for the case with parameters).

The `observation` table consists of rows with just unlabeled data, offset from 0:
```
observation {
  ensemble_run_id int
  offset int
  length int
  values float[]
}
```

The `observation_label` table contains only the label data, also offset from 0:
```
observation_label {
  ensemble_run_id int
  offset int
  length int
  name string
}
```

In order to create the _n_-vector as used by ERT, one would only need the `observation` table. The ordering is explicitly given, and it is possible to check for gaps and overlaps.

The `observation_label` provides a way to label the data points in more than one way. It is assumed that the `name` can repeat, so as that it's possible to eg. have a group of all evenly-indexed data points, by creating far too many rows.

The reason for allowing `observation` to split is to make it easy to upload an observation. Currently they're uploaded in groups according to the user's configuration, and it'll allow us to continue doing this approach. Note that it's entirely possible to store the vector as in a single row, but at the time it's probably more work than is worth.

Note that I've chosen to store the data in a offset-range format rather than something else entirely arbitrarily. It should be easy to change once we see the scope of the data.

Note also that while I'm tying these objects one-to-many-ly to ensemble runs, this is not necessarily the case and will most likely be implemented entirely differently.

**Comment by markusdregi** [comment]
This appears to be a feasible technical approach! However, it would be great if you could address the various use cases in https://github.com/equinor/webviz-ert/issues/60#issuecomment-756273400...

**Comment by dotfloat** [comment]
The implementation of transforming the observation values will be a separate issue. This issue is how to store and address the raw observation data as given by the user at ensemble run start. This proposal will allow to label the data in multiple distinct ways. However, the transformations themselves are stored separately and are beyond the scope of this particular issue.

I could envision a:
```
observation_transform {
  ensemble_run_id int
  offset int
  length int
  set_active bool?
  scale float?
}
```
Where fields marked with `?` are nullable. A `set_active` that is `NULL` means not to change whether it's active. A `scale` that is `NULL` is the same as scaling by 1. Other operations will be added.

Then there is a sequence of these `observation_transform`s. To obtain the final observation data, you'd start with the data in `observation` table, go apply the sequence and voila. Caching this will be handled separately.

**Comment by markusdregi** [comment]
Does this issue extend beyond https://github.com/equinor/webviz-ert/issues/60 @dotfloat? If so, should we move it to `ert-storage`?

**Comment by dotfloat** [comment]
This issue has little to do with https://github.com/equinor/webviz-ert/issues/60 . Closing as I have since realised that this is not necessary.
