### ISSUE TITLE
Document how to restart ES-MDA in GUI

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1290]
ERT v 2.14 introduced the possibility to restart ES-MDA from an existing iteration , eg after a crash. The procedure is quite complex and easy to get wrong, as the user has to understand the case concept in ERT and set the case name and iteration number accordingly. There is a description of how this works in the rel.notes, but not explained elsewhere in the documentation. There is an empty tab in the documentation for the GUI, where it might fit in.  I  propose to provide a recipe of how to restart ES-MDA.

**Comment by frode-aarstad** [comment]
I have tried with my limited knowledge of ES-MDA to capture the description above in a image. Please comment @sondreso @eivindsm 

![restart-es-mda.PNG](https://images.zenhubusercontent.com/5f7c6199af8f0314c28e6cc8/49d4625e-7acf-41ce-a6f1-4e3269246237)

**Comment by eivindsm** [comment]
I support this; the explanation complemented with this image should do the trick.
