### ISSUE TITLE
Remove coefficient generation in the Prefect Ensemble

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#1302]
Coefficient sampling and storing should not be the responsibility of the Prefect ensemble.

Decide what component should be responsible for coefficient sampling and storing and remove the logic from the Prefect ensemble evaluation.

**Comment by markusdregi** [comment]
After #1311 have been merged I think we can just remove it without any movement as sampling is already happening there. Then we at least have narrowed it down to one place, and then we can continue the discussion whenever appropriate on whether to move it even further...
