### ISSUE TITLE
Add name of config-file as metadata to an ensemble 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1308]
For now, we should add the name of the configfile to the ensemble. At later stages with the introduction of ERT3 there will be more context to be added.

**Comment by oysteoh** [comment]
The name of the config-file better suits in the project itself - which we don't use in our database currently. This will be introduced with ERT3. This issue needs to wait until it's clarified what concepts / data / relations ERT3 will introduce

**Comment by oysteoh** [comment]
Relates to #1383

**Comment by markusdregi** [comment]
The motivation of the issue is unclear and in addition appears to not be actionable at the moment. I'm thinking it can be closed, but feel free to reopen if you disagree.
