### ISSUE TITLE
The ensemble object should create the snapshot

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#1313]
Currently, the ensemble evaluator contains the logic of creating the snapshot. I think that logic should be moved inside the ensemble

**Comment by markusdregi** [comment]
The motivation for the move is not immediately clear to my. Could you please elaborate @DanSava?

**Comment by jondequinor** [comment]
The method `create_snapshot` doesn't _need_ to be in the `EnsembleEvaluator`, and within it, it executes a bunch of snapshot API, when it really should only have to call `ensemble.to_snapshot()`.

So it's smells a bit due to the feature envy/inappropriate intimacy.
