### ISSUE TITLE
ERT will crash when there is no START keyword in the DATA file

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1319]
**Describe the bug**
The following is displayed if the DATAFILE does not contain a START keyword, even though START is not required by the simulator if only TSTEP is used.

![image](https://user-images.githubusercontent.com/3437958/106103700-a2618280-6141-11eb-875b-f63d427a9f87.png)

The exception is triggered by this line:
https://github.com/equinor/libres/blob/master/lib/enkf/ecl_config.cpp#L139

However, the start date is not used anywhere else in the code, and could probably be removed.

**To Reproduce**
1. Run the setup in the attached file 
[ert_debug.tar.gz](https://github.com/equinor/ert/files/5885465/ert_debug.tar.gz)

**Expected behavior**
It should not matter to ERT whether the START keyword is set or not, this should be left to the simulator. 

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: bleeding
 - Python version: 3.6
 - Remote/HPC execution involved: Affects both local and remote execution

**Additional context**
Reported by user on Slack

**Comment by mortalisk** [comment]
Setup was failing even when we uncomment START keyword. However, it was failing with SEG FAULT in stead of the util_abort. Eclipse accepts the DATA file.

**Comment by mortalisk** [comment]
Note: When there is no START keyword Eclipse will use default value, which is different for ecl100 and ecl300. OPM uses the same as ecl100.

**Comment by mortalisk** [comment]
equinor/ecl#815 was tested with local queue, but not with LFS

**Comment by markusdregi** [comment]
Did you look into just removing the `start_date` variable all together in `libres` instead of patching the parsing of it? There is no need for ERT to parse the Eclipse deck beyond what it **really** needs to ™️
