### ISSUE TITLE
Run HM tutorial for the ensemble evaluator

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1322]
**Definition of done:**

The HM tutorial should run as part of the Jenkins test pipeline for new releases.

**Comment by sondreso** [comment]
Update: Hangs forever with both the normal and short HM tutorial

**Comment by sondreso** [comment]
Works with the short hm tutorial, but the long hm tutorial fails because the parallell stages tries to open websocket servers on the same port.  This is blocket by #1358

**Comment by sondreso** [comment]
Update: The above issue is now fixed, but now the HM tutorial fails with unsuccessful realisations. Needs further investigations.

**Comment by mortalisk** [comment]
This runs now after we have removed the nfs adaptor in #1517

**Comment by jondequinor** [comment]
Where's the jenkinsfile for the ee hm tutorial job?

**Comment by sondreso** [comment]
It uses the same Jenkins file as the normal HM tutorial, but a new job was created that sets the `ERT_OPTIONS` parameter to `--enable-ensemble-evaluator` 🙂

**Comment by mortalisk** [comment]
I just realized this will screw up the current release. I therefore changed the jenkins job to only print hello world for now. After the release, we can make it run the hm-tutorial again
