### ISSUE TITLE
Rip out the legacy legacy consumption

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1323]
Legacy tracker would be really good to kill.

**Why?**
During the work of creating the evaluator and the event based interaction between the evaluation and the monitoring the existing mechanism of communicating directly via shared memory was kept. First, it was kept as default and later as a fallback mechanism via `--disable-ensemble-evaluator`. It is time to remove the option of direct memory communication to lower the complexity of the implementation.

**Definition of Done**
The option `--disable-ensemble-evaluator` is no longer supported and the code to support it is removed.

**Comment by markusdregi** [comment]
Seems like we are going to be stuck with the legacy evaluator on-premise for quite some time @jondequinor. Was that the code you wanted to get rid of or the legacy legacy consumption? And if the first, do you think keeping the issue around given the current expected timeline makes sense?

**Comment by sondreso** [comment]
the legacy legacy consumption (and translation to "fake" snapshots) is what we want to get rid of, so think this issue still makes sense!

**Comment by jondequinor** [comment]
Updated. Sondre is correct, was probably thinking about the legacy tracker.

**Comment by markusdregi** [comment]
Thanks for the clarification! So this is basically then the natural post-step after making the ensemble evaluator production ready on-premise?

**Comment by sondreso** [comment]
Yes 😄

**Comment by jondequinor** [comment]
Me and @sondreso took a look at logging and found that
- Ert usage with the `--disable-…` flag is low
- Errors pertaining to the evaluator are of little concern right now, meaning they aren't many, and they are mostly tracked by existing issues. 

We can conclude that the time is ripe for the ripping.
