### ISSUE TITLE
Monitoring of progress of ERT3

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1325]
We should discuss whether we want monitoring in the cli or a GUI. And in both cases we should inspect whether we can unify monitoring in `ert` and `ert3` for that particular usage (cli vs gui).

**Comment by sondreso** [comment]
Very crude implementation done here: https://github.com/equinor/ert/pull/1511/commits/70cf859f09665b99ac6512ee727ad0c3b825012c

**Comment by jondequinor** [comment]
I think this should naturally be re-opened when we need it.
