### ISSUE TITLE
Have the unix step fetch data from file storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1328]
The unix step will need large files and we should implement and tests strategies for doing this. Ie. the files being persisted in blob storage and the step fetching the data from there.

**Comment by jondequinor** [comment]
A place to start this discussions could be the high level design of the API it would consume? From a `UnixStep` point-of-view, the interface could be something like this:

```python
# on the way in

# for globbed files
path = await incoming_globbed_files_transmitter.dump("to/some/path")

# for a smaller vector of floats
record = await incoming_vector_transmitter.load()

# larger records
record_stream = incoming_grid_transmitter.stream()
while True:
    foo = await record_stream.readuntil()
    …
…
# on the way out
await outgoing_transmitter.transmit()
```

Interface is thus

```python
class RecordTransmitter:
    def stream() -> asyncio.StreamReader:
        pass

    async def dump(location: Path) -> 'asyncio.Future[Path]':
        # the result of this awaitable will be set to the Path of the folder into which this record was dumped
        pass

    async def load() -> 'asyncio.Future[Record]':
        pass
```
where the two latter methods are convenience methods, they are just streams that either goes on disk, or in memory.

Further

```python
class RecordTransmitter:
…
@staticmethod
def from_record(record, name: str) -> RecordTransmitter:
    pass

async def transmit() -> asyncio.Awaitable:
    pass
```

where `transmit` will magically either dump it to disk (the location is of no concern for the unix step) or upload it into the clouds. What happens is determined by the config either passed directly, or produced using the record name.

Issues:

- Transmitters, I think they should concern themselves with MIME, but not what the record type is. For instance, that the record is formatted for transmission in protobuf, should be enough to transmit the record. But the type is perhaps someone else's responsibility.
- Records. They can be many types, but when is this decided?

**Comment by sondreso** [comment]
Additional points from discussion: 

- `dump()` (and possibly also `load`) needs to have format (e.g. csv/json) specified when dumping non-binary / structured data. 
- We discussed passing around the record between steps, but reading this a second time I think it makes more sense to pass around a transmitter for each of the records, in other words making the transmitters the input/output. To solve the issues discussed around in-memory records, the `from_record` could just copy the data into the transmitter. 
- We still might run into issues about keeping track of the exact type of record when passing them around (was it a mapping from int to float or from float to float?), but I think we should be able to hide this in the implementation of the transmitter. In addition this needs to be fully configured for the output of steps, such that we can validate and track the format correctly (be able to do the correct thing :tm: ).
