### ISSUE TITLE
Style checking/linting

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1347]
**Is your feature request related to a problem? Please describe.**
I noticed the ert code base does not use a linter.

**Describe the solution you'd like**
Use a linter that checks pep8 compliance, and our own style preferences.

**Describe alternatives you've considered**
`pylint` or `flake8`

**Additional context**
The linter should probably  only be used on the new modules that are being introduced.

**Comment by markusdregi** [comment]
Related to: https://github.com/equinor/ert/issues/1346

**Comment by markusdregi** [comment]
Note that we already run `flake8` and would like to run `pylint` as well on the `ert3` modules.

**Comment by markusdregi** [comment]
Duplicate of #1346
