### ISSUE TITLE
Refactor ERT's authtoken system

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1355]
Currently we're using `HTTPBasic` authentication strategy in a way that isn't visible from OpenAPI. Use FastAPI's `APIKey*` classes to handle auth instead.

**Comment by markusdregi** [comment]
Is this still relevant @dotfloat? Can you move it to `ert-storage` in that case?

**Comment by dotfloat** [comment]
Closing in favour of https://github.com/equinor/ert-storage/issues/6
