### ISSUE TITLE
Use a postgres instance hosted in Azure as storage backend

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1360]
Have `ert3` run with a storage backed by a postgres instance hosted in Azure.

**Update**
This issue is completed when any version of `ert` can be ran using the Postgres instance hosted in Azure.

**Comment by dotfloat** [comment]
This should not be an `ert3`-only thing, but also apply to `ert` with `--enable-new-storage`.

**Comment by markusdregi** [comment]
This might be easier to test using `ert` depending on the progress of having ert3 use new storage

**Comment by oysteoh** [comment]
This is now solved.
