### ISSUE TITLE
Add inderterminate animation to GUI

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#1366]
And add labels to be more in tune with the old GUI

**Comment by frode-aarstad** [comment]
The work is part of the ert/refactor-out-queue-from-ui brnach

In particular this commit 
https://github.com/equinor/ert/pull/1312/commits/ddd9422bcc0065591e86ef2699f13c061d64ad5d

**Comment by sondreso** [comment]
Will be part of the review of the entire QT refactor branch, closing this for now!
