### ISSUE TITLE
Improved documentation of parallel runs

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1379]
The documentation does not seem to have a very good description of how parallel runs are configured in ERT. The NUM_CPU kw is briefly explained, but that is only a part of the story. In reality ERT, when the DATA_FILE kw is set, parses the DATA file for kws PARALLEL for MPI and SLAVE for RC runs to determine how many CPUs are needed. The NUM_CPU kw is hence optional. I would suggest some prosaic description of how it works and what the options are. I know that it might change with ert3, but think it is worth the effort :)

**Comment by valentin-krasontovitsch** [comment]
i think this issue can well be picked up during our current work on the config.

it also seems to be related to #3979

for more details, one may refer to a [slack discussion on the topic](https://equinor.slack.com/archives/CDPJULWR4/p1664540398481229) [INTERNAL LINK]

in particular, @oyvindeide might have a lot of insight here.

**Comment by valentin-krasontovitsch** [comment]
it seems like this was already covered in 29fb7c5e6e59e71208a3c2196f9cbb150afc64bc and 0f1cb47175b7a610fff25d64a03f9fe0ae92014a!
