### ISSUE TITLE
We need to add metadata to the values retrieved from the api telling if they are calculated ( i.e log ) or original.

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1381]

**Comment by markusdregi** [comment]
Can you please add some information to this one?

**Comment by dotfloat** [comment]
I did a quick grep and it seems like the only place where we care about `LOG10` is here: https://github.com/equinor/ert/blob/3a38adebebafe958297e1054033a22100a597896/ert_gui/tools/plot/plot_api.py#L15

**Comment by oysteoh** [comment]
> Can you please add some information to this one?

Probably lacking some information here yes - so... The point is we need to store / calculate both values, and add this metadata (if it is calculated log or an original value ) to the data from the api. Changed the header accordingly - it is not important if it is stored or not - we just need to indicate for the client if it is a calculated value or not.

**Comment by markusdregi** [comment]
That makes a lot more sense! But what is the rationale for the database being responsible for doing ie. `log` operations instead of leaving such calculations to the consumer?

**Comment by oysteoh** [comment]
We don't necessarily have to store this data, but indicate if it is i.e a `log`one. If i'm not totally wrong ( i still lack knowledge regarding the data and not fully understand everything ) but i think there is keys which already has values with i.e `log10` as @dotfloat  enters above here . And if we are using these - we need to indicate in the data sent towards the client that this is the case. But - you might have some thorough insight to this and can point us in the right direction? 😄 
```
log_keys = [k for k in all_keys if k.startswith("LOG10_")] 
```

**Comment by dotfloat** [comment]
Sorry, the `LOG10_` stuff comes from _libres_, where it goes through some shallow layers of Python code into never-ending layers of C getter functions. Seems that only GEN_KW objects can be set to be _log10_. This information should be obtainable though.

**Comment by markusdregi** [comment]
No thorough insight, but I think we can allow us to have better metadata formats then dumping it in the key in the new storage... We might have to serve it towards ert, but I think we should avoid having it in the core storage implementation 🤔

**Comment by dotfloat** [comment]
I made an issue specifically targetting metadata: #1383

**Comment by markusdregi** [comment]
Do we perhaps have some additional information we can add to this issue @dotfloat and @oysteoh to make it more up to date? Is it still relevant? Should it be moved to `ert-storage`?

**Comment by dotfloat** [comment]
I don't have a good enough understanding of why we even have `LOG10_`. I think @ManInFez or @xjules know more.

**Comment by dotfloat** [comment]
Closing due to not actionable at this time.
