### ISSUE TITLE
Storage: Add metadata column

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1383]
Add a `metadata` column to all tables of note. This _NULLABLE_ column contains JSON data, that is optional and doesn't cause a fatal error if invalid or otherwise contains unexpected data (unless you're trying to extract something specific from it). This structure isn't indexable. That is, you shouldn't have the ability to look for eg. responses where the metadata contains `{"foo": "bar"}`. If this is something that the user desires, we should make it a column.

This metadata column is considered mutable, unlike all other data. (Perhaps we can have an immutable and a mutable column in the future).

This is to allow adding metadata to rows without having to do all of the bureaucracy of creating alembic migrations.

**Comment by dotfloat** [comment]
Also add a `<base>/metadata` endpoint to each relevant resource. Eg, `/ensembles/1/responses/2/metadata`:
* `GET`: Return the JSON data as is, or `{}` if it's `NULL`
* `PUT`: Replace the JSON data with whatever the user submitted
* `PATCH`: Update the JSON data. As if by `metadata.update(input_metadata)`

We can discuss more advanced semantics for eg. appending to an existing list, but I reckon a different solution is advisable in that case.

**Comment by oysteoh** [comment]
Adding a new column for observation, ensemble, record, experiment, update step (?), observation-trasformation

should be of type json ( postgres ), pickletype ( sqlite )
