### ISSUE TITLE
Use storage for record communication between client and compute

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1393]
Record transmitters were introduced in https://github.com/equinor/ert/pull/1469. However, currently the transmitting is based on in-memory data and shared file systems.

We should implement a `StorageTransmitter` that allows for lazily pulling and pushing data from/to storage at need.

**Comment by markusdregi** [comment]
@sondreso & @jondequinor: Feel free to add context if needed 👍🏻

**Comment by sondreso** [comment]
We need a third Record transmitter which implements the interface described [here](
https://github.com/equinor/ert/blob/master/ert3/data/_record.py#L175) and allows us to put data directly into the new ert storage. 

Today we have two types of transmitters already, ([SharedDisk](https://github.com/equinor/ert/blob/master/ert3/data/_record.py#L214) and [InMemory](https://github.com/equinor/ert/blob/master/ert3/data/_record.py#L298)). These are OK, but neither allows us to use cloud storage to transfer data to and from the compute nodes.

**Comment by markusdregi** [comment]
This will be resolved by #1426

**Comment by sondreso** [comment]
Not closed by #1426, but duplicate of https://github.com/equinor/ert/issues/1790
