### ISSUE TITLE
Report `Failure` when the starting an ensemble errors

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1394]
**Is your feature request related to a problem? Please describe.**
Currently, if an error occurs when starting an legacy or prefect ensemble evaluation, the error is logged and a `Failure` event is sent. This is probably not reported as such in the GUI/CLI.

**Describe the solution you'd like**
A report that then ensemble evaluation could not start due some exception, probably printing the exception.

**Comment by oyvindeide** [comment]
I think this is the case now? Will close the issue, but if you have a way of reproducing with latest version feel free to reopen and we will prioritize this issue.
