### ISSUE TITLE
Let user specify desired storage server address

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1402]
We most likely want the user to be able to specify which storage server they want to connect to, depending on the asset. Currently ERT spawns the storage server, which creates the `storage_server.json` with information about where to find that server. In the future we should let the user create a similar file which ERT reads.

The address should default to `localhost:51820` in case the user is a developer or student/non-Equinor person who's trying ERT locally using a local ERT Storage + Postgres instance.

Assets would have to specify the address of their storage instance + some randomly generated secret token.

**Comment by markusdregi** [comment]
For `ert3` in thinking this will be part of the `init`/`workspace` state persisted in `<workspace>/.ert`

**Comment by oysteoh** [comment]
@sondreso would you put this is you backlog of issues? It is related to the configuration of ERT3.

**Comment by markusdregi** [comment]
I don't think we should put all issues touching configuration in the owl backlog, because that basically prevents you from doing anything related to the business logic of ERT. And that is not very autonomous... Feel free to pick this up whenever it is to be prioritised.

**Comment by lars-petter-hauge** [comment]
https://github.com/equinor/ert/issues/1541#issuecomment-1055082316
