### ISSUE TITLE
Sketch  workspace data model

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1404]
Should explain:
 - workspace
 - experiment
 - ensemble
 - record
 - stages and steps
 - forward model / ensemble pipeline
 - algorithm pipeline
 - when do two experiments share an ensemble?

**Comment by markusdregi** [comment]
Some info can be extracted from: https://github.com/equinor/ert/issues/1399

**Comment by markusdregi** [comment]
Should align with https://github.com/equinor/ert/blob/master/docs/rst/manual/architecture/concepts.rst

**Comment by oysteoh** [comment]
@markusdregi can you make this an epic or close it / make issues out of it? This issue is not actionable.

**Comment by markusdregi** [comment]
I agree that it is not actionable as is, unless you have opinions about the matters above. As we have scheduled some work drawing these things soon, I'll just keep the issue for now as a list.
