### ISSUE TITLE
Introduce workspace concept into storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1405]
`ert3` comes with a workspace concept, storage have a similar concept named `experiment`. These two seem to be almost the same and should be aligned.

Definition should be agreed upon up front in https://github.com/equinor/ert/issues/1404

**Comment by dotfloat** [comment]
We haven't had a discussion on this yet. Here are my preliminary thoughts:

The `workspace` seems like an easy way for users to organise their experiments. We could envision that every user have their own workspace where they each do their own experiments. In ertviz, the user could have a default workspace that is active, but then could select a colleague's workspace to look at their data.

# Table
The workspace is a very simple object, only having a name.
```
workspace {
  id: int
  name: str

  experiments: List[Experiment]
  created_by: str           # Azure AD email, Linux username

  time_created: Timestamp   # When this DB entry was created 
  time_updated: Timestamp   # When this DB entry was updated (metadata column is mutable, so it makes sense)
  metadata: Optional[JSON]  # https://github.com/equinor/ert/issues/1383
}
```
Only experiments are tied to the workspace. Maybe in the future we'll want to have some per-workspace settings. Eg the user could have background images and tell the which workspace is which by the breed of cat they've used.

# Endpoints
The endpoints are generic CRUD ones.

**Comment by markusdregi** [comment]
Duplicate of https://github.com/equinor/ert-storage/issues/70
