### ISSUE TITLE
Reduce ert3 testing time

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1413]
A lot of the current ert3 test runtime comes from the large ensemble size of the `deo` experiment (currently `1000`). I suggest we reduce it to a double digit number for faster CI! Perhaps 42 is a good number?

Since some of the tests are still using the `examples` this will probably induce some miner changes in the tests as well...

**Comment by sondreso** [comment]
That test actually has proven very useful, since it stretches the evaluator quite a lot. The large size of the snapshots and number of updates being sent have caught some bugs that would be hard to find otherwise. But maybe we should move this to a evaluator test instead!

**Comment by markusdregi** [comment]
Then I don't mind :) Let us think about whether we should close this issue...

It makes sense to have a "large" integration test. And with https://github.com/equinor/ert/pull/1412 it is starting to move out of the standard unit test suite ran locally anyway.

What I really want to is to be able to run `pytest .`, possibly with a `--unittests`, and get a test suite that runs below 30 seconds. Preferable below 10, but that might be a lot to hope for 🤷

**Comment by sondreso** [comment]
Agreed, think a fast running suite of unittests would be nice to have!

**Comment by markusdregi** [comment]
Should hopefully be resolved by #1345
