### ISSUE TITLE
Use string IDs rather than ints in JSON schema

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1422]
The JSON schema sends IDs as `int`s, because they're `int`s in the database. For the user, it really doesn't matter that they're `int`s. It's not like you can do arithmetic on them.

We should change the types to be `str`s. Instead of:
```json
"ensemble": {
  "id": 123
}
```
it should be:
```json
"ensemble": {
  "id": "123"
}
```

This will allow us to change to eg. UUIDs in a way that's invisibile to the user:
```json
"ensemble": {
  "id": "1234-5678-4321"
}
```

On the server, we would then do SQL queries by `int(ensemble.id)`

Spawned from #1420

**Comment by markusdregi** [comment]
Please move the issue to ert-storage if it is still relevant @dotfloat

**Comment by dotfloat** [comment]
This has already been resolved with https://github.com/equinor/ert-storage/pull/59 :)
