### ISSUE TITLE
ERT gets segmentation fault in the when using rms roff files

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#1423]
**ERT segmentation fault some time after the RMS forward model is completed.**
ERT get segmentation fault. The model is a simplified workflow that has replaced the Eclipse forward model with an average operation. The purpose of the model is to test ERT with localization. No new features from localization development by Joakim is used. The ERT workflow job to setup the localization configuration (by a python script) runs as it should. 

**To Reproduce**
1. The version is the 'bleeding ' komodo version pr 16.02.2021 kl 10.00
2. The config file: Localized under /project/fmu/users/olia/test_project_aps/ert/model/test_aps_drogon_grid_12_1.ert for RMS12.1 and /project/fmu/users/olia/test_project_aps/ert/model/test_aps_drogon_grid_12.ert  for RMS12.0.2
3. The RMS project is located under; /Project/fmu/users/olia/test_project_aps/rms/model/test_aps_drogon_grid.rms12.1 for RMS12.1 and same name but extension .rms12.0.2 for RMS12.0.2
4. Both Single realization and Ensemble experiment fails for both cases so it looks like it is not related to which RMS version was run.
It fails after all forward models are finished.

**Enviromment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo Release: bleeding-py36 
 - 3.6
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by eivindjahren** [comment]
A git bisect reveals that this is due to commit 9853b9f53070f812dbe485ceb2068308f4f80dad . I believe the logic applied is flawed so that it now might misidentify a roff file as a grdecl file if `ecl_kw_grdecl_fseek_next_kw` returns true while `util_string_equal(extension, "grdecl")` returns false.

**Comment by markusdregi** [comment]
@oddvarlia Is this still an issue?

**Comment by oddvarlia** [comment]
Nei den ble fikset.

**Comment by markusdregi** [comment]
Issue has been resolved
