### ISSUE TITLE
Blob record

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1426]
**Is your feature request related to a problem? Please describe.**
Currently in the SPE1 example we have to rely on shared disk and copy the datafile into the runpath.

**Describe the solution you'd like**
 I want a more explicit mechanism for treating this data. In particular I want to be able to treat it the same way as records are currently handled. That is, I want a blob record!

**Comment by sondreso** [comment]
#1469 makes this feasible in the prefect ensemble and introduces the blob record in code. Still need to expose it to the user as a configuration option.

**Comment by sondreso** [comment]
Should get rid of this TODO: https://github.com/equinor/ert/blob/master/ert3_examples/spe1/stages.yml#L40

**Comment by frode-aarstad** [comment]
Am I right to assume we want to be able to write ie:
`$ ert3 record load example_data resources/SPE1CASE2.DATA.jinja2 `
to load any type of data other than JSON like we currently only allow ?

**Comment by markusdregi** [comment]
Yes, something along those lines... Do we want explicit types? As in, something along the lines of:
```
$ ert3 record load example_data resources/SPE1CASE2.DATA.jinja2 --record-type=blob
```

**Comment by frode-aarstad** [comment]
Explicit types sounds like a good idea.

**Comment by frode-aarstad** [comment]
How should the blob record be fetched from storage. Should there be an entry in ensemble.yml, ie:
`
    source: storage.example_data
    record: data
`
Or should blob records be treated differently?

**Comment by markusdregi** [comment]
I think they should be treated as the current records. Meaning that I would expect to be able to load them as indicated in the post above and afterwards do

```yaml
    source: storage.example_data
    record: data
```

as you wrote. I would also expect to be able to do:

```yaml
    source: workspace.example_data
    record: data
```

and that being equivalent to first loading `example_data` and afterwards point to it in storage.

The similar notation for numerical records is `stochastic.example_data` and I think this should change, but that goes beyond this PR. In particular I think we should consider introducing a more standard URI scheme later :)
