### ISSUE TITLE
ERT3: Records of type index-series might contain index-axis related metadata 

### ISSUE THREAD

**Issue by xjules** [equinor/ert#1430]
Motivation:
`Responses` can be of two major types (on a very high level that is): `time-series` or  `index-series`. The `index-series` type describes a more general group of responses, where `indices` can refer either to a location (eg. an `id` of reservoir model compartment, location as an index to 3D voxels, etc.) or to an observation index. Such observations can come about at different time-steps or at different locations.

Such a `response` / `observation` domain context is currently not persisted neither provided in `ert`. It is only required that an observation has its equivalent response value regardless in space or in time. Nevertheless, for the sake of visualization, for instance, the `response` / `observation` domain context would make a perfect sense.

Within the scope of `ert3`, a new concept of Records and how the data are to be stored into the `ert3` database might provide a suitable entry-way, where a user can provide such contextual metadata: https://github.com/equinor/ert/issues/1407 
For example, `index-series` type could contain an index `type` (location, matrix coordinates, obs-index, etc) and the corresponding `index` to  `type` mapping.

**Comment by markusdregi** [comment]
Please add some more information about you actually would like to achieve here @xjules :)

**Comment by markusdregi** [comment]
We currently do support indexed records (integers and strings) in `ert3` via records. Is perhaps what we are after to also support `time-series` @xjules?

**Comment by eivindjahren** [comment]
Ert3 has been removed
