### ISSUE TITLE
Better Exceptions handling via ert api

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1434]
When running via `ert api` and encountering an exception, useful output isn't outputted as it would if you were to run the FastAPI directly. This is due to logging and debug flags and such.

Investigate how we can make a full stack trace appear in the terminal.

**Comment by ManInFez** [comment]
This is more the case when ert storage is run in a separate process spawned by the main thread and thus not having access to stdout/stderr

**Comment by oysteoh** [comment]
This should not be an issue anymore
