### ISSUE TITLE
Test example with large data size 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1444]
Experiment with 100-1000 realisations, with 1000000 parameters/response values all being floats per realisation. 1 GB of blob data per realisation (should also test few large files vs many small files).

The example should also be made such that we can measure performance criterias such as performance (time it takes to transport data), stability and cost.

**Comment by markusdregi** [comment]
Example with blob storage usage is demoed here: https://github.com/equinor/ert/pull/1511

**Comment by markusdregi** [comment]
I suggest we make a similar setup for postgres and see how it runs

**Comment by markusdregi** [comment]
This has been tested
