### ISSUE TITLE
Create version of Record that support using references to data

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1447]
When the Postgres version is ready, we should create a version of Record that allows us to pass references to the data stored in the DB and pull it down on the compute side.

**Comment by markusdregi** [comment]
I was thinking of whether it should perhaps even be the record's responsibility to know how to persist oneself to a stream. Then, for the unix step we could get the record (which might be a  reference) and then ask it to persist itself to a local file presented as a stream. Then the reference can even choose to not keep the data in memory, but only load it, write to file and forget about it again.

The same record capability could later be used to implement record export in the cli; which we probably should implement at some point. Just a thought 😇

**Comment by sondreso** [comment]
I think this is a good idea! But I think the user sometimes will need to know whether they are working with a stream or not 🤔  So maybe we could do something `like record.data(stream=True)` to get a stream?
