### ISSUE TITLE
Resolve ambiguity regarding ensemble/forward-model records

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1451]
Suppose a workflow creates a record named `cat` and there is a forward-model step which outputs a record named `cat`. If there is a step that uses `cat` as input, the ordering is ambiguous.

We can resolve this by disallowing forward-model steps creating records with names that already exist ensemble-wide. If that is a good solution, I'll document and enforce it in ERT Storage.

**Comment by markusdregi** [comment]
Unless this is a real blocker of your data model in storage (which I hope it is not!) I recommend that we postpone this discussion, or at the very least lift it to a general discussion. The reason being that we are currently not ready to deliver this as a feature, neither as in multiple stages per forward model, nor as in workflows. Which prevents us from doing any real learning on this topic.

Instead I suggest that we focus on the two scopes for which records currently can exist, namely in project and experiment scope. And then we push this discussion when we are ready to both discuss and implement this in configuration, storage and workflow manager alike...

**Comment by eivindjahren** [comment]
I am closing this as related to the ert3 config which is no longer being actively developed.
