### ISSUE TITLE
Monitoring widget confused during ES and ES-MDA

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1480]
Description:
The monitoring widget in the new version of ERT ( komodo-testing, 2021.03.rc4) is reporting misleading status in subsequent iterations for ES and ES-MDA.

I have spotted to similar issues:
The reported status for all realization ie frames representing the queue state, are all green from start, even before the jobs are submitted to que, as illustrated by attached image. Behavior is as expected for the first iteration, this only applies for  iter-1 and onwards.

The new total progress bar at the top is confused for ES and ES-MDA runs. For ES I get 100% progress when the second iteration has been created. For ES-MDA with 3 iterations (1-3) the progress is advanced by 20% after each successful iteration, as it it think the total number of iterations is 5.  
 
**To Reproduce**
Run ES / ES-MDA with gui and observe 

**Expected behavior**
Consistent reporting coloring and progress reporting in accordance with actual events.

**Screenshots**
![Monitoring](https://user-images.githubusercontent.com/41294438/110341391-91523e00-802a-11eb-89c4-9582fa18a9af.PNG)

Screen shot captured during ES run exactly when the second iterations had been created, before the jobs were submitted to LSF. I would hence expect total progress to be ca 50% and the status of realizations to be blue or unknown.

**Enviromment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo Release: 2021.03.rc4

**Comment by sondreso** [comment]
Related to #1476
