### ISSUE TITLE
Run an ert3 setup in Azure

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1492]
Make sure ert3 still runs in Azure using the PBS cluster.

**Comment by markusdregi** [comment]
Steps to succeed:

Prep work:
```
<login to Azure cluster>
mkdir ert-azure-test
cd ert-azure-test
python3 -m venv env
source env/bin/activate
```

Installation
```
pip install --upgrade pip
pip install ert
```

Prepare setup:
```
git clone https://github.com/equinor/ert.git
cd ert/examples/polynomial
sed -i 's/local/pbs/g' experiments/evaluation/ensemble.yml
```

```
ert3 init
ert3 run evaluation
ert3 export evaluation
```

Note: It took quite some time for the compute instances to spawn up when I was running this. So do expect to wait a little the first time you run this...

**Comment by sondreso** [comment]
I have successfully executed the above steps
