### ISSUE TITLE
Reset ert-storage between tests

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1497]
Currently ert-storage is started as a service when testing ert3 and kept until all tests are finished. This could in the future result in unforseen sideeffects, as information is potentially shared across tests. A way of resetting ert-storage in between tests should be used.

**Comment by markusdregi** [comment]
Is this not fixed already @ManInFez? :)

**Comment by markusdregi** [comment]
This is fixed by the `ert_storage` fixture: https://github.com/equinor/ert/blob/5d8e8bfa19b82452e333aad7f388239ba5bbb969/tests/ert3/conftest.py#L260
