### ISSUE TITLE
Add schemathesis for the storage API

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1506]

**Comment by oysteoh** [comment]
Blocked by #1389

**Comment by markusdregi** [comment]
Is this still relevant @oysteoh ?

**Comment by oysteoh** [comment]
@dotfloat is this something we still want to do? Looking into the related #1389 and that as well seems to have no decision yet. Should we close and open when the need is there?

**Comment by oysteoh** [comment]
We have decided to use an example-database currently, and will close this issue as it is duplicating the feature of testing.
