### ISSUE TITLE
Improve the user experience with respect to storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1507]
**Context**
In https://github.com/equinor/ert/pull/1490 `ert3` started utilising `ert-storage` for persisting data. Currently, one has to do the following post-installation:

```
export ALL_THEM_ERT_STORAGE_ENVIRONMENT_VARIABLES
ert-storage &
ert3 init

ert3 some_command
```

Personally I don't think this is a great user experience.

**Goal**
I'd like to see the relevant configuration for storage persisted entirely within the workspace data as described in https://github.com/equinor/ert/issues/1402. But, in addition I suggest that we strive to avoid having the user export environment variables and launching ert-storage directly. Such that we get back to `ert3 init` and `ert3 some_command` being sufficient. Also, currently a restart of your machine (and more) will result in the user having to restart `ert-storage`. I'd like to avoid that...

**Approach**
A possible approach to avoid the environment variables is to let the `init` command accept optional arguments that configure the storage connection. It could also possibly launch `ert-storage` if it is a local option.

For the various situations where the database is running locally, we could consider either trying to relaunch storage automatically if it appears to be down. Or we could offer an `ert3 service ...` cli that helps the user relaunch needed services (can be reused later for an experiment server etc) and then hint towards trying this if we fail to connect to storage.

**Comment by ManInFez** [comment]
In #1705, a first example is being used for checking that ert-storage service is available.  This could maybe be moved to the `init` argument, but I think an `service` argument can be a good idea for launching local services. e.g. `ert3 service storage start`

**Comment by jondequinor** [comment]
Another way to do it, is to put the complexity of orchestration into its own repo. This is a very conventional way of doing it when multiple _services_ (ERT, Storage, Evaluator, etc) are involved.

The orchestration thing can
- capture things that ought to be in the provisioning/deployment domain,
- increase parity between real world deploys and local testing,
- clearly define a _main_ process which contains the life cycles of the other services,
- allow the services to open random ports, having the orchestration thing open ports/create proxies…

aaaaaaaaaaand we're implementing docker here. What shall we call it?

**Comment by markusdregi** [comment]
📦 `ertbox` 📦

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
