### ISSUE TITLE
Jenkins ert-storage test running

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1508]
Komodo doesn't have `ert-storage`, which means that we can't run ERT3 tests that require `ert-storage` to be present on Jenkins.

The `ert-storage` PR starts the storage automatically as a fixture, so it should be enough to just have it be installed.

**Comment by oysteoh** [comment]
This should wait until the decision of having one mono-repo or multiple repositories have been made

**Comment by markusdregi** [comment]
Are we not ready for enabling these tests on Jenkins now @ManInFez?

**Comment by ManInFez** [comment]
Soon @markusdregi :)
