### ISSUE TITLE
Install ert-storage from PyPi

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1509]
`ert-storage 0.1.1` is available on pypi, this can now be added to the setup.py, and the install step in the CI can be removed or changed to just `pip install ert-storage` if it should not be included in `install_requires`.

**Comment by markusdregi** [comment]
Nice!

I would welcome a patch installation from PyPI any day (and then close this issue) :)

Then we can do the discussion on how to deal with `ert-storage` and whether it should be a direct dependency of `ert` in a separate issue...
