### ISSUE TITLE
Incomplete GUI after completed ES-MDA

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1512]
**Describe the bug**
Some realization jobs are pending, even though the experiment is marked as done.

**To Reproduce**
Run ES-MDA

**Expected behavior**
Status should reflect reality

**Screenshots**
![image](https://user-images.githubusercontent.com/53553193/111434524-ed3e5600-86ff-11eb-9a12-028ac34552f7.png)

**Comment by frode-aarstad** [comment]
Putting back in todo awaiting more info to be able to reproduce

**Comment by jondequinor** [comment]
From me? Or have you spoken directly to the user?

**Comment by frode-aarstad** [comment]
Directly to the user

**Comment by frode-aarstad** [comment]
Communicated with @oddvarlia. He has not been able to reproduce the problem lately but will contact us if it shows up in the future
