### ISSUE TITLE
PIP Install Python 3.7

### ISSUE THREAD

**Issue by OPMUSER** [equinor/ert#1516]
**Describe the bug**
Cannot install ert 2.20.1 or any other version under Python 3.7 ( I need to use this version of Python for other applications).

**To Reproduce**
1. `pip install ert==2.20.1`

**Expected behavior**
Ert to be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/17958927/111861241-b5494400-8987-11eb-9663-70caae8d4dbd.png)

```
ERROR: Could not find a version that satisfies the requirement equinor-libres>=8.0.0b0 (from ert)
ERROR: No matching distribution found for equinor-libres>=8.0.0b0
```

C:\windows\system32>
**Enviromment**
 - OS: Windows 7
 - ERT/Komodo Release: 2.20.1
 - Python version 3.7
 - Remote/HPC execution involved: no

**Additional context**
None

**Comment by sondreso** [comment]
Hello, and thank you for your interest in ert! 

ert (or more accurately the dependencies [libres](https://github.com/equinor/libres) and [ecl](https://github.com/equinor/ecl)) are unfortunately not available for Windows. If you want to use ert on windows I recommend using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), however, I believe this is not available for windows 7.

**Comment by dotfloat** [comment]
ERT and its dependency libres are written for, and thus depend heavily on POSIX. You may have some luck with [Cygwin](https://www.cygwin.com/), the open source POSIX implementation for Windows, but it's entirely uncharted territory for us, and thus is unsupported.

Update to Windows 10 and use WSL, or install Linux on either a virtual machine or actual hardware.

Closing as WONTFIX.
