### ISSUE TITLE
Unclear outcome of jobs killed by MAX_RUNTIME

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1525]
**Describe the bug**
When ERT kills jobs due to MAX_RUNTIME, it's hard or impossible for the user to figure out why (especially if he/she forgets that the MAX_RUNTIME setting was set).

**To Reproduce**
1. Set MAX_RUNTIME to less than you expect some job will run
2. Run ERT (preferably executing via lsf)

**Expected behavior**
Users should be given productive feedback

**Comment by berland** [comment]
See also https://github.com/equinor/libres/issues/1108

**Comment by sondreso** [comment]
Somewhere in the queue we have information about if the job was killed. We could make a new QueueStatus indicating that the job was killed (or actually utilise the one that is currently there correct (might involve changing the current queue driver)). This should propagate to the snapshot and be visible in the GUI/CLI.
