### ISSUE TITLE
UserWarning when running ert3

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1532]
**Describe the bug**
When running the polynomial example (and most likely other setups), the following warning is presented:

> UserWarning: Tasks were created but not added to the flow: {<Task: Task>}. This can occur when `Task` classes, including `Parameters`, are instantiated inside a `with flow:` block but not added to the flow either explicitly or as the input to another task. For more information, see https://docs.prefect.io/core/advanced_tutorials/task-guide.html#adding-tasks-to-flows.
  next(self.gen)

It appears in CI and was reproduced locally. The setup seems to run fine, but the warning should not appear 🤔 

**To Reproduce**
1. Check out master
2. Run `pip install .[ert-storage]`
3. `cd examples/polynomial`
4. `ert-storage&`
5. `ert3 init`
6. `ert3 run evaluation`

**Expected behavior**
No `UserWarning` in terminal

**Local environment**
 - OS: MacOS
 - ERT/Komodo Release: commit: `e1a70985713d1e109c8b484a209e7d20b75169ca` from `master`
 - Python version: 3.7
 - Remote/HPC execution involved: no

**Additional context**
There is also another stack trace appearing currently (`websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason`), but that is documented in a separate issue: https://github.com/equinor/ert/issues/1307

**Comment by frode-aarstad** [comment]
Closed the PR. 

This issue will be addressed when we refactor the Prefect code.

**Comment by DanSava** [comment]
Asked a question on the prefect github page (https://github.com/PrefectHQ/prefect/discussions/4365), it seems it was a small bug. 

A PR was opened that will fix the warning, and it should not show up in future versions of Prefect.
