### ISSUE TITLE
ERT legacy plotter unable to plot GEN_OBS for which some data are missing

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1533]
**Describe the bug**
ert from komodo-2021.3 does not plot responses for GEN_DATA/GEN_OBS for which there are missing data points; only observed values are displayed. Previous version of ert is able to plot. 

**To Reproduce**
Run the HM tutorial, manually tamper with the RFT_ files for one or more realization so that they get a value = -1.0 and _active=0. Plot the vector.

**Expected behavior**
Would expect ERT to plot values for the realizations that do have active values

**Screenshots**

**Enviromment**
 - OS: [RHEL7
 - ERT/Komodo Release: 2021.03 (stable)
 - Python version 3.6
 - Remote/HPC execution involved: no

**Additional context**
Issue originally posted by Alok Saraf working at Oseberg. And I guess we for debugging purposes could access his files.

**Comment by markusdregi** [comment]
I'll see if I can reproduce this locally and narrow down the commit...

**Comment by sondreso** [comment]
Had a quick look through the commits yesterday, and around this(https://github.com/equinor/ert/commit/820908639d30b1b4c58e8543c668aadc2cc709f7) commit there are changes to the plot api and data loading which might influence this. Just if you wanted a place to start the search 🙂

**Comment by eivindsm** [comment]
If we start poking in this part of the code, I would like to add another issue. In the case where you attach more than one observation to the same GEN_DATA object, the plotter only display the first observation, ignoring the rest. This one is not new, and it has probably always been so.

**Comment by DanSava** [comment]
This does not seem to be a very new issue with ert or libres. I was able to reproduce it using ert 2.16.1 from Dec 10 2020 and libres libres 8.0.0 Jan 10 2021

**Comment by markusdregi** [comment]
Hmm, interesting 🤔 How about if you move even further back?

**Comment by DanSava** [comment]
Found this little piece of joy in libres 
``` c++
/**
   When the forward model is creating results for GEN_DATA instances,
   it can optionally signal that not all elements in the gen_data
   should be active (i.e. the forward model failed in some way); that
   is handled through this function. When all ensemble members have
   called this function the mask config->active_mask should be true
   ONLY for the elements which are true for all members.

   This MUST be called after gen_data_config_assert_size().
*/
void gen_data_config_update_active(gen_data_config_type * config,
                                   const forward_load_context_type * load_context,
                                   const bool_vector_type * data_mask) {
  pthread_mutex_lock(&config->update_lock);
  int report_step = forward_load_context_get_load_step(load_context);
  if (int_vector_iget(config->data_size_vector, report_step) > 0)
    update_config_to_datamask(config, load_context, data_mask, report_step);
  config->active_report_step = report_step;
  pthread_mutex_unlock(&config->update_lock);
}
```

which as far as I understand from the comment it sets all the active mask 0 for all realizations if it is 0 in even one of the iterations of a realization.

And this beautiful thing is from 2010 a bit refactored in 2018

**Comment by DanSava** [comment]
So as far I can tell if you tamper with the `_active` files for any iteration it will be equivalent to tampering with the `_active` file for that iteration in all realizations.

**Comment by markusdregi** [comment]
Makes sense from the perspective of analysis! I think this concludes that this is not a regression as first believed at least...

Do we store the `active_mask` for each realisation so that we could possibly look into plotting not active data points as well?

**Comment by joakim-hove** [comment]
> [...] it sets all the active mask 0 for all realizations if it is 0 in even one of the iterations of a realization.

The `active_mask` is owned by the shared `config` object - i.e. there is *only one* active mask in this context.

**Comment by DanSava** [comment]
From the perspective or ert there is only one `active_mask` for all realizations I am not sure if there is a way to retrieve from libres the `active_mask` for each of the realizations

**Comment by markusdregi** [comment]
Thanks for the prompt feedback @joakim-hove and @DanSava! Then this sounds like a won't fix...

If you would like us to look into plotting non-active data points in general, we can do that @eivindsm. But then it will display data from the entire ensemble and I think we should open a new issue in that case...

**Comment by eivindsm** [comment]
Agree with that @markusdregi. I guess this should be appended to the feature list for the new plotter, where we have started to distinguish between active and inactive summary observations. This is sort of the same thing.
