### ISSUE TITLE
Move records, config, config->ensemble mapping out of ert3

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1545]
**Describe the bug**
A smell, rather. ert3 defines and uses a `Record`. ert3 uses a `PrefectEnsemble`. `PrefectEnsemble` (indirectly) depends on `Record`. 🚴 

As for configuration, ert3 hugs the configuration, but this isn't well placed, because it should be usable outside ert3 as well. For instance, there's a ert3-like configuration parser here https://github.com/equinor/ert/blob/1dd180fdb62826c312e1dce40391f75a1468ab8b/tests/ensemble_evaluator/test_prefect_ensemble.py#L32-L46 which is unfortunate, as it could be beneficial for other parts of ert to be able to use this configuration.

Same goes for mapping between configuration and ensemble. This mapping should also not live inside ert3, but rather be moved somewhere explicit, outside ert3.

**Comment by markusdregi** [comment]
Would be neat to land this one first so that we have a good home to move them to https://github.com/equinor/ert/issues/1520

**Comment by jondequinor** [comment]
@markusdregi did you have a plan for this? Or should it be an exercise of the implementer?

**Comment by markusdregi** [comment]
No grand plan. I was just hoping that we could perhaps rig ourselves with an `ert`-package and move it into there instead of `ert_shared`?

**Comment by sregales-TNO** [comment]
issue #1787 is similar or the same as this issue and could be merged (one removed for the other)

**Comment by markusdregi** [comment]
I'm closing this one as #1787 lives within a larger plan. It should achieve what this issue is seeking...
