### ISSUE TITLE
ert3 should use numerical ert-storage endpoint

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1550]
**Describe the bug**
ert3 storage always uses the `file` endpoint, it should use a numerical one _if_ possible

**Comment by markusdregi** [comment]
Suspect is here: https://github.com/equinor/ert/blob/5d8e8bfa19b82452e333aad7f388239ba5bbb969/ert3/storage/_storage.py#L86

We should as Jonas states store all numerical records as numerical records.
