### ISSUE TITLE
Create test for function step that executes command in an other python environment

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1556]
Given a module and function "foo:bar" we need a test that asserts that a `FunctionStep` and the "bar" function can be executed in a python environment without the "foo" module.

This way we can develop and refactor the `FunctionStep` without the fear of breaking this hard-to-test scenario.

**Comment by markusdregi** [comment]
Is this currently not working since you labelled it as a bug?

**Comment by jondequinor** [comment]
It's just not optimally implemented. Payback is better.
