### ISSUE TITLE
Set iteration number from cli

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1575]
Currently, the iteration number (`ITER`) of a run is possible to set in the GUI before launching. However, the same functionality is not available from the cli. To reduce the redundancy between cli and GUI and to resolve the motivation of https://github.com/equinor/ert/issues/217 without forcing users to use the GUI I suggest that we implement the optional flag `--iter` which can be set to a positive integer similarly to the functionality in the GUI.

**Comment by verveerpj** [comment]
Is this with the Iterate Ensemble Smoother simulation mode? Specifically "Number of iterations"? The other simulation modes do not seem to miss cli options to set iteration-related parameters.

**Comment by markusdregi** [comment]
No, it is to set the iteration number within a specific iteration. For instance, you can run an evaluation using the gui (single iteration) and specify that this is iteration number `x`. Then, the magic string `<ITER>` will be templated by `x` in your forward model.

**Comment by verveerpj** [comment]
`ert ensemble_experiment poly.ert --iter-num=1` does this already, or is that not what is meant?

**Comment by markusdregi** [comment]
At closer inspection this issue appears to have been solved somewhere between me thinking that we should do this, me creating this issue and you now making these comments ;) Closing it...
