### ISSUE TITLE
Ert error in the FlowNet pipeline on server

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/ert#1579]
**Describe the bug**
I am running Ert in the equinor/FlowNet pipeline. The execution crashed when Ert is invoked to start the history matching step.
`The ERT workflow failed. Check the ERT log for more details."
subprocess.SubprocessError: The ERT workflow failed. Check the ERT log for more details.`
FlowNet and Ert are run on a server, reserving a node and running them 'locally'

**To Reproduce**
In order to decouple Flownet and Ert, Ert can be run starting from the configuration files generated by FlowNet
`ert es_mda ahm_config.ert`
The ahm_config.ert file is attached, with 'ert_error.out' that is the Ert run with the stdout error, and the 'site-config' file.
[ert_logfiles.tar.gz](https://github.com/equinor/ert/files/6366425/ert_logfiles.tar.gz)

**Expected behavior**
History matching es_mda 

**Enviromment**
 - OS: CentOS Linux 7
 - ERT/Komodo Release: 2.21.1
 - Python version 3.6.9
 - Remote/HPC execution involved: yes, a cluster node is reserved and execution is run LOCAL

**Comment by markusdregi** [comment]
Hi @Riccardopeli and thanks for reaching out!

There seems to be some issues with the `site-configuration` and the various jobs you try to install. Could you check that the paths that you have specified actually are present on the machine that you are trying to run ERT from?

**Comment by Riccardopeli** [comment]
I checked all the paths and they are present. I am worried that executes/writes/copies/reads files without permissions.
For instance, when you  say ` jobs you try to install`, this means that ert installs anything? 
It is been a while that I am facing this error, without understanding what is causing it

**Comment by markusdregi** [comment]
After inspecting your setup again I think I see what the problem is. Your path contains `--`, which is interpreted in the configuration file as the start of a comment by ERT. Which implies that the rest of the path is ignored... So that is the concrete, technical issue here.

However, it seems like the jobs that are installed are provided by default from `libres`. Are you sure you even need those lines in your site-configuration?

**Comment by Riccardopeli** [comment]
The issue was the exactly the presence of `--` in the paths. 

Thank you for you time!

**Comment by markusdregi** [comment]
Happy to help @Riccardopeli!
