### ISSUE TITLE
Use ert-storage pydantic models in ert.shared.storage.extraction

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1595]
The data-types in data extraction is very convoluted use of basic python data structures. We create bare dict objects and transmitting them as json. We could use the pydantic models from ert-storage to clearly express in the code which types being transmitted.

It should still be possible to run ert without ert-storage, so importing these models has to be done in a sensible manner.

**Comment by oyvindeide** [comment]
This is mostly not the case anymore, the only thing that exists is the `PRIOR_NAME_MAP`, which is custom, will close this issue.
