### ISSUE TITLE
Refactor ERT3 config evaluator module

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#1599]
_evaluator currently has code smells such as:
- hardcoded snippets.
- if clause that will always be True
- large functions
- redundant function arguments
These problems make it harder to maintain, understand and grow the codebase

These code smells can be easily be reduced/removed by implementing the DRY  methodology together with simple concise functions

This is an example of a function that can be broken down into smaller parts
[_evaluator example](https://github.com/equinor/ert/blob/master/ert3/evaluator/_evaluator.py#L105)
![image](https://user-images.githubusercontent.com/82570369/116545311-87451100-a8f0-11eb-92f8-64a702969af5.png)

**Comment by jondequinor** [comment]
The `ee_config` should be removed altogether see #1545

**Comment by sondreso** [comment]
While I don't think this issue is completely fixed, a lot has changed in the code since it was made, and it should be reopened as multiple smaller more specific issues. Closing this for now
