### ISSUE TITLE
Cancelling evaluator is slow

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1607]
**Describe the bug**
While a poly smoother case is evaluating, cancelling it takes a long time

**Expected behavior**
Cancelling should be immediate.

**Comment by markusdregi** [comment]
On local queue or lsf? And using the prefect ensemble or the legacy evaluator?

**Comment by jondequinor** [comment]
Probably all queue types for legacy, but so far just tested with local.

**Comment by markusdregi** [comment]
Thanks 👍🏻 I think for the `lsf`-cluster we are also bounded by how fast the lsf-server is capable to process these requests... Would be interesting to do a comparison with how fast the prefect ensemble manages to cancel 🤔

**Comment by jondequinor** [comment]
I think this was actually a deadlock, so "slow" was extremely generous. 😁
