### ISSUE TITLE
Build plain ERT documentation

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1610]
We should build a plain version of the ERT documentation and host it on Read The Docs or a similar service.

**Comment by sregales-TNO** [comment]
What is "plain" in this context?
No styling? less complex/high-level documentation?

**Comment by sondreso** [comment]
There are internal configuration and jobs that are included in the documentation built for internal use here: https://fmu-docs.equinor.com/docs/ert/index.html. So plain refers to building without this 😄

**Comment by markusdregi** [comment]
Yes, what Sondre said. Basically the documentation that is built in CI :)

**Comment by verveerpj** [comment]
The necessary changes to ERT have now merged in the main branch. To deploy the documentation to ReadTheDocs, the following needs to happen:
- An account has to be made on ReadTheDocs.
-  A decision has to be made which versions are published (release and/or latest?)
- The account may be coupled to a GitHub account to import ERT and set it up conveniently, or ERT may be imported manually. The latter may better as we don't need to use a GitHub account, but will require a bit more manual setup, such as automatic updates on pull requests.

**Comment by markusdregi** [comment]
Done! The documentation can be found here: https://ert.readthedocs.io/en/latest/
