### ISSUE TITLE
Upgrade to websockets 9.0

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1615]
Websockets 9.0 have quite a few changes that we need to incorporate: https://websockets.readthedocs.io/en/stable/changelog.html

It also has Python 3.9 support, which means that ert can also support python 3.9 when both ert and libres support websockets 9.0.

**Comment by sondreso** [comment]
Not this should be done in libres as well!

**Comment by jondequinor** [comment]
We'll need https://github.com/equinor/komodo-releases/pull/1303 as well in order to have CI pass fully.
