### ISSUE TITLE
Propagate scope of data into ert-storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1631]
Currently, there exists records in two different scopes in `ert3`. The experiment/ensemble (which is merged at the time) scope and the workspace scope. The first is dealt with by attaching records to the corresponding experiment. However, the later is done by keeping an internal experiment named `__ensemble_records__` where the records are put. It would probably be better if we pass these records to `ert-storage` as workspace records, as otherwise other consumers also will have to know that `__ensemble_records__` is not a real experiment.

For implementation, see: https://github.com/equinor/ert/blob/e3ac8b81ecd58b95a3579d619f7d65750c331029/ert3/storage/_storage.py#L15

**Comment by ManInFez** [comment]
Are we sure that we should have free roaming records with a workspace, or should it be within experiments. Right now the records is required to be attached to an ensemble. I think records should only be able to live within an experiments or ensembles but not within the outer encapsulating workspace

**Comment by markusdregi** [comment]
The records attached to the workspace was supported to be able to share records between experiments. We can of course support that in a different fashion, but our users should be able to work with records that are being used by multiple experiments in a natural fashion.

**Comment by oyvindeide** [comment]
Will close this as related to ert3, it is still referenced in https://github.com/equinor/ert/issues/2707
