### ISSUE TITLE
Discussion around merging libres and ert

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1633]

**Comment by markusdregi** [comment]
**Criteria 1**
We should continue to build the `res` module for backwards compatibility.

**Comment by markusdregi** [comment]
**Question**
Can we preserve the GitHub history in a sensible manner?

**Comment by markusdregi** [comment]
**Question**
How do we do the folder structure of the repo? Should libres also be dealt with in the same build system as ert? Or should we let `libres` live entirely within its own folder with its own `setup.py` etc?

**Comment by frode-aarstad** [comment]
Proposed approach: Try the methods proposed by Markus in the post above.

**Comment by markusdregi** [comment]
To preserve the libres history I think the first steps in an upstream branch should be:

- move all of libres into a `root/libres/` folder (this avoids collisions - make sure to drag along their git history!),
- move the GitHub Actions of libres into `root/.github` and make them all run,
- make the GitHub Actions all run based on the libres code in the repository, not installing from libres

After this, we have a livable solution where libres is more or less detached from the ert package. A new branch can be created from this branch where we can make an attempt at pulling all the content of `root/libres` into `root`. This would induce a single setup.py file etc.

**Comment by jondequinor** [comment]
I'm not sure why `root`, so I used the conventional `src` instead. Achieves the same if I am not mistaken?

**Comment by markusdregi** [comment]
`root` was just used to indicate the root folder of the repository...

**Comment by jondequinor** [comment]
> How do we do the folder structure of the repo? Should libres also be dealt with in the same build system as ert? Or should we let libres live entirely within its own folder with its own setup.py etc?

Keeping the equinor_libres package around isn't listed as a criterion, but both semeio and everest dep on libres. Semeio is trivial to migrate, but everest would depend on dead code unless it wants to depend on ert. There are no public (github) dependents https://github.com/equinor/libres/network/dependents.

We could keep libres around for a few years and freeze development—making exceptions only for minor everest-related extensions/bug fixes. That's neither insane nor impractical.

Me and @sondreso merged the setup-files of ERT and libres. There are no technical issues, only social ones.

**Comment by markusdregi** [comment]
I think we should for quite some time keep libres around as read-only. But before that we will have to migrate the issues :)

All dependencies of libres should move and depend on ERT instead, including Everest 👍🏻

Care to elaborate on the social issues? Any new ones?

**Comment by jondequinor** [comment]
> Care to elaborate on the social issues? Any new ones?

I have little to no insight into the interaction between libres and the most prominent of those dependents, so I was speculating. But if migrating to ERT is OK, it should be fine.

**Comment by frode-aarstad** [comment]
Closing as implementation has begun
