### ISSUE TITLE
Columns in ERT gui detailed view are not re-sizable

### ISSUE THREAD

**Issue by kvashchuka** [equinor/ert#1638]
Currently it is not possible to change the width of the columns in the realisation's detailed view

**Comment by jondequinor** [comment]
I've looked at this. One way to do this would be to
- do `self._job_view.horizontalHeader().setSectionResizeMode(QHeaderView.Interactive)`
- calculate good `sizeHint` for each column in the header.

Another way to do it would be combine interactive resize with `self._job_view.horizontalHeader().resizeSections(QHeaderView.ResizeToContents)` but that's costly for large views and should not happen more than once.
