### ISSUE TITLE
Failing semeio unit tests

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#1666]
The semeio interation unit tests are flaky on jenkins

`
=========================== short test summary info ============================
FAILED tests/jobs/stea/test_integration.py::test_stea_fm_single_real[ecl_case0-random_eclbase-]
FAILED tests/jobs/stea/test_integration.py::test_stea_fm_single_real[a_random_ecl_case-ecl_base1-,<ECL_CASE>=<ECLBASE>]
`

console log from jenkins:
[consoleText.txt](https://github.com/equinor/ert/files/6458329/consoleText.txt)

**Comment by jondequinor** [comment]
@frode-aarstad shouldn't this be in the semeio issue list? Or was it deliberately put here?

**Comment by sondreso** [comment]
I think we will close this if there are no more details, not very actionable at the moment.

**Comment by frode-aarstad** [comment]
I will close it for now
