### ISSUE TITLE
Integrate pydantic architecture to Ensemble (& PrefectEnsemble)

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#1694]
**Problem**
The evaluators `ert_shared/ensemble_evaluator/* and ert3/evaluator/*` were created in tandem, by different parties, with different strategies. and now, as a result, we have the [_build_ee_config ](https://github.com/equinor/ert/blob/master/ert3/evaluator/_evaluator.py#L108)function that builds an ensemble evaluator configuration dictionary from the ensemble and stages configurations ([_stages_config](https://github.com/equinor/ert/blob/master/ert3/config/_stages_config.py) and [_ensemble_config](https://github.com/equinor/ert/blob/master/ert3/config/_ensemble_config.py)).  This "middle man" function nor [PrefectEnsemble](https://github.com/equinor/ert/blob/8200a0da3b47606aad765107f4163d254340e285/ert3/evaluator/_evaluator.py#L281) (wich the output of  ee_config is given as arguments ) does not validate the values of the ensemble evaluator configuration. And even though PrefectEnsemble encapsulates its attributes, we cannot ensure the credibility of the input parameters, since it's a non-validated dictionary that can be mutated down the line prior to [PerfectEnsemble](https://github.com/equinor/ert/blob/master/ert_shared/ensemble_evaluator/prefect_ensemble.py#L101). This situation is redundant and non-optimal.

**Solution**
- Validation of the instance object fields should be introduced in the keychain and deligated to the object model itself. Pedantic is here your friend. 
- Instance object should be immutable, again pydantic is your friend
- middle man function `ee_config' should be removed.

**Code fundation**
[scratcher.zip](https://github.com/equinor/ert/files/6520707/scratcher.zip)

**Comment by sregales-TNO** [comment]
I think this should be split even further into Pydantic model implementation and Ensemble Evalutator API

**Comment by sregales-TNO** [comment]
Should this issue be converted to an epic?

and have issues such as:
- Introducing immutable pydantic version of PrefectEnsemble and Ensemble
- Create an API for pydantic models
- Integrate API into the Ensemble evaluation sequence
- removing "middle man function"
- purge non-pydantic models from ensemble_evaluator module

**Comment by markusdregi** [comment]
I fully agree that the situation should be improved. However, by going down the pydantic road we are betting even harder on a single shot configuration approach where everything is passed to the constructor at the same time. However, there has earlier been presented good arguments for why a mini-DSL would be a good alternative. Perhaps we should reiterate that discussion before launching?

Also, I'm not entirely sure what alternatives we have to the "middle man function" 🤔 I think it would be good to discuss this in terms of responsibilities. And then I'm thinking that:
- user configuration (or the derived pydantic models) should never be passed to the evaluator as user configuration is an ert3 client responsibility and should not leak beyond that,
- flagging invalid evaluator configuration should be the responsibility of the evaluator,
- as user configuration is the original description of the actions to be carried out, but is not to be passed to the evaluator, ert3 will have to translate parts of its configuration into a corresponding evaluator,
- most of ert3 does not need to now how one translates an ert3 configuration into a corresponding evaluator, this responsibility should be isolated, while the remaining parts of the implementation operates on higher level of abstraction both with respect to the configuration itself and how the evaluator is constructed.

**Comment by sregales-TNO** [comment]
What is mini-DSL?
I agree that user configuration should not bleed further than ert3 module.
I propose that we create a PrefectEnsemble API reference ert_shared.ensemble_evaluator API within ert3.evaluator instead instantiate the class directly.
This API allows us to have a loose coupling between ert3 and ert_shared, where ert3 handles user configurations, and ert_shared is responsible for creating and evaluating the ensemble.

As for Pydantic, I'm still convinced that it would be best. if we continue using the builder pattern used in ert_shared.ensemble_evaluator.entity module, but separating the builder from the model for better readability. the Builder pattern should resolve the single-shot configuration (please correct me if I'm wrong)

(agreeing to the last bullet point)
I'm more inclined to do the translation/interpretation of the user configuration within the ert_shared.ensemble_evaluator API. ert3 should not have to know how (Prefect)Ensemble looks like or anything within ert_shared.ensemble_evaluator module for that matter. Just the exposed API functions.

**Comment by markusdregi** [comment]
mini-DSL: A small, domain specific language. A well-crafted builder pattern in this case...

**Comment by markusdregi** [comment]
> I'm more inclined to do the translation/interpretation of the user configuration within the ert_shared.ensemble_evaluator API.

Is that not a contradiction to the `ert` configuration not leaking into the evaluator? I think it is better for an isolated part of `ert` to have knowledge about the evaluator, then it is for an isolated part of the evaluator to have any knowledge what so ever about ert...
