### ISSUE TITLE
Stop sending messages via websocket from the evaluator to the ensemble

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#1716]
Explore the possibilities of communicating directly between the evaluator and the ensemble instead of over websockets.

**Comment by markusdregi** [comment]
Could you provide some more information? Do you have any plans for how the messages are to be sent instead?

**Comment by frode-aarstad** [comment]
Updated

**Comment by markusdregi** [comment]
As in we are considering to explicitly assume they are running in the same process with shared memory? I have no problem with that, I'm just wondering...

**Comment by frode-aarstad** [comment]
Yes. We were discussing why they were sent over websockets but could not come up with a good reason why. So inorder to reduce the complexity and simplify of the code (as exemplified by the user_cancel event flow) we might consider doing this.

But perhaps the shared memory assumption is wrong. In that case this issue becomes a no-op

**Comment by markusdregi** [comment]
If you briefly describe the responsibility of the ensemble and the evaluator I think that should more or less answer this :)

**Comment by verveerpj** [comment]
The ensemble runs either in a thread (legacy) or in a sub-process (prefect), and communicates some status back to the evaluator. That could be done via a queue: Queue.Queue for threads and multiprocessing.Queue, respectively, which I believe follow the same API.  Presumably the ensemble evaluator would then send out CloudEvents via websockets for monitoring purposes.

The question is, would this offer an advantage? Would it not be better to rely on a single messaging system instead? If we are not happy using websockets, which is done in a rather low-level manner currently, should we maybe consider abstracting the messaging system better?

**Comment by verveerpj** [comment]
After discussion within the squad, we came to the conclusion that it is best to keep the current situation as: the ensemble talks to the evaluator via websockets based dispatcher implement in the evaluator. Otherwise, we would need to build a separate message channel, since communication from the prefect ensemble cannot be in-memory.

Therefore I am closing this issue.

**Comment by DanSava** [comment]
Adding image used during the discussion

![Screenshot from 2021-06-02 14-42-05](https://user-images.githubusercontent.com/4508053/120474459-eba43600-c3b0-11eb-9607-3a3f3e5ac8bd.png)
