### ISSUE TITLE
Remove __init__.py from tests folder

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1734]
According to https://docs.pytest.org/en/6.2.x/goodpractices.html?highlight=good%20practices#tests-outside-application-code we should not have `__init__.py` files in our tests folder. Our current setups means that modules in the root of the repository always will be loaded when running pytest, making it very difficult to run tests against the installed version of the package.

**Comment by markusdregi** [comment]
🚀

**Comment by sregales-TNO** [comment]
If we are switching to standalone test modules (no __init__), then each module name must be unique. Thus there will be some drastic changes.

https://docs.pytest.org/en/6.2.x/pythonpath.html#standalone-test-modules-conftest-py-files

**Comment by sondreso** [comment]
True, still think we should do it! But is it that many files that have the same name right now? :thinking:

**Comment by sondreso** [comment]
This should also be done for the libres tests that will be included from #1714, but one can start with only the ert tests

**Comment by sregales-TNO** [comment]
I will be using the following solution for resolving the conftest import problem.
https://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada/50610630#50610630

**Comment by sregales-TNO** [comment]
I believe that the conftest.py files can stay where they are and implementation of the solution from the previous comment I made can be ignored. But then the none fixture functions present in conftests that are later explicitly imported into other module will need to be extracted out. example [assert_distrobution](https://github.com/equinor/ert/blob/master/tests/ert3/conftest.py#L183) and it's explicit [import] (https://github.com/equinor/ert/blob/master/tests/ert3/engine/integration/test_engine.py#L11)

Reason for this extraction/refactoring:
- once the root __init__ is removed the module can no longer find conftest
  example: test.ert3.conftest -> ert3.conftest: now we no longer reference the ert3 submodule of tests, but the ert3 
  project module and that has no submodule conftest
- Plus implementing functions in conftest that will be explicitly call in other test module is not the optimal use of conftest. conftest is meant for loading plugins, hooks, and fixtures for the module it lives in. and is called and configured by pytest itself (NOT the DEV).
