### ISSUE TITLE
Ert3 storage error handling

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1735]
How should ert3 handle storage errors? 

The ert-storage instance might crash, be out of reach or on wrong side of Jupiter. What should be the default behavior when we get a unexpected response from ert-storage?

**Comment by oysteoh** [comment]
Good question which needs to be addressed! Not put much thoughts into it yet, but at least as a couple of first comments i think we should have a status check in the beginning of the run printing which storage you are connecting to ( like local, on-prem postgres or azure ? ) and if the connection is ok or not. If not ok we should at least not allow any runs before that is fixed i would say. What should we do if the storage is going down during the runs - i really don't know. I guess that depends on the direction we set going forward. Are we to depend on the new storage entirely - like removing internal storage? If we do - would it then make sense to continue the run - or should we have a graceful shutdown after some retry-scheme? With the new storage my impression is that is should be fairly easy to continue from the iteration you left, so hopefully there will not be much time lost after the connection is back again? If we are to continue with the old storage during the runs and only persist data to new storage for reading afterwards - would it make sense to queue up all transactions to be made while the database is down and then fire them off when connection is restored?

**Comment by markusdregi** [comment]
`ert3` at least depends entirely on the new storage API and as of such I don't think we should separate between which implementation of storage is fueling it underneath 🤔

I think we should aim for `ert3.storage` to raise exceptions and leave the decision on what to do to the caller... Most places some robustness is warranted, but given that there is no shared disk area there is only so much one can do without a storage instance that responds. So, if multiple attempts for posting the data fails I don't think there is much one can do besides shutting down the realization and label it as failed even though the data was produced...

**Comment by jondequinor** [comment]
I don't think you can make a general rule. There are different ways it can fail, and probably different types of requests (idempotent vs not e.g.). Might also not be feasible to determine all failure modes up front, might have to experience them.

**Comment by oysteoh** [comment]
> `ert3` at least depends entirely on the new storage API and as of such I don't think we should separate between which implementation of storage is fueling it underneath 🤔

`ert3` i didn't think of - and sure - that one needs storage to be present. I guess a retry scheme for connection errors - and then - as jonas points out - there will be failing requests in different ways when we now introduce the concept of relations between entities and are doing validation on the data.

**Comment by eivindjahren** [comment]
As ert3 is no longer a part of the ert project, this discussion can be repoened if still an issue regarding ert-storage.
