### ISSUE TITLE
Persisting ert-storage connection info in ert3 workspace

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1761]
The connection info (token, url) for ert-storage when running ert3 could potentially be stored in the workspace for ert3. While this makes sense for ert-storage services running "in the cloud" it is not so trivial for locally running ert-storages. A discussion regarding persisting such information is in order.

**Comment by markusdregi** [comment]
Could we not store the connection information that is to be persisted inside some file in `<workspace>/.ert/` independently of where "ert-storage" is running?

**Comment by ManInFez** [comment]
Perhaps, but this information might get stale. If we restart ert-storage, we will get a different security token.

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
