### ISSUE TITLE
Starting, checking and stopping ert3 services

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1765]
In https://github.com/equinor/ert/pull/1705 we introduce an `service` option for the ert3 command line. This can start ert-storage and check whether ert-storage is available. The current implementation should only be a starting point for a better service handling where it is possible to start, connect, stop or otherwise handle any service required by ert3. Discussion commence!

**Comment by eivindjahren** [comment]
Closing as we are no longer going in the direction of ert3. Feel free to reopen if still relevant.
