### ISSUE TITLE
Migrate forward models to EXECUTABLE from PORTABLE_EXE

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1770]
After https://github.com/equinor/ert/issues/1718 `PORTABLE_EXE` is deprecated and we should use `EXECUTABLE` instead. The following jobs needs to be migrated: 

- [ ] symlink
- [ ] make_directory
- [ ] delete_directory
- [ ] make_symlink
- [ ] careful_copy_file
- [ ] delete_file
- [ ] copy_directory
- [ ] copy_file
- [ ] move_file
- [ ] eclipse300
- [ ] eclipse100
- [ ] rms
- [ ] flow
- [ ] template_render
- [ ] FLOW
- [ ] MAKE_SYMLINK
- [ ] RMS
- [ ] ECLIPSE300
- [ ] SYMLINK
- [ ] MOVE_FILE
- [ ] TEMPLATE_RENDER
- [ ] COPY_FILE
- [ ] MAKE_DIRECTORY
- [ ] CAREFUL_COPY_FILE
- [ ] COPY_DIRECTORY
- [ ] DELETE_DIRECTORY
- [ ] DELETE_FILE
- [ ] ECLIPSE100

**Comment by jondequinor** [comment]
I think that, actually, most of these are false-positives. Seems libres configuration deprecates the _item_ not the keyword.
