### ISSUE TITLE
Create ert python module

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1786]
Create a separate module called ert and setup CI to run mypy, pylint, flake8 and black on this module. Create a matching test setup according to best practices for python testing.

**Comment by verveerpj** [comment]
Questions/remarks:
- Is the idea to make the minimal ert package, without moving anything in, which we do incrementally in follow-up issues?
- I am guessing the matching test setup is already being done (at least partially) by Sharlon in a separate issue, so better not within this issue?

**Comment by verveerpj** [comment]
It appears the `ecl` package already installs a package `ert`, that is unfortunate...

**Comment by jondequinor** [comment]
That import has been deprecated for [a year and a half](https://github.com/equinor/ecl/pull/690) now. Nuke it I guess?

**Comment by verveerpj** [comment]
It seems so, there is an issue: https://github.com/equinor/ecl/issues/790

So that issue becomes a blocker for this one.
