### ISSUE TITLE
Separate indexes and data in Records

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1791]
Currently the records store data and indexes together for some of the record types, while others have the indexes stored separately of the data. We should make this consistent, where we always store the data and indexes separate. (This should generalise to n dimensional matrixes as well).

The data field of the record should not be a dict (storing both the index and the data). See https://github.com/equinor/ert/blob/main/ert/data/_record.py#L114

**Comment by markusdregi** [comment]
I think the `pandas.DataFrame` approach of allowing indexing both using integer indecies and using keys would be the best. Then we control the pattern for both integer and key lookup to the extent that we can potentially support fast access for both down the road. Also, that leaves the possibility for implementing interpolation strategies close to the data open.

**Comment by sondreso** [comment]
Suggested using  [xarray](http://xarray.pydata.org/en/stable/getting-started-guide/why-xarray.html) in https://github.com/equinor/ert/issues/1731. Think we can close this and continue the discussion there as the axis/indecies is an important part of the data format.
