### ISSUE TITLE
Isolate unit tests and integration tests

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1795]
Currently our CI runs for 10+ mins. It would be great to isolate a set of tests that we could run in less than 1 minute (marked with pytest.mark).

**Comment by jondequinor** [comment]
I think the default, unmarked, should belong to unit tests. We write more of these. 

There are less integration tests, and we write them less often, so easier to keep marks up to date.

**Comment by oyvindeide** [comment]
We have split this into different pipelines now
