### ISSUE TITLE
Unify ert_- and libres_tests' source_root function

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#1805]
**Problem description.**
Currently, there are two different functions/fixtures doing the same task but with two different approaches. 
Ert_tests' source_root is solving the problem using os.path
Libres_tests' source_root is solving the problem using pathlib.Path

This also implies that the functions/classes that instantiate this function also uses further uses the two different library philosophies. 

furthermore, there is also constant a variable that references source_root this can also be reduce together with the once above.

**Solution description**
Pick on! I choose the pathlib.Path way.  Pull that function/fixture to the root of the tests, and then fix the cascading calls to appropriately use the same library philosophy. A

**Alternative**
None pathlib.Path has a superiority complex do not antagonize it.

**Comment by jondequinor** [comment]
One is `pathlib` because it was recently changed. That's it. That's the reason for why they differ. There is no other reason, and the same can be said for _not_ choosing `pathlib`—there are none.
