### ISSUE TITLE
Cleanup lingering Jenkinsfiles

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#1809]
**Problem description**
Now that we have unified libres and ert there are Jenkinsfiles lingering around that can be unified/cleaned up. Currently, there are two pipelines for testing komodo. [example](https://github.com/equinor/ert/tree/main/libres/ci/jenkins)

**Describe solution**
Unify all CI files under one umbrella/directory project_root/ci.

**Comment by jondequinor** [comment]
We have two because one of them is special. One builds from scratch all its deps and also tests with Equinor tests.
The other copies over files and tests against bleeding.
