### ISSUE TITLE
Add link to vanilla documentation in README

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1810]
It would be neat if the README would point to the vanilla documentation hosted on ReadTheDocs 🚀 

Docs can be found here: https://ert.readthedocs.io/en/latest/

**Comment by Patil2099** [comment]
I would love to pick this up.

**Comment by ertomatic** [comment]
Feel free @Patil2099 👍 I suggest we add a small paragraph on documentation above the development section with a link 😎
