### ISSUE TITLE
Webviz-ert plotting ert3 spe1 nonchronological

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1811]
**Describe the bug**
The responses generated in ert3 spe1 example are plotted non-chronologically. Meaning the last timestep is sometimes not connected to the rest of the plot, and sometimes connected the first with the last

Fetching record data manually provides a dataframe with the columns in chronological order. 

**To Reproduce**
1.  source komodo bleeding
2. run ert3 spe1 example
3. run ert vis
4. open the wopt_prod in the plot viewer using the "evaluation" ensemble,
**Expected behavior**
The trace should show a line going from timestep to timestep in a chronological fassion

**Screenshots**

![newplot](https://user-images.githubusercontent.com/4976547/123267797-b0071280-d4fd-11eb-8508-d2024579de3d.png)

**Enviromment**
 - OS:RHEL7
 - ERT/Komodo Release: bleeding (2021.06.24)
 - Python version 3.6

**Additional context**

**Comment by ManInFez** [comment]
The dataframes returned from ert-storage for SPE1 is containing lots of NaN. Also it returns the dataframe is not sorted by the columns (dates).

**Comment by ManInFez** [comment]
I am using flowdaily from project res x86_64_RH_7

**Comment by markusdregi** [comment]
Hmm, perhaps it would be useful to inspect the files that are later uploaded as records?

**Comment by ManInFez** [comment]
So the dates in the resulting data produced by flow are different from various realizations. For instance one realization has result from  `2024-08-09T07` and another  has from `2024-08-15T12` When they are stacked together in a dataframe the missing values are represented as NaN. Webviz-ert does not handle dataframes with NaN particularly gracefully.
