### ISSUE TITLE
HISTORY_OBSERVATION does not load the last entry in the summary vector

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1820]
**Describe the bug**
When loading SUMMARY_OBSERVATIONS the last data point in the summary vector is not loaded, and becomes `nan`.
The responses are loaded for the last time step, indicating that this is not an intended feature.

**To Reproduce**
Add this to: `tests/data/test_integration_data.py`
```python
@pytest.mark.usefixtures("copy_snake_oil")
def test_summary_collector():
    res_config = ResConfig("snake_oil.ert")
    ert = EnKFMain(res_config)
    summary = EclSum("refcase/SNAKE_OIL_FIELD.UNSMRY")
    data = SummaryObservationCollector.loadObservationData(ert, "default_0")

    assert (
        data["FOPR"].values.tolist()
        == summary.numpy_vector("FOPRH", report_only=True).tolist()
    )
```

**Expected behavior**
Expect that test to pass and that the internal `ert` data is the same as the refcase summary vector.

**Comment by oyvindeide** [comment]
This has been tested more thoroughly on a real eclipse case, and the problem is also present there.

**Comment by oyvindeide** [comment]
Currently a test is failing on my PR because of a test comparing with some internal data. More details in the linked PR.

**Comment by sondreso** [comment]
Blocked until someone with write access to internal test data is available. See: https://github.com/equinor/ert/pull/1818#issuecomment-884691940
