### ISSUE TITLE
Undefined behaviour: C analysis modules break const-correctness

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1821]
The definition of eg. `analysis_updateA` has most of its parameters marked as `const`.
https://github.com/equinor/ert/blob/4be43976259356052cae84268c0fc9948bf3952d/libres/lib/include/ert/analysis/analysis_table.hpp#L16-L24

However, the implementation doesn't mark these as const. This is undefined behaviour in C++.
https://github.com/equinor/ert/blob/4be43976259356052cae84268c0fc9948bf3952d/libres/lib/analysis/modules/rml_enkf.c#L502-L510

At some point, these matrices are actually mutated, even though they're marked as const in libres!
https://github.com/equinor/ert/blob/4be43976259356052cae84268c0fc9948bf3952d/libres/lib/analysis/modules/rml_enkf.c#L331-L334

This is dangerous behaviour and should be fixed.

**Comment by eivindjahren** [comment]
I believe this has been resolved.
