### ISSUE TITLE
Merge two github folders

### ISSUE THREAD

**Issue by kvashchuka** [equinor/ert#1825]
**Is your feature request related to a problem? Please describe.**
Currently there are two folders: `.github` and `ci/github`. Inside `ci/github` there is only one script - `build_linux_wheel.sh`.

**Describe the solution you'd like**
`build_linux_wheel.sh` is only called in `.github/workflows/build.yml`, so I think it makes sense to move it there and delete `ci/github` folder.

**Comment by sondreso** [comment]
The `.github` folder is reserved for github specific functionality, so I think we should be a little careful to add our own scripts into this folder. I would consider just keeping the current setup, where `.github` is used for the github specific files and `ci/github` is used for tools/scripts that we have extracted for reuse.

**Comment by markusdregi** [comment]
I agree with @sondreso point and I'm hence closing the issue.
