### ISSUE TITLE
Synchronize editable and non-editable behavior for ert installation

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#1837]
**Problem description.**
At the moment if you install ert using `pip install -e .` you will get different behavior from pytest in comparison to `pip install .` This should be the same for both installation methods.

When ert is installed as editable the following are build.
`_skbuild/`
`ert.egg-info/`
`ert_shared/version.py`
`res/.libs/`

these files/directories are not present when ert is install (non-editable).
this is because "When you do pip install . most of this goes into site-packages—cwd is clean."
As a result, you are unable to collect and run ert or libres tests

**Comment by jondequinor** [comment]
Most of this is out of our control, though. `_skbuild` and `res/.libs` probably stem from `scikit-build`. `ert_shared/version.py` is `setuptools_scm` and `ert.egg-info` is probably `setup.py develop` being called. Additionally, not seen here, a symlink and a `pth` entry is made inside `site-packages` which points back to `cwd`.

When you do `pip install .` most of this goes into `site-packages`—`cwd` is clean.

If there is some behavior that differs/lacks between them, then we fix that. But what's described here, is as far as I can see, completely normal.

**Comment by sregales-TNO** [comment]
Does that imply that we want to keep this behavior? If so do I just close this issue?
This is issue was created because of [this](https://equinor.slack.com/archives/C01MCMWD075/p1624977903100700) discussion.

If we do decide to continue down this behavioral change
Is there an alternative solution other than what we currently have?
I search around and the best I was able to find was on [stackoverflow](https://stackoverflow.com/questions/42585210/extending-setuptools-extension-to-use-cmake-in-setup-py/48015772#48015772), but this seems like a greater change than I was expected this issue to be.

**Comment by jondequinor** [comment]
Isn't the problem that you can't run tests with non-editable install?

**Comment by sregales-TNO** [comment]
Yes that is correct

**Comment by jondequinor** [comment]
Could you update the description?

**Comment by sregales-TNO** [comment]
This issue will be close unable to be reproduced on other systems, @kvashchuka and @oysteoh tried but were unsuccessful. This could be a WSL problem, but if it is, then it's not worth the cost to fix. Since ERT is primarily build for Linux/Unix systems and not a subsystem on windows.
