### ISSUE TITLE
Reports of unresponsive monitoring GUI on RGS nodes

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1838]
Users are reporting unresponsive monitoring GUI on RGS nodes. A first step would be to try to recreate this with a benchmark setup with ~200 jobs and ~200 realisations. We should also look into whether the local and lsf queue system makes a difference here.

**Comment by jondequinor** [comment]
Seems es mda will trigger this quite easily with 200 reals 50 jobs.

**Comment by jondequinor** [comment]
I wasn't able to reproduce this later this evening with the same config as before, so I'm strongly suspecting

1. varying load on the RGS nodes impacts the GUI
2. the amount of work being done in the GUI thread makes it very sensitive to 1.

**Comment by markusdregi** [comment]
That is a good theory @jondequinor! A similar one would be that the load on the disks are high during the day and the performance of the monitoring is impacted by the disk performance as well 🤔

**Comment by jondequinor** [comment]
The GUI shouldn't be affected by slow disks. It still might be, but then it is a bug. 


I have a pr that will reduce the work being done.

**Comment by jondequinor** [comment]
Primary hypotheses is that _any_ python less trivial than a dict lookup in a `paint` function, will cause considerable lag for moderately busy GUIs. I found that common paint operations needs to each cost < 10 microseconds. Sorting a dict will add a 10-50x penalty. Instantiating a pydantic model—1000x penalty. 😨 

This means that if the `paint` function access the underlying model (which it will) this operation will have to avoid the above, and simply access pre-rendered data.

We do sorting of dicts and unnecessary allocation of objects in `paint` functions, and we do instantiate quite heavy pydantic models in the GUI thread. That needs to stop.

Will propose a fix.

**Comment by jondequinor** [comment]
Current plan is:

- Pass `SnapshotDict` directly to GUI so the GUI thread does not need to instantiate this itself
- Simplify `SnapshotModel` API by introducing `update(Union[FullSnapshotEvent, SnapshotUpdateEvent])` and by requiring the "pre-rendered" data to exist. This means that `SnapshotModel.prerender(Union[FullSnapshotEvent, SnapshotUpdateEvent])` needs to be called, and should be called on the event outside of the GUI thread (and in testing).
- Introduce the "queue differ" which is in use for the evaluator, but hasn't been used so far for legacy. This reduces the amount of updates sent to the GUI (i.e. we send too many updates currently).
- Switch to `QImage` rendering of job status visualization inside the realization visualization.
- Do less, be more conservative in proxy models and views (make more assumptions, reject more events, etc).
