### ISSUE TITLE
Improve GUI to better support model updating best practices

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#184]
The GUI should in a natural manner allow the users to:
- evaluate the prior
- compare prior and observed values and based on this:
  - identify outliers,
  - activate and deactivate realisations,
  - activate and deactivate observations,
  - adjust the errors of the observations,
- find and evaluate multiple posteriors based on the different sets of "observation filters" created above
- compare the different posteriors

**Comment by jondequinor** [comment]
This is hard/impossible to start. What are the domain specific best practices?

**Comment by markusdregi** [comment]
I agree. I've tried to improve the issue text a bit...

**Comment by jondequinor** [comment]
Should of course be implemented for both the GUI and the CLI.

**Comment by markusdregi** [comment]
Parts of this have already been implemented (in a not so user friendly manner) by being able to restart experiments... Data analysis of observations are being studied in the visualisation milestone as we speak. Improving the user experience of the first part will come up as an integral part of the `ert3` design. Closing this one...
