### ISSUE TITLE
Editable install not working in komodoenv

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#1844]
To reproduce:

- make a komodoenv
- install ert with pip install -e .
- change a python source file
- run ert
- observe that change did not take effect

**Comment by markusdregi** [comment]
Do you manage to reproduce this with other packages as well, or is it only with ERT? Have you tried fetching the location of the the ERT installation you actually pick up?

**Comment by mortalisk** [comment]
> Do you manage to reproduce this with other packages as well, or is it only with ERT? Have you tried fetching the location of the the ERT installation you actually pick up?

I will try to investigate some more regarding this.

**Comment by mortalisk** [comment]
When I first start python console and run ert from there, things behave as expected, and files location are as expected.

Not sure how to verify which files are picked up when running with the installed script. Using `which ert` points me to the komodoenv I created, so that seems correct.

**Comment by markusdregi** [comment]
Something like `python -c "import ert_shared; print(ert_shared.__file__)"` might be helpful.

**Comment by mortalisk** [comment]
That does indeed give me a different result, and points to `/prog/res/komodo/2021.06.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/__init__.py` Not sure why that would give a different result, but it does.

**Comment by markusdregi** [comment]
Me neither, but this should at least help figuring it out...

**Comment by mortalisk** [comment]
`python -c "import ecl; print(ecl.__file__)"` gives expected path to the komodoenv.

**Comment by oyvindeide** [comment]
This issue seems a bit stale, though probably not solved, will close it.
