### ISSUE TITLE
Internal tests not running

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1845]
**Describe the bug**
After the integration of libres none of the internal tests are running on jenkins.

**To Reproduce**
Run the tests on main

**Expected behavior**
Internal tests are running, not skipped (for example `tests/res/enkf/test_enkf_obs.py`)

**Comment by kvashchuka** [comment]
@oyvindeide Are all of the tests skipping or only some? Because in the new Jenkins pipeline that will be in place when https://github.com/equinor/ert/pull/1826 is merged, I see only one test is skipped in `tests/res/enkf/test_enkf_obs.py`:

`../../libres/tests/res/enkf/test_enkf_obs.py ..s.... `

**Comment by kvashchuka** [comment]
Or are you talking about the tests that are explicitly skipped in `testkomodo.sh`?
https://github.com/equinor/ert/blob/6a9d73a03a4ffa82092bdde4a2e7d04cfa286190/ci/jenkins/testkomodo.sh#L48

**Comment by markusdregi** [comment]
There are some tests coming from libres that runs on top of internal test-data. When building with CMAKE they are activated by setting `EQUINOR_TESTDATA_ROOT` to point to the test directory.

**Comment by ManInFez** [comment]
I guess we should wait with this until https://github.com/equinor/ert/pull/1826 is merged

**Comment by markusdregi** [comment]
Or just create a branch on top of #1826 :)

**Comment by ManInFez** [comment]
So #1852 will run the equinor test in the ert-job, I guess #1826 will result in a job doing more (run ctests, etc), while also running parallel
