### ISSUE TITLE
Run tests using ert-storage with authorization

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1847]
The ert-storage test client is not using token based authorization. We should have a integration test which also uses tokens. The authorization is turned off [here](https://github.com/equinor/ert/blob/6a9d73a03a4ffa82092bdde4a2e7d04cfa286190/tests/storage/conftest.py#L42) 

This might require some work in the test-client on ert-storage.

**Comment by oyvindeide** [comment]
´ert-storage` has been deprecated, so closing this issue.
