### ISSUE TITLE
Support for QC on forward models

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#185]
> Support for QC on forward models to ensure that the model is "compliant" before continuing to simulate or load results.

**Comment by markusdregi** [comment]
The basic capabilities for supporting this already in place in _ERT_. If someone comes up with a good system for doing QC on models, we could of course discuss integrating it. But that system itself is currently outside the scope of _ERT_.

**Comment by andreabrambilla** [comment]
I am not sure it's the exact same thing being asked here, but *IF* we'll ever address the validation of forward models in Everest (that was discussed long ago), it could be ported to ERT as well

**Comment by markusdregi** [comment]
@andreabrambilla This is something completely different. They want validation on the reservoir models that are being produced by realizing the parameters in the model ;)

**Comment by markusdregi** [comment]
Should talk to FMU regarding existing QC scripts. Could expose functionality for dumping health status or progress status in runpath, that the GUI would pick up and display.

**Comment by markusdregi** [comment]
This is covered by other internal projects for now...
