### ISSUE TITLE
Parallell blocks of jobs

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#186]
> Support the possibility of specifying multiple jobs that would run independently in parallel.

**Comment by markusdregi** [comment]
The cost of supporting this is probably far larger then the gain of supporting this..

**Comment by markusdregi** [comment]
This is far into the future

**Comment by jondequinor** [comment]
This is most likely going to be solved by the new ERT configuration system:tm:. There, some process topology would be specified by the user, and the implementation should follow that work. 

See https://github.com/equinor/libres/milestone/3 as well as a bunch of other tasks describing this.
