### ISSUE TITLE
Implement functionality flag a job as failed after submit retries towards the LSF queue instead of ERT blow up

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1862]
relates to #1842 

After fixing the retry-schema of queue submits - ERT now blows up when retries are exhausted ( currently 100x2sec ) instead of just hanging. We should make it possible to flag the jobs as failed after the retries instead of `util abort` and enter the normal way of dealing with failed jobs and the thresholds we have set for us to have a successful ensemble or not. 

@markusdregi  please chime in with additional information regarding this issue and how it may be fixed if you have any suggestions 👍

**Comment by xjules** [comment]
This has been resolved in the scheduler.
