### ISSUE TITLE
Job status not updated for LSF when using the ensemble evaluator

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1874]
**Describe the bug**
While testing #1863 I realised that running a bleeding ERT on an LSF cluster with the ensemble evaluator enabled is not giving any updates to the job statuses. Instead, they all remain pending while there is clear progress on disk and in the end even the queue system reports it as completed.

**To Reproduce [using LSF]**
Steps to reproduce the behavior towards LSF:
1. Open an RGS node
2. Source komodo/bleeding
3. Get a fresh copy of the poly_example
4. Change `QUEUE_SYSTEM` from `LOCAL` to `LSF`
5. Run `ert gui poly.ert --enable-ensemble-evaluator`
6. Run an ensemble experiment and observe that none of the job statuses are changing in the detailed view

**Expected behavior**
I expected the job statuses to update and at the end of the run both the jobs and the entire realisation to be labelled green in the details status window.

**Screenshots**
<img width="1276" alt="Screenshot 2021-07-15 at 13 59 26" src="https://user-images.githubusercontent.com/1557864/125784779-13def777-b1f2-4514-a5fe-749e813cfbd7.png">

**Enviromment**
 - OS: On-premise
 - ERT/Komodo Release: bleeding
 - Python version: 3.6
 - Remote/HPC execution involved: yes

**Comment by markusdregi** [comment]
This is most likely a consequence of https://github.com/equinor/ert/issues/1870. I suggest we keep it open until #1870 is resolved and then test this again...

**Comment by mortalisk** [comment]
![Screenshot 2021-07-23 at 11 32 07](https://user-images.githubusercontent.com/596662/126764021-1918a0a9-2d52-4c52-8b89-4976ebc72d44.png)

I got 4 jobs that did not update.

**Comment by sondreso** [comment]
Except for the infrastructure problems described here https://github.com/equinor/scout/issues/394, this is now working as expected.
