### ISSUE TITLE
Rename EnsembleRecord and MultiEnsembleRecord

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1875]
Records are data structures that store data of a particular type. Currently, `NumericalRecord` and `BlobRecord` derive from the `Record` base class and store structured numerical data, and binary data, respectively.

The `EnsembleRecord` and `MultiEnsembleRecord` classes do not derive from `Record`. Instead, they are containers of records, such as `NumericalRecord` and `BlobRecord`. These classes do not fit naturally in the `Record` hierarchy, and should indeed not be forced into it.

Yet their current naming suggests that they are records, which the unsuspecting developer may expect to derive from `Record`. 

Both  `EnsembleRecord` and `MultiEnsembleRecord` should be renamed to clarify that they are not records, but rather collections of records. 

Suggestions could be: `EnsembleRecord` => `RecordEnsemble` and `MultiEnsembleRecord` => `MultiRecordEnsemble`, but some thought should be given to a good naming scheme.

**Comment by markusdregi** [comment]
I think the suggested change makes sense 👍🏻 But I'll sleep on them :)

**Comment by sregales-TNO** [comment]
I have spoken with @sondreso and @verveerpj and decided to name the classes EnsembleRecord => RecordCollection and MultiEnsembleRecord => RecordCollectionMap
**Reason for the change:**
The word "Ensemble" means a group of items. (apple, tire, and sun are a group of unrelated Items and can still be an Ensemble) This means that Ensemble is ambiguous. while it still works, to an extent, for EnsembleRecord, it is redundant and more confusing while used alongside the word "Multi".
**Why Collections:**
Collection while being a synonym for Ensemble, is a recognized and agreeable label that is widely used for this data structure in programming.
**Why Map:**
MultiRecordCollection nor MultiCollectionRecord is clear, and we don't want Record at postfix for the reasons Peter describes. MultiEnsembleRecord is collection of a collection of Records. writing CollectionCollection is redundant and confusing, thus Map, Mapping is a generic version of Collections.abc.Mapping exactly what we need.
