### ISSUE TITLE
Support for Markov chain Monte Carlo

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#188]

**Comment by andreabrambilla** [comment]
Do we have any documentation/link/paper/book about this?

**Comment by markusdregi** [comment]
We do indeed. Among others: https://www.onepetro.org/conference-paper/SPE-113390-MS

We also have some internal reports and one of the authors as our product owner.. But we'll take a go through of these issues one of the next days :+1:

**Comment by joakim-hove** [comment]
> Do we have any documentation/link/paper/book about this?

Markov Chain Monte Carlo (MCMC) is a general purpose technique to sample from distribution; there is a *large* amount of literature available dating back to the Manhatten project. I would strongly reccomend understanding the general concept before looking to petroleum specific implementations.

**Comment by andreabrambilla** [comment]
I do have a basic understanding of MCMC (was looking into that for ray-tracing a few years back), I meant if we have some documentation about applying it to history matching ;)

**Comment by markusdregi** [comment]
Closing this as a duplicate of https://github.com/equinor/ert/issues/1107
