### ISSUE TITLE
Cleanup `share/ert/workflows`

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1880]
There are numerous workflows in `share/ert/workflows` that are neither tested nor documented. I suggest we cleanup the content with the following approach:

- [x] remove workflows in the repository that is not installed and available on-premise in a fresh Komodo build,
- [x] remove workflows that are not functioning anymore (referring to missing internal functions etc),
- [x] log usage of remaining workflows to central logger (when it is up and running) such that we can detect usage,
- [x] remove workflows that are not appearing as active in logs,
- [ ] write tests and move remaining workflows to `semeio`.

**Comment by markusdregi** [comment]
`std_scale_correlated_obs` should be deprecated and users should be referred to `misfit_preprocessor` in semeio instead.

**Comment by markusdregi** [comment]
Adding this issue to our logging efforts as a demonstration of it functioning. When the workflows remaining are logging as described in the issue description, this issue can be moved out of the logging epic.

**Comment by oyvindeide** [comment]
Created: https://github.com/equinor/ert/issues/1987 to split out the logging part of this issue, and marked it as blocked by that issue.

**Comment by ManInFez** [comment]
None of the jobs appear to be active according to the logging. Should we remove them all?

**Comment by markusdregi** [comment]
I'm pretty certain the shell workflows are in use...

**Comment by dafeda** [comment]
![Screenshot 2022-02-14 at 10.35.51.png](https://images.zenhubusercontent.com/6130ca879df65d2e3b887f65/4e1628ee-595d-4ec0-8fab-cc4fba94ef6d)

Based on the Workflow distribution, it seems as if shell-jobs are used, for example `COPY FILE` and `MAKE DIRECTORY`.
Am I misunderstanding something @ManInFez ?

**Comment by ManInFez** [comment]
@markusdregi @feda I guess I only looked in share/workflows/jobs/internal

**Comment by sregales-TNO** [comment]
I'm not doing this issue due to my lack of access to the FMU logs. to see what workflow is and isn't being used.

**Comment by sondreso** [comment]
`GEN_DATA_RFT` is already part of semeio: https://github.com/equinor/semeio/blob/main/setup.py#L30. Might be that the version in ERT is not used :thinking:

**Comment by oyvindeide** [comment]
Maybe, worth looking into what is actually used, will reopen so we remember to check.

**Comment by oyvindeide** [comment]
Test have been added for the remaining jobs. So will close this as completed now.
