### ISSUE TITLE
test_std_enkf_debug fails if the build folder is not inside the source folder

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1881]
std_enkf_debug is not copied to the installed folder, and if the build folder isn't in the source folder, the test will fail. This test is possibly deprecated?

**Comment by markusdregi** [comment]
**Definition of Done**
Conditional skip in the above commit is removed again.

**Comment by sondreso** [comment]
`std_enkf_debug` is removed, so this is no longer relevant
