### ISSUE TITLE
Job_runner should distinguish between ERT2, ERT3 and everest

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1890]
Currently they all report to be ERT (e.g. `ert_pid`).

**Comment by oyvindeide** [comment]
So the job runner does not really have that context at the moment, do you have a good idea of how we should inject that context?

**Comment by sondreso** [comment]
One option would be ta inject this into the `jobs.json` file as is done with the `ee_id` and certificates.

**Comment by oyvindeide** [comment]
I guess that should be fine, so this: https://github.com/equinor/ert/blob/aef6849d0ca791d739958d84e22ebb6a427628ec/res/job_queue/queue.py#L555 and this https://github.com/equinor/ert/commit/93469fc79b75b759be16b41c5a59c512620dacbc should be a good starting point for solving this then.

**Comment by sondreso** [comment]
Yes. I'm not sure I like the growing number of places that add information to the `jobs.json` file, but I don't really see any better options.

**Comment by jondequinor** [comment]
I agree, and the responsibility for creating it initially is in libres, which we've demonstrated multiple times now is too low level.

**Comment by jondequinor** [comment]
> I'm sorry, I've been back and forth on this in the code base.. Who are they all?

Everest and ERT.

**Comment by oyvindeide** [comment]
I think we are at a point where this is not very fruitful to perform. I will close this issue, but feel free to reopen if there is merit to doing it.
