### ISSUE TITLE
Replace libecl filesystem utilities with std::filesystem equivalents

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1892]
List of functions to look out for:

- `util_addmode_if_owner` (2 uses)
- `util_alloc_abs_path` (13 uses)
- `util_alloc_atlink_target` (1 uses)
- `util_alloc_cwd` (15 uses)
- `util_alloc_filename` (82 uses)
- `util_alloc_link_target` (1 uses)
- `util_alloc_normal_path` (1 uses)
- `util_alloc_realpath` (11 uses)
- `util_alloc_realpath__` (1 uses)
- `util_alloc_rel_path` (9 uses)
- `util_alloc_tmp_file` (11 uses)
- `util_chdir` (9 uses)
- `util_chdir_file` (2 uses)
- `util_clear_directory` (14 uses)
- `util_copy_directory` (1 uses)
- `util_copy_file` (9 uses)
- `util_entry_exists` (5 uses)
- `util_entry_readable` (2 uses)
- `util_file_exists` (103 uses)
- `util_file_mtime` (5 uses)
- `util_file_readable` (3 uses)
- `util_file_size` (2 uses)
- `util_files_equal` (4 uses)
- `util_is_abs_path` (19 uses)
- `util_is_directory` (20 uses)
- `util_is_executable` (11 uses)
- `util_is_file` (21 uses)
- `util_is_link` (4 uses)
- `util_make_path` (29 uses)
- `util_make_slink` (1 uses)
- `util_mkdir_fopen` (25 uses)
- `util_mkdir_p` (2 uses)
- `util_move_file` (1 uses)
- `util_path_split` (1 uses)
- `util_same_file` (2 uses)
- `util_split_alloc_dirname` (3 uses)
- `util_split_alloc_filename` (3 uses)
- `util_unlink` (22 uses)
- `util_unlink_existing` (21 uses)
- `util_update_path_var` (1 uses)
- `util_walk_directory` (1 uses)

**Comment by jondequinor** [comment]
@markusdregi did you intend to migrate this to ERT? It seems to be an ecl issue.

**Comment by dafeda** [comment]
Since we are now on C++17 we can use std::filesystem.

**Comment by dotfloat** [comment]
I think this thing is somewhat out of date now :)

You can edit the OP to your heart's content.

**Comment by sondreso** [comment]
Closing this as it is stale, feel free to re-open issues for more specific cases
