### ISSUE TITLE
Remove data_root

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1897]
After https://github.com/equinor/libres/issues/934 has been resolved there seems to be no more usage of the `DATA_ROOT` functionality passed to the forward model. This should be double checked and if correct, all traces of this should be removed from the code base.

**Comment by oyvindeide** [comment]
Only used here: https://github.com/equinor/ert/blob/a641ec80bb40ddc79b0914a5377f92eb5a59e338/src/ert/_c_wrappers/job_queue/forward_model.py#L124

**Comment by sondreso** [comment]
It's written to the `jobs.json` file, which means we don't know who might read that file and use it. However, the use is probably very limited if any, so the approach here I think is the remove it. If we get feedback that it is used, we will instead revert the change.
