### ISSUE TITLE
Improved observation configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#190]

**Comment by markusdregi** [comment]
A possible solution to this would be to redo the structure of the observations configuration and make it _yaml_ instead.

**Comment by markusdregi** [comment]
We should start by revising how this was done in the existing format together with @joakim-hove. If we are to drop the refcase, we should not support references to the history of the refcase when defining the observations.

**Comment by jondequinor** [comment]
This should maybe be tackled in the new configuration work? Not on its own.

**Comment by markusdregi** [comment]
I agree
