### ISSUE TITLE
Replace double underscore with single underscore for python private class members

### ISSUE THREAD

**Issue by xjules** [equinor/ert#1901]
Usually double underscores `self.__` are reserved by Python, so we should replace those with single underscore `self._`.  For example: `self.__context -> self._context`

**Comment by oyvindeide** [comment]
Could not find any instances of this anymore, so solved!

**Comment by sondreso** [comment]
There are still many examples of this in the code, but I believe we should still close this issue. The better approach is to move towards not using `__` to indicate private function iteratively  as we develop and refactor the code.
