### ISSUE TITLE
Move ForwardModelStatus to everest

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1902]
Now that the legacy tracker is deleted, we no longer read the status from files in the runpath in ert. Everest is the only consumer of this could, and we should move it there instead. 

The `load` method tries to open a non-existent/corrupt/written to/just deleted file. These various scenarios should be tested.

**Comment by sondreso** [comment]
No that the legacy tracker is deleted, we no longer read the status from files in the runpath.

**Comment by sondreso** [comment]
Still used by Everest, so we should invest in some test

**Comment by jondequinor** [comment]
Could possibly be removed from libres and migrated to Everest as well.

**Comment by sondreso** [comment]
Yes, I think that makes the most sense. Changed PR title and description to match

**Comment by oyvindeide** [comment]
We should use the same communication in ERT and Everest, so I am closing this issue as we would take another approach.
