### ISSUE TITLE
Store job std{out,err} logs in a separate directory

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1903]
Currently, the `stdout` and `stderr` logs from jobs are written into the runpath directory as `[job name].stdout.[job#]`. A complicated pipeline may have hundreds of these files, which makes it difficult for users to debug or otherwise look at other files.

I propose we put all of these logs into a subdirectory of runpath called `logs/` without adding this as an option. The location of the logs is an implementation detail, and if anyone is actually using these to do useful work (other than a human reading them) then we'll discover it swiftly with such an aggressive implementation.

**Comment by markusdregi** [comment]
**Definition of done**
- The standard location for stdout and stderr files are changes to `<runpath>/logs` such that jobs that do not configure the path always end up with their logs in that directory.

- In addition we should change (or just rely on the default) for all standard jobs in the repository.

- Last, we should check if any of the jobs in semeio also configures this explicitly and if so, apply the above step in that repository as well.
