### ISSUE TITLE
Add more help text in RMSRunException

### ISSUE THREAD

**Issue by berland** [equinor/ert#1904]
When RMS fails for whatever reason, users are presented with the output from this exception:

https://github.com/equinor/libres/blob/9b72ec583032bc3d893af70f7562d82c5b4263dc/python/res/fm/rms/rms_run.py#L151

This error and the traceback is reported as the "error message", although it never gives the full answer and those who tries to help always have to ask for more details.

Suggestion:
* Remove the traceback. It gives uses the impression that there are details there that experts can diagnose, while it never says anything interesting.
* Add ~hints~  instructions to look at stderr and stdout, and rms/model/workflow.log in the message.

**Comment by eivindjahren** [comment]
The plan is now to remove the RMSRunException and use rms-sys: https://github.com/equinor/ert/issues/7859
