### ISSUE TITLE
Parsing of num_cpu from data file is buggy

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1905]
The parsing of the number of processors needed from the data file seems to be buggy: 
https://github.com/equinor/ecl/blob/007f000ba97b04b670217aa425220f907c022e79/lib/ecl/ecl_util.cpp#L1294:L1309

In particular, if the word parallel is used elsewhere in the file it seems to fail. 
```
----------------------------------------------------------------------
-- A very simple test case for the shared memory parallel option.
-- --------------------------------------------------------------
```
Failing case can be found here: `/prog/res/ecl/grid/2020.2/eclipse/data/PARALLEL.DATA`

**Comment by markusdregi** [comment]
I'm not surprised that this ends up being yet another incomplete implementation of this. As I see it we have at least three options:

- Start depending on `opm-common` and use it for parsing the keyword. This is a large dependency to introduce, especially when the direction of the project is to extract the domain simulator parsing out of the ERT tool itself.
- Stop providing support for parsing the parallell option from the datafile. This would warrant an unwanted breaking change for ERT2. In particular, when there is no good alternative at the moment.
- Slightly improve the parsing in libecl such that the content of lines following a `--` is ignored completely and the only input accepted is `PARALLEL %d`.

I suggest we move forward with option three as it is the one most in line with the direction of the project, while simultaneously allowing our users to continue their daily operations until an alternative is in place.

**Comment by verveerpj** [comment]
Looking at this in the code and with a simple example I cannot see any issue with having the word `PARALLEL` in a comment. However, the case that is mentioned does have `PARALLEL` in its title section, and if I do that in a simple example, the parsing does not fail, but returns the wrong value. Thus, I am assuming that this is the real issue. Will look into options to fix this.

**Comment by verveerpj** [comment]
The current code does not really parse the file, just does a search for the `PARALLEL` keyword. We don't want to start parsing now for the `TITLE` keyword, just to avoid any occurences of `parallel` in there, since then we are starting to build a parser, which likely will lead to more pain...

However, it seems that the eclipse specification of this file format requires that keyword start at the beginning of the line. So checking if the `PARALLEL` string starts at the beginning of a line should do the trick.

**Comment by verveerpj** [comment]
Resolved in the `ecl` repository.
