### ISSUE TITLE
Stop changing the permissions of job executables

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1907]
If a forward model config has the same name as the `EXECUTABLE` but different case, this will fail on case insensitive systems. Libres will change the executable bit on the config and pass it to job dispatch as an executable, leading to some strange behavior.

A couple of things could be changed:

* libres should probably not change the executable bit
* libres presumably first searches cwd for a file, before searching `PATH`, order should perhaps be reversed?

**Comment by markusdregi** [comment]
I believe cwd is indeed inspected first, but in case your path is a relative path ERT will no longer support this and it will try to search for the executable in PATH instead. The executable bit I very much agree with and I think we should stop doing it.

Implementation can be found here: https://github.com/equinor/ert/blob/47718c11af96c08e04fd295dc9b7db4187e5cf02/libres/lib/job_queue/ext_job.cpp#L405
