### ISSUE TITLE
Yaml configuration file

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#191]

**Comment by markusdregi** [comment]
Depends on https://github.com/Statoil/libres/issues/238

**Comment by markusdregi** [comment]
We should start by revising how this was done in the existing format together with @joakim-hove.

**Comment by markusdregi** [comment]
Needs https://github.com/Statoil/libres/issues/238

**Comment by oyvindeide** [comment]
Will close this as a duplicate of several other issues, filter on [configuration](https://github.com/equinor/ert/labels/Configuration).
