### ISSUE TITLE
Make logging configurable 

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1910]
While running a large Everest job on a TNO cluster, it was noted by their system administrators that many http requests were made to a server in Norway, bogging down their DNS server.

After conferring with the scout team, this appears to be due to logging code, which contacts a server, which I understood not to be functional anymore anyway.

Awaiting a rework of the logging code, we should disable the call for now.

I will do this by disabling the call in the `log_message` fucntion in `python/ert_logger/__init__.py`, adding a comment.

As the logging issue probably should be resolved properly at some  point, I will leave this issue open after a fix has been merged.

**Comment by markusdregi** [comment]
Logging should by default be propagated to file. It should be possible to opt in for logging to a centralised logger and we should utilise this within Equinor to get good metrics.

**Comment by oyvindeide** [comment]
Adding customizable handles was solved in: https://github.com/equinor/ert/commit/b2ec3d79841d9eb4497d20b5339e8c938b50ca12. I am closing this as the original cause of the issue was solved, and logging is now configurable.
