### ISSUE TITLE
Forward model eclipse100/300: change forwarding of stdout to .OUT

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1911]
eclrun started from version 2109.3 to forward stdout to file .OUT as opposed to .LOG for older versions. It has been decided to update other EQNR wrapper scripts to adhere to this new standard. 

I hence propose that the eclipse forward job in libres also starts forwarding stdout to .OUT for versions >= 2019.3. In the transition other wrapper scripts symlink .LOG ->.OUT for backwards compatibility. Not sure how good an idea this really is...

Note that the monitoring in ERT will be affected by this as it displays the .LOG file in the Detailed monitoring widget.

**Comment by sondreso** [comment]
In the eclipse job, the output from the process is sent both to the standard out file (which the GUI reads from), and to the .LOG file. The code easily allows us to multiplex over more output streams, so we could just add the contents to .OUT as well. The question is: Do we want to (1) always provide both files, (2) provide only .LOG for  < 2019.3 and only .OUT for >= 2019.3, or (3) provide only .LOG for  < 2019.3 and both for >= 2019.3?

**Comment by eivindsm** [comment]
Pls contact @vkip for a discussion on this topic.

**Comment by vkip** [comment]
If it does not matter for the ERT GUI, my suggestion would be to do what eclrun does, so option (2) above [only .LOG for < 2019.3 and .OUT for >= 2019.3]. In addition to eclrun consistency this avoids duplication and confusion wrt. what is the difference between the files. Not a strong opinion though, so definitely willing to listen to arguments for the other options..

**Comment by sondreso** [comment]
> In addition to eclrun consistency this avoids duplication and confusion wrt. what is the difference between the files.

I very much agree with this, so I will implement option 2 :slightly_smiling_face:
