### ISSUE TITLE
Precision discrepancy between parameters txt/json and internal values

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1914]
There is a discrepancy in float precision in the formatted files that libres creates in runpath's and the internal unformatted floats, at the 6th decimal point.

This issue stems from [`value_export.cpp`](https://github.com/equinor/libres/blob/974d957bb7c7052a7973d513f4e6a73719170e23/lib/enkf/value_export.cpp), which uses the `%g` formatting for floats in `fprintf`. These are limited to 6 decimals by default. While `fprintf` doesn't make a guarantee for round-trip conversion (ie, conversion from `float` to `string` to `float` should be bit-wise identical initial `float`), it is possible to have a best-effort round-trip conversion by increasing the precision of the formatted floats. The [`std::numeric_limits<float>::maxdigits10`](https://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10) is a constant for `float` that describes the minimum digits necessary to represent all float values in decimal notation.

There is a well-regarded C float-to-string conversion library called [ryu](https://github.com/ulfjack/ryu), which guarantees round-trip conversion.

The futuristic alternative is C++17 [`std::to_chars`](https://en.cppreference.com/w/cpp/utility/to_chars), but currently it's only supported by the very bleeding-edge GCC 11's `stdlibc++` and MSVC 19.24+, and not at all in Clang's `libc++`. These are beyond the scope of any of the manylinux docker images.

**Comment by oyvindeide** [comment]
I think this is solved @pinkwah? Will close it, but feel free to reopen.
