### ISSUE TITLE
Fix test_field_basics test

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1916]
As a part of reintroducing the Equinor tests into the test pipeline (see https://github.com/equinor/libres/pull/1138), test_field_basics was skipped since it was causing an abort.

This should be fixed and the test reintroduced.  

https://github.com/equinor/libres/blob/da6c7d20af60bdadfa8d7f61ec114dfedd6e0d20/tests/res/enkf/test_field_export.py#L28

**Comment by eivindjahren** [comment]
This test is now running
