### ISSUE TITLE
Spawn issues for all deactivated tests

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1918]
**Introduction**
Over the last years a handful of tests have been deactivated for various reasons. They should all be activated again. However, this should start by just creating an overview of all the deactivated tests. Most tests are either deactivated via CMake or using the `skip` fixture.

**Suggested process**
For every deactivated test in the repository;
- activate the test and verify that it is still failing (if not, make a PR to reactivate it),
- create an issue pointing to the deactivated test. Attach the error it produces, the commit when it was deactivated and if recoverable - the reason it was deactivated. Add the `testing` and `payback` labels.

**Definition of done**
There are no deactivated tests in ERT without a corresponding issue.

**Comment by oyvindeide** [comment]
No skipped tests anymore without corresponding issue :fireworks:
