### ISSUE TITLE
Introduce uniform record

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1919]
**Context**
Quite some data that is passed through our workflows are fixed over the ensemble. That is, we have a single set of values or a blob that should be passed to all realisations. A realisation should not, by nature, be left with the task of producing a record that is fixed for the entire ensemble. Hence, this job is left for the user when setting up experiments (and for workflows in the future).

**Terminology**
Many words can be used to describe data that is equal over the entire ensemble; uniform, fixed, global, constant, homogenous and so forth. While constant could be tempting, I suggest we leave that keyword for now, as that could also be used to describe data that cannot be changed through a pipeline.

**Usage**
In https://github.com/equinor/ert/pull/1855 blob records are introduced for the users. And in particular, the implementation cumulates in that the SPE1 datafile can be transported as a blob to all of the realisations. This blob should be treated as and be honest about being a uniform record that is the same for all realisations; both in configuration and in that it should not be persisted in storage per realisation.

Another usecase is numerical data that is also fixed over the entire ensemble. For instance, in #1853, we hint towards making the `x`-values more explicit in the polynomial example. With a fixed numerical record it should be possible to have a single list of values encoded in a JSON file that one could load and later use over the entire example.

**Extra**
After such records are introduced we should make sure they are treated neatly in the sense that we can:
- load a fixed record into storage and afterwards use it in experiments of varying ensemble size and
- that loaded fixed records can be used in a hassle free manner within sensitivity analysis experiments without having to make sure the record ensemble is of the correct size.

**Comment by DanSava** [comment]
Regarding the terminology, now that the `EnsembleRecord` has been renamed as `RecordCollection`, we can call this proposed new record type `EnsembleRecord`.

Regarding the usage from the description seems like it would be natural to split this into Numerical and Blob Ensemble records just like a normal record. But if that is the case then it means that Ensemble(uniform/global/constant/fixed)Record cannot be an instance of a Record and we would end up with Ensemble(uniform)NumericalRecord and Ensemble(uniform)BlobRecord classes which would only contain extra information regarding if they need to be stored for one particular realization or for all realizations.

It seems more natural to me to maybe expand a bit the current Numerical and Blob records with a field that would contain this information if it is for the entire ensemble or just for a particular realization. And then the transmitters would be able to decide how the data is transmitted.

**Comment by verveerpj** [comment]
I think that the record itself should not have knowledge if it is used uniformly or not, since they are currently not much more than a data struct. However, the `RecordCollection` class embodies an ensemble, with a size, and the data for each realization.  So maybe it is best that the `RecordCollection` objects contain the information that its content is uniform.
