### ISSUE TITLE
Varying blob record as input

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1921]
**Introduction**
Our ERT2 pipelines frequently depends on blob data that varies over the ensemble as input to the forward model.

**Usecase**
We have carefully crafted datafiles for the different realisations that we now want to use in our modelling setup. They reside on disk and we should be able to refer to them and have the different input decks be simulated in the different realisations.

**Syntax**
I'm slightly uncertain what would be a good syntax for preparing this. We could use shell expansion of `*` when running `ert3 record load`, but this will make the mapping from realisation id to corresponding blob implicit as we would have to extract it from the expanded paths. Or, we could pass a path format to the load command and then we load all matching files 🤷🏻 Good ideas are welcome...

**Definition of done**
There is a SPE1 example where there are different datafiles crafted for the different realisations and each realisation gets their corresponding datafile to simulate.

**Additional information**
It is most likely a good idea to resolve #1920 before this issue.

**Comment by DanSava** [comment]
As I see things I think we should discuss two cases with respect to varying blob records. 

*Case 1*: We only have one data file that will vary for each of the realizations of the ensemble

An example of the structure on disk would look something like the following:
![one_blob_resource](https://user-images.githubusercontent.com/4508053/128678164-9ca97a5e-a76e-41be-b629-0eb706a3896c.png)


*Case 2*: We have multiple data file that resides on disk in a user-defined folder structure 
 An example of the structure on disk would look something like the following:

![multiple_blob_resources](https://user-images.githubusercontent.com/4508053/128678420-b18164dd-61d3-4c3f-bb87-77d97fd95bfa.png)

For both cases, I assume two possible locations where the resource folder can be located. 
1. At the root level of the workspace in which case it would be used for all the experiments defined in the workspace:

![global_resources](https://user-images.githubusercontent.com/4508053/128679237-94f21791-a2bc-4293-adce-98a4380bc76a.png)


2. At the level of the experiment in which case it would overwrite any defined global resources for all experiments

I agree that loading the resources into storage can be done using the `record load` command and then using a path something like:

`ert3 record load record_name resources/realizations/realization_*REAL_ID*/file_name` 

The implementation would replace `*REAL_ID` with the realization number and would build a record collection containing all the separate blob records and store it into storage. 

Using the `record load` route in my opinion can be expensive when it comes to storage interactions. If we have very large data files that need to be stored in storage currently the data flow when running an experiment is the following:

* Ensemble collection is retrieved from storage 
* When preparing the experiment the collection is retrieved from storage and then it is loaded back into storage for the experiment we are running.
*  Before we start evaluating the ensemble collection is retrieved from storage one more time and for each of the records a transmitter is made and data is transmitted, this can also be a storage transmitter which would result in loading into storage the individual records associated with each realization and then finally the evaluation of the experiment would start. 

This means that the same data will be loaded into storage on three separate instances, and then downloaded on another 3 separate instances before being used in the execution node when running the forward model scripts.

It would be a lot less resource-intensive if it would be possible to solve  https://github.com/equinor/ert/issues/1944 and transmit the data for the ensemble inputs as records using a storage transmitter and then just using the realization mapped transmitters in the evaluation. This will result in loading data once and downloading it also only once on the execution node before using it when running the scripts in the forward model.

**Comment by jondequinor** [comment]
How is this achieved today? Could not find any hints in the HM tutorial. I think we should support today's approach to some extent.

At the same time, I think implicit mapping via file/folder name (some_blob_res_0, …, some_blob_res_n) is a bit awkward—unless they are generated programmatically. Then fine. If they are made by hand, I think an explicit mapping in a manifest file offers a bunch of advantages.

```
blob_res_manifest.yml

location: my_experiment/real0/some_blob_res
realization: 0
record: some_blob_res_0

…
```

And then loaded with `ert3 record load --manifest blob_res_manifest.txt`

**Comment by oyvindeide** [comment]
I am not sure I understand the issue, and not sure it is relevant anymore, feel free to reopen if more details can be added, and it is still relevant.
