### ISSUE TITLE
Move configuration schema to sensitivity algorithms

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1924]
**Introduction**
As a step towards making it possible to plug-in new algorithms in ERT3 the responsibility of defining what can be configured for a specific algorithm should be moved from the configuration module into the algorithm itself.

That is, the pydantic schema defining the input data should be served by the algorithm it belongs to, not reside within `ert3.config`.

**Definition of done**
Exposing a new configurable option for a sensitivity algorithm can be implemented entirely within `ert3.algorithms`.

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
