### ISSUE TITLE
Allow loading external analysis modules using absolute path

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1927]
Currently if the `libname` will always be appended to `<site-packages>/res/.libs` to find external analysis modules, even though `libname` might be an absolute path. We should allow specifying analysis modules with absolute paths. See: 

https://github.com/equinor/ert/blob/d8cde48d08df663ced850685cbcdb5210cc304d7/libres/lib/analysis/analysis_module.cpp#L157-L163

**Comment by jondequinor** [comment]
It should in the very least look inside the linker search paths.

**Comment by markusdregi** [comment]
Loading external analysis modules are no longer supported and hence the issue is not relevant anymore.
