### ISSUE TITLE
Bug in argument parsing for forward model jobs

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1940]
**Describe the bug**
Odd number of ' escaped by " " triggers an error message. 

**To Reproduce**
1. Add an argument with with ' escaped by " `FORWARD_MODEL SOMEJOB(<ARG>="last/part/of/path' ")`
2. The following error message will show: `Error message: subst_list_add_from_string: missing string delimiter in argument: <ARG>=last/part/of/path'`

**Expected behavior**
Use of ' escaped by " " should be allowed, and not trigger a error message. 

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.07.00
 - Python version: 3.6
 - Remote/HPC execution involved: No (but unrelated)

**Additional context**
Originally reported by user on slack

**Comment by ManInFez** [comment]
Since " is stripped in the initial parsing of the config file, we are unable to utilize " to escape characters in the argument parsing.

**Comment by ManInFez** [comment]
Closing this as a wont fix.
