### ISSUE TITLE
Inconsistent status messages from CLI

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1943]
**Describe the bug**
Ert displays the followings status 

```
    ■ Waiting         0/194
    ■ Pending         0/194
    ■ Running         0/194
    ■ Failed          2/194
    ■ Finished      192/194
    ■ Unknown         0/194
Simulations completed.
2 jobs failed due to the error: Process exited with status code 1
135 jobs failed due to the error: The run is cancelled due to reaching MAX_RUNTIME
```
While the number of failing jobs is correct, the number of jobs reported to be killed by MAX_RUNTIME is way too high, and conflicts with the number of finished jobs reported by ert. 

**To Reproduce**
Not able to reproduce the error at this point.

**Expected behavior**
Status messages from ert should be consistent and not conflict with each other. 

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.07
 - Python version: 3.6
 - Remote/HPC execution involved: yes

**Additional context**
Originally reported by user on Slack

**Comment by sondreso** [comment]
This bug has not been reproduced since the original report, and the code has been change quite a bit in this time period.

**Comment by jondequinor** [comment]
Was also probably legacy legacy evaluation.
