### ISSUE TITLE
Include an explanation of ERROR_MODE and ABS in the documentation

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1950]
We should include a sentence in the docs explaining that ABS is the default for ERROR_MODE and that ERROR will be interpreted as the absolute value (also verify in the code that this is correct)

**Comment by hnformentin** [comment]
Investigating, the documentation actually explicits "By default, the observation error is set to 10% of the observed value, with a minimum of 0.10. It can be changed as follows: ..."
What is the default behaviour wanted in the code? ERROR_MODE=ABS or ERROR_MODE=REL?

**Comment by sondreso** [comment]
This issue was written based on this message: https://equinor.slack.com/archives/C01MCMWD075/p1628746906029400

The intention was not the change the error values, but rather explain what the default setting for the ERROR_MODE option is (see [link](https://ert.readthedocs.io/en/latest/reference/configuration/observations.html?highlight=ERROR_MODE#history-observation-keyword)), and explain the effects of the different settings (`ABS`, `REL` or `RELMIN`).
