### ISSUE TITLE
Clean up code related to legacy network logging

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1963]
The old network reporter is disabled due to: 

https://github.com/equinor/ert/blob/efde2166e217b93fdbae568b6b0fc563ade4a49a/ert_logger/__init__.py#L18-L19

However, code for the old network reporter (https://github.com/equinor/ert/blob/main/job_runner/reporting/network.py) is still active, while it ultimately never logs anything. This should be clean up (either removed, or updated for a new logging solution).

**Comment by sregales-TNO** [comment]
Can this issue be more descriptive, please

**Comment by sondreso** [comment]
I have updated the description a bit, please add anything comments you might have @oyvindeide :smile:
