### ISSUE TITLE
Inputs stored as tuple in configuration, but could benefit from being a Mapping-like type

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1965]
**Describe the bug**
We have a lot of this code

`input_.location for input_ in step.input if input_.record == record_name`

Indicates that a simple list is inadequate.

**Comment by sondreso** [comment]
We should probably not update the configurations itself, or in other words the user should still input it as a list. However, in code we should be able to use it as a map (either by more advanced getters, converting it when creating, or similiar)
