### ISSUE TITLE
Use setuptools instead of CMake

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1967]
Use the built-in functionality of setuptools rather than the complex CMake to build libres.

The goal of this issue is to simplify development and testing of libres.

**Comment by dotfloat** [comment]
Considering closing this and instead improving the CMake experience. This is due to a lot of missing functionality in setuptools.Extension, which in practice is only meant for compiling just a few C sources.

**Comment by oyvindeide** [comment]
Has been done :+1:
