### ISSUE TITLE
How should we handle SUMMARY data in ert3

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1971]
What we would like to achieve: 
- Handle multiple vectors
- Handle groups of vectors

**Comment by xjules** [comment]
Maybe parsing summary files (Eclipse related tools) should be outside of ert (eg. external forward model job)? Hence, ERT should not know about eclipse files.

**Comment by jondequinor** [comment]
I think the code responsible for the parsing of summary vectors should at least be peripheral, and a candidate for being a plugin. If we want to support `ert3 record load foo.USMRY` e.g., we would need parsing in ERT.

**Comment by xjules** [comment]
> I think the code responsible for the parsing of summary vectors should at least be peripheral, and a candidate for being a plugin. If we want to support `ert3 record load foo.USMRY` e.g., we would need parsing in ERT.

Yes, I agree that we need this (or similar) functionality, but the corresponding transformation should be then a plugin (as you hinted above). The issue being that transformations use transmitters ... or maybe not

**Comment by jondequinor** [comment]
> The issue being that transformations use transmitters ... or maybe not

But there's an indirection in the transmitter, the serialisation registry, that can be extended. And most likely made into a plug-in system later on.

**Comment by sondreso** [comment]
Continued in #2121 and #2123
