### ISSUE TITLE
Specify versions in install_requires

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#1999]
Most dependencies are without version-requirements.

Some are specified with the exact version, some with just a lower-bound and others with just an upper bound.

I propose we either specify lower bounds like done in for example [flask](https://github.com/pallets/flask/blob/main/setup.py), or we follow SemVer and for each package specify a range like `package >= 1.0.0, < 2.0.0`.

Thoughts?

**Comment by jondequinor** [comment]
What is the gain?

**Comment by dafeda** [comment]
> What is the gain?

When no versions are specified, we are saying that `ert` works with for example **all** versions of `numpy`.
This might of course be the case, but usually there's at least a lower bound.

A good read is [The Package Dependency Blues](https://blog.miguelgrinberg.com/post/the-package-dependency-blues).

**Comment by jondequinor** [comment]
I agree, but unlike Peter's _App_, we're actually distributing ERT with exact versions.

**Comment by dafeda** [comment]
> I agree, but unlike Peter's _App_, we're actually internally distributing ERT with exact versions.

Installing dependencies with `pip install -e .` might lead to a different environment than installing with, say, `pip install -r requirements.txt`.
I think this could lead to having internal distributions running on a different environment than what we use for development.

Since this is an open-source project, someone might use ERT as a reusable component, and not providing any lower-bounds might lead to the dependency blues. 

Probably not a major concern, but I think it's nice to be more explicit where we can.

**Comment by markusdregi** [comment]
I think it makes sense to specify the range of versions we are compatible with for each dependency.

As @jondequinor states, it might not be an issue when distributing in Equinor, as we build pinned version anyway. And I think we should continue doing that. But, as a project I think it would be good to provide at least lower bounds for the different dependencies we have.

**Comment by sondreso** [comment]
I vote for adding lower-bounds, but leaving the upper-bounds unspecified until we actually experiences issues with this.
