### ISSUE TITLE
"Export data" in GUI does not work

### ISSUE THREAD

**Issue by berland** [equinor/ert#2003]
**Describe the bug**
Workflow CSV_EXPORT2 tied to the "Export Data" button in the GUI fails to export anything due to wrong runpath file provided
to csv_export2.py

**To Reproduce**
1. Run experiment, sens_analysis_aps.ert from the tutorials folders (or probably any other)
2. Click "Export Data"
3. Click "Export" in the dialogue box

**Expected behavior**
CSV file exported to selected path.

**Screenshots**
![image](https://user-images.githubusercontent.com/306834/132186202-fe313d48-bf3e-4b6a-af1c-48044aa92eed.png)

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.09.rc1-py36 (and rc2-py38)
 - Remote/HPC execution involved: yes

**Additional context**

Error message in terminal window is:
```
2021-09-06 10:04:46,480 - fmu.ensemble.ensembleset - ERROR - Could not open runpath file .ert_runpath_list
The script 'CsvExport2Job' caused an error while running:
2021-09-06 10:04:46,481 - root - ERROR - Failed to execute CSV_EXPORT2
```

while the available filename is:
```
./output/run_path_file/.ert-runpath-list_sens_aps
```

**Comment by berland** [comment]
Reproducible in ERT 2.26.1 / komodo 2021.08.03.

**Comment by oyvindeide** [comment]
How is the runpath list file set in the config?

**Comment by berland** [comment]
`RUNPATH_FILE            ../output/run_path_file/.ert-runpath-list_<CASE_DIR>`

**Comment by oyvindeide** [comment]
Thanks! Found the cause, it has been hard-coded here: https://github.com/equinor/ert/blob/191b723c53e19f5c91b69ef41fb131ecdfb51eb3/ert_shared/exporter.py#L62
