### ISSUE TITLE
Remove transmit_data from the Transmitter

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2005]
Also, do some research to see if the pydantic pickling issue is solved and released.

**Comment by jondequinor** [comment]
https://github.com/cloudpipe/cloudpickle/issues/403 is the pydantic+cloudpickle issue

**Comment by sondreso** [comment]
I have looked into the cloudpickle issue, and I cannot reproduce this with cloudpickle 1.6.0 and pydantic 1.8.2 (everything on Python 3.6). However, I can verify that the change in https://github.com/cloudpipe/cloudpickle/pull/409/files is not included and that the tests introduced in that PR still fails. So my best guess is that something changed in Pydantic, such that this is no longer an issue. We also have tests that should capture this if it ever appears again.
