### ISSUE TITLE
hypothesis and pytest fixtures

### ISSUE THREAD

**Issue by vincent-lg** [equinor/ert#2006]
**Describe the bug**

Using pytest's fixtures of scope function with hypothesis doesn't work (on purpose).

I would like to have some code that runs before and after EVERY test function.  My use case, which is probably not that outlandish, is to reset an in-memory database object.  Yes, I would like to use hypothesis with a database.  It wouldn't be great testing if tests succeeded or failed based on what already is in the database, so I would like to clear it between tests.

Pytest fixtures do the job, I've used them several times.  But with `hypothesis`, there's an issue: since my tests use the `given` decorator, it might make sense to have fixtures using an additional scope.  In my case, I don't want the database to reset every time the function is called... but I do want it to reset when every function ends.

**To Reproduce**

1. In a `conftest.py` file, some simple fixture:

    ```python
    import pytest

    @pytest.fixture
    def db():
        print("Before db.")
        yield
        print("After")
    ```

2. Write a simple test in a separate file.  In my case, it's `test_account` and it refers to an external model, but that's easy to emulate:

    ```python
    @given(account=st.builds(Account))
    def test_create(account, db):
        data = account.dict(exclude={"id"})
        created = account
        assert created.dict(exclude={"id"}) == data
    ```

When running `pytest`, I get the following error:

```
...
E                               hypothesis.errors.FailedHealthCheck: test/test_account.py::test_create uses the 'db' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.  See https://docs.pytest.org/en/latest/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session for details on fixture scope.                                                                   
E                               See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.function_scoped_fixture to the suppress_health_check settings for this test.
```

So yeah, the error is verbose, there's a URL, but I couldn't get this fixture to work.  I tried to remove the `yield` keyword, to make it a normal function and add the finalizer to the request: no dice.  I actually tried to have this fixture do nothing and return something right away, no dice either, the error persists.  The documentation doesn't mention context manager (at least, I don't see it), so perhaps I'm missing something obvious.

So the first question is: why not?  The concept of scope, in particular function scopes, may be a little counter-intuitive when using `@given`, but then, it doesn't seem to cancel out the initial intent.  Obviously, having a scope of `module` or `session` doesn't solve my issue, since this fixture will run only once (per module, or per session test), which is not what I want.

**Expected behavior**

Considering the error is complete and explicit, I'd say this is the intended result.  What would be the best way to address my issue without breaking anything?

**Enviromment**
 - OS: win10 (64-bit)
 - Python version: 3.9

Thanks for this great tool!

**Comment by jondequinor** [comment]
I think you have filed an issue against the wrong project. Did you mean to file against hypothesis? This is ERT.

**Comment by vincent-lg** [comment]
Yes, a mistake on my part, I'm sorry for the inconvenience.
