### ISSUE TITLE
Introduce MetaRecord

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2009]
`MetaRecords` allows grouping of other `(Meta)Records`. This will create a hierarchy of `MetaRecords`, where all leaf nodes will be Records that contain data ([`NumericalRecords`](https://github.com/equinor/ert/issues/1731) and `BlobRecords`) 

This concept can be viewed as adding an extra dimension to the Record, but an important difference is that `MetaRecord` should be used where the axis of the grouped Records are not necessarily the same (I.e. adding them into a matrix instead of grouping them would result in a sparse matrix due to non-overlapping points on the axis).  

This solves several problems that we have in our code today: 
- Output from steps where the number of records are not defined up front, but we want to be able to export and use these in other parts of the pipeline (still as a group if we want to be able to reason about the flow of up front, and give the user feedback about inconsistencies). This is a common problem for Well related vectors in summery files.
- Parameter groupings (if these groups don't necessarily share the same sampling points) 
- Allowing different number of records in a group between realizations. (Frequent problem in optimization, as for example Well#3 might never be started for some realizations)  

Points that should be considered: 
- We want it to be possible to make groupings from other (groups of) records. We also might want to split (or at least extract) one part of the group. 
- We want to be able to export `MetaRecords` to and from all step types. 
- Transmitters should work on `MetaRecords` and `Records`. 
- We should be able to enforce restrictions on these `MetaRecords`. I.e. If the user want to link an observation to a specific part of a `MetaRecord`, we should be able to tell immediately after execution of that step whether that data was produced or not. (I.e history match against production data for Well#2). This could also allow that data to be individually passed on to other steps (instead of being a  part of the group)

We should design a interface for Records and `MetaRecords` first, i.e. define the desired behavior when using these concepts. 

Questions:
 - Should we have any constraints on the "sub-dimensions" of a `MetaRecord`, for example enforce that they have the same unit. (Consider a grouping of 3D matrices, do we want them all to be cubes in the same space (but not necessarily same points in that space)?) 

This could potentially also be merged with concept that we discussed earlier about using references to data instead of passing around the actual data. `MetaRecords` would then be define the hierarchy of Records, while the leaf nodes will always be pointers to either `NumericalRecords` or `BlobRecords`. (Then we could also make `MetaRecord` == `Record`, and avoid the potentially confusing name and focus on the interface of the `Record`)

**Comment by xjules** [comment]
Good start @sondreso ! I think that 
> We want it to be possible to make groupings from other (groups of) records. We also might want to split (or at least extract) one part of the group.

belongs quite likely into the desired features as this allows us to impose groupings directly on any data (obs, parameters, sim. results, ...) direct specification in the config for example:
```yaml
  input:
    -
      record: wopr:op_group_1
      group_mask:  WOPR:OP*
      # not sure about location
      location: wopr_op.json

    -
      record: wopr:op_group_2
      group_keys: WOPR:OP1 WOPR:OP2
     # not sure about location
      location: wopr_op.json
```

which also should create the leaf `Records` automatically for both cases. Naturally, such `MetaRecords` needs to undergo some validation wrt. above `Questions` section part (no strong opinion there, but my guess would be that such sub-dimensions should bear at least the same unit).

**Comment by xjules** [comment]
After the discussion with @sondreso I append the notes regarding the `MetaRecord` concept:

**Comment by markusdregi** [comment]
I'm think this is a good direction 😎 However, I think we should aim at a different name...

On the question of constraints I think requiring the same unit type would be highly beneficial for plotting etc.

**Comment by xjules** [comment]
Some comments from different discussions:
- We might need to form two types of `MetaRecords`, for `BlobRecords` and `NumericalRecords` respectively with the same API preferably
- Currently, we might not to impose any similarity among the sub-records contained within the `MetaRecord`, but we should be able to **inject**, **replace** or **remove** a sub-record from the `MetaRecord`
- Ex. `MetaRecord` of `BlobRecord` type: directory where each file is a standalone record while files can be added or removed when necessary. Use-case: Eclipse restart simulation files
- Ex. `MetaRecord` of `NumericalRecord` type: Summary vectors  where each exacted summary key is a standalone record 
- Until such concept is crystallized and also implemented in `ert-storage`, `MetaRecord` can be implemented as a numerical record with pointers or references to sub-records, where each sub-record is a "standard" record.
