### ISSUE TITLE
Importing ert-storage causing errors due to missing env-variable

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2012]
When testing api-compability , we need to set the ERT_STORAGE_DATABASE_URL first in order to avoid exception when importing the ert-storage module. Is it unfortunate that the dark-storage which should have no dependencies towards the new ert-storage needs to relate to this URL ( even if it is a dummy variable )?

**Comment by DanSava** [comment]
I think this will be solved by https://github.com/equinor/ert/pull/2018 right @dotfloat  ?

**Comment by dotfloat** [comment]
No. This issue should be in the ert-storage, and have the database connection be set during startup of the FastAPI app, rather than when the Python module is loaded.

**Comment by oysteoh** [comment]
I'm currently looking into this, forgot to move to `in-progress` :grimacing:
