### ISSUE TITLE
GUI crashed in detailed view

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2027]
**Describe the bug**
GUI crashed in the detailed view during a simulation that had been going on for a long (too long) time, effectively terminating ert.

**To Reproduce**
Not able to reproduce every time, fails with:
Traceback (most recent call last):
File "/path/to/env/site-packages/ert_gui/simulation/run_dialog.py", line 226, in <lambda>
viewer.finished.connect(lambda _, f=selected_file: self._open_files.pop(f))
KeyError: '/path/to/an/std_file/realization-x/iter-x/some_file.stdout.x

**Expected behavior**
Using detailed view should not stop the ert process.

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.08.03
 - Python version: 3.6
 - Remote/HPC execution involved: yes

**Comment by jondequinor** [comment]
@oyvindeide wasn't it concluded that this was most likely disk issues?

**Comment by oyvindeide** [comment]
I am not sure concluded is the right word, but it is not implausible at least. I think we should be robust to that though, and not tear down the entire process if that occurs, so add a `try ... except` or something.
