### ISSUE TITLE
Should webviz-ert be able to visualize relations between ensembles?

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2032]
In the new storage with the databases we have relations between ensembles. Should this also be possible when pulling data from EnkfMain?

**Comment by markusdregi** [comment]
I'm fine with that not being within the original scope; as it is not available today in the Qt-plotter nor a consistent concept in the implementation of ERT2. I'm thinking we can consider the ensembles to be a set of unrelated ensembles at first and then consider to extend later. This kind of relational data should probably be ok to store in an sqlite database if necessary down the road, as performance should not be an issue...

**Comment by oysteoh** [comment]
Nice! Then i'll just close this issue for now :+1:
