### ISSUE TITLE
Remove subprocesses from tests

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/ert#2044]
Not a bug, but more of an opinionated statement.
Subprocess should not be used in tests.
Why? Let there be a test that runs and asserts a subprocess has run correctly. Even though, it might have worked perfectly when it was implemented once it fails in the future (due to a feature or refactoring) we are unable to understand the reasoning for the failure(s) since what happens within the subprocess is a mystery to debug console.

**To Reproduce**
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. introduce a breaking change that causes a test carrying a subprocess (CLI).

**Expected behavior**
A failed subprocess test 
example: https://github.com/equinor/ert/blob/191b723c53e19f5c91b69ef41fb131ecdfb51eb3/tests/libres_tests/res/fm/test_rms_run.py#L281 (not the only one)

**Enviromment**
 - OS: Ubuntu 20.04
 - ERT/Komodo Release: main branch
 - Python version: 3.6.13
 - Remote/HPC execution involved: [no]

**Comment by markusdregi** [comment]
I'll add my two cents 🪙

The RMS test you are pointing at is testing the code as it is being consumed in the wild, namely as an executable. As such, it is more of a function / integration test. I think that is valuable, but I also agree that it does not make debugging easy. But that is not the job of a functional test. Instead, we should supplement these tests with unit tests...
