### ISSUE TITLE
Running HM tutorial and visualize from dark-storage

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2060]

**Comment by mortalisk** [comment]
We have done this with regards to performance. Looks good. Slightly slower than qt gui, but that is to be expected. But similar to what we saw in the planning demo on hm tut short. Ran in /scratch/fmu/mbend/r006/ert/model if anyone wants to look at the results.

It crashes when opening the already existing cases. But this is the same behaviour as the qt gui displays already.

**Comment by oysteoh** [comment]
Putting it into review - it is done as far as i'm concerned - but people can have a go if they want to running it! :+1:
