### ISSUE TITLE
Remove unused resources in ert_gui/resources/gui

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2078]
The html documentation in `ert_gui/resources/gui/help` is not used and very, very stale. Links to pages at Norsk Regnesentral, which hosted the ert documentation eons ago. These should be removed. 

The rest of the documentation found in the , `ert_gui/resources/gui/doc` should also be removed or made relevant again

**Comment by dafeda** [comment]
I can't find `ert_gui/resources/gui/help` and `ert_gui/resources/gui/doc`.
Am I missing something?

**Comment by sondreso** [comment]
This was fixed in https://github.com/equinor/ert/pull/2086, but the issue was not closed :slightly_smiling_face:
