### ISSUE TITLE
traceback in nominal shutdown of failling experiment

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#2081]
**Describe the bug**
There's a traceback in the output of ERT at the end of a failing experiment.

```
Simulations failed with the following error: Simulation failed!
1 jobs failed due to the error: Process exited with status code 1
2021-09-23 20:13:50,415 - ert_shared.main - ERROR - ert crashed unexpectedly
Traceback (most recent call last):
  File "/Volumes/equinor-dev/work/ert/ert_shared/main.py", line 415, in main
    args.func(args)
  File "/Volumes/equinor-dev/work/ert/ert_shared/cli/main.py", line 86, in run_cli
    _clear_and_exit(1)  # the monitor has already reported the error message
  File "/Volumes/equinor-dev/work/ert/ert_shared/cli/main.py", line 26, in _clear_and_exit
    sys.exit(args)
SystemExit: 1
ert crashed unexpectedly
```

Here's the output pre a806ee131820a979de168c22271d6fbc9d9dd866

```
Simulations failed with the following error: Simulation failed!
1 jobs failed due to the error: Process exited with status code 1
```

I see now that the logger produces this, because we want logging. But `ert_shared.main` and `ert_shared.cli.main` are not really talking to each other here. They are both doing `sys.exit` which might be not optimal.

/cc @oyvindeide

**To Reproduce**
1. `pip install ert`
2. `ert test_run test-data/local/failing_poly_example/poly.ert`

**Expected behavior**
Clean shutdown

**Enviromment**
 - OS: RHEL7 and macOS
 - ERT/Komodo Release: main
 - Python version: 3.8
 - Remote/HPC execution involved: no

**Additional context**
Assumption here is that the traceback is confusing and not really conveying any useful information to the user.

**Comment by oyvindeide** [comment]
I agree that in that case we should not have a traceback. We should not really raise `sys.exit()` outside the main entry point though, and know this was implemented when they were not part of the same entry point. So suggest we instead raise a different exception and catch that in the main entry point to avoid this instead of catching `sys.exit` in the main entry point.

**Comment by oyvindeide** [comment]
Something like this: https://github.com/equinor/ert/pull/2082

**Comment by jondequinor** [comment]
Yeah, very good. Will take a closer look tomorrow.
