### ISSUE TITLE
Raise error in start_ert_server contextmanager

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2085]
Would it be useful to raise a `RuntimeError("Unable to start server...")` or something like that before the `yield`?

That way we could avoid getting an "ert crashed unexpectedly" when we know that we were unable to start the server.

https://github.com/equinor/ert/blob/1cd0bb65fe8853d0253e6b26eaa289f602835fbf/ert_shared/main.py#L388-L401

**Comment by BjarneHerland** [comment]
Looks like the situation has changed since this issue was reported and IMHO this does not seem to be a problem anymore.

https://github.com/equinor/ert/blob/2200b0d79ba2f36944af9a07f2391d53fd865066/ert_shared/main.py#L428-L461

 Suggesting to close this.

**Comment by ManInFez** [comment]
After refactoring of starting ert services this is a wont fix
