### ISSUE TITLE
Cache libres in Github Actions

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2087]
It takes a while to compile libres, which is especially annoying when it rarely changes. We could use Github Actions' caching functionality to recall the compiled binaries, and recompile if they've changed.

1. Find the commit hash for the `libres/` directory
2. Fetch the caches. Check if `libres-{hash}.zip` exists
    1. If it does, extract and put somewhere where ERT can use it
    2. If it doesn't, compile and cache it

**Comment by oyvindeide** [comment]
It is not really true that libres (now ert) rarely changes, so I will close this as it is not that relevant anymore.
