### ISSUE TITLE
`Error message: state_map_iset__: illegal state transition for realization: x`

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/ert#2088]
**Summary of investigation after observing `Error message: state_map_iset__: illegal state transition for realization:91 16 -> 8` during `ensemble_experiment`:**

1) An `ert es_mda` run (`iter-{0,1,2,3}`) was successfully executed with 100 realizations, with some failed realizations (which is normal).
     - One of these failed realizations was realization 91, which did not successfully complete `iter-1` (failed during Eclipse simulation).

2) In a (prediction) `ert ensemble_experiment` following the `es_mda` run, realization 91 is expected to fail (since there is no `iter-3` to use as starting point for the realization).
    - What is unexpected behavior though is that when realization 91 (as expected) fail, this also crashes the ERT client with:
    ```
    Error message: state_map_iset__: illegal state transition for realisation:91 16 -> 8 

    See file: /tmp/ert_abort_dump.username.YYYYMMDD-HHMMSS.log for more details of the crash.
    Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
    Aborted (core dumped)
    ```
---

After some test runs, this appears to be related to ERT storage. When the `es_mda` run is finished, there have been automatically created "cases" called `default_{0,1,2,3}` in ERT storage. When the (prediction) `ensemble_experiment` is started afterwards (using same storage path in the configuration file), it looks like default chosen case by ERT is `default_3` (the last generated case by ERT in `es_mda`). Either deleting ERT storage between `es_mda` and the following `ensemble_experiment`, use different ERT storage paths in the two ERT config files, or alternatively create + use a new "case" different from `default_*` in the ERT GUI, removes the crash / error message.

---

**Conclusion with current information:**
* _Workaround for user:_ Delete ERT storage between `es_mda` and `ensemble_experiment`, use different ERT storage paths (i.e. value for `ENSPATH`) in the two ERT configuration files, or create a new ERT case in ERT GUI before (prediction) ensemble experiment.
* _Potential ERT bug fix:_ Do not by default reuse `default_*` from previous `es_mda`run when subsequently starting an ensemble experiment.

**Comment by jondequinor** [comment]
Another potential bugfix is to obtain a proper _mask_ for the `run_context` that is created in this case.

**Comment by oyvindeide** [comment]
Think this might be solved already, but need to double check

**Comment by oyvindeide** [comment]
Related to: https://github.com/equinor/ert/pull/4574

**Comment by mortalisk** [comment]
The abort in question is this one: https://github.com/equinor/ert/blob/a9092929ef81bb525f044762c6e59c3a36dffb36/src/clib/lib/enkf/state_map.cpp#L99-L101

**Comment by oyvindeide** [comment]
This no longer crashes, but instead keeps the failed parent realizations as failed. Will close this as completed.
