### ISSUE TITLE
Replace the package `ansicolors` with `colorama` or something similar

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2089]
The package [ansicolors](https://pypi.org/project/ansicolors/) is not actively maintained, supports only up to Python 3.6, and is specified with a specific version in our `setup.py`:

https://github.com/equinor/ert/blob/9f9f75124b93ba5fa9114c4bcc9da985b4228e85/setup.py#L72

Should be replaced with something more actively maintained, for example [colorama](https://pypi.org/project/colorama/).

**Comment by dafeda** [comment]
Looked into `colorama` a bit, but it seems not trivial to use with colors defined as `COLOR_WAITING = (164, 200, 255)` for example.
Also, not sure if it's a bad sign that the project has not seen changes in years since what it does is pretty straight forward.
I suggest closing this issue.
What do you think @jondequinor ?

**Comment by jondequinor** [comment]
The ansi sequences are from the 70s. And they're pretty static, so I'm not sure how big of a problem it is :)

**Comment by dafeda** [comment]
Thanks, I agree 👍
