### ISSUE TITLE
Stop logging to stdout

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2096]
As we are adding logging statements for `WARNING` and above these will show up on `stdout`, we might want to remove this handler so we dont pollute `stdout` with information that is useful to log, but not that useful to the user.

https://github.com/equinor/ert/blob/f79b4a294288429956cd932d8b39e06cf4d8fd9d/ert_logging/logger.conf#L10

**Comment by dafeda** [comment]
From what I can gather, a `KeyboardInterrupt` would raise `ErtCliError` if `model.hasRunFailed()` is `True` at that point in time.

I've tried running and killing the command line below, and `model.hasRunFailed()` is set to `False`, which means no `ErtCliError`.

```console
ert test_run test-data/local/poly_example/poly.ert
```


https://github.com/equinor/ert/blob/5a5f2446b3347b082f7616eeb5ca771ea38a8cd0/ert_shared/cli/main.py#L73-L86

**Comment by oyvindeide** [comment]
But if I add:         
```
logger = logging.getLogger(__name__)
logger.exception()
```
at any time in the call stack (for example https://github.com/equinor/ert/blob/5a5f2446b3347b082f7616eeb5ca771ea38a8cd0/ert_shared/cli/main.py#L76)  I still get a traceback, so in case someone logs an exception somewhere else it should not be printed to stdout.
