### ISSUE TITLE
Documentation - SIMULATION_JOB

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2111]
[SIMULATION_JOB](https://ert.readthedocs.io/en/latest/reference/configuration/keywords.html#simulation-job) is in the [List of Keywords](https://ert.readthedocs.io/en/latest/reference/configuration/keywords.html) defined as:

"Experimental alternative to FORWARD_MODEL."

In [reference/configuration/forward_model](https://ert.readthedocs.io/en/latest/reference/configuration/forward_model.html#the-simulation-job-alternative) we write that:

"The difference between FORWARD_MODEL and SIMULATION_JOB is in how commandline arguments are passed to the final executable."

I've got two questions.

1. Is it still experimental?

2. When and why should I use one over the other?

**Comment by dafeda** [comment]
Write-up by @markusdregi 

The very short summary is that:
as Åsmund states above, SIMULATION_JOB is a lightweight version of FORWARD_MODEL that does nothing but allowing you to point to an executable and allow you to pass raw command line arguments to that executable,
it is heavily used in Everest (the Everest configuration transpiles all jobs into SIMULATION_JOB) and
it was introduced simultaneously as an experimental feature in ERT.
The major issue on this is that while you can write my_executable --with-super-argument in the Everest configuration and all is good, the ERT configuration will immediately interpret the later part of such a command (SIMULATION_JOB my_executable --with-super-argument ) as a comment. Which mutes a large part of the idea of getting closer to the command you would write in the terminal on behalf of ERT.
The unix step in ERT3 is built on similar thoughts, but in that configuration (being YAML) you can write command line arguments in all their flavours and be able to avoid ending up with a lot of comments…
We can’t remove SIMULATION_JOB without doing quite some work in the Everest - ERT interaction. We can label it as not experimental anymore, but the biggest carrot of the keyword is not easily realisable in ERT2 configuration :shrug:

**Comment by markusdregi** [comment]
As I see it, we have the following options:
- keep it as an experimental feature for the lifetime of ERT2,
- remove the feature entirely,
- raise the quality to something we would not consider experimental,
- remove it from the documentation, but keep the implementation.

The factors impacting this is listed in the comment above. My conclusion based on this is as follows:
- the first alternative is an easy way out, it requires no work and we just proceed with other things. It does however come of as a bit odd.
- the second alternative dictates quite some work to keep Everest alive. In my opinion, more work than it is worth given the current direction of the projects.
- the third alternative is also quite work intensive and in addition it is not clear how to keep compatibility with the comment syntax and still harvest the carrots of the feature. In addition, it is a nice-to-have feature in ERT2, so I would question how large adoption it would get, even if completed.
- the last alternative can be seen as an extension of the first. We keep the implementation for Everest purposes, but decide that we don't really recommend users using the keyword directly. So, we move the documentation of the keyword out of the user documentation and into the code and simultaneously remove the usage of the keyword from our examples.

I'm leaning towards the first or last alternative 🤷🏻

**Comment by dafeda** [comment]
I'm leaning towards the first alternative, but perhaps we should update the documentation a bit.
Perhaps write that it is used in Everest etc.?

**Comment by markusdregi** [comment]
But the fact that it is used by Everest is probably not useful information for a user reading the documentation?

**Comment by dafeda** [comment]
> But the fact that it is used by Everest is probably not useful information for a user reading the documentation?

I agree, but I think the information should be somewhere to reduce the risk of fellow developers pondering this very same question in the future.

**Comment by markusdregi** [comment]
I agree! But perhaps that is better left in documentation within the code? 🤷🏻

**Comment by dafeda** [comment]
> I agree! But perhaps that is better left in documentation within the code? 🤷🏻

That makes sense, thanks.
I've tried finding a good place to put a description and this is what I came up with:

https://github.com/equinor/ert/pull/2754
