### ISSUE TITLE
Remove ci/jenkins/testkomodo.sh

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2136]
Currently the testkomoo.sh is being used in the komodo-release testing pipeline on KOMODO-jenkins. the ci-pipeline for PRs are using the three other scripts in ci/jenkins. When the job has been split up on the KOMODO-jenkins we can delete this file

**Comment by berland** [comment]
Superseded by https://github.com/equinor/komodo-releases/issues/3768
