### ISSUE TITLE
Mark test_engine:test_gaussian_distribution as flaky

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2140]
The test found here:

https://github.com/equinor/ert/blob/37568cf79f8fa0ec7039cee672428b1d97068b65/tests/ert_tests/ert3/engine/integration/test_engine.py#L290

is acting flaky. We should reconsider of testing the values coming out of the distribution is a good idea. Values are created with `scipy.stats` module should not be required to test in our code.

**Comment by sondreso** [comment]
Related to https://github.com/equinor/ert/issues/1231

**Comment by BjarneHerland** [comment]
See https://github.com/equinor/ert/pull/2209 for a proposal
