### ISSUE TITLE
Mature and implement the notion of a workspace

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2168]
**Introduction**
There is currently a notion of a _workspace_ that is used in both social discussions and code related to ert3. The concept is in dire need of being matured and implemented accordingly in code.

**A suggested definition of a workspace**
I view the workspace as the working area for which ERT3 setup and input data resides. In particular, the ert3 examples would be two different workspaces:
- https://github.com/equinor/ert/tree/main/ert3_examples/polynomial
- https://github.com/equinor/ert/tree/main/ert3_examples/spe1

As of such, ert-storage is not part of the workspace, while the (future) configuration indicating which storage instance is used is part of the the workspace.

As of such, the workspace is currently presented at a file system by files, directories and their layout.

**Codification**
There currently exists an `ert3.workspace` module that presents a very small set of the reasoning done over the workspace (see https://github.com/equinor/ert/tree/main/ert3/workspace). However, the logic of the current layout of the configuration files, their names etc is not implemented in the workspace, but within the cli when loading the configuration files. I suggest that we move towards an implementation where `ert3.workspace` provides an abstraction over the file system such that the knowledge of the configurations stemming from files, how they are organised and named all is encapsulated within this module. The remaining `ert3` implementation should not inspect the file system for configuration.

**Remarks**
Notice that by the above definition https://github.com/equinor/ert/blob/9cfb07b5d3020d3e6c88bffe5d7ec7058dadf9cd/ert3/workspace/_workspace.py#L45
the workspace should not be able to indicate whether an experiment has already been ran, as that is the responsibility of `storage`, possibly together with `engine` do decide.

**Comment by sondreso** [comment]
Remaining work is documented in #2418, #2419 and #2420
