### ISSUE TITLE
Validation of ERT3 configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2169]
**Introduction**
ERT3 configuration is a complex endeavour that we must take seriously such that our users are able to use our tool.
Currently there are Pydantic schema's that validates the content of the individual files. However, there is no cross validation between the different files. For instance there is no validation on that the configured forward model stage in `ensemble.yml` actually exists in `stages.yml`. This and other similar cases should be validated.

**Thoughts**
- Validation that can be done before launching an experiment should be possible to do up front to validate a setup before launching
- Validation should have no side effects
- A user configuration error should not be possible to interpret as a bug when communicated and vice versa
- We should provide as many configuration errors as possible. That is, we should not only present the first error discovered, but strive to accumulate an as extensive list as possible.
- Since user configuration is complex, we should aim at the schemas for validation are also possible to use for generating documentation.

**User experience - cli**
I would like to validate an experiment through the cli via something along the lines of `ert3 validate my_experiment`. I expect this command to have no side effects! And to provide me with an as extensive list as possible of configuration error. That is, if ERT later errors before starting the forward model and it is not an infrastructure failure, it should have been picked up already by the validation.

**User experience when running**
When launching an experiment I would like ERT to do similar validation as above such that any configuration error that can be discovered up front is communicated to me as a user before any actions that have side effects are carried out.

**Responsibility of validation**
While preserving the above functionality, it is not immediately clear that the entirety of validation should happen within the schemas. For instance, when introducing a `composite stage` (see https://github.com/equinor/ert/discussions/2162) a DAG of data flow will be described for which the best entity to validate is perhaps the ensemble builder. This responsibility needs to be handled in a reasonable manner while still ensuring a good experience for our users.

**Comment by sondreso** [comment]
I think we can consider this issue done after https://github.com/equinor/ert/pull/2433 was merged, and while there are aspects if this issue that are up for discussion it is not very actionable at the moment. We should rather open specific issues if there are aspects with the configuration validation that we would like to improve.
