### ISSUE TITLE
Set "ITER" from workflow

### ISSUE THREAD

**Issue by ttekttek** [equinor/ert#217]
Currently it is possible to set the iter number from the workflow RUN_SMOOTHER_WITH_ITER. It would be very good to have it accessible either as a workflow job "SET_ITER" or "ENSEMBLE_RUN_WITH_ITER".

I will use it to test and screen different observations sets and scalings without overwriting the runpath everytime (without explicitt chaning the runpath). I can also think of other applications, and think it will be useful for others.

**Comment by markusdregi** [comment]
I suggest we add this to the CLI and try to use cli in a bash script to cover this functionality instead.

**Comment by markusdregi** [comment]
Moved to #1575
