### ISSUE TITLE
Improved configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2173]
This milestone aim at multiple improvements related to ERT3 configuration and it's surrounding concepts and implementation. The total work is covered by the following epics:
- https://github.com/equinor/ert/issues/1924
- https://github.com/equinor/ert/issues/2170
- https://github.com/equinor/ert/issues/2169
- https://github.com/equinor/ert/issues/2168

**Comment by sondreso** [comment]
Most of the issues in this milestone have been completed, and the current direction of ert3 also means that https://github.com/equinor/ert/issues/1924 will be pushed to the backlog and should rather be part of a new configuration effort later. Hence, this milestone is closed!
