### ISSUE TITLE
Implement CSV_EXPORT job

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2190]
Extract data from the storage API to replicate how CSV_EXPORT2 writes its data.
Important to keep the current format unless good reasons for doing something else.
The result of the extraction should be equal both when storage api is backed by new storage and by dark storage.

**Comment by frode-aarstad** [comment]
I am not able to find any references to CSV_EXPORT3. I do find CSV_EXPORT2 though ..

**Comment by oysteoh** [comment]
Yes, it is CSV_EXPORT2 which is used in ert ( through semeio ). My bad.

**Comment by sondreso** [comment]
Closing this in favor of https://github.com/equinor/ert/issues/3423
