### ISSUE TITLE
Fetch casename from storage api

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2193]
In the qt plotter, retrieving casenames should be backed by storage api ( ensemble names )

**Comment by perolavsvendsen** [comment]
Will such an API be available to others? E.g. sub-processes ran in workflows and/or forward jobs? I guess what I am asking is if solving this may give some progress on #2359?

**Comment by frode-aarstad** [comment]
I think that should be possible and a good use-case for it. The main motivation for this is making the data currently stored on shared disk more accessible. Perhaps @oysteoh has any thoughts on this ?

**Comment by DanSava** [comment]
Resolved by #2835
