### ISSUE TITLE
The capability of plotting refcase should be preserved

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2197]
Currently the refcase is plotted in the qt plotter, but is not available in new storage. We should get the data from the refcase.

**Comment by oysteoh** [comment]
Before making a decision regarding how to proceed with this, we need to document following: 
- What data is plotted from the refcase ( i.e what data do we get when retrieving the refcase )
- Does it have it's own api? If so - where is it located?

**Comment by oysteoh** [comment]
Alternatives currently could be 
- Not doing anything with the refcase and leave it as is (retrieve data the "old" way)
- Extend the API to also handle refcase. If so - we also need to do the same for the api on top of new storage and with that also move the concept of refcase into our new stuff
- Incorporate refcase in to our current api / datastructures as a normal realization / ensemble and with that be able to expose it and plot it. 


@sondreso and @markusdregi  please provide insight and opinions if you have any.

**Comment by frode-aarstad** [comment]
Part of this should also be to replace the following function calls in plot_api

`self._facade.refcase_data(key)`
`self._facade.has_refcase(key)`

**Comment by oysteoh** [comment]
> Part of this should also be to replace the following function calls in plot_api
> 
> `self._facade.refcase_data(key)` `self._facade.has_refcase(key)`

And with this - you are then referring to the pyqt plotter which loads data and then for each entry it goes back and ask what type of data it is right? So - by adding some metadata to our response in the API this could be avoided? And - this should be discussed as well together with the refcase-issue as it will cause the pyqt-plotter to force changes in our API which we might not want to have ?

**Comment by oysteoh** [comment]
With the meeting today, we concluded following:
- Plotting of the refcase to be removed in pyqt-plotter
- Preserve the functionality adding historical vectors for a key when plotting
- Functionality extracting the history vectors should be adjusted in the dark-storage. For a key - it can either be retrieved from it's realization ( then it has to be internalized through the config-file ) or from it's refcase. We should change our api always to serve a historical vector for a key if it exists in either refcase or realization. ( This is especially to have backwards-compability to old cases where they haven't internalized the historical vector and depends on it being retrieved from refcase ) 
- By changing the way of retrieving historical vectors to always add one pr realization ( usually this will be the same vector across all realizations, but in rare cases it could also be different ), we could/should (depending on how it performs) check if all the vectors are the same and then only plot one of them.
 
@sondreso - is this in line with your summary of the discussion?

**Comment by sondreso** [comment]
Yes, this is very good summary :+1:

**Comment by oysteoh** [comment]
Added 
- https://github.com/equinor/ert/issues/3297
- https://github.com/equinor/ert/issues/3298
- https://github.com/equinor/ert/issues/3299
