### ISSUE TITLE
ert3 service check storage - print something when successful 

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2199]
Running 

```console
$ ert3 service check storage
```

prints `ERROR: Ert storage not found!` when unable to connect but nothing when it successfully connects.

Probably a better user experience if we print something at success.

**Comment by sondreso** [comment]
What are the exit codes in the two different scenarios? 🤔

**Comment by jondequinor** [comment]
```
ert3 service check storage
(trapper) jonas@x:ert$ echo $?
0
```

So I would say this is behaving as expected.

**Comment by jondequinor** [comment]
> Are you saying that it's not necessary to write a message to console?

Yes, `check` to me indicates that it could be used in a test in a script. 

You haven't described what you'd like the message printed on stdout to be, but if you're looking for connection information, I think I would like something like `ert3 service ls storage` instead.

Sort of like `git ls-remote upstream` (`ls`) and `git ls-remote upstream --exit-code` (`check`).
