### ISSUE TITLE
Activate or deactive individual observations within an obs node of type GEN_OBS

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#2215]
**Wanted feature:**
For observation node of type GEN_OBS, there seems not to be any functionality to select a subset of the N observation data for this observation node. The only workaround I see (but that may be wrong) is to write the selected subset of the GEN_OBS nodes observation data to file and create a new GEN_OBS node from file.

**Use case:**
Let say we have spatially distributed observations not coming from wells. One example could be timelapse gravimetry data or other geophysical data where it is feasible to calculate a scaling factor field for each combination of observation and a FIELD parameter and use the row_scaling functionality for this. This implies that one new 'ministep' in the localisation setup is created for each observation so this approach is not feasible for large number of observations (e.g. seismic data), but for more moderate set of observations in the GEN_OBS node.

**Implementation:**
New methods for the GEN_OBS type to activate or deactivate individual observations could be implemented in the GenObservation class.
Typical use within localisation setup will then be:
1. Get a list of all observation keys from ERT instance.
2. For a given correlaton group ('ministep'):
   Create a new observation group using  e.g. obs_group=ert_local_config.createObsdata(obs_group_name)
   Selected observation key with type GEN_OBS type to be used.
   Get the obs node. Select the relevant timestep to be active.
   Set the relevant observation within the GEN_OBS node (specified obs indices) active and the rest of the obs inactive)
   Add the observation node with a subset of its observation data active to the obs group:
       obs_group.addNode(key,timestep)

The new methods (feature) is connected to "Set the relevant observation within the GEN_OBS node active or inactive"

Alternative workaround:
Get the GEN_OBS node and get the observation(s) values and std from it to be used. Write it to file and create a new GEN_OBS node from the file that was written to disk.

**Comment by oyvindeide** [comment]
Seems this has been solved, so will close this issue.
