### ISSUE TITLE
Have BaseService delete _server.json during SIGTERM

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#2259]
**Steps to reproduce:**
1. Start `ert api poly.res` (or your favourite ERT config)
2. Observe that the file `storage_server.json` exists in the current working directory
3. Kill ERT's process ID with SIGTERM (use `ps ax | grep ert` to find the ID; use `kill <ID>` to kill with SIGTERM)
4. Observe that the file still exists

**Possible reason:**
The signal is only caught by Python, which immediately shuts down. This jumps out of the normal shutting-down routine of BaseService

**Possible solution:**
Use the `atexit` module to register an exit function which deletes this file. Iirc, functions registered with `atexit` are called even in the event of a signal handling. Note that with this solution, we'll need to make sure that we don't accidentally delete another process' `_server.json` file:
```py
with Storage.start_server() as session:
    do_stuff(session)
# `storage_server.json` is deleted here by normal means
do_more_work()
# Another process make Storage
sys.exit()  # Oops, we registered a function which deletes that other process' `storage_server.json`
```

**Comment by DanSava** [comment]
Did not get a chance to finish this up before I started my vacation. I am putting it back in todo for now if somebody else wants a crack at it.
