### ISSUE TITLE
Review the function calling pattern in enkf_main_smoother_update

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2267]
There are many cases of functions calling a slightly differently named function with slightly different parameters, we would like to move this information up in the stack.

An example could be found here: https://github.com/equinor/ert/blob/a7a4f7ed0760f06091bf2e52e2d483409e5d3c6d/libres/lib/enkf/enkf_main.cpp#L1278

**Comment by jondequinor** [comment]
Any conclusion to this?
