### ISSUE TITLE
Move the notion of storage out of the workspace module

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2275]
Currently the workspace module use storage to check if an experiment has been run or not. This should be moved out of the workspace module, as the workspace should not have knowledge about the state in storage.

**Comment by verveerpj** [comment]
I have made a pull request to remove the function that uses storage to check if an experiment has run (PR #2311). However, the storage is also initialized in the workspace module:

https://github.com/equinor/ert/blob/fb623eb3f5c36598c73c0b10fdea3b9f7a1f190c/ert3/workspace/_workspace.py#L50-L58

Maybe we should also do that elsewhere? I.e. maybe that should be the responsibility of whatever code initializes the workspace.
