### ISSUE TITLE
Deactivate report steps for GEN_DATA

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#228]
**Task**
Today, a single or multiple report steps are provided to the definition of GEN_DATA. This is an unused feature (due to complexity) that should simply be removed. In addition it appears to have been broken for quite some time.

I suggest that we implement and utilize the schema of #218 on this one.

**Related issues**
Needs #218.
Relates to #193.

**Comment by oyvindeide** [comment]
Think we probably should refactor this, but it is working and is actively used in the GENDATA_RFT job. Have added it to our current TODO, but think the result might be that we just close this issue.

**Comment by oyvindeide** [comment]
Report steps work in ert, and are tested as part of the test suite. I will close this issue, as changing the report steps are part of a broader issue.
