### ISSUE TITLE
ActiveList method addActiveIndex fails to return correct error message when called by invalid argument

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#2289]
ActiveList method addActiveIndex fails to return correct error message when called by invalid argument. I applied the function within a localisation script. The following error message was reported:
"The script LocalisationConfigJob caused an error while running: ArgumentError object has no attribute message. "

**Comment by pinkwah** [comment]
The `ArgumentError object has no attribute message` is a cwrap error that hides the actual error message.

What do you mean by "invalid argument"? Wrong type or incorrect data?

**Comment by oyvindeide** [comment]
Related to: #5694 , will close
