### ISSUE TITLE
Incomplete documentation 

### ISSUE THREAD

**Issue by TerryHannant** [equinor/ert#2298]
**Describe the bug**
Key concepts page in documentation is not complete

**To Reproduce**
1. Go to https://ert.readthedocs.io/en/latest/getting_started/key_concepts.html
2. Check concepts sections, Each one only contains a TODO

**Expected behavior**
A clear and concise description of each concept is included

**Comment by kwinkunks** [comment]
I think we might also want to move this glossary page out of the **Getting started** part of the user guide and into a more Reference-oriented part of the docs. (If we even keep it, I guess it's not that highly sought after.)

The best approach might be to simply define these components as they arise in the user guide. A person can always search for occurrences to find them. Something to discuss when we have the content.

**Comment by eivindjahren** [comment]
There has been a lot of work done on the documentation and the links referenced here are now broken because everything has been reorganized. Additionally, I cannot really find any parts of the documentation that contain any TODO flags any longer so I am closing this issue.
