### ISSUE TITLE
ert documentation section Architecture/Communication Protocol is not understandable

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#2314]
**Describe the bug**
In the ert documentation, the section [Architecture/Communication Protocol](https://fmu-docs.equinor.com/docs/ert/architecture/communication_protocol.html) is not understandable

**To Reproduce**
Look at https://fmu-docs.equinor.com/docs/ert/architecture/communication_protocol.html

**Expected behavior**
Visually pleasing documentation

**Comment by eivindjahren** [comment]
We could also change the issue to missing documentation of the communication protocol. The narratives portion went away with the need to change the protocol. Maybe you could shine a light on this @lars-petter-hauge .

**Comment by lars-petter-hauge** [comment]
Technically it was the fact that we are elevating when we are using `asyncio` (https://github.com/equinor/ert/issues/3948), and the implementation of `Narratives` where not async. We have an issue on introducing a different tool contract driven testing https://github.com/equinor/ert/issues/4275. The possibility of auto-generating docs could be used to decide which tool to use. I'll update the linked issue

**Comment by sondreso** [comment]
Narratives are not longer part of ERT and the documentation mentioned in the issue is also removed 🙂
