### ISSUE TITLE
Introduce templates to Transmitters

### ISSUE THREAD

**Issue by xjules** [equinor/ert#2320]
Currently, in record transmitters we differentiate whether a given record is of a specific type just by using data type or by `isinstance` method (ie. `BlobRecord`, `NumericalRecord`). If we are to introduce new Record type (`MetaRecord` https://github.com/equinor/ert/issues/2009) this would further branch the transmitters. Therefore we should instead introduce templates into `RecordTransmitters` in the following way:
```python
class RecordTransmitter(Generic[record_class]):
...
    async def load(self) -> record_class:
        pass

    @abstractmethod
    async def transmit_record(self, record: record_class) -> None:
        pass
```

**Comment by jondequinor** [comment]
Can you explain the difference between this and the current implementation? The mentioned methods all operate on the abstract base class `Record` e.g. https://github.com/equinor/ert/blob/main/ert/data/record/_transmitter.py#L81

**Comment by xjules** [comment]
> Can you explain the difference between this and the current implementation? The mentioned methods all operate on the abstract base class `Record` e.g. https://github.com/equinor/ert/blob/main/ert/data/record/_transmitter.py#L81

Sure, the idea is to introduce a generic Type (including here the RecordStore), eg. 
```python
record_class_type = TypeVar(
    "record_class_type",
    BlobRecord,
    NumericalRecord,
    RecordStore[numerical_record_data],
    RecordStore[blob_record_data],
)
```
Please note the difference between using type Union `record_class_type = Union[BlobRecord, NumericalRecord, RecordStore[numerical_record_data],  RecordStore[blob_record_data]]`, where `TypeVar` is a template meaning `exclusive or` where `Union` is `either or`. This would require to create a dedicated transmitter for each of types in `TypeVar`, eg. 
```python
class BlobRecordTransmitter(Transmitter[BlobRecord]):
    async def load(self) -> record_class_type:
        ...
    async def transmit_record(self, record: record_class_type) -> None:
        ...
```
We thought it would make verification much easier, but it's up for discussion.

**Comment by Blunde1** [comment]
[Relevant pep on scope](https://www.python.org/dev/peps/pep-0484/#scoping-rules-for-type-variables)
Since the transmitter class is Generic on `record_class` (T) all enclosed methods will have to be of the same type. The way I see it, this is really the difference between `Union` and `TypeVar` in this case. This is more strict, but perhaps exactly what we want and actually a good thing?

**Comment by eivindjahren** [comment]
This is no longer a class in ert. If there is some other class that needs templates we can just open a new issue for it.
