### ISSUE TITLE
Validate input that comes as resources from the workspace when loading the experiment

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2330]
Some of the input types that can be specified in the ensemble config are coming as resources from the workspace. These should be validated when the experiment is loaded.

**Comment by verveerpj** [comment]
I am a bit unsure what needs to be validated. We can check that the file/directory exists in the resources directory. That should be done in the workspace, since at the ensemble config we don't want to know yet that these are files/directories. Anything else?
