### ISSUE TITLE
Move package_data to ert module 

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#2345]
**Describe the bug**
`package_data` added to `ert` should reside within the module itself, is now added to a separate package `share` (see `package_data` in `setup`, the `key` here refer to the module name)

**To Reproduce**
1. `pip install ert`

**Expected behavior**
Expected package_data to reside in the `ert` package.

**Comment by dafeda** [comment]
Why do we want `share` to be under `site-packages/ert`?

Not sure why we need `share` at all. Who are we sharing with?

Do we want for example `ert3_examples` to go under `site-packages/ert` as well?

```python 
    package_data={
        "share": share_files,
        "ert_gui": extra_files,
        "ert_logging": logging_configuration,
        "ert3_examples": ert3_example_files,
        "res": [
            "fm/rms/rms_config.yml",
            "fm/ecl/ecl300_config.yml",
            "fm/ecl/ecl100_config.yml",
        ],
    },
```
