### ISSUE TITLE
Investigate memory usage

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2353]
We should try to get an overview of how much memory is required for real users so we can determine if we need to do lazy loading at all.

**Comment by sondreso** [comment]
What are we considering to lazy load? 🦥

**Comment by oyvindeide** [comment]
In this case we are talking about the analysis module and what to keep in memory versus disk. And if we need all the additional steps that are there today.

**Comment by BjarneHerland** [comment]
I'll give this a shot

**Comment by BjarneHerland** [comment]
A variation: Perhaps it's more elegant to introduce our own global, singleton logger for C++ which just fwds to the Python logger? Avoiding the need to pass a callback-function in each C++ call as demonstrated in https://github.com/equinor/ert/pull/2500

Input?

**Comment by BjarneHerland** [comment]
Leaving this for now as agreed - feel free to pick up and contact me for details.
