### ISSUE TITLE
Remove unused parameter `dbg`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2361]
```dbg``` parameter is unused and can be removed from ```ies_enkf_linalg_extract_inversion```, ```ies_enkf_linalg_extract_active_A0``` and ```ies_enkf_linalg_store_active_W``` functions

https://github.com/equinor/ert/blob/ee9028aa05c17acfa1f81f97d40801c5cd5b623a/libres/lib/analysis/modules/ies_enkf.cpp#L636

https://github.com/equinor/ert/blob/ee9028aa05c17acfa1f81f97d40801c5cd5b623a/libres/lib/analysis/modules/ies_enkf.cpp#L684-L711

https://github.com/equinor/ert/blob/ee9028aa05c17acfa1f81f97d40801c5cd5b623a/libres/lib/analysis/modules/ies_enkf.cpp#L716-L718

**Comment by sregales-TNO** [comment]
Can I get a further description, of things such as, why we are removing this ```dbg``` argment?

**Comment by dafeda** [comment]
The `dbg` argument is not used in the function, so I thought we might as well remove it.

**Comment by sregales-TNO** [comment]
simple enough
thanks
