### ISSUE TITLE
Update how shared resources are resolved in ert 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2368]
**Describe the bug**
The way ert discovers the share path is not robust, and after https://github.com/equinor/ert/commit/fb623eb3f5c36598c73c0b10fdea3b9f7a1f190c we could use https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data. This should be updated: 
https://github.com/equinor/ert/blob/5e7605ab46a7ff075835e64f62de0dc994d845b2/ert_shared/hook_implementations/jobs.py#L10-L21

**Expected behavior**
Shared resources are fetched in a more robust way.

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: main
 - Python version
 - Remote/HPC execution involved: no

**Comment by lars-petter-hauge** [comment]
Note that https://github.com/equinor/ert/issues/2345 should be fixed first

**Comment by oyvindeide** [comment]
Changed in: https://github.com/equinor/ert/commit/8f556c5104a3aa9c8f1a729e5a371927108585e8
