### ISSUE TITLE
How to include EclSum serializer?

### ISSUE THREAD

**Issue by berland** [equinor/ert#2382]
Currently transmitters are responsible for reading file contents and pass contents to serializers; 

https://github.com/equinor/ert/blob/6302a0a3bb426d3f599adaf01f53b82e85e07533/ert/data/record/_transmitter.py#L121-L125

EclSum requires opening of two files (`SMSPEC` and `UNSMRY`), hence, it is not possible to provide a single file pointer. 

Additionally, the code above assumes that the files on disk can be opened in text mode.

Would it make sense to let the serializers open the files?

**Comment by berland** [comment]
An alternative is to decide not to support Eclipse binary output files directly, but support some other transformed summary file format. 

In any case, Webviz will recommend all FMU users to inject a forward model to convert all summary files to pyarrow files, using `ecl2df`.

**Comment by jondequinor** [comment]
> Would it make sense to let the serializers open the files?

Yes! The serialisation module should be capable of this, and the current API is woefully inadequate. It was a start, but it now needs an upgrade. 

(Might have to look into whether or not the transformation concept should supersede the serialisation module.)

**Comment by berland** [comment]
Should we expose both async and sync function calls for decoding and encoding to/from path?
