### ISSUE TITLE
Use RecordCollection as general record collection, not only over ensembles

### ISSUE THREAD

**Issue by berland** [equinor/ert#2383]
`RecordCollection` is written with knowledge of the ensemble concept, which might not be necessary. 

https://github.com/equinor/ert/blob/080115c5a895fb65daea6cc199e689e55ffc9f05/ert/data/record/_record.py#L188-L212

A possibility is to rename the `ensemble_size` property to just `length`, and then use this class also for collections of records for example within single realizations.

**Comment by sondreso** [comment]
Renaming to length I think is a good idea, but lets hold of on merging the Collection concept here with a collection concept in the ensemble until we have implemented the MetaRecord/RecordStore/RecordTree :slightly_smiling_face:
