### ISSUE TITLE
ERT ignores failure of workflows. Should be able to enable/disable stop of ERT if an ERT workflow fails

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#2386]
ERT workflow for localisation can fail to validate its input and pydantic returns an error message caused by a raise ValueError() from validation. But ERT continue to the next step (which is the update step) when running Ensemble Smoother or other update options.
The localisation workflow is typically run after initial ensemble is created, but before the ensemble is updated, and a failure in the localisation workflow is ignored. The user can get the impression that it all worked well, but no localisation is activated.

How to reproduce this:
Just run an ERT model, call a workflow to be run just after initial ensemble is created by the workflow option PRE_FIRST_UPDATE. Ensure that the workflow is failing in validation and don't do anything except raise a ValueError in validation.

Expected behaviour:
Have an option to tell ERT that if a workflow fails, ERT should stop and report ERROR or ignore error raised by the workflow job.
In some cases like in post-processing, results may be used even if a post-processing workflow fails, but for workflows that are a part of the model setup like a localisation workflow, it should report failure of the workflow and stop ERT to avoid giving the impression that it works. 

Suggestion:
A workflow should send a signal to ERT main that it has failed and whether the failure should trigger  a stop of ert or not. It depends on the nature of the workflow how a failure should be treated and it should be up to the workflow job(s) to signal back to ert main to stop or ignore. In any case it must report error from the workflow (and that is up to the workflow jobs to do).

**Comment by jondequinor** [comment]
Also see https://github.com/equinor/ert/issues/719

**Comment by BjarneHerland** [comment]
@jondequinor is this relevant input for the ExperimentServer?

**Comment by jondequinor** [comment]
Workflows is encapsulated by the "legacy ensemble", but it's very possible to have workflows communicate with the experiment server via websockets and reports its status via that route.

**Comment by hnformentin** [comment]
We had a short discussion on [slack scout](https://equinor.slack.com/archives/GCCF1U6MT/p1683268987691339). Probably not all have access, so I will try to summarise for future users and developers.

We updated the milestone this issue makes part of and classified as a feature.

** Current behaviour **

There is an understanding that the current behaviour is actually the expected one. Being transparent, what we should do in the event of a failure is not always obvious. A couple of reasons were speculated:
- the easiest/only way implementing/supporting a feature needed at some point.
- drive by the user consensus that the worst thing a computer program can do is to crash
- the developer should choose between errors util_abort("Let the system burn down") or I see your error and continue like nothing happened

Some workflows, like MISFIT_PREPROCESSOR should stop the workflow, while others are fine to continue.

** Future behaviour **
Making the behaviour user configurable is the way to go.
There is no clear list, but having an option (either at install time or run time) sounds like the best option here. So for example the localization workflow or the mistfit preprocessor are workflows that would stop ert, while perhaps the sumo workflow should not (though I am not entirely sure that is true).

It seems that Johan Sverdrup has also been asking for this feature earlier. When this issue get prioritised, we could find a few users that are willing to test it when developed and then make it configurable.

Over time we might even consider changing the default from pretending like nothing happened to halting, but that is a longer discussion.
