### ISSUE TITLE
Check if keyword: `ENKF_SCHED_FILE` can be removed

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2397]
This does not seem to be used, and could probably be removed.

**Comment by BjarneHerland** [comment]
[Documentation](https://github.com/equinor/ert/blob/main/docs/rst/manual/reference/configuration/keywords.rst) links the keyword ENKF_SCHED_FILE to two other keywords: 

- Section on ENKF_MERGE_OBSERVATIONS indicates that this keyword is only relevant if used together with ENKF_SCHED_FILE? Should we remove it also? I cannot find it referenced other places in documentation. 

- Section on FORWARD_MODEL states `Note that the ENKF_SCHED_FILE keyword can be used to change the FORWARD_MODEL for sub-sequences of the run.` I assume this statement can be removed from docs?

As I don't know enough about using ERT this issue cannot move forward before points above are resolved.

**Comment by joakim-hove** [comment]
Can safely be removed

**Comment by BjarneHerland** [comment]
> Can safely be removed

What about `ENKF_MERGE_OBSERVATIONS` ?

**Comment by joakim-hove** [comment]
>What about ENKF_MERGE_OBSERVATIONS ?

Same

**Comment by BjarneHerland** [comment]
Jolly good!  😄

**Comment by BjarneHerland** [comment]
@joakim-hove  does this comment refer to `ENKF_MERGE_OBSERVATIONS` ?

https://github.com/equinor/ert/blob/f938dab450dc9fbf31aa1458511a767388bdb827/libres/lib/enkf/enkf_main.cpp#L1088-L1092

**Comment by joakim-hove** [comment]
Yes
