### ISSUE TITLE
Simplify setting of `CONAN_CACERT_PATH`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2401]
https://github.com/equinor/ert/blob/359872ed722c0cb5c0ee08bdb2af731cd009fe7a/setup.py#L7-L15

Can we simplify this to @dotfloat :

```python
if "CONAN_CACERT_PATH" not in os.environ: 
    os.environ["CONAN_CACERT_PATH"] = "/etc/pki/tls/cert.pem"
```

**Comment by dotfloat** [comment]
Ye. It was over-engineered in case we need to add more platforms. In hindsight, very unnecessary.

**Comment by sondreso** [comment]
I think @lars-petter-hauge experienced this on a managed Mac on the internal network as well, so we might need more platforms.

**Comment by lars-petter-hauge** [comment]
That is true, I simply worked outside of the internal network for that day (before returning to the dungeon that is home office).

I can dig up the path to the certificates on my managed mac..

**Comment by pinkwah** [comment]
Oof yeah that could get a bit nasty on a mac... :/

**Comment by lars-petter-hauge** [comment]
I'll ask and see :)

**Comment by pinkwah** [comment]
After a cursory glance at the requests library, it seems to just use the `certify` package, which is provides the Mozilla certificates just like on Linux. The first step should be to check whether other Python packages work.

It is also possible to create your own `cacert.pem` with `security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain` [1]

[1]: https://stackoverflow.com/a/70054211

**Comment by dafeda** [comment]
Can we close this @pinkwah , @lars-petter-hauge ?

**Comment by pinkwah** [comment]
You opened the issue. You can also close it.
