### ISSUE TITLE
ERT crashes with segmentation fault if wrong input to GEN_OBS

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#2404]
If GEN_OBS is specified with INDEX_LIST but data following is a file name to an index file instead of a list of indices, ERT end up with segmentation fault. If correct specification is used by using INDEX_FILE when a file name follows, it is OK.

**Expected behavior**
Raise a ValueError with an understandable error message.

It was tested on komodo release 2021.11.02-py36 and latest ert code from main branch with the same behaviour. All my tests were run interactively using ert gui

**Comment by oyvindeide** [comment]
There should most definately come a better error message out of this, do you have a minimal failing example?

**Comment by oddvarlia** [comment]
You can use the poly example, replace the index list numbers in INDEX_LIST = 0,2,4,6,8; with INDEX_FILE = 0,2,4,6,8; in file observations and run with ES update and get  _segmentation fault_ error

**Comment by andreas-el** [comment]
Not reproducible on latest stable 2023.02.07

```diff
(2023.02.07-py38) andrli@be-lx919901 ~/project/ert (main)$ git diff test-data/poly_example/observations
diff --git a/test-data/poly_example/observations b/test-data/poly_example/observations
index dff1ae0..b29eb56 100644
--- a/test-data/poly_example/observations
+++ b/test-data/poly_example/observations
@@ -1,6 +1,6 @@
 GENERAL_OBSERVATION POLY_OBS {
    DATA       = POLY_RES;
-   INDEX_LIST = 0,2,4,6,8;
+   INDEX_LIST = index_file.txt;
    RESTART    = 0;
    OBS_FILE   = poly_obs_data.txt;
 };
```
```
(2023.02.07-py38) andrli@be-lx919901 ~/project/ert (main)$ cat test-data/poly_example/index_file.txt 
0
2
4
6
8
(2023.02.07-py38) andrli@be-lx919901 ~/project/ert (main)$ 
```
Tested using both INDEX_FILE and INDEX_LIST keywords with identical results. Both successful.
