### ISSUE TITLE
Make `load_collection_from_file` async

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#2409]
**Issue**
The module `_record.py` is currently synchronous. It deals directly with IO, using the ert serializer module which is async.
Thus, it is meaningful that `_record.py` should be async.
Having to wait for event loops to complete, is indicative of this. 

**Suggested solution**
Make selected functions in module `_record.py` asynchronous.

**Comment by berland** [comment]
The call `tarfile.add()` (inside `path_to_bytes()`) looks very problematic to make async.

**Comment by sondreso** [comment]
The issue title is slightly misleading here. Most of `_record.py` does not involve operations that benefits from being async. Think it could be renamed to "_make `path_to_bytes` and `load_collection_from_file` async_", as these are the only functions that have IO operations. I think it could also be argued that these functions do not belong to `_record.py`, especially `path_to_bytes`, so maybe consider moving them to a separate module also.
