### ISSUE TITLE
test_batch_sim acts flaky on github actions

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2436]
____________ BatchSimulatorTest.test_batch_ctx_status_failing_jobs _____________

self = <test_batch_sim.BatchSimulatorTest testMethod=test_batch_ctx_status_failing_jobs>

    @tmpdir()
    def test_batch_ctx_status_failing_jobs(self):
    
        config_dir = os.path.join(self.TESTDATA_ROOT, "local/batch_sim")
        shutil.copytree(config_dir, "batch_sim")
        os.chdir("batch_sim")
    
        self.assertTrue(os.path.isfile("batch_sim_sleep_and_fail.ert"))
        res_config = ResConfig(user_config_file="batch_sim_sleep_and_fail.ert")
    
        external_parameters = {
            "WELL_ORDER": ("W1", "W2", "W3"),
            "WELL_ON_OFF": ("W1", "W2", "W3"),
        }
        results = ("ORDER", "ON_OFF")
        rsim = BatchSimulator(res_config, external_parameters, results)
    
        cases = [
            (
                0,
                {
                    "WELL_ORDER": {"W1": idx + 1, "W2": idx + 2, "W3": idx + 3},
                    "WELL_ON_OFF": {"W1": idx * 4, "W2": idx * 5, "W3": idx * 6},
                },
            )
            for idx in range(10)
        ]
    
        batch_ctx = rsim.start("case_name", cases)
        while batch_ctx.running():
>           self.assertContextStatusOddFailures(batch_ctx)

/home/runner/work/ert/ert/tests/libres_tests/res/simulator/test_batch_sim.py:595: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/ert/ert/tests/libres_tests/res/simulator/test_batch_sim.py:563: in assertContextStatusOddFailures
    self.assertEqual(JobStatusType.JOB_QUEUE_FAILED, status)
E   AssertionError: JobStatusType(name = "JOB_QUEUE_FAILED", value = 8192) != None

**Comment by oyvindeide** [comment]
got much of the same: 
```
____________ BatchSimulatorTest.test_batch_ctx_status_failing_jobs _____________

self = <test_batch_sim.BatchSimulatorTest testMethod=test_batch_ctx_status_failing_jobs>

    @tmpdir()
    def test_batch_ctx_status_failing_jobs(self):
    
        config_dir = os.path.join(self.TESTDATA_ROOT, "local/batch_sim")
        shutil.copytree(config_dir, "batch_sim")
        os.chdir("batch_sim")
    
        self.assertTrue(os.path.isfile("batch_sim_sleep_and_fail.ert"))
        res_config = ResConfig(user_config_file="batch_sim_sleep_and_fail.ert")
    
        external_parameters = {
            "WELL_ORDER": ("W1", "W2", "W3"),
            "WELL_ON_OFF": ("W1", "W2", "W3"),
        }
        results = ("ORDER", "ON_OFF")
        rsim = BatchSimulator(res_config, external_parameters, results)
    
        cases = [
            (
                0,
                {
                    "WELL_ORDER": {"W1": idx + 1, "W2": idx + 2, "W3": idx + 3},
                    "WELL_ON_OFF": {"W1": idx * 4, "W2": idx * 5, "W3": idx * 6},
                },
            )
            for idx in range(10)
        ]
    
        batch_ctx = rsim.start("case_name", cases)
        while batch_ctx.running():
>           self.assertContextStatusOddFailures(batch_ctx)

/home/runner/work/ert/ert/tests/libres_tests/res/simulator/test_batch_sim.py:595: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/ert/ert/tests/libres_tests/res/simulator/test_batch_sim.py:561: in assertContextStatusOddFailures
    self.assertEqual(JobStatusType.JOB_QUEUE_SUCCESS, status)
E   AssertionError: JobStatusType(name = "JOB_QUEUE_SUCCESS", value = 512) != None
=============================== warnings summary ===============================
```

**Comment by markusdregi** [comment]
Again here: https://github.com/equinor/ert/runs/5050952134?check_suite_focus=true

**Comment by BjarneHerland** [comment]
And here  https://github.com/equinor/ert/runs/5482742975?check_suite_focus=true

**Comment by BjarneHerland** [comment]
The None-value causing these issues come from here
https://github.com/equinor/ert/blob/f53d60231fe2d7d45de87fcf949e51b0277de61a/res/simulator/simulation_context.py#L179-L180
caused by
https://github.com/equinor/ert/blob/f53d60231fe2d7d45de87fcf949e51b0277de61a/res/enkf/run_arg.py#L66-L67

This again is caused by this loop
https://github.com/equinor/ert/blob/f53d60231fe2d7d45de87fcf949e51b0277de61a/tests/libres_tests/res/simulator/test_batch_sim.py#L594-L596
which assumes that jobs are added to the (running) queue faster than the sleep(). The error is simple to reproduce by inserting a delay, e.g. time.sleep(2), between these two lines
https://github.com/equinor/ert/blob/f53d60231fe2d7d45de87fcf949e51b0277de61a/res/job_queue/queue.py#L346-L347
