### ISSUE TITLE
Session tests fails on komodo 

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#2441]
`
self = <ert_storage.client.session.Session object at 0x7f20c43e52e0>

    def _resolve_url(self) -> str:
        """Resolve which of the candidate base urls to use."""
        for url in self._connection_info["urls"]:
            try:
                # Original code has auth token passed but is it actually used?
                resp = requests.get(f"{url}/healthcheck")
                if resp.status_code == 200:
                    return url
            except requests.ConnectionError:
                pass
        # Needs better exception message
>       raise RuntimeError("None of the Storage URLs provided worked")
E       RuntimeError: None of the Storage URLs provided worked

/prog/res/komodo/test-hash-py38-rhel7/root/lib/python3.8/site-packages/ert_storage/client/session.py:83: RuntimeError`

**Comment by BjarneHerland** [comment]
This code does not exist any more. Could you point to the new code which does this, if any?

**Comment by lars-petter-hauge** [comment]
I can't determine which test that actually failed on this, only the location of the error. Please update with the test in question

**Comment by BjarneHerland** [comment]
Putting this on the "old issue, not occuring anymore"-list
