### ISSUE TITLE
Add benchmarks for thread pool matrix functions

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2446]
We have a bunch of thread pooled matrix operations which have dubious performance claims. Let's test these using the Catch2 benchmarking framework and compare them to the non-thread pool versions. Should the multithreaded matrix ops be slower for large but realistic matrices, we should delete the functions entirely.

**Comment by oyvindeide** [comment]
Not solved yet, but will be closed by: #https://github.com/equinor/ert/pull/2872
