### ISSUE TITLE
Align ERT2 and ERT3 parameter model

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2450]
### Background
It was noticed that `webviz-ert` fails to visualise parameters coming from ERT3 (https://github.com/equinor/webviz-ert/issues/191). After further investigation it turns out that the reason is that ERT2 and ERT3 differentiates in how they present their parameters for `ert-storage`, with `webviz-ert` only supporting the one utilised by ERT2.

### More details
The data that is to be modelled can be viewed as a (multi-)dimensional matrix per realisation. And concretely in the situation from above we are to model a set of `coefficients` named `a`, `b` and `c`. Which brings us to a single-dimensional matrix with indices `a`, `b` and `c` for each realisation.

**ERT3** currently publishes this per realisation; that is the values of `a`, `b` and `c` per realisation. Which at the end implies that `ert-storage` holds the full `[ensemble id's] x [a, b, c]` matrix.

**ERT2** currently publishes this matrix per index; that is the values of `a` for each realisation, followed by the values of `b` for each realisation and last the values of `c`. Furthermore, these values are published in a flatten manner. That is that we publish `a` and `b` as `coefficients.a` and `coefficients.b` respectively and hence loosing the explicit connection between `a` and `b`.

**webviz-ert** currently fails to visualise parameters that contains multiple values per realisation. That is, it succeeds at visualising `coefficients.a`, but fails at visualising `coefficients: (a, b, c)`.

The good news is that conceptually ERT2 and ERT3 agrees on the format of the data at hand. And furthermore, this format aligns rather well with `NumericalRecord` and `RecordCollection` in `ert.data`.

### Moving forward
We should aim at using `ert-storage` to represent our data as naturally as possible. This entails that we should have ERT2 publish the parameters without flattening to avoid loosing structure. Furthermore, `webviz-ert` should be able to visualise single-dimensional matrices per realisation. In other words, the complete span of possible `GEN_KW` parameters in ERT2 and parameters in `ERT3`.

Note: It is an acceptable first solution that `webviz-ert` flattens the parameter structure for visualisation. That is, when choosing parameters to visualise one is presented with `coefficients:a`, coefficients:b` and `coefficients:c`. However, the responsibility of making data in `ert-storage` visualisable should reside on `webviz-ert`.

**Comment by eivindjahren** [comment]
Closing as this discussion is framed as ERT2 vs ERT3 which is no longer the current direction. Feel free to reopen if there is still a relevant discussion to be had.
