### ISSUE TITLE
Make sure local traffic does not pass through the proxy

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#2452]
A user has reported problems with ERT in Yammer. 

https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTQ5MDc4NTkwMzAwOTc5MiJ9

After looking at the logs there seems to be quite a large amount of network errors happening during the run. To reduce the load on the network we should make sure only traffic that needs to pass through the proxy does that.

**Comment by sondreso** [comment]
The usage of localhost vs external IP was not the main issue behind the reported problems. More error handling has been introduced to ensure that we keep the connection in case of intermittent network failures, and connection details should be handled by a more robust solution for service discovery. Closing this issue
