### ISSUE TITLE
Running ert3 seems to open one new port each request

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2456]
**Describe the bug**
While debugging https://github.com/equinor/ert/issues/2381 i noticed in the console
```
 OpenAPI Docs: http://penguin:51820/docs
        Username: __token__
        Password: rwitqktK0Sdu6x6Z

INFO:     Started server process [5620]
INFO:uvicorn.error:Started server process [5620]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     127.0.0.1:40490 - "GET /healthcheck HTTP/1.1" 200 OK
INFO:     127.0.0.1:40492 - "GET /experiments HTTP/1.1" 200 OK
INFO:     127.0.0.1:40494 - "GET /healthcheck HTTP/1.1" 200 OK
INFO:     127.0.0.1:40496 - "GET /experiments HTTP/1.1" 200 OK
INFO:     127.0.0.1:40498 - "GET /healthcheck HTTP/1.1" 200 OK
INFO:     127.0.0.1:40500 - "POST /experiments HTTP/1.1" 200 OK
INFO:     127.0.0.1:40502 - "GET /healthcheck HTTP/1.1" 200 OK
INFO:     127.0.0.1:40504 - "POST /experiments/0c491f79-bd81-42a9-94de-6eae140d61be/ensembles HTTP/1.1" 200 OK
```

This doesn't seem correct. 

**To Reproduce**
As described in https://github.com/equinor/webviz-ert/issues/190

Look at the console where you have started ert-storage in step 2. You should see the port bumped at each request.

**Expected behavior**
I would expect the host and port stay the same throughout the entire run.

**Additional context**
It should be verified this behavior is not present in ert2 - if it is make another issue or append to this one. 

Related to https://github.com/equinor/ert/issues/2381 .

**Comment by jondequinor** [comment]
Not an https://en.wikipedia.org/wiki/Ephemeral_port?wprov=sfti1 ?

**Comment by frode-aarstad** [comment]
The same behavior is present in ert2.  Verified by running:

`ert api snake_oil.ert`
`ert vis`

**Comment by oysteoh** [comment]
> Not an https://en.wikipedia.org/wiki/Ephemeral_port?wprov=sfti1 ?

I don't know actually, just saw it and thought it was weird. But maybe it is intentional and should be like this? I guess verifying the behavior at least should be done and discover if it intentional or not.

**Comment by dotfloat** [comment]
Yeah. Step 1 in this issue is to check whether this is actually intended behaviour on part of [uvicorn](https://github.com/encode/uvicorn), or whether we are accidentally creating new storages. The fact that these `INFO`s come right after each other would suggest @jondequinor 's correct.

**Comment by frode-aarstad** [comment]
Seems like this is intended behaviour.
