### ISSUE TITLE
Document ERT C++ develop & debug from the command line with gdb/lldb, valgrind, sanitizers, etc.

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2457]
Since there are non-zero number of users working on the C++ codebase, we should write some docs on how to debug the code. This issue is likely in two parts:
1. Debugging the EclTestArea/Catch2 tests
2. Debugging the C++ code via Python code

I personally use these tricks, that we could include in the doc:
1. Use `-DCMAKE_BUILD_TYPE=Debug` to get a debug build [^1]
2. Use `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG"` [^2]
3. Use address and undefined behaviour sanitizers. [^3]
4. Hook onto a running `pytest` instance with `gdb`/`lldb`. @oyvindeide (or was it @lars-petter-hauge ?)
5. Use `export PYTHONMALLOC=malloc` when running `valgrind pytest`, so as to not get spammed by memleak false-positives

[^1]: Among other things, this doesn't inline function definitions, making it possible to spot errors in functions such as this:
    ```c++
    int get_int(foo_t * sometimes_is_null) {
        return sometimes_is_null->value; // UB: dereferencing a nullptr
    }
    ```
[^2]: Enable debug versions of `std::` functions. Eg, `std::vector::operator[]` normally doesn't check whether the query is within the input range, but the debug version does and throws `std::out_of_range` if it isn't. Another example is `std::lower_bound` (binary search), which requires that the input is sorted; the debug version will first call `std::is_sorted` and throw an exception if it isn't.
[^3]: I always have to StackOverflow this and I'm too lazy to do it now.

**Comment by dafeda** [comment]
Here's a nice description of how to debug C extensions written by 🐼 

https://pandas.pydata.org/docs/development/debugging_extensions.html

**Comment by lars-petter-hauge** [comment]
> 4\. Hook onto a running `pytest` instance with `gdb`/`lldb`. @oyvindeide (or was it @lars-petter-hauge ?)

Probably me, you helped me out getting the debugger to stop at breakpoints. From what I understand; preload the library in order to have the debugger be able to set breakpoint in a dynamically loaded library:
```
gdb python # or lldb..
image add <name>.so
```

**Comment by pinkwah** [comment]
Don't have much C code left, closing.
