### ISSUE TITLE
Replace `hash_type` with `std::unordered_map` or something similar

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2460]
`hash_type` is a type defined in `ecl` which we should be able to replace with something standard like `std::unordered_map`.

https://github.com/equinor/ert/blob/cd43dba890a885482f24c57ff03bcefca012b23e/libres/lib/enkf/local_ministep.cpp#L46-L47

**Comment by dotfloat** [comment]
Do note that `hash_type` is type-erased, unlike `unordered_map`, which means the key and value types can be anything. Ie, like `Dict[Any, Any]`.

Consider finding the `hash_type`s, creating an issue for each and making this issue an epic. A cursory `rg hash_type | wc -l` shows that there are 109 uses of this text.

**Comment by joakim-hove** [comment]
> which means the key and value types can be anything. Ie, like Dict[Any, Any].

More like `Dict[Str, Any]` - the key type is *always* `const char*`; do however observe that in actuality the value type is the same for all elements in a `hash_type` container (although that is not enforced).

Also observe that the `hash_type` typically manages the memory of the value objects by calling `xxx_free__( value_ptr )` when the element is removed from the container. Unless the content of the `std::unordered_map` has value semantics some `std::unique_ptr` trickery would be required to ensure that elements are properly destroyed when they are removed from the map.

**Comment by oyvindeide** [comment]
Think I will close this issue as it is a bit to general, and should be handled on a case by case basis.
