### ISSUE TITLE
Improve performance dark-storage / api

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2468]
User-feedback ( very limited for now - https://github.com/equinor/webviz-ert/issues/175) regarding performance tells us that even on `dark-storage` the performance visualizing with "real" data is not good enough. We should look into if it is possible to make this better / identify bottlenecks etc which could be made into actionable issues in the upcoming planning.

**Comment by frode-aarstad** [comment]
I had a discussion and a look at the code together with @mortalisk  and came up with some topics for the discussion.

Discuss the typical use case for webviz ert to make sure the benchmarking and optimizations are accurate.
- Limitations on memory, bandwidth
- Is the use case different from QT-plotter?
- Are there cases where QT-plotter currently does not work?
- Get a realistic test setup

Find the bottlenecks in the current implementation. Get some numbers and make sure that it is actually possible to get closer to the QT-plotter performance. There is an added overhead that is unavoidable by going through the API.
- Drawing in webviz-ert?
- Running on RGS?
- Loading from StorageAPI?

    
Potential improvements.

Webviz-ert
- Async / parallel loading of data
- Smarter reading of data from API / read more data in each call
- Don't create a new DataLoader with each call


Storage API / dark storage
- New endpoints for reading more data ie: /parameters
- Caching / try and predict what user will request next


Extra.
- Should the storage API do any computations?
- Storage API scalability - large amounts of data and users
- Server side rendering of plots / views
