### ISSUE TITLE
Replace active_list with std::vector

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2485]
We should be able to replace active_list_type with a std:vector by changing the construction to getting all the incidences instead of the `mode` property. That should enable us to remove quite a few code paths. Should check why this was implemented initially.

**Comment by joakim-hove** [comment]
The mode concept was used because size is not known at construction time.

**Comment by oyvindeide** [comment]
Will close this issue as it is not that relevant, we will probably refactor this slightly as a part of changing parameter saving.
