### ISSUE TITLE
Improve the storage_server.json

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2510]
- We should remove all of the url's ( maybe keep the FQDM )
- Add process_id for us to be able to check if storage is actually running on the machine or not.

**Comment by oysteoh** [comment]
Resolved in https://github.com/equinor/ert-storage/pull/184

**Comment by jondequinor** [comment]
That's an open 🤔

**Comment by oysteoh** [comment]
Specified wrong issue 😬   And it is in review, thought it was closed 👍 

Will be fixed by the merge of https://github.com/equinor/ert-storage/issues/181
