### ISSUE TITLE
Get hold of a real case and figure out the dimensions

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2511]
We need a proper test dataset for us to test the performance. By getting hold of a real case we should get the different dimensions and sizes and change the snake-oil case to be as big as this dataset.

**Comment by berland** [comment]
Mock it!
```python
import numpy as np
import pandas as pd

import ecl2df
from ecl.summary import EclSum

date_count = 1000
column_count = 1000

dframe = pd.DataFrame(
    index=pd.date_range(start="2020-01-01", freq="D", periods=date_count),
    data=np.random.randint(0, 1000, size=(date_count, column_count)),
)
dframe.columns = ["WOPR:OP_" + str(idx) for idx in dframe.columns]
dframe.index.name = "DATE"

eclsum = ecl2df.summary.df2eclsum(dframe.reset_index(), "MOCKEDCASE")
EclSum.fwrite(eclsum)
```
(`df2eclsum` here is quite slow, this example takes ~a minute. If needed, importing `ecldf` can be skipped.)

**Comment by oysteoh** [comment]
Leaving this open but not working actively on it. We have more or less a good impression of what a "normal" case is which is enough for our current testing

**Comment by oysteoh** [comment]
from @berland
iterations: O(1)
realizations: O(100) 
smry-vectors:  O(100) -> O(1000) ( pr realisation )
timesteps, worst-case:  365days*50years = O(10000)
observations: O(10)
number of scalar model parameters (designmatrix  and  hm-parameters): O(10) -> O(100)

**Comment by oysteoh** [comment]
Leaving this open for reference while working on test-datasets.

**Comment by jsorb** [comment]
Accidentally came across this one. Johan Sverdrup model dimensions:
iterations: 1-4
realizations: 200
smry-vectors: 20 000 ( pr realisation )
timesteps = ~5000 (but only reporting 600-700)
number of scalar model parameters (designmatrix and hm-parameters): 306

**Comment by BjarneHerland** [comment]
Please see how to set up a logger in C++ e.g. here

https://github.com/equinor/ert/blob/4fc6d5f6f9f5deef3586002741d22bb189be9342/libres/lib/analysis/update.cpp#L40

as well as [this](https://github.com/equinor/scout/issues/519) together with code/solution when it is done.

The idea is to log desired info (dimensions, memory usage, whatnot...) and create a corresponding receiver/visualisation. When the added logging gets included in official builds, we receive data from actual usage which can be visualized in the Azure log-dashboard and help us gain insight.

**Comment by oysteoh** [comment]
> Accidentally came across this one. Johan Sverdrup model dimensions: iterations: 1-4 realizations: 200 smry-vectors: 20 000 ( pr realisation ) timesteps = ~5000 (but only reporting 600-700) number of scalar model parameters (designmatrix and hm-parameters): 306

Thanks! Very valuable input! 👏

**Comment by oysteoh** [comment]
We have a good understanding of dimensions from different cases - closing this issue.
