### ISSUE TITLE
Make interfaces of the transformations and the transmitters reflect their responsibility

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2512]
The transmitters should __always__ take or return Records/RecordTrees, and this should then be passed to/from a transformation in order to be serialised to/from a file. 

Some specifications: 
- Transformations can be bi- or unidirectional
- We should have bi-directional transformations of both Records and RecordTrees to common formats such as json or yaml. 
- Summary transformation should be uni-directional (from file)
- File loading and dumping belongs to the Transformations

**Comment by verveerpj** [comment]
One step here is to get rid of the `dump `method in the transmitters. It seems these are only used in the file and executable transformations, so these should simply write the file themselves. However, the shared disk transmitter has an optimization in the dump, which circumvents loading and saving the file, when possible, it just does a file copy. That optimization will be lost, if the transformation is to remain agnostic of the transmitter.

**Comment by verveerpj** [comment]
It is also specified that file loading belongs to the transformations. It seems to me that transmitters do no do file loading in that sense. They have a `load` method, but if understand correctly that is just to get a record in memory, by whatever means that particular transmitter type uses (i.e. could be network, file, or memory). The `SharedDiskRecordTransmitter` seems to be the only one doing loading from file. That seems fine to me, or are we thinking to forward that action to a transformation?

**Comment by verveerpj** [comment]
If we are talking about making transformations for json/yaml loading dumping, should we not rather make a separate issue for that?

**Comment by sondreso** [comment]
> That optimization will be lost, if the transformation is to remain agnostic of the transmitter.

True, and I think this is OK for now.

> It is also specified that file loading belongs to the transformations. It seems to me that transmitters do no do file loading in that sense. They have a load method, but if understand correctly that is just to get a record in memory, by whatever means that particular transmitter type uses (i.e. could be network, file, or memory). The SharedDiskRecordTransmitter seems to be the only one doing loading from file. That seems fine to me, being an implementation detail, or are we thinking to forward that action to a transformation?

> Should the transmit_file method move out of RecordTransmitter?

Yes, by file loading the intention was that `transmit_file` should be moved out of the transmitter and into the transformation. 

> If we are talking about making transformations for json/yaml loading dumping, should we not rather make a separate issue for that?

Yes, bu I also dont think they need to be specific transformations for all of these. A FromFileTransformation could get a mime tyoe and use that to get a serializer for that specific type.

**Comment by verveerpj** [comment]
If `dump` and `transmit_file` would be removed from the Records, it seems the transformations would end up just using the `load` method, to get the record into memory, or `transmit_record` to get a record transmitted. Do we want to decouple transformations and transmitters more, by making the transformations taking records instead of transmitters?

**Comment by verveerpj** [comment]
> Yes, bu I also dont think they need to be specific transformations for all of these. A FromFileTransformation could get a mime tyoe and use that to get a serializer for that specific type.

That probably makes sense, but I guess we are still looking at a lot of places in the code where we should use them. So, maybe something to do last in this issue, or spawn a separate issue after doing the other tasks.

**Comment by sondreso** [comment]
> If dump and transmit_file would be removed from the Records, it seems the transformations would end up just using the load method, to get the record into memory, or transmit_record to get a record transmitted. Do we want to decouple transformations and transmitters more, by making the transformations taking records instead of transmitters?

Yes, I think this would be a good idea! I think it would be nice if the transformations take/outputs a Record, which comes from / is given to a transmitter, depending on the direction.

**Comment by verveerpj** [comment]
Then the plan is to follow these steps:

1. Remove `dump` from the record classes, make sure transformations can do that job.
2. Remove `transmit_file` from the record classes, make sure transformations can do that job.
3. Change the transformations to use input/output records, fully decoupling them from transmitters.

Does that cover this issue, or am I still missing something?

I will create an issue for making json/yaml transformations, I am thinking the above task is sufficient for one PR.

**Comment by sondreso** [comment]
> or am I still missing something?

Nope sounds good!
