### ISSUE TITLE
Remove the notion of several local_datasets within a local_ministep

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2539]
the local_dataset type was used as an identifier of a group of parameters to be used across time when running kalmann filter. As we are not running across time anymore (since the last 5< years, we can remove this and assume all parameters within a ministep are to be updated.

**Comment by BjarneHerland** [comment]
@joakim-hove hvor mya i denne skissen tror du gjelder fremdeles?

https://github.com/equinor/ert/blob/3d3270391c14f8d12c429d389823cd9c10a9a84d/libres/lib/enkf/local_config.cpp#L30-L72
