### ISSUE TITLE
Ensemble record api should support retrieval of multiple realizations

### ISSUE THREAD

**Issue by TerryHannant** [equinor/ert#2545]
Some use cases of the ert-storage api retrieve a potential large number of realizations (100+).  Currently this is performed via a HTTP call per realization which is inefficient.

By combining multiple calls into a single call passing a list of realizations a large should result in more efficient clients

**Comment by eivindjahren** [comment]
The current api has (as far as I know) no endpoints that support giving a realization id, only ensemble id and experiment id, so this issue is resolved.
