### ISSUE TITLE
ExtJob._set_executable has the wrong ResPrototype

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#2548]
https://github.com/equinor/ert/blob/6e144541e63a05e1e86b694afa9ebd79b36478c3/res/job_queue/ext_job.py#L49

vs

https://github.com/equinor/ert/blob/6e144541e63a05e1e86b694afa9ebd79b36478c3/libres/lib/include/ert/job_queue/ext_job.hpp#L60-L61

Related to #4180

**Comment by oysteoh** [comment]
@eivindjahren this was found during some cleanup of issues done by @oyvindeide . I guess we could either close this as not relevant anymore or address it now in our milestone?

**Comment by eivindjahren** [comment]
We will fix this by closing #4180 at the very least.
