### ISSUE TITLE
The RNGConfig test incorrectly documents config_dict

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#2556]
`tests/libres_tests/res/enkf/test_rng_config.py` uses a structure for config dicts which is not correct, but does not fail due to fudging.

**Comment by valentin-krasontovitsch** [comment]
i'm sorry, but I'm confused - so just looking at the keys and values used, it seems like everything is fine. an rng config only has two fields, seed and algorithm type. the algorithm type is (at the moment) uniquely determined, and the default is, as far as i can see, always used. so the only variable is the seed - changing the seed value in one of the options in `test_dict_constructor` fails the test.

the only other thing i can come up with that might have been meant here is the structure of the prepared dict - the one passed as argument `config_dict` is

```
{'RANDOM_SEED': 'abcdefghijklmnop'}
```

while the `config_content` argument gets

```
{
  "INTERNALS": {
    "CONFIG_DIRECTORY": "simple_config"
  },
  "SIMULATION": {
    "QUEUE_SYSTEM": {
      "JOBNAME": "Job%d"
    },
    "RUNPATH": "/tmp/simulations/run%d",
    "NUM_REALIZATIONS": 1,
    "JOB_SCRIPT": "script.sh",
    "ENSPATH": "Ensemble",
    "SEED": {
      "RANDOM_SEED": "abcdefghijklmnop"
    }
  }
}
```

which is much more complicated. so perhaps we should pass such a complex dict to the `config_dict` argument, too :thinking:

**Comment by eivindjahren** [comment]
Then it might be that this has changed since the creation of the issue. Perhaps we can just close it now?

**Comment by eivindjahren** [comment]
I think the issue is about the disparity between the `RngConfig` class expecting to read from `config_dict[ConfigKeys.RANDOM_SEED]` while the test is setting `config_dict["SIMULATION"]["SEED"][ConfigKeys.RANDOM_SEED]` which `RngConfig` just ignores. I think just using `config_dict[ConfigKeys.RANDOM_SEED]` is the right approach.

**Comment by valentin-krasontovitsch** [comment]
I see! let me take another look at that, and at what `RngConfig` is or should expect : )

**Comment by valentin-krasontovitsch** [comment]
ok now that i'm looking at it, i'm actually confused again - the test sets

```
config["SIMULATION"]["SEED"] = {ConfigKeys.RANDOM_SEED: random_seed}
```

then passes said config to `ResConfig`:

```
res_config = ResConfig(config=config)
```

but when it comes to using the `config_dict` argument, it actually passes the simpler dict:

```
rng_config = RNGConfig(config_dict=config["SIMULATION"]["SEED"])
```

which is exactly what `RNGConfig` expects, and hence all is good - i think you commented but removed that we could maybe close this issue. i'm starting to think you might have been right?

**Comment by eivindjahren** [comment]
Ah, yes, I see. I am confused by my own issue a since it is a while a go. I am making a mental note to make more descriptive issues. I think the correct way to solve this is to simplify the test to make it obvious how `RngConfig(from_dict=...)` is used.

**Comment by valentin-krasontovitsch** [comment]
XD ok gotcha!
