### ISSUE TITLE
Not all config objects handle optional values in dict

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#2567]
Some dict objects handle defaulting of values such as `AnalysisConfig`:

https://github.com/equinor/ert/blob/3f84b979b985376aade9203a6b977b9b541d8c14/res/enkf/analysis_config.py#L152-L163

while others do not, such as `QueueConfig`, do not:

https://github.com/equinor/ert/blob/3f84b979b985376aade9203a6b977b9b541d8c14/res/enkf/queue_config.py#L87-L94

**Comment by oysteoh** [comment]
Relates to #2553

**Comment by DanSava** [comment]
This might be blocked by #3801, #3918 and #2571

**Comment by eivindjahren** [comment]
We have decided that from_dict path will have defaults, so this will be resolved by #3986.
