### ISSUE TITLE
Test functions in analysis/update.hpp

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2574]
The public functions in update.hpp should be tested using catch2:

- [ ] analysis_save_parameters
- [ ] analysis_save_row_scaling_parameters
- [ ] analysis_load_parameters
- [ ] analysis_load_row_scaling_parameters
- [ ] analysis_run_analysis_update_with_rowscaling
- [ ] analysis_run_analysis_update
- [ ] analysis_assert_update_viable
- [ ] analysis_copy_parameters

**Comment by oyvindeide** [comment]
Have split this into sub issues and attached them to our current epic, so closing this.
