### ISSUE TITLE
Performant webviz-ert on-premise

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2576]
Definition of done:
Running visualizations on various cases on an RGS node should be comparable performant between the PyQt plotter and webviz-ert.

Cases to test on:
- Drogon
- HM tutorial
- at least one real asset case

This milestone we need to complete and what is focus right now:

Make an API implementation serving data from `enkf_fs` such that `webviz-ert` runs with performance comparable to PyQt on-premise. Afterwards we’ll develop the PyQt-plotter and data export to utilize the same API implementation.

Clarifications and boundaries
- A data API that serves our current needs in production and can be shared between ERT2 and ERT3.
- ERT3 data model is to be a superset of the ERT2 data model
- The same visualization solution ( webviz-ert ) for both ERT2 and ERT3 and for both Azure and on-premise users.
- How to store data in `ert-storage` is an implementation detail not yet decided. Currently we have explored and utilized `sqlite`, `postgres` and `azure blobs`. This is not set in stone and can be discussed. **Not priority of the current milestone!**.
- We do not concern ourselves too much with whether it will work well in azure at this moment
- We expect large changes to both API definition and implementation down the road.
- The data API definition implemented by dark-storage should be able to back webviz-ert (and afterwards csv_export  and PyQt plotting ) in a satisfying manner on-premise. Other consumers we don't consider at the moment.
- Language of choice is currently python , but if there is strong reasons to utilize something else in `ert-storage` , that could be brought up when the need arise.  **Not priority of the current milestone!**.
- Support for `sqlite` is currently there to make development and testing easier. If good reasons ( i.e we are hindered to use postgres features if keeping `sqlite`- this concern should be raised and we should consider dropping it.)
- It shold be possible visualizing while running ERT. Currently there is thrown quite aggressive messages when running two `enkf_main's` side-by-side. This message should be muted when we by purpose are doing this ( but kept for all other use-cases ). Everest is actually doing the same - so it should be possible to look in that direction for inspiration.

Explanations

**Azure**
ert-storage is to be our implementation of the data API definition in Azure. It will immediately take a central role, in that it will be our storage location for data that needs to be persisted. That is, ert3 will actively leverage it as its storage facility and webviz-ert
should be able to visualise results due to the data model of ert3 being a superset of ert2. Recall that one of the large differences in ert3  is that we are aiming for an explicit data flow and hence all input and all the output data you want to keep will have to be persisted.

**Data categories**
Currently, we are approaching this from the perspective that we have two fundamental data categories; numerical data and opaque data. The numerical data is data ERT can inspect the content off and retrieve numerical values from. It is explicitly labelled as such and needs to adhere to certain data formats we define. Parameters, observations, model responses, controls and other data that one would like to drive an algorithmic process on top off, or that you would like to visualise out-of-the-box with ERT, is to adhere to this format.
Opaque data is data for which ERT needs to transport and keep for the user, but for which we will not attempt to inspect the content off. Various file structures used as input for simulators and other model building tools will be treated as opaque data. Similarly with much of the output data. This will be the largest part of our total data sizes!

**Data sizes**
Input data is expected to be up to a few GB’s per realisation, while output data might be as large as a few 100 GB’s per realisation. For both input and output data we expect the numerical data to be a few GB’s at tops. Hence, the largest chunk of data will be outputted opaque data. Ensemble sizes are expected to range between 40 (small) to 1000 (large), and possibly even larger in the future…
Tested data storage technology
During the spring we did some testing of an implementation of the API definition in Azure where opaque data was persisted as blobs in blob storage and the hierarchal data and numerical data was persisted in a postgres-instance. That displayed decent performance and cost; and was hence what made us confident in moving forward. Notice that both technologies are to be considered an implementation detail, but at least we know that there are technologies available that we could use as a starting point. More information on this can be found in the DG1 report for Move2Cloud.

**Comment by markusdregi** [comment]
This work has completed.
