### ISSUE TITLE
Consider deprecating and removing "Jobs for ranking realization"

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2577]
The jobs `OBSERVATION_RANKING`, `DATA_RANKING`, `EXPORT_RANKING` and perhaps `INIT_MISFIT_TABLE` are meant to be used for ranking realizations.

Here's a link to the documentation: https://github.com/equinor/ert/blob/main/docs/rst/manual/reference/workflows/built_in.rst#jobs-for-ranking-realizations

Do we want to give users the tools to rank observations?
From my (admittedly limited) understand of ensemble methods, we don't.

ERT will hopefully soon start logging which jobs are being run which should give some nice stats for this discussion.

**Comment by dafeda** [comment]
`DATA_RANKING` was removed in commit 2169c1e116dde34de0c0ccce5e3f39832903b1e7

**Comment by dafeda** [comment]
`OBSERVATION_RANKING` was removed in commit ca2353b315457dbe674d879d081c2bbff55dab74

**Comment by dafeda** [comment]
`EXPORT_RANKING` was removed in commit 2ca6bcf2652aa0535f39b5bbfb23d6d64e34e7cb

**Comment by dafeda** [comment]
I think it makes sense to keep `INIT_MISFIT_TABLE`, so closing issue.

**Comment by oyvindeide** [comment]
> I think it makes sense to keep `INIT_MISFIT_TABLE`, so closing issue.

Misfits makes sense, but not sure this is actually used? Had a quick search, and could not find it. Misfits are available in the new plotting solution, so better to direct anyone that needs it there? I am tempted to reopen this to delete `INIT_MISFIT_TABLE`, unless you really disagree?
