### ISSUE TITLE
Possible simplification: remove inflation code

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#2606]
On of the eternal problems with the various Kalman Filter based approaches is that amount of information in observations is overestimated, leading to to severe updates and "ensemble collapse"[1]. One of the not-very-sucessfull attempts to address this in the past was by manually inflating  variance by pushing the members away from the mean. This is implemented with [inflate](https://github.com/equinor/ert/blob/main/libres/lib/analysis/update.cpp#L816) which can in my opinion be removed. Removing that will have significant ripple effects.

[1]: Ensemble collaps: that the variance among the ensemble members is far too small - they have essentially collapsed on one single member.

**Comment by oyvindeide** [comment]
Closed in: https://github.com/equinor/ert/pull/2617
