### ISSUE TITLE
analysis::inflate seemingly does nothing as use_count is always empty

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#2616]
https://github.com/equinor/ert/blob/2419a3d9670a8347b544a13e9cc81cb97235981e/libres/lib/analysis/update.cpp#L802

Incrementing the counter was removed in https://github.com/equinor/ert/commit/9bfbd4fc7d6cf95b124284d111e2c58a72717963

**Comment by joakim-hove** [comment]
Ser #2606
