### ISSUE TITLE
Cast experiment output as `RecordTree` in `ert.engine`

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#2619]
The experiment output is a List of `Record`s that belong together.
In `ert.engine._export.export()`
```
 data: List[Dict[str, Dict[str, Any]]] = []
  for iens in range(ensemble_size):
      inputs = {record: data[iens] for record, data in parameters.items()}
      outputs = {record: data[iens] for record, data in responses.items()}
      data.append({"input": inputs, "output": outputs})

  workspace.export_json(experiment_name, data)
```
This should perhaps be cast as a `RecordTree` that has a corresponding `Transformer` that could be used to save to json.
The employment of such a transformation might be hid in the `Workspace`

**Comment by verveerpj** [comment]
There is another similar case in `engine.analyze_sensitivity`

**Comment by xjules** [comment]
I think the problem here might be that the records might not be homogeneous and thus it would require us to handle at least 2 RecordTrees. An option would be just have create a RecordTree that can posses both Record types.

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
