### ISSUE TITLE
Remove all `safe_cast` and ecl-type type_id stuff from libres

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2625]
Safe-cast is a misnomer, since "safe"-casting a `void*` requires us to interpret it as an `int`, which defeats the purpose of safely casting it.

A saner alternative would be to have a `struct ecl_object { int __type_id; };` and safe cast from `ecl_object*` rather than `void*`, but that would require us to change a lot of code, and I feel it's easier to just `static_cast` directly with no checking.

**Comment by oyvindeide** [comment]
Almost all the ecl stuff is gone, so will close this issue.
