### ISSUE TITLE
Add `script/build-debug` helper script

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2626]
This script will:
1. Somehow check that `_skbuild` is correct. Or figure out if it's possible to specify an alternative eg. `_skbuild_debug`.
2. Installs build requirements from `pyproject.toml` (verifies they exist)
3. Does `python setup.py build_ext --inplace --build-type=Debug`
4. Symlinks `_skbuild_debug/**/compile_commands.json` to `{git-root}/compile_commands.json` so that we can jump around in the code
5. Maybe also detects whether ecl is compiled in debug, and merges `compile_commands.json` from it so we can navigate both `ecl` and `libres`?

**Comment by jondequinor** [comment]
For 1 and 2 you can probably use

```
import skbuild.constants

def SKBUILD_DIR():
    return "/dev/null"
```

(Weird how there's seemingly no good way of overriding that.) 

Together with `-e` and `--no-build-isolation` and the debug qualifier you could get editable install as well.

**Comment by pinkwah** [comment]
Closing as won't need
