### ISSUE TITLE
YYYY-MM-DD (ISO-8601) support in ERT configuration

### ISSUE THREAD

**Issue by berland** [equinor/ert#2639]
**Is your feature request related to a problem? Please describe.**
ERT configuration does not support dates written in ISO-8601 (YYYY-MM-DD) in configuration files and observation files.

**Describe the solution you'd like**
YYYY-MM-DD is recognized automatically alongside MM/DD/YYYY.  There is already support for iso-dates in `ecl`, in `util_sscanf_isodate`.  The function `util_sscanf_date_utc` is currently in use in ERT, and returns ok, but a negative `time_t` if given an ISO-formatted date (!). 

Supporting ISO-dates early even for ERT2 can be useful in order to be able to deprecate MM/DD/YYYY later, getting users to fix configuration files requires a long deprecation period.

**Describe alternatives you've considered**
Await ERT3 yaml configuration format for ERT, where support for ISO-8601 can be exclusive.

**Additional context**
https://equinor.slack.com/archives/CDPJULWR4/p1640196273105900

**Comment by markusdregi** [comment]
I think resolving this for ERT2 now makes sense. Especially since it has been requested by users...

I see you have already started on this @berland 👍🏻 Just make sure to bring it into the next planning as well if not resolved before that...
