### ISSUE TITLE
Test the Drogon case with last webviz-ert

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2648]
On RGS - test the new release of webviz-ert with regards to performance compared to the old pyqt plotter ( komodo bleeding should contain last changes in webviz-ert )

**Comment by oysteoh** [comment]
Using bleeding and the last changes there - i can see a huge improvement. The experience of loading a response key is somewhat  equal between the pyqt plotter and the webviz-ert. Timing is not though, i measured with a watch from click to the data was presented. Difficult and not a precise way of doing it, but approx 1,5 sec to load a key in pyqt plotter and 3,0 sec in the webviz-ert app. Seems to be fairly consistent and by that loading a drogon response key i would say takes twice the amount of time as in the pyqt plotter.

**Comment by sondreso** [comment]
I don't think this issue belongs in the ert repositry, should we move it to the team repo or webviz-ert?

**Comment by oysteoh** [comment]
the issues we need to fix is located in the ert-api so i think it should belong in ert repo.

**Comment by sondreso** [comment]
Alright. Since the title of this issue was not related to any specific issue in ert I was thinking this could be moved and new issues spawned when something specific needed to be fixed :slightly_smiling_face:

**Comment by oysteoh** [comment]
Drogon tested with acceptable performance
