### ISSUE TITLE
Pass forward parser arguments when starting storage server

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#2672]
Currently starting the `Storage` server through `run_ert_storage` will initialise the server without passing forward the `database-url`. The same is valid for the `run_webviz_ert` approach

https://github.com/equinor/ert/blob/a495b05edfb0798b928bbe0b37858368e23af6e7/ert_shared/main.py#L39-L40

**Comment by lars-petter-hauge** [comment]
I don't think the previous way of setting backend url is used anymore?

https://github.com/equinor/ert/blob/e34e7b626210e3e8b82a7b065ad189f49f642acc/ert_shared/main.py#L190-L203

I at least couldn't find it used anywhere. From looking at the commit it looks like anything that used to use it has been removed/moved. @sondreso as author of the commit adding it, anything I should look into before removing it?

**Comment by sondreso** [comment]
While my name is on the commit, I can't take credit for this specific code. This is one of the occasions where I get the (dubious) honor of creating a PR on behalf of the joint work of the entire squad :sweat_smile: See: https://github.com/equinor/ert/pull/860

**Comment by sondreso** [comment]
But if the argument is not in use, we should just remove it :shrug:

**Comment by lars-petter-hauge** [comment]
Hah, right.. Suppose it won't be the last time you're poked :P
