### ISSUE TITLE
SPE1 demo is currently broken

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2684]
**Describe the bug**
The spe1 demo silently fails on the main branch (see https://github.com/equinor/ert/runs/4772647822?check_suite_focus=true)

**To Reproduce**
1. `pip install ert`
2. `ert3 service start storage`
3. `ert3 init --example spe1`
4. `cd spe1`
5.  `ert3 run evaluation`

This results in: 
```
Error while loading stages configuration data:
5 validation errors for StagesConfig
__root__ -> 0 -> output -> keys
  extra fields not permitted (type=value_error.extra)
__root__ -> 0 -> function
  field required (type=value_error.missing)
__root__ -> 0 -> script
  extra fields not permitted (type=value_error.extra)
__root__ -> 0 -> transportable_commands
  extra fields not permitted (type=value_error.extra)
__root__ -> 0 -> output -> keys
  extra fields not permitted (type=value_error.extra)
```

**Expected behavior**
The above commands should run the evaluation. If there is a problem with the configuration the script should return a non-zero exit code (and thus fail the Github Action pipeline):

**Enviromment**
 - OS: RHEL7 and Ubuntu 20.04
 - ERT Release: main
 - Python version: 3.6 and 3.8
 - Remote/HPC execution involved: no

**Comment by markusdregi** [comment]
The reason this slipped through is that this catch does not result in a faulty exit status: https://github.com/equinor/ert/blob/6f8586239f528e3d1d9dcdb6888d0a8cbc5ce8c8/ert3/console/_console.py#L329
