### ISSUE TITLE
Investigate potentially changed behaviour on inconsistent time maps 

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2691]
There are indications during debugging of https://github.com/equinor/ert/issues/2546 that the real issue is inconsistent time maps.

The issue is created by running predictions with different report steps for the realisations as discussed in the internal [Wiki](https://wiki.equinor.com/wiki/index.php/Debugging). However, it is now reported that the GUI is hanging instead of closing down as previously.

A good start would be to try to reproduce the `inconsistent time maps` issue and see how ERT behaves now compared to earlier...

**Comment by markusdregi** [comment]
The [SPE1 ERT3 example](https://github.com/equinor/ert/tree/main/ert3_examples/spe1) produces varying report dates over the ensemble. I believe it is either straight forward or an excellent learning oppertunity to pick up the necessary pieces to produce an ERT2 setup with `inconsistent time maps`... Feel free to reach out if help is needed :)

**Comment by sondreso** [comment]
This is fixed, and inconsistent time map will no longer result in a `util_abort` that hangs the GUI.
