### ISSUE TITLE
Allow leaving runpath directories on disk for debugging

### ISSUE THREAD

**Issue by berland** [equinor/ert#2700]
The unix step uses a temporary directory and runpath that is deleted both on success and failure. This hampers debugging, and there should be a possibility to configure preservation (and thus also printing of the location) somehow.

https://github.com/equinor/ert/blob/1d3e102b111cdeb6edd855151488b3ea517f48d9/ert_shared/ensemble_evaluator/entity/unix_step.py#L101

Simplest workaround for local debugging:
```
+++ b/ert_shared/ensemble_evaluator/entity/unix_step.py
@@ -98,7 +98,10 @@ class UnixTask(prefect.Task):
             transmitter = outputs[output.get_name()]
             await transmitter.transmit_record(record)
 
-        with tempfile.TemporaryDirectory() as run_path:
+        run_path = tempfile.mkdtemp()
+        for a in [1]:
+            print(run_path)
             run_path = Path(run_path)
             self._load_and_dump_input(transmitters=inputs, runpath=run_path)
             with Client(
```

**Comment by markusdregi** [comment]
I'm afraid it is not as easy as that as the unix step will be running on a temporary file system on the compute node in Azure. Not explicitly deleting it will make debugging easier when running locally, but will not change much as of now in Azure when using a compute cluster.

A bigger discussion on debugging is probably needed... 🤷🏻
