### ISSUE TITLE
Crash when ert3 is exporting a blob record with tar-contents

### ISSUE THREAD

**Issue by berland** [equinor/ert#2715]
**Describe the bug**
Crash when exporting a record of directory type (tar-blob).

```
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3256: invalid start byte
```

**To Reproduce**
1. Add an output record to `stages.yml`:
```
  output:
    -   
      record: runpathdir
      location: .
      is_directory: true
```

that intends to store the entire filesystem at the time of a finished run. 

2. `ert3 run evaluation`
3. `ert3 export evaluation`

**Expected behavior**

No crash. Potentially the blob record  dumped to `experients/evaluation/runpathdir.tar` but that is possibly a feature request.

**Screenshots**

**Enviromment**
 - OS: Ubuntu 21.10
 - ERT release: 2.32.+++
 - Python 3.9
 - Remote/HPC execution involved: no

**Additional context**
The blob record in storage can be `curl`ed down and extracted using `tar`.

**Comment by xjules** [comment]
As of now, we store `record_type` metadata only when it concerns `RecordCollection` and `RecordTree`; hence we can't deduce that the record to be exported is a `BlobRecord`.
