### ISSUE TITLE
Progress window

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#272]
The current layout of displaying job details in a horizontal layout together with the more global view quite quickly leads to a lot of horizontal scrolling. We could consider moving to a vertical layout instead with the detailed job view underneath.

**Comment by berland** [comment]
Also wanted: Colour coding in the `status` column

**Comment by berland** [comment]
Suggestion: Clear 'start_time' and 'end_time' cells (to empty string instead of datetime.now()) for jobs where status == Waiting
