### ISSUE TITLE
Clean-up status parsing logic in the C-implementation of the queue

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2741]
While running the forward model the job dispatchers writes two files related to the status of the forward model (`STATUS` and `status.json`).

It was noticed during https://github.com/equinor/ert/pull/2706 that the C-layer of the queue no longer parses any of these files. It uses the presence and time stamp of these files to make conclusions about the state of the forward model, but that is in no way transparent from the implementation.

Hence, the content of the status files are written by the job dispatcher in Python and read only by the Forward Model logic implemented in Python and utilised by the ERT client.

I suggest that we consider making this clearer in the implementation, starting by getting an overview of the remaining usage of the status files in the C-layer. If possible, we could stop letting the C-layer have a notion of these files at all and instead use a `.<some-fitting-name>` file to use for the existence and time step verification that is currently done in the remaining implementation.

**Suggested definition of done**
The C-layer no longer have a notion of the status files of the forward model.

**Comment by valentin-krasontovitsch** [comment]
gonna start tackling this issue by documenting my findings / musings here.

> getting an overview of the remaining usage of the status files in the C-layer

so far, I've dug into `src/clib/lib/job_queue/` - there we have `job_queue.cpp`, which implements the `job_queue_struct`. That one has a `status_file` field, which is passed to `job_queue_node_alloc` upon creation of a new, well, now I get lost in the semantics again, job on a node? besides that a get method, and the pointer is freed during teardown, just the usual, i suppose.
on to `job_node.cpp` - implements `job_queue_node_struct`, which has a field `status_file`, which gets freed during teardown. during allocation of a `job_queue_node`, we have the following allocation of the status file:

```
util_alloc_filename(node->run_path, status_file, NULL);
```

I could not find ... to be continued

**Comment by valentin-krasontovitsch** [comment]
so after a live discussion with Sondre @sondreso I have learnt the following:

it is desirable that the queueing system does not read files at all for checking its own status. for instance confirming that a job is running - when the queueing system internally has the information that a job is running, then there is no need to confirm so by reading a file. in general, reading from file system is unfortunate in this situation - the file being read is written by the computing cluster running the jobs, while it is read by the instance of ert issuing the jobs, running on whatever laptop / workstation the user is sitting in front of. this raises the need for shared disk access available to both, and raises some concurrency issues (how do we check that the write is done?).

Sondre confirmed that introducing new files written by the python code which are then read by the C layer does not achieve separation of concerns, so we're gonna drop that idea and consequently PR #3795 which implemented the idea.

Ideally we should remove the reading of files from the queueing system altogether, but this appears non-trivial, as the modified timestamp of the status file is used to keep track of the progress of a job.

Oh, and finally `enkf` is the original / old name of `ert`, and is thus synonymous with `ert`.

**Comment by eivindjahren** [comment]
Tis issue will be resolved by https://github.com/equinor/ert/issues/6270
