### ISSUE TITLE
Long running ERT session started on a remote computer is going to be killed

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#2742]
**Describe the bug**
If I start ERT on a remote computer and ERT is supposed to run for 3 weeks. After three days, ERT and the remote session is killed due to inactivity.

**To Reproduce**
TBD

**Expected behavior**
TBD

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: likely any
 - Remote/HPC execution involved: yes

**Comment by sondreso** [comment]
This is a problem that should be addressed the policy of the remote computer setup, and is outside the responsibility of ert to fix. We will contact them through other channels, hence closing this issue.
