### ISSUE TITLE
Schematic diagram for updating in the analysis module

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#2743]
Different variants for updating now employs the same `initX()` but called with different parameters d71b9fe5c678878d80811a491960a31332dcb114 
Document how `initX()` is called conditioned on which updating algorithm is chosen.
Possibly in a schematic diagram.

**Comment by oyvindeide** [comment]
The code has been moved to https://github.com/equinor/iterative_ensemble_smoother and the documentation has been updated.
