### ISSUE TITLE
Remove prefix in parameters.txt

### ISSUE THREAD

**Issue by berland** [equinor/ert#275]
GEN_KW adds a prefix with the ID when parameters are dumped to `parameters.txt`

So if you have
`GEN_KW RELPERM ../templates/relperm.tmpl ../parameters/relperm.params`
and `relperm.params` contains (among others) the line
`NW CONST 2`
then `parameters.txt` will get the line
`RELPERM:NW 2`
in each realization.

The suggestion is to write
`NW 2` 
instead in parameters.txt.

This makes it easier to switch between `DESIGN_KW` and `GEN_KW` with the same template files. Dropping the prefix means that we should ensure uniquely named parameters, which is not necessary today (I think even ERT will let you reuse the same parameter in the same parameter file, that might be a bug). 

As pr. today, you cannot use a GEN_KW generated number in two different files, and the easiest workaround pr. now is to use DESIGN_KW in that case, which can be cleaner if the namespace is dropped.

Internal discussion: https://www.yammer.com/statoil.com/#/Threads/show?threadId=1222922541

**Comment by markusdregi** [comment]
Thank you for the suggestion @berland! Unfortunately, the layout of this file is a crucial part of the _ERT_ api and it could have severe consequences to change this. In addition, I would like to point out that this file is most likely to disappear in _ERT 3.0_ (more than a year into the future). A more interesting discussion to have is to figure out what you would like to achieve and then build this around the structured part (the keys not containing `:`) in the `parameters.json`.

**Comment by markusdregi** [comment]
Namespaces are a good thing. In addition we will be breaking the parameter output format in ert2. Instead, this should be considered in the parameter output format in ert3. I trust that we will be able to gather relevant feedback when necessary.
