### ISSUE TITLE
ERT3 monitoring

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2758]
**Introduction**
Until recently ERT3 provided no feedback while running an ensemble. As a temporary solution the following PR was merged to support a workshop: https://github.com/equinor/ert/pull/2732.

In general I would like to get feedback on how far the evaluation has progressed, how many realisations have completed, failed etc.

**Issues**
- [x] Use the cli monitoring in ert3
  - [x] #2894
  - [x] #2895
- [x] #2896

**Definition of done**
ERT3 supports monitoring the evaluation similarly to ERT2. In particular, since the evaluator and its events is utilised by both ERT2 and ERT3 the monitoring implementation should be possible to share. The most realistic and inline with ERT3 currently being CLI-only is to make the CLI monitor shared between ERT2 and ERT3 such that it is utilised and further developed by both versions.

Optional: Move monitoring code into the `ert` module, and add type hinting etc.

**Note**
If there is momentum to port the Qt-monitor as well; that is of course great :)

**Comment by lars-petter-hauge** [comment]
I would like to add that adding records to storage can take a considerable amount of time. I believe we do not have any kind of monitoring in this phase for ert2 (as it isn't really relevant).

Especially large directories (many files) are time consuming, both to tarball and to send (so simply only letting the user know when it's sending will still result in a long waiting time without any response from ert, while creating the tarball).

**Comment by markusdregi** [comment]
That is an excellent point @lars-petter-hauge 👍🏻 It should be discussed on launch whether we want to include it into the milestone. It would be valuable for our users!

> I believe we do not have any kind of monitoring in this phase for ert2 (as it isn't really relevant).

That is not entirely true, but it is a bit complicated. If we split this into moving input data to the forward model and output out of the forward model again (as those are the two concepts that carry over from ert2 to ert3), then large input data is largely covered my copying files within the forward model itself. Which implies that the monitoring of the forward model also takes care of monitoring copying and hence you do to some extent have monitoring.

For output data there are explicit states for each realization dictating whether it is loading data or that has completed :)

**Comment by markusdregi** [comment]
I did not interpret it that way either, I just wanted to point out that it does and that we actually do monitor both large input and parts of the large output in different ways ;)

**Comment by sondreso** [comment]
This milestone is now complete
