### ISSUE TITLE
ERT3 - failing realisations

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2759]
**Introduction**
A natural part of evaluating ensembles is to have failing realisations. It is even part of the [concepts of evaluation](https://ert.readthedocs.io/en/latest/developer_documentation/concepts.html#evaluating-an-ensemble).

Currently, ERT3 will fail with a runtime exception if a realisation failed: https://github.com/equinor/ert/blob/612dca1d8e40465fbdc2de28e39155c17cd3f1b2/ert3/evaluator/_evaluator.py#L30-L31

**Definition of Done**
ERT3 should be capable of handling failing realisations in that if some realisations fails it should:
- present relevant information to the user, including which realisations failed,
- store the data for the successful realisations such that it is possible to export and visualise the successful realisations,
- allow to rerun only the failed realisations of the experiment via something like `ert3 run evaluation --rerun-failures`,
- expose the option for how many retries an ongoing run should do for a failing realisation (this probably requires passing options to `prefect`) and
- consider supporting to store the runpath of a failing unix step as a blob for local debugging.

**Comment by sondreso** [comment]
Given the current development plan of ERT3 this is no longer relevant
