### ISSUE TITLE
On the usage of mimes for validation of data passing

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2764]
**Introduction**
Currently, there is a `mime` type attached to input records of an ensemble (configured in `ensemble.yml`) and for input and output records of all steps (configured in `stages.yml`). This information is used to validate that the data being passed into the forward model (root stage) is consistent with the expected data of that stage. This is however not the intended usage of mimes and should be changed.

**The role of mimes**
A mime should be used to indicate serialisation and deserialisation format at hand when loading from disk or persisting to disk.

**Consequences**
Hence, it makes sense to specify a mime type when loading input records from disk. That is, when the `ert3 record load` functionality is being used or the `resources.<some-resource>` in `ensemble.yml`. This indicates the data format of the content that is to be loaded. However, when records are fetched from storage or `parameters.yml` via the `storage.<record-name>` or `stochastic.<parameter-name>` it makes no sense to dictate the mime type as the data has already, or will be created, under the hood without any interaction with disk.

Similarly, it makes sense that a unix step has to specify the mime type of all its input and output records as they are respectively being persisted to disk or loaded from disk. But, a function step is not doing this and should hence not have mime types configured for neither its input nor output records.

This also entails that it should be perfectly fine to have a different mime types when loading records prior to the ensemble evaluation and when persisting the same record in a unix step. That is, you could load a record persisted as json and write it as yaml (or csv whenever we support that).

Notice that it is the role of the transformation to convert records between its record representation and whatever the mime type indicates that it can be serialised to (or from).

Last, the validation of record types when being passed into the forward model (configured in `ensemble.yml`) or between two steps it should be the consistency of record type that is validated,  not the specified mime types.

**Comment by BjarneHerland** [comment]
Get this warning occasionally, then timeout

https://github.com/equinor/ert/runs/5344286386?check_suite_focus=true

**Comment by jondequinor** [comment]
It's harmless, and also slated for removal.

**Comment by jondequinor** [comment]
- mime is now a property of a file transformation
- transformations are required for 1) IO in unix steps, 2) stuff loaded from `resources` 
- transformations are optional for functions steps, and optional for `stochastic` and `storage` sources
- mime is not exclusively used to check compatibility of inputs/outputs—more data is used to check compatibility

Hence this should be closed.
