### ISSUE TITLE
Improvement when parsing ert-config 

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2766]
When parsing arguments for forward model jobs or workflow jobs we see some strange behaviour when escaping certain characters:
- spaces works only in double quotes
- commas works only with single quotes 

Only one should be necessary 
```
FORWARD_MODEL REPLACE_STRING(<FROM>='some, thing', <TO>="some stuff", <FILE>=file.txt) : success
FORWARD_MODEL REPLACE_STRING(<FROM>='some, thing', <TO>='some stuff', <FILE>=file.txt) : -> some stuff becomes somestuff
FORWARD_MODEL REPLACE_STRING(<FROM>="some, thing", <TO>="some stuff", <FILE>=file.txt) : util abort
```

**Comment by ManInFez** [comment]
I am not sure this is possible to solve without major breaking of current config parsing.

**Comment by markusdregi** [comment]
Spaces outside of quotes also behaves oddly. For instance:
- `<OPTIONAL_ARGUMENT>= stuff` will be ignored and
- `<FAULTY_ARGUMENT>=part-included part-excluded` will have the second part ignored.

**Comment by verveerpj** [comment]
I have added these 5 examples to the test for the C function that parses these strings, and they work fine.

One of the following things could be going on:
1. That C function (`subst_list_add_from_string`) is maybe not used anymore.
2. The string is pre-processed somewhere before calling `subst_list_add_from_string`.
3. The string is post-processed somewhere after calling `subst_list_add_from_string`.

I will try to figure out which one it is...

**Comment by verveerpj** [comment]
It seems to be number 2. `subst_list_add_from_string` receives a modified string. Somewhere the arguments are split and then put together again, incorrectly.

**Comment by verveerpj** [comment]
It turns out that when the config file is read, the lines are split by space and double quotes (`"`) are removed. Later when a `FORWARD_MODEL` key is detected, the parts are simply concatenated before further processing. So, in the process double quotes and whitespace are lost.

It will be a bit of a job to fix that while making sure that nothing breaks elsewhere...

**Comment by berland** [comment]
Double quotes are necessary in https://fmu-docs.equinor.com/docs/ert/reference/forward_models.html#ECL2CSV-examples in order to escape the comment characters `--`.

**Comment by oysteoh** [comment]
Will be fixed as part of rewriting the config parser. This issue should be used as reference to things we need to fix as part of the work.

**Comment by mortalisk** [comment]
There is a prototype for a new parser in #4720 where a test `itest_quotations_in_forward_model_arglist` is added to document the new possible behaviour for this.

**Comment by oysteoh** [comment]
This one solved now with the merge of the new parsing @mortalisk ?

**Comment by oysteoh** [comment]
This will be solved when the new parser replacing the old one and is used by default. Not actionable issue
