### ISSUE TITLE
Remove ThreadPool

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2774]
Following #2650 it seems like the current approach to threads leaves a lot to be desired. My biggest argument is that it's not a [Thread pool](https://en.wikipedia.org/wiki/Thread_pool) but rather an array of threads that are created and joined immediately after each other.

The current implementation requires type erasure (casting to `void*`) and has unsubstantiated performance claims.

In the future we may implement some other _existing_ C++ library to do the job of managing a thread pool or multi-threaded workloads. However, when that time comes, there should be a good case in favour of increasing the complexity of the code.

**Comment by BjarneHerland** [comment]
#2818 may be a candidate for introducing a new thread-pool library

**Comment by pinkwah** [comment]
I would note that all of `block_fs` thread pool usage makes little sense. All we do there is create 32 directories split over 4 threads. We can just create those files single-threadedly.

**Comment by BjarneHerland** [comment]
https://github.com/equinor/ert/issues/2819

**Comment by pinkwah** [comment]
Feel free to close this issue and spawn smaller actionable issues. Removing all of threadpool might be a far too large task to do in a single PR.

**Comment by BjarneHerland** [comment]
> I'll make `analysis/update.cpp` serial and assess impact on performance, if any.

"Anecdotal evidence" using existing tests indicates that dropping threads in save/load has minimal impact on performance.

Then there is the issue of threading in the matmul-operation. For this we should probably also understand why BLAS is not used.

Will try to apply results of https://github.com/equinor/ert/pull/2704 to get a realistic scenario for benchmarking.

**Comment by BjarneHerland** [comment]
> In the future we may implement some other _existing_ C++ library to do the job of managing a thread pool or multi-threaded workloads

Do you have any suggestions? I'd prefer using [std::future](https://en.cppreference.com/w/cpp/thread/future) or similar but as of now it has shortcomings. Boost might [deal with these](https://www.boost.org/doc/libs/1_78_0/doc/html/thread/synchronization.html#thread.synchronization.futures.reference.wait_for_any) if we want to depend on it though, and it also provides a [proper thread_pool](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/thread_pool.html) which probably will serve as a drop-in in our codebase.

**Comment by BjarneHerland** [comment]
@pinkwah  [this list ](https://en.wikipedia.org/wiki/Futures_and_promises#List_of_non-standard,_library_based_implementations_of_futures) may be a nice starting-point if we want to pick some 3rd party library to replace our home-spun threadpool
