### ISSUE TITLE
NoPortsInRangeException failure on Jenkins

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2778]
I received the below exception in CI on Jenkins. It is unrelated to my work and both the test and the code appears untouched for months. Hence, I expect it to either have been flaky for some time or be affected by other changes.

**Stacktrace**
```
_______________________ test_find_available_port_forced ________________________

unused_tcp_port = 57880

    def test_find_available_port_forced(unused_tcp_port):
        custom_range = range(unused_tcp_port, unused_tcp_port)
        host, port, sock = port_handler.find_available_port(
>           custom_range=custom_range, reuse_addr=True
        )

/tmp/jenkins-scout-f_scout_ci/workspace/komodo_testing/ert-custom-script-pr@2/test-root/tests/ert_tests/shared/test_port_handler.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

custom_host = None, custom_range = range(57880, 57880), reuse_addr = True

    def find_available_port(
        custom_host: Optional[str] = None,
        custom_range: Optional[range] = None,
        reuse_addr: bool = False,
    ) -> Tuple[str, int, socket.socket]:
        current_host = custom_host if custom_host is not None else _get_ip_address()
        current_range = (
            custom_range if custom_range is not None else range(51820, 51840 + 1)
        )
        if current_range.start == current_range.stop:
            try:
                return (
                    current_host,
                    current_range.start,
                    _bind_socket(
                        host=current_host, port=current_range.start, reuse_addr=reuse_addr
                    ),
                )
            except PortAlreadyInUseException:
                pass
        else:
            attempts = 0
            while attempts < current_range.stop - current_range.start:
                try:
                    attempts += 1
                    num = random.randrange(current_range.start, current_range.stop)
                    return (
                        current_host,
                        num,
                        _bind_socket(host=current_host, port=num, reuse_addr=reuse_addr),
                    )
                except PortAlreadyInUseException:
                    continue
    
>       raise NoPortsInRangeException(f"No available ports in predefined {current_range}.")
E       ert_shared.port_handler.NoPortsInRangeException: No available ports in predefined range(57880, 57880).

/tmp/jenkins-scout-f_scout_ci/workspace/komodo_testing/ert-custom-script-pr@2/test-kenv/root/lib64/python3.6/site-packages/ert_shared/port_handler.py:52: NoPortsInRangeException
```

**Link to job**
https://ci.equinor.com/scout/job/komodo_testing/job/ert-custom-script-pr/6142/console

**Comment by markusdregi** [comment]
First experienced here: #2755

**Comment by lars-petter-hauge** [comment]
Running this with `pytest-repeat`, looks to take more than 1000 tries, so run it with 10 000:

`pytest --count=10000 -x tests/ert_tests/shared/test_port_handler.py::test_find_available_port_forced`

With 3 tries of the above command it failed after: 4080, 1450 and 1770 tries.

**Comment by lars-petter-hauge** [comment]
I'll just add the possibility that we could rerun the test n times if it fails. I tried with `pytest-rerunfailures` and specified that it can retry once. Out of a 10 000 number tries, it had to retry two of the tests, both succeeded on the second attempt.

I don't particularly like solving flaky tests like that though.. And it's a bit annoying if it is the fixtures fault, as the codebase then isn't flaky..

**Comment by jondequinor** [comment]
Should we migrate to `unix_connect` and `unix_serve` for tests where the websocket is not under test?

It's an admission that our approach to port selection isn't really working well, but well enough for most cases. And I think that makes sense given the constraints we're facing.

**Comment by lars-petter-hauge** [comment]
We had some discussion on video and did some more testing. Here follows the conclusions:

The `unused_tcp_port` checks against localhost when providing an unused port:

https://github.com/pytest-dev/pytest-asyncio/blob/9246f5825f589ff01f1c67620ce34bdc416c5af3/pytest_asyncio/plugin.py#L490
```
 def _unused_port(socket_type: int) -> int: 
     """Find an unused localhost port from 1024-65535 and return it.""" 
     with contextlib.closing(socket.socket(type=socket_type)) as sock: 
         sock.bind(("127.0.0.1", 0)) 
         return sock.getsockname()[1] 
```

In `find_available_port`, we use our public ip address if a `current_host` is not provided (as given in `_get_ip_address`).

Using the public ip address is fine in production, but for unit testing paired with `unused_tcp_port` we have to specify localhost.

Tested hardcoding localhost and ran 30 000 runs without a failure.

**Comment by BjarneHerland** [comment]
http://ci.equinor.com/scout/job/komodo_testing/job/x-ert-ERT/3390/

**Comment by BjarneHerland** [comment]
https://github.com/equinor/ert/runs/5510989778?check_suite_focus=true

**Comment by BjarneHerland** [comment]
http://ci.equinor.com/scout/job/komodo_testing/job/x-ert-ERT/3416/
