### ISSUE TITLE
Add docstring and type hints to `_Ensemble`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2787]
An `Ensemble` in the data assimilation domain is a collection of realisations that represent probability distributions.

`_Ensemble` as implemented has a member called `self._reals` but also other members.

In my opinion, `_Ensemble` needs a docstring that explains why we are defining an ensemble to be something more than a collection of realisations, and what the different parameters are.

https://github.com/equinor/ert/blob/4f176e052a50b8d10c5489abfd372f17e6f97f18/ert_shared/ensemble_evaluator/ensemble/base.py#L80-L86

**Comment by oyvindeide** [comment]
The type hints have been added, but there are no doc strings, something you can add @sondreso?

**Comment by oyvindeide** [comment]
Related to: https://github.com/equinor/ert/issues/2816

**Comment by dafeda** [comment]
`_Ensemble` is no more.
