### ISSUE TITLE
Make all Ensembles cancellable 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2790]
Currently Both the `Legacy` and `Prefect` ensemble is cancellable, and only the test ensemble is not. Making all ensembles cancellable would greatly simplify logic related to stopping, error handling and cleanup. Currently only the `TestEnsemble` isn't cancellable, so this change should only affect tests. 

See also: https://github.com/equinor/ert/pull/2786

**Comment by oyvindeide** [comment]
`TestEnsemble` no longer exists, so closing this.
