### ISSUE TITLE
Use abstract classes instead of function pointer tables for observation types

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#2792]
The following types should be unified under a single abstract class (and expose these classes to Python via pybind11 instead of CWrap).

- `gen_obs`
- `summary_obs`
- `block_obs`

The purpose for doing this is to allow code reuse. For example, each of these types have to deal with active lists (a list of indices representing active observations). The current solution is to have code duplication, when it could be unified.

**Comment by oyvindeide** [comment]
These are now dataclasses (except for block_obs, which has been deleted), will close this as not very relevant anymore.
