### ISSUE TITLE
Let the user use progress window to debug forward models

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#280]
It should be possible to do basic debugging of your forward model using the progress window. To achieve this one needs to support:
  - #274 (displaying the error messages dumped to file),
  - as well as keeping the data available also after the end of an ensemble has finished (possibly with all the realizations failing).

**Comment by markusdregi** [comment]
@ManInFez Is not all of this done?

**Comment by ManInFez** [comment]
I found that the fix I did was never merged in. I have a new pr on this now
