### ISSUE TITLE
Remove matrix_alloc_column_compressed_copy

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2814]
**Describe the bug**
The function `matrix_alloc_column_compressed_copy()` in `libres/lib/res_util/matrix.cpp` does not seem to be used anywhere except from `libres/old_tests/res_util/test_ert_util_matrix.cpp`

**Comment by BjarneHerland** [comment]
Can probably get rid of `matrix_column_compressed_memcpy()` in the same effort

**Comment by oyvindeide** [comment]
This has been removed :+1:
