### ISSUE TITLE
Ignore .ert folder when initializing ert3 workspaces

### ISSUE THREAD

**Issue by berland** [equinor/ert#2823]
When developing, there might be ert3 workspace remnants in a tainted repo. The `ignore`  option for `shutil.copytree()` can be used to skip the `.ert` folder,  which we never want to copy when initializing an example.

https://github.com/equinor/ert/blob/e5fa49ca0a60d38cc33d870ceeac2746f569404b/ert3/console/_console.py#L215

**Comment by eivindjahren** [comment]
Closing because it is related to ert3, which is no longer the direction taken by the project.
