### ISSUE TITLE
Define ERT_HAVE_THREAD_POOL in the right place

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2827]
In `libres/lib/res_util/matrix.cpp` ERT_HAVE_THREAD_POOL is used to enable e.g. definition of `matrix_inplace_matmul_mt2()`

https://github.com/equinor/ert/blob/9d5b76259bf720e19a5bb6ba3d1ac49a991b46f7/libres/lib/res_util/matrix.cpp#L986

However, ERT_HAVE_THREAD_POOL is not set in the ERT-repo but in CMakeLists.txt in ECL

https://github.com/equinor/ecl/blob/293875faebdf2c1c39e764752417007eac2f7f55/lib/ert_api_config.h.in#L6

and then picked up by `libres/lib/res_util/matrix.cpp` via

https://github.com/equinor/ert/blob/9d5b76259bf720e19a5bb6ba3d1ac49a991b46f7/libres/lib/res_util/matrix.cpp#L34

which seems slightly backwards.

**Comment by dafeda** [comment]
The `#ifdef ERT_HAVE_THREAD_POOL` part is deleted in the PR introducing Eigen:

https://github.com/equinor/ert/pull/2872

We might perhaps get rid of `#include <ert/util/ert_api_config.hpp>` as well.

**Comment by BjarneHerland** [comment]
Seems to be unused now. Created https://github.com/equinor/ecl/issues/869 to remove from ECL.
