### ISSUE TITLE
ERT3 init hits the proxy with on-prem environment setup

### ISSUE THREAD

**Issue by berland** [equinor/ert#2837]
**Describe the bug**
If `ert3 init` hits the proxy when accessing `127.0.0.1`, then it will get a redirect response that it won't (?) and cannot follow. 

**To Reproduce**
It should be okay to have the environment variable(s) `http_proxy` pointing to a real proxy, but the env variable `no_proxy` should take care the exception for the loopback address.

On-prem, in a bash setup, this is a possible environment (not intentionally user-manipulated):
```
[havb@be-lx895926] $ env | grep -i no_proxy
NO_PROXY=localhost,127.0.0.1
no_proxy=localhost,127.0.0.0/8,::1
```

That these are not equal, should be regarded as a setup bug. Which of these variables are used, varies by application. Python prefers the lower-case version. Python `requests` library  does not support CIDR blocks like `127.0.0.0/8.`

With `http_proxy` defined, and `no_proxy` as above, `ert3 init` fails with
```
$ ert3 init
Failed to fetch from experiments. Response: <HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>

Traceback (most recent call last):
    [...]
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Workarounds**

`export no_proxy=localhost,127.0.0.1`

or

add `http://localhost:51820` as the first entry in `storage_server.json`.

**Expected behavior**
ERT should avoid using the proxy.

**Enviromment**
 - OS:  RHEL7
 - ERT: 2.32~git
 - Python version 3.6
 - Remote/HPC execution involved: no

**Additional context**

See https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

**Comment by sondreso** [comment]
Closing this since this is a error in the environment configuration, and something that is not the responsibility of ert
