### ISSUE TITLE
Investigate and clean up threading in update.cpp

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2839]
The file `libres/lib/analysis/update.cpp` uses thread_pool in two different ways

1. load and save parameters
2. update the A matrix in `run_analysis_update_without_rowscaling()`

Loading/saving parameters are clearly IO-bound and depends on responses from whatever storage-system is used. Must be benchmarked on relevant platforms (RGS-node, possibly cloud).

**Comment by BjarneHerland** [comment]
@oyvindeide  I believe your squads recent activities makes this obsolete?

**Comment by oyvindeide** [comment]
The first part has been solved, but point 2 on your list is still active, we can add it to our TODO though as it fits in nicely, thanks for notifying!

**Comment by dafeda** [comment]
No more threading once https://github.com/equinor/ert/pull/2872 is merged I think.

**Comment by BjarneHerland** [comment]
@oyvindeide Did you guys finish the second part also with the migration to Eigen?

**Comment by oyvindeide** [comment]
Yes, so this issue was solved as a part of #2872
