### ISSUE TITLE
Investigate and clean up threading in block_fs_driver.cpp

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2843]
The file libres/lib/enkf/block_fs_driver.cpp uses thread_pool in the dtor for `ert::block_fs_driver`

https://github.com/equinor/ert/blob/d6cd336e67a9070ea48a7f062e6fda3690e5ef72/libres/lib/enkf/block_fs_driver.cpp#L236-L247

to write index-files and clean up here

https://github.com/equinor/ert/blob/fcaa73d9727e055cc786c86a7971719563e91b50/libres/lib/res_util/block_fs.cpp#L1237-L1247

The `enkf_fs_type` (aka `enk_fs_struct`) holds three such objects in `unique_ptr`s

https://github.com/equinor/ert/blob/fcaa73d9727e055cc786c86a7971719563e91b50/libres/lib/enkf/enkf_fs.cpp#L153-L155

which are cleaned up at this point

https://github.com/equinor/ert/blob/fcaa73d9727e055cc786c86a7971719563e91b50/libres/lib/enkf/enkf_fs.cpp#L578

I.e. the dtors for the `ert::block_fs_driver` objects run at the end of `enkf_fs_umount(enkf_fs_type *fs)`

**Comment by BjarneHerland** [comment]
There is in fact a second threadpool in `block_fs_driver`

https://github.com/equinor/ert/blob/d6cd336e67a9070ea48a7f062e6fda3690e5ef72/libres/lib/enkf/block_fs_driver.cpp#L272-L280

**Comment by BjarneHerland** [comment]
@joakim-hove do you have input to what we can expect for `this->num_fs`? Is this the hard-coded value 20 (or similar)?

**Comment by joakim-hove** [comment]
The point about this is to distribute the different realuzations over different file system directoeies - so that realuzation `iens` is stored in fs/directory `,iens mod num_fs`.

The actual value used is for all practical purposes hardcoded to 32 (I think).

**Comment by BjarneHerland** [comment]
Thanks for useful info. I'll try to track down where this value is set.

**Comment by joakim-hove** [comment]
> I'll try to track down where this value is set.

It is written to the "mountfile" [here](https://github.com/equinor/ert/blob/main/libres/lib/enkf/block_fs_driver.cpp#L282) and that function again is invoked [here](https://github.com/equinor/ert/blob/1645f3ea1699aee1ebbd8219758c574b51aef1ae/libres/lib/enkf/enkf_fs.cpp#L365).

**Comment by BjarneHerland** [comment]
There are 3 of these `ert::block_driver` -objects in use here
https://github.com/equinor/ert/blob/1645f3ea1699aee1ebbd8219758c574b51aef1ae/libres/lib/enkf/enkf_fs.cpp#L154-L156
The two representing `dynamic_forecast` and `parameter` manage 32 files/directories each, while the one representing `index` only manages 1 file.

The maximum parallellism we can achieve here is thus 32 simultaneous updates, but since the thread-pools are sized to 4, current code achieve less. It will not exhaust a modern system to let 32 updates run simultaneously.

Below are results from a simple benchmark which just mounts and immediately umounts one case, run with pytest-benchmark on RGS using the snake_oil-example as well as a large synthetic benchmark sized like described [here](https://github.com/equinor/scout/issues/524)
```
             | snake_oil | large poly |
original     | 40ms      |  1.32s     |
std::future  | 34ms      |  0.34s     |
sequentially | 19ms      |  2.47s     |
```
Removing all use of threads and just use the call-thread performs best on the small snake_oil example, but not on the larger example. Using `std::future` with async scheduling reduces time significally on the large example.

Hence, the proposed solution is to replace the thread-pool with `std::future` and leave guidelines in code for how many files/directories should be used.
