### ISSUE TITLE
Transformation that converts design matrix into records

### ISSUE THREAD

**Issue by xjules** [equinor/ert#2847]
When working on doe (design of experiment) it is currently quite cumbersome to read the parameters from the design matrix file (eg. by means of an external job) and then create parameter json representation (one by one) in order to load them later on explicitly as records. Therefore it would be meaningful to have a transformation that reads such a design matrix csv file and does the parameter records automatically.

**Comment by berland** [comment]
For reference, this is the corresponding code for ERT2: https://github.com/equinor/semeio/blob/main/semeio/jobs/design2params/design2params.py

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project. Feel free to reopen if still relevant.

**Comment by sondreso** [comment]
This one relates to code in the `ert.data` package and is still relevant

**Comment by sondreso** [comment]
Closing in favor of https://github.com/equinor/ert/issues/4656
