### ISSUE TITLE
Ensemble smoother module

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2858]
**Introduction**
During recent work the implementation of the analysis module and its interaction with core ERT (in particular `EnKFMain`) got quite some love ❤️ In this milestone we would like to continue that work by honing out a module that allows for natural and easy interaction with the ensemble smoother algorithms. Preferably, also in Python 🐍

**Module**
The various smoother based history matching algorithms are gathered in a separate module that we'll call `ensemble_smoother` for now and are exposed as part of a corresponding C++ namespace. In particular, it should be possible to access:

- `ensemble_smoother::simple`
- `ensemble_smoother::iterative`
- `ensemble_smoother::multiple_data`

Notice that the ensemble smoother and iterative ensemble smoother implementations currently reside within the analysis module and that achieving the above is mainly a question of refining the purpose of the module from `analysis` to `ensemble smoothers`. The ES-MDA algorithm however is partly implemented in the run models and it might be a good idea to gain some experience with es and ies, as well as some run model experience, before attempting to move the es-mda implementation as well.

**The coupling of ensemble smoother**
Currently, the analysis module is aware of central ERT concepts, including the storage implementation. Ideally, the ensemble smoother should only be concerned with numerical data at an abstraction level that makes it unaware of the mechanism that stores the results. On the other side, there is most likely a need to lazily load the data needed to avoid loading all the data into memory at once. These are requirements that we need to balance.

I suggest that we define interfaces for the data structures passed to the smoothers, either in the smoother module or in the `ert.data` module that allows for representing the input and output data of the smoother. And that we afterwards implement this interface on top of `enkf_fs`, such that the smoothers are still able to read and write the data it should, but now unaware that these data stems from or ends up in storage.

In particular, this should make the ensemble smoother implementations independent and unaware of the rest of ERT, besides potentially depending upon `ert.data` (which again should be considered a fundamental module in ERT not depending on any other module).

**Ease of using the smoothers**
To ease future usage, writing tests and get a feeling for the abstraction above I suggest that we consider ease of using the smoother directly from Python as a guiding metric. That is, given that you have some relevant data in a standard Python numerical data structure (data frames, numpy matrix or similar); how natural is it to build the necessary
data structures, pass them to any of the smoother implementations and retrieve the results?

**The smoothness of no side effects**
Above we described how we aim at passing the smoothers the handles it needs as an abstract data handle with an as narrow scope as possible target towards numerical data operations. In addition to that we should aim at all the smoother implementations being without side effects; that is, it should not persist any state beyond what the data handles allows it to.

For the IES implementation this has consequences, as it needs to do some book keeping, between the different iterations. That is, it creates data at the 0th call that is needs a the 1st call to behave as expected. This should be solved by the IES implementation (and possibly the other smoothers) returning a book keeping data structure with the intent; if you want me to behave as expected at next iteration, please pass me this book keeping data as part of my input.

The benefits of this are many; it allows for robust persistence of book keeping without putting storage responsibility on the analysis module, it makes testing easier and it makes restarts or continuations of experiments possible.

**Comment by joakim-hove** [comment]
> Currently, the analysis module is aware of central ERT concepts, including the storage implementation.

That might be splitting hairs; and I might miss the essential point. But I actually disagree with the statement above. The function `smoother_update()` in `update.cpp` is aware of the storage structures; it is the responsability of this function to assemble data from storage and pass it as matrices to the lowest level analysis functions. 

Maybe an alternative way to rephrase it is that the storage access and matrix assembly which currently happens in `smoother_update()` should be lifted up in the stack/reorganized/... Observe that in the `smoother_update()` function the storage access / matrix assembly is independent of the analysis approach used later, I think that is a valuable point to maintain for a refactor.

**Comment by markusdregi** [comment]
You are completely right @joakim-hove in that access to storage does not go very deep into analysis module, but `update.cpp` does currently reside within the analysis folder 🤷🏻 The idea would be that (I) knowledge of storage technology and ability to represent it as an abstract, but limited numerical data handles, (II) using those handles to create needed matrices (in-memory) and (III) running the analysis, are separated concerns where the two last resides within the smoother module, while the first is external to the analysis module.

**Comment by dafeda** [comment]
> On the other side, there is most likely a need to lazily load the data needed to avoid loading all the data into memory at once.

Do we today have a way of doing a global update without loading all data into memory at once?

**Comment by dafeda** [comment]
We had a discussion where we used the attached image as guide.
Here I summarise what I think we ended up concluding.
I've probably made a mistake here and there, but I think it is useful to try and design functions and run models using the algorithm itself as guide.

```python
W_{i+1} = calculate_W(A, D, W_{i})
```

`calculate_W` performs steps 5-9.

The new posterior can then be calculated by

```python
X_{i+1} = I + W_{i+1} / Sqrt(N - 1) # Step 10
A = AX_{i+1} // Step 11
```

At this point we might want to check convergence by

```python
X_{i} = I + W_{i} / Sqrt(N - 1)
if (Norm(X_{i+1} - X_{i}) < eps): # Do something
```

A run model might then look something like

```python
A = initialize_ensemble(nparams, ens_size)
d = fetch_observations()
D = measurement_ensemble(d, ens_size)
W = np.zeros(nparams, ens_size)
X_prev = I + W / sqrt(N - 1) 

for range(i_max):
  W = calculate_W(A, D, W)
  X_new = I + W / sqrt(N - 1)
  A = A @ X_new
  if (np.norm(X_new - X_prev) < eps): # Do something, break I guess
  # Run forward model
  A = g(A) # The function g represents for example Eclipse.
```

![ies_image](https://user-images.githubusercontent.com/45088507/153350357-1388712d-1ba2-4bda-8287-bbfb5d24bfed.png)

**Comment by oyvindeide** [comment]
All the issues in this milestone have been closed now, so closing the epic.
