### ISSUE TITLE
Investigate speed gain of using multi thread for matrix multiplication

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2866]

**Comment by dafeda** [comment]
In the switch to Eigen, we are no longer using multi threaded multiplication, so I think this issue can be closed.

**Comment by BjarneHerland** [comment]
@dafeda  As part of the Eigen-switch, perhaps you would wrap up #2827 as well?

**Comment by oyvindeide** [comment]
Closed by implementing Eigen
