### ISSUE TITLE
Replace serialization package with transformations

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#2880]
There's currently some conflict when it comes to _serde_ of numerical data. Namely that `mime` is not the pivotal thing for deciding how serialize. I can very well have a `application/octet-stream` full of summary keys.

Additionally, serialization in itself isn't very useful, what we really want is transformations.

I suggest we replace everything in the `serialization` package.

**Comment by oyvindeide** [comment]
Closing as related to ert3
