### ISSUE TITLE
Possible void return 

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2882]
This code
https://github.com/equinor/ert/blob/1645f3ea1699aee1ebbd8219758c574b51aef1ae/libres/lib/analysis/analysis_module.cpp#L72-L77
may return void when a pointer is expected - unsure how Python/CWrap copes with this.

Should probably use one of those smoothers as default, or at least return NULL.

**Comment by joakim-hove** [comment]
There is "a fix" for that here: https://github.com/equinor/ert/pull/2855

**Comment by BjarneHerland** [comment]
> There is "a fix" for that here: #2855
