### ISSUE TITLE
Move cli monitoring from `ert/ert_shared` into `ert/ert`

### ISSUE THREAD

**Issue by berland** [equinor/ert#2894]
* Add type hinting
* Refactor ert2 pull this code from a new location
* Move/refactor existing tests.

**Comment by sondreso** [comment]
Why was this closed @Blunde1? :thinking: Is it not still a part of https://github.com/equinor/ert/pull/2960

**Comment by Blunde1** [comment]
Oh, it is still part of #2960 !
