### ISSUE TITLE
Create tracker events in ert3

### ISSUE THREAD

**Issue by berland** [equinor/ert#2895]
* Create a dummy `BaseRunModel`, see API below
* Add `create_tracker()` in ert3 console

The `BaseRunModel`-like object needs to implement the following API:

- `isFinished() -> bool`: a method indicating whether or not the experiment is done. Since there's nothing beyond evaluating ensembles, this is `true` as soon as prefect finishes and the results are stored.
- `teardown_context() -> None`: a noop for ert3
- `hasRunFailed() -> bool`: a method which returns `true` if something failed
- `getFailMessage() -> Optional[str]`: a method which may return an error message in the case of failure
- `getPhaseName() -> str`: Set to `Evaluating...`?
- `currentPhase() -> int`: Set to `0`.
- `phaseCount() -> int`: Set to `1`.
- `isIndeterminate() -> bool`: whether or not we cannot determine progress. Always `false` for the time being.

**Comment by xjules** [comment]
Having a question here: Shall we employ `ert_shared.cli.monitor.Monitor` that consumes the tracker?
Something like this?
```python
        config = EvaluatorServerConfig()
        tracker = EvaluatorTracker(
            DummyBaseRunModel(),
            config.host,
            config.port,
            1,
            0,
            token=config.token,
            cert=config.cert,
        )
        monitor = ert_shared.cli.monitor.Monitor(out=out, color_always=False)
        monitor.monitor(tracker) 
```

**Comment by jondequinor** [comment]
If possible, yes. Then we _should_ be able to get stuff like

```
    Waiting         0/100
    Pending         0/100
    Running        90/100
    Failed          0/100
    Finished       10/100
    Unknown         0/100
```

for free. And it would be the same code for both ERT2 and ERT3.

**Comment by jondequinor** [comment]
Note that the `create_tracker` factory and 

```python
general_interval=5,
detailed_interval=10,
num_realizations=None,
```

are all deprecated after `tracker/legacy.py` has been nuked.
