### ISSUE TITLE
Invetsigate Pivotting of Surmmary data

### ISSUE THREAD

**Issue by TerryHannant** [equinor/ert#2900]
Preliminary profiling of retrieving Summary vectors via api found that a pivot  performed at

https://github.com/equinor/ert/blob/main/ert_shared/libres_facade.py#L171

Can take longer to perform than reading data from dark storage
For example 200 realizations x 30 000 on RGS node:

-   reading data from dark storage - 2.0s
-   performing pivot - 2.9s

Thus this check is a heavy overhead when retrieving data via API, 

Investigation needs to be done to see if its possible to avoid the pivot by allocating the data in the correct shape during loading.

**Comment by BjarneHerland** [comment]
Closing this, refer to https://github.com/equinor/ert/issues/2899#issuecomment-1044746682
