### ISSUE TITLE
Suggestion / thought

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#2902]
The last(?) refactoring of Analyis to enable the adaptive localization work I am supposed to do (long way coming ...) is to move the analysis state container `ies::data::Data` to the `local_ministep` class, the purpose of this is to enable local updates and iterated analysis simultaneously - which is currently not possible.

The entire local_xxx functionality is implemented C style with cwrap bindings to Python code which is used from code outside the ert repository - i.e. api must be retained. On the other hand the new `ies::data::Data` class has C++ linkage - i.e. this is right now slightly incompatible. My suggestion is to change the local_xxx classes to proper C++ and use pybind. I have not tried it out - but I hope and think it should be possible to delineate this with the C / C++ linkage challenge spreading through the entire code.

**Comment by oyvindeide** [comment]
This sounds like a good idea to do 👍 In terms of users outside of ert, are you aware of many users? We are using this functionality in [semeio](https://github.com/equinor/semeio), but if there are good reasons to change the API that should not be a problem. If we have others users as well though, we might want to keep the API as is.

**Comment by joakim-hove** [comment]
> In terms of users outside of ert, are you aware of many users? We are using this functionality in [semeio](https://github.com/equinor/semeio),

I was mainly thinking of `semeio`; I do not know whether all of @oddvarlia work is fully in `semeio`?

**Comment by oyvindeide** [comment]
Yes, the work @oddvarlia has done is all in `semeio` as far as I know, though he probably does some testing outside. As long as we keep the functionality that should be ok. We removed the local dataset for example which means we had to do some changes in semeio, but is worth in when it is simplification I would say.

**Comment by oyvindeide** [comment]
Good question, part of it might still be relevant, through large parts are not. @ManInFez will you be touching some of this?

**Comment by dafeda** [comment]
Not longer relevant.
