### ISSUE TITLE
User story for adding an extra parameter to an FMU model in ERT3

### ISSUE THREAD

**Issue by berland** [equinor/ert#2952]
As an ERT3 user, I would like to be able to add a new parameter to my FMU setup with small amount of hassle.

Let's assume the users has an existing forward model with a config file which needs the additional parameter. The user understands that this will entail at least:

* Modify hers "FORWARD_MODEL" to cope with this. This is outside the scope of ERT.
* Modify a template file in the `resources` directory, adding a `jinja2` statement somewhere, pointing to a new parameter name.
* _Not_ add or change an existing `render` command in `stages.yml`, because it is already there pointing to the template file and the output file.
* The user does _not_ want to declare this extra parameter as a new record in `ensemble.yml`, as this will be interpreted as too much hassle.
* Declare the new parameter in `parameters.yml` with a name and a distribution. 
* Optionally, declare this new parameter to belong to a certain parameter group, associated to the given forward model. However, this needs to make sense also for parameters that can be given to multiple forward models.
* Avoid having to index scalars in templating (e.g. `OP2_OFFSET:{{op2_offset[0]}}` should be `OP2_OFFSET:{{op2_offset}}`.

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
