### ISSUE TITLE
support editable mode `-e` for `ert3 init --example example`

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#2959]
**Describe the bug**
When I want to change e.g. the `stage.yml` configuration in the `polynomial` example, I want to run it for each change. As far as I can see, this isn't currently possible. I'd like to be able to have some _static_ assets be symlinks.

The list of assets to symlink does not have to be final, exhaustive or even remotely "correct". The configs (`**/*.yml`) and scripts (`**/*.py`) is a good start. Or all files. Not sure.

**Expected behavior**
```sh
ert3 init --example -e polynomial
cd polynomial
echo "lol" > stages.yml
```
`stages.yml` is now changed in the `ert3/examples/polynomial` folder as well.

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
