### ISSUE TITLE
Adjust timeout functionality in base service

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#2961]
Currently there is a hard timeout of 20 sec in base service which in some cases is not enough. This should be upped to a higher number and / or utilize retries. In addition - some information should be printed in the terminal stating what is the reason of shutting down.  It would also be nice having this functionality available through the cli for debug-purposes.

**Comment by DanSava** [comment]
The associated PR(https://github.com/equinor/ert/issues/2945) was merged do we still need this issue to be open?

**Comment by oysteoh** [comment]
No - i think we can close it for now.
