### ISSUE TITLE
Remove "lazy-loading mode" in forward_load_context 

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#2972]
There is a hardcoded flag `lazy_load` here

https://github.com/equinor/ert/blob/324d702235a69961d6396afffa8e7e4eac4a6dab/libres/lib/enkf/forward_load_context.cpp#L98

which toggles how summary-data is loaded. Setting this flag to `false` greatly improves loading-time while (presumably) requiring a lot of memory.

It is believed that current hardware normally has sufficient memory to allow disabling this  memory-saving mode. As a fallback we can optionally introduce an environment-variable to enable lazy-loading in cases where this turns out to be necessary.

We might also introduce the memory-logger in an appropriate place to gather real data of amount of memory needed to set up a context for the forward-model.

Note that this flag is also set here

https://github.com/equinor/ecl/blob/293875faebdf2c1c39e764752417007eac2f7f55/lib/ecl/ecl_sum.cpp#L483

but that entry-point does not seem to be used outside of ECL.

**Comment by BjarneHerland** [comment]
@mortalisk @markusdregi @oysteoh @TerryHannant @frode-aarstad   might have input to this

**Comment by mortalisk** [comment]
Solves #2873

**Comment by mortalisk** [comment]
Should I mark my PR as solving this as well, or do you intend to merge that code now, since I am still struggling to get my PR stable.

**Comment by BjarneHerland** [comment]
> Should I mark my PR as solving this as well, or do you intend to make a new PR to merge that code now, since I am still struggling to get my PR stable.

Mmmm...  wasn't aware of issue #2873. Some of us agreed in a discussion yesterday that I should create this issue in order to resolve the lazy-loading problem quickly. Feel free to close this as duplicate of #2873 and make a PR with the simple solution. Alternatively you can grab this one + submit (trivial) PR, leaving #2873 as a placeholder for a proper solution to the underlying problem.
