### ISSUE TITLE
FMU workflows in ERT3

### ISSUE THREAD

**Issue by berland** [equinor/ert#2985]
An FMU developer needs to be able to make general scripts available to be run as "workflows" (ert2-lingo), that is, scripts that are able to work with data from multiple realizations. 

Existing workflows/scripts for ERT2 from the FMU side, pr repository, include:
* subscript: `csv_merge`, `csv_stack`, `fmuobs`
* fmu-dataio: `WF_CREATE_CASE_METADATA`
* ecl2df: None
* pyscal: None
* fmu-tools: None installed, but provides fmudesign which can be run as a user written workflow.
* fmu-ensemble: None, but intended to be wrapped by user written workflows.
* xtgeo: None

Drogon uses the workflows:
* ahm_analysis (drogon-specific python script, not from semeio)
* dpdt2yml: Processes (well-test) data from project disk and outputs to project disk.
* create_case_metadata: (fmu-dataio)
* export_misfit: Drogon-specific scripts. Uses observations and `getTotalChi2()` from the ert instance (`ErtScript.ert()`). Writes data to project disk.
* echo_config_file: Writes the path of the current ert-file to a destination on scratch, alongside `realization-*` directories.
* run_fmuconfig: Runs a project-specific shell script.
* copy_seisobs: Copies data from project disk to scratch, alongside realization directories.

These scripts need the capability of being run at the correct time, and, for ERT2, access to the filesystem (project disk and scratch disk). Command line arguments must be configurable from the ERT setup, and the command line arguments need to be rendered to be able include ERT runtime parameters (typically variables containing directory paths) and environment variables.

**Comment by eivindjahren** [comment]
ert3 is o longer part of the project. Feel free to reopen if still relevant
