### ISSUE TITLE
User feedback when all jobs completed successfully but the realization(s) failing

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3004]
Had a user today which was running ERT with a slightly modified config-file. The user wanted to remove all eclipse-related stuff and only run all other jobs with RMS ++. 

All realizations completed successfully it seems, all jobs OK ( OK file in all output-folders ). But - in the ERT GUI all realizations is marked as failed ( Clicking on one realization reveal all jobs with the status green and success ). 

We was able to track down what was causing this by looking at the log file in `..ert/output/log` which revealed loading of summary-key failed. The reason was the user had removed all eclipse related jobs, except from loading the summary keys. 

It would be nice giving the user feedback on this directly instead of having to look through log-files. 

> Found info in logfile under:
> project/../../../../..../ert/output/log
> Stating that loading of ECLIPSE summary files failed.
> In my config file the loading of summary files were not commented out - although I am not running Eclipse.

**Comment by jondequinor** [comment]
Maybe check if the configuration can be validated, and in this case fail early?

**Comment by oyvindeide** [comment]
We should be able to validate this by checking if there is a `SummaryConfig` and that there should be an `ECL` or `flow` forward model, this should just be a warning though (which should be in the Suggestor), as there could be cases where a user will create their own summary file without having that either of those forward model jobs.

**Comment by DanSava** [comment]
There have been some changes related to checking for output files that the forward model is expected to produce. Now in a similar case to the one described in the issue description, we get an error message for each realization in the GUI, but only after the case finished running. 


![Image](https://github.com/user-attachments/assets/04979663-7ef4-4232-ab7b-472523be83d3)

Not sure if this is enough to close the issue or not.

**Comment by oyvindeide** [comment]
In terms of closing this, we can add a cross validation at startup. If there is a SummaryConfig (i.e. we expect to read summary files after the forward model), but no FLOW or ECL jobs, that should give a warning in the suggestor.
