### ISSUE TITLE
Clarify usage of weak-references in enkf_fs_manager

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#3014]
This documentation

https://github.com/equinor/ert/blob/fcc1be73269c5b3d834b6acf356be343321020f6/res/enkf/enkf_fs_manager.py#L136-L139

very explicitly states that a weak reference is returned from this method. However, the reference is actually a copy created here

https://github.com/equinor/ert/blob/fcc1be73269c5b3d834b6acf356be343321020f6/res/enkf/enkf_fs_manager.py#L57-L59

Implementations of both `weakref()` and `copy()` are found here

https://github.com/equinor/ert/blob/fcc1be73269c5b3d834b6acf356be343321020f6/res/enkf/enkf_fs.py#L56-L68

but `weakref()` is never used anywhere AFAICS.

Either the documentation should be changed to reflect reality and `weakref()` removed, or we should actually start using weak references (which were probably implemented for good reasons at some point in time).

**Comment by BjarneHerland** [comment]
Note that this test

https://github.com/equinor/ert/blob/fcc1be73269c5b3d834b6acf356be343321020f6/tests/libres_tests/res/enkf/test_enkf_fs_manager2.py#L27-L38

states that reference-count in C++ -world is 2 when a single `EnkfFs` Python-object has been returned from `getFileSystem()`. By replacing `fs.copy()` with `fs.weakref()` here 

https://github.com/equinor/ert/blob/fcc1be73269c5b3d834b6acf356be343321020f6/res/enkf/enkf_fs_manager.py#L57-L59

the initial refcount becomes 1, which makes sense and refers to the `EnkfFs` Python-object in the rotating cache of `enkf_fs_manager`.

Note that the rotating cache implemented in `enkf_fs_manager`, in order to add new objects, removes the oldest object when the cache reaches its limit. If we were to return weak references to cached objects, such references would point to invalid C++ objects when the cache is rotated sufficiently.

Hence, we **must** use the `copy()` method, and can thus remove `weakref()` and comments about weak references as mentioned in this issue.

**Comment by oyvindeide** [comment]
Good catch, we have refactored this now and removed `weakref`, so will close this issue.
