### ISSUE TITLE
Verify correct observations in local obsdata

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#3069]
Add check that the local_obsdata_node's key actually exists as a valid observation key.

**Comment by joakim-hove** [comment]
As part of the final PR for local configuarition rewrite: https://github.com/equinor/ert/pull/2981 the complete set of available observation and parameter keys is internalized - this could potentially be utilized to address this issue.

**Comment by oyvindeide** [comment]
This has been added in: https://github.com/equinor/ert/pull/3322
