### ISSUE TITLE
More flexible forward models

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#307]
The forward model in ERT currently runs in one go, component by component sequentially with the same resources independent of individual needs. More flexibility could be implemented so that:
- individual forward model components are allowed to run with specific requirements such as ncpu, hardware, memory, operating system, etc
- that independent components could run in parallel

**Comment by markusdregi** [comment]
This will be addressed by stages in new config file.

**Comment by markusdregi** [comment]
Let us prioritise this if it becomes relevant.
