### ISSUE TITLE
Render step with early template validation

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3116]
Briefly mentioned in user story https://github.com/equinor/ert/issues/3114 — I want to jot down what we discussed as a possible implementation.

- A render step can take multiple record inputs and one template input to produce one output record (a blob to be parsed as parameters by e.g. eclipse or RMS).
- A part of the process of creating this step, validation can occur. A jinja context can be built from the non-template inputs and attempted to be rendered with fictitious values. If the template is rendered, it is likely to be rendered on the cluster as well.

**Comment by oyvindeide** [comment]
Closing as ert3 related
