### ISSUE TITLE
FLAKY: test_gen_data_config

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#3151]
Failure in test_gen_data_config seems flaky
```
res/enkf/data/test_gen_data_config.py .F 
```
Full log: https://ci.equinor.com/komodo/job/unit-tests/job/ert/1493/console

**Comment by sondreso** [comment]
Happened again here: https://ci.equinor.com/komodo/job/unit-tests/job/ert/1507/console

**Comment by BjarneHerland** [comment]
Hmm...  [stress-testing this with no failures](https://ci.equinor.com/scout/job/komodo_testing/job/ert-custom-script-pr/10535/consoleFull
). 1000 repetitions with varying load on host (test takes from 1.1s to 25s to complete)

**Comment by BjarneHerland** [comment]
Triggered another stresstest with same result. Moving this issue to the "old issue, not occuring anymore"-list

**Comment by sondreso** [comment]
And again here: https://ci.equinor.com/komodo/job/unit-tests/job/ert/1520/console

**Comment by sondreso** [comment]
Has not been reproduced after Flaky-test initiative, so will close this one. Re-open if it appears again!
