### ISSUE TITLE
Improved reproducility using `RANDOM_SEED`

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#3169]
When setting the `RANDOM_SEED` in the configuration file the sampled parameter values are reproducible. However, small changes in the configuration will break this reproducibility.

Using the same random seed I would like to be able to:
- change the size of the ensemble and still see the same parameter values for the realization indexes that are present in both ensembles. That is, if I increase the ensemble size from 100 to 200 I'd like the parameter values of the first 100 realizations to be the same in both ensembles. Similarly, if reducing the ensemble size from 100 to 50 I'd like the parameter values of the first 50 realizations to be the same.

- Adding or removing a GEN_KW entry (or a different parameter group) should not change the sampled values of the other parameter groups in the ensemble.

**Comment by sondreso** [comment]
See also: https://github.com/equinor/ert/issues/1908
