### ISSUE TITLE
Log the entire configuration on startup

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3180]
We need to know more about configurations to solve e.g. #2766, so the entirety of the configuration should be logged on startup. It should enjoy privacy guards like all other logging.

**Comment by oyvindeide** [comment]
> We need to know more about configurations to solve e.g. #2766, so the entirety of the configuration should be logged on startup. It should enjoy privacy guards like all other logging.

It will be sanitized like all other logging, but would advise to do some additional checking before implementing as there is much more potential for the user to insert custom information in the config file.

**Comment by verveerpj** [comment]
> > We need to know more about configurations to solve e.g. #2766, so the entirety of the configuration should be logged on startup. It should enjoy privacy guards like all other logging.
> 
> It will be sanitized like all other logging, but would advise to do some additional checking before implementing as there is much more potential for the user to insert custom information in the config file.

That is indeed an issue, and I guess the user could put whatever they like in comments? So dumping the file might not be a good idea.

**Comment by verveerpj** [comment]
Discussed in the owls standup, and we estimate the risks to be low, so we will log the file as is.
