### ISSUE TITLE
ensemble evaluator swallows exceptions

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3197]
**Describe the bug**
Imagine you introduce a bug in some code used by the dispatcher/batcher in the ensemble evaluator

```
def _match_token(token: str, source: str) -> str:
    f_pattern = _regexp_pattern.format(token=token)
    match = re.search(f_pattern, source)
    raise RuntimeError("nope")
    return match if match is None else match.group()  # type: ignore
```

You won't actually see this error, it will be silently swallowed because the `asyncio.Task` that sees that exception, is never awaited (normally it is, but after nominal completion).

**Expected behavior**
Errors must not be swallowed, they must be propagated so that the application fails

**Comment by BjarneHerland** [comment]
Jenkins: test ert please
