### ISSUE TITLE
Build html from ipynb files in documentation

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#3214]
Due to a security problem with mistune<2, the nbconvert packages can not be used, thus none of the regular ipynb webpage builders can be used. When this is resolved, we should replace the static html-pages for all notebook files.

Currently this applies to:
- Oscillator.ipynb
- Polynomial.ipynb

**Comment by eivindjahren** [comment]
There are no longer any `.ipybn` files in the ert repository so I am closing this issue. If anything else we need to apply nbconvert to, please open a new issue for it.
