### ISSUE TITLE
Make asyncio usage compatible with Python 3.12 (remove deprecation warning)

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3228]
The `get_event_loop` method is deprecated in Python 3.10 (https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop). Refactor our usage of asyncio in ert to be compatible with future releases of asyncio

**Comment by berland** [comment]
Deprecation plan has been changed, this is deprecated from Python 3.12.

The call is currently only being used in https://github.com/equinor/ert/blob/01c1f9a9ffcbe663e2e9c79052ba4ff18e74562e/src/ert/async_utils.py#L20C1-L25C40

**Comment by berland** [comment]
The RunTimeError caught in this code is triggered by everest. Erts own tests will pass without the `try` clause in `async_utils.py`.

**Comment by berland** [comment]
> The RunTimeError caught in this code is triggered by everest's pytest. Erts own tests will pass without the `try` clause in `async_utils.py`.

Not perfectly true, Ert's tests on its everest interface (batch simulation) will fail.

**Comment by berland** [comment]
Everest gui tested manually to work fine with this.
