### ISSUE TITLE
Progress dialog hangs

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3244]
**Describe the bug**
The progress dialog hangs when running `ensemble experiment` (at least) in cases with forward model lasting for a longer period. Reproduced by running poly case with sleep for an hour.

**To Reproduce**
1. `pip install ert`
2. Inject sleep (e.g. for an hour) in poly example
3. Run ensemble experiment

**Expected behavior**
Run dialog to state that it has finished.

**Comment by BjarneHerland** [comment]
Tried this today using GUI and 3600s sleep in `poly_example/poly_eval.py` but running ensemble-experiment with progress dialog open finishes as expected.

Can this be reproduced? I use an ARM-based Mac-laptop.

**Comment by BjarneHerland** [comment]
Tried again this morning - still works fine.

**Comment by BjarneHerland** [comment]
This can be reproduced by explicitly raising e.g. a `OSError` (or `ValueError` or something **not** websocket-specific) in this try-catch block

https://github.com/equinor/ert/blob/7094c19e92260c3e97ea87e4f60665ec9e0e12c0/ert_shared/ensemble_evaluator/sync_ws_duplexer.py#L110-L117

For example 1s after first call

```python
        try:
            t = getattr(self, "_firsttime", time.time())
            if time.time() - t > 1:
                raise OSError("Boooom!")
            else:
                self._firsttime = t

             event = asyncio.run_coroutine_threadsafe( 
                 self._ws.recv(), loop=self._loop  # type: ignore 
             ).result() 
             yield event 
         except OSError: 
             self.stop() 
             raise 
```
