### ISSUE TITLE
ERT does not quit if Event viewer is open

### ISSUE THREAD

**Issue by berland** [equinor/ert#3273]
**Describe the bug**
If the Event viewer window is open, and the user closes ERTs main window, the application does not quit (meaning that the command prompt is restored) before also the Event viewer window is closed manually by the user.

**To Reproduce**
1. Start ert, on say snake_oil
2. Click "Event viewer"
3. Close ERT main window (ERT main window now closes, but the terminal is not ready for new commands yet)
4. Close Event viewer window.

**Expected behavior**
Event viewer window should automatically close when ERTs main window is closed.

**Enviromment**
 - OS:  RHEL7
 - ERT: ca 2.34
 - Python 3.6
 - Remote/HPC execution involved: no

**Comment by sondreso** [comment]
This is the same with the other windows in ert, for example if you close the main window while the run dialog is still open. We should look into if it is possible to close all other windows when the main application window exits
