### ISSUE TITLE
Remove pinning of manylinux2014

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3282]
In https://github.com/equinor/ert/commit/ba719f64f2cb014fc25631450c6e77dd5ca81291 the tag for manylinux was pinned, since it started to fail on the new release. We should investigate and fix the problem, so that the pin can be removed again.

**Comment by verveerpj** [comment]
There is now a similar issue in `ecl`, so that should be fixed at the same time: https://github.com/equinor/ecl/issues/864
