### ISSUE TITLE
Replace `util_sscanf_double` with locale-agnostic version

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#3296]
This function comes from libecl and uses `strtod`, which uses the global locale to determine whether to use `,` or `.`. Replace it with something like:
```c++
bool ert::from_string(const std::string &str, double &value) {
    std::istringstream ss{str};
    ss.imbue(std::locale::classic());  // Set to C locale for this stream only (not globally)
    ss >> value;
    return ss.good();
}
```

**Comment by oyvindeide** [comment]
Now only used in the queue system, so should be feasible to replace it.

**Comment by pinkwah** [comment]
Might as well wait until there's no more C code in Ert. We still have resdata to deal with so it's not like this would fix anything.
