### ISSUE TITLE
Remove `ActiveList` from data container functions

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#3327]
`ActiveList` is misused in our data container objects and are used to specify a subset of elements on which to work on, rather than "active" in the sense of an observation being active. For example, the following function allows the user to sub-select a set of observations, or return all:

https://github.com/equinor/ert/blob/27fe7774b9e6a846c9798fb640694291b3e98a8c/libres/lib/enkf/block_obs.cpp#L249-L277

A more correct type to use here is `std::optional<set::set<std::size_t>>`, where `std::nullopt` means to use all. We could alias the type to `Selection` or some other fitting name.

This issue is for functions starting from `enkf_node.cpp` and down to all of the different data containers we have and not anywhere where we actually want to have a list of 'active' observations.

Refer to https://github.com/equinor/ert/pull/3048

**Comment by oyvindeide** [comment]
related to #5694

**Comment by oyvindeide** [comment]
Will close this, as most of the code this discusses has been removed, and removing ActiveList as a concept is covered by linked issue.
