### ISSUE TITLE
Utilizing the `ert-api` from the pyqt-plotter, data is not refreshed before ERT is restarted

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3347]
Opening the plotter while ERT is running only gives you an updated list of cases, but no data except from observations. The data is filled only once the ERT run has completed / closed and then reopened. ~We should change and adapt to what has been the functionality previously before using the `ert-api`~ Ideally this should work and we should be able to see data after each iteration at least. If we discover this is a bigger "bug" and existed for a while, we should have a proper discussion and assess what needs to be done and if that should be part of our milestone.

This also means - if i understand correctly - that running CSV export in workflows utilizing the `ert-api` will hit the same issue with no data to export.

**Comment by DanSava** [comment]
> This also means - if i understand correctly - that running CSV export in workflows utilizing the ert-api will hit the same issue with no data to export.

I think you are correct we will hit the same issue if the user runs CSV export while ERT is running

**Comment by DanSava** [comment]
Did some testing and it seems also for the main ERT branch trying to open the plotter while ERT is running is a bit prone to issue, i.e. the plot is empty for the responses only the observations are shown. 

The behaviour is a bit different for different simulation modes. Tested the api-adoption branch with ESMDA mode and it worked as the main while opening the plotter while the run is in progress.

**Comment by frode-aarstad** [comment]
Did some testing running ES_MDA on snake_oil using the api-adoption branch and it seems like the data **is** updated during a run, its just slow. The cases show up quite fast while the the data takes some time to show up. Even when the run is done I had to wait 2-4 mins before the data for the last ensemble can be plotted.

**Comment by oysteoh** [comment]
Solved with #3386
