### ISSUE TITLE
Stress test Dash prototype visualization on a real-sized scenario

### ISSUE THREAD

**Issue by xjules** [equinor/ert#335]
Maybe on Reek, or Egg, or any other model

Part of https://github.com/equinor/ert/issues/328

**Comment by xjules** [comment]
With @ManInFez we made a stress test with visualizing 3 cases each with ca. 100 timesteps and 200 realizations. When switching to webgl (dash supports it thankfully) we managed to get an interactive visualization (on default laptop). On my desktop PC I was rendering easily  the same settings but with 500 realizations for each each case.
![image](https://user-images.githubusercontent.com/6409506/56138062-5a866100-5f96-11e9-9625-f7d611e92920.png)

**Comment by andreabrambilla** [comment]
Awesome, I guess this task is concluded then :+1:
