### ISSUE TITLE
Global pytest timeout

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3374]
### Discussed in https://github.com/equinor/ert/discussions/3344

<div type='discussions-op-text'>

<sup>Originally posted by **jondequinor** May  4, 2022</sup>
1. We should acknowledge that ERT will be flaky for a long time. Its design implies a lot of deeply buried synchronization issues that are exacerbated by using files writes/reads as means for communication.
1. Furthermore, our test suite runs for a very long time, and we want to cut that down.

Given these two assumptions, should we have a global [pytest timeout](https://pypi.org/project/pytest-timeout/)?

```ini
[pytest]
timeout = 60
```

Integration tests currently in conflict with this could be exempted from this policy by setting the timeout to 0 (or some higher number):

```python
@pytest.mark.timeout(0)
def test_integration():
    pass
```

**Comment by eivindjahren** [comment]
I think we can close this as we have good handling of timeouts now. What do you think @oyvindeide ?

**Comment by oyvindeide** [comment]
I guess it is just more likely to cause more problems if we introduce a timeout, so, yes, I agree.
