### ISSUE TITLE
Remove analysis update writing to storage while updating

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3377]
Today the update algorithm will save and load parameters to storage while updating. We should replace this with keeping them in memory, and only writing once the update is completed.

**Comment by oyvindeide** [comment]
Or at least explore how much memory this will require on a large case.

**Comment by oyvindeide** [comment]
Blocked by: #[3487](https://github.com/equinor/ert/issues/3487)

**Comment by oyvindeide** [comment]
If this proves to be infeasable because the memory required is too large, we could consider using some other temporary storage.

**Comment by oyvindeide** [comment]
No longer considered blocked, this should be as contained as possible if we have to revert it if it actually consumes too much memory.

**Comment by dafeda** [comment]
Are we talking about these or something else?

https://github.com/equinor/ert/blob/bcc93d8cf92238187bfa6c996b64d0584f85d1ae/src/ert/analysis/_es_update.py#L108-L113

https://github.com/equinor/ert/blob/bcc93d8cf92238187bfa6c996b64d0584f85d1ae/src/ert/analysis/_es_update.py#L125-L131
