### ISSUE TITLE
Flaky test: ensemble_config_add_node: a configuration object:TIME has already been added

### ISSUE THREAD

**Issue by berland** [equinor/ert#3379]
Flaky test on Ubuntu, py38:

https://github.com/equinor/ert/runs/6405472194?check_suite_focus=true#step:9:2677

```
Abort called from: ensemble_config_add_node (/github/workspace/libres/lib/enkf/ensemble_config.cpp:263)

Error message: ensemble_config_add_node: a configuration object:TIME has already been added - aborting 

```

**Comment by BjarneHerland** [comment]
@mortalisk this one is failing in `performance_tests/test_dark_storage_performance.py::test_direct_dark_performance`. Didn't you investigate / fix some problems with those lately - does this look familiar?

**Comment by mortalisk** [comment]
This does not look familiar.

**Comment by oyvindeide** [comment]
Seemingly this test is no longer flaky as there are no new reports since May, closing.
