### ISSUE TITLE
Create matricies in python and passing by reference

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3396]
Here: https://github.com/equinor/ert/blob/98c74fe90bfbc9d9502edd91f8e263ab5a6c0008/res/enkf/es_update.py#L74 we create the matrices in C++ because we are not able to pass them by reference between numpy and Eigen, we should have a look at that again to simplify saving and loading parameters.

**Comment by ManInFez** [comment]
matrices are now owned by python after https://github.com/equinor/ert/commit/7615fe3ab79643846e3e93906f38a3a717fbc661
