### ISSUE TITLE
Investigate running python save function through pybind11

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3397]
In order to save parameters and responses in a seperate storage instance we might consider forwarding a save function to, for example, the exit callback so that we dont have to refactor everything into python to be able to save responses. Might be just as easy to refactor the reading though.

**Comment by BjarneHerland** [comment]
@oyvindeide did you have a particular save function in mind here? 😄

**Comment by oyvindeide** [comment]
Yes I did, but was not a very descriptive issue 😅 I have added some more context in the description now 👍

**Comment by oyvindeide** [comment]
We will aim for doing this directly from python instead, so this is not required.
