### ISSUE TITLE
Performance testing of saving/loading from different file formats for storage

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3398]
Format suggestions: https://docs.xarray.dev/en/stable/user-guide/io.html

**Comment by dafeda** [comment]
Should we close this for now @oyvindeide ?

**Comment by oyvindeide** [comment]
I think that is reasonable, perhaps link it to the PR where some testing was performed?

**Comment by oyvindeide** [comment]
Some testing results here: https://github.com/equinor/ert/pull/3404
