### ISSUE TITLE
"job box" seems to present jobs out of order

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3399]
**Describe the bug**
In the GUI, the run dialog has a grid where each job is presented by a colored box in a grid. These are now becoming green out of order. We've recently touched this code in https://github.com/equinor/ert/pull/3167 so might be related, but I have not bisected.

**To Reproduce**
1. duplicate forward model section of the poly_example to have hundreds of poly jobs
2. `ert gui my_config.ert`
3. Run single realization experiment

**Expected behavior**
The boxes are becoming green sequentially

**Screenshots**
![Screenshot from 2022-05-18 14-39-01](https://user-images.githubusercontent.com/53553193/169044434-2c7f804d-27ea-4303-9c17-92651c0cc543.png)

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: main
 - Python version: 3.8

**Comment by jondequinor** [comment]
Seems to only affect the initial full snapshot, as all updates are seemingly in order.

**Comment by xjules** [comment]
Made some tests and can confirm that it's not correct. Looking into it now.
