### ISSUE TITLE
Design and implement experiment statemachine

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3407]
**Background**:

- https://github.com/equinor/ert/issues/1691
- https://github.com/equinor/ert/issues/3401

The design of the ensemble evaluator state machine (aka. _snapshot_) is problematic:

- it does not scale well since it uses _recursion_ for updating a _large dict_. Recursion is fine for general work on a dict, but our problem is highly specific. And dict access is slow in python.
- transitions are captured in code with a high branching factor, making reasoning about it complex (see https://github.com/equinor/ert/blob/8c7760647bd22317ab14c677463e03f355dde371/ert/ensemble_evaluator/snapshot.py#L106-L138 and https://github.com/equinor/ert/blob/8c7760647bd22317ab14c677463e03f355dde371/ert/ensemble_evaluator/snapshot.py#L162-L249)
- does not deal well with out-of-order events, missing events, etc.

**Definition of done**:

We should design the state machine in such a way that it:

- scales well, i.e. is fast for thousands of realizations with hundreds of jobs
- is easy to work with: the context and code for each transition is isolated and declarative-like

**Comment by oyvindeide** [comment]
Will close this as there has been significant improvements to this since this issue was created.
