### ISSUE TITLE
Load results manually needs to be repeated every time ERT is launhed

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#3418]
User reported in #ert-users

>I have a case, that ran successfully with "OK"-file generated, but due to wrong refcase, all realizations got "STATE_LOAD_FAILURE". I changed the refcase, and used `Load results manually` from the GUI. It worked great, and the case info showed "STATE_HAS_DATA". I then closed ERT, and reopened - to find that "STATE_LOAD_FAILURE" was "back again". Should it not be "saved" in one way or another?

**Comment by oyvindeide** [comment]
Seems the FS in not synced when the loading from forward model
