### ISSUE TITLE
In failed simulations dialog sort entries by realisation and iteration

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3435]
When the output is printed to: https://github.com/equinor/ert/blob/d2ee53b55ef27a333d1f60d29e1aa183d74137c6/ert_gui/simulation/run_dialog.py#L401 there is no sorting of the output, so realizations are intermingled. This might not be easy to solve as the messages will get propagated out of sync. We might be able to attempt some kind of sorting though. Somewhat related to: https://github.com/equinor/ert/issues/3417

**Comment by jondequinor** [comment]
Don't we have this information currently, in the GUI data model, as well as the CLI?

**Comment by oyvindeide** [comment]
We have the state, i.e. failed or not, but not the `failed_msg` on a realisation base I believe, but yes, adding some information there should probably solve it.

**Comment by jondequinor** [comment]
Where is the `failed_msg` coming from? Maybe I can help determine if it's in the state or not.

**Comment by oyvindeide** [comment]
Currently it is [here](https://github.com/equinor/ert/blob/23f6b0229a5b2dcb824d52665db72eaa941ca871/ert_shared/models/base_run_model.py#L170), so before it was just `All simulations failed!` or something of that nature, it has now been expanded to include all errors that happen while simulating.

**Comment by dafeda** [comment]
I tried modifying `poly.ert` such that this error box would pop up by changing:

```python
def _evaluate(coeffs, x):
    if coeffs["a"] > 0.5:
        raise Exception("Evaluation failed.")
    else:
        return coeffs["a"] * x**2 + coeffs["b"] * x + coeffs["c"]
```

The error box does not show up, even though some realizations failed:

<img width="1312" alt="failed_realizations" src="https://user-images.githubusercontent.com/45088507/174535883-61c9380d-8ae8-4443-aeb2-2c838bd65a7b.png">

The error box does however pop up if all realizations fail, i.e., if:

```python
def _evaluate(coeffs, x):
        raise Exception("Evaluation failed.")
```

Is this as expected?
