### ISSUE TITLE
Figure out how to run QT alongside experiment server

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3443]
The first iteration of the experiment server is probably going to be one-shot and CLI-only. For the GUI, the complexity is increased because

- The QT GUI should probably run in its own thread
- Multiple experiments could be started, and multiple experiments should be trackable by the GUI.

Exactly how this should be designed and implemented is currently up in the air.

**Comment by jondequinor** [comment]
Note that if we make asyncio functionality that we think we should somehow run in a QT thread, take a look at https://github.com/CabbageDevelopment/qasync — three forks, they all died! Now that's sad, but perhaps not completely surprising…

**Comment by xjules** [comment]
Since both QT and `ExperimentServer` depend on enkfmain, the current solution / suggestion is to start up `ExperimentServer` in `RunDialog` and inject enkfmain (alongside `BaseRunModel` derivate) into the `ExperimentServer` from the `RunDialog`. Not sure if there is a better way to do it @jondequinor.

**Comment by jondequinor** [comment]
Me and @Blunde1 discussed this, and these were the conclusions (as I recall, at least):

- Start experiment-server in a thread that lives for the entirety of ERT using `asyncio.run`.
- Start the GUI in the main thread and share `ExperimentServer` in both threads, i.e. inject `ExperimentServer` into the main window, and propagate it down to the simulation selector window (simulation panel).
- `EnkfMain` is owned by the GUI and passed to `ExperimentServer.add_legacy_experiment` to be used in the `create_model` factory. The `ExperimentServer` and the thread in which it lives should not care about `EnkfMain`, it should only see the _thing_ resulting from calling the `create_model` factory which implements the `Experiment` protocol/interface. 
- All other `ExperimentServer` usages by the GUI (cancel, tracking state) should go over the network.
- The GUI should not know about `BaseRunModel` and its derivatives. All API from `BaseRunModel` should be replaced by talking to the `ExperimentServer`.
- The GUI thread _must_ be in the main thread (kernel constraint on macos).

Some comments on the current suggestion (`exp_server_from_gui`):

- https://github.com/lars-petter-hauge/ert/blob/a647c49e2e3658128c464c8e882e9df9dec35837/ert_gui/simulation/run_dialog.py#L296-L301 is too late to start the server with the current `ExperimentServer` design in mind.
- `simulation_thread` only lives for one experiment, which means it cannot manage the server's life cycle
