### ISSUE TITLE
Run ert3 experiments using the experiment server

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3456]
This work depends on, at the very least, #3414. This will provide an outline for how to start migrating ert3/prefect ensembles to the experiment server.

After #3414 it should be actionable:

- running an experiment needs to start the server
- an experiment must be created, using some args and a factory. ERT2 and ERT3 are probably not compatible here, so a proxy should be made.
- decide whether or not local work should communicate to the server using websockets or queues.

**Comment by eivindjahren** [comment]
Closing as we are no longer persuing ert3. Feel free to reopen if still relevant to the current direction.
