### ISSUE TITLE
Log invocations of "Create Plot" in ERT

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3462]
We have now introduced utilization of the ert-api when plotting from the qt-plotter. It would be really nice to see the usage of this functionality in order to evaluate how stable the api turns out to be when this now eventually enters stable. Also - the qt plotter is planned to be phased out in the future. Having logs of the usage will help us to decide when it is time to remove. 

@oyvindeide whould this be possible to add to the "ERT start command" window on the log-dashboard? I see it as an equivalent to `ert vis` but of course it has not its own entrypoint and cannot be logged that way i guess?

**Comment by oyvindeide** [comment]
No, would not show up there, and would be hard to do that. We could of course add some additional logic, but probably better to have a logging statement when the qt-plotter is opened, and have that as a seperate visualisation, if I understand the question correctly.

**Comment by frode-aarstad** [comment]
I guess a seperate visualisation is ok. I guess having it in the existing graph was only for simplicity.

**Comment by frode-aarstad** [comment]
Will solve this in two parts. First add a log entry when starting the plotter then add a graph to the dashboard that tracks this log entry.
