### ISSUE TITLE
Hide http-requests log-statements from the terminal

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3463]
Running qt-plotter now when it is utilizing the ert-api causing spamming of the terminal with http-requests. These - in my opinion - gives the user no value. I suggest hiding all GET/PUT/POST/DELETE requests.

**Comment by frode-aarstad** [comment]
Would also be nice to remove or add to a logger the `print()` in `_storage_main.py`

**Comment by oysteoh** [comment]
and - we should probably have the possibility of showing the messages through a `--verbose` flag or equivalent?
