### ISSUE TITLE
Make job queue status tracking more collaborative

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3464]
**Describe the bug**
The torque driver will update each job's status using a resource intensive command, qstat. Many of these calls might kill the PBS server.

**To Reproduce**
1. Run 1000 realizations using Azure PBS

**Expected behavior**
I would't expect qstat calls to be made unless:

- the last job in the forward model has ended
- it has been more than, say, 10 seconds since last job-level update from the cluster
- MAX_RUNTIME went into effect

**Enviromment**
 - OS: RHEL7 RGS
 - ERT/Komodo Release: stable
 - Python version: 3.6
 - Remote/HPC execution involved: yes, PBS on Azure

**Comment by sondreso** [comment]
The torque driver has been improved recently and will now call `qstat` significantly less.
