### ISSUE TITLE
Remove enkf_node implementation of SUMMARY

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3465]
We have been doing refactoring of the callbacks, and should be ready to save data differently from before. This includes removing `enkf_node` implementation `SUMMARY` which is loading responses from the forward model in the OK callback. This includes creating a new function on `EnkfFs` to store time series data, and moving all interaction with `SUMMARY` data (i.e. plotting) to the new interface.

**Comment by dafeda** [comment]
Callback in question:

https://github.com/equinor/ert/blob/49f1617944e38a6a53fa2836316324f2f67711e6/libres/lib/enkf/enkf_state.cpp#L513

**Comment by oyvindeide** [comment]
Blocked by: #3825

**Comment by oyvindeide** [comment]
Closed by: #4300
