### ISSUE TITLE
MacOS: decimal point should be "." but it is ","

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#3478]
**Describe the bug**
In MacOS, the standard decimal point is ",". For running ert is ".". This difference leads ert not to run properly and tests to fail.

**To Reproduce**

(A)
On a MacOS computer:
1. `pip install ert`
2. `ert gui test-data/local/poly_example/poly.ert`

OR

(B)
1. `pip install ert`
2. `pytest tests`

**Expected behavior**

(A)
** WARNING: You are using a locale with decimalpoint: ',' - the ert application is
            written with the assumption that '.' is  used as decimalpoint, and chances
            are that something will break if you continue with this locale. It is highly
            recommended that you set the decimalpoint to '.' using one of the environment
            variables 'LANG', LC_ALL', or 'LC_NUMERIC' to either the 'C' locale or
            alternatively a locale which uses '.' as decimalpoint.

OR

(B)
Three tests do not pass:
- test_workflow_thread_cancel_external
- test_workflow_thread_cancel_ert_script
- test_success_ert3

**Screenshots**
Not applicable.

**Enviromment**
 - OS: MacOS
 - ERT/Komodo Release: 2.36.0rc1.dev23+g8a3c21e68 (tested)
 - Python version: 3.8.9
 - Remote/HPC execution involved: no

**Additional context**
This problem happened also with other colleagues setting up in MacOS.

**Comment by pinkwah** [comment]
This is a known problem due to libres: https://github.com/equinor/ert/issues/521

Basically, you have a numerics locale that uses `,` as decimal. Python ignores this unless you explicitly use the `locale` module. However, C, due to its age and bad decisions, actually uses the locale when writing to files using `fprintf`. The solution is to rewrite parts of libres to either only use Python or to use C++ streams with `stream.imbue(std::locale::classic())` to force the streams to use the C locale (where decimal point is `.`).

Either way setting `LC_NUMERIC=C` prior to running ERT tends to avoid the issue.

This issue should be closed as duplicate. Or you can change it so the issue is about the warning not being printed. (Should also mention that this is an issue on Linux as well and not just macOS)

**Comment by xjules** [comment]
> This is a known problem due to libres: #521
> 
> Basically, you have a numerics locale that uses `,` as decimal. Python ignores this unless you explicitly use the `locale` module. However, C, due to its age and bad decisions, actually uses the locale when writing to files using `fprintf`. The solution is to rewrite parts of libres to either only use Python or to use C++ streams with `stream.imbue(std::locale::classic())` to force the streams to use the C locale (where decimal point is `.`).
> 
> Either way setting `LC_NUMERIC=C` prior to running ERT tends to avoid the issue.
> 
> This issue should be closed as duplicate. Or you can change it so the issue is about the warning not being printed. (Should also mention that this is an issue on Linux as well and not just macOS)

Not in this case. Even when setting LC_NUMERIC=C, the decimal point is guessed wrongly on  MacOS (at least on some versions I guess).

**Comment by hnformentin** [comment]
Thanks for the input @pinkwah and @xjules . 
We tried `LC_NUMERIC="C" ert gui poly.ert ` as suggested in the warning, but the warning persists

> ** WARNING: You are using a locale with decimalpoint: ',' - the ert application is
>             written with the assumption that '.' is  used as decimalpoint, and chances
>             are that something will break if you continue with this locale. It is highly
>             recommended that you set the decimalpoint to '.' using one of the environment
>             variables 'LANG', LC_ALL', or 'LC_NUMERIC' to either the 'C' locale or
>             alternatively a locale which uses '.' as decimalpoint.
> 

Nevertheless, if you do as you mentioned here `LC_NUMERIC=en_US.UTF-8 ert gui poly.ert`, the warning is not presented anymore, seemingly it takes the correct decimal point.

I will check if the tests work with your suggestions as well, if so, I think we should at least review the warning message.

**Comment by hnformentin** [comment]
@xjules can you check on your mac if `LC_NUMERIC=en_US.UTF-8 ert gui poly.ert` works?

**Comment by xjules** [comment]
No it din't work in my case :/

**Comment by hnformentin** [comment]
I got help in Slack -> mac and it seems to work: apple meny (settings); text & language; advanced

![image](https://user-images.githubusercontent.com/62240435/179671217-dc6ebf07-8561-4010-81b6-6b7824128767.png)

**Comment by hnformentin** [comment]
With that `pytest` works under ert, but it stops at 97% `tests/performance_tests/enkf/test_load_state.py [1]    6354 killed     pytest tests`. But at least I do not get the error messages related to decimal separator.
