### ISSUE TITLE
Ask to look at the parameters, responses and observations on some large cases

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3486]
We need to check how many parameters, observation and responses it is likely that we need to save.

**Comment by dafeda** [comment]
Had a chat with Torbjørn Ek from Troll.
They do not use grid-parameters (field-parameters) and have in total 833 parameters.
Need to talk to someone that uses grid-parameters.

**Comment by dafeda** [comment]
There is a limit to the size of grid ecl can create because it must be able to hold it all in memory.
Users have reported ERT crashing because of too large GRIDs.
As long as we are doing global updates and not localization, we must hold all parameters and observations in memory.

**Comment by oyvindeide** [comment]
We know users would like to do updates on grids, so this might be an issue down the line. Currently ert will crash if grids can not be loaded into memory, so we will have to deal with this holisticly if we would like to support that properly. For now we can keep everything in memory.
