### ISSUE TITLE
Save configuration information in base_run_model

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3488]
The settings used for updates, scaling factors, etc. should be persisted when we run an experiment.

**Comment by dafeda** [comment]
Could these be added to for example the dict `simulation_arguments`?

https://github.com/equinor/ert/blob/431aea8f40fd65a233f63842806be554aa048542/src/ert/shared/models/base_run_model.py#L62

**Comment by pinkwah** [comment]
Write this data to disk in a HDF5 file inside of storage.

**Comment by oyvindeide** [comment]
Should also include type of experiment, number of iterations, etc.
