### ISSUE TITLE
Segmentation fault from qsub on Azure

### ISSUE THREAD

**Issue by berland** [equinor/ert#3495]
**Describe the bug**
Flakyness on Azure (torque driver) triggers Segmentation fault.

This error occurs on maybe 10% of trial runs with `drogon_design.ert` ensemble experiment.

**To Reproduce**
Start ERT on e.g. `drogon_design.ert` on an Azure node.
Select ensemble experiment, and click 'Start simulation' 
Watch the terminal where you started `ert`

**Expected behavior**
No crash

**Screenshots**
```
Failed to get torque job id from file: /tmp/enkf-submit-std-22072-738907 
qsub command                      : qsub 
File content: []
torque_job_parse_qsub_stdout: 
QObject::~QObject: Timers cannot be stopped from another thread
Trying to construct an instance of an invalid type, type id: 1024
Trying to construct an instance of an invalid type, type id: 1024
Segmentation fault (core dumped)
```

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: git main
 - Python version: 3.8
 - Remote/HPC execution involved: yes, Azure.

**Additional context**
Most likely this fails for the same reason as #405 
At time of experiencing the bug, there were ~500 jobs in the PBS queue on the cluster.

**Comment by berland** [comment]
In another reproduction of this error, the following was also emitted:
```
Traceback (most recent call last):
  File "/private/havb/blenv36/root/lib64/python3.6/site-packages/ert_gui/model/real_list.py", line 131, in _source_data_changed
    self.dataChanged.emit(proxy_top_left, proxy_bottom_right, roles)
TypeError: QAbstractItemModel.dataChanged(): argument 3 has unexpected type 'NoneType'
```

**Comment by berland** [comment]
This behaviour is probably intended as "Failed to get torque id.." is a hard error in the code:

https://github.com/equinor/ert/blob/89941f692540f38eaa47ec780dae68e64d481e63/libres/lib/job_queue/torque_driver.cpp#L345

https://github.com/equinor/ecl/blob/9efe3c51f03657b6f26dfa6d362195f80d9713c6/lib/util/util.cpp#L4220

**Comment by sondreso** [comment]
Solved by https://github.com/equinor/ert/pull/3537
