### ISSUE TITLE
Crash in real_list.py while experiencing qstat problems on Azure

### ISSUE THREAD

**Issue by berland** [equinor/ert#3498]
**Describe the bug**
GUI crash when ERT experiences troubles with the torque cluster status, seen while ERT also fails as in #3495 

```
Failed to get torque job id from file: /tmp/enkf-submit-std-22072-738907 
qsub command                      : qsub 
File content: []
torque_job_parse_qsub_stdout: 
QObject::~QObject: Timers cannot be stopped from another thread
Trying to construct an instance of an invalid type, type id: 1024
Trying to construct an instance of an invalid type, type id: 1024
Traceback (most recent call last):
  File "/private/havb/blenv36/root/lib64/python3.6/site-packages/ert_gui/model/real_list.py", line 131, in _source_data_changed
    self.dataChanged.emit(proxy_top_left, proxy_bottom_right, roles)
TypeError: QAbstractItemModel.dataChanged(): argument 3 has unexpected type 'NoneType'
```
(and the GUI dies)

**To Reproduce**
Start ERT on e.g. `drogon_design.ert` on an Azure node.
Select ensemble experiment, and click 'Start simulation' 
Watch the terminal where you started `ert`

Then cross your fingers, this is flaky!

**Expected behavior**
No crash.

**Enviromment**
 - OS:  RHEL7, Azure.
 - ERT/Komodo Release: git main, ~2.36
 - Python version: 3.6
 - Remote/HPC execution involved: yes, torque driver

**Additional context**
This bug might share the same resolution as #3495, or it should result in a PR that makes the GUI code resilient to the failure in #3495.

**Comment by jondequinor** [comment]
I think the best course of action here is to allow ERT to not segfault in case of trouble with `qstat`.

My guess is the `roles` was collected. 🤷 The reason is that the model defined in `real_list.py` is just a proxy for the "snapshot model", and there we always emit `dataChanged` with no `roles` argument, which defaults to a `QVector`. Maybe `SIGSEGV` reaches the C++ code before Python? I don't really know how that works.

**Comment by berland** [comment]
When ERT writes "Failed to get torque job id..." it will do a `util_exit()` which is supposed to quit all of ert (`exit(1)`), meaning that the following errors on QObject timers and dataChanged might be expected.

**Comment by sondreso** [comment]
The segmentation fault that (most likely) was the trigger for this has been resolved, so closing this.
