### ISSUE TITLE
Plotting ensemble of cost functions when using IES

### ISSUE THREAD

**Issue by geirev** [equinor/ert#351]
Related to the [PR 343](https://github.com/equinor/ert/pull/343)
It is possible to plot the evolution of the ensemble of cost functions after each iteration, and this provides useful monitoring of the HM process. An example plot is given below. IES currently dumps the cost function values to a file cost.dat. Functionality for easy plotting of the cost functions would be useful to have in ERT.

![image](https://user-images.githubusercontent.com/22790296/56721125-86e36f80-6744-11e9-8440-4d2536b7ebe7.png)

**Comment by jondequinor** [comment]
IES should use a _reporter_ to dump these frames/series, so it can be semantically distinguished and use a general approach (i.e. can be used for other types of data as well).

**Comment by jondequinor** [comment]
Should be discussed in https://github.com/equinor/ert/issues/1022

**Comment by markusdregi** [comment]
Visualisations for misfit are being worked on in the webviz-ert instance.
