### ISSUE TITLE
Use `std::filesystem::path` to represent `mount_point`, `root_path` and `case_name` 

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#3516]
https://github.com/equinor/ert/blob/6585a04f36614aeb4801e9e647daa787c3cb6e9a/libres/lib/enkf/enkf_fs.cpp#L146-L149

It seems as if `mount_point` and `root_path` are one and the same, even though a dosctring states that:

https://github.com/equinor/ert/blob/6585a04f36614aeb4801e9e647daa787c3cb6e9a/libres/lib/enkf/enkf_fs.cpp#L148

This should be fixed as well.

**Comment by pinkwah** [comment]
`root_path` is not used.
`case_name` can be deduced from `mount_point`.
Consider making `mount_point` `std::filesystem::path` and adding new getter function `case_name()` which returns `this->mount_point.filename()`.

**Comment by oyvindeide** [comment]
Most of this has been moved to: `enkf_fs.py`, so will close this issue.
