### ISSUE TITLE
Support job log files

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#353]
Currently we have a lot of jobs that basically just wraps another script or application (take Eclipse as an example). The standard out of these scripts are not that interesting, the log files are however. Today we have a concept of `stdout` and `stderr` for all of the jobs. We could also add a concept of `log-file`, such that one could get hold of the _Eclipse_ log file via _ERT_.

**Comment by jondequinor** [comment]
Strongly consider some general reporter approach here instead.

**Comment by markusdregi** [comment]
I completely agree @jondequinor. But it might make sense in a `unixstep` to have first class support for logging to a file no?

**Comment by markusdregi** [comment]
This will come up naturally in some manner when we have a serious look at logging and message passing from the forward model.
