### ISSUE TITLE
Design and choice of communication protocol for ERT

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3579]
As stated in https://github.com/equinor/ert/issues/3407 it is observed that the current implementation of the pydantic statemachine (snapshot) is slow when updating state from events. Some early work has been done to demonstrate other possibilities. The following paths have been explored:

 - Rework the datamodel of snapshot to avoid the recursive update with a flat structure (see work in https://github.com/equinor/ert/pull/3521)
 - Use protobuf and utilize its internal merging of messages (see https://github.com/equinor/ert/pull/3568). Switching to protobuf would also allow us to use grpc, although protobuf can still be used together with websockets.

A parallel discussion has been on how much of a performance benefit sending delta state provides, compared to the added complexity of implementing it. Part of measuring the performance is to check how much the clients (GUI) is affected by sending full snapshot.

We should evaluate the performance of these options by checking the following on rgs (and compare with current implementation):
 - Use protobuf with grpc and send full state on all snapshots, with the argument that protobuf could provide the necessary performance in order to make it possible for full state. Expected bottleneck could be performance hit on the client side (GUI) and the increased transfer size
 - Use protobuf with grpc and implement delta state for sending to clients. This entails that we need to create delta snapshots.
 - Rework the snapshot with a flat structure (but keep cloud events and websockets)

**Comment by xjules** [comment]
I agree with the performance tasks. I would suggest that whatever task is picked the responsible person will create a corresponding issue that will be used as a placeholder for discussions and presenting the results.

**Comment by jondequinor** [comment]
Note that using the protobuf approach experimented with in #3581 does not imply gRPC. protobuf is just a data format, so we can choose to proceed with our use of websockets.

**Comment by xjules** [comment]
It was decided to proceed with the Protobuf, so closing this one.
