### ISSUE TITLE
Get information about parameter/response saving to fs

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3589]
Currently we are passing EnsembleConfig whenever we are saving and loading to `fs`, we should extract that data and make storage responsible instead.

**Comment by dafeda** [comment]
Are we thinking that we for example don't pass `ensemble_config` to `load_parameters`, but instead only pass whatever is needed?

https://github.com/equinor/ert/blob/863a5300d5774b9e4f9b18cb807f3ceac440c859/src/ert/analysis/_es_update.py#L84-L86

**Comment by oyvindeide** [comment]
Yes, or internalize the ensemble_config in `enkf_fs`, did something like that here: https://github.com/equinor/ert/pull/3807/files#diff-27f3b09264880e596302715e448e947ccf3e1a8d88396fd546eb90dd3a0480ac, but not completed.

**Comment by dafeda** [comment]
> Yes, or internalize the ensemble_config in `enkf_fs`, did something like that here: https://github.com/equinor/ert/pull/3807/files#diff-27f3b09264880e596302715e448e947ccf3e1a8d88396fd546eb90dd3a0480ac, but not completed.

Is the goal of that PR (#3807) to close this issue?

**Comment by oyvindeide** [comment]
Partially, but think the current status is that we approach this slightly differently, so will close this issue.
