### ISSUE TITLE
Error messages from logging appears in logs for failed simulations

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3594]
**Describe the bug**
If logging (to Azure) fails, log messages (python logging) will appear in the failed simulations log. This is confusing for the user, as these errors has nothing to do with the simulations themselves.  

Example scenario: 
If the config is to large, logging will failed with `Data drop 400: Telemetry item length must not exceed 65536`. If the forward model also fail, this message shows up in the simulation error log. 

**To reproduce**
Steps to reproduce the behaviour:
1. `source /prog/res/komodo/testing/enable`
2. Navigate to `poly_example` directory 
3. `echo "MAX_SUBMIT 1" >> poly.ert && for i in {1..10000}; do echo -e "MIN_REALIZATIONS 2\nMIN_REALIZATIONS 1" >> poly.ert; done`
4. `echo -e "    import time\n    import sys\n    time.sleep(100)\n    sys.exit(1)" >> poly_eval.py` (Click edit and copy this command raw, Github has strange formatting on the number of spaces )
5. `ert gui poly.ert`
6. Quickly run ensemble experiment
7. Observe `Data drop 400: Telemetry item length must not exceed 65536 ...` appears in the error log 

**Expected behaviour**
Errors from Azure logging should not appear in simulation error log

**Screenshots**
![image](https://user-images.githubusercontent.com/3437958/177147896-191d6254-1444-49ed-9058-0344f460df71.png)

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2022.06.01
 - Python version: 3.8
 - Remote/HPC execution involved: no

**Additional context**
Originally reported on [Slack](https://equinor.slack.com/archives/CDPJULWR4/p1656579776414549)

**Comment by frode-aarstad** [comment]
Not able to reproduce this. How do I make logging to azure fail? I guess running it on either an RGS node or my local equinor laptop the azure should be reachable.
