### ISSUE TITLE
Deprecate `%d` formatting of `<IENS>` and `<ITER>`

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3601]
Usually one will include a %d in the job name and two in RUNPATH. This is not required but the runpaths generally need to be different for every realization and iteration. There is a different mechanism for this which are the magic substitution strings `"<IENS>"` and `"<ITER>"`, so the runpath could be set to `"simulations/realization<IENS>/iteration<ITER>/"`

**Comment by sondreso** [comment]
The use of %d in the runpath has been deprecated
