### ISSUE TITLE
Some problems about installing ERT

### ISSUE THREAD

**Issue by xclmj** [equinor/ert#361]
Hi, all,
        
      I am a beginer of ERT,  I have successfully installed the libecl and libres, however, the Cmakelist file is missing when I try to install ert following the provided installation instruction at https://github.com/equinor/ert.  In the instruction,  the following two steps are given,

4. Run cmake to configure ert

When running cmake you must tell cmake where the libecl code is located with -DCMAKE_PREFIX_PATH i.e. in addition to other possible arguments you must at least add:

-DCMAKE_PREFIX_PATH=/local/ert/install
-DCMAKE_INSTALL_PREFIX=/local/ert/install

in addition you probably want to pass -DCMAKE_INSTALL_PREFIX to configure where the ert distribuion should be installed, normally that will be the same location where you have already installed libecl and libres.
5. Run make to compile ert

After you have run cmake you should run make and make install to build and install ert:

bash% make
bash% make install

However,  the cmake cannot be operated.  I am wondering is there any missing files?**

I'd appreciate it if someone can assist me to solve this problem. 

best regard

**Comment by markusdregi** [comment]
Dear @xclmj.

No surprise you are a bit, as we are currently changing the build system in _ERT_. You can either checkout the most recent tag for version `2.5` (which is currently `2.5.rc2`) and use the `cmake` style of building _ERT_ or you can use `python setup.py install --prefix=....` instead.

Cheers

**Comment by xclmj** [comment]
Thanks very much for your rapid replying.  By the way, I notice the instruction that the installation of python wraper for libecl is optional,  this is  compulsory for libres and ert?

best regard

**Comment by markusdregi** [comment]
It should not be necessary. However, I've never heard of anyone testing this (as most users want to use the Python module in their forward model anyway), so no guarantees ;)

**Comment by markusdregi** [comment]
Notice that with https://github.com/equinor/ert/pull/362 the build instructions have been updated. Thanks for reporting.

**Comment by xclmj** [comment]
Thanks for your kind help, and I have successfully installed the ERT.  By the way, I notice that libecl is an independent part from the ERT project.  libecl can be used to read and write eclipse files,  and it will be very useful to compile the libecl dynamic library to my own code where we want to develop a multi-level parallelized data assimilation algorithm.  I'd appreciate it if you can help me about how to link the libecl.so to my code when compling them and how to call the function to read eclipse file.

best regard

**Comment by markusdregi** [comment]
> libecl can be used to read and write eclipse files

It can indeed. But note that its capabilities are limited to the output-files of _Eclipse_.

I'm not sure I understand your question. By compiling all of the three repositories to build _ERT_ you have already built _libecl_ and added the installation path of  the _libecl_ library to your `LD_LIBRARY_PATH`, have you not?

**Comment by joakim-hove** [comment]
If you are using cmake as your build system you can just add:
```
find_package(libecl REQUIRED)
```
to your `CMakeLists.txt` file and you should be good to go. Use of cmake is highly recommended (all build systems s...  - some less than others ...), but at the lowest level something like[1]
```
g++ your_file.cpp -I$PREFIX/include -L$PREFIX/lib -lecl   [1]
```
should get you going. But observe that this way you will *immediately* come into minor hassles like - is it `$PREFIX/lib` or `$PREFIX/lib64` - what to do with transitive libraries like `zlib` and `m` and so on - these pains are reduced with cmake.

As for use of the libecl library - look at the [the tests](https://github.com/equinor/libecl/tree/master/lib/ecl/tests)

[1]: `$PREFIX` should correspond to the path passed to cmake when installing libecl.
