### ISSUE TITLE
protobuf dispatchers

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3616]
**Describe the bug**
After a discussion about data formats, and with https://github.com/equinor/ert/issues/3581 in mind, @Blunde1, @kvashchuka and me, decided we would move forward with protobuf as a data format. A natural place to start is writing a new "[reporter](https://github.com/equinor/ert/blob/main/job_runner/reporting/base.py)" that produces protobuf messages.

Suggested work

- The schemas from #3568 should be ported
- Automatic generation of schmas install-time
- Protobuf event reporting if experiment-server feature flag, disable CloudEvents also

**Comment by xjules** [comment]
The three suggested works are already (to some extent) solved #3620 .
