### ISSUE TITLE
Order of operations with substitutions is not explicit

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3622]
With the new `res/enkf/substituter.py`, the order of operations is significant, and can easily done incorrectly. For instance: 
```python
        run_context = ert.create_ensemble_experiment_run_context(...)
        ert.set_geo_id(geo_id, sim_id, itr)
```
here the paths in run_context may have included `<GEO_ID>` which were to be substituted, but the call to `set_geo_id` happened after the runpath was created. This could be avoided by delaying the substitution to the latest moment, which was the strategy before the introduction of `substituter.py`. However, this means that the substituter will be included everywhere which increases complexity.

An alternative strategy is to make it required to set the geo id with the substituter (or similar object) which has to be passed as an argument, making it more clear that the setting has to happen first:

```python
        substituter = ...
        substituter.add_substitution("<GEO_ID>", geo_id, sim_id, itr)
        run_context = ert.create_ensemble_experiment_run_context(..., substituter)
```

**Comment by oyvindeide** [comment]
@eivindjahren is this still relevant, or covered by other issues?

**Comment by eivindjahren** [comment]
I am closing as, although it is not obvious, the entirety of enkf_main is stateful, and `create_ensemble_experiment_run_context` is an action.
