### ISSUE TITLE
Selecting a subset of realizations in the GUI will be reported as failure

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#366]
If one selects a subset of the realizations in the GUI and run an ensemble experiment, that is interpreted as a failure. Could also be a problem with the model updating algorithms.

**Reproduce**
Remove the `MIN_REALIZATIONS` from `poly.ert`, launch the GUI, select a subset of the realizations (i.e. `0-50`) and run.

**Comment by ManInFez** [comment]
This has been a "feature" for quite some time. The minimum required realizations is set by the config file, and is set to the NUM_REALIZATIONS unless MIN_REALIZATIONS is defined. This could be changed to BaseRunModel to count the  initial "active realizations", unless anyone has any objections?

**Comment by markusdregi** [comment]
I think that is a good way to go about it for now. The GUI is actively changing the config file and should make the necessary additional changes.
