### ISSUE TITLE
Flaky tests overview

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3676]
List of flaky test.

When creating a new issue for a flaky test, please include:
 - Traceback
 - link to failing github actions / jenkins job
 - Note which os/versions are failing

- [x] https://github.com/equinor/ert/issues/3639
- [ ] https://github.com/equinor/ert/issues/3677
- [x] https://github.com/equinor/ert/issues/3697

**Comment by oyvindeide** [comment]
All issues closed :tada:
