### ISSUE TITLE
Flaky test_storage_service, ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by berland** [equinor/ert#3677]
**Describe the bug**
Crash on Ubuntu, python 3.9

https://github.com/equinor/ert/runs/7628811854?check_suite_focus=true#step:9:580

**Expected behaviour**
No crash

**Screenshots**

**Environment**
 - OS:  Ubuntu 20.04. Github actions.
 - ERT/Komodo release: ~2.38
 - Python version 3.9
 - Remote/HPC execution involved: no

**Additional context**

Python docs: https://docs.python.org/3.9/library/select.html

This man-page warns about using `select`, and is perhaps what we are exposed to:
https://man7.org/linux/man-pages/man2/select.2.html

> WARNING: select() can monitor only file descriptors numbers that
       are less than FD_SETSIZE (1024)—an unreasonably low limit for
       many modern applications—and this limitation will not change.
       All modern applications should instead use [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html) or [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html),
       which do not suffer this limitation

**Comment by oyvindeide** [comment]
As far as I can tell this has not been flaky since, and because the last update here was in August, I am closing this issue.
