### ISSUE TITLE
Employ Protobuf in Clients/GUI section of data exchange

### ISSUE THREAD

**Issue by xjules** [equinor/ert#3681]
Based on to the successful performance measurement tests https://github.com/equinor/ert/issues/3581 and once https://github.com/equinor/ert/issues/3616 is completed, Protobuf data format should be employed for the client / GUI end of the experiment server communication protocol. 

We should take the following issue (ie. running exp. server next to QT) into consideration https://github.com/equinor/ert/issues/3443 .
For completeness, the Protobuf dispatcher PR is here: https://github.com/equinor/ert/pull/3620

**Comment by jonathan-eq** [comment]
@xjules Can this be closed?

**Comment by xjules** [comment]
Yes, closing this one as well.
