### ISSUE TITLE
Add Protobuf experiment level events to base run models

### ISSUE THREAD

**Issue by xjules** [equinor/ert#3706]
Currently there was not need to produce events from based run models, but experiment server does produce the events (CloudEvents at the moment), which should become Protobuf events.

**Comment by xjules** [comment]
This should include creating a Workflow type messages in the protobuf schema, replacing thus the currently CloudEvents handling PRE_HOOKS and POST_HOOKS.

**Comment by berland** [comment]
No protobuf left in the source code.
