### ISSUE TITLE
Include 'es-mda' method in ert/docs/advanced folder examples

### ISSUE THREAD

**Issue by ajikmr** [equinor/ert#3708]
Hello.
Examples in the folder  'ert/docs/advanced' show 'ensemble_smoother' and 'iterative_smoother' methods. It will be good to add 'es-mda' to the same for clarity and comparison purpose.

Also, importing 'ies' does not work. Instead '_ies' works.

Thanks.

**Comment by dafeda** [comment]
Solved by creating ES-MDA example in `iterative_ensemble_smoother`-package: https://github.com/equinor/iterative_ensemble_smoother/tree/main/docs/source
