### ISSUE TITLE
Configuration file initialised twice - user feedback printed twice

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3712]
**Describe the bug**
When `EnkfMain` is initialised in dark storage, the configuration is parsed. Any feedback to the user will then be displayed a second time.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Include a deprecated keyword, e.g. "LOG_FILE"
3. `ert gui my_config.ert`
4. Watch warning about deprecated keyword displayed twice

**Expected behaviour**
Single warning given

**Comment by frode-aarstad** [comment]
We discussed solving this by forcing stderr from subprocesses to DEVNULL. While it would solve this particular problem are we not hiding other potentially important stderr messages from the console? or are stderr from subprocesses not interesting? Any comment on this @sondreso

**Comment by sondreso** [comment]
Maye not send it to devnull but to a separate log file?

**Comment by frode-aarstad** [comment]
Yea I think thats better
