### ISSUE TITLE
RunDialog missing a job status message

### ISSUE THREAD

**Issue by berland** [equinor/ert#3713]
**Describe the bug**
User reports that some (one or two) realizations never get pass the pending state in the RunDialog GUI. The log file reveals that ERT indeed knows the job has been running and also finished.

**To reproduce**
?

**Expected behaviour**
The GUI should report correct information for all realizations.

**Screenshots**
![image](https://user-images.githubusercontent.com/306834/183088829-0c76c38b-2e8e-4f42-979f-cb809a8736f2.png)

Log excerpt:

```
2022-08-05 12:47:13,515 - res.job_queue - Thread-141 - DEBUG - Set TOPPAND-137(137) to JOB_QUEUE_SUBMITTED
2022-08-05 12:47:13,816 - res.job_queue - Thread-61 - DEBUG - Set TOPPAND-57(57) to JOB_QUEUE_RUNNING
2022-08-05 12:47:13,817 - res.job_queue - Thread-41 - DEBUG - Set TOPPAND-37(37) to JOB_QUEUE_DONE

```

**Environment**
 - OS: RHEL7
 - Komodo release: 2022.08.00-py38-rhel7
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Additional context**
Slack thread with user report: https://app.slack.com/client/T02JL00JU/CDPJULWR4

**Comment by andreas-el** [comment]
Relates to #6191

**Comment by sondreso** [comment]
Most likely fixed by https://github.com/equinor/ert/pull/6226, feel free to reopen if this happens again!
