### ISSUE TITLE
Warn user instead of error after run when active realisations < MIN_REALIZATIONS

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3727]
**Describe the bug**

If the user specifies a set of realizations that is smaller than `MIN_REALIZATIONS` in the config file, all forward models can succeed and still ert will produce a failure. Ert has enough information before running that this will fail.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Make sure `MIN_REALIZATIONS` > 1
3. `ert gui my_config.ert`
4. Run experiment and specify single realization

**Expected behaviour**
A warning that user has specified less than `MIN_REALIZATIONS` from config and have them either specify more realizations or change `MIN_REALIZATIONS`.

**Environment**
 - OS: [e.g. RHEL7]: all
 - ERT/Komodo release: main
 - Python version: all
 - Remote/HPC execution involved: [N/A] (valid for both)

**Other**
https://github.com/equinor/ert/pull/3426
This PR changed the behaviour, as ert used to take the minimum between chosen realizations and `MIN_REALIZATIONS`. This issue proposes that the change should stay, but we can stop users from running an experiment that ultimately will fail.

**Comment by sondreso** [comment]
See also: https://github.com/equinor/ert/issues/4328
