### ISSUE TITLE
"Warning:: invalid node" printed multiple times on the terminal

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#3749]
**Describe the bug**
The warning "Warning:: invalid node ... " is printed in the terminal multiple times when we create a new plot with simulations. Printing the warning seems to make loading the plot much slower. This was experienced while running Drogon tutorial, but probably happens with other config files.

**To reproduce**
Steps to reproduce the behaviour:
1. `tar xhf /scratch/fmu/share/drogon/course/drogon_current.tar.gz`
2. `ert gui /private/USER/drogon_20211115_12-12/resmod/ff/21.0.1/ert/model/drogon_ahm.ert`, substitue USER
3. Click `Create plot`
4. Select TRACER_SIM@1, default_0 and default_3
5. Get error:
6. ** Warning:: invalid node found at offset:18783552 in datafile:/private/hnfo/drogon_20211115_12-12/resmod/ff/21.0.1/ert/output/storage/01_drogon_ahm/default_3/Ensemble/mod_0/PARAMETER.data_0 - data will be lost, node_size:0
** Warning:: invalid node found at offset:11829696 in datafile:/private/hnfo/drogon_20211115_12-12/resmod/ff/21.0.1/ert/output/storage/01_drogon_ahm/default_3/Ensemble/mod_5/PARAMETER.data_0 - data will be lost, node_size:0

**Expected behaviour**
The warning should not be printed or should be printed only once.

**Screenshots**

**Environment**
 - Komodo release: 2022.08.01-py38 and 2022.08.01-py38

** Additional comments: **
@oyvindeide, maybe you have something to add/modify on this issue.

**Comment by oysteoh** [comment]
Could you check if @frode-aarstad 's fix merged today also removed the error msgs you discovered here? https://github.com/equinor/ert/pull/3753

**Comment by oyvindeide** [comment]
Will be fixed in storage refactor, closing.
