### ISSUE TITLE
Create one common folder for logs

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3756]
**Is your feature request related to a problem? Please describe.**
ERT creates several logs every time it is started, which quickly will fill up and clutter the current folder with new files. We should have a separate folder for logs, such that it is easier to both find relevant logs, but also make it easier to clean them up once they are not needed anymore. 

**Describe the solution you'd like**
One folder named `logs` (or something similar) where all logs are stored. It would also be nice if this folder was configurable.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hnformentin** [comment]
This is probably related to #3749

**Comment by sondreso** [comment]
#3749 is related to the double parsing of the config file that happens when the API is started, so not directly related to this one where the goal is to have one common place to store log files for ERT.

It is related to https://github.com/equinor/ert/issues/3432, though that is slightly broader.

**Comment by frode-aarstad** [comment]
What would be the preferred way of specifying the log dir. On the command line, using an environment variable or adding a new (or using an existing) keyword to the ert config file?

**Comment by sondreso** [comment]
I think the command line option is the best 🙂
