### ISSUE TITLE
Torque driver loses tracking of finished jobs

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3781]
**Describe the bug**
The Torque driver seems to lose tracking as jobs are finished (meaning ert still things they are running), particularly when there are many jobs executed at the same time. The normal progression for jobs from running to finished is `R -> E -> F`, see the following from the qstat manual: 
```
...
E  Job is exiting after having run
F  Job is finished
...
R  Job is running
...
```

ERT detects the E state, and will set the job as done, however if the job is in the E state for a very short amount of time ERT will not detect it. There is no handling for the F state in ert (should be the same as for the E state), but in order to get jobs in F state you need to run `qstat` with the `-H` option. Note that this requires changes in the [qstat proxy](https://github.com/equinor/ert/blob/main/src/clib/lib/job_queue/qstat_proxy.sh) as well. 

**To reproduce**
Steps to reproduce the behaviour:
1. Run polynomial example in Azure, and observe that some jobs will be marked as `UNKNOW`, and an error message about `JOB_QUEUE_STATUS_FAILURE` will appear in the terminal. 

**Expected behaviour**
ERT should handle both E and F state, as well as be able to track all jobs until they are marked as success or failure. 

**Screenshots**
N/A

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: main
 - Python version: 3.8
 - Remote/HPC execution involved: yes (PBS)

See also: https://github.com/equinor/ert/issues/3726

**Comment by berland** [comment]
`qstat -x` seems a better option, it will merge the default output with the extra output provided by `-H` (which otherwise only prints Finished jobs)
