### ISSUE TITLE
gui plot does not include History data set and label for observations

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#3791]
**Describe the bug**
Plotting the Drogon data as the tutorial does not display History data set.
From the discussion we had with @berland and @lars-petter-hauge , History is expected to be displayed.
What we intended to have removed was only the Refcase.
Also, the labelled for the observations is missing.

**To reproduce**
Steps to reproduce the behaviour:
1. Get a copy of the data set of Drogon tutorial (tar xhf /scratch/fmu/share/drogon/course/drogon_current.tar.gz)
2. source /prog/res/komodo/stable/enable
3. cd drogon_20211115_12-12/resmod/ff/21.0.1/ert/model
4. ert gui drogon_ahm.ert
5. Select data as indicated in the image

**Expected behaviour**
Expected to have the History data plotted, in addition to the ensembles and the observations.
Also, I would expect to have the observation + uncertainty labelled, because it is relevant to know if we are plotting +- 1 standard_deviation, or +-3 standard_deviation.

**Screenshots**
This is from the Drogon tutorial:
![image](https://user-images.githubusercontent.com/62240435/185863789-d0be0b40-a6f3-4de1-abbf-2d5f5245f3aa.png)

This is what is plotted from ert gui:
![Screenshot from 2022-08-22 09-06-42](https://user-images.githubusercontent.com/62240435/185863694-866dbe33-c552-4def-a02a-ffe51a0bb004.png)

**Comment by hnformentin** [comment]
This is actually a change in ert behavior, the config file of Drogon should contain the history values to be loaded.

**Comment by lars-petter-hauge** [comment]
It should also be noted that changing the ert config file (e.g. including `SUMMARY <name>H` (the `H` suffix) of the vector will only make ert load the history vector into storage.

The previous ert version would include plotting those historic vectors if available. In the new version, given that the user has opted for loading historic vectors, they will have to explicitly pick them from the list of vectors to plot.

And it is likely also inefficient, as I guess the plot will plot the historic vectors for all realizations (so duplicate plots...)
