### ISSUE TITLE
Creating SiteConfig from dict and from file results in very different objects

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3801]
When creating `SiteConfig` from a file name. The job list will be populated, while if you create from dict, the list will not be populated. This will have to be reconsiled in some way. Perhaps the best way to handle it is that both code paths will have to explicitly add the jobs.

Current behavior:
```python
>>> from ert._c_wrappers.enkf import SiteConfig
>>> filename = "..." # name of config file
>>> config_dict = {...} # Config dictionary with same values as the config file
>>> SiteConfig(filename).getAvailableJobs()
ExtJoblist(size=28, joblist=['DELETE_FILE: 94668020356560',...
>>> SiteConfig(config_dict=config_dict).getAvailableJobs()
ExtJoblist(size=0, joblist=[]) ...
```

**Comment by oysteoh** [comment]
Relates to #2571
