### ISSUE TITLE
Create experiment builder

### ISSUE THREAD

**Issue by xjules** [equinor/ert#3804]
It would make sense to implement experiment builder, exposing thus `simulation_arguments` as different parameters that currently come in a form of dictionary entries. Part of such builder is to then set (and create) the experiment id. 

One minor issue being that the Ensembles shouldn't not be pre-created at the same time, but rather to use `EnsembleBuilder` as an experiment attribute which would then build the ensemble once prepared to be run. This reflects mainly dynamic parameters, which can change between different ensemble runs; eg. a list of `active_realizations`.

**Comment by xjules** [comment]
For a reference please have a look at the comment from @lars-petter-hauge https://github.com/equinor/ert/pull/3811/files#r964512272

**Comment by oyvindeide** [comment]
EnsembleBuilder has been removed, and there has been a lot of changes to this part of the code, so suggest creating new issues which will be more relevant when this is revisited.
