### ISSUE TITLE
Broken functions in job_queue

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3809]
The following functionality is supposedly used outside of ert but seems to simply be broken, and should likely just be removed:

https://github.com/equinor/ert/blob/d20ddc3b63cf4f5a7dc2efcfe841e7944d287392/src/ert/_c_wrappers/job_queue/workflow_job.py#L98

`WorkflowJob::isPlugin` calls `issubclass(script_obj, ErtPlugin)` which probably always fails, the intention was probably to call `isinstance(script_obj, ErtPluin)`.

https://github.com/equinor/ert/blob/d20ddc3b63cf4f5a7dc2efcfe841e7944d287392/src/ert/_c_wrappers/job_queue/workflow_job.py#L146

run calls `script_obj` which is supposedly an instance of ErtScript which is not callable. Likely the code changed from `loadScriptFromFile` returning the ErtScript class to returning an instance of ErtScript

**Comment by oyvindeide** [comment]
This has recently seen some refactoring, is this issue still relevant, or can it be closed?

**Comment by eivindjahren** [comment]
I believe it is no longer relevant.
