### ISSUE TITLE
IndexError: _Map_base::at when starting simulation

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3813]
**Describe the bug**
ERT produces the following error message at the very start of the simulation:

![image](https://user-images.githubusercontent.com/3437958/186855092-7909e402-33b1-4a8d-9e65-93ecd64a9f60.png)

**To reproduce**
To be determined

**Expected behaviour**
No error message or more clear feedback if something is not configured correct.

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2022.08.01
 - Python version: 3-8
 - Remote/HPC execution involved: yes

**Additional context**
Originally reported on Yammer. Follow link to see complete log file: https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTg4NTMxOTU5NzgxNzg1NiJ9

**Comment by oyvindeide** [comment]
This occurs because the user has a `GEN_KW` named `PRED`, minimal case to reproduce:

```
JOBNAME my_name%d
NUM_REALIZATIONS 1
GEN_KW PRED template.txt kw.txt prior.txt
```
which also requires:

`template.txt`:
```
MY_KEYWORD <MY_KEYWORD>
```

`prior.txt`:
```
MY_KEYWORD NORMAL 0 1
```
