### ISSUE TITLE
Check if `GEN_PARAM` is in use

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3829]
This might not be used by anyone, and should check if it could be removed. It is a slight variation of `GEN_KW`, but unsure if anyone is actually using it.

**Comment by frode-aarstad** [comment]
`AppTraces
| where Message has "Content of the configuration file" and Message has "GEN_PARAM"
`
Returned 0 hits since 01.01.2022

**Comment by sondreso** [comment]
NB: We only store logs for the last three months :slightly_smiling_face:
