### ISSUE TITLE
Add functionality related to delete existing ERT storage for ensemble CASE based on user config/choice

### ISSUE THREAD

**Issue by KetilN** [equinor/ert#3857]
**Problem description:** 
Existing ERT storage often contains REFCASE with different DATES in the Eclipse SCHEDULE compared to the dates in the Eclipse SCHEDULE in the multiple simulation cases. By deleting the ERT storage or creation of a new CASE-NAME, this problem is resolved. Constant creation of new CASE-names is of course an ordinary used workaround today, but this makes the usage of ERT much more complicated than needed, since this requires a constant focus on cleanup of intermediate cases, and it also make some confusion regarding which CASE-version to further develop.

**Proposed solution:**
The proposal is to add two related fuinctionalities:

1. Add a CONFIG-OPTION in the ERT-config that states:

ALWAYS_DELETE_EXISTING_ERT_STORAGE_BEFORE_NEW_ENSEMBLE_RUN

If set to "1" or "TRUE" (exact "parameter type" needs to be defined in detail), 
ERT-Storage should be deleted every time before a new ensemble folder structure is created.
Default should be set to "0" or "FALSE".

2. If the user is about to run a new ensemble run, the user should always be asked:
"You have an existing ERT-storage. Do you want to delete the ERT-Storage ?"

**Alternatives that have been considered**
A relevant alternative is that ERT always deletes the ERT-storage per default before the new ensemble folder structure is created.
An extra option in this alternative could be to make the opposite parameter names: 
DO_NOT_DELETE_EXISTING_ERT_STORAGE_BEFORE_NEW_ENSEMBLE_RUN. (Default: "0"/"False".)

The reason for this alternative to be set aside, is that right now we have not been able to analyze all 
negative side-effects of adding this feature. 
Maybe later after multiple users have selected to delete existing ERT storage for their new ensemble runs,
this may prove to be a general good alternative for all.

**Additional context**
The main context for this feature request is that history matching is performed on an ensemble, 
and that prediction is performed in turn based on the Eclipse restart files from this ensemble.
Then SCHEDULE DATES will normally be different between the history matching and the prediction.

**Comment by oyvindeide** [comment]
I am going to close this issue because there has been a significant refactoring of the internal storage, so the original cause for this issue is no longer present. It is slightly related to: https://github.com/equinor/ert/issues/8021, which we will fix. If there are any new issues with storage, feel free to make a new issue, and we look into it.
