### ISSUE TITLE
Investigate lsf failure handling

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#386]
Users have reported issues when the lsf system and/or disk goes down temporarily. In particular, the `lsf` commands are not available. We could mock this scenario and test how ERT behaves to try to increase the robustness.

We should also investigate how killing jobs behave in this scenario.

**Comment by ManInFez** [comment]
Using symlink to mock loosing lsf commands results in:

Loosing connection: 
- all unfinished realizations are set as waiting
- all submitted realizaions run and finish on the cluster
- kill simulation will not do anything to the submitted realizations

regaining connection: 
- continue as normal, resubmitting all that realizations set as waiting

Will look into the lsf_driver to prevent it from submitting jobs which are already running/pending on the cluster
