### ISSUE TITLE
Make it more clear how to delete `storage_server.json`

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3865]
**Describe the bug**
From time to time ERT is leaving the `storage_server.json` behind on disk after it is terminated. The assumption is that this happens when ERT util_aborts and the "at_exit" handlers in python is not invoked and removing the file as it should. This again leads to users getting the message about this file they do not relate to, and they question what to do. In order to reduce this "noise" we should have a look and see if there is anything more we can do to make sure we are cleaning up what we should no matter how ERT is terminated.

**Comment by oysteoh** [comment]
We have discussed this and there is not much we can do currently when ERT goes util_abort on us. But - we should make it even more clear what should be done to remove the `storage_server.json` file. Printing the actual command to remove it along with the message we currently do would be a nice improvent, especially after #3873 .

**Comment by DanSava** [comment]
I think it might be possible that in place of printing the command to remove the file and make the user do it and then restart ERT. To just start the storage server again and overwrite the connection information.

**Comment by oysteoh** [comment]
But - imagine one user running ERT  - and then another user tries to run the same config-file. Wouldn't that cause the `storage-server.json` to be ripped out underneath the first users feets?
