### ISSUE TITLE
Set up Jenkins jobs that test against different komodo version

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#387]
Make jenkins jobs that run all tests of libres and ert every night using komodo: bleeding, unstable, testing and stable.

**Comment by mortalisk** [comment]
I have some difficulty understanding what is wanted here.

Should there be two separate jobs, one for ert and one for libres?

Should the tests run against the version in komodo or against the version in git?
 - if against git, then should both res and ert be the one from git, or one at a time

I guess we would expect the stable and unstable to fail a lot of the time, except right after a new deploy if things are working? Bleeding will reflect if the current master branches of everything is compatible with each other.  What is testing?

**Comment by andreabrambilla** [comment]
The point here is to test against the code in the komodo releases.
Which means:
- `komodo_version` is a parameter of the build
- retrieve the version of `ert` used in the `$komodo_version` release (there is a piece of code that does this in the `everest-komodo-run` job 
- clone the `ert` repo anche checkout the version determined in the previous step
- run the tests

**Comment by mortalisk** [comment]
Done: Set up multi-komodo-run which runs both ert and libres with all komodo releases ech night. However only a few of them are passing. I also was unable to get the compiled c tests in libres to run correctly.

Todo: Figure out if we should run c tests, and if so, how. Figure out why each failing build fails.

**Comment by andreabrambilla** [comment]
Out of curiosity, are you doing this using Jenkins pipelines or something else?

**Comment by markusdregi** [comment]
> Todo: Figure out if we should run c tests, and if so, how.

We should definitively run the C-tests as a lot of the code is only tested from a C-perspective. Whether it makes sense to have tests in C++ given that _libres_ now only have a Python API is another discussion. But, step by step...

**Comment by mortalisk** [comment]
C tests are now pasing in libres.
Some python tests are still failing for libres. Separate issues should be created to solve these.
Python tests for Ert are running for bleeding.

When (and if) the pull requests are merged, the jenkins jobs libres-komodo-run and ert-komodo-run should be changed to run against equinor/ert and equinor/libres instead of my corresponding forks.

**Comment by mortalisk** [comment]
Currently failing python tests for libres:

- ErtWorkflowListTest
- SiteConfigTest
- ResConfigTest
- AnalysisConfigTest
- JobDispatchTest (this one is already fixed in #653)

**Comment by mortalisk** [comment]
The jenkins multi configuration project [multi-komodo-run](https://ci.equinor.com/be/view/SCOUT/job/multi-komodo-run/) runs each night for bleeding, unstable, testing and stable, and starts the two other projects [libres-komodo-run](https://ci.equinor.com/be/view/SCOUT/job/libres-komodo-run/) and [ert-komodo-run](https://ci.equinor.com/be/view/SCOUT/job/ert-komodo-run/)
