### ISSUE TITLE
random seed in test not random enough ?

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#3870]
**Describe the bug**
The following test fails in CI github action on a PR with unrelated changes:

```
FAILED libres_tests/integration/test_parameter_sample_types.py::test_initialize_random_seed[We initialize twice without setting the random seed either time so expect the result to be different both times]
```

This flakiness / unexpected failure should be addressed. The test has been disabled in the meantime, cf. PR #3869 / commit 408b630cdb0f269cae4f6ad576ffb7033bf98267

**Comment by oyvindeide** [comment]
Think we came to the conclusion that this test was a bit redundant, we are using numpy as our RNG now, and think we can assume that it is more robust.
