### ISSUE TITLE
Move queue enum states into a standalone file

### ISSUE THREAD

**Issue by xjules** [equinor/ert#3885]
The following states and the corresponding transitions should be moved to a stand-alone file:
https://github.com/equinor/ert/blob/202ccd9c5000b1bb86b7b179f9d0dd4d62e7e1cb/src/ert/_c_wrappers/job_queue/queue.py#L61-L86

**Comment by jonathan-eq** [comment]
Closing this as the first part has already been done in 29d0fe49, and the second part is jobqueue specific so there is a different, corresponding type map in scheduler.
