### ISSUE TITLE
Memory diagnostic and reporting for forward models

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#389]
On cluster nodes with limited memory, it is beneficial / necessary for the user to provide the queuing system upfront information on how much memory is required. Average users typically have no idea. It would be very useful if ERT could monitor and report memory usage for jobs as a whole and for each forward model component ( this one is more tricky).

**Comment by joakim-hove** [comment]
This could probably be done in the job dispatch script, the psutil library seems to have relevant functionality all ready

**Comment by markusdregi** [comment]
It does also seem that one can get lsf to report maximum memory usage in the report for each forward model...

**Comment by eivindsm** [comment]
Having job_dsipatch monitor this enables the possibility to track each individual forward model component to. This could be reported in the new monitoring display along with status and logs.

**Comment by sondreso** [comment]
> This could be reported in the new monitoring display along with status and logs.

Does this refer to the lower panel in the simulation window like below? 
![Screenshot from 2019-08-14 12-23-24](https://user-images.githubusercontent.com/3437958/63014320-8ce59380-be8e-11e9-9d09-619641d1ef01.png)

**Comment by markusdregi** [comment]
@sondreso Yes, that is what I had in mind 👍
