### ISSUE TITLE
Provide a QC-tool for manual comparision of DATES in template CASE SCHEDULE, REFCASE SCHEDULE and OBSFILE

### ISSUE THREAD

**Issue by KetilN** [equinor/ert#3906]
**Is your feature request related to a problem? Please describe.**
ERT-users often would like to update the SCHEDULE DATES in a FMU-project. A main problem today is that inconsistencies between a REFCASE and the BASECASE lead to "for the user" unexpected behaviour that often leads to need for adjusting and rerun of FMU-ensembles.

**Describe the solution you'd like**
I want ERT to provide a manual oriented QC-tool for manual comparision of DATES in BASECASE SCHEDULE, REFCASE SCHEDULE and OBSFILE.

**Describe alternatives you've considered**
An alternative is an automatic approach for warning the user automatically about inconsistencies between a REFCASE and the BASECASE. Since this seems to difficult, a manual approach is chosen,

**Additional context**

**Comment by KetilN** [comment]
Here is a new user case where the user tried to add some wells to the BASE model without updating the REFCASE:

https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjA3NjQyNDA1MDgxMDg4MCJ9

**Comment by KetilN** [comment]
Please also consider to remove the need to process the REFCASE if only Prediction run is used. In this user problem case, an easy fix seems to be just to remove the REFCASE, and this should have been possible to discover automatically by ERT.

**Comment by KetilN** [comment]
The concept "template CASE" will replace the word BASECASE.

**Comment by KetilN** [comment]
Note that this Feature Request is not relevant anylonger given a 100 % fullfillment of this newer Feature Request: 
Automate generation of REFCASE to be used in Assisted History Matching in ERT #4556

**Comment by oyvindeide** [comment]
Will close this as it is related to #4556, thanks for creating the issue though 😄
