### ISSUE TITLE
Discover the reason why protobuf needs to be pinned

### ISSUE THREAD

**Issue by xjules** [equinor/ert#3923]
Resinsight / rips requires `protobuf==3.19.1` or lesser version and failing with newer versions. Since ert now depends on protobuf too, which should find out why this is so.

**Comment by xjules** [comment]
The `protobuf` is now relaxed to `protobuf<4`; see here: https://github.com/equinor/ert/pull/3968
The should include whether `proto2` or `proto3` is related to pinning it.

**Comment by berland** [comment]
`rips` pins currently to below `3.21`: 
https://github.com/OPM/ResInsight/blob/dev/requirements.txt

**Comment by oyvindeide** [comment]
Protobuf is not pinned anymore, so will close this.
