### ISSUE TITLE
Restrictions on time map cause the AHM case to fail

### ISSUE THREAD

**Issue by MitraMor** [equinor/ert#3927]
In the AHM course , case "sens_analysis_with_pred.ert" will failed due to the following error. 

![failed](https://user-images.githubusercontent.com/43606882/191733895-8223e9cd-476e-4fd6-ab28-809203532f82.jpg)

I have tried to run it with older version of Komodo and then it works with a warning in terminal. Please look at following: 

![not failed](https://user-images.githubusercontent.com/43606882/191735540-18b8157a-f67c-495f-ac39-b8d484c13768.jpg)

Can you remove this restriction? The AHM course is coming and there are not enough time to change the files or update the course material.

The error is explained in slacks:
 https://equinor.slack.com/archives/CDPJULWR4/p1663765317969209

**To reproduce**

1. Download the AHM: wget https://sdp.equinor.com/wikidocs/FMU/public/reek_hm_r006_20210415.tar.gz
2. ert gui sens_analysis_with_pred.ert
3. Run experiment Smoother

**Expected behaviour**
As shown in picture 1

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - First one: 2022.08.02-py38  (stable version komodo)
 - Older version that is used: 2021.12.01-py36  
 - Remote/HPC execution involved: no

**Comment by oyvindeide** [comment]
Could only reproduce that the changed behavior was an explicit error message instead of a silent error which both had the same result, no data was loaded. Feel free to reopen though if your experience was different.

**Comment by hnformentin** [comment]
@oyvindeide I think the problem that we just discussed is the same reported here. It is indeed difficult to reproduce (as we tried :-) , but did you get any other insights that could help to understand why no message popped up when the time map error happened?

**Comment by oyvindeide** [comment]
No, did not find out anything new, but strange that it worked the second time we ran the case. I think I figured out why there was no error popping up, but that was unrelated: https://github.com/equinor/ert/pull/4127

**Comment by oyvindeide** [comment]
Maybe related to: https://github.com/equinor/ert/issues/4946

**Comment by oyvindeide** [comment]
@MitraMor do you know if this is possible to reproduce or if it has been fixed?

**Comment by MitraMor** [comment]
Hi, I have not check it recently. I can check it later on but not this week.

**Comment by oyvindeide** [comment]
Think this is fixed in recent versions, feel free to reopen if it can be reproduced.
