### ISSUE TITLE
Delete or verify that snake_oil_field works

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#3938]
**Describe the bug**
We are not sure that [test-data/local/snake_oil_field/make_data.py](https://github.com/equinor/ert/pull/3851/files#diff-3b7a85ae1dce0d6bfe4c230af28d4de4f91d080322d114239ae1573db664b9ef)is working. Check if this is the case and fix or delete.
Problem identified while reviewing #3851.

**Comment by berland** [comment]
```
(new) [havb@be-lx895926:/work/projects/ert/test-data/local/snake_oil_field] main$ python make_data.py
Traceback (most recent call last):
  File "make_data.py", line 8, in <module>
    from ecl.util import RandomNumberGenerator
ImportError: cannot import name 'RandomNumberGenerator' from 'ecl.util' (/work/venv/new/lib64/python3.8/site-packages/ecl/util/__init__.py)
```
