### ISSUE TITLE
Change how data is stored in `pandas` in `MeasuredData`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#3959]
Note that this is a breaking change since `MeasuredData` is returned in `get_measured_data` of `libres_facade.py`.
This is used by `semeio` and possibly other projects.

Data is currently stored like this (see `tests/ert_tests/data/test_integration_data.py`):

![foprh_current](https://user-images.githubusercontent.com/45088507/192958771-9adbefd9-343f-4fd2-b495-938bb0e04bb4.png)

I would like it to be something like this:

![foprh_new](https://user-images.githubusercontent.com/45088507/192958841-c0dc6436-ca0c-4f35-86ca-b7b4b13af0c0.png)

To be able to do things like this:

![foprh_query](https://user-images.githubusercontent.com/45088507/192958858-4c7e7466-3104-4dda-8fd5-2e81fe4f4042.png)

**Comment by pinkwah** [comment]
Blocked by #4079

**Comment by oyvindeide** [comment]
@dafeda is this still something we would like to do in the short term?

**Comment by dafeda** [comment]
Not in the short term no. We can close and re-open at a later stage.

**Comment by oyvindeide** [comment]
We can keep the issue open, but I will remove it from our TODO then.

**Comment by dafeda** [comment]
> Blocked by #4079

Removed block since issue is closed

**Comment by dafeda** [comment]
Closing as stale and not that important.
