### ISSUE TITLE
Move enkf_node implementation of SURFACE

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3977]
We have been doing refactoring of the callbacks and sampling, and should be ready to save data differently from before. This includes removing enkf_node implementation SURFACE which is loading parameters from the forward model in the OK callback or in the creation of the run path. We should try to drop `surface.cpp` and instead load the surface using XTGeo, and probably just save the surface as is.

**Comment by dafeda** [comment]
Just jotting down some findings.

I think the part we want to replace with XTGeo is in `surface_config_set_base_surface` where the function `geo_surface_fload_alloc_irap` is called.

`geo_surface_fload_alloc_irap` is implemented in ECL and loads RMS Surface Files that I think have the format .IRAP.

`surface_config_set_base_surface` is only called from `enkf_config_node_update_surface`, but `enkf_config_node_update_surface` is called twice;

once from `enkf_config_node_alloc_SURFACE_full`

and once from `ensemble_config_init_SURFACE`.

`enkf_config_node_alloc_SURFACE_full` is called from the Python class `EnkfConfigNode` while `ensemble_config_init_SURFACE` actually parses the config-file.

**Comment by ManInFez** [comment]
closed by #4484
