### ISSUE TITLE
Error when starting up if the Eclipse DATA-file used in RUN_TEMPLATE include a PARALLEL keyword and no NUM_CPU is set in the ERT-configfile

### ISSUE THREAD

**Issue by KetilN** [equinor/ert#3979]
**Is your feature request related to a problem? Please describe.**
Without this feature, the LSF-cluster will get overloaded with Eclipse-jobs running out of the NUM_CPU=1 allocation of cpu's per job.

**Describe the solution you'd like**
I want that the user cannot startup ERT before the user has by intention setup a NUM_CPU value in the ERT-configfile when the Eclipse DATA-file used in RUN_TEMPLATE include a PARALLEL keyword, and that the user gets an error message that reflects this.

**Describe alternatives you've considered**
Another alternative I have considered, is to only report a warning message to the user. However, the experience is that the warnings from ERT is read by too little users, and especially it is seldom that the users take action from them.

**Additional context**
The main context for this issue, is that the ERT-config-file includes a RUN_TEMPLATE statement that points to an Eclipse DATA-file that includes a PARALLEL keyword.

**Comment by oyvindeide** [comment]
Thanks for reporting! We have had some discussions regarding this, and I think in the first iteration we will remove the deprecation warning for `DATA_FILE` and add more documentation around how `NUM_CPU` works and add a recommendation about how to use that. Our motivation for deprecating this functionality was that we wanted to be explicit about what resources are being allocated, and secondly we dont have a very good parser of the data file, so the parsing can be error prone.

**Comment by oyvindeide** [comment]
Closed by: https://github.com/equinor/ert/commit/29fb7c5e6e59e71208a3c2196f9cbb150afc64bc
