### ISSUE TITLE
Simplify config objects

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#3986]
After #3957 - Initialization of the following should be moved out to ResConfig. These remaining issues should be really simple and stupid. The moving of the functionality should not change behavior from what it is today.

- [x] #4004
- [x] #4020
- [x] #3987
- [x] #4068 
- [x] #4073
- [x] #4209
- [x] #4012
- [x] #3751
- [x] #3918
- [x] #4035 
- [x] #4048
- [x] #4178
- [x] #2571
- [x] #4168
- [x] #4180
- [x] #4197 
- [x] #4253 
- [x] #4254
- [x] #4337

**Comment by valentin-krasontovitsch** [comment]
at least these have implicit site config parsing, according to a quick grep:

- hook manager
- site config
- queue config (not anymore after eivind's PR)
- ert workflow list
