### ISSUE TITLE
No clean up occurs if CLI is stopped with Ctrl+C

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4006]
**Describe the bug**
If the CLI is stopped with Ctrl+C the simulations are not stopped, instead ert stops with `ERT crashed unexpectedly with: Signal 2 received`

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Run experiment (Test) from CLI
3. Press Ctrl+C

**Expected behaviour**
Would expect to get a message, `Killing simulations, please wait` and that the jobs running in the queue are cancelled.

This was intended to be handled here:
https://github.com/equinor/ert/blob/2a987aea12b5db4f5770e5723e1e98800499f81c/src/ert/shared/cli/main.py#L114

but because of: 
https://github.com/equinor/ert/blob/2a987aea12b5db4f5770e5723e1e98800499f81c/src/ert/services/_base_service.py#L48

and 
```python
def cleanup_service_files(signum: int, frame: Optional[FrameType]) -> None:
    for file_path in SERVICE_CONF_PATHS:
        file = Path(file_path)
        if file.exists():
            file.unlink()
    raise OSError(f"Signal {signum} received.")
```
we are raising an OSErros instead which is only caught at the very entry point.

**Comment by oyvindeide** [comment]
Duplicate of: #3134

**Comment by oyvindeide** [comment]
Decided to reverse, this is related to: https://github.com/equinor/ert/issues/3134

**Comment by berland** [comment]
Catching the `OSError` is fixed in https://github.com/equinor/ert/pull/7026 

Killing all simulation upon ctrl-c is currently not something we want to do.
