### ISSUE TITLE
Torque driver unable to get job status

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/ert#405]
Running Ert (cli) on the Azure cluster using the torque driver
Right after starting, a message like this is spit out for every job:```** Warning: failed to get job status for job:218 from file:/tmp/enkf-qstat-5956-365084```  
I do have write access to the `/tmp` folder, but the file is not created (regular users might have write access to that folder, but that's another issue).

The jobs actually are started and complete correctly, but Ert hangs, most likely because it's unable to detect that the jobs are completed

**Comment by markusdregi** [comment]
Did you test the setup on the internal torque cluster first?

**Comment by markusdregi** [comment]
The torque driver sees little usage and since the current Azure testing is done on a PBS-cluster I'm voting for closing this one.

**Comment by jondequinor** [comment]
This seems to have reemerged.

```
qstat: Invalid credential
** Warning: failed to get job status for job:6725 from file:/tmp/enkf-qstat-25008-648985
Exception in thread Thread-6:
Traceback (most recent call last):
 File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
   self.run()
 File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
   self._target(*self._args, **self._kwargs)
 File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/res/job_queue/job_queue_node.py", line 218, in _job_monitor
   raise AssertionError(
AssertionError: Unexpected job status type after running job: JOB_QUEUE_STATUS_FAILURE
```

Shouldn't we try again if the error code here
https://github.com/equinor/ert/blob/d88cdd1c278c779609b514e7286bae57612d5a3e/libres/lib/job_queue/torque_driver.cpp#L527-L528
is non-zero?

**Comment by jondequinor** [comment]
It was indicated in chatter about this issue, that 

> The source of invalid credential is possibly if the PBS master  scheduler service is being restarted. Trying again after 1-2 sec should get the real status.

Sounds like retrying 3-10 times with exponential sleeps could work.

**Comment by sondreso** [comment]
The torque driver has the following comment above the `get_qstat_status` function:
https://github.com/equinor/ert/blob/dd35621640fe727732c012861553cf68fea3dfcf/libres/lib/job_queue/torque_driver.cpp#L505-L513

However, looking at the monitoring code in this function https://github.com/equinor/ert/blob/dd35621640fe727732c012861553cf68fea3dfcf/res/job_queue/job_queue_node.py#L172

It does not appear that the `JOB_QUEUE_STATUS_FAILURE` is ignored, but instead is considered to be the actual status of the job. The LSF driver does not produce this response for any codepaths, which is probably the reason why this error does not appear in production.
