### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#406]

**Comment by Amrithnath** [comment]
Hey @markusdregi  I haven't done this before but I would like to try, could you point me in the right direction so I can start?

**Comment by markusdregi** [comment]
That is really cool @Amrithnath. I must admit that we neither are experts on _CircleCI_. We have mostly been using _Travis_ and _Jenkins_, but would like to start utilizing other CI providers as well.

@sondreso and @jondequinor just started the same process in another of our repositories: https://github.com/equinor/configsuite/pull/81. If you are interested, you are most welcome to try to setup a CircleCI pipeline for _ERT_.

**Comment by Amrithnath** [comment]
Alright giving this a try 😄

**Comment by Amrithnath** [comment]
Quick question, the ERT build would be starting from step two of README.md for this project right?

**Comment by markusdregi** [comment]
No, _libecl_ and _libres_ are currently not available on PyPI (nor pip installable for that matter). If I were you I would start by trying to install the software locally and having the tests succeed. Also, the `.travis.yml` (https://github.com/equinor/ert/blob/master/.travis.yml) might be helpful together with the readme.

**Comment by dotfloat** [comment]
Closing because we are using Github Actions instead.
