### ISSUE TITLE
Validate unknown function in init transform argument to enkf config nodes early (applies to FIELD config key and perhaps others)

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4070]
One argument to config keys that define enkf config nodes (which end up in ensemble config, so related to #4254) is an init transform, and there a function can be specified. if that function cannot be found, a util abort is triggered.

we should catch this error in python and return a meaningful error message.

a corresponding test is already defined (and skipped with reference to this issue) in `tests/test_config_parsing/test_ensemble_config.py`.

---

- [ ] Update docs with information on all available init & input and output transformations

**Comment by oysteoh** [comment]
Possible answer is to just delete code / simplify, should be investigated
