### ISSUE TITLE
Validate unique names for enkf config nodes early

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4071]
It appears that adding two enkf config nodes (which is the underlying type of many different config nodes, like field, gen_kw, gen_data, ...) to the ensemble config with identical names (here and there in the code also referred to as key, methinks) causes the C part of ert to call util abort.

we should capture this error early, ideally in python.

this issue is related to #4254, might even automagically get closed once that one is done.

the corresponding test is already fleshed out and skipped with reference to this issue in `tests/test_config_parsing/test_ensemble_config.py`, just the error message match should be updated in the tests once the error message is composed.

**Comment by oysteoh** [comment]
Possible answer is to just delete code / simplify, should be investigated
