### ISSUE TITLE
Plot vectors missing in recent Komodo update (2022-10-02)

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#4096]
ERT GUI plotting is missing some vectors after recent komodo update.

Komodo version 2022.09.03-py38  works fine:
![2022-09-03](https://user-images.githubusercontent.com/114403625/196633292-7ce1f2e4-383f-4dd8-b253-a8980d961014.png)

Komodo version 2022.10.02-py38 is missing some vectors in the plot:
![2022-10-02](https://user-images.githubusercontent.com/114403625/196633309-9b7975c7-c140-4021-8cdb-dbc450c3ca5b.png)

Original text:
> Hi, I see a problem in "create plot" ert gui since yesterday (after Komodo updated). While I am sourcing stable eversion (2022.10.02-py38) I do not see all the vectors in create plot (below picture) but when I source older version from September (2022.09.03-py38) everything looks normal, and it works (picture 2). Can you fix this bug?

**Comment by oyvindeide** [comment]
Suggest fixing this problem by expanding the summary key list immediately when the configuration is created, instead of sending the key matcher to the call back and then syncing the configuration to storage afterwards. That way, everything should be in sync at all times.

**Comment by andreas-el** [comment]
It turns out that wildcards do work, -- as long as there is a refcase present.
This is likely the reason why storage was inspected for available vectors.

**Comment by andreas-el** [comment]
Either adding a REFCASE to the .ert configuration or add expanded SUMMARY keywords will solve the issue for the REEK model.
```
REFCASE                 ../input/refcase/model/REEK
```

or

```
SUMMARY ROIP:1
SUMMARY ROIP:2
SUMMARY ROIP:3
SUMMARY ROIP:4
SUMMARY ROIP:5
SUMMARY ROIP:6
SUMMARY WOPR:OP_1
SUMMARY WOPR:OP_2
SUMMARY WOPR:OP_3
SUMMARY WOPR:OP_4
SUMMARY WOPR:OP_5
SUMMARY WOPRH:OP_1
SUMMARY WOPRH:OP_2
SUMMARY WOPRH:OP_3
SUMMARY WOPRH:OP_4
SUMMARY WOPRH:OP_5
SUMMARY WWPR:OP_1
SUMMARY WWPR:OP_2
SUMMARY WWPR:OP_3
SUMMARY WWPR:OP_4
SUMMARY WWPR:OP_5
SUMMARY WWPRH:OP_1
SUMMARY WWPRH:OP_2
SUMMARY WWPRH:OP_3
SUMMARY WWPRH:OP_4
SUMMARY WWPRH:OP_5
SUMMARY WGPR:OP_1
SUMMARY WGPR:OP_2
SUMMARY WGPR:OP_3
SUMMARY WGPR:OP_4
SUMMARY WGPR:OP_5
SUMMARY WGPRH:OP_1
SUMMARY WGPRH:OP_2
SUMMARY WGPRH:OP_3
SUMMARY WGPRH:OP_4
SUMMARY WGPRH:OP_5
SUMMARY WOPT:OP_1
SUMMARY WOPT:OP_2
SUMMARY WOPT:OP_3
SUMMARY WOPT:OP_4
SUMMARY WOPT:OP_5
SUMMARY WOPTH:OP_1
SUMMARY WOPTH:OP_2
SUMMARY WOPTH:OP_3
SUMMARY WOPTH:OP_4
SUMMARY WOPTH:OP_5
SUMMARY WWPT:OP_1
SUMMARY WWPT:OP_2
SUMMARY WWPT:OP_3
SUMMARY WWPT:OP_4
SUMMARY WWPT:OP_5
SUMMARY WWPTH:OP_1
SUMMARY WWPTH:OP_2
SUMMARY WWPTH:OP_3
SUMMARY WWPTH:OP_4
SUMMARY WWPTH:OP_5
SUMMARY WGPT:OP_1
SUMMARY WGPT:OP_2
SUMMARY WGPT:OP_3
SUMMARY WGPT:OP_4
SUMMARY WGPT:OP_5
SUMMARY WGPTH:OP_1
SUMMARY WGPTH:OP_2
SUMMARY WGPTH:OP_3
SUMMARY WGPTH:OP_4
SUMMARY WGPTH:OP_5
SUMMARY WWCT:OP_1
SUMMARY WWCT:OP_2
SUMMARY WWCT:OP_3
SUMMARY WWCT:OP_4
SUMMARY WWCT:OP_5
SUMMARY WWCTH:OP_1
SUMMARY WWCTH:OP_2
SUMMARY WWCTH:OP_3
SUMMARY WWCTH:OP_4
SUMMARY WWCTH:OP_5
SUMMARY WGOR:OP_1
SUMMARY WGOR:OP_2
SUMMARY WGOR:OP_3
SUMMARY WGOR:OP_4
SUMMARY WGOR:OP_5
SUMMARY WGORH:OP_1
SUMMARY WGORH:OP_2
SUMMARY WGORH:OP_3
SUMMARY WGORH:OP_4
SUMMARY WGORH:OP_5
SUMMARY WWIR:WI_1
SUMMARY WWIR:WI_2
SUMMARY WWIR:WI_3
SUMMARY WWIRH:WI_1
SUMMARY WWIRH:WI_2
SUMMARY WWIRH:WI_3
SUMMARY WWIT:WI_1
SUMMARY WWIT:WI_2
SUMMARY WWIT:WI_3
SUMMARY WWITH:WI_1
SUMMARY WWITH:WI_2
SUMMARY WWITH:WI_3
SUMMARY WBHP:OP_1
SUMMARY WBHP:OP_2
SUMMARY WBHP:OP_3
SUMMARY WBHP:OP_4
SUMMARY WBHP:OP_5
SUMMARY WBHP:ROP_4
SUMMARY WBHP:ROP_5
SUMMARY WBHP:RWI_2
SUMMARY WBHP:RWI_3
SUMMARY WBHP:WI_1
SUMMARY WBHP:WI_2
SUMMARY WBHP:WI_3
```
