### ISSUE TITLE
Everest broken after configuration work

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4109]
Seems like we have made some changes breaking everest
https://github.com/equinor/ert/commit/7c4b087e372fc05264c08749960d88ffaa81de59

**Comment by DanSava** [comment]
From `everest/util/__init__.py`

``` python 
def get_system_installed_jobs():
    """Returns list of all system installed job names"""
    res_config = _dummy_res_config()
    installed_jobs = res_config.site_config.get_installed_jobs()
    return installed_jobs.getAvailableJobNames()
```

Might have something to do with the breaking change.

ResConfig SiteConfig no longer supports `get_installed_jobs()`
