### ISSUE TITLE
Narratives uses TypeDict in a nonstandard way

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4124]
In https://github.com/equinor/ert/blob/0324ea059f51aa163dd093e6cff4301dd5bc8734/src/ert/shared/ensemble_evaluator/narratives/narrative.py#L74

`narratives.py` uses TypedDict and expects it to work like `dataclass`. However, this is not supported by `mypy`, and is not the intended use of `typing.TypedDict` according to the documentation.

**Comment by oyvindeide** [comment]
Narratimes have been removed, closing
