### ISSUE TITLE
Possible misplacement of docs around TEMPLATE config keyword

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4139]
In [working around ensemble config](#4075), we figured out that we could remove the `OUTPUT_FORMAT` option - but in the docs, that one was tied to the `TEMPLATE` keyword.

now i'm left with the impression that the info text about the template keyword should perhaps be somewhere else than it is right now, but I don't understand enough of the code / usage of the config to confidently place it myself, so I'm creating this issue instead.

**Comment by oysteoh** [comment]
I'll close this one for now as it is not actionable.
