### ISSUE TITLE
Loading indicator when manual analysis is performed

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4146]
When using RunAnalysis the `Run` button should be greyed out and there should be a spinning wheel or similar to indicate that the analysis is running.

**Comment by oyvindeide** [comment]
This might be solved already, should check that first.

**Comment by oyvindeide** [comment]
Related to #4094

**Comment by sondreso** [comment]
Duplicate of https://github.com/equinor/ert/issues/4840
