### ISSUE TITLE
Requirements File does not list pyqt5

### ISSUE THREAD

**Issue by DataScienceLeadJr** [equinor/ert#415]
requirements.txt does not list pyqt5 (whichever version might be wanted)

**Comment by markusdregi** [comment]
Hi @DataScienceLeadJr.

Thanks for reaching out! Notice that the pyqt5 support is still experimental and not thoroughly tested. We are currently working on ensuring Python 3 and pyqt5 compatibility, but we are not all done yet. The requirements will be updated then.

The absolute safest option is to use pyqt4.12.1 as is used in the internal stable deploy of _ERT_ in _Equinor_, or the 4.11.3 as used in the _Travis_-setup.

**Comment by DataScienceLeadJr** [comment]
Ah, I see. :+1:

Should base our project's ERT installation on the version-2.5 release branch then, which requires pyqt4.12.1? Which is not pip installable and so is not in the requirements.txt file?

I'll update the README on our side then to be more specific about the git clone url

**Comment by markusdregi** [comment]
Version 2.5 is at least the current stable version yes, with respective versions for libecl and libres indicated in the `.libres_version` etc. Which version you should use depends of course, but the stable version would definitively be much more stable then pulling the master branch.

Also, I sent you an email as I'm curious to know a little more about this project of yours ;)

**Comment by DataScienceLeadJr** [comment]
project: it's actually Wouter's DDPD ;)
So you guys have already talked about it turns out!

Closing this one then, since it's a none-issue.
