### ISSUE TITLE
use setuptools automatic script generation to advertise ert entry point

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#418]
Leave it to setuptools to install an ert _executable_.
See https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

Rationale:
- Is more portable, setuptools is informed on how to create executables in most environments.
- We can remove the _binary_, forcing installation of ert, which has the benefit of reducing potentially broken builds.
- Consistent with how popular tooling is distributed, e.g. nose, bandit, pyflakes, pylint.

**Comment by sregales-TNO** [comment]
Where are the entry points of ert?

- ert3.console:main
- ert_shared.main:main

**Comment by markusdregi** [comment]
No, that is only the `ert3` entry point. I think this issue basically boils down to stop using `scripts`

https://github.com/equinor/ert/blob/31c19c5adef61626c52b2d1c1f2d885cd9a52c89/setup.py#L23

and move that endpoint into `entry_points` instead 👍🏻

**Comment by sregales-TNO** [comment]
correction on the "see" link
- https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html?highlight=automatic%20script%20creation#entry-points-and-automatic-script-creation
- https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html
