### ISSUE TITLE
Simplify ExtJobList

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4180]

**Comment by valentin-krasontovitsch** [comment]
Related work has been done and merged in #4025 and #4114

**Comment by eivindjahren** [comment]
A good first step would be to move ForwardModel from being inside `ModelConfig` to being `ResConfig().forward_model`. This would mean moving the handling of the keywords `SIMULATION_JOB` and  `FORWARD_MODEL` to `res_config.py`.

**Comment by valentin-krasontovitsch** [comment]
I will try to do this first then, as i'm currently working on #4178 - let me know if this is needed sooner rather than later, i'm also open to pair programming this

**Comment by andreas-el** [comment]
That would be great to do. Let me dive into the code to get a feel before we start.

**Comment by eivindjahren** [comment]
I made a first stab of this here: https://github.com/equinor/ert/pull/4195
