### ISSUE TITLE
Add `<TIMESTAMP>` magic string / predefined define for ert config file substitutions

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4184]
This was raised in [a slack discussion](https://equinor.slack.com/archives/CDPJULWR4/p1667294063812139) [INTERNAL LINK] - the idea is for instance to be able to store results from different runs persistently, instead of having them overwritten, by adding a timestamp for instance in the case path.

at the moment, once #4183 is merged, one can use `<DATE>`, which gets substituted dynamically with the current date (`yyyy-mm-dd`) at the moment of ert runtime (startup), but for different runs started on the same day this is not sufficient.

we propose adding a `<TIMESTAMP>` predefined, which has time in addition to date.

**Comment by oyvindeide** [comment]
Think I will close this issue as it is not clear which `TIMESTAMP` we would use, it it startup time, or time of substitution? Might introduce more confusion than it solves.

**Comment by valentin-krasontovitsch** [comment]
for the described use-case, as far as i understand, it does not matter which time stamp is used - using *now* at runtime of initialising the config parser would be sufficient.
but it does add complexity, and i can see how it might lead to confusion.

as this was a user request, i suggest either hearing back with the user whether the use-case still exists and ask questions to clear out any confusion, or raising this during planning, as originally suggested.

**Comment by oyvindeide** [comment]
Have not heard repeated requests for this, and am not able to figure out who originally requested this, so will close this issue now.

**Comment by valentin-krasontovitsch** [comment]
always nice to get these notification emails with little throwbacks to scout, even if they are somewhat bittersweet, as in this case ; )
