### ISSUE TITLE
Simplify EnkfConfigNode

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#4253]

**Comment by andreas-el** [comment]
## Some good candidates for untangling next:
### Internalize
file: ./src/clib/lib/enkf/enkf_state.cpp
```
        if (config_node->internalize != NULL)
                bool_vector_safe_iget(config_node->internalize, report_step);
```

Notes:
- Internalize is set only during construction from enkf_config_node.py
- Internalize is only accessed ever from enkf_state.cpp

### Obs_keys

**Comment by oysteoh** [comment]
Changed the scope from moving completely to Python to just simplification
