### ISSUE TITLE
Replace narratives with off-the-shelf 

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4275]
We should consider replacing the narrative with an off-the-shelf module. An example of this is the package from `pact-foundation`, which has a python implementation `pact-python`.

**Comment by lars-petter-hauge** [comment]
The current implementation of narratives will have to be refactored quite a bit to fit with the refactoring in https://github.com/equinor/ert/issues/3948. For now we will remove the narratives and replace with new tests at a later stage, when we are picking up the continuation of experiment server.

**Comment by lars-petter-hauge** [comment]
Note that auto-generating docs should count in favour of tool chosen https://github.com/equinor/ert/issues/2314.

**Comment by oyvindeide** [comment]
As Narratives has been removed, I will close this issue.
