### ISSUE TITLE
Check if SCHEDULE_PREDICTION_FILE can/should have additional arguments in the config file

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#4288]
Currently, the key SCHEDULE_PREDICTION_FILE allows the additional arguments 
 * PARAMETER
 * INIT_FILES

It is not clear if they should be allowed or not. If not please remove the code that handles them.

**Comment by oysteoh** [comment]
Where is this defined? What i can find is that this key takes one or multiple files as an argument? 🤔

**Comment by valentin-krasontovitsch** [comment]
it's defined mostly in the source code, in ensemble config's init, and it uses (piggy backs) enkf config node type gen_kw - it is hence quite difficult to figure out which parts of a gen kw config node are used when it's a schedule file.

i have inquired the wise ones about this directly, and got the following first response (from @berland):

> Jeg vil gjette dette er blant de historiske ert-nøkkelordene som ikke er mye i bruk i dag. Utfra dokumentasjonen så er hovedfeaturen at man kan legge til en  %d-formatering slik at man kan ha realisasjonsspesifikke filer. Dette kan man gjøre på andre måter, så jeg vil si at vi bør deprecate og fjerne. Jeg har selv aldri brukt dette og kan heller ikke huske å ha sett noen som har brukt det.
