### ISSUE TITLE
Revise documentation structure

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#429]
The structure and major topics of the documentation should be revised.

**Comment by sondreso** [comment]
Review the headings and the logical ordering of the pages to make the menu less messy.

Make the headings shorter and to the point, eg 'Data types' in stead of 'The data types available in ERT''.

The Running ERT page is a good start and should replace the first paragraphs of the 'Keywords page'.

Under ADVANCED the 'Eclipse or not' could -> /dev/null, and 'The Smoother update' might fit together with theory.

**Comment by mortalisk** [comment]
Reading the Welcome page or Running ERT page, it is not clear what a config.ert file is, how I can get one, so I can try launching it as described.
