### ISSUE TITLE
update workflow example in documentation

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#4306]
The workflow example is showing how to calculate misfit using obs_vectors chi2 calculation. This functionality has been removed from obs_vector and the example should be updated.

**Comment by ManInFez** [comment]
This is for our enkf_fs_refactor branch, so it will still be available on main until we merge.

**Comment by oyvindeide** [comment]
I think we will just remove this example all together, as we would like to change this api significantly. We can reintroduce it at a later stage when the api is more mature.
