### ISSUE TITLE
`script/build` doesn't catch changes in qstat script

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4317]
**Describe the bug**
When the qstat script at `src/clib/lib/job_queue/qstat_proxy.sh` gets updated, `script/build` doesn't catch that and copy it to some dir in PATH, leading to qstat related tests suddenly failing locally. One needs to either run a full setup with pip or with the build script (removing _skbuild).

**To reproduce**
Steps to reproduce the behaviour:
1. Make some breaking change in your PATH version of the qstat script
2. run `script/build`
3. run e.g. `python -m pytest tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py`
4. observe that the tests fail

**Expected behaviour**
The tests pass, as your breaking changes are overwritten by the script in `src`

**Comment by valentin-krasontovitsch** [comment]
discussed with Zohar, he confirmed that this could be fixed in the script, gonna make a PR

**Comment by berland** [comment]
This is also an issue with `pip install -e`, it will not make a symlink from the venv back to the source code, so editing the shell-script in your code repo will not update the venv-installation.

**Comment by valentin-krasontovitsch** [comment]
good to know! do you have a suggestion for a work-around / fix for that case?

**Comment by valentin-krasontovitsch** [comment]
after live discussion we think it's either a no-fix as the manual copying is very easy (presuming the developer is aware of the issue), or we manage to get setuptools to create symlinks for scripts when running `pip install -e .` - i will attempt the latter.

anyways this consideration will be out of scope of this PR.

**Comment by pinkwah** [comment]
I reckon the solution will be to port this `qstat_proxy.sh` to Python and install it as a normal `console_command`, like `ert`.

**Comment by valentin-krasontovitsch** [comment]
closed by #4380
