### ISSUE TITLE
Total_progress_bar will exceed 100% if invalid iteration is chosen

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4327]
writing iteration: 7 in ensemble experiment starts out the progress bar at 700% and it goes up to 800%  and finishes at 100% . Because of this, it also aborts at self._total_progress_bar.setValue(progress) if you set iterations to an overflowing value.

**Comment by mortalisk** [comment]
![Screenshot from 2022-11-17 14-38-44](https://user-images.githubusercontent.com/596662/202703387-718305cb-ffbe-4c2f-ac65-d0b30dc46c25.png)
![Screenshot from 2022-11-17 14-42-23](https://user-images.githubusercontent.com/596662/202703394-a006960f-db69-4a65-835f-d4faf9778d06.png)

**Comment by dafeda** [comment]
![progress](https://user-images.githubusercontent.com/45088507/215702616-eee402cb-a77c-491a-b2ee-69ea7f94378d.png)

Total progres seems to in general go to 200% and then drop down to 100% when done.
