### ISSUE TITLE
Go through all keywords in documentation

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#433]
- Compare keywords in documentation and code to make sure that all that are to be used are documented and all that are not to be used are deprecated. Make sure that all that are deprecated are done so both in code and in documentation.

- After the synchronization keyword logic between documentation and code, we should also evaluate if more keywords should be deprecated.

-  I suggest you check the date for config_install_message-line. If it is more than two years ago, remove it without hesitation :wink: If not, we can discuss it case by case...

**Comment by andreabrambilla** [comment]
See also #392

**Comment by xjules** [comment]
Should be cross-checked with all the subconfigs too: https://github.com/equinor/libres/issues/534

**Comment by jondequinor** [comment]
Properly documented keywords that needs additional work:
 - `ANALYSIS_COPY` https://github.com/equinor/libres/issues/696

_Note that this list will be updated._
