### ISSUE TITLE
Support later versions of SLURM (--workdir) not working on SLURM v 21.08.8-2

### ISSUE THREAD

**Issue by gabrielserrao** [equinor/ert#4356]
I am trying to run ERT in the cluster (with SLURM  21.08.8-2) but I am having compatibility problems, for example:  "sbatch: unrecognized option '--workdir=/scratch/smrserraoseabr/Projects/ERT/ert/test-data/poly_example_slurm/poly_out_slurm/realization-36/iter-0'"

**Comment by oysteoh** [comment]
We currently have ERT running towards several SLURM clusters without issues. Could you please attach the parts in your config-file related to how the cluster is configured?

**Comment by oyvindeide** [comment]
Think this was fixed in: https://github.com/equinor/ert/pull/4527, so I will close this issue. But if that is not the case, please report and we will reopen it.
