### ISSUE TITLE
Include a new SLURM QUEUE_OPTION (QUEUE_OPTION SLURM ACCOUNT xxx)

### ISSUE THREAD

**Issue by gabrielserrao** [equinor/ert#4357]
To use the cluster I have to include an account and this key word is not currently available as option to include in the .ert file.

**Comment by pinkwah** [comment]
Thanks for the issue. We are currently working on rewriting the queue system in ERT and we may include this in the new SLURM driver ( #7104 ).

**Comment by DanSava** [comment]
https://github.com/equinor/ert/pull/8175 Will also resolve this and will be supported using the `PROJECT_CODE` general key

**Comment by DanSava** [comment]
Resolved by https://github.com/equinor/ert/pull/8175
