### ISSUE TITLE
Explore necessary actions to move storage interaction to Python

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#436]
Revise the existing code base and make a plan for moving the storage interaction to Python and design an API on top of the storage.

**Comment by ManInFez** [comment]
Points of interaction:
- The "ok" callback function is executing the internalization of data generated by the ensamble. The invocation of the callback is moved to pytthon, which makes the writing of data more accessible
- The analysis module is interacting with the enkf_fs module directly which might be problematic. 
- The plotting is accessing the data through the python layer already.
- Enkf_node is the main "interactor" for enkf_fs

**Comment by ManInFez** [comment]
ert_run_context is updating a refcounter in enkf_fs

**Comment by ManInFez** [comment]
- block_obs_get_observations - referenced but never used
- custom_kw_read_from_buffer - referenced but never used
- data_ranking_init -> enkf_node_user_get -> ... -> enkf_load
- enkf_config_node_has_container -> enkf_node_has_vector / enkf_node_has_node

- enkf_main -> (except update)
   - Holds the enkf_fs main reference
   - enkf_main_alloc_node_ensemble -> enkf_node_load (loads all nodes into memory)
   - enkf_main_inflate_node ->
      - enkf_main_alloc_node_ensemble 
      - enkf_node_store
   - serialize_node -> enkf_node_serialize -> enkf_node_load
   - enkf_main_serialize_dataset
   - deserialize_node

**Comment by ManInFez** [comment]
- enkf_obs_get_obs_and_measure_summary -> enkf_node_load
