### ISSUE TITLE
Improve GUI appearance

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4363]
After a short workshop some low hanging fruits to make using the GUI simpler were identified:

- [x] #4364
- [x] #4365
- [ ] #4366
- [x] #4367
- [x] #4368
- [x] #4369
- [x] #4370
- [ ] #4371
- [ ] #4372
- [ ] #4373
- [ ] #4374
- [ ] #4375
- [ ] #3578

**Comment by sondreso** [comment]
Closing this in favor of https://github.com/equinor/ert/milestone/24
