### ISSUE TITLE
When pressing start simulations - make detailed progress window replace/overlay simulation panel

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4368]
It is only possible to run a mode one at a time, hence the `Simulation Panel` with `Start Simulations` is irrelevant after pressing the `Start Simulations` button. The `Detailed Progress` window however is the interesting part. Have the `Detailed Progress` window replace the `Simulation Panel` after user has started running. Exiting the `Detailed Progress` panel should reveal the `Simulation Panel` again.

Possible conflict of interest: It will no longer be possible to start another run and at the same time keep the `Detailed Progress` window from last run if one wants to check `stdout` etc from it.

The attached image shows a suggestion for this. Note that https://github.com/equinor/ert/issues/4366 might make the `Detailed Progress` window dockable, consider solving that first.

<img width="1333" alt="Screenshot 2022-11-23 at 10 32 02" src="https://user-images.githubusercontent.com/26920711/203513343-8b445e69-d812-4fab-830e-53213cadd62f.png">

**Comment by sondreso** [comment]
Will be fixed by tabs, so closing in favor of https://github.com/equinor/ert/issues/4366
