### ISSUE TITLE
Hide lesser used button in hamburger / dots menu

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4370]
Currently all buttons have similar size indicating equal importance. However some buttons, e.g. `Create Plot` is likely more used than `Manage Cases`. The following buttons are candidates to be grouped in a dots menu:

 - Manage Cases
 - Plugins
 - Run Analysis

**Comment by oyvindeide** [comment]
Do we really want this? There are not that many icons, and I would think that for example `Manage cases` should feature more prominently, not less.
