### ISSUE TITLE
Discover what Time steps refer to in manage cases dialog (in tab initialize from existing) - Remnant from old times?

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4373]
The Manage Cases feature might not be the most used option, but we should make sure that it function as expected. The Timestep could be a reference to how ERT used to work, where it made sense to use Timestep and Report step.

<img width="639" alt="Screenshot 2022-11-23 at 10 41 51" src="https://user-images.githubusercontent.com/26920711/203514804-c0e08efd-e33a-4ec5-80a3-147e430cff2e.png">

**Comment by sondreso** [comment]
Parameters are always stored to timestep 0, so we should remove the functionality to configure this.

**Comment by eivindjahren** [comment]
This is no longer in the GUI so I am closing this issue
