### ISSUE TITLE
Investigate queue systems

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#438]
When moving to cloud we should utilize a new queue system and leave lsf behind. We should investigate the possibilities available for this. Slurm could be an alternative.

**Comment by jondequinor** [comment]
going with prefect for now as a "queue system"

**Comment by sondreso** [comment]
I guess the issue was more discussing HPC systems, but as Jonas says, going with prefect/dask we get support for the most popular clusters out of the box.
