### ISSUE TITLE
Build Qt5 in Komodo

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#439]

**Comment by jondequinor** [comment]
Seems to be solved in aea12b160f3224f91761ff8297e0b2c0d4679ba0 in the private komodo repo?

**Comment by andreabrambilla** [comment]
I forgot about that, I thought it was never merged. In any case, I would not blindly rely on that script. 
Qt5 has not been built as part of a regular release in a long time, so we don't really know if that script still works

Bonus: it may be worth bumping qt version while we are at it

**Comment by jondequinor** [comment]
Following https://wiki.qt.io/Building_Qt_5_from_Git …

**Comment by jondequinor** [comment]
PR: https://github.com/equinor/komodo-releases/pull/3

**Comment by markusdregi** [comment]
This should be charged to natstat.
