### ISSUE TITLE
Progressbar in Detailed Progress does not update after pressing kill simulations

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4396]
**Describe the bug**
Progressbar in Detailed Progress does not update after pressing kill simulations

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert` (versions given below)
2. Use forward model running long enough to kill simulation manually
3. `ert gui my_config.ert`
4. Run experiment (IES/Smoother/ESMDA/Test)
5. Press "Kill Simulations"

**Expected behaviour**
Expects the progress to show that all realizations have failed.

**Screenshots**
Working - ert version 2.27.0:

![2021-01-06](https://user-images.githubusercontent.com/26920711/204488604-feb2b22e-9b9a-41aa-9ff0-bff7dffee7fd.png)

Failing - ert version: 2.28.1 (and also main)

![2021-10-04](https://user-images.githubusercontent.com/26920711/204489421-01663410-0618-4a5f-ab50-d025e7663f4b.png)

**Environment**
 - ERT/Komodo release:
Failed in: 2021.10.04-py36 (ert version: 2.28.1)
Worked in: 2021.09.01-py36) (ert version: 2.27.0)

**Comment by kwinkunks** [comment]
FWIW, I found the same in v4.0.3 on Komodo 2022.10.04-py38, except everything gets stuck in 'pending'. 

![image](https://user-images.githubusercontent.com/1692372/205017268-d1e6fb68-b7dc-4a6f-be2d-d02adc414dea.png)

**Comment by pinkwah** [comment]
I notice that there is a difference in behaviour between JobQueue and Scheduler as well. Scheduler marks all reals as failed, while JobQueue says they are still running.

**Comment by xjules** [comment]
Closing this issue as it has been fixed since.
