### ISSUE TITLE
Remove deprecated SCHEDULE_PREDICTION_FILE - not before May 2023

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4397]
Cf. #4288 - the keyword was deprecated, and should be removed no earlier than three months later.

**Comment by valentin-krasontovitsch** [comment]
blocked until February 1st, 2023

**Comment by oysteoh** [comment]
Is this one added to the suggestor @valentin-krasontovitsch ?

**Comment by valentin-krasontovitsch** [comment]
good question - i didn't add it, as i think this issue was created before the suggester. but i'll look into it! thanks for pointing it out!

**Comment by valentin-krasontovitsch** [comment]
actually it was already added, just didn't see it / spot it : )

what do you think about the schedule for removing the keyword? should i update the subject of this issue? or can we go ahead with removal in february?

**Comment by oysteoh** [comment]
Have a look at the logs and check if it has been used .. I would say if it is not we'll go ahead and remove it?

**Comment by valentin-krasontovitsch** [comment]
no usage in (3 month window) log snapshot from today - but didn't we want to wait for a while (3 months) after announcing through the suggester? of course i don't mind removing now...

**Comment by oysteoh** [comment]
when was the deprecation-warning released? if in the december-release i suggest yes that we wait a bit like you said 👍

**Comment by valentin-krasontovitsch** [comment]
yeah i think it was in dan's release - ok, then we wait : )
