### ISSUE TITLE
Align DEFINE and DATA_KW behavior 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4400]
- [ ] Communicate to the rest of the team / ert-users on slack/yammer our intentions

Previously, DEFINES only resultet in limited support of mixing "define before use" and "use before define":

The following follows the "define before use" order (`<USER>` is defined before it is used in the definition of `<HOME>`)
```
DEFINE <USER> eja
DEFINE <HOME> /home/<USER>
```
"use before define" is simply the opposite order:
```
DEFINE <HOME> /home/<USER>
DEFINE <USER> eja
```
Mixing these two orders has limited support (you can mix up to three times for a chain of define dependencies).
Also, there is no hard requirement that a key starts `<` and ends with `>` (something we have seen in the wild). This means that substitution can lead to computationally complex behavior.

**Comment by eivindjahren** [comment]
There is some difference between `DEFINE` and `DATA_KW` though, but perhaps we should wait a bit for that.

I think a simple thing to support is the "define before use":
```
SUB <USER> eivind
SUB <HOME> /home/<USER>
SUB <PROJECT_PATH> project/
RUNPATH <HOME>/<PROJECT_PATH>/runpath/
```

This should mean RUNPATH is given `/home/eivind/project/runpath`. A simple approach we can take for now is to say that

```
SUB <HOME> /home/<USER>
SUB <USER> eivind
SUB <PROJECT_PATH> project/
RUNPATH /home/<USER>/<PROJECT_PATH>/runpath/
```
results in undefined behavior. Actually *forcing* this to fail or warn of potential problems will remain out of scope for a while.

Currently this scenario works for `DEFINE` (once we remove the obvious problem of putting the DEFINES into a dict). However, for `DATA_KW` that means reversing the list.
