### ISSUE TITLE
test_many_concurrent_qstat_invocations is flaky

### ISSUE THREAD

**Issue by berland** [equinor/ert#4409]
**Describe the bug**
A test is flaky, at least when run together with `pytest-xdist`

`tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py::test_many_concurrent_qstat_invocations[834-1000]
`

**To reproduce**
Steps to reproduce the behaviour:

`pytest -x -n 24 tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py  --count 1000`

Gave after a few minutes (on a beefy ubuntu 22.04 workstation):
    
 ```
               else:
                    assert state == CacheState.CACHE_EXISTS
>                   assert (
                        process.returncode == 0
                    ), "Check for race condition if AssertionError"
E                   AssertionError: Check for race condition if AssertionError
E                   assert 1 == 0
E                    +  where 1 = <Popen: returncode: 1 args: [PosixPath('/home/berland/projects/ert/src/ert/_...>.returncode

/home/berland/projects/ert/tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py:311: AssertionError
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
011111111111111111111111111111111111111110

```

**Expected behaviour**
No error

**Screenshots**

**Environment**
 - OS: Ubuntu 22.04
 - ERT/Komodo release: main
 - Python version: 3.10
 - Remote/HPC execution involved: no

**Additional context**

**Comment by lars-petter-hauge** [comment]
Observed in https://github.com/equinor/ert/pull/4405

**Comment by berland** [comment]
A possible explanation is that the order of execution of spawned subprocesses gets mixed when the test machine is heavily loaded, which we accomplish with `pytest-xdist`. 

The line
https://github.com/equinor/ert/blob/ef198daf316987e28e136dbc4eaad83ac86127e4/tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py#L262
controls the probability of mixed order of execution, and bumping this number will probably mitigate the issue (but not prevent it entirely).

Testing on local iron, a sleeptime of 0.01 will always test within 1000 repetitions of the test, while a sleeptime of 0.02 is not able to reproduce the error. The cumulative sleep in the test function is `sleeptime * 400`, so this bump adds 4 seconds the the total test time, which should not matter when running tests in parallel (other tests will benefit from the sleeptime, so the total test-time might not increase).
