### ISSUE TITLE
STATUS file is appended to before it exists

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#4415]
**Describe the bug**
The status file in runpath is appended to before it exists
```
src/_ert_job_runner/reporting/file.py", line 121, in _write_status_file
    with append(file=STATUS_file) as status_file
FileNotFoundError: [Errno 2] No such file or directory: 'STATUS'
```

**To reproduce**
Can be tricky to reproduce at it is a race condition. Has been happening when running tests recently

**Environment**
Happens on OSX and RHEL9

**Comment by jonathan-eq** [comment]
I will try this one!

**Comment by jonathan-eq** [comment]
Could not reproduce.
