### ISSUE TITLE
Substitute deprecated frame.append with pandas.concat instead

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#4420]
**Describe the bug**
Some deprecations warnings were observed in Github Actions. One of them is:

FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead. 
    data = data.append(gen_data)

**Expected behaviour**
Replace and don't have this future warning.

**Comment by oyvindeide** [comment]
I cant find any instances of this anymore, the example provided has been removed. If there are any instances left, feel free to reopen this issue.
