### ISSUE TITLE
Semeio tests/test_ert_integration.py::test_forward_model_error_propagation are failing

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#4427]
**Describe the bug**

#4421  and #4419  very simple ert PRs have semeio tests failing on the following:

tests/test_ert_integration.py::test_forward_model_error_propagation[OTS-<CONFIG>=config.ots-config.ots is not an existing file!] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/OTS.stderr.0'

tests/test_ert_integration.py::test_forward_model_error_propagation[DESIGN2PARAMS-<IENS>=not_int-invalid int value: 'not_int'] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/DESIGN2PARAMS.stderr.0'

tests/test_ert_integration.py::test_forward_model_error_propagation[DESIGN_KW-<template_file>=no_template- no_template is not an existing file!] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/DESIGN_KW.stderr.0'

tests/test_ert_integration.py::test_forward_model_error_propagation[GENDATA_RFT-<ECL_BASE>=not_ecl-The path not_ecl.RFT does not exist] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/GENDATA_RFT.stderr.0'

tests/test_ert_integration.py::test_forward_model_error_propagation[PYSCAL-<PARAMETER_FILE>=not_file-not_file does not exist] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/PYSCAL.stderr.0'

tests/test_ert_integration.py::test_forward_model_error_propagation[STEA-<CONFIG>=not_a_file-not_a_file is not an existing file!] - FileNotFoundError: [Errno 2] No such file or directory: 'simulations/realization-0/iter-0/STEA.stderr.0'

**Comment by sondreso** [comment]
Will close this as there have been no further reports since December. Feel free to reopen if this is not the case!
