### ISSUE TITLE
Make runpath file format consistent

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#4443]
There are multiple instances in the code where the runpath file format is replacing 
`realization-%d/iter-%d` with `realization-real_number/iter-iter_number` by using the following pattern:
```
                if run_path.count("%d") == 2:
                    s = run_path % (j, i)
                else:
                    s = run_path % (j)
```
we should try to avoid this by making sure that runpath file format throughout the codebase is of the form `realization-<IENS>/iter-<ITER>`

Related to #4432

**Comment by mortalisk** [comment]
Isn't this pattern necessary for when the user configures the run-path to only have one %d ?

**Comment by DanSava** [comment]
Is there a problem with `realization-<IENS>`?
