### ISSUE TITLE
Error reading summary-key-set

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#4460]
From yammer: https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjAzNjA5MTU0NTI1NTkzNiJ9

ERT is crashing during startup because the` <case>/files/summary-key-set` has size zero.  
The user is running in Stavanger

**Comment by frode-aarstad** [comment]
[ert-log-2022-12-07T1033.txt](https://github.com/equinor/ert/files/10183805/ert-log-2022-12-07T1033.txt)

**Comment by frode-aarstad** [comment]
Query for checking this error
```
let Aborts = AppExceptions
 | where ExceptionType  == "UtilAbort";
Aborts
 | where OuterMessage  contains "util_fread_int"
```

**Comment by oyvindeide** [comment]
No results found in the new year, so I will close this issue, feel free to reopen if it is seen again. Seems likely it was an infrastructure issue.
