### ISSUE TITLE
Silence warning of subdirectories inside `INSTALL_JOB_DIRECTORY`

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4487]
when (some?) hypothesis tests fail, we see

```
WARNING  ert._c_wrappers.enkf.res_config:res_config.py:508 Unable to locate job file /home/val/code/equinor/ert/src/ert/shared/share/ert/forward-models/res/script
WARNING  ert._c_wrappers.enkf.res_config:res_config.py:508 Unable to locate job file /home/val/code/equinor/ert/src/ert/shared/share/ert/forward-models/templating/script
```

apparently the files are there but it's a directory of files!! we should investigate, as this might be a serious bug

**Comment by eivindjahren** [comment]
The problem comes from `ResConfig._create_job()` complains that it found something which was not a file (in this case a directory) inside of the directory pointed to by `INSTALL_JOB_DIRECTORY` . We should maybe just silently ignore subdirectories in `INSTALL_JOB_DIRECTORY`.
