### ISSUE TITLE
Analysis module when running ies is not available

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#451]
When iterable is choosen when retrieving list of available analysis modules - no one is retrieved which is causing a exception further down the line. Not sure why it works in python2, but we should make sure it's also works as intended in py2 and not just works by chance.

**Comment by markusdregi** [comment]
This should be tested with the Equinor installed site-config (the right one, not the other one that is installed).

**Comment by markusdregi** [comment]
Will most likely be resolved by: https://github.com/equinor/ert/issues/469
