### ISSUE TITLE
enkf_fs_refactor: Coalesce responses into one object

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#4510]
Each realisation's response produces a single vector that together produce a single ensemble response. When updating, exporting or visualising the data, we most often want to obtain a full matrix/object rather than load each realisation separately. As such, there should be a `finalize` function in `Storage` that combines the responses together in a single file and marks the ensemble run as complete.

NB: I use the word 'object' to mean something more generic than a matrix since response vectors may have different lengths across realisations.

**Comment by oyvindeide** [comment]
Think I will close this as we will start off with them as separate files, and then we can look into coalescing down the line.
