### ISSUE TITLE
Provide a QC-tool to check the group controls defined in the REFCASE and compare them with the template CASE

### ISSUE THREAD

**Issue by KetilN** [equinor/ert#4540]
**Is your feature request related to a problem? Please describe.**
User Story: As a FMU engineer in an asset, I would like to add an extra “well group-control” to an existing FMU-project.  
Major frustration user event: First after updating the FMU-project and running my ensemble after several days, I get an error message from ERT ala "Unknown well group-control”.

**Describe the solution you'd like**
There should be a QC-tool in ERT to use before starting an ensemble, to check the group controls defined in the REFCASE and compare them with the BASECASE.

**Describe alternatives you've considered**
An automatic update of the REFCASE based on the BASECASE would of course be better, but this can be problematic when doing AHM since the REFCASE needs to be rerun before the ensemble can be started.
Another alternative is to redesign ERT so that REFCASE is not needed when doing AHM, but this is a must bigger effort than just providing a QC-tool.

**Additional context**
The error message in this case is very difficult to understand, only something like: "ERROR: Unknown well group-control”.

**Comment by KetilN** [comment]
The concept "template CASE" will replace the word BASECASE.

**Comment by KetilN** [comment]
Note that this Feature Request is not relevant anylonger given a 100 % fullfillment of this newer Feature Request: 
Automate generation of REFCASE to be used in Assisted History Matching in ERT #4556

**Comment by oyvindeide** [comment]
Based in the discussion in the issue, and the fact that REFCASE is now optional, I will close this issue. Feel free to reopen if you feel it is still relevant.
