### ISSUE TITLE
Pressing "create plot" button hangs

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4542]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Add a failing forward model job to `test-data/poly_example/poly.ert` (e.g. `FORWARD_MODEL ECLIPSE100(<VERSION>=2017.1)` without having eclipse installed)
2. `ert gui test-data/poly_example/poly.ert`
3. Do a test run
4. Once the job has failed press "create plots"

This hangs

**Expected behaviour**
create plots is disabled when plots cannot be created or gives a reasonable error message.

**Comment by lars-petter-hauge** [comment]
Adding that an error message saying "Server not started" is shown, and the following exception is thrown:

```
Traceback (most recent call last):
  File "/Users/LPHA/GitProjects/ert/src/ert/gui/tools/plot/plot_tool.py", line 13, in trigger
    plot_window = PlotWindow(self._config_file, self.parent())
  File "/Users/LPHA/GitProjects/ert/src/ert/gui/tools/plot/plot_window.py", line 90, in __init__
    cases = self._api.get_all_cases_not_running()
AttributeError: 'PlotWindow' object has no attribute '_api'
[1]    3209 abort      ert gui poly.ert
```

**Comment by andreas-el** [comment]
This issue was introduced in commit `be1d708` when the suggester altered the startup of storage and gui window.
