### ISSUE TITLE
Automate generation of REFCASE to be used in Assisted History Matching in ERT

### ISSUE THREAD

**Issue by KetilN** [equinor/ert#4556]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when ERT end-users have done changes on their template CASE without updated their REFCASE like changing/adding dates in the SCHEDULE file, they do not get any warning before after the simulation run is completed.

**Describe the solution you'd like**
Use the method described here to automatic generate the REFCASE to be used in Assisted History Matching in ERT:
(https://wiki.equinor.com/wiki/index.php/ResScript:Python:Scripts:emulate_refcase_simulation.py)

And see this script as a method for how this method is being used specifically for Gullfaks:

/project/gullfaks/resmod/gfmain_brent/2015a/r004/ert/input/refcase/create_refcase.sh

**Describe alternatives you've considered**
I have considered that a QC-tool is made in Issue #3906:
Provide a QC-tool for manual comparision of DATES in template CASE SCHEDULE, REFCASE SCHEDULE and OBSFILE 
and I have considered that a QC-tool is made in Issue #4540:
Provide a QC-tool to check the group controls defined in the REFCASE and compare them with the template CASE 

But a much better solution is to have an automated generation of REFCASE.
Since ERT normally only supports static DATES-setup in the Eclipse SCHEDULE file,
it should be possible to have an automated generation of REFCASE.

**Additional context**

**Comment by rnyb** [comment]
Access to the `/project/gullfaks/resmod/gfmain_brent/2015a/r004/ert/input/refcase/create_refcase.sh` file is limited so adding the content below:

```
#!/usr/bin/env bash
#
# Script creates summary file based on sch file --> needed for ert REFCASE keyword
# Only need to be run when sch file is updated/changed (manual process)
#
# To run: >sh create_refcase.sh
#
#  Wiki documentation:
#  https://wiki.statoil.no/wiki/index.php/ResScript:Python:Scripts:emulate_refcase_simulation.py
###################################################################################

REF_CASE="GULLFAKS_REF"
DATA_FILE="../../../eclipse/model/GULLFAKS.DATA"
SCH_FILE="../../../eclipse/include/schedule/gullfaks_hist.sch"

START_DATE="1985-10-01"

NX=99  # NX=$1 # number of grid cells in X direction
NY=120 # NY=$2 # number of grid cells in Y direction
NZ=47  # NZ=$3 # number of grid cells in Z direction

VECTORS="WBP9" # additional well wectors to include in UNSMRY-file

####################################################################################

CWD=`basename $PWD`

if [ "$CWD" != "refcase" ]
then
 echo "ERROR: You are not located in a directory with the name 'refcase', i.e. I assume you are not in the reference case directory... I don't dare to do rm -f $REF_CASE*. Quitting." >&2
 exit 1
fi

echo "Removing old reference case files (rm -f $REF_CASE*)"
rm -f $REF_CASE*

echo "Removing ECL.CFG (rm -f ECL.CFG)"
rm -f ECL.CFG

cp $DATA_FILE $REF_CASE.DATA

echo "Changing Eclipse to NOSIM mode (nosim $REF_CASE.DATA)"
/project/res/resscript/nosim $REF_CASE.DATA > /dev/null

echo "Running eclipse (runeclipse -i $REF_CASE.DATA > $REF_CASE.LOG)"
runeclipse -v 2015.2 -i $REF_CASE.DATA > $REF_CASE.LOG

echo "Creating $REF_CASE.SMSPEC and $REF_CASE.UNSMRY"
#../../ert/bin/emulate_refcase_simulation.py -f $REF_CASE $SCH_FILE $START_DATE $NX $NY $NZ -w $VECTORS > /dev/null
emulate_refcase_simulation.py -f $REF_CASE $SCH_FILE $START_DATE $NX $NY $NZ > /dev/null

#delete files not needed
rm -f *.DBG
rm -f *.ECLEND
rm -f *.ERR
rm -f *.LOG
rm -f *.PRT
rm -f *.job*
rm -f *.CFG

echo "Reference case created" 
```

**Comment by oyvindeide** [comment]
We have a solution for this in the pipeline which involves not using the refcase when reading responses, but allowing each realization to have an independent time map, with the only requirement that there are responses where there are observations. Will close this as solved as it is soon available for testing.
