### ISSUE TITLE
Fixed point substitution fails for the forward model keyword

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4566]
Testing of the current release candidate revealed that the following now fails with hitting the substitution limit:
```
DEFINE <RMS_VERSION> 1.2.3
FORWARD_MODEL RMS(<RMS_VERSION>=<RMS_VERSION>)
```

The issue is that the expected behavior of the `FORWARD_MODEL` keyword is like that of an argument list, but in reality the above situation is equivalent to 

```
DEFINE <RMS_VERSION> 1.2.3
FORWARD_MODEL RMS(1.2.3=1.2.3)
```

this has coincidentally worked before the introduction of fixed point substitution as when the forward model was to determine the value of its parameter `<RMS_VERSION>` the following substitutions were available:
```
DEFINE <RMS_VERSION> 1.2.3
DEFINE 1.2.3 1.2.3
```
However, with fixed point substitutions this results in a loop.

One way to solve this, is to turn off substitutions on the line containing the `FORWARD_MODEL` keyword so that the left hand side in the assignments are not substituted, which seems to be what the user expects. This would result in the following substitutions being available for the parameters:
```
DEFINE <RMS_VERSION> 1.2.3
DEFINE <RMS_VERSION> <RMS_VERSION>
```
which does terminate in our fixed point substitution (it would not work in a substitution scheme that does not ensure liveness, but that would create other problems as well).

**Comment by valentin-krasontovitsch** [comment]
question: what's liveness?

**Comment by eivindjahren** [comment]
https://en.wikipedia.org/wiki/Safety_and_liveness_properties
