### ISSUE TITLE
Rerun with additional forward models without having parameters.txt overwritten

### ISSUE THREAD

**Issue by rnyb** [equinor/ert#4571]
**Is your feature request related to a problem? Please describe.**
As a user I often need to add new forward models without having to rerun everything. This is mainly done to save time (a HM run can take hours - days to fully rerun), but can also be relevant for older cases that is hard to rerun fully. However, when doing this the `parameters.txt` file (and STATUS file) is overwritten. This is an unwanted situation and the user needs to make creative solutions to avoid it.

**Describe the solution you'd like**
There should be an option for the user to easily rerun parts of workflow without having the `parameters.txt` file overwritten.

**Comment by rnyb** [comment]
One suggestion could be to never write parameters.txt if neither GEN_KW nor DESIGN2PARAMS is present in the ERT model file.

**Comment by oyvindeide** [comment]
Hi, sorry for being slow to respond. Today the `parameters.txt` will be backed up if they already exists, but I guess that is not the feature you are asking for?

**Comment by rnyb** [comment]
> Hi, sorry for being slow to respond. Today the `parameters.txt` will be backed up if it already exists, but I guess that is not the feature you are asking for?

Correct. The backup file is great on it's own, but that is not what is requested here. The idea is to be able to avoid user specific copy hacks to get back original state.

**Comment by oyvindeide** [comment]
> One suggestion could be to never write parameters.txt if neither GEN_KW nor DESIGN2PARAMS is present in the ERT model file.

We could probably not write it when there are no `GEN_KW` in the model, but ert as such does not really know that `DESIGN2PARAMS` exists, so would be hard to account for that. That highlights the main problem, we dont know if there are other forward models that rely on this file existing, which means removing it will probably cause a lot of problems.
