### ISSUE TITLE
Refactor StateMap

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#4575]
Should this happen here? Maybe it should happen one level higher in the callstack? Or ideally we should add a single enum per parameter, but that sounds like it is outside the scope of this PR, and should be an issue instead.

_Originally posted by @oyvindeide in https://github.com/equinor/ert/pull/4486#discussion_r1062342416_

**Comment by oyvindeide** [comment]
This is a lot of this happening throughout the code base:

```python
        for realization_nr in active_realizations:
            storage.update_realization_state(
                realization_nr,
                [
                    RealizationStateEnum.STATE_UNDEFINED,
                    RealizationStateEnum.STATE_LOAD_FAILURE,
                ],
                RealizationStateEnum.STATE_INITIALIZED,
            )
```
where we need to update the state, this should be more confined.

**Comment by oyvindeide** [comment]
Closing as wontfix
