### ISSUE TITLE
Look at load time of ERT GUI after introduction of suggestor

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4590]
There is an impression that the load time of ERT GUI is taking longer than usual in bleeding. It should be investigated if the load-time actually has increased and then i.e if the introduction of the suggester is causing this.

**Comment by andreas-el** [comment]
build | with fix | with suggester | before suggester
-- | -- | -- | --
git hash | de00ce7 | 1033798 | 855614e
  | 14.5 | 26.5 | 21.5
  | 11.5 | 25 | 12.5
  | 11.5 | 22 | 16
  | 16 | 25 | 12
  | 12 | 23 | 16
  |   |   |  
avg | 13.1 | 24.3 | 15.6

The UI is seems to be more responsive (quicker to load) than before. At least the experienced delays are gone and more comparable as it was before.

**Comment by eivindjahren** [comment]
I guess we close this as Done-Done as it has been investigated and we have a fix which is lined up for release.
