### ISSUE TITLE
improve error message shown for failed parsing of forward model job

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4599]
Related to #4566

We would like to provide users with better feedback, and give as much context for an error during parsing of a forward model as possible. at the moment, for a substitution failure / warning, only the causing token and the resulting substituted token are supplied. 

We would like to supply the whole line. 

Not in the scope of this issue is supplying the line number in the responsible config file, or the config file name (although the latter should at least be investigated).

**Comment by mortalisk** [comment]
As per https://wiki.equinor.com/wiki/index.php/Debugging the error message given for FORWARD_MODEL "parameter list", (ie. FORWARD_MOEL ECLIPSE300(<PARAMETER>=list) is confusing enough to be difficult to debug. It should contain location information and show exactly what is wrong.

**Comment by oysteoh** [comment]
There is more to be done here , @eivindjahren  please fill in

**Comment by eivindjahren** [comment]
I think while doing this we should partially resolve #2766

**Comment by valentin-krasontovitsch** [comment]
hmm i can try to pick up 2766 after finishing the current work on 4694, and see which parts / which behaviour is controlled / lives outside of the parser? and if it resides in the parser, i should talk to you-know-who, who's currently working on you-know-what?

**Comment by eivindjahren** [comment]
We could probably get some of the pain points out of the way regardless and finalize the parser later.

**Comment by valentin-krasontovitsch** [comment]
sounds good.

**Comment by valentin-krasontovitsch** [comment]
the only point left in the check box list is

> Incorrect format in the parameter list does not give location information so its hard to know what failed.

I'm not sure if there are any left-over cases where we could add more context? do you recall, @eivindjahren? or have we done as much as we can, for now?

**Comment by oysteoh** [comment]
Poke @eivindjahren 👆

**Comment by eivindjahren** [comment]
I think the epic is blocked until we replace the parser.

**Comment by oysteoh** [comment]
This issue will be closed when the new parser replacing the old parsing and is used by default
