### ISSUE TITLE
Raise error if GEN_OBS is longer then the corresponding GEN_DATA

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4636]
Currently there is a test on main that fails on the enkf_fs_refactor branch, because main raises an exception if the observation vector is larger than the corresponding response. On enkf_fs_refactor this is just filtered out silently. We should raise an exception if we drop observations. In the future we may allow users to drop these observations if they actively chose.

**Comment by ManInFez** [comment]
This is resolved in the rebase branch https://github.com/equinor/ert/pull/4627

**Comment by oyvindeide** [comment]
Fixed after rebase
