### ISSUE TITLE
Issues related to summary plotting of several cases

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#464]
A couple of issues realted to plotting showed up during the HM course. They arrise when opening several cases with different assumptions. Issue can be reproduced with HM_tutorial setup:
 wget http://sdp.statoil.no/wikidocs/FMU/public/reek_hm_20190528.tar.gz,
I can also demonstrate

- ERT seg. faults when attempting to plot a vector where one case has observations and the other does not have values for the historical period (eg it is run from restart)

- When plotting cases with and without values for historical period: ERT is unable to plot historical vector if the first case that was loaded was a prediction dataset without history. However, if the first case has history it will plot nicely.

**Comment by markusdregi** [comment]
Do you know if this used to work?

**Comment by eivindsm** [comment]
No, not sure

**Comment by markusdregi** [comment]
Alright, thanks for the report :+1: Let us discuss this further on Friday.

**Comment by markusdregi** [comment]
This should be reproduced with new testing version before we proceed.

**Comment by mortalisk** [comment]
Can't reproduce
