### ISSUE TITLE
Make Runpath in GUI copyable

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#4641]
**Is your feature request related to a problem? Please describe.**
I have observed users manually typing the runpath displayed in the GUI to send it to colleagues.

**Describe the solution you'd like**
Be able to copy the runpath. 
Perhaps add a copy symbol.

**Additional context**
![copyable_runpath](https://user-images.githubusercontent.com/45088507/212348799-75a2299f-0eef-413b-83c1-3f96e5790faa.png)

**Comment by DanSava** [comment]
Suggestion:

Look into `lbl.setTextInteractionFlags(Qt.TextSelectableByMouse)` this will allow the label text to be selectable using the mouse and then `Ctrl+C` and `Ctrl+V` will work.
