### ISSUE TITLE
Validate runpath on start

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#4642]
**Is your feature request related to a problem? Please describe.**
GUI can be started with an invalid runpath which will cause a crash at a later stage.

**Describe the solution you'd like**
Make sure runpath is valid before starting GUI.

**Additional context**
![validate_runpath](https://user-images.githubusercontent.com/45088507/212349100-0c8d717d-85c6-43e0-a12c-9160958fa800.png)

**Comment by oyvindeide** [comment]
This sounds like it should be easy, but very system dependent, for example the example you have provided is valid on RHEL7:

```bash
[my_user@my_computer foo]$ mkdir }
[my_user@my_computer foo]$ mkdir {
[my_user@my_computer foo]$ ll
total 0
drwxrwxr-x 2 my_user my_user 6 Jan 27 14:47 {
drwxrwxr-x 2 my_user my_user 6 Jan 27 14:47 }
[my_user@my_computer foo]$ cd {
[my_user@my_computer {]$ pwd
/path/to/something/foo/{
```

**Comment by dafeda** [comment]
Closing due to system dependence.
