### ISSUE TITLE
Dialog for existing runpath has confusing prompts

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4643]
While doing weird stuff I triggered this error dialog:

<img width="694" alt="Screenshot 2023-01-15 at 22 41 23" src="https://user-images.githubusercontent.com/596662/212568825-6c641016-76ba-4e67-898b-4ad64e618a13.png">

It is not obvious which button does what.

To reproduce:
1. run ert gui poly.ert
2. run an experiment
3. do step 1-2 again
4. observe dialog

Expected:
A question that the yes/no buttons would answer, or some other reasonable connection between dialog text and buttons.

**Comment by oyvindeide** [comment]
so add something like, `are you sure you want to continue?` after: `ERT is running in an existing runpath`?

**Comment by Jehan-h20220012** [comment]
I would like to work on this issue as it would also help me in my acedemics and I will successfully raise PR to get merged which will solve this issue.

**Comment by mortalisk** [comment]
@oyvindeide yes, that would make sense.
@Jehan-h20220012 I guess you can just make a PR, and we'll review it.

**Comment by Jehan-h20220012** [comment]
Sure @oyvindeide Thank You

**Comment by Jehan-h20220012** [comment]
@mortalisk  @sondreso @oyvindeide Please look into my PR and approve it for merge!

**Comment by Jehan-h20220012** [comment]
@mortalisk @sondreso @oyvindeide Please review my PR!

**Comment by oyvindeide** [comment]
Hi @Jehan-h20220012, sorry for being absent, I have started the tests on your PR, and everything should be good to go soon :smile:

**Comment by oyvindeide** [comment]
Hi again, most of the tests failed on your PR, not related to your changes, but there was a change in an external dependency. This has been fixed on `main`. Can you rebase on main?

**Comment by Jehan-h20220012** [comment]
> Hi @Jehan-h20220012, sorry for being absent, I have started the tests on your PR, and everything should be good to go soon 😄

Its okay, no problem! @oyvindeide

**Comment by Jehan-h20220012** [comment]
> Hi again, most of the tests failed on your PR, not related to your changes, but there was a change in an external dependency. This has been fixed on `main`. Can you rebase on main?

Yes, got it👍. Will do it soon and update the PR again.
