### ISSUE TITLE
For some cases of job failures, ert does not give good error messages

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4651]
For the following failure modes, the lsf queue could be polled to give the user some indication of what has gone wrong, but we do not do that currently.    

* MAX_RUNTIME (which is set in your ERT config file) is exceeded
* scratch disc is full
* disk system or the cluster hardware is in trouble
* Out of memory on the compute node

**Comment by mortalisk** [comment]
Related to #2831

**Comment by oysteoh** [comment]
This issue is not actionable and thus closing.
