### ISSUE TITLE
When general observations have mismatching sizes, you don't get a good error message.

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4652]
https://wiki.equinor.com/wiki/index.php/Debugging contains a indication that users are having hard time debugging mismatches in column length in general observations under "Error: General observations fail".

**Comment by oyvindeide** [comment]
Also related, though does not solve completely: https://github.com/equinor/ert/commit/4ccc634bf4be52cd0c938a7e704b8577ecc6232d

**Comment by oysteoh** [comment]
@oyvindeide do you have more insight into this? How to reproduce etc?

**Comment by oyvindeide** [comment]
This it should be possible to reproduce by for example using the poly case with shorter response.

**Comment by DanSava** [comment]
Trying to reproduce the issue by limiting the number of realizations to a number smaller than the observations we get the following error:
![Screenshot from 2023-03-31 12-18-30](https://user-images.githubusercontent.com/4508053/229089346-7e5b4567-01b5-4eae-a5c9-e924f4e2ce15.png)

I assume this is the not `good` error message the user sees. What would be a better error message in this case?

**Comment by DanSava** [comment]
I updated the debugging wiki with the image above and added a solution recommendation
