### ISSUE TITLE
Error message Internal error when lookup up index: -1 when loading summary data

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4653]
When ERT loads (internalizing) summary data, through `TimeMap::indicies` the user may get the unhelpful error message `Internal error when lookup up index: -1`. Might be related to restarts. In other cases it has been seen to be sensitive to BASIC=3 (works fine) vs BASIC=6 (triggers crash) in RPTRST in the Eclipse DATA-file, which causes a small difference in the summary files emitted by Eclipse.

**Comment by oysteoh** [comment]
Sloths have worked on this lately , we should check with them. The error message here should be updated to make more sense

**Comment by oyvindeide** [comment]
We have not seen this error, and it is not clear how to reproduce, so will close this issue.
