### ISSUE TITLE
Create a design matrix importer

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4656]
As can be seen under "Error: ERT fails due to wrong number of parameters in design matrix" in https://wiki.equinor.com/wiki/index.php/Debugging . The github.com/equinor/semeio forward model job `DESIGN2PARAM` leaves a lot to be desired, it should be replaced with an ert feature that imports the design matrix.

**Comment by sondreso** [comment]
This will be solved as part of: https://github.com/equinor/ert/issues/8457
