### ISSUE TITLE
The error message "subst_list_add_from_string: missing '=' in argument:" should contain location info.

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4657]
As per https://wiki.equinor.com/wiki/index.php/Debugging the error message given for `FORWARD_MODEL` "parameter list", (ie. `FORWARD_MOEL ECLIPSE300(<PARAMETER>=list)` is confusing enough to be difficult to debug. It should contain location information and show exactly what is wrong.

**Comment by mortalisk** [comment]
Closed as duplicate of #4581

**Comment by DanSava** [comment]
> Closed as duplicate of #4581

@mortalisk Should this be closed?

**Comment by mortalisk** [comment]
I think not. I must have had a bad day. The linked issue regards improving substitution failure messages, while this is a config parsing error.
