### ISSUE TITLE
Reintroduce support for active information for GEN_DATA

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4665]
At one point in the refactor this functionality was removed:
```cpp
        char *active_file = util_alloc_sprintf("%s_active", filename);
        if (fs::exists(active_file)) {
            file_exists = true;
            FILE *stream = util_fopen(active_file, "r");
            int active_int;
            for (int index = 0; index < size; index++) {
                if (fscanf(stream, "%d", &active_int) == 1) {
                    if (active_int == 1)
                        bool_vector_iset(gen_data->active_mask, index, true);
                    else if (active_int == 0)
                        bool_vector_iset(gen_data->active_mask, index, false);
                    else
                        util_abort("%s: error when loading active mask "
                                   "from:%s only 0 and 1 allowed \n",
                                   __func__, active_file);
                } else
                    util_abort("%s: error when loading active mask from:%s "
                               "- file not long enough.\n",
                               __func__, active_file);
            }
            fclose(stream);
            logger->info("GEN_DATA({}): active information loaded from:{}.",
                         gen_data_get_key(gen_data), active_file);
        } else
            logger->info("GEN_DATA({}): active information not provided.",
                         gen_data_get_key(gen_data));
```
we should reintroduce it, it is currently in use in the `GENDATA_RFT` job: https://github.com/equinor/semeio/blob/main/semeio/jobs/rft/gendata_rft.py#L17-L21, https://github.com/equinor/semeio/blob/7c48099562f4c250d4b82cc6eca4074b97c31591/semeio/jobs/rft/gendata_rft.py#L52

**Comment by oyvindeide** [comment]
Blocked by: #4290

**Comment by dafeda** [comment]
This used to be in the file `gen_data.cpp` that was removed in this commit:

https://github.com/equinor/ert/commit/72083e3ae310cac9b6f3b302706d09fa080518f4

**Comment by dafeda** [comment]
The job `gendata_rft` saves to disk the same data twice.

Once via the function [_write_gen_data_files](https://github.com/equinor/semeio/blob/7c48099562f4c250d4b82cc6eca4074b97c31591/semeio/jobs/rft/gendata_rft.py#L10) that in addition to saving the data itself also saves two files with information about which rows are active.

The data is also [saved to .csv](https://github.com/equinor/semeio/blob/7c48099562f4c250d4b82cc6eca4074b97c31591/semeio/jobs/rft/gendata_rft.py#L200-L201) which we may be able to use instead.

Ideally, we should modify the `gendata_rft` job to only save the data once.
