### ISSUE TITLE
Config Validation - Catch mismatch between expected and given arguments for forward model jobs

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4694]
# background

tracked by #4599 

Forward model jobs are given in the command line according to the following format:

```
FORWARD_MODEL JOB_NAME(<ARG_A>=VALUE_A, <ARG_B>=VALUE_B)
```

where `JOB_NAME` refers to a job installed by a certain mechanism, and the key value pairs inside parantheses get parsed to a so-called "private args" substitution list.

the job referred to by name is defined through a job file that for instance looks like this:

```
$ cat src/ert/shared/share/ert/forward-models/old_style/COPY_FILE
STDOUT      copy_file.stdout
STDERR      copy_file.stderr
EXECUTABLE  ../../shell_scripts/copy_file.py
ARGLIST     <FROM> <TO>

MIN_ARG    2
MAX_ARG    2
ARG_TYPE 0 STRING
ARG_TYPE 1 STRING
```

observe the `ARGLIST` line. the arg list supplied on said line gets passed as arguments to the executable referenced by `EXECUTABLE`, after applying substitutions. We apply both substitutions from the so-called global scope, i.e. substitutions made up of predefined defines and defines parsed from the config file.

## goals

validate that the correct number of arguments is given in the forward model definition, compared to the job definition file.

this means we have to make sure that after applying all substitutions, there are no more elements of the form `<SOMETHING>` in the arg list.

also, it might be sensible to alert the user when a key value pair supplied in the forward model has no effect on the arg list, as that is probably not intended.

to summarize:

- [x] validate that enough substitutions are available to resolve all expected substitutions in the arg list of the job definition file
- [x] check that all supplied private args are used / necessary / have an effect

when we discover an unresolved argument, or a private arg without that does not resolve, we issue a warning.

## caveats / questions

- arg which uses pointy brackets and is not intended for substitution

are these even permitted? -> No! We catch these by interpreting them as unresolved intended substitutions, and report them as warnings to the user

- arg resolved both by global and private substitution

presumably, as long as something resolves the to be substituted strings, we're happy? -> yes, we are. we don't mind who or what does the job, as long as it gets done.

- some jobs have defaults, e.g.

```
$ cat src/ert/shared/share/ert/forward-models/old_style/ECLIPSE100
EXECUTABLE ../res/script/ecl100.py
DEFAULT <VERSION> version
DEFAULT <NUM_CPU> 1
DEFAULT <OPTS> ""
ARGLIST <ECLBASE> -v <VERSION> -n <NUM_CPU> <OPTS>
```
should make sure to consider that

**Comment by eivindjahren** [comment]
It isn't complete out of the question to simply add a list of "required" arguments:
```
$ cat src/ert/shared/share/ert/forward-models/old_style/COPY_FILE
STDOUT      copy_file.stdout
STDERR      copy_file.stderr
EXECUTABLE  ../../shell_scripts/copy_file.py
ARGLIST     <FROM> <TO>
REQUIRED <FROM>, <TO>

MIN_ARG    2
MAX_ARG    2
ARG_TYPE 0 STRING
ARG_TYPE 1 STRING
```

**Comment by valentin-krasontovitsch** [comment]
yeah, that is an option! it is a bit redundant, since we also have default values (for instance in the RMS job), but more verbosity helps more - of course there can be a difference between arguments without default values and required arguments, thinking of what the executable "requires". that seems to be a bit out of scope though / has the taste of a new feature, and I'm not sure if we want that.

or perhaps i misunderstand you, and you had a different idea about using the REQUIRED keyword?

at the moment my solution for "are enough args supplied" is a reformulation of the question into "are there any magic (sub)strings left in the arg list after all substitutions and default values (besides ITER and IENS which are OK)", and then you don't need the REQUIRED

**Comment by eivindjahren** [comment]
That is an option, yes. Although it does mean that the arglist cannot contain '<' or '>' that are not supposed to be replaced or they will have to have special "escape" syntax.

**Comment by eivindjahren** [comment]
I think maybe we need to communicate with the product owner about what we are considering here as I am not sure what sort of breaking changes we can/should make.

**Comment by valentin-krasontovitsch** [comment]
worry not - no breaking changes are being introduced. no behaviour changes at all should be introduced by the PR i'm making right now, as a matter of fact. an additional check function is called, which (assuming bug-free-code:tm:) has no side-effects besides issuing a warning if the validation fails.

as far as i understand, the code right now "permits" arguments with pointy brackets (<>) and will continue to do so, albeit with a warning. so worst case scenario is users complaining about noise. perhaps we can adjust the corresponding warning message to reflect that this (having `<FOO>` in the args after substitutions) is permissibly behaviour... i'll leave it up to the reviewer

**Comment by eivindjahren** [comment]
Yea, its the false positive noise I am worried about. I think we can do this, but lets use a logger.warning first and then replace it with a ConfigWarning once we have some numbers on how often this will happen in the wild.

**Comment by valentin-krasontovitsch** [comment]
alrighty, fair enough, although i personally think we're being tooooo caregul :stuck_out_tongue_winking_eye: changed from `ConfigWarning` to `logger.warning`
still need to adjust the tests to check the logs though rather than catch the warning...
