### ISSUE TITLE
Separate WorkflowJob data from the status of the running job

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4701]
After converting `WorkflowJob` to python, it is now clear that `WorkflowJob` does many different things:

1. It is used to load `ErtPlugins`.
2. It is used to load `ErtScript`.
3. It is used to denote an executable that can be called in a workflow.
4. It holds the information of a running exectuable/script/plugin.

Of those, the 4th point seems to have a big impact and be reasonably easy to to fix: push out the properties `isCancelled`, `hasFailed`, `isRunning` `stdoutdata` and `stderrdata` to its own class, say `JobRun` with methods `cancel(self)` and a function `run_job(self, job: WorkflowJob, ert: EnkfMain, arguments: List[Any], verbose: bool=False) -> JobRun`.

**Comment by eivindjahren** [comment]
The general idea is that `Workflow` and `WorkflowJob` has a `run` method, but that seems redundant because we also have a `WorkflowRunner` which should have the responsibility of all running. `Workflow` and `WorkflowJob` should probably be limited to concerns relating the setup/config.

**Comment by DanSava** [comment]
Seems that the `WorkflowRunner` is there to run a `workflow` in a separate thread and that is why there is a `run` method in `WorkflowRunner` and also in the `Workflow` and also when running a workflow we are running all the `WorkflowJobs` hence the need for the `run` method there as well... so I am not really following how you are suggesting to limit the concerns of `Workflow` and `WorkflowJob` just to setup and config.

**Comment by eivindjahren** [comment]
We can drop this change if it doesn't make sense. The issue generally was that the very many concepts were jammed into the "Workflow" class. I proposed changing the last one as it seemed the easiest change. Personally I would just wrap a workflow into a class private to `WorkflowRunner`:

```python

class _WorkflowExecution:
   def __init__(self, workflow: Workflow, ert: EnKFMain):
     ...
      
   def run(self):
     ...
```
So when `WorkflowRunner` wants to run a workflow it uses
```python
self._execution = _WorkflowExecution(workflow, ert)
self._workflow_executor.submit(execution.run)
```

**Comment by oysteoh** [comment]
@eivindjahren  do we have any updates to this issue? Should it still be present in the backlog or closed?

**Comment by eivindjahren** [comment]
Itis a blocker for https://github.com/equinor/ert/issues/5214
