### ISSUE TITLE
Seemingly ert version 4.2 has a problem related to ecl2csv style args

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4705]

**Comment by berland** [comment]
`ecl2df` configures a hook that is to be used as in :
https://fmu-docs.equinor.com/docs/ert/reference/forward_models.html#ECL2CSV

which is tested (for every komodo release) in https://github.com/equinor/ecl2df/blob/master/tests/test_ert_hooks.py  (and this works in 2022.12)

**Comment by eivindjahren** [comment]
@berland What is the error message?

**Comment by eivindjahren** [comment]
This was not actually a bug in ert.
