### ISSUE TITLE
Make __init__ of ResConfig simpler

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4710]
Currently ResConfig can take a filename or dictionary. Arguments given to `__init__` should already parsed and initialized objects:
```python
class ResConfig:
  def __init__(
    self,
    ens_path,
    substitution_list,
    env_vars,
    random_seed,
    queue_config,
    ert_workflow_list,
    runpath_file,
  ):
  ...
```

Reading from config and dictionary should be delegated to classmethods:

```python
class ResConfig:
  ...
  @classmethod
  from_file(cls, filename):
    ...
```

This should enable us to make a `__repr__` that satisfies `eval(repr(res_config)) == res_config`.

**Comment by DanSava** [comment]
What is the advantage of supporting something like:

```
eval(repr(res_config)) == res_config.
```

**Comment by eivindjahren** [comment]
Objects like that are generally easier to work with. The docs specify that `__repr__` should either be of the form `< description >` (an object of type class works like that) or satisfy `eval(repr(a)) == a`.
