### ISSUE TITLE
Load results manually shows wrong default iteration to load

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#4721]
**Describe the bug**
Load results manually shows wrong default iteration to load

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Click on Load Results Manually

**Expected behaviour**

**Screenshots**

![load_results_manually_bug](https://user-images.githubusercontent.com/45088507/214772431-9f3487a6-8973-4dcb-b6a8-037cd9042518.png)

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: main branch on 26. January

**Comment by valentin-krasontovitsch** [comment]
what should the default iteration to load be, @dafeda ?

**Comment by dafeda** [comment]
> what should the default iteration to load be, @dafeda ?

Sorry, I should have been a bit more specific.
Preferably one that actually exists, and perhaps it could be deactivated if the run path does not exist. In this case I just opened `poly.ert` and did not run a simulation of any kind.
If I click "Run results manually" followed by "Load" I get an error message saying "Failed load data for GEN_DATA node:POLY_RES".

**Comment by andreas-el** [comment]
> > what should the default iteration to load be, @dafeda ?
> 
> Sorry, I should have been a bit more specific. Preferably one that actually exists, and perhaps it could be deactivated if the run path does not exist. In this case I just opened `poly.ert` and did not run a simulation of any kind. If I click "Run results manually" followed by "Load" I get an error message saying "Failed load data for GEN_DATA node:POLY_RES".

You're trying to load invalid or non-existent results? The default number should be changed though, but does it make sense to ever have something other than zero there?
This seems to be already present in earlier releases also. The difference being that the error messages are found only in the `Event Viewer`.

Note that i ran 'Ensemble Experiment' on the poly-case, so iteration 2 should be invalid.

2022.11
![screenshot_manual_nov22](https://user-images.githubusercontent.com/114403625/214817024-046a11d7-e1d9-4fc9-bbae-c5aaefcb68f4.png)

2022.12
![screenshot_manual_dec22](https://user-images.githubusercontent.com/114403625/214817118-2217185e-edec-4573-890c-2e1ede3debd0.png)
