### ISSUE TITLE
Summary keys containing wildcards are not expanded with no refcase

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#4751]
When running the Drogon case in prediction mode we now (in komodo from Nov) get warnings when we start ert, related to the 
specification of the SUMMARY keyword in the ert pred config file. It does not seem to accept the * in the well names. And we do not 
have a refcase for the pred runs.

![image](https://user-images.githubusercontent.com/114403625/215744542-1038c449-c6b0-482b-be73-c41d460bcd07.png)

**Comment by ManInFez** [comment]
This will be fixed in the enkf_fs refactor work

**Comment by oyvindeide** [comment]
So this error message is a bit misleading, as this is not actually an error. However there seems to be an issue with reading responses for a prediction run.

**Comment by oyvindeide** [comment]
This has been fixed, there is a different issue related to prediction runs though.
