### ISSUE TITLE
Qt components exits lifetime scope

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#4752]
![2023-01-31_10-16-54](https://user-images.githubusercontent.com/114403625/215746009-7e82aa03-f008-4a3d-b5f0-dd9f00778c9f.png)

Ref.
https://equinor.slack.com/archives/CDPJULWR4/p1675156587427899?thread_ts=1671522230.777849&cid=CDPJULWR4

```
I have rerun the drogon_pred_ref.ert and despite the warnings run the Ensemble Experiment. After the run, I see that there is nothing that I can plot from ert gui.
```

**Comment by andreas-el** [comment]
Note that this might be related to the summary keys issue #4751

**Comment by eivindjahren** [comment]
It seems that the plot window has the rundialog as parent. When rundialog is removed then I believe that the plot window is assumed closed.

**Comment by eivindjahren** [comment]
Could be that the offending line is https://github.com/equinor/ert/blob/7506f0ab72ce2676c796245f6ce272531318206f/src/ert/gui/simulation/run_dialog.py#L110

**Comment by valentin-krasontovitsch** [comment]
to recreate, start a run, wait for it to finish, hi create plot button from run dialog, close the run dialog, and wait a bit, maybe while playing with the plot window
