### ISSUE TITLE
Suggestion for UMASK typo

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4764]
**Describe the bug**
The suggestion for UMASK keyword says "canbe" instead of "can be"

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Edit a config (e.g. poly_example) and add UMASK 123 on a line
3. `ert gui my_config.ert`
4. Read sentence in suggester
5. …

**Expected behaviour**
Correct spelling

**Screenshots**
![Screenshot from 2023-02-01 09-16-27](https://user-images.githubusercontent.com/596662/215987905-d898e118-8edb-4ece-b52d-e1cb01d518a1.png)

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: [e.g. 2.18 or 2022.12.03]
 - Python version 3.8
 - Remote/HPC execution involved: no

**Comment by eivindjahren** [comment]
This is already solved by https://github.com/equinor/ert/commit/b7d85726fd0fe149226c6af765d71e076b1a4c47
