### ISSUE TITLE
Possible flaky test in `test_event_reporter.py`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#4804]
FAILED tests/unit_tests/c_wrappers/job_runner/test_event_reporter.py::test_report_with_reconnected_reporter_but_finished_jobs - AssertionError: 10 seconds should be sufficient to send three events
assert (1675593001.6637156 + 10) > 1675593011.7096798

**Comment by Jehan-h20220012** [comment]
I want to work on this issue. Please assign me.

**Comment by dafeda** [comment]
> I want to work on this issue. Please assign me.

Thanks for showing interest. Please pick an issue marked as a good first issue.

**Comment by sondreso** [comment]
Hi @Jehan-h20220012! I have assigned you to https://github.com/equinor/ert/issues/4643

**Comment by Jehan-h20220012** [comment]
> Hi @Jehan-h20220012! I have assigned you to https://github.com/equinor/ert/issues/4643

Thank you so much!!

**Comment by dafeda** [comment]
This seems not to be a problem any longer.
