### ISSUE TITLE
Assertion Error of unexpected job status can happen with JOB_QUEUE_DO_KILL_NODE_FAILURE

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4809]
https://github.com/equinor/ert/blob/b828844409c74bcd22bd57f7196c9861a4bb8694/src/ert/_c_wrappers/job_queue/job_queue_node.py#L249-L252

**Comment by oyvindeide** [comment]
Any more stack trace from this?

**Comment by valentin-krasontovitsch** [comment]
this has now been observed while debugging a user case. while running esmda, the following exception occurs during the first iteration (`iter-0`) for realization 41:

```
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/job_queue_node.py", line 249, in _job_monitor
    raise AssertionError(
AssertionError: Unexpected job status type after running job: JOB_QUEUE_DO_KILL_NODE_FAILURE
```

ert keeps spinning, moves on to iteration 1, and fails during init with

```
Could not load node: INIT_FILES iens: 41 report: 0
```

(cf. also [internal slack thread](https://equinor.slack.com/archives/C01MCMWD075/p1687501135192689) and further discussion in channel)

cf. also 

- [an old occurence of the error in issue #1566](https://github.com/equinor/ert/issues/1566),
- a [general issue on unhandled job queue states](https://github.com/equinor/ert/issues/1900), and
- [an in-depth comment on the conditions around this error state](https://github.com/equinor/libres/pull/966#issue-646382248)
