### ISSUE TITLE
Add helpful links to the suggester gui

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4811]
**Is your feature request related to a problem? Please describe.**
When users get a suggestion it should be easy to contact us or find the documentation

**Describe the solution you'd like**
Using the get_help_links form plugin manager, add links to the suggester gui

**Describe alternatives you've considered**
Putting links in each specific error message. Not have useful links. Let users figure things out themselves.

**Additional context**
None

**Comment by DanSava** [comment]
What are the useful links that should be added to the "Suggestor" GUI? also should the same links be displayed when running using the CLI?
