### ISSUE TITLE
Use testing-requirements.txt file for required testing dependencies

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#485]
These deps should not live in separate scripts. 

Remember to update `testkomodo.sh` (https://github.com/equinor/ert/pull/475)

See also https://github.com/equinor/libres/issues/752

**Comment by oyvindeide** [comment]
Which deps are you thinking of? Is it this one in `testkomodo.sh`: `python -m pip install mock`? All test requirements are located in `setup.py`, and don't think we should introduce a separate file in `ert` for test requirements we have to keep in sync with `setup.py` or we'll quickly end up in the same situation we are in #648

**Comment by sondreso** [comment]
Agree, I think the solution you are adding closes this issue.

**Comment by oyvindeide** [comment]
Does it though? Test requirements won't be installed as `testkomodo.sh` doesn't run the tests with `python setup.py test`. It works for now because `pytest` is installed in `komodo`, but might not stay that way.

**Comment by jondequinor** [comment]
We have `dev-requirements.txt` for now. Isn't that good enough?
