### ISSUE TITLE
Opening Create Plot from Detailed Progress after run completes results in unresponsive widget

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4870]
**Describe the bug**
Opening Create Plot from Detailed Progress after run completes results in unresponsive widget (does not freeze).

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. Press Create Plot

**Expected behaviour**
A responsive widget.

**Comment by eivindjahren** [comment]
I wasn't able to reproduce this on main, has it been fixed?

**Comment by eivindjahren** [comment]
This seems to be fixed.
