### ISSUE TITLE
Run FMU tutorial in a Python 3 deploy

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#488]
Run the existing FMU-tutorials in a deployed Python 3. If it breaks, include the relevant people.

**Comment by oysteoh** [comment]
Blocked by #517 #516

**Comment by markusdregi** [comment]
This is currently blocked by the Python 3 milestone, but also the fact that the FMU tutorial is currently broken due to RMS licensing.

**Comment by jondequinor** [comment]
Could we just run the HM tutorial instead?

When it comes to RMS, should we roll our own test?

**Comment by markusdregi** [comment]
I'm not entirely sure what you're thinking? Instead of the FMU tutorial or something even more specific to RMS?

**Comment by jondequinor** [comment]
Yes. We have the SPE1 case running a minimal eclipse run, as well as several eclipse runs in the hm tutorial—but nothing afaics for RMS.

**Comment by markusdregi** [comment]
Alright, so what you would like to see is a minimal RMS setup? I think that is a very good idea 👍 Issue?

**Comment by jondequinor** [comment]
https://github.com/equinor/ert/issues/642
