### ISSUE TITLE
More informative error message when disk is full

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#489]
If scratch disk is full, the error message is somewhat cryptic for the average user. Should be clear what the problem is.

```
“util_make_path: failed to make directory:/scratch/my/runpath/realization-0/iter-0/ - aborting: No such file or directory(2)”.  

"Abort called from: util_make_path (`....cache/libecl-2.4.1/lib/util/util.c:4675)"
```

**Comment by markusdregi** [comment]
See if we get information about failing to create folder/file from error codes? If not, see if we can give the user a message depending on how much disk space is left...

**Comment by jondequinor** [comment]
Do we own all the code that might have side effects that includes disk writes? I.e. cannot the user create arbitrary scripts that interact with the scratch disk?

**Comment by markusdregi** [comment]
Sure, but when the forward model does this then the job fails. When the client does this, ERT completely goes down. The demonstrated problem occurs in our code.

**Comment by jondequinor** [comment]
Right, but in terms of informing the user, those cases can be equally bad. I.e. the FM could fail with an equally confusing "file not found" error, and even though ERT runs, the user would not know what to do next. So my argument is that we must include a warning as a part of the solution to this issue.

The warning has the added benefit of allowing the user to make room on the disk in front of a run.

**Comment by markusdregi** [comment]
Yes, but that is mostly Python code or externally developed software. I would assume Python at least, without having checked, to fail with a more informative message then libecl util currently does.

**Comment by markusdregi** [comment]
But, if we find a good place and condition to display the warning; I’m all for it!

**Comment by mortalisk** [comment]
After thinking a while on how to improve this generally, I gave up. So far I did the minimal fix, which I think takes care of this exact situation.
