### ISSUE TITLE
Creating new case from GUI crashes GUI

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4894]
To reproduce:
1) Go to Manage cases
1) Make sure `New case` is selected as `Current case`
1) Press +
1) Give name
1) Press OK

**Comment by oyvindeide** [comment]
Related to, and might be fixed by: https://github.com/equinor/ert/issues/4893

**Comment by frode-aarstad** [comment]
Can confirm that this still causes a core dump

**Comment by frode-aarstad** [comment]
Fixed by rebase on main
