### ISSUE TITLE
Verify that `Initialize from existing` copies parameters correctly

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4895]
Check that this functionality is tested, and if not, add a test.

**Comment by frode-aarstad** [comment]
There are tests for this

**Comment by oyvindeide** [comment]
Double check that there is also a test covering this functionality. There have been some changes to tests regarding this on main, so worth checking if a rebase will solve this, or there is a basis to expand on (the test is called `test_main_window.py` on `main`)

**Comment by frode-aarstad** [comment]
The functionality used is `copy_from_case ` which has its own test in `test_parameter_sample_typres.py `so it should be covered.

**Comment by frode-aarstad** [comment]
This relates to #4835

**Comment by oyvindeide** [comment]
First step is trying to figure out if this is being used by anyone. Asking specific users and asking generally in for example slack could be the first step. If we dont find anyone that uses this we can consider removing it, and rather reintroduce it later under a new name, for example `Copy parameters`

**Comment by oyvindeide** [comment]
This is not in use, and we should remove it, and bring back this feature in a more natual way down the line.
