### ISSUE TITLE
Invalid gridfiles can lead to segfaults

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4921]
**Describe the bug**
With the following in the config file 
```
FIELD G1 PARAMETER ./g1_field.grdecl INIT_FILES:g1.grdecl MIN:-5.0 MAX:5.0 FORWARD_INIT:True
GRID   Grid.EGRID 
```

If the `Grid.EGRID` is not valid, e.g. produced by doing `grid.to_file("Grid.EGRID")` on an xtgeo grid (which results in a roff formatted file, not an egrid formatted file), ert may segfault.

**Comment by oyvindeide** [comment]
Will be closed by: https://github.com/equinor/ert/pull/5251
