### ISSUE TITLE
Unhandled exception in run_dialog

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4923]
The following unhandled exception can occurr:

```
Failed to pop: .../realization-36/pred/ECLIPSE100.stderr.128 from {}
Traceback (most recent call last):
File ".../lib64/python3.8/site-packages/ert/gui/simulation/run_dialog.py", line 230, in remove_file
self._open_files.pop(selected_file)
KeyError: '...realization-36/pred/ECLIPSE100.stderr.128'
```

**Comment by sondreso** [comment]
Do we have steps to reproduce this? 🙂

**Comment by eivindjahren** [comment]
So the code has a comment from 2021 about this particular case happening from @oyvindeide . There might be a duplicate issue, but I have been unable to find it.
https://github.com/equinor/ert/blob/bca8ad60bc865a2e4ff5f7e2bdaa95d5548c0486/src/ert/gui/simulation/run_dialog.py#L223-L226

**Comment by oyvindeide** [comment]
With no steps to reproduce, and no recent reports, I will close this issue.
