### ISSUE TITLE
QA-routines

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#493]
We should sit down a formulate an MVP for QA routines that can be used in addition to the automatic tests to verify readiness for a new release. I think we should start with manual routines and then we can consider whether we should automate or change them later on. The intended usage is that they are gone through when the first release candidate is made to identify potential flaws and then another time when a release is ready.

**Comment by oyvindeide** [comment]
I think it is safe to close this as the tests for new releases have changed quite a bit since this issue was made.
