### ISSUE TITLE
Fail to load data when ert is used in prediction mode.

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4946]
**Describe the bug**
Users have reported that when ert is used in prediction mode after an assisted history match run the results are not loaded as expected.

**To reproduce**
Steps to reproduce the behaviour:
Currently dont have a way to reproduce, has been reproduced with Drogon, but not with any of our tests cases. Run drogon prediction.

**Expected behaviour**
Expected plot:
![image](https://user-images.githubusercontent.com/44577479/220909325-db2e2da6-4e32-412f-9713-f61fd5e9f247.png)

Current plot:
![image](https://user-images.githubusercontent.com/44577479/220909399-57cf57e9-abf4-4672-bb0e-aa88db5f3acb.png)

A few diagnostics have been tried:

This is by default not running with REFCASE

Running the case again with refcase from the prediction run -> ert will not start
Using history matched ensemble as refcase -> simulations run, but expected results are not loaded

**Comment by oyvindeide** [comment]
Was first thought this was related to: https://github.com/equinor/ert/issues/4751

**Comment by oyvindeide** [comment]
Thanks for testing! Is this the 2023.02.06 version of komodo? I ran something similar, but missing the prediction mode, and the `** Warning: Cannot expand * due to missing refcase file. Provide refcase file or add fully expanded SUMMARY key to configuration
` is indeed there, I thought it was gone (will have to check what happened there). That message is gone in the `main` branch though, and will be released soon. However that was message was a false positive as ert still loaded the data:

![image](https://user-images.githubusercontent.com/44577479/221789737-5f076e58-0baf-4a25-8bef-ef00960c6cd8.png)

Your testing indicates that something is wrong with the time though, and it almost looks like all the time steps are loaded correctly, except for the one very obviously wrong in 1970?

**Comment by sago64** [comment]
Yes sorry - good question. Case was ran in previous komodo version and stored for course purpose (tutorial ). But my test and opening is indeed using 2023.02.06.  Yes not sure about the 1970 for the 2 pred case...I am not sure this is the same problem Alif reported but hoping it is related. I will try to check with him today as we didn't run things the same way. Will come back to you if we get more testing results.

**Comment by oyvindeide** [comment]
Thanks! If we were to try to replicate this with a smaller example, what would it take, i.e. what is fundamentally different from an ahm run? For example, the fact that you restart from eclipse is not really something that ert cares about, so might be a detail we can omit.What is the content of the summary file in terms of time steps?

 * Is it all of the history and the prediction?
 * Are you using the TIMEMAP keyword?

General configuration
* There are no parameters?
* Are you loading GEN_DATA? Are they loaded as expected?

**Comment by sago64** [comment]
**Is it all of the history and the prediction?
Are you using the TIMEMAP keyword?**
Not sure about that I would need to check with the RE experts but the restart set up has as input the timestep it has to start from (manual from user). 
![image](https://user-images.githubusercontent.com/55280570/221802130-61488187-0277-45f1-b933-8dd20a868a74.png)

**General configuration

There are no parameters?
Are you loading GEN_DATA? Are they loaded as expected?**

Yes there is a parameter and I am tempted to test without, that could cause problem I imagine...?
![image](https://user-images.githubusercontent.com/55280570/221802368-aaab50bd-4de2-4687-96e2-65b2657cb394.png)

**Comment by oyvindeide** [comment]
> Yes there is a parameter and I am tempted to test without, that could cause problem I imagine...?

Should not cause any problems I think, can you plot it? It might be the reason for the 1970 (which is the start point for unix time), as it is fixed to time step 0.

**Comment by oyvindeide** [comment]
`GEN_KW` would be the parameter, so looks like there are no parameters, and looks like no `TIMEMAP` either, which means ert should read if from the summary file.

**Comment by sago64** [comment]
Sorry a bit of confusion for me , yes no gen_KW but when we try to plot NPV (GEN_DATA in the config file) then we get this error: 
![image](https://user-images.githubusercontent.com/55280570/221823607-9b3c538e-9774-483c-822d-082018fb60cc.png)
Sorry for the pngs...

**Comment by sago64** [comment]
Alif will do some testing too trying to reproduce the issue he gets when running with the current komodo (which I do not have here since the runs are existing from before). Wether it is related to my case or not let's see. Thanks!

**Comment by oyvindeide** [comment]
Seems a few lines are missing from the image, do you have them as well?

**Comment by sago64** [comment]
More png...

![image](https://user-images.githubusercontent.com/55280570/221847983-e4685696-3e37-47de-935d-9daa63efd759.png)

**Comment by alifbe** [comment]
@oyvindeide this looks similar to the issue reported here
https://github.com/equinor/webviz-ert/issues/376

I also experience similar issue:
without pred_ref:
![Image](https://user-images.githubusercontent.com/11570927/222125248-cfa02f9d-6d46-4e84-aac2-d3e2dcc971d1.png)
with pred_ref:
![Image](https://user-images.githubusercontent.com/11570927/222125614-6e4551e8-2f15-4f51-b2a3-592df9977956.png)

I created a new case called empty from ERT gui just for testing and from what I can see, pred_ref is probably not empty but contain invalid data?

**Comment by oyvindeide** [comment]
Thanks! Looks like a similar error to @sago64, might look a more in detail what data is actually loaded.
