### ISSUE TITLE
Display the number of parameters in the GUI

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4958]
It would be nice if the number of parameters in the case are shown next to the parameter names in the GUI.

**Comment by Jehan-h20220012** [comment]
Can anyone help me slove this issue so that I can raise the PR?

**Comment by frode-aarstad** [comment]
Something like this @oyvindeide :


![Image](https://github.com/equinor/ert/assets/30144033/b495cd75-4e4e-422f-a994-56d5a7bee1b2)

**Comment by oyvindeide** [comment]
Sorry for the late reply, so next to COEFFS there would be (3) in the poly example. And if you have a surface it would be (nx * ny) and for field (nx * ny * nz)
