### ISSUE TITLE
util abort raised if CONFIG_EXECUTABLE is missing permissions

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4960]
The call to a `res_env_alloc_PATH_executable` in `config_schema_item.cpp` will call `util_abort` if it doesn't have permissions to access the executable:

https://github.com/equinor/ert/blob/c29496db6d4a79f35c32268f8ee23286be924d7f/src/clib/lib/config/config_schema_item.cpp#L417

So a external job with the config:

```
EXECUTABLE /private/exec
```

where ert does not have access to `/private/` will result in an abort signal instead of an error message.

**Comment by valentin-krasontovitsch** [comment]
what is the source for this error, where did we encounter / see it? can we have a link to some logs please? @eivindjahren
