### ISSUE TITLE
Relative path problems when using `INSTALL_JOB` inside and outside INCLUDE file

### ISSUE THREAD

**Issue by rnyb** [equinor/ert#5011]
Relative path problems when using `INSTALL_JOB` inside and outside INCLUDE file
ERT seems to re-use relative location from include file.
Not sure if this is intended behaviour or a bug, but it has caused some user problems as it is hard to understand

**To reproduce**

1) define INSTALL_JOB inside an include file
2) define another INSTALL_JOB after include file

e.g.
```
INCLUDE  ../input/config/install_custom_jobs.ert
-- Add one more forward model outside include file
INSTALL_JOB   SOLVE_EVERYTHING   ../bin/jobs/FM_SOLVE_EVERYTHING
```

This will fail to install SOLVE_EVERYTHING as ERT seems to remember the relative location from INCLUDE file.
I.e. one needs to write
`INSTALL_JOB   SOLVE_EVERYTHING   ../../bin/jobs/FM_SOLVE_EVERYTHING`  -- relative to include file location
or
`INSTALL_JOB   SOLVE_EVERYTHING   <CONFIG_PATH>/../bin/jobs/FM_SOLVE_EVERYTHING`

**Comment by eivindjahren** [comment]
The fix for this issue should be enabled by default now.
