### ISSUE TITLE
There is a mismatch between what the grammar permits and the code handles with regards to arglist in the new parser

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5017]
There are several cases related to arglist and multi/single occurrence where the lark parser may give bad error messages. The following input for instance:

```
NUM_REALIZATIONS 10
FORWARD_MODEL job(<this>=<that>) job(<one>=<two>)
```
gives the error message `"No terminal matches 'j' in the current parser context, at line 3 col 34\n\nFORWARD_MODEL job(<this>=<that>) job(<that>=<mean>)\n             
                    ^\nExpected one of: \n\t* NEWLINE\n\t* COMMENT\n""`

However, in `_TreeToDictTransformer.keyword` the transformation of the tree into `List[Union[Instruction, JobInstruction]]` is complicated by handling cases which the parser will not produce. Also, the error messages given for these cases will have to be tested/evaluated for whether they are possible to understand.

**Comment by mortalisk** [comment]
The only problem I understand here, is that the error message could have more information. But we also can't really foresee all the different ways one could do silly things, so I think in general the best we can do is give an indication of where we found something unexpected, which is exactly what this message does.

What has this got to do with single-occurrence?

**Comment by eivindjahren** [comment]
@mortalisk What I was thinking is that we only have one multi-occurrence `JobInstruction` on no single occurrence `JobInstruction`s so the code is a bit convoluted for picking that out of the tree. I think we should make some investigation about which trees are not permitted to occur versus what does the dictionary transformer handle and check that there are no bad states or bad error messages.

**Comment by mortalisk** [comment]
I think this is no longer relevant
