### ISSUE TITLE
Problems with installing Forward Model jobs fail silently

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5055]
https://github.com/equinor/ert/blob/9e2a24f0f5347b428db1adf422e12ddfe191ba74/src/ert/_c_wrappers/enkf/ert_config.py#L578

This has to be handled with care because this is the machnism in which the the reservoir simulators are installed so any warning here will show up in most dev and external environments.

**Comment by oysteoh** [comment]
- We need to look into if it is possible to move the Equinor spesific jobs from default site config ( i.e ECLIPSE ) to avoid annoying messages / warnings on developer computers
- Add message to the suggestor if we try to install a job which does not exist

**Comment by eivindjahren** [comment]
After looking closer into this, I believe that all that is necessary is a bit of a refactor. I misunderstood the situation when we first looked into this issue.
