### ISSUE TITLE
Esc closes run_dialog with no message

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/ert#506]
As a user I do not want the monitoring dialog (`run_dialog.py`) to close immediately when the `Esc` key is pressed (possibly inadvertently), so that I can check what is the status of the case I am running

The dialog disappears, it seems that simulations keeps running, but it's unclear whether new ones will be submitted or not. Pressing again `Run simulations` bring up a new dialog partially filled, but I suspect new simulations are also submitted.
Pressing, eg, `Create plot` after closing the dialog with `Esc` causes ERT to crash.

I suspect the best solution would be to just avoid closing the dialog.
@ManInFez recently added some cose to handle a `QCloseEvent` but that does not seem to work properly, at least on my machine (OSX, Python27, Qt5)

**Comment by sondreso** [comment]
Resolved by #514
