### ISSUE TITLE
Not longer possible to set `step_length` in `SIES`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5062]
**Describe the bug**
Not completely sure that this in fact is the case, but I suspect that [this commit](https://github.com/equinor/ert/commit/cd3b47b106bccfa45c2de094b38399592b7a194c#diff-636527661d6dcb9dc9554d4db4bd8d303771b625e35a6a66b849e1eaf068a862R185) introduces a regression where user-provided `step_length` is no longer used in `SIES`.

Specifically see line `211` of `_es_update.py` where `step_length=module_config.get_steplength(w_container.iteration_nr)` is removed.

**Comment by eivindjahren** [comment]
I believe the module_config.get_steplength was reimplemented in iterative_ensemble_smoother with the idea that its parameters would be passed to the IterativeEnsembleSmoother constructor in `src/ert/shared/models/iterated_ensemble_smoother.py` but that was not done. So this seems to indeed be a bug.

**Comment by eivindjahren** [comment]
I have confirmed that cd3b47b106bccfa45c2de094b38399592b7a194c does stop the ability to set steplength. Adding `step_length=module_config.get_steplength(iterative_ensemble_smoother.iteration_nr)` on line `199` does make the following snapshot test succeed with a snapshot created before  cd3b47b106bccfa45c2de094b38399592b7a194c (and fails without the addition):
```
@pytest.mark.integration_test
def test_that_running_ies_with_different_steplength_produces_different_result(
    tmpdir, source_root, snapshot
):
    shutil.copytree(
        os.path.join(source_root, "test-data", "local", "poly_example"),
        os.path.join(str(tmpdir), "poly_example"),
    )

    with tmpdir.as_cwd():
        with open("poly_example/poly.ert", mode="a", encoding="utf-8") as fh:
            fh.write(
                """
RANDOM_SEED 1234
ANALYSIS_SET_VAR IES_ENKF IES_MAX_STEPLENGTH 0.5
ANALYSIS_SET_VAR IES_ENKF IES_MIN_STEPLENGTH 0.2
ANALYSIS_SET_VAR IES_ENKF IES_DEC_STEPLENGTH 2.5
ANALYSIS_SELECT IES_ENKF
"""
            )

        parser = ArgumentParser(prog="test_main")
        parsed = ert_parser(
            parser,
            [
                ITERATIVE_ENSEMBLE_SMOOTHER_MODE,
                "--target-case",
                "iter-%d",
                "--realizations",
                "1,2,4,8,16",
                "poly_example/poly.ert",
                "--port-range",
                "1024-65535",
            ],
        )
        FeatureToggling.update_from_args(parsed)

        run_cli(parsed)
        FeatureToggling.reset()
        facade = LibresFacade.from_config_file("poly.ert")
        iter_0 = facade.load_all_gen_kw_data("iter-0")
        iter_1 = facade.load_all_gen_kw_data("iter-1")
        iter_2 = facade.load_all_gen_kw_data("iter-2")
        iter_3 = facade.load_all_gen_kw_data("iter-3")
        result = pd.concat(
            [iter_0, iter_1, iter_2, iter_3],
            keys=["iter-0", "iter-1", "iter-2", "iter-3"],
        )
        snapshot.assert_match(
            result.to_csv(float_format="%.12g"), "ies_steplength_snapshot"
        )
```
