### ISSUE TITLE
PlotAPI may timeout for setups seen in real use

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5065]
The following error condition can seemingly be hit by users which have large setups:

https://github.com/equinor/ert/blob/924e13b7d2abe8d1de1b4a17dceeabf7b400b652/src/ert/gui/tools/plot/plot_window.py#L91-L95

**Comment by eivindjahren** [comment]
We have seen this traceback in real usage:
 ```
None of the URLs provided for the ert storage server worked.
Traceback (most recent call last):
  File "/.../ert/gui/tools/plot/plot_window.py", line 53, in __init__
    self._api = PlotApi()
  File "/.../ert/gui/tools/plot/plot_api.py", line 21, in __init__
    self._reset_storage_facade()
  File "/.../ert/gui/tools/plot/plot_api.py", line 24, in _reset_storage_facade
    with Storage.session() as client:
  File "/.../ert/services/storage_service.py", line 89, in session
    base_url=inst.fetch_url(), auth_token=inst.fetch_auth()[1]
  File "/.../ert/services/storage_service.py", line 77, in fetch_url
    raise TimeoutError(
TimeoutError: None of the URLs provided for the ert storage server worked.
```

**Comment by mortalisk** [comment]
Could this be because observation loading is slow? I remember we once doubled the timeout of initializing dark_storage, because it spent a minute parsing some observation file.

**Comment by tralsos** [comment]
Are you sure it is only for large setups ? I had a similar error message "None of the URLs provided..." when running drogon (and all other models), and I learnt from another user with the same problem it was related to a proxy setting in one of my startup files .bashrc or .profile, so when I removed that everything was fine.

**Comment by oysteoh** [comment]
Good point @tralsos  . @eivindjahren  do you think it is possible to distinguish ( and advice the users ) between a "real" bug and the proxy-errors? Now we are treating `RequestError` and `TimeoutErrors` the same way.

**Comment by eivindjahren** [comment]
I am not sure. I think we would require some assistance from e.g. @oyvindeide

**Comment by oysteoh** [comment]
@eivindjahren you have assigned yourself to this, do you know if it is still a problem? Is the current criticality `high` relevant?

**Comment by eivindjahren** [comment]
I will have another look at whether this is a problem on Troll, if it is I think I will have to unassign myself as I have no way of reproducing the failure.

**Comment by oyvindeide** [comment]
Tested this recently, and is still happening.

**Comment by eivindjahren** [comment]
This should be ~twice as fast now, but we will have to test with troll before we know for sure.

**Comment by eivindjahren** [comment]
Just got confirmation that this is still the case

**Comment by oyvindeide** [comment]
Will close this as it has been superseded by: #8369 and #8125
