### ISSUE TITLE
magic strings will not be substituted into the INCLUDE keyword

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5073]
```
DEFINE <SOME_PATH> /some/path
INCLUDE <SOME_PATH>/test.ert
```
In the above example, the old parser will try to include `<SOME_PATH>/test.ert` and not `/some/path/test.ert`.

I believe this is already fixed in the new parser but we should create a test for that.

**Comment by DanSava** [comment]
Check and it seem it is not fixed in the new parser either

**Comment by DanSava** [comment]
Solving this issue will require a redesign of how the defines are handled. They need to be available for substitution when the include mechanism is reached.

**Comment by oysteoh** [comment]
Resolved with #5059
