### ISSUE TITLE
Test internalization with many realizations and big data

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#508]
The callback is now running in parallel, without the max cap of 4, so this should be tested with massive amounts of data and realizations.

**Comment by ManInFez** [comment]
Tested:
100 realization, 384 MB internalized data per realization, 50 concurrent realizations
500 realization, 22 MB internalized data per realization, 200 concurrent realizations

**Comment by markusdregi** [comment]
Good start!

We should also test this with `#concurrent realizations` * `data` higher then available RAM on machine....

**Comment by ManInFez** [comment]
100 realization, 1.4 GB internalized data per realization, 100 concurrent realizations - Hits maximum memory usage and is killed

**Comment by ManInFez** [comment]
100 realizations. 996 MB in 32 MB chunks per realizations, 100 concurrent realizations  - Success

**Comment by markusdregi** [comment]
@eivindsm What do you think?

**Comment by markusdregi** [comment]
This should be actioned upon. https://github.com/equinor/ert/issues/567
