### ISSUE TITLE
Suggestion for workflow wf_fmuobs

### ISSUE THREAD

**Issue by tklov11** [equinor/ert#5082]
**Is your feature request related to a problem? Please describe.**
I notice that the workflow job wf_fmuobs reports back "None" even if the observations have been written to file. Perhaps "OK" is a better report?

INFO:ErtScriptModule_4:Writing observations in YAML (webviz) format to file: None

**Describe the solution you'd like**
Substitute None with OK. None indicates that nothing was written to file, even when the file was written ok as far as I can see.

**Describe alternatives you've considered**

**Additional context**

**Comment by rnyb** [comment]
I think this already have a solution ready in subscript repo, ref:
https://github.com/equinor/subscript/issues/520
https://github.com/equinor/subscript/pull/522
