### ISSUE TITLE
Failed realizations due to MAX_RUNTIME leads to "Could not load node" error

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#5109]
**Describe the bug**
User reported the following. Several others have seen similar failures, related to "could not load node" of some kind.

```
MAX_RUNTIME reached in run path ...
Runtime: 18000.692074775696 (max runtime: 18000)
Realization: 0 failed after reaching max submit with:

Workflow job ... failed
...
Could not load node: DUMMY iens: 1 report: 0
```

**To reproduce**
Steps to reproduce the behaviour:
Unknown

**Expected behaviour**
Successful run

**Screenshots**
From terminal:
![image](https://user-images.githubusercontent.com/596662/225861249-8de49ee8-aceb-4922-802d-ff934df9ee25.png)

**Environment**
 - OS:. RHEL7
 - ERT/Komodo release: 2023.03.01
 - Python version
 - Remote/HPC execution involved: yes

**Comment by sondreso** [comment]
Is this maybe related to https://github.com/equinor/ert/issues/4979?

**Comment by eivindjahren** [comment]
@sondreso Could be related. I believe that the users that reported #5109 ran esmda automatically without running analysis manually. #4979 only happens when you run analysis manually as `STATE_PARENT_FAILURE` seemingly only occurrs when you run analysis manually.
