### ISSUE TITLE
Move deprecation warnings into the new parser

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#5119]
**Issue**

We are parsing a config file twice, once when creating the ert_config object and again when trying to generate the list of suggestions. This should be refactored to only do the parsing once.

**Comment by oysteoh** [comment]
Would probably make sense to wait until the new parser is the only one

**Comment by oysteoh** [comment]
Is this actionable now @DanSava  - or do we need to wait until the old parser is gone?
