### ISSUE TITLE
Experiments and starting from an existing case

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#5128]
Once https://github.com/equinor/ert/issues/5095 is resolved, it might reveal an issue we have with the ERT logic.

It brings us closer to the definition of "experiment" as a snapshot of the user's config at the time of simulation run. Each time ERT GUI is started, it will create an ensemble named `default`, or find an existing one. If the user starts and closes ERT -- creating a default case in the process --, changes their config and starts ERT again, it'll load `default` as the current case which will be the one used if the user clicks on the "evaluate" button. Ideally, data about the config will be taken from the experiment of the `default` case, which at this time is the user's previous configuration. If the user intends the evaluation to be run with the new config, they will be mistaken. We should provide a way from the default ensemble to switch to a new config.

**Definition of done:** It's possible to start an ensemble run on any existing case, using the new config.

This could, for example, be done via a message box saying `f"Detected change in ERT configuration. Do you want to create a new empty case '{case.name}' with the new configuration?"`.

**Comment by oyvindeide** [comment]
Closing this as the restart functionality and `default` case has changed a lot since this was create. Today we use the in memory configuration for new experiments, and the on disk configuration for existing experiments. I think this is the most consistent way to do it.
