### ISSUE TITLE
Adjust test_job_runner_startup_overhead timeout to previous 4 seconds

### ISSUE THREAD

**Issue by xjules** [equinor/ert#5138]
**Describe the bug**
Not really a bug, but having timeout of 4 seconds for job_runner startup was not enough on Azure. Thus, we should aim to have it back to original 4 once the Azure infrastructure is "ready" for it.

**To reproduce**
Check https://github.com/equinor/komodo-releases/actions/runs/4488061743/jobs/7893344998

**Expected behaviour**
The test on Azure should not timeout.

**Environment**
 - OS:  RHEL7
 - ERT/Komodo release: 2023.03.03, /prog/komodo - Azure
 - Python version 3.8
 - Remote/HPC execution involved: no

**Comment by eivindjahren** [comment]
This test was removed as it was too unreliable. We had one incident which would have had this test fail, but instead failed the individual test timeout. That timeout was then just increased in the PR. I think we have a small problem of test failures being ignored and the test either modified to be less strict or removed entirely, but that is unrelated to this issue.
