### ISSUE TITLE
Unexpected case "gui"

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#5141]
**Describe the bug**
After running a config, a new case called "gui" is created

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run Smoother, select yes to question of whether to use default case
4. Create plot
5. Observe the case list, there is a case gui with the second iteration results

**Expected behaviour**
Two cases, default with the first iteration result, default_smoother_update with the updated results.

**Screenshots**

**Environment**
 - OS: MacOS
 - ERT main, as of 24 March
 - Python version, 3.9
 - Remote/HPC execution involved: no

**Additional context**

**Comment by yngve-sk** [comment]
Maybe some progress on it, looking further into it

In `ensemble_smoother_panel.py`, this code exists:

```python
    def getSimulationArguments(self):
        arguments = Arguments(
            mode="ensemble_smoother",
            current_case="gui",
            target_case=self._target_case_model.getValue(),
            realizations=self._active_realizations_field.text(),
        )
        return arguments
```

changing `"gui"` here to something else results in that token being outputted as a case when plotting after running Ensemble Smoother on default

**Comment by andreas-el** [comment]
There is also a problem that this causes new identically named 'gui' cases found in the selector.
