### ISSUE TITLE
Main gui case list not updated after new cases are created

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#5142]
**Describe the bug**
After running an experiment, one might expect the new cases to be selectable from the drop down menu of the experiment. But they are not

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run Smoother
4. Close monitor
5. Try to run again, with one of the newly created cases, observe your inability to do so

**Expected behaviour**
Able to select a new case

**Environment**
 - OS: MacOs
 - ERT main as of 24th March
 - Python version: 3.9.12
 - Remote/HPC execution involved: no

**Comment by oysteoh** [comment]
Cannot be reproduced on Linux, should have a go on MacOs and see if it is possible to reproduce there

**Comment by andreas-el** [comment]
Not reproducible on Mac using Python version 3.9.6 using bleeding 2023.03.31.

Other bugs are present;
'gui' case showing up in selector #5141
'default' not being present on startup #5178

**Comment by DanSava** [comment]
I guess this can be closed as it is no longer reproducible
