### ISSUE TITLE
Backport bugfixes to April-release

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5177]
Gather bugs fixed in the `done` column and backport to april release. Low threshold for leaving commits behind if it is difficult to backport.

**Comment by eivindjahren** [comment]
Following is a list of candidates for backports. We should have a low threshold for not backporting if there is a lot of merge conflicts or other indications that backporting will create problems:

- [ ] #4989
- [ ] #4963 
- [ ] #4933 
- [ ] #4953 #4987 #5048 #5031
- [ ] #4968 
- [ ] #5042 
- [ ] #4580 
- [ ] #4922
- [ ] #3727 
- [ ] #5144
