### ISSUE TITLE
Case selector does not behave correctly

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5178]
**Describe the bug**
When starting ERT we except the `current case` to contain the `default` case on fresh startup. 

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`

![Image](https://user-images.githubusercontent.com/4508053/229041667-b204ead8-e628-4a21-8f57-852db11467bc.png)

**Expected behaviour**
Able to select a default case in the `current case` dropdown list.

**Environment**
 - OS: UNIX
 - ERT main as of 30th March
 - Python version: 3.10.8
 - Remote/HPC execution involved: no

**Comment by andreas-el** [comment]
Related to #5154
