### ISSUE TITLE
Suggest what to do when target case exists

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#5203]
As a total ERT noob, I'm running HM tutorial (Reek) from the command line in the same way that we do it in CI, eg like 

    ert es_mda --target-case default_%d --disable-monitoring reek_hm/r006/ert/model/hm_analysis.ert

Attempting to rerun the job gives me an unreported fatal error and the notice:

    - Target case: default_0 exists

We should give the user:

- The information that this was a fatal error
- One or two hints about how to fix it
- Perhaps also the option to just deal with it and move on

**Comment by oyvindeide** [comment]
This should now be fixed as we allow duplicate name and separate on uuid.
