### ISSUE TITLE
GEN_KW: Files generated from templates use system locale

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#521]
My system uses `LANG=nb_NO.UTF-8` which causes generated floating point numbers to incorrectly use a comma as a decimal separator instead of a dot. For example, running `poly_example` will produce the following `coeffs.json` files:

```json
{
    "a": 0,836308,
    "b": 0,90515,
    "c": 1,57191
}
```

This can be worked-around by setting `LC_NUMERIC=en_US.UTF-8` prior to starting `ert`.

One solution would be to `setlocale(LC_ALL, "en_US.UTF-8")` as early as possible. A better solution would be to respect the user's locale for anything user-facing (GUI), but format configs with C locale.

**Comment by oyvindeide** [comment]
Think this has been fixed as the writing of these files are now done in python. Feel free to reopen if you can still reproduce.
