### ISSUE TITLE
Dependencies defined in both setup.py and requirements.txt

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/ert#522]
Dependencies are duplicated/defined both in `setup.py` and `requirements.txt`. This is a source of confusion and dependencies getting out of sync.

E.g. currently, installing `ert` using `setup.py` installs `matploblib<3` (while `requirements.txt` has removed the `<3` criteria).

**Comment by markusdregi** [comment]
You are absolutely right. We are currently evaluating how we are to define requirements in our Python projects. I do however believe that as an end-user/consumer, you should let the installation take care of this and hence get dependencies from `setup.py`.

**Comment by markusdregi** [comment]
Relates to: https://github.com/equinor/ert/issues/485 https://github.com/equinor/ert/issues/648
