### ISSUE TITLE
New ensembles not showing up in current case selector dropdown

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#5230]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run experiment (IES/Smoother/ESMDA)
4. New created ensembles are available for plotting.
5. New created ensembles are not available in the `current case` dropdown in any of the simulation pannels. 
6. They show up after restarting ert 

**Expected behaviour**
The new ensembles resulting from (IES/Smoother/ESMDA) should show up in the `current case` dropdown. 

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: 2023.04.rc8-py38
 - Python version
 - Remote/HPC execution involved: no

**Comment by andreas-el** [comment]
This was changed in commit b2f7c2cc5 - CaseSelector keeps track of global current_case
According to the originator of this commit, this change is quite tied into the storage change done between ert versions 4.5.0 and 5.0.0.

**Comment by andreas-el** [comment]
Closed as won't do due to this considered as a low priority issue that has a reasonable and easy workaround. The upcoming release will also have this issue resolved.
