### ISSUE TITLE
Fix deprecation warning: Implementing implicit namespace packages (as specified in PEP 420) is preferred

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#5260]
Fix deprecation warning:

packages/google/rpc/__init__.py:20: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.rpc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    pkg_resources.declare_namespace(__name__)

../../test-kenv/root/lib64/python3.8/site-packages/pkg_resources/__init__.py:2349
  /private/f_scout_ci/runner-linapp1194/_work/_temp/test-kenv/root/lib64/python3.8/site-packages/pkg_resources/__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(parent)

**Comment by jonathan-eq** [comment]
I will try this one!
