### ISSUE TITLE
Solve flake8-bugbears B017

### ISSUE THREAD

**Issue by berland** [equinor/ert#5284]
```
$ pip install flake8-bugbear
$ flake8 | grep B017 | wc -l 
8
```

`flake8-bugbear` says:

> B017 `assertRaises(Exception)` and `pytest.raises(Exception)` should be considered evil. They can lead to your test passing even if the code being tested is never executed due to a typo. Assert for a more specific exception (builtin or custom), or use `assertRaisesRegex` (if using `assertRaises`), or add the `match` keyword argument (if using `pytest.raises`), or use the context manager form with a target.

which makes sense. We should fix these to avoid being exposed to the test itself failing.

**Comment by jonathan-eq** [comment]
I am doing this
