### ISSUE TITLE
log full contents of config file / config dict

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5291]
we would like to be able to see the forward model with exact arguments as supplied in the config file, and perhaps the resulting config dict for internal ert usage.

at the moment, we drop (among others) the forward model lines from the logs as our logging backend (azure log analytics) seems to have a [restriction of 1 MB per API call](https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits#logs-ingestion-api)

we should

- test the suspected limit
- make sure that we log the whole config file / config dict if it fits
- perhaps break up the content into several chunks if it's too large

and finally the latter should perhaps be solved not in ert, but in one of our internal packages used for logging to azure

**Comment by valentin-krasontovitsch** [comment]
encoding the content in base64 still produced content that was more than 2048 bytes long, so it seems we need to chunk the file

**Comment by eivindjahren** [comment]
We have investigated this and it seems difficult because of size restrictions. May be possible in the future.

**Comment by valentin-krasontovitsch** [comment]
@eivindjahren should this be open or closed now? it seems to be placed in the done column
