### ISSUE TITLE
Starting plot tool with experiment running case causes error

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#5296]
**Describe the bug**
Starting with an already run drogon storage, already run with previous release. Then starting plot tool while experiment running,
causes an exeption

**To reproduce**
Steps to reproduce the behaviour:
1. source /prog/res/komodo/testing/enable 
2. cd drogon_20230202_12-27/resmod/ff/21.0.3/ert/model/
3. `ert gui drogon_ahm.ert`
4. Run experiment Smoother
5. Click yes to use existing case
6. wait a bit
7. click plot button
8. observe error

**Expected behaviour**
Ert to run as normal, plot tool to not crash

**Screenshots**
![Screenshot from 2023-04-26 13-52-16](https://user-images.githubusercontent.com/596662/234567412-8ac3fe67-1fb8-436d-a18e-f65aa4e80d68.png)

**Environment**

 - OS: [e.g. RHEL7]
 - ERT/Komodo release: 2023.05.b3-py38-rhel7
 - Python version
 - Remote/HPC execution involved: no

**Additional context**

**Comment by oyvindeide** [comment]
Does this have an existing storage from `main`? If so that will not be compatible with older ert<5. It looks like that might be the case here?

**Comment by mortalisk** [comment]
> Does this have an existing storage from `main`? If so that will not be compatible with older ert<5. It looks like that might be the case here?

Could be, unsure which version it was run with already.
