### ISSUE TITLE
profile poly example

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5305]
in a recent retrospective, we discussed memory usage in ert. we would like to use less memory, if possible, and stop increasing memory usage where unnecessary.

to this end, we would like to profile the poly case for memory usage.

we should consider where to profile (in which environment), how precisely / deeply to profile (total usage / by functions / over time during invocation?), and finally we might want to monitor whatever data this produces over time, i.e. run the profiling on PRs (as a test, with a check that might fail?!) or as part of nightly (to simply gather data over time).

**Comment by eivindjahren** [comment]
There is now tests running with memory profiling on and one of them uses the poly_template so I will close this as resolved.
