### ISSUE TITLE
ECL2CSV failed on parsing UDQ for WSEGVALV keyword

### ISSUE THREAD

**Issue by hrsut** [equinor/ert#5307]
**Describe the bug**
ECL2CSV failed to parse WSEGVALV keyword that is calling UDQ variable.

**To reproduce**
To reproduce this bug. Simply create a schedule files with UDQ, and try to parse it by calling a string, since now WSEGVALV is only expecting floats.

**Expected behaviour**
It is expected that WSEGVALV keyword can take UDQ variables to be called inside it.
ref Eclipse manual page 2352.

**Environment**
 - OS: [RHEL7]
 - ERT/Komodo release: [2023.04.02-py38]
 - Python version
 - Remote/HPC execution involved: [no]

**Comment by berland** [comment]
This issue cannot be fixed in Ert.

ECL2CSV is an ERT plugin coming from https://github.com/equinor/ecl2df, the issue can be reported there, or further upstream in https://github.com/OPM/opm-common/
