### ISSUE TITLE
Possibly simplify summary key lists in ensemble_config

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#5308]
During a PR-review, this question came up: 
https://github.com/equinor/ert/pull/5265#discussion_r1177607746

> It seems that isinstance(key, list) is always true in tests. Is it the case that summary_list will only contain lists? In that case it could possibly simplify the logic here.

ensemble_config.py:266
```
        for surface in surface_list:
            surface_node = self.get_surface_node(surface)
            self._create_node_metainfo(surface, 1, EnkfVarType.PARAMETER)
            self.addNode(surface_node)

        for key in summary_list:
            if isinstance(key, list):
                for kkey in key:
                    self.add_summary_full(kkey, self.refcase)
            else:
                self.add_summary_full(key, self.refcase)
```

**Comment by DanSava** [comment]
When we first started the config refactoring and parsing there was the test config `dict` that would contain list of summary keys and the config_content_to_dict that would generate something different. That is no longer the case so yes the logic can be simplified.
