### ISSUE TITLE
Monitoring and Eclipse stdout

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#532]
Stdout from Eclipse now points to the .LOG file. This is good, however during runs the file is long and overwritten frequently, and this makes it impossible to scroll in the viewer. Suggestion: display something similar to 'tail -f' when status is running, and the entire file when status is done.

Also it seems like the 'LOG file has been moved from the place where eclipse was run to runpath. This is confusing and should be fixed. Eg if eclipse was run in iter-0/eclipse/model/HM.DATA, the HM.LOG file seems to be renamed and moved to /iter-0.

**Comment by eivindsm** [comment]
Ok, that is not super user friendly. Can it be defaulted in the standard eclipse job?

Eivind

**Comment by markusdregi** [comment]
> Ok, that is not super user friendly. Can it be defaulted in the standard eclipse job?

Of course. The users will never see this. My comment above was to the ones trying to resolve the task :+1:

**Comment by dotfloat** [comment]
> Also it seems like the 'LOG file has been moved from the place where eclipse was run to runpath. This is confusing and should be fixed. Eg if eclipse was run in iter-0/eclipse/model/HM.DATA, the HM.LOG file seems to be renamed and moved to /iter-0.

We've arrived at two different possible solutions:
1. Set default `STDOUT`s for eclipse as @markusdregi proposes. The files will be `<ECLBASE>.LOG.1`, `<ECLBASE>.LOG.2` etc, where the number represents the job index in the forward model.
2. Write to `<ECLBASE>.LOG` as we have done previously, except that this time the output also shows up in the GUI.

Please advise on which you'd prefer, @eivindsm .

**Comment by markusdregi** [comment]
It should be noted that while the first alternative is using the existing functionality of _libres_, the second alternative is not and will require a little bit of extra code complexity to float.

**Comment by eivindsm** [comment]
It is imminent that we do not tamper too much with how the forward model components behave compared with regular usage. The user expects the log file to reside with the data file. Hence, I clearly prefer option 2 ( unless I misunderstood again :) )

**Comment by dotfloat** [comment]
The log file will be in the same directory as other Eclipse files. The difference between the two alternatives is only in the file name. The first alternative would have `.LOG.#` (where # is some number), while the second alternative would have `.LOG` like it did previously.

**Comment by eivindsm** [comment]
Perfect, so alternative 2 seems to be the better option.
