### ISSUE TITLE
Add to/from-json for Surface

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5323]
Currently the surface information is saved explicitly in: https://github.com/equinor/ert/blob/daea5dfe98e874b157491162eccf93115d1189a2/src/ert/storage/local_experiment.py#L180 which is called in the constructor: https://github.com/equinor/ert/blob/daea5dfe98e874b157491162eccf93115d1189a2/src/ert/storage/local_experiment.py#L104-L107, we should instead save this on the experiment in a `parameters.json` file with a structure something like:
```json
{
    "parameter_1": {
        "name": "parameter_1",
        "type": "Field",
        "nx": 12
        ...
    },
    "parameter_2": {
        "name": "parameter_2",
        "type": "SurfaceConfig",
        "rotation": 1
        ...
    }
}

```
where `SurfaceConfig` has a `to_json` and `from_json` we can use to save/load metadata.

**Comment by dafeda** [comment]
https://github.com/equinor/ert/blob/09b86c04c2d87926e6895f14c5789b22bd4b9d05/src/ert/storage/local_experiment.py#L102

Addition of this solves the issue I think.

**Comment by oyvindeide** [comment]
Closing as completed then :+1:
