### ISSUE TITLE
Allow newline between options  in GEN_DATA keyword

### ISSUE THREAD

**Issue by alifbe** [equinor/ert#5331]
**Is your feature request related to a problem? Please describe.**
In some cases, the result_file option in GEN_DATA keyword is a very long path. It will be nice to be able to split the options into multiple line. From the documentation, it mentions that all options for GEN_DATA keyword are required, so it should be possible to parse all the options even they are in multiple lines.

**Describe the solution you'd like**
It should be possible to define GEN_DATA in ERT using either one of these:

``GEN_DATA AMP_2020_2018_TOP   RESULT_FILE:share/results/points/topvolantis_amplitude_mean_20200701_20180101_%d.txt   INPUT_FORMAT:ASCII  REPORT_STEPS:1``

````
GEN_DATA 
    AMP_2020_2018_TOP   
    RESULT_FILE:share/results/points/topvolantis_amplitude_mean_20200701_20180101_%d.txt   
    INPUT_FORMAT:ASCII  
    REPORT_STEPS:1
````

**Describe alternatives you've considered**

**Additional context**

**Comment by oyvindeide** [comment]
Fixed in: https://github.com/equinor/ert/pull/9406
