### ISSUE TITLE
Default case names for ES and ES-MDA

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#537]
Should discuss if to revert new default case names for es and es-mda. I originally assumed they would be similar to case name in runpath, but they are not. Let's discuss.

**Comment by markusdregi** [comment]
Revert to old functionality for now

**Comment by oyvindeide** [comment]
I can't find where this has changed, any more details to troubleshoot this issue?

**Comment by markusdregi** [comment]
Try running es-mda with master and `2.5` to see if you can reproduce that the case names have changed.

**Comment by oyvindeide** [comment]
Right, I was looking at the `runpath` not the case name, I've reproduced, will investigate.

**Comment by oyvindeide** [comment]
As this change was made for all iterative analysis modules this also applies to `IES`, do we want to revert the change there as well?

**Comment by oyvindeide** [comment]
> Right, I was looking at the runpath not the case name, I've reproduced, will investigate.

Wasn't actually able to reproduce, and the original question remains, can't find where this behavior has changed the last three years, so while the change suggested here will make the default name for `ES` and `ES-MDA` behave in the same way (i.e. both append `_smoother_update_%`, it will change existing behavior. 

@eivindsm do you have a way to reproduce the changes you observed?

**Comment by oyvindeide** [comment]
After further discussion we decided to keep the original behavior, but that I could be good to have a discussion about the relationship between the `case name` and the names in the `runpath`. Closing this.
