### ISSUE TITLE
ERT reports missing time mismatch after restart

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#538]
After running a prediction case from restart and get funky stuff:
Time mismatch for step:70   New_Time: 01/11/2005   existing: 31/12/1969
Time mismatch for step:71   New_Time: 01/12/2005   existing: 31/12/1969
Time mismatch for step:72   New_Time: 01/01/2006   existing: 31/12/1969
Error while handling error. Exiting. File: /var/jenkins/jenkins-be/workspace/komodo/cache/libres-master/lib/enkf/time_map.cpp Function: time_map_summary_update_abort, Line: 630
Error message: time_map_summary_update_abort: inconsistency when updating time map
Error while handling error. Exiting. File: /var/jenkins/jenkins-be/workspace/komodo/cache/libecl-master/lib/util/util.c Function: util_abort_signal, Line: 4446
Error message: Program received signal:6
Aborted (core dumped)

I have a testcase reproducing this issue. Get in touch

**Comment by markusdregi** [comment]
This was produced while going through the tutorial in: https://github.com/equinor/ert/issues/540

**Comment by ManInFez** [comment]
Unable to reproduce. Most likely a bad state, could be user error or something in when running the MDA. Should investigate further in the next pre-test version

**Comment by markusdregi** [comment]
Cannot reproduce. User error? We will rerun tutorial before release.
