### ISSUE TITLE
Performance test xarray saving/loading (responses)

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5398]
One of the bottlenecks in the current storage solution is saving and loading datasets. We should benchmark different ways of doing this, for example:

- [ ] Scipy as engine with groups as folders
- [ ] netcdf4 as engine with native groups (have often seen this segfault, which might make it unviable)
- [ ] h5netcdf as engine with native group
- [ ] The h5netcdf package directly, converting the loaded data to xarray Dataset

**Comment by pinkwah** [comment]
`scipy` is best ingen protest
