### ISSUE TITLE
Go through history matching tutorial with new release

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#540]
@eivindsm Will provide link to wiki page.

**Comment by eivindsm** [comment]
As discussed with Markus the HM tutorial and corresponding data set is a comprehensive suite suitable for testing. Unfortunately, the wiki is down, so sending a link is difficult as of now. My personal copy in Stavnager is can be used for testing: /project/fmu/tutorial_ert/users/eism/r003/r003_20190912/ert/model

A membership in the fmu group is necessary for access.

**Comment by eivindsm** [comment]
Link to tutorial: https://wiki.equinor.com/wiki/index.php/HM_ERT_tutorial

**Comment by jondequinor** [comment]
Is this done in the nightly CI? Or is it expected to be manual?

If the latter, can this be automated?

**Comment by markusdregi** [comment]
This is currently manual. Making the functionality available by the cli tested automatically for this case as well should be no problem. We can just make a similar setup to the one we have for the tutorial. However, when it comes to the GUI functionality it requires a bit more effort

**Comment by mortalisk** [comment]
I will attempt to automate it

**Comment by jondequinor** [comment]
https://github.com/equinor/ert/issues/584

**Comment by jondequinor** [comment]
We're closing this in favour of the automated check.
