### ISSUE TITLE
Fix SUMMARY keyword handling

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#5400]
There is some weird behavior now regarding `SUMMARY` keyword. It looks like doing `SUMMARY * FORWARD_INIT:True` ends up creating some dynamic result meta info with forward_init=True which I don't think is how this used to behave at least it isn't documented.

Docs say (or at least used to) that `SUMMARY a b c` should be the same as `SUMMARY a\nSUMMARY b\nSUMMARY c`  but that wasn't the case when we started working on the config and I am not sure if it ever worked that way.

Not sure whether this actually effects ert, but it is weird that `ErtConfig.from_dict({"SUMMARY": ["*", "FORWARD_INIT:True"]})` ends up doing what it does now.

**Comment by andreas-el** [comment]
Related to https://github.com/equinor/ert/pull/5397

**Comment by DanSava** [comment]
Directly from the documentation the summary data type:

```
Summary: SUMMARY
~~~~~~~~~~~~~~~~

The ``SUMMARY`` keyword is used to configure which summary vectors you want to
load from the (Eclipse) reservoir simulation. In its simplest form, the
``SUMMARY`` keyword just lists the vectors you wish to load. You can have
multiple ``SUMMARY`` keywords in your config file, and each keyword can mention
multiple vectors:

::

   SUMMARY  WWCT:OP_1  WWCT:OP_2  WWCT:OP_3
   SUMMARY  FOPT FOPR  FWPR
   SUMMARY  GGPR:NORTH GOPR:SOUTH

```

So I guess the documentation describes `SUMMARY a b c ` and it should behave like `SUMMARY a\nSUMMARY b\nSUMMARY c`
