### ISSUE TITLE
Unpin `scipy` at 1.9.1

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#5423]
`ert` is pinned at <1.9.2 but I can't see any comments or issues explaining why.

https://github.com/equinor/ert/blob/main/setup.py#L147

There was an issue with `xtgeo` and `pyscal` requiring <= 1.9.2 due to [a bug in SciPy](https://github.com/scipy/scipy/pull/16780). The bug has supposedly been fixed but `pyscal` seems to still have issues, [see this](https://github.com/equinor/pyscal/issues/388). AFAICT, `xtgeo` [is fixed](https://github.com/equinor/xtgeo/issues/811).

Komodo currently has 1.9.1 and I'm leaving it there for now.

**Comment by andreas-el** [comment]
Looks like Pyscal has been fixed also!
https://github.com/equinor/pyscal/pull/401

Verified that Xtgeo uses SciPy 1.10.1 in its tests. ✅
