### ISSUE TITLE
Introduce Qtest

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#543]
Plain Python unittesting of the Ert GUI is currently futile. As an example, the `run_dialog`, a very central part of simulation runs, instantiates ~20 graphical `Q`-objects in its initializer. You would need to mock this, as most of them require a `QApp`. This is not practical.

[`pytest-qt`](https://pypi.org/project/pytest-qt/) integrates nicely with `pytest` where `qbot` provides the `QApp`.

The rationale for introducing qt testing is the folllwing:
_After some development task of the Ert GUI code is executed, determining whether net code quality has gone up, is an exercise left to our users._

**Comment by dotfloat** [comment]
I was looking into integrating this into `unittest` stuff that we already have. Ideally we'd be able to write something like:

```python
class HelloTest(unittest.TestCase):
    def test_hello(self, qtbot):
        widget = HelloWidget()
        qtbot.addWidget(widget)

        qtbot.mouseClick(widget.button_greet, QtCore.Qt.LeftButton)

        self.assertEqual(widget.greet_label.text(), 'Hello!')
```

According to https://stackoverflow.com/a/22694144 , it's not possible to use `pytest-qt`'s `qtbot` in `unittest` stuff as described above. We can probably create a `class QTestCase(unittest.TestCase)` that has `qtbot`'s functionality (ie. `qtbot.addWidget` -> `self.addWidget`) and instantiates `QApplication` on first run.

**Comment by jondequinor** [comment]
This has been done.
