### ISSUE TITLE
Fix surface not being read from run path

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5434]
Make sure this code path is tested, making https://github.com/equinor/ert/blob/0f4b6059c58c685a0c5bf27e545109bddfa943fd/tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py#L733-L738 test values across the ensemble.

**Comment by dafeda** [comment]
Here's what's currently in `main`:

https://github.com/equinor/ert/blob/6a33e5d1cf9055499b68f0a1ad3fd59bca9734d4/tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py#L753-L772

        assert not (surf.values == surf2.values).any()
```

I think this solves this issue.
