### ISSUE TITLE
`plot_api.py`: UserWarning: Could not infer format, so each element will be parsed individually...

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5452]
**Describe the bug**

Getting these warnings when plotting results from running `poly.ert` on main.

```console
UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.columns = pd.to_datetime(df.columns)
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui plot.ert`
3. Plot some things

**Expected behaviour**
No warning

**Environment**
 - OS: macos
 - ERT/Komodo release: main
 - Python version 3.10
 - Remote/HPC execution involved: no

**Comment by berland** [comment]
FYI: Was fixed in https://github.com/equinor/ert/commit/1d73cc3663c690f7496fe8e8dd8e8c2c6d248a15 but that was reverted two commits later.

**Comment by dafeda** [comment]
> FYI: Was fixed in [1d73cc3](https://github.com/equinor/ert/commit/1d73cc3663c690f7496fe8e8dd8e8c2c6d248a15) but that was reverted two commits later.

Why was it reverted?

**Comment by berland** [comment]
https://app.slack.com/client/T02JL00JU/search/search-eyJkIjoibWl4ZWQiLCJxIjoiVTAzVjRUQVNNIiwiciI6Im1peGVkIiwicyI6InJlY2VudE1lc3NhZ2VzIn0=/thread/CKC3H3W74-1684196630.667349

**Comment by frode-aarstad** [comment]
blokced by https://github.com/equinor/ecl2df/issues/448

**Comment by oyvindeide** [comment]
Check if this is still relevant, the blocking issue has been solved.

**Comment by frode-aarstad** [comment]
Not relevant
