### ISSUE TITLE
'ert_shared/ertplot.py'

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#547]
That stand-alone program doesn't work with the current codebase and looks abandoned. Is an earlier version used anywhere in production?

The alternatives are:
- Fix it so it works. (+ add unit tests)
- Remove it from the codebase.

Would love to hear some input.

**Comment by markusdregi** [comment]
Could you try to establish when it last worked? Does it work in version `2.5`?

**Comment by dotfloat** [comment]
Doesn't seem so.

https://github.com/equinor/ert/blob/81c76bf01eab0ea5ecbac5628ba678a96e3e9a0f/python/python/ert_gui/ertplot.py#L59

https://github.com/equinor/ert/blob/81c76bf01eab0ea5ecbac5628ba678a96e3e9a0f/python/python/ert_gui/tools/plot/plot_window.py#L26-L33
