### ISSUE TITLE
PyQt dependency in ert cli

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/ert#552]
From what I can tell, it looks like #465 was reintroduced [here](https://github.com/equinor/ert/commit/f014337fd76867ea2816c1dcca45076aeb259290#diff-6f34528ec850101ca6f6058318322590R7).

With master I currently get:
```
ert --help
Traceback (most recent call last):
  File "[...]/python3.6/site-packages/ert_gui/gert_main.py", line 18, in <module>
    from PyQt4.QtCore import Qt, QLocale
ModuleNotFoundError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/bin/ert", line 2, in <module>
    from ert_shared.main import main
  File "[...]/python3.6/site-packages/ert_shared/main.py", line 8, in <module>
    from ert_gui.gert_main import run_gui
  File "[...]/python3.6/site-packages/ert_gui/gert_main.py", line 21, in <module>
    from PyQt5.QtCore import Qt, QLocale
ModuleNotFoundError: No module named 'PyQt5'
```

[`from ert_shared.main import main`](https://github.com/equinor/ert/blob/e4fc1105ba5230ad70bf694d2dae887bd0e9792d/ert_shared/bin/ert#L2)
↓
[`from ert_gui.gert_main import run_gui`](https://github.com/equinor/ert/blob/e4fc1105ba5230ad70bf694d2dae887bd0e9792d/ert_shared/main.py#L8)
↓
[`from PyQT5.... import ...`](https://github.com/equinor/ert/blob/e4fc1105ba5230ad70bf694d2dae887bd0e9792d/ert_gui/gert_main.py#L20-L22)

**Comment by markusdregi** [comment]
Thanks for the report @anders-kiaer!

We will look into it.

Team: I think we should support cli running without Qt, and if so, perhaps we should add a CI-test that validates that we can?
