### ISSUE TITLE
New parser should handle pre-defines similarly to old parser

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5521]
Currently, for instance `<CONFIG_PATH>` is handled differently in `ExtJob.from_config_file`. 

The users expect `<CONFIG_PATH>` to be the directory of the main ert config, but is currently pointing at the directory of the ExtJob config. It seems that this behavior is only present in the new parser.

**Comment by eivindjahren** [comment]
For the new parser, it should be enough to `lark_parse(..., pre_defines={})`

**Comment by oysteoh** [comment]
Resolved by https://github.com/equinor/ert/commit/14ab7012d7e660829ff6fd02b7fba6f31a616bd3
