### ISSUE TITLE
Implement LocalEnsemble `finalize` function, which combines all realisations into one dataset.

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5527]
This has potential performace improvements. We should do it explicitly in the run models after we have finished loading all data. Could potentially be done in a different thread (or process). Then load results manually should probably do this directly and not do the callbacks individually first.

**Comment by pinkwah** [comment]
Gonna wait with implementing this until we have figured out the starting on an existing case issue.

**Comment by eivindjahren** [comment]
Resolved by https://github.com/equinor/ert/pull/7563
