### ISSUE TITLE
Total progress is 100% while realizations are still running

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5552]
**Describe the bug**

User on Yammer reported that ERT states ensemble experiment is done while realizations are still running.

https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjI5Mzc1NTYzMTY3MzM0NCJ9

![image](https://github.com/equinor/ert/assets/45088507/f8f67ac1-9e6f-45cc-8a69-805bdb6e3880)

**To reproduce**
Steps to reproduce the behaviour:

Not sure how to reproduce this

**Expected behaviour**
`Total progress` and `Running` should show the same thing.

**Comment by andreas-el** [comment]
Relates to #6248

**Comment by sondreso** [comment]
Most likely fixed by https://github.com/equinor/ert/pull/6256, re-open if this happens again.
