### ISSUE TITLE
Create analysis report for quality control of history match / sensitivity analysis

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5556]
Currently, we only provide information in the `deprecated` file as to what happened during an update.
A report of sorts is needed to allow users to better assess the quality of the analysis step.
Convergence, which observations, responses, realizations were used, settings used to localize etc. etc.

See #4156

**Comment by oyvindeide** [comment]
We should also store this information along with parent ensemble, etc.

**Comment by oyvindeide** [comment]
Related to #4156

**Comment by oyvindeide** [comment]
Will close this as much of the indicated information is now propageted to the file on disk, and will soon be available in the GUI, we will create issues for individual pieces of information to add later.
