### ISSUE TITLE
APIs run_gui and run_cli should be consistent

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#557]
`run_gui` and `run_cli` should act somewhat similar, even though they are quite dissimilar: The GUI should intercept any simulation errors, and present them in the GUI. The CLI should present simulation errors as an error with the command, i.e. log to `sys.stderr` and exit with a non-`0` exit code (exact same thing `sys.exit` does when called with a non-integer argument).

So my suggestion is that the return signature is the same as the [`sys.exit`](https://docs.python.org/2/library/sys.html#sys.exit) parameter signature.

A stream handler for logging errors when running the CLI could also be added.

**Comment by oyvindeide** [comment]
We should add a log stream handler to the `GUI` with level `ERROR` so we can give more information to the user, and potentially a lower level stream handler if the `verbose` flag is set. We should also review the exit codes, especially for the CLI, for example we should check how keyboard interrupt is handled.

**Comment by oyvindeide** [comment]
Most of this has been completed, and there is a different issue for dealing with handling the exceptions. Will close this
