### ISSUE TITLE
Only save mask instead of field on experiment

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5654]
Currently we are saving a copy of the field on each experiment, however we are only using the `ACTNUM` from said field. This means we are storing much more data that needed. We should change to only storing the mask as a numpy array.

We are currently doing that here:
https://github.com/equinor/ert/blob/28804d83441fd874806f2666f5e1bc034b57a926/src/ert/storage/local_experiment.py#L104-L109

we could replace the explicit `save_grid` functionality with an option on the experiment to save blob data (for example), so other parameters could potentially use the same in the future. That involves removing:
https://github.com/equinor/ert/blob/28804d83441fd874806f2666f5e1bc034b57a926/src/ert/storage/local_experiment.py#L45
and replacing it with something like:
``` python
def get_blob_data(self, key):
    return self._path / "blob_data" / key"
```

**Comment by frode-aarstad** [comment]
@oyvindeide Is this not already done?

**Comment by oyvindeide** [comment]
Yes, forgot to link the issue, will close
