### ISSUE TITLE
Refactor Qt widgets

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#566]
Currently, many widgets don't follow the MVC pattern, nor use Qt's signals & slots. The biggest problem area from what I've seen is [`/ert_gui/simulation/detailed_progress.py`](https://github.com/equinor/ert/blob/f617112410d02cc8554d56c75e3cb896c82a8615/ert_gui/simulation/detailed_progress.py), where we should, among other things, use Qt's built-in widgets instead of calculating mouse-clicks and such ourselves.

This should be paired with #543 .

**Comment by jondequinor** [comment]
We will be doing exactly this, but motivated by https://github.com/equinor/ert/issues/1238

**Comment by jondequinor** [comment]
- [ ] Re-implement STDERR STDOUT
- [ ] Better handling of dates in Qt
- [ ] Re-introduce `calculate_progress` to correctly report progress
- [ ] Test models
- [x] Test legacy tracker
- [x] Test evaluator tracker
