### ISSUE TITLE
Pydantic v2

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#5672]
Pydantic v2 has been released. See here for migration guide: https://docs.pydantic.dev/2.0/migration/

I imagine this shouldn't affect us too much, but we will still have to test it.

The main blocker for this is perhaps FastAPI, which has its own issue on this matter: https://github.com/tiangolo/fastapi/issues/9710

**Comment by verveerpj** [comment]
It was not a straightforward upgrade for me. I would suggest starting with using it with `from pydantic import v1 as pydantic_v1` (not tested by me), so that at least it can be upgraded and pinning can be avoided.

**Comment by pinkwah** [comment]
We should find all places in komodo that uses Pydantic v1 and change to the following

```
try:
    from pydantic.v1 import BaseModel
except ImportError:
    from pydantic import BaseModel
```

This is verbose, but at least doing this will make the version compatible with both v1 and v2 of the package, so we don't have to move everything over all at once.
