### ISSUE TITLE
Weird behavior when INDEX_LIST is shorter than the number of observations for GEN_OBS

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#569]
Should fail, with a sensible error message. Current behavior seems to fetch random memory and use that as index for the last observations. Places the observations with indexes somewhere in the range from -1e9 to 1e9.

**Comment by markusdregi** [comment]
Instructions on how to edit the poly case to reproduce would we nice ;)

**Comment by sondreso** [comment]
Closing this, as I am not able to reproduce...
