### ISSUE TITLE
add regression test for unhandled job queue state

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5709]
i missed out on adding a regression test for the unhandled job state that was described in #4809 and solved by #5667.

@berland found this [example test](https://github.com/equinor/ert/blob/main/tests/unit_tests/c_wrappers/res/job_queue/test_job_queue.py#L107) that one might be able to piggy-back on and adjust to produce the desired state that would trigger the changes covered by the PR.

it would at least be nice to have a test covering this.

**Comment by xjules** [comment]
Based on the findings, we should:

- remove `JOB_QUEUE_DO_KILL_NODE_FAILURE` state, since the initial though was to use this state to blacklist the node automatically but this feature is either gone or we don't know where to find it.
- Where the `JOB_QUEUE_DO_KILL_NODE_FAILURE` state is set we should use just `JOB_QUEUE_DO_KILL` instead.
- Thus no regression test is needed :)

**Comment by valentin-krasontovitsch** [comment]
the ert app state that triggers the to be removed `JOB_QUEUE_DO_KILL_NODE_FAILURE` and is now handled, is not replicated in tests. replacing the `JOB_QUEUE_DO_KILL_NODE_FAILURE` with another state constant / name will not alleviate that - unless you also suggest to not handle that application state anymmore :thinking:

**Comment by valentin-krasontovitsch** [comment]
I think I'm failing to make myself understood.

Check out this [code snippet](https://github.com/equinor/ert/blob/b2df82ce73d16fdf9e6a555cc9cec8f66027ed08/src/clib/lib/job_queue/job_node.cpp#L238):

```
        if ((current_status & JOB_QUEUE_RUNNING) &&
            (node->status_file && !(fs::exists(node->status_file)))) {
            // it's running, but not confirmed running.
            time_t runtime = time(nullptr) - node->sim_start;
            if (runtime >= MAX_CONFIRMED_WAIT) {
                std::string error_msg = fmt::format(
                    "max_confirm_wait ({}) has passed since sim_start"
                    "without success; {} is assumed dead (attempt {})",
                    MAX_CONFIRMED_WAIT, node->job_name, node->submit_attempt);
                logger->info(error_msg);
                msg = error_msg;
                job_status_type new_status = JOB_QUEUE_DO_KILL_NODE_FAILURE;
                job_queue_node_set_status(node, new_status);
            }
        }
```

that's where we at the moment use `JOB_QUEUE_DO_KILL_NODE_FAILURE`. if i understand correctly, you want to just use `JOB_QUEUE_DO_KILL` instead - fine, perfectly reasonable.

what I'm saying (and this issue is about) is: the state or code path described by this if condition is not covered by our tests. that's all. so unless we want to remove the whole if block, we might want to consider adding a test that covers this path.

seeing how we were not handling that state in the python code, which led to bad user experience and a difficult to debug error, it seems prudent to have a regression test, and i should have fixed it as part of the original PR...

**Comment by xjules** [comment]
> that's where we at the moment use JOB_QUEUE_DO_KILL_NODE_FAILURE. if i understand correctly, you want to just use JOB_QUEUE_DO_KILL instead - fine, perfectly reasonable.

Yes, that's the main point - his particular state is not used as intended and `JOB_QUEUE_DO_KILL` would server the same purpose.

> what I'm saying (and this issue is about) is: the state or code path described by this if condition is not covered by our tests. that's all. so unless we want to remove the whole if block, we might want to consider adding a test that covers this path.

That makes perfect sense and can be part of the PR! 
Any idea how to come about this constraint:  `const time_t MAX_CONFIRMED_WAIT = 10 * 60;` ?

**Comment by valentin-krasontovitsch** [comment]
the magic number of 10 minutes (10 * 60 seconds) has basis in the previous magic number of 2 minutes, which seemed to be not long enough. we suspect that the condition checked for can occur, and be resolved after 2 minutes, so we increased the waiting time. assuming long running realizations of several hours, and asuming that this condition does not actually occur very often, this increased timeout seemsd an acceptable penalty

**Comment by xjules** [comment]
After several back and forth discussions, the plan is to remove this state entirely since 
1) It only sets the state to  `JOB_QUEUE_DO_KILL_NODE_FAILURE` and this state is essentially not treated adequately. 
2) It is quite I/O bound due to the frequent poking of the status file (from the job_queue that is the server) and thus can alleviate some workload.

**Comment by berland** [comment]
This is not relevant anymore.
