### ISSUE TITLE
LSF_SERVER config linting

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5715]
Have had a user-support case where the user got an exception like this and was not able to continue

```
ssh: Could not resolve hostname $ert_lsf_server: Name or service not known
Submitting: /usr/bin/ssh $ERT_LSF_SERVER bsub -o /private/ooh/test/poly_example/poly_out/realization-1/iter-0/poly_1.LSF-stdout -q mr -J poly_1 -n 1 -R "select[cs && x86_64Linux]" -P user:ooh /prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/equilibrium/bin/komodo_job_dispatch /private/ooh/test/poly_example/poly_out/realization-1/iter-0 
ssh: Could not resolve hostname $ert_lsf_server: Name or service not known
```

Reason for this is that she had 
```
QUEUE_OPTION LSF LSF_SERVER $ERT_LSF_SERVER
```
in her config-file. This is not the way we do it anymore and this is configured through ert-configurations. What happens here is that LSF_SERVER is set to $ERT_LSF_SERVER ( not resolved since the variable does not exist ) and overwrites what we have in ert-configurations. 

Not sure if this is a big problem - but in general - should we warn users about overwrites or in some way mitigate at least things like this to happen as it is not very user-friendly!

Update 31-08-23:
This would be useful for inspecting all QUEUE_OPTION provided. If any (for a given queue system) have duplicates, we know that they will be overwritten.

**Comment by andreas-el** [comment]
Site-wide variables: https://fmu-docs.equinor.com/docs/ert/reference/configuration/site_wide.html

**Comment by andreas-el** [comment]
in ert_config.py
```python
 @classmethod
    def from_dict(cls, config_dict) -> "ErtConfig":
        substitution_list = SubstitutionList.from_dict(config_dict=config_dict)
        runpath_file = config_dict.get(
            ConfigKeys.RUNPATH_FILE, ErtConfig.DEFAULT_RUNPATH_FILE
        )
        substitution_list["<RUNPATH_FILE>"] = runpath_file
        config_dir = substitution_list.get("<CONFIG_PATH>", "")
        config_file = substitution_list.get("<CONFIG_FILE>", "no_config")
        config_file_path = os.path.join(config_dir, config_file)

        errors = cls._validate_dict(config_dict, config_file)
        errors += cls._validate_queue_option_max_running(config_file, config_dict)

        if errors:
            raise ConfigValidationError.from_collected(errors)

        ensemble_config = EnsembleConfig.from_dict(config_dict=config_dict)
        errors += cls._validate_ensemble_config(config_file, config_dict)
```

If you setup a site_wide config file;
```
QUEUE_SYSTEM LOCAL -- note that this was added just for debug purposes only

-- Set some properties of the local LSF system
QUEUE_OPTION LSF LSF_QUEUE hmqueue
QUEUE_OPTION LSF MAX_RUNNING 100
QUEUE_OPTION LSF LSF_SERVER   lsf-front01.company.com
QUEUE_OPTION LSF BSUB_CMD     /path/lsf/bin/bsub
QUEUE_OPTION LSF BJOBS_CMD    /path/lsf/bin/bjobs
QUEUE_OPTION LSF BKILL_CMD    /path/lsf/bin/bkill
```

You can test with the poly-example and refer to the site-wide.ert using;
```
export ERT_SITE_CONFIG=path/to/your/file
```

**Comment by andreas-el** [comment]
One possible approach would be to count the options provided in the configuration (which is site & user configuration combined). In the case where two or more exist, we know that variables will be overwritten.
