### ISSUE TITLE
UX: GUI cancelling ensemble should pop some explanation / error message

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5725]
Related to #5273 (found while trying to solve that one)

**To reproduce**

1. Get your hands on a user model that has lots of fast running forward models, run it with tons of realizations (cf. comments in #5273, and observe that at time of writing, this was difficult / impossible to reproduce with an artificial case since we've done some changes that made the situation more stable)
2. Run it, wait for gui to bring down ensemble
3. Observe failure, without message explaining the failure
4. Have to look for reason for failure in the logs, looking for a needle in a hay stack without a priori knowledge (the ert logs just show bunch of queue killed messages, the ee logs have somewhere hidden that the gui is cancelling the ensemble)

**Expected behaviour**
Would have loved some message along the lines of what is found in the logs - something like 

> GUI tracker could not connect to ensemble evaluator server for updated about the progress of the ensemble simulations, cancelling ensemble

**Screenshots**

![Screenshot from 2023-07-18 08-18-19](https://github.com/equinor/ert/assets/15932677/380d9fee-9dcb-4ae4-bacc-8dfbdd22ba43)

**Environment**
 - OS: RHEL7 (rgs node)
 - ERT/Komodo release: bleeding 2023-07-17
 - Python version 3.8
 - Remote/HPC execution involved: totes

**Comment by xjules** [comment]
Let's check if this is logged already.

**Comment by xjules** [comment]
Errors and more explanations why realizations have failed is now logged and displayed to the users. Let's wait for some feedback.

**Comment by berland** [comment]
It should not be possible to have the ensemble brought down like this any more. Suggesting to close.

**Comment by oyvindeide** [comment]
Closing!
