### ISSUE TITLE
Linting/gathering of obvervation config errors

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#5729]
Currently observation config errors are not raised until its invocation from ENKFMain, and it is yet to be decided where and how, and if, these errors should be gathered the same way. TO BE DECIDED, but it is an issue as it does not currently smoothly integrate with the `ert lint` command

**Comment by oysteoh** [comment]
Putting this into the backlog as it is not necessary to solve for the current milestone

**Comment by eivindjahren** [comment]
This works as expected now.
