### ISSUE TITLE
`UPDATE_SETTING` keyword is documented and checked but unused

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5739]
`ConfigKeys.UPDATE_SETTING` exists and is documented in `keywords.rst` but is currently unused. Need to investigate whether this has been unintentionally dropped or has not been working correctly for a long time.

If it hasn't been done anything for a long time, it should be removed.

**Comment by andreas-el** [comment]
This used to control smoother settings overlap and cutoff (now named ENKF_ALPHA and STD_CUTOFF).
The UPDATE_SETTINGS keyword was removed back in 2019, and affected keywords were refactored after that.
Both ALPHA and CUTOFF are available still.
