### ISSUE TITLE
MAX_RUNTIME not working?

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#576]
Users have reported `MAX_RUNTIME` to not work properly over `lsf`. I suggest to modify the poly case so that the job sleeps for a long time, add `MAX_RUNTIME 2` and see whether we can reproduce.

**Comment by ManInFez** [comment]
Which version are the using?

**Comment by wouterjdb** [comment]
Currently 2.4.git (for some reason I have a very old version - I'll rebuild my env now and report back)

**Comment by ManInFez** [comment]
Sorry, are you building your own, or are your sourcing komodo? In the komodo case, which komodo version?

**Comment by wouterjdb** [comment]
I'm building my own environment.

**Comment by ManInFez** [comment]
Are you building the current master, or are you checking out a specific tag?

**Comment by wouterjdb** [comment]
Building master for ert, libres but 

```
# Download and set LIBECL_VERSION specified in libres:
$(wget https://raw.githubusercontent.com/equinor/libres/master/.libecl_version -q -O -)
```

for libecl.

**Comment by markusdregi** [comment]
@wouterjdb You don't necessarily have that old an res build; see https://github.com/equinor/libres/issues/818

**Comment by wouterjdb** [comment]
> @wouterjdb You don't necessarily have that old an res build; see [equinor/libres#818](https://github.com/equinor/libres/issues/818)

Aha! Ok, so then it might be much younger. 👍

**Comment by ManInFez** [comment]
Very recently (12 days) we made some changes that should mitigate the MAX_RUNNING problem. So if you built it before that, it might be already fixed ;)

**Comment by wouterjdb** [comment]
Before meaning after I guess? :) So if I build master per today it might be solved?

**Comment by ManInFez** [comment]
Meaning, if the version you were experiencing the bug with was older, it might have been solved in newer version.  (built, as in past tense)

**Comment by wouterjdb** [comment]
Testing now....

**Comment by markusdregi** [comment]
@wouterjdb `MAX_RUNNING` is limiting the number of concurrent jobs ;) I think what you are after is `MAX_RUNTIME`

**Comment by wouterjdb** [comment]
Yes, that's what I have....  (Just change the title, that's wrong)

**Comment by markusdregi** [comment]
Alright!

**Comment by ManInFez** [comment]
Then the problem is probably not fixed in the current master :laughing:

**Comment by wouterjdb** [comment]
> Then the problem is probably not fixed in the current master 😆

I was already afraid you were going to say that....

**Comment by wouterjdb** [comment]
In the meanwhile I'm getting into compilation errors... so hold on to your hats. 🎩

**Comment by jondequinor** [comment]
@wouterjdb, could you attach a `jobs.json` file for a job that was produced using a config with `MAX_RUNTIME`? You'll find one in your runpath for some `real_/iter_/…`.

**Comment by wouterjdb** [comment]
@jondequinor I will.... by the time I managed to get my environment back and can do a run again.... 😉

**Comment by wouterjdb** [comment]
**ERT Config snippit:** (MAX_RUNTIME = 10 seconds)
```
NUM_REALIZATIONS 10
MIN_REALIZATIONS 40%
MAX_RUNTIME 10
STOP_LONG_RUNNING TRUE
ITER_COUNT 10

--QUEUE_SYSTEM LOCAL
--QUEUE_OPTION LOCAL MAX_RUNNING 1

--Use the LSF cluster to run simulations
QUEUE_SYSTEM LSF
LSF_SERVER st-grid01
QUEUE_OPTION LSF LSF_QUEUE mr
QUEUE_OPTION LSF MAX_RUNNING 200

```

**All simulations running after one minute:**
![image](https://user-images.githubusercontent.com/9119793/69712624-6da00880-1103-11ea-9e0b-2de3c958ecb1.png)

Snippit from jobs.json (guess this is the part you want to know, and it is the same for all three jobs in my workflow):

```
  "environment" : null,
  "exec_env" : null,
  "license_path" : null,
  "max_running_minutes" : null,
  "max_running" : null,
  "min_arg" : null,
  "arg_types" : [],
  "max_arg" : null
```

**Comment by wouterjdb** [comment]
Doesn't look very promising with all `null `and `[]` values.....?

**Comment by ManInFez** [comment]
Yes, it looks like the value is not propagated through to the jobs.json file, which is where the executor is looking. We will look into it. As for the moment, if MAX_RUNTIME is crucial, check out the latest stable release of ERT. Should be tag 2.5.3.

**Comment by wouterjdb** [comment]
> Yes, it looks like the value is not propagated through to the jobs.json file, which is where the executor is looking. We will look into it. As for the moment, if MAX_RUNTIME is crucial, check out the latest stable release of ERT. Should be tag 2.5.3.

OK - will try 2.5.3

**Comment by ManInFez** [comment]
Make sure you also use the corresponding libres and libecl versions!

**Comment by wouterjdb** [comment]
Thanks for the tip.

**Comment by wouterjdb** [comment]
Just quickly checked, but 2.5.3 is far too long ago for us. We are relying on the `es_mda` command line interface. We'll have to find some other version then that has the support - but not the error. Not sure which one that is though at this point.

**Comment by markusdregi** [comment]
> We'll have to find some other version then that has the support - but not the error. 

I'm pretty sure that would be the empty set of versions to be honest. I think you best bet is to wait until the issue is resolved. We are prioritising this high as we want to get a release out soon...

Thanks a lot for the feedback. We'll keep the issue updated.

**Comment by ManInFez** [comment]
It is possible to define a maximum run time for individual jobs in the job config.
E.g.:
POLY_EVAL 
```
EXECUTABLE poly_eval.py
MAX_RUNNING_MINUTES 1
```

will be killed after 1 minute

**Comment by markusdregi** [comment]
It it is the global one that is used, because they want to use the standard eclipse job, yet kill it if it spends to long time...

**Comment by markusdregi** [comment]
https://github.com/equinor/ert/issues/577 stems from the same user report.

**Comment by wouterjdb** [comment]
I still, randomly it seems, get jobs that are never killed. I've set the `MAX_RUNTIME` to 300 seconds, but the following is the status on my run:

![image](https://user-images.githubusercontent.com/9119793/73076132-c7337200-3ebd-11ea-972a-e68438168e91.png)

Where the submit time of those two runs are (time of writing: 15:26):

![image](https://user-images.githubusercontent.com/9119793/73076173-db776f00-3ebd-11ea-8ca2-27ac5d865f64.png)

I **will** have to kill them manually now otherwise nothing will happen......

**Comment by wouterjdb** [comment]
Some further investigation actually shows that one of the realizations that has this problem has in fact simulated the case successfully with OPM Flow (the simulation is done, and successful) but the STATUS file shows no end date/time of that job.

**Comment by wouterjdb** [comment]
Also, in the jobs.json file I see for all jobs: 

`"max_running_minutes" : null`

**Comment by ManInFez** [comment]
I am not sure why it is not working, but to clearify "max_running_minutes" is not the same as MAX_RUNTIME. MAX_RUNTIME in the config file is regulating the run time for a realization, max_running_minutes operates on single forward model jobs.

**Comment by ManInFez** [comment]
Which version of libres are you now using? Where the status of the jobs on LSF "running"? MAX_RUNNING will not start timing the job until the job is reported as running on LSF

**Comment by wouterjdb** [comment]
OK - my bad on that point. I wasn't aware that these two were not the same thing.

However, that unfortunately does not yet explain why I'm getting into the situation of "ghost jobs" living forever.

I tried to run again a large ERT setup again during the weekend and both when using RGS and the "LOCAL" queue I ended up with two realizations in the "running" state forever. Interestingly, when running on RGS I have the opportunity to kill the job simply by running "bkill xxxxx". I was a bit in the dark what to kill when running in "LOCAL"; so I did not manage to go to the next iteration.

**Comment by markusdregi** [comment]
That adding the `OK` file does not work is no surprise as ERT does not look for it before the script is reported to have terminated. Could you please ensure that you are on the latest versions of libres and ERT, as fixes have been done on this code recently?

Is it still OPM being reported as not finishing? If so, are you using the default OPM-job or a custom one?

**Comment by wouterjdb** [comment]
I'm on version 2.8.a2 - which should include the recent change with respect to MAX_RUNNING.

**Comment by wouterjdb** [comment]
I create the "FLOW" job as follows:

https://github.com/equinor/ddpd-flownet/blob/cc7ca9cdb5b85f73e1886071d7f314dfde9cafd4/build_environment.sh#L154-L176

**Comment by wouterjdb** [comment]
During the night I had another go at running a full ensemble. Again, I had to manually kill a few jobs to get further in the iterations. This morning it was stuck again as follows:

![image](https://user-images.githubusercontent.com/9119793/73247058-61423580-41b0-11ea-8595-c154f2d72fdc.png)

Running bjobs reveals that there is in fact only 1 realization that is running:

![image](https://user-images.githubusercontent.com/9119793/73247267-cbf37100-41b0-11ea-8a8e-e9316834fa57.png)

Looking up the details it turns out that this is realization 722. In the JOB_LOG I see that the jobs were restarted once - and the last job that was called is OPM Flow (there is some deletion job afterwards which was not called anymore). The simulation in fact fully succeeded, but still the `.LSF-stdout` reports an `TERM_EXTERNAL_SIGNAL`:

![image](https://user-images.githubusercontent.com/9119793/73247753-e843dd80-41b1-11ea-951b-17f9bf47fd1b.png)

**Comment by markusdregi** [comment]
@ManInFez & @wouterjdb: Do you know if this is still an issue?

**Comment by wouterjdb** [comment]
Haven't been running on LFS for nearly a year.... Not sure if this is still an issue.

**Comment by markusdregi** [comment]
Thanks for the update @wouterjdb!

**Comment by markusdregi** [comment]
Closing the issue due to inactivity.
