### ISSUE TITLE
Rephrase from simulation to experiment

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#5771]
**Describe the issue**
ERT runs experiments, which is one or more simulation (eclipse), and this is still misleadingly called simulation.
#5746 removed the link between the user interface and the program by using "Experiment" ("Run Experiment") instead of "Simulation" ("Start Simulation") in buttons and labels.
This broke the obvious link between the UI and the logic, and should be fixed!
Update the rest of the code to use "experiment" where it is appropriate (comments, variable names, methods, etc.)

**Comment by jonathan-eq** [comment]
I am not familiar enough with ERT to know where the line between experiment and simulation goes, but I will give it a try!

**Comment by oyvindeide** [comment]
Think this has mostly been completed now, feel free to reopen if it has not happened everywhere.
