### ISSUE TITLE
Move data loaders from libres into ERT data API

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#581]
- `GenDataCollector`
- `PlotBlockDataLoader`
- `SummaryCollector`
and any other data loaders should be moved from libres into ERT's data API.

Rationale:
`PlotBlockDataLoader` pertains to plotting, which belongs in the ERT domain.
`SummaryCollector` is exclusively used by the CSV export (an ERT feature).
`GenDataCollector` is exclusively used by the RFT export (an ERT feature?).

**Comment by markusdregi** [comment]
I suggest we carry out #1563 first 👍🏻

**Comment by oyvindeide** [comment]
I am closing this as the merge between `ert` and `libres` has happened, and we are likely to do a larger refactor of the data structure in ert.
