### ISSUE TITLE
Not all observations are shown in the gui

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5816]
For a group of summary observations, only one of the observations are plotted in the ert gui plot window. This can be reproduced using https://github.com/equinor/fmu-drogon. An example of the observation file for Drogon where there are 9 observations with the KEY WGOR:A1. Seemingly from the update log they are all active in the update step. 

![the key in config](https://github.com/equinor/ert/assets/32731672/885b5ca3-8a67-42fe-8836-d4c42e75073b)
![only one shown](https://github.com/equinor/ert/assets/32731672/fa319541-4005-4ed7-bd0f-356bf6c42140)

**Comment by DanSava** [comment]
Are the images generated using main or the latest stable release?

**Comment by oyvindeide** [comment]
This has been fixed in: https://github.com/equinor/ert/commit/d9f72f657e7a72c8390bb6143642ee665c95d802, will back port this to version 5.0
