### ISSUE TITLE
CSV export should be possible using CLI

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#589]
It seems like the CSV export workflow requires `ert.gui` to function. It needs to be callable from the CLI.

**Comment by eivindjahren** [comment]
Just tried the following:

1. Add file `wf` to `test-data/snake_oil` containing the line `CSV_EXPORT test.csv`
2. Add `LOAD_WORKFLOW wf` to `snake_oil.ert`.
3. Ensure that there is at least one ensemble in storage for snake_oil.
4. Run `ert workflow wf snak_oil.ert`

And this succeeds so I am closing the as solved.
