### ISSUE TITLE
Refactor gui snapshot handling after rewrite in ensemble evaluator

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5908]
**Describe the bug**
The work on #5273 done in #5828 causes one test to timeout rather reliably:
```
tests/unit_tests/gui/simulation/test_run_dialog.py::test_large_snapshot
```
and another to fail less reliably, but still observable:
```
tests/unit_tests/gui/test_full_manual_update_workflow.py::test_that_the_manual_analysis_tool_works
```
(cf. [github workflow run for the latter](https://github.com/equinor/ert/actions/runs/5887771103/job/15967796004))

We suspect that our rewrite of the snapshot inside ensemble evaluator makes the calls used in the gui to handle (partial) snapshot update events more expensive time-wise.

there is an obvious way of refactoring the gui to

- decouple the gui interpretation of snapshot events from the ensemble evaluator snapshot's internal structure
- make the calls used less expensive

this might also alleviate some of the problems reported by users and experience by us, where the gui lags behind actual realization and forward model state by up to several hours(!)

**Comment by jonathan-eq** [comment]
Blocked by https://github.com/equinor/ert/issues/6252
