### ISSUE TITLE
New observations parser does not handle "include"

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5931]

**Comment by oysteoh** [comment]
@oyvindeide / @sondreso  this is a breaking change notified by one user ( i think released in 2023.06 - correct me if i'm wrong @eivindjahren ) . Should we make an announcement for the users / add it to the release docs / post a message on slack... ?

**Comment by eivindjahren** [comment]
I think adding to doc and the next announcement we make should suffice.
