### ISSUE TITLE
Allow for capitalized GRDECL extension in FIELD keyword

### ISSUE THREAD

**Issue by geirev** [equinor/ert#5950]
**Is your feature request related to a problem? Please describe.**
It is quite common to use capitalized file names in Eclipse models, but filenames with capitalized ".GRDECL" extensions are no longer supported in ert.

**Describe the solution you'd like**
I think it is easier to allow ert to use field definitions like
FIELD PORO  PARAMETER PORO.GRDECL  INIT_FILES:<PRIDIR>/Poro/PORO_%d MIN:0.001234
then to update the file names and input statements in multiple eclipse models.

![Screenshot from 2023-08-22 13-43-38](https://github.com/equinor/ert/assets/22790296/4e2c83a0-013e-496c-965c-abddbb3b31af)

**Comment by dafeda** [comment]
Thanks Geir, this makes sense I think.
