### ISSUE TITLE
Overburden time shift

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#596]
We need to check whether this is possible to make open. A lot of the logic is already in _libecl_.

**Comment by jondequinor** [comment]
What is overburden time shift?

**Comment by markusdregi** [comment]
It is the movement of the seabed over time while the reservoir is depleted, which again is used as observations when history matching our models. The top level scripts currently resides in: https://github.com/equinor/ert-statoil/tree/master/ert_statoil/ots.

I just sent the emails to figure out whether we can open source this.

**Comment by markusdregi** [comment]
This is to be open.

**Comment by markusdregi** [comment]
Note: The current OTS code depends on the config parser from libres. We will probably have to support this for some time, but we should design a new format based on yaml that can be the main source of configuration.

**Comment by xjules** [comment]
There is a particular file required for `test_ots_reservoir.py` test,  is it possible to find it?
`OTS/upscaled_model_28x61x35/SYNC_150109_28x61x35.EGRID`

**Comment by xjules** [comment]
> There is a particular file required for `test_ots_reservoir.py` test, is it possible to find it?
> `OTS/upscaled_model_28x61x35/SYNC_150109_28x61x35.EGRID`

Have decided to analyze some default libres `test-data` grids.
