### ISSUE TITLE
STEA

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#597]
Move job from ERT-Statoil and Spinning Jenny.

**Comment by markusdregi** [comment]
This makes no sense to have open

**Comment by xjules** [comment]
> This makes no sense to have open source. But maybe it does? Because I have realised that stea is open.

I think we can make it open-source since anybody having the stea account can make use of it.

**Comment by lars-petter-hauge** [comment]
How does this impact our environment - since we then have three jobs doing the same thing. Just adding without removing sounds like.. cause of issues

**Comment by markusdregi** [comment]
The one in spinning Jenny should disappear I guess? ERT-Statoil will only be present in our Python 2 deploys and semeio only in the Python 3 deploys, so that should be good no?
