### ISSUE TITLE
Back up jobs.json when running in existing runpath

### ISSUE THREAD

**Issue by erlid** [equinor/ert#5989]
**_Is your feature request related to a problem? Please describe._**
Problem: It is hard to track down history behind content on `<RUNPATH>` when user has run some sort of post-process ERT simulation in existing `<RUNPATH>` bacause `jobs.json` gets over-written

**_Describe the solution you'd like_**
Make ERT create a back-up of `jobs.json` when running in existing runpath - just like current version does for `parameters.txt`

**_Describe alternatives you've considered_**
N/A

**_Additional context_**
Applicable when jobs.json changes e.g. when user run some sort of post-processing simulation with ERT on existing <RUNPATH>

**Comment by oyvindeide** [comment]
I think we ideally want to present this context of what has run in a better way (through the GUI for example), but as long as we don`t have that solution I agree that ERT should be consistent in the way it treats the job files, and that we should back up `jobs.json` as well. For context, the code is here: 

https://github.com/equinor/ert/blob/6695973937b784b4185edb86afba505a674bbdd6/src/ert/enkf_main.py#L367-L367

so we do the same as `parameters.txt`: https://github.com/equinor/ert/blob/6695973937b784b4185edb86afba505a674bbdd6/src/ert/enkf_main.py#L57
