### ISSUE TITLE
DESIGN_KW

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#599]
This can be open

**Comment by oysteoh** [comment]
@eivindsm, @markusdregi 

`design_kw` consists of two parts as i see it - `run_design_kw.py` and `run_design2param.py`

`run_design_kw.py` is only doing template rendering which already exists in libres. Should we make use of what is already available when doing the python3 version and force users to update their jobs ? Or - should we port and immediately deprecate and tell users to migrate? Or what to do?

**Comment by eivindsm** [comment]
In the long run we need to support running ensembles based on DEO matrices naively. At this time we should make sure things fly with py3. I would argue that the two parts should remain to ensure to limit impact for our users. Maybe @berland has an opinion on the matter?

**Comment by berland** [comment]
Yes, we are not ready to refactor this, DESIGN_KW forward model must live as is in Python 3.

**Comment by markusdregi** [comment]
I vote for keeping as is now and then as soon as we have a better alternative available we start deprecating ;)

**Comment by oysteoh** [comment]
moving forward porting the design_kw job and making tests... i find the key replacement stuff a bit fluffy and we need to make it clear what is happening. extracting the parameters.txt from reek - i have the following example illustrating my question.

MULTFLT_F1 0.115187
MULTFLT:MULTFLT_F1 0.115187
LOG10_MULTFLT:MULTFLT_F1 -0.938597

as it is today, if you write <MULTFLT_F1> in a template-file, it will be replaced by 0.115187 - which is the value of the more specific MULTFLT:MULTFLT_F1. It's kinda difficult writing tests and logic towards this. Is it possible to require the use of full path to the keys, i.e MULTFLT:MULTFLT_F1 ? or is that maybe already in place for most templates ?we could ofcourse continue with just picking whatever specified in the template, but - the parameters.txt file is as i understand legacy and a replacement is already inplace - parameters.json. in this file, the ambigious key MULTFLT_F1 is removed and only the unambigious key's are present.

**Comment by berland** [comment]
See also #275

**Comment by oysteoh** [comment]
we decided to move forward keeping old logic and still use parameters.txt
