### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#600]
Unify CSV_EXPORT workflows in libres and ERT-Statoil. We should also talk to @berland about the FMU solution.

**Comment by markusdregi** [comment]
Open

**Comment by oyvindeide** [comment]
There are several different approaches to `CSV_EXPORT`, the main challenge with all of them is that they rely on a `path_file` to read eclipse data from the `run_path`. This is a problem as it's not compatible to how `ert` will work in the future. `CSV_EXPORT` should get it's data from the ert data api, which will allows us to get all data, not just summary data, and will work regardless of where ert is running. Before we implement `CSV_EXPORT` we should have a clear definition of how the `design_matrix` will be implemented so we don't have a lot of interim solutions. The design matrix should have a programmatic api so we don't have to rely on files.

**Comment by oyvindeide** [comment]
Depends on: #181

**Comment by oyvindeide** [comment]
In the future the behavior of the `libres` `CSV_EXPORT` should be kept, but should be integrated with the new data api and moved out of `libres` as it currently makes `libres` depend on `ert`, and the job is not properly tested.

**Comment by oysteoh** [comment]
As the new data api in ERT is beeing worked on, we initiate work on this task in parallel as it is a good thing designing an api with multiple consumers. The new CSV export will replace all other csv export from both ert-statoil and libres.

**Comment by oysteoh** [comment]
Depends on: #602

**Comment by markusdregi** [comment]
CSV export is now done with `CSV_EXPORT2`. Improvements to this might very well come, but that should be described in new issues...
