### ISSUE TITLE
flaky test: FAILED tests/unit_tests/config/test_ert_config.py::test_validate_job_args_no_warning - assert 2 == 0

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#6007]
we haz a flaky test - on a pr just changing some docs, cf. [github action run](https://github.com/equinor/ert/actions/runs/6021860222/job/16335569152?pr=6005) (unit tests macos)

**Comment by dafeda** [comment]
Got this error in a PR that only updates docs.

https://github.com/equinor/ert/actions/runs/6109269901/job/16580022914?pr=6057
