### ISSUE TITLE
Run History Matching Tutorial in deployed komodo Python 3

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#601]

**Comment by oysteoh** [comment]
Duplicate #488

**Comment by sondreso** [comment]
No HM and FMU tutorial are different things :slightly_smiling_face:

**Comment by sondreso** [comment]
This is blocked by scripts (create_relperm) in the tutorial that uses resscript. 
The inteded job tu use instead (create_relperm_pyscal) also has a bug (in pyscal) that is blocking the completion of this issue (https://github.com/equinor/pyscal/issues/65)

**Comment by markusdregi** [comment]
Apparently @eivindsm have some thoughts on how this should be resolved. We will discuss is during the planning 👍

**Comment by markusdregi** [comment]
Blocked by pyscal problems: https://github.com/equinor/pyscal/issues/66

**Comment by berland** [comment]
pyscal issue is resolved in git master.
