### ISSUE TITLE
MOVE_DIRECTORY forward model job

### ISSUE THREAD

**Issue by erlid** [equinor/ert#6060]
**Is your feature request related to a problem? Please describe.**
There are standard jobs for copying, deleting files and directories, but moving exists for files only.
![image](https://github.com/equinor/ert/assets/57486677/a7f1cac8-334e-4ff3-b6f1-b7946d952c41)

**Describe the solution you'd like**
`MOVE_DIRECTORY` as pre-configured job in ERT

**Comment by oyvindeide** [comment]
This seems like a good feature, we will add that as a built in job!
