### ISSUE TITLE
warnings are reported on mac with python 3.11

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6068]
The following test fails with mac python 3.11
```
FAILED tests/unit_tests/config/test_ert_config.py::test_validate_job_args_no_warning - assert 2 == 0
 +  where 2 = len(WarningsRecorder(record=True))
```

See logs here: https://github.com/equinor/ert/actions/runs/6119450127/job/16609540434

**Comment by jonathan-eq** [comment]
<frozen importlib._bootstrap>:241: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject.

**Comment by eivindjahren** [comment]
Did you resolve this @jonathan-eq ? I haven't seen the failure in a while and I see you have unassigned yourself from it.

**Comment by eivindjahren** [comment]
Seems like we don't test on mac 3.11 anymore so that might be it. I am rephrasing the issue.

**Comment by jonathan-eq** [comment]
I put this back because I could not get python3.11 to work locally, and I wanted to reproduce the context which the issue occurred in.

**Comment by eivindjahren** [comment]
We haven't seen this warning in a while and it is not clear what this issue is about anymore so I am closing it.
