### ISSUE TITLE
Status GUI for WORKFLOWs

### ISSUE THREAD

**Issue by berland** [equinor/ert#608]
After all FORWARD_MODELs are finished, nicely visualized and trackable in the GUI, ERT commenced with the workflows and its own post-processing. These may have an arbitrary run-time (some being user-written), (and emits log messages to the terminal window where ert gui was started). While this is ongoing, the "Simulations" modal window is spinning with "Post processing..."

I suggest some similar GUI as for the realizations forward models, where the status and potentially logs can be inspected.

**Comment by markusdregi** [comment]
Thanks for the input 👍 This is on the long-term agenda of propagating messages and statuses in ERT in general ;)

**Comment by sondreso** [comment]
While not entirely closed by https://github.com/equinor/ert/pull/3136, this at least solved most of the requested information in this issue. A better visualization and improvements beyond this requires some discussion around the concepts of workflows and experiments, so closing this as not actionable right now. See also: https://github.com/equinor/ert/issues/2985
