### ISSUE TITLE
Restart failed runs from last successful forward model component

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#609]
Ref yammer thread: https://www.yammer.com/statoil.com/#/threads/inGroup?type=in_group&feedId=7932201&view=all

I propose that we implement support for restarting failed runs from the last successful forward model component. This could be used both in batch runs ( during eg ES-MDA) and from the GUI.

**Comment by markusdregi** [comment]
I think this is a good idea 👍

**Comment by jondequinor** [comment]
Closed and moved into https://github.com/equinor/ert/issues/1250 as a fundamental design goal.
