### ISSUE TITLE
error when using eclipse 2023.1

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#6097]
**Describe the bug**
From Mohsen Dadashpour on Yammer:
> I tried to change the eclipse version from 2021.3 to 2023.1. But when I am running ERT in prediction phase ERT stops with Error in eclipse 
> 
> <time>10:44:38</time>
> <job>ECLIPSE100</job>
> <reason>Process exited with status code -7</reason>
> <stderr>
> <Not written by:ECLIPSE100>
> </stderr>
> 
> But when I checked the PRT file I see that Eclipse already finished without any error.
> Any Idea why this happens?
> 

see:
https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjQwMjQ2MjE3OTAxNjcwNCJ9

**To reproduce**

**Expected behaviour**
eclipse 2023.1 should run successfully

**Environment**
 - RHEL7
 - komodo version 2023.06.06-py38
 - py38
 - Remote/HPC execution involved: yes

**Comment by berland** [comment]
Tried to reproduce with hm-tutorial, but both `VERSION=2021.3` and `VERSION=2023.1` works fine.

**Comment by berland** [comment]
Awaiting new information in Yammer thread to see if this is an Ert related problem. If not, close within a few days.

**Comment by berland** [comment]
Closing, probably not an error on ERTs side.
