### ISSUE TITLE
Default version for forward model ECLIPSE100 does not work

### ISSUE THREAD

**Issue by berland** [equinor/ert#6104]
**Describe the bug**
If the ert configuration file contains
```
FORWARD_MODEL ECLIPSE100
```
and not
```
FORWARD_MODEL ECLIPSE100(<VERSION>=2021.3)
```
then ERT will fail when the job_runner gets to the Eclipse job, and the user has to dig into `ECLIPSE100.stderr.15` to find the error message
```
<traceback snipped>
ValueError: The default version has not not been set in the config file:/prog/res/komodo/2023.06.11-py38-rhel7/root/lib/python3.8/site-packages/ert_configurations/resources/ecl100_config.yml
```

**Expected behaviour**
Since the documentation does not state that `VERSION` is a mandatory argument, it should pick a default version. If the argument should be made mandatory, the documentation should state it, and optinally the config validation code should tell the user immediately that this will not work.

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2023.06
 - Python version: 3.8
 - Remote/HPC execution involved: no

**Comment by sondreso** [comment]
This should be fixed by making `<VERSION>` a required argument.

**Comment by andreas-el** [comment]
Possibly relates to #6495
