### ISSUE TITLE
MAX_RUNTIME kills runs that are pending on LSF

### ISSUE THREAD

**Issue by wouterjdb** [equinor/ert#612]
I observed that setting a `MAX_RUNTIME` actually kills runs that are still at the "pending" status on LSF - is that by design?

This makes it hard to control the "flow of simulations" with the `MAX_RUNTIME` keyword when the LSF system is busy as some (many in my case, due to a relatively short `MAX_RUNTIME`) runs will fail before they even start.

**Comment by markusdregi** [comment]
Thanks for reporting @wouterjdb. That is probably not the intended behaviour no. We'll have a look...

**Comment by markusdregi** [comment]
If still a problem this should be possible to reproduce and test using the work in https://github.com/equinor/ert/pull/1849.

**Comment by ManInFez** [comment]
This is no longer an issue, timer is not started before job reports as running. Tested with mocked bjobs
