### ISSUE TITLE
Unpin setuptools-scm

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6125]
**Describe the bug**
The version.py generated by  setuptools-scm got miss-malformed for version setuptools-scm==8. Check here:
https://github.com/equinor/ert/actions/runs/6247503552/job/16960301138?pr=6118
```sh
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ert/shared/__init__.py:2: in <module>
    from ert.shared.version import version as __version__
E     File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ert/shared/version.py", line 4
E       __version__ : str = version : str = '7.0.0b1.dev114+gb1e9c3d30'

```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install setuptools-scm==8.0.0`
2. `pytest`

**Expected behaviour**
Should work

**Comment by oyvindeide** [comment]
WIll be fixed in a few minutes: https://github.com/pypa/setuptools_scm/issues/905, closing
