### ISSUE TITLE
MeasureData-related tests on bleeding

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#613]
See https://ci.statoil.no/be/job/ert-komodo-pipeline/293/console
`tests/data/test_measured_data.py FFF......FFFFFFFFFFF....FF              [ 48%]`
Example error:
```
>       assert md._data.equals(expected_result)
E       assert False
E        +  where False = <bound method DataFrame.equals of     test_key   \n           1  2\nOBS        2  3\nSTD        5  6>(           test_key     \nkey_index         1    2\ndata_index        1    2\nOBS             2.0  3.0\nSTD             5.0  6.0)
E        +    where <bound method DataFrame.equals of     test_key   \n           1  2\nOBS        2  3\nSTD        5  6> =     test_key   \n           1  2\nOBS        2  3\nSTD        5  6.equals
E        +      where     test_key   \n           1  2\nOBS        2  3\nSTD        5  6 = <ert_data.measured.MeasuredData object at 0x7f884c19d110>._data

```

Was the tests not changed after `key_index` and `data_index` were introduced?

**Comment by oyvindeide** [comment]
Looks like those tests from the master branch is being run against an older version of ert, which makes sense since bleeding hasn't run since this was merged. Should fix itself once bleeding builds.

**Comment by oyvindeide** [comment]
This was because the tests being run where out of sync with the komodo version.
