### ISSUE TITLE
After clicking `Kill realizations` realizations with state `Waiting` are submitted before being stopped.

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6134]
After executing `Kill realizations`, ERT spends time on submitting realizations of state Waiting before it kills them. Would be nice if ERT could just avoid submitting the Waiting - and focus on killing the pending and running realizations.

Some context here:
https://github.com/equinor/ert/blob/main/src/clib/lib/include/ert/job_queue/job_status.hpp

**Comment by xjules** [comment]
This might be already solved by the new Scheduler Queue system.

**Comment by xjules** [comment]
Can this be closed @oyvindeide ?

**Comment by berland** [comment]
This is solved in the new Scheduler. The "Waiting" state is the implicit state in `job.py` before it is submitted, and if the time in waiting is nonzero, it is awaiting "sleep_until_we_can_submit". When kill is clicked, all job tasks are cancelled from scheduler.py, and this await will be cancelled and the realization killed.
