### ISSUE TITLE
Ert does not notify missing remote login keys

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6141]
Running ert in drogon first time on rgs node has all jobs in waiting. After waiting for 20 minutes, we tried running bqueues and bjobs in terminal, only to be met by "Cannot find your passwordless remote login keys (in /private/USER_GOES_HERE/.ssh/authorized_keys)"

**Comment by jonathan-eq** [comment]
Also, not sure if related, but running in azure did not work without 'PBS_SERVER=s268-lcjm'

**Comment by xjules** [comment]
We should at least implement a "clever" retry in the new LSF driver, which check the correct exit code and look up the error message.

**Comment by berland** [comment]
When .ssh is not present, bjobs and bsub (in /global/bin) will give these error messages (and exit code 1)
```
[havb@be-lx139213:~]$ mv .ssh dot-ssh
[havb@be-lx139213:~]$ bjobs
bjobs: Cannot find your passwordless remote login keys (in /private/havb/.ssh/authorized_keys)
bjobs: You will need to run /prog/LSF/script/setup-ssh-keyauth
bjobs: or open a service ticket for assistance. Please include this message
[havb@be-lx139213:~]$ bsub "sleep 10"
bsub: Cannot find your passwordless remote login keys (in /private/havb/.ssh/authorized_keys)
bsub: You will need to run /prog/LSF/script/setup-ssh-keyauth
bsub: or open a service ticket for assistance. Please include this message
```

**Comment by berland** [comment]
This problem is solved by https://github.com/equinor/ert-configurations/pull/88

For legacy driver in komodo bleeding we get the terminal spammed with:
```
Failed to get lsf job id from file: /tmp/enkf-submit-f2zDAc
bsub command                      : bsub
bsub: Cannot find your passwordless remote login keys (in /private/havb/.ssh/authorized_keys)
bsub: You will need to run /prog/LSF/script/setup-ssh-keyauth
bsub: or open a service ticket for assistance. Please include this message
```

For scheduler, we get after some seconds Ert failing all realizations with one message pr. realization:
Experiment failed with the following error: Experiment failed! All realizations failed!
```
Command "/global/bin/bsub -q mr -J poly_lsf.ert-0 /private/havb/projects/ert/test-data/poly_example/poly_out/realization-0/iter-0/.lsf_submit_mix4btsi.sh /private/havb/projects/ert/test-data/poly_example/poly_out/realization-0/iter-0" failed with exit code 1 and error message: bsub: Cannot find your passwordless remote login keys (in /private/havb/.ssh/authorized_keys)
bsub: You will need to run /prog/LSF/script/setup-ssh-keyauth
bsub: or open a service ticket for assistance. Please include this message
```
