### ISSUE TITLE
`ert.storage`: Datasets don't load if they're missing in at least one realisation

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#6163]
**To reproduce:**
1. Run poly_example
2. Observe that the plot displays data
3. Delete `POLY_RES.nc` in any of the realisation directories in `storage/`
4. Observe that the plot is missing for POLY_RES entirely

**Desired outcome:**
Ert shows the remaining 99 `POLY_RES` realisations.

**How to solve (maybe):**
If the data for any of the realisations is missing, storage throws a `KeyError`. Perhaps we can relax this and instead fill in the missing realisation with `NaN`? 

https://github.com/equinor/ert/blob/e28e2ebb166c83665c62a687fe1601b9841794b0/src/ert/storage/local_ensemble.py#L214-L215

**Comment by frode-aarstad** [comment]
The same is true for parameters if for some reason they should be also be deleted

**Comment by frode-aarstad** [comment]
Will be adressed in #6736
