### ISSUE TITLE
Avoid mentioning  "SortedList" to user in error message

### ISSUE THREAD

**Issue by berland** [equinor/ert#6170]
**Describe the bug**
The config parser correctly gives an error message stating:

`/private/havb/bigpoly/bigpoly.ert: Line 8 (Column 1-9): When configuring REPORT_STEPS:SortedList([0]) RESULT_FILES must be configured using %d`

but the string "SortedList" should not be in there, it will confuse users.

**Expected behaviour**
ERT should write back exactly what it found in the config file.

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: bleeding, 7.*
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Comment by adkbbx** [comment]
Hey there,
I'm intrested in contributing to this issue do let me know how I can help.

**Comment by larsevj** [comment]
It looks to me like this has already been fixed on bleeding by 14afd4a,
`/Users/LEVJE/Project/ert/test-data/poly_example/poly.ert: Line 16 (Column 1-9): When configuring REPORT_STEPS:[10] RESULT_FILES must be configured using %d`, 
do you concur @berland ?

**Comment by larsevj** [comment]
Seemingly fixed in 14afd4a.
