### ISSUE TITLE
Converting c-vector of datetimes to Python datetime is too slow for summary internalization

### ISSUE THREAD

**Issue by berland** [equinor/ert#6184]
A profiling of the "bigpoly"-case with a summary file with 50000 dates has revealed that this line takes up too much time:

https://github.com/equinor/ert/blob/5c24b07cf45aaa7a7a15fac32ce51b83d05fc856/src/ert/config/summary_config.py#L47

When (many) realizations finish at the same time, the code is heavy enough to starve the single process ERT has available for CPU resources. This adds to the "many realization issue". 

For the bigpoly case, the line takes an average of 20 seconds to pass. Minimum is 0.6 seconds (which is probably what you get when there is no CPU starvation at that particular moment in time). Maximum is 47 seconds.

**Comment by kwinkunks** [comment]
IDK if it does what you need or not, but `pandas.to_datetime(arraylike)` is 5&times; faster for me than looping over the array and doing `datetime.fromtimestamp(arraylike)`.

**Comment by xjules** [comment]
I thought about using multiprocessing (since the `c_time` is already loaded to memory):
```python
with Pool() as p:
        time_map = p.map(convert_to_datetime, c_time)
```

**Comment by berland** [comment]
> IDK if it does what you need or not, but `pandas.to_datetime(arraylike)` is 5× faster for me than looping over the array and doing `datetime.fromtimestamp(arraylike)`.

Pandas's `to_datetime()` is problematic here as it bails on dates past year 2262.

**Comment by pinkwah** [comment]
I would advise checking the performance of `multiprocessing.Pool`. For a vector of 50k I would be really surprised if spawning a number of _processes_ and then collecting is more performant than the naive approach.

**Comment by berland** [comment]
https://github.com/equinor/ert/commit/2cb020277821d3f5e91bc3f5189ce29a440fd994 (now reverted) was an attempt to optimize this code:

Similar test to that in the first post yields minimum time 0.06s and maximum time 1.46s, yielding a 10x speed increase.

**Comment by berland** [comment]
Profiling 
https://github.com/equinor/ert/blob/2cb020277821d3f5e91bc3f5189ce29a440fd994/src/ert/config/summary_config.py#L36-L69
on bigpoly (100 realizations) gives: 

| Operation      | Min time (seconds) | Max time (seconds) |
|----------------|-------------------|--------------------|
| Making `EclSum` object        | 0.76              | 6.72               |
| `read_dates()`     | 0.06              | 1.43               |
| `read_summary() `  | 0.18              | 1.74               |
|` summary_data.sort()`        | 0                 | 0.001              |
| `xr.Dataset()` + comprehensions  | 0.13              | 3.01               |
| `drop_duplicates()` | 0.0175            | 2.5                |

**Comment by JHolba** [comment]
520f3b5939f42e92500a6cc8fdc70d983776ed14 is now in main. it is a rewrite of 2cb020277821d3f5e91bc3f5189ce29a440fd994, using manual conversion to python datetime instead of pybind11's automatic one. on my local computer read_dates was about 30x faster than 
`c_time = summary.alloc_time_vector(True)
time_map = [t.datetime() for t in c_time]`
