### ISSUE TITLE
OpenPBS fills path with files

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#6189]
When running ERT in Azure, the config-path is filled with status-files like this image shows. Most of them are empty, unless something bad has happened.

Hans R. propsing we are adding this option to the PBS options
``` 
Since you can add PBS options in your config, the self service way is to add "-o /dev/null -e /dev/null"  
```
[documentation](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Flatisresearch.umn.edu.mcas.ms%2Fcreating-a-PBS-script%3FMcasTsid%3D28375&McasCSRF=4443686301a39c5f00644f629a4e927158ee49908741b3fb1eeb923b8a02ca90)

![MicrosoftTeams-image (6)](https://github.com/equinor/ert/assets/4184190/65c24fc6-be3c-4e81-bf38-021f0d29a2ed)

**Comment by berland** [comment]
These files being present should indicate that the user has set KEEP_QSUB_OUTPUT in their config,

https://fmu-docs.equinor.com/docs/ert/reference/configuration/keywords.html#torque-keep-qsub-output

**Comment by oysteoh** [comment]
I also getting these - haven't added anything in my config.... Surprised if Trine have added this in her config... 🤔

**Comment by oysteoh** [comment]
@andreas-el  do you see these files when you are running in Azure now?

**Comment by andreas-el** [comment]
> @andreas-el do you see these files when you are running in Azure now?

Yes. Most are empty, some have messages. Is the keyword set in the site-config perhaps?

**Comment by berland** [comment]
It is not present in `ert-configurations`.

**Comment by andreas-el** [comment]
```
s268-rgs0006.s268.oc.equinor.com
qsub version 23.06.06
PBS_SERVER=s268-lcjm
```

| Command        | Result           |
| ------------- |:-------------:|
| qsub myjob |  Output and error file |
| qsub -k eo myjob | None |
| qsub -k oe myjob | None |
| qsub -k n myjob | Output and error file |
| qsub -k o myjob | Error file |
| qsub -k e myjob | Output file |

To me it looks like the arguments and results are all inverted. I.e. you ask to keep output, but get error.
If you want to keep both, you get none etc.

**Comment by andreas-el** [comment]
Seems like identical behaviour on http://s034-lcatop01.s034.oc.equinor.com/
