### ISSUE TITLE
Torque driver behavior with NUM_CPU > 1 is not suitable for azure

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6192]
Having `NUM_CPU 2` and `QUEUE_SYSTEM TORQUE` you will by default get this error message: 
```
 Error in config, job's config requires 2 processing units, but config says NUM_CPUS_PER_NODE: 1, and NUM_NODES: 1, which multiplied becomes: 1 
```
The fix is to add `QUEUE_OPTION TORQUE NUM_NODES 2` or `QUEUE_OPTION TORQUE NUM_CPUS_PER_NODE 2` to your config, however this is unlikely to work well with azure.

**Comment by berland** [comment]
This is fixed in todays  `openpbs_driver.py`
