### ISSUE TITLE
test_that_get_machine_name_is_predictive is flaky/failing, at least on mac

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6194]
```
FAILED tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py::test_that_get_machine_name_is_predictive - AssertionError: assert 'localhost' == 'barfoo01.internaldomain.barf'
  - barfoo01.internaldomain.barf
  + localhost
```

https://github.com/equinor/ert/actions/runs/6326334522/job/17179843970?pr=6193

**Comment by berland** [comment]
On of these exceptions has probably happened:
```
    except (socket.gaierror, exception.DNSException):
        return "localhost"
```

**Comment by dafeda** [comment]
Got this one here:

https://github.com/equinor/ert/actions/runs/6379526008/job/17312259077?pr=6213

**Comment by berland** [comment]
I am trying to reproduce it in https://github.com/equinor/ert/pull/6202, when there is a reproduction there, it will shed (hopefully) shed some light on exactly what happens when this problem occurs, in order to deal with it correctly.
