### ISSUE TITLE
Property test gen_kw_config transfer functions

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#6198]
Currently the clamped normal is property tested, and `trans_derrf` soon. The others are untested, and would benefit from testing with e.g. hypothesis -- in particular well suited to test properties on functions related to probability.

**Comment by eivindjahren** [comment]
There are some really nice tests for these in `tests/unit_tests/config/test_transfer_functions`. Thanks! I will close this as resolved, but that shouldn't stop anyone from adding more ;)
