### ISSUE TITLE
Localisation job fails in komodo release 2023.06 and current version in call to RowScaling functions

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#6205]
ERT failes running the localisation job LOCALISATION_JOB implemented in semeio, but fails in code related to RowScaling.
The error indicates mismatch between expected input to the function and the actuall input to the function.
A test shows that it works for komodo release 2023.05 and earlier. This failure is reported by several users using localisation.

**To reproduce**
Steps to reproduce the behaviour:
1. Run A case in current komodo (2023.09.00) using the localisation workflow (LOCALISATION_JOB)

**Expected behaviour**
That it works as it did before komodo release 2023.06

**Screenshots**
![Capture](https://github.com/equinor/ert/assets/77153131/e6b9dbb3-e1e6-4f1a-ae84-14b146567aaf)
![Capture2](https://github.com/equinor/ert/assets/77153131/aa54d006-e1ad-41bf-ab07-25824e975be8)

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2023.09.00 and 2023.06.11
 - Python version
 - Run on Stavanger cluster

**Additional context**
Note it worked for komodo release 2023.05 and earlier.

**Comment by oddvarlia** [comment]
Probably due to the changes when ROFF format supply fields in float32 instead of float64, the RowScaling also must take float32 instead of float64

**Comment by oyvindeide** [comment]
Fix and deployed 👍
