### ISSUE TITLE
MAX_RUNTIME doesn't always work

### ISSUE THREAD

**Issue by wouterjdb** [equinor/ert#621]
I've observed multiple times now that 1 (or more I think?) simulations are not killed whereas `MAX_RUNTIME` dictates that they should be killed after 300 seconds (in my case).

Example: I'm running a thousand realizations. After a couple of successful iterations only 939 realizations are left. In iteration five, 1 simulation is never killed and keeps on running for ever and ever - stopping progress completely. (This is on LSF - I can force going to the next iteration by running `bkill #####`)

![image](https://user-images.githubusercontent.com/9119793/70975486-5329d100-20aa-11ea-8b9a-c31b97926d3d.png)

**Comment by markusdregi** [comment]
A fix to the `MAX_RUNTIME` keyword was merged at 3rd of December. Could you check which version you are currently running of _libres_? :)

**Comment by wouterjdb** [comment]
```
import res
>>> res.__version__
'2.4.git'
```

**Comment by markusdregi** [comment]
Yes, we are aware and have fixed it 👍 In the meantime, if you still have the GitHub repo around a commit hash or message would work...

**Comment by wouterjdb** [comment]
aa7150a563

**Comment by markusdregi** [comment]
Yeah, that should be fresh enough. We'll try to reproduce locally and keep you posted.
