### ISSUE TITLE
Add docstrings for ert classes and methods

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6238]
**The problem**
The ERT codebase is split into dozens of different classes, and for someone onboarding; it can be challenging to understand the purpose/intent/functionality of some of them as it is overwhelming. It does not help that there is no clear documentation of the hierarchy of classes, or how/if they communicate with each other. 

**The goal**
Each class should have a docstring that describes:
- The function of the class
- Where the class is used
- What problem it solves
- Potential challenges it can cause

**Describe alternatives you've considered**
It could also be useful to draw a diagram showing how the different classes interact with each other, or perhaps a data flow diagram. This could be difficult to illustrate as some say it would look like an "explosion at the spaghetti factory"

**Comment by oyvindeide** [comment]
I very much agree with the intention of this issue, but think it is unlikely that we will be able to this in one PR to close the issue, and should keep it in mind as we develop further.
