### ISSUE TITLE
Unify `load_parameters` and `load_response`

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6245]
First off, one is plural, the other is singular, this is technically a breaking change, but the is not yet part of the public api, so we can change one of them.

https://github.com/equinor/ert/blob/4aaa3124f64ec0bf59e4c5bc46ca4e22e2086f30/src/ert/storage/local_ensemble.py#L198

They also have a quite different implementation, though they are essentially doing the same thing. This should be unified.

**Comment by kvashchuka** [comment]
In the end, we want to have only one of those two functions, or am I misunderstanding this?

**Comment by oyvindeide** [comment]
No, we want to functions, as while they do much of the same under the hood, I think it makes sense to have two different end points. But the signature and behavior should be aligned. For example, `load_parameters´ will return an empty dataset while `load_response` will throw a `KeyError`, I think the latter is better for both (but I am biased as I implemented that).
