### ISSUE TITLE
Main progress bar out of sync with detailed progress

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6248]
**Describe the bug**
When realizations are waiting, they now show up as pending in the the detailed view, while they show up as waiting in the main progress bar. In this case, they have not yet been submitted, so the detailed view should show waiting.

This is a result of the jobs only having one waiting status, while ert/the queue system has two states:

Pending: submitted, not yet running
Waiting: not yet submitted

I.e. in cases where we dont know `waiting` or `pending`, we need to chose what the queue system is reporting.

<img width="1480" alt="image" src="https://github.com/equinor/ert/assets/44577479/93d17957-a7aa-4414-adfb-fee36bd81003">

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui snake_oilt.ert`
3. Run ensemble experiment

**Comment by andreas-el** [comment]
Could the progress bar rely on information from the queue? This feels similar to what we already fixed in the realisation boxes, where the outside border held the queue status, while the dots/squares inside show status for individual jobs.

**Comment by oyvindeide** [comment]
> Could the progress bar rely on information from the queue? This feels similar to what we already fixed in the realisation boxes, where the outside border held the queue status, while the dots/squares inside show status for individual jobs.

Not sure I fully understand what you mean? The progress bar is showing the queue, yes. This issue is related to the fix for the outside boxes and the internals of the boxes, as now non-submitted and submitted apparently have the same status in the detailed view. A fix would be that if the individual jobs are showing pending, but the queue system is waiting, the color should be that of waiting, instead of pending as it is now. It is interesting for the users to see if the job has been submitted to the cluster, but not yet started, or if it has not been submitted.
