### ISSUE TITLE
Create diagram illustrating class/component interaction in ERT experiment

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6252]
**The problem**
It is difficult visualizing and understanding ERT when it is split into dozens of classes which seemingly all call one another somehow.

**A potential solution**
A dataflow diagram showing how an experiment is run and in what order the components/classes are ran

**Comment by jonathan-eq** [comment]
Putting this on hold for a bit, so I can revisit it with fresh eyes.

**Comment by oyvindeide** [comment]
Think I will close this issue as it looks a bit stale, and think it will be hard to keep something like this up to date if implemented.

**Comment by jonathan-eq** [comment]
^It is a bit stale now, but the main idea is still there. I think it would be good to have this available for onboarding new team members.

**Comment by jonathan-eq** [comment]
> Think I will close this issue as it looks a bit stale, and think it will be hard to keep something like this up to date if implemented.

It is a bit stale now, but the main idea is still there. I think it would be good to have this available for onboarding new team members.
