### ISSUE TITLE
job_queue_node test is flaky, interferes with qstat-proxy

### ISSUE THREAD

**Issue by berland** [equinor/ert#6265]
The test in

https://github.com/equinor/ert/blob/dfa7316ba6846790391b01e20f021ccb72bcc795/tests/unit_tests/job_queue/test_job_queue_node.py#L191

is flaky as in https://github.com/equinor/komodo-releases/actions/runs/6451269586/job/17512121821

The error is claimed to be reproducible with

`@reproduce_failure('6.83.0', b'AAAAAgABAAAAAA==')
`
but that is not enough. There is interference with qstat_proxy in this error, could be other parallel test runs.

**Comment by eivindjahren** [comment]
Should we just drop the test for torque for now?

**Comment by berland** [comment]
Reproducible with 

```
$ pytest tests/unit_tests/job_queue/test_job_queue_node.py::test_submitting_updates_status -sxv --count 100
...
tests/unit_tests/job_queue/test_job_queue_node.py::test_submitting_updates_status[84-100] PASSED
tests/unit_tests/job_queue/test_job_queue_node.py::test_submitting_updates_status[85-100] ** Warning: failed to get job status for job:1 from file:/tmp/ert-qstat-std-128507-665220
FAILED
```
