### ISSUE TITLE
Running `Ensemble Experiment` with `Iteration` set to `2` crashed ERT.

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#6267]
**Describe the bug**
Running `Ensemble Experiment` with `Iteration` set to `2` crashed ERT.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run `Ensemble Experiment`

`ValueError: Phase must be integer between (inclusive) 0 and 1`

**Expected behaviour**
I ran the same thing using 2023.06.11-py38 and it works.
ERT just ignores the fact that I set Iteration to 2 and sets it back to 0 before running.
Not sure if this is the exact behaviour we want, but ERT should not crash.

**Environment**
 - OS: macOS
 - ERT/Komodo release: main
 - Python version 3.10
 - Remote/HPC execution involved: no

**Comment by oyvindeide** [comment]
>  ERT just ignores the fact that I set Iteration to 2 and sets it back to 0 before running.

In that case, what did the run path look like? Did it run in `iter-0` or `iter-2`? If `iter-1` the previous behavior is buggy.

**Comment by andreas-el** [comment]
This issue seems to be resolved in PR https://github.com/equinor/ert/pull/6471
