### ISSUE TITLE
Improve forward init documentation

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#628]
In the list of configuration keywords, there is a description of the option `FORWARD_INIT`. This option allows for parameter values to be sampled by the forward model instead of by ERT. The documentation is lacking on the behavior relative to the values in storage; as what is really happening is that if ERT has values, those will be dumped to the runpath, and if not, it will read those from the runpath after the forward model finishes. However, if you change your runpath and "case" in the config file, but not your storage case, you will end up with the same parameter values but different RMS seed.

**Comment by sondreso** [comment]
Closed by #666
