### ISSUE TITLE
ERT will kill realizations in ensembles with spread in runtime

### ISSUE THREAD

**Issue by berland** [equinor/ert#6287]
Due to 

https://github.com/equinor/ert/blob/e090a8a11d9e6fc32bfc11ddae2e5d8375368c09/src/ert/job_queue/queue.py#L51

and

https://github.com/equinor/ert/blob/e090a8a11d9e6fc32bfc11ddae2e5d8375368c09/src/ert/job_queue/queue.py#L454-L456

ensembles with some spread in runtimes for each realization (that is not unthinkable, they might be doing differnent things, say a prediction run with different schedules controlled through a design matrix) will have the long-running members killed, without it being possible for the user to control through the configuration file.

This feature should be either configurable, or removed. Users can already set their limit for long-running jobs through the MAX_RUNTIME configuration key.

**Comment by berland** [comment]
Feature was added in https://github.com/equinor/ert/commit/16156b9978fb717d5b17f3e9575fc6c12ff08236

**Comment by sondreso** [comment]
This should only be activated if STOP_LONG_RUNNING is set to True: 

https://github.com/equinor/ert/blob/e090a8a11d9e6fc32bfc11ddae2e5d8375368c09/src/ert/ensemble_evaluator/_builder/_legacy.py#L202-L211

**Comment by berland** [comment]
Right, and it should be False by default, thus this feature is indeed user configurable.
