### ISSUE TITLE
Update workflow_runner to new libres API using context manager

### ISSUE THREAD

**Issue by xjules** [equinor/ert#629]
Workflow_runner can be initiated via context manager as follows:
```python
with WorkflowRunner(workflow) as workflow_runner:
            self.assertTrue(workflow_runner.isRunning())
```
Relates to https://github.com/equinor/libres/pull/806

**Comment by sondreso** [comment]
@xjules Could you add some context to this issue if it's still relevant?

**Comment by xjules** [comment]
> @xjules Could you add some context to this issue if it's still relevant?

I don't think it's relevant anymore, i.e., when I've checked it's used as a context manager. So closing this one.
