### ISSUE TITLE
Investigate usability of Linux C-groups

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6295]
We should answer the following questions:
- Do normal users have access?
- Memory specs for the C-group - will it raise warning if we exceed the memory cap?

**Comment by hansrune** [comment]
My comment was probably not saved.... C-groups can be used in both LSF, OpenPBS and SLURM to govern per node memory consumption. Whether you want to enforce / kill jobs that exceed requested (or default) limits is configurable 
Memory requirements are also used for job placement, so still useful for best possible utilization of nodes -  even with no  enforcement. IMO - enforcement is a last resort. Downside today with no enforcement , is that a bad job can grow beyond limits and cause OOM kill for a the largest memory job on the same node.

**Comment by xjules** [comment]
Closing this issue as it is not relevant anymore.
