### ISSUE TITLE
Remove pyrsistent as dependency

### ISSUE THREAD

**Issue by berland** [equinor/ert#6324]
Pyrsistent is listed as a dependency, but its usage is now reduced to this line:

https://github.com/equinor/ert/blob/400a12ad7e2f2b15aa01107c2cf98fd088e96285/src/ert/gui/model/snapshot.py#L273

which makes a deep dictionary copy of something that is already a dictionary (its argument was previously a pyrsistent object).

The only other usage of pyrsistent is in src/ert/serialization/registry.py, which use probably don't warrant the extra dependency.

**Comment by eivindjahren** [comment]
There is no more usage of pyrsistent and it is no longer a dependency so I am closing this issue.
