### ISSUE TITLE
Implement TORQUE API for slurm for test code

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6329]
The goal is to use TORQUE driver via `qstat` and `qsub` in order to access slurm cluster.
This will give us a possibility to test TORQUE on `ubuntu-latest`.
NB: Currently this is only valid for `ubuntu-latest` until the infrastructure installs slurm on our onprem nodes.

**Comment by berland** [comment]
https://installati.one/install-slurm-wlm-torque-ubuntu-18-04/
