### ISSUE TITLE
FileDialog slow at loading large files

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#633]
The fileviewer reads 1M chars at startup, then 16K chars every 1s. That means that for files greater than 1M, the fileviewer will be slow at loading the entire file. The decision to have a slow refresh was made because we need to compute the `QSize`s of incoming text, and the most Qt-like way to do this was to compute on the GUI thread. When processing a lot of lines that thread would hang and cause ERT to be entirely unresponsive. Solution I looked at are as follows:

1. __Offload the computation to a separate thread:__
This should in principle work, however I'm not satisfied that the required Qt components (primarily `QItemDelegate` and `QAbstractItemModel`) are thread-safe. Furthermore, passing the processed data back to the GUI thread seems tricky. The best 

2. __Assume fixed glyph sizes and don't compute line heights:__
This can be done via [`QFontMetricsF`](https://doc.qt.io/qt-5/qfontmetricsf.html). However, even if we specify monospace fonts, I'm not convinced that all glyphs are of the same size. We also need to compute the widths of each line in order to set scrollview width. This can easily be done by multiplying `len(line)` with glyph width (when we assume that all glyphs are of same size). However, [`QStyledItemDelegate`](https://doc.qt.io/qt-5/qstyleditemdelegate.html) adds some pixels of padding around each [`SO_ViewItem`](https://doc.qt.io/qt-5/qstyleoptionviewitem.html), which is different based on platform and/or theme. We seemingly can't access this information.
3. __Reimplement view to not use `QAbstractItemView`:__
This will allow us to manually set the padding, and so it'll solve most of point 2. This will mostly require us to reimplement the `paintEvent` member function, but it isn't an insurmountable task.

**Comment by sondreso** [comment]
The performance of the fileviewer have proven sufficient in the last two years, so closing this as a wont fix for now. Feel free to re-open!
