### ISSUE TITLE
Runpath copy-button will provide invalid path

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6337]
Clicking the copy-button will the invalid path:

/Users/ANDRLI/Project/ert/test-data/poly_example/poly_out/realization-<IENS>/iter-<ITER>

Should this default to real-0, iter-0 ?
Or should it give the runpath? I.e. /Users/ANDRLI/Project/ert/test-data/poly_example/poly_out/ instead?

**Comment by andreas-el** [comment]
Tested on Ert version 7.0.1

**Comment by oyvindeide** [comment]
A third option is to provide the untemplated path, which might make the most sense?
