### ISSUE TITLE
Remove `current_case` from ensemble smoother

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6385]
In ES-MDA there is no current case, only target case format, and if you run an experiment with 3 iterations, you get the following cases after running:

target_case_format_0
target_case_format_1
target_case_format_2
target_case_format_3

However if you run ensemble smoother, you typically get:

default
default_smoother_update

However if you current case for example named `es-mda-3`, you get:

es-mda-3
default_smoother_update

We should remove the current case for ensemble smoother, and adopt the same approach as ES MDA

**Comment by frode-aarstad** [comment]
So in the ensemble smoother we want to replace the "current case" combobox with a "target case format" text area?

**Comment by oyvindeide** [comment]
I think the first approach is the best, otherwise we end up with multiple cases with the same name.
