### ISSUE TITLE
Failed conversion of queue driver option values are silently ignored

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6391]
In the following `self.set_option` will return False if the option string failed to convert to int/bool/float etc. However, this is never checked and the option is silently not set.

https://github.com/equinor/ert/blob/8c54c23329e169bd4cda584bf61a5fa85cde83a4/src/ert/job_queue/driver.py#L55

Also, this conversion happens when the `start simulations` button is pressed. We would like to signal such a failure as soon as the application starts so that it can be shown in the `problems detected` window.

**Comment by xjules** [comment]
This requires to implement validators for different drivers in queue config: `src/ert/config/queue_config.py`
