### ISSUE TITLE
ERT GUI crashes when running a minimal example and choosing show details

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#6393]
**Describe the bug**
When running the ERT GUI with a minimal configuration file consisting only of 
```
NUM_REALIZATIONS 1
```
it crashes when choosing the option "Show details" during an ongoing experiment. Produces the following error:
![image](https://github.com/equinor/ert/assets/60844986/0bcd7b55-b735-4d87-955e-dfd59ecc71d1)

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. Press "Show details"

**Comment by jonathan-eq** [comment]
Try moving the if statement in gui/model/snapshot.py:133 outside of the loop on line 129.
