### ISSUE TITLE
Create minimal RMS test case and automatically run it for each <thing>

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#642]
The minimal RMS test case should test a RMS happy path, whatever that is. It could draw inspiration from the ert_spe1 case we already run (defined in the team repo).

<thing> is most likely a new komodo release.

**Comment by markusdregi** [comment]
We should talk to Jan Rivenæs about this.

**Comment by oysteoh** [comment]
current status - wait for @berland and @jcrivenaes to create tar's with RMS cases which we can use to run tests against RMS.

**Comment by sondreso** [comment]
Is there any updates on this issue?

**Comment by oysteoh** [comment]
@jcrivenaes says "We have been working ( and still is ) with a new and better syntetic model called Dragon ( which will replace Reek ). This would be ideal as a minimal RMS test case as it contains much python with integration towards xtgeo, fmu-tools etc"

**Comment by markusdregi** [comment]
Duplicate of https://github.com/equinor/fmu-dev/issues/8
