### ISSUE TITLE
Check if final publish is superfluous

### ISSUE THREAD

**Issue by berland** [equinor/ert#6439]
The event emitted by the lines:
https://github.com/equinor/ert/blob/b54ea943f57934358fbf3cf3b3cb6537ac96753c/src/ert/job_queue/queue.py#L371-L384
is seen in practice to be a repetition of a previously sent event.

Consider removing this publish if there is really no use for it.

**Comment by jonathan-eq** [comment]
Was this already resolved by https://github.com/equinor/ert/commit/0569a3d?

**Comment by berland** [comment]
I can't say for certain what fixed it, but I am quite sure the issue is gone now.
