### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#645]
Hello, could you point me to the necessary steps/configuration to build the documentation?

**Comment by sondreso** [comment]
You can build the documentation by running `sphinx-build -nvWE docs/rst/manual path/to/output/folder` from the root of the ERT directory. This requires both sphinx and ERT to be installed.

**Comment by ertomatic** [comment]
Travis builds the documentation if you want a complete example ;)

**Comment by joakim-hove** [comment]
> You can build the documentation by running sphinx-build -nvWE docs/rst/manual path/to/output/folder

Thank you - that worked as a charm. I had to `pip install` the additional packages `sphinx-argparse` and `sphinx_rtd_theme` - was that expected?

**Comment by sondreso** [comment]
Yes, these are sphinx extensions necessary to build the documentation (also listed in `requirements.txt`) :slightly_smiling_face:

**Comment by joakim-hove** [comment]
> [...] also listed in requirements.txt

Yes - I see that now; not in `setup.py` though - which I used for installation.

**Comment by markusdregi** [comment]
I just realised as well! I'll create an issue.

**Comment by joakim-hove** [comment]
Thanks for the help - closing.

**Comment by markusdregi** [comment]
https://github.com/equinor/ert/issues/648
