### ISSUE TITLE
Make the update step run in parallell

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6472]
We can look into ways of parallelizing the update step, options include looking into dask, openmpi, etc. Must make sure this does not make #6334 more complicated.

**Comment by oyvindeide** [comment]
Blocked by: https://github.com/equinor/ert/issues/6474, we can revisit once we evaluate the results from that.

**Comment by dafeda** [comment]
Did experiments with using multiprocessing and shared memory, but could not get consistently better performance.
Note that I did not spend much time on this, and it is probably possible to get some gains here.
Closing this for now, but may re-open once we get some user-feedback.
