### ISSUE TITLE
Speed up adaptive localization by computing matrices once in IES

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#6478]
- [ ] https://github.com/equinor/iterative_ensemble_smoother/issues/167
- [ ] #6474
- [ ] #6479

**Comment by Blunde1** [comment]
Be consistent about notation on both sides
https://github.com/equinor/iterative_ensemble_smoother/issues/129
Comment here if needed

**Comment by tommyod** [comment]
Work on the `iterative_ensemble_smoother` side will happen here:
https://github.com/equinor/iterative_ensemble_smoother/blob/6a91f4c79fe328a32dc3f329eb3be1cbf40bc49a/src/iterative_ensemble_smoother/experimental.py#L139

**Comment by oyvindeide** [comment]
This has been done in https://github.com/equinor/iterative_ensemble_smoother/pull/168, so closing this issue.
