### ISSUE TITLE
Under some conditions, ECLIPSE100 job will give `AttributeError: 'NoneType' object has no attribute 'executable'`

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6495]
The following error has been observed in real world use: 
```
<error>
  <time>18:10:03</time>
  <job>ECLIPSE100</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File ".../ert/shared/share/ert/forward-models/res/script/ecl100.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File ".../ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 488, in run
    run.runEclipse(eclrun_config=eclrun_config)
  File ".../ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 355, in runEclipse
    raise subprocess.CalledProcessError(return_code, self.sim.executable)
AttributeError: 'NoneType' object has no attribute 'executable'
</stderr>
  <stderr_file>.../realization-23/ECLIPSE100.stderr.19</stderr_file>
</error>
```

**Comment by sondreso** [comment]
Solving https://github.com/equinor/ert/issues/4241 will also fix this issue. Problem is that when the version is not available through `eclrun` it will fallback to the old way of specifying versions (which we don't need to support anymore). Should be much easier to give a sensible error message once this is done.

**Comment by DanSava** [comment]
Just a small FYI: 

* The condition under which ECLIPSE100 job will give AttributeError: 'NoneType' object has no attribute 'executable' is when there is an Eclipse licence failure.

**Comment by berland** [comment]
In newest ert, line 355 in the above traceback now corresponds to line 382.

**Comment by berland** [comment]
This is a plain bug in that `self.sim is None` whenever we use ecl_run instead of the legacy setup.  The bug stems from an oversight in https://github.com/equinor/ert/commit/26718548353345c608aaf111afec06d0b667dc19#diff-b8a4faa1aca971e76b90d4b08d1aae94820bf9ed0f76cb9c3a9de2cb43e61172
