### ISSUE TITLE
Iteration number displayed in UI labels is not consistent with iteration specified

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6516]
**Describe the bug**
When running the poly-example and specifying iteration-2, you would expect that Iteration 2 is presented throughout the UI.
Rundialog has conflicting iteration numbers.
When opening STDOUT or STDERR files in rundialog, the Iteration is also wrong.

**Expected behaviour**
Iteration 2 being displayed throughout the Ert UI.

**Environment**

OS: macOS
ERT/Komodo release: main
Python version: 3.11
Remote/HPC execution involved: no

![Screenshot 2023-11-08 at 09 47 50](https://github.com/equinor/ert/assets/114403625/6fa7e4b5-2563-461f-b394-57f7a3b9f3f6)
![Screenshot 2023-11-08 at 09 50 25](https://github.com/equinor/ert/assets/114403625/a2277c1f-1ded-4026-abf4-8fe03aa4ec4b)
![Screenshot 2023-11-08 at 09 50 37](https://github.com/equinor/ert/assets/114403625/df9179bd-df5d-4c1d-baba-ac92325171c8)

**Comment by larsevj** [comment]
In addition the progressbar does not start at 0 when setting an iteration different from 0. For instance for iteration 5 it starts at 83 %.
