### ISSUE TITLE
Different memory notations on different queues

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#6517]
Ert users should be able to specify memory options for queues, even though they internally have different memory usage notations. 

| Queue | Accepts only ints | Suffix | Link | Ert docs |
|-----------|----------|----------|---------|--------|
| SLURM | Yes (default to M) | K, M, G, T | [Link](https://slurm.schedmd.com/sbatch.html) | int format only | 
| TORQUE | No | kb, mb, gb | [Link](https://docs.adaptivecomputing.com/torque/4-0-2/Content/topics/commands/qsub.htm) | `"mb"` or `"gb"` |
| LSF |  Yes (in MB) | KB,K,MB,M,GB,G,TB,T,PB,P,EB,E,ZB,Z  | [Link](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=requirements-resource-requirement-strings)| `LSF_RESOURCE` documented (a bit unclear how to specify mem usage) |

Related command line options per queue:
SLURM (int defaults to M) (ert docs describe INT only)
	`-- mem` [KMGT]
	`-- mem-per-cpu` [KMGT]
	`-- mem-per-gpu` [KMGT]
	`-- tmp` [KMGT]

TORQUE (Requires notation b, kb, mb, gb, tb, w, kw, mw, gw, tw) (ert docs say "mb, gb")
	`-- mem` (amount of physical memory used by job)
	`-- pvmem` (virtual memory used by any single process in job)
	`-- vmem` (virtual memory used by all concurrent processes in job)

	
LSF (No notation, number in MB) (not described in docs, describes a LSF_RESOURCE, outdated?)
	`-- M` (memory per core process memory limit)
	`-- R` (memory per core minimum available memory per core)

Other inconsistencies:
* `src/clib/tests/job_queue/test_job_slurm_driver.cpp` has a test that asserts `SLURM` has a "mb" suffix

**Comment by berland** [comment]
Could it be an idea to standardize on one notation, and choose the same as Dask? I can't find it specified, but I see examples like "5 GiB" and "4 MiB"
