### ISSUE TITLE
Failed internalizing data from forward model

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6525]
**Describe the bug**
Tying to load data from simulation:

```
Thread-5 - ERROR - Realization: 1 failed after reaching max submit (1):
status from done callback: unable to infer dtype on variable 'time'; xarray cannot serialize arbitrary Python objects
```

**To reproduce**
Steps to reproduce the behaviour:
This is most likely related to reading summary data past 2263 and pandas not supporting that in the version we are using.

**Comment by xjules** [comment]
Can this be closed @oyvindeide ?

**Comment by frode-aarstad** [comment]
Seems like its still a problem in the latest xarray. 
Ref:
https://github.com/pydata/xarray/issues/7493
https://docs.xarray.dev/en/stable/user-guide/weather-climate.html#cftimeindex
