### ISSUE TITLE
Confusing error message with misconfigured observation

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6529]
If you have an observation that needs `REFCASE` or `TIME_MAP`, but they are not provided, you get a confusing error message:

```
/Users/OYVEID/projects/ert/ert/test-data/snake_oil/observations/observations.txt: list index out of range.
The time map is set from the TIME_MAP keyword. Either the time map file has an incorrect/missing date,
or the  observation is given an incorrect date.
```
A few things are confusing:
1. It does not tell me which observation is causing the error
2. I have not set `TIME_MAP` (nor `REFCASE`), which is also confusing.

To reproduce:
1. Modify the snake oil case by removing `TIME_MAP` and `REFCASE`
2. Remove `HISTORY_OBSERVATION` from the observation config

The `GEN_OBS` is using `DATE`, which requires us to look up time.

**Comment by eivindjahren** [comment]
The error thrown is rethrown from any IndexError in a big scope. The error message should be moved to a smaller scope where it knows more about what is going on.
