### ISSUE TITLE
Allow configurations of jobs in configuration file

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#654]
We want a sane configuration of jobs in ERT. An approach to this is that the jobs and their configuration options are provided through the plugin system. 

We will do this configuration using namespaces (inspired by vscode); however, we will use configsuite and in the first iteration not allow for multiple namespaces in one key (e.g. `forward_model.eclipse.executable_path: /some/path/to/exec` will be `forward_model: {eclipse : {executable_path: /some/path/to/exec}}` 

The user configuration file will in the beginning be located as a separate file on the same level as the `*.ert` config file. When ert3 and the new yaml config format is released, the job configuration will be included in the same file. 

This new configuration will allow for layering forward models configurations (default -> site-config -> user settings). When a forward model is to run, ERT will flatten the configs and make them available for `job_dispatch` via the `jobs.json` file. As a first iteration `job_dispatch` will dump the configurations into a `.config` folder where the jobs can acces them from. However, in the future we might want to pass them directly to the forward models.   

We also want to move all forward models from libres to semeio. During this process we need to ensure that they are still available for everest and ert (python 2). We do this using ert-statoil and templating the path into the site-config file.

**Comment by markusdregi** [comment]
Outdated.
