### ISSUE TITLE
ExportModel.exportField not working

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#656]
The `ExportModel` `exportField` method will not work as one of the called functions does not exist: https://github.com/equinor/libres/blob/f3fdee66b1facc5fe6f6e820e2872c8f4bff8fde/python/res/enkf/config/enkf_config_node.py#L136

**Comment by markusdregi** [comment]
Is this still an issue @oyvindeide? Steps to reproduce would be great 👍🏻

**Comment by oyvindeide** [comment]
This class has been [deleted](https://github.com/equinor/ert/commit/2ce246a2ceea34c1a1a7241ec043fcbea608e93f), so will close this.
