### ISSUE TITLE
Remove dependency on setup.py test

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#657]
python setup.py test is deprecated due to security concerns, and with it pytest-runner which we are using to run tests (https://pypi.org/project/pytest-runner/), we should move to a different way of running tests. Either pytest directly or tox.

**Comment by jondequinor** [comment]
Aren't we using tox now? Preemptively closing.

**Comment by oyvindeide** [comment]
We are not using tox in `ert`, and still have `pytest-runner` in `setup.py`.

**Comment by oyvindeide** [comment]
Definition of done: remove `pytest-runner` from `setup.py` and ensure that all tests are passing as expected.
