### ISSUE TITLE
ert vis doesn't work with Python 3.11

### ISSUE THREAD

**Issue by kvashchuka** [equinor/ert#6574]
**Describe the bug**
Running `ert vis poly.ert` (on mac) with Python 3.11 crashes with "Cannot connect to localhost" error in the browser. It is working with Python 3.10. Tested on Firefox and Chrome

**To reproduce**
Steps to reproduce the behaviour:
1. Create a python environment with Python 3.11 version
2. `pip install ert`
3. `ert vis my_config.ert`
4. Browser will open with the message `Firefox can’t establish a connection to the server at localhost:5001.`

**Expected behaviour**
It shouldn't crush

**Comment by larsevj** [comment]
The following exception is also printed to the console:

            

![Image](https://github.com/equinor/ert/assets/60844986/63de6311-dc1e-4494-87b9-5ecc5d0d712c)

**Comment by oysteoh** [comment]
Duplicated by [github.com/equinor/scout/](https://github.com/equinor/scout/issues/936)
