### ISSUE TITLE
ERT shows error when a sub directory exists inside a WORKFLOW_JOB_DIRECTORY

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#6577]
**Describe the bug**
ERT shows an error when using WORKFLOW_JOB_DIRECTORY, and there is a sub directory inside the directory pointed to. 

Possible regression from previous versions. 

**To reproduce**
Steps to reproduce the behaviour:
1. TBD

**Expected behaviour**
One of:
- Fail as we do now if this is not a regression from previous behavior, but give better error message for directories.
- Ignore sub-directory. 
- Traverse sub directory for config files (This would also fail in the reported case)

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2023.10.03
 - Python version: 3.8
 - Remote/HPC execution involved: no

**Additional context**
Link to internal report: [Viva Engage](https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjUzNDg0OTMxMjM0MjAxNiJ9?trk_copy_link=V1)

**Comment by erlid** [comment]
![image](https://github.com/equinor/ert/assets/57486677/91d30ee8-54d8-4bd6-b2d3-d4a277730a3b)
