### ISSUE TITLE
RHEL7 testing

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#661]
The internal cluster in Equinor will be upgraded to RHEL 7. A test cluster has been set up and we should make sure that ERT floats like the flagship it is ⚓️

**Comment by markusdregi** [comment]
**Setup**
Create rgs node: be lx rhel 7 test
Use `QUEUE_OPTION  LSF  QUEUE rhel7` in config file to run on rhel 7 cluster nodes.

**Testing**
- [] Run poly case and plot stuff
- [] Run history matching tutorial, see https://github.com/equinor/komodo-releases/pull/171/files

**Comment by oysteoh** [comment]
ERT => floats like a flagship :boat: Have runned forward models in both py2 and 3 against rhel7 lsf cluster on the rhel7 test-node rgs.

**Comment by markusdregi** [comment]
Did you also test a setup including RMS @oysteoh?
