### ISSUE TITLE
Test ERT against LSF v10

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#6616]
As soon as we have access to nodes running RHEL 8, we should investigate if there are issues with running ERT against IBM Spectrum LSF version 10 (This version is required for RHEL8+ support.)

IBM's release notes are here but they are not especially easy to parse https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=notes-whats-new

Exactly which changes we see will depend on the Fix Pack (point release, basically).

**Comment by xjules** [comment]
Currently, there have been no major issues reported (besides running RMS specific versions). So closing this one.
