### ISSUE TITLE
Qt problems on the RHEL 6 machines?

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#662]
Try to run ERT from a RHEL 6 machines with the Python 3 deploy and verify that the GUI launches without Qt problems.

**Comment by markusdregi** [comment]
@eivindsm Experienced problems with the unstable build

**Comment by sondreso** [comment]
This was due to wrong versions of pyqt in the komodo-release. Keeping it open until a new release confirms that this is working

**Comment by sondreso** [comment]
Should be fixed by https://github.com/equinor/komodo-releases/pull/128
Waiting for the releases to be built in order to confirm.

**Comment by sondreso** [comment]
working in /prog/res/komodo/2020.02.a1-py36
