### ISSUE TITLE
Adaptive localization checkbox is unchecked when closing `Edit variables` window

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#6632]
**Describe the bug**
Adaptive localization checkbox is unchecked when closing `Edit variables` window.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Choose `Ensemble Smoother`
4. Check the adaptive localization checkbox 
<img width="470" alt="Screenshot 2023-11-22 at 10 02 17" src="https://github.com/equinor/ert/assets/45088507/88c6b062-eec9-431b-aed1-eea6cc14f8f7">
5. Close and re-open the `Edit variables` window
6. Notice the the adaptive localization checkbox is not checked

**Expected behaviour**
Checkbox should remain checked.

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: bleeding
 - Python version 3.8

**Comment by andreas-el** [comment]
This seems to have been broken in commit aab17a23f
