### ISSUE TITLE
Running single test run with an existing storage is not possible

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6633]
**Describe the bug**
If trying to start a single test run with an existing storage, you get an error message:

![bilde](https://github.com/equinor/ert/assets/44577479/db2a9a14-a2c7-4228-92a7-458101684c01)

**To reproduce**
Steps to reproduce the behaviour:
1. Run ensemble experiment to create a case
2. Run single test run which will fail

**Expected behaviour**
The expected becavior is that we create a new experiment for Singel test run,at least if we dont already try to run into an existing experiment with 1 realization (which is effectively overwriting). So either:
1. Always create new experiment (which potentially creates a lot of small ensembles)
2. Provide drop down with ensembles that has 1 realization that can be overwritten

**Comment by andreas-el** [comment]
Issue was introduced between October release `2023.10.04` and November RC `2023.11.rc6`

**Comment by dafeda** [comment]
Not able to reproduce this on `main`.
Ran `Ensemble Experiment` using `poly.ert` followed by a `Single realization test-run` without getting the error reported in this issue.

**Comment by oyvindeide** [comment]
This was reverted to the old behavior on `main`, but the way it is done is sub-optiomal as we rerun in an existing ensemble. which could cause storage to come out of sync. I downgraded the criticality, but we should still improve it.

**Comment by oyvindeide** [comment]
Closing this as it has been fixed in a backport, created https://github.com/equinor/ert/issues/6923 for the underlying issue.
