### ISSUE TITLE
Add additional unit tests for validation of the LocalDriver

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6679]
We should test and validate edge cases when running sub/kill/status commands.

- [x] Executable not found
- [x] Submitting fails
- [x] Waiting goes on forever
- [x] Killing does not work (eg. subprocess doesn't respond to `SIGTERM`)
- [x] #6841

**Comment by jonathan-eq** [comment]
Should #6844 be removed from this issue as it is not milestone relevant?

**Comment by xjules** [comment]
> Should #6844 be removed from this issue as it is not milestone relevant?

Yes, let's remove this one as the correct "requirements" are not clear to me.
