### ISSUE TITLE
Remove [setup_requires] in setup.py.

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#668]
`[setup_requires]` in `setup.py` uses `easy_install` and should be replaced by a safer alternative (https://setuptools.readthedocs.io/en/latest/setuptools.html).

>Setuptools offers the setup_requires setup() keyword for specifying dependencies that need to be present in order for the setup.py script to run. Internally, Setuptools uses easy_install to fulfill these dependencies.
>
>pip has no way to control how these dependencies are located. None of the Package Index Options have an effect.

**Comment by sondreso** [comment]
See #657 and `setuptools_scm` is specified in `pyproject.toml` and can be removed
