### ISSUE TITLE
If simulation fails outside forward model the gui waits for 60s before showing done button

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6697]
**Describe the bug**
If the simulations fail outside of the evaluation of the forward model, the gui will just hang without anything happening for 60s, when a timeout occurs, and the `Done` button appears.

**To reproduce**
Steps to reproduce the behaviour:
1. Add and hook a workflow in the config:
```
LOAD_WORKFLOW cv_export
HOOK_WORKFLOW csv_export PRE_SIMULATION
```
2. Create a file: `csv_export` with contents: `CSV_EXPORT`, importantly, the workflow requires 1 arguments, we are not providing that
3. Start any simulation

**Expected behaviour**
Would expect the GUI to immediately report that the experiment failed, instead it is pending for 60 (ish) s before showing: 

![bilde](https://github.com/equinor/ert/assets/44577479/a74c8b77-74b9-4238-be88-9833dfe2c884)

**Comment by oyvindeide** [comment]
This comment is probably of importance:
https://github.com/equinor/ert/blob/ef5a851bb2355975cbd4130d7cd010df4ebea30d/src/ert/gui/simulation/run_dialog.py#L298-L300

**Comment by sondreso** [comment]
This can be reproduced by hooking a workflow that fails (with STOP_ON_FAILURE set to true) to the PRE_SIMULATION hook.

**Comment by dafeda** [comment]
Closed by: https://github.com/equinor/ert/commit/a5881af83f0b610c7473eafdf7d7fdd1889ccbed
