### ISSUE TITLE
Implement Pydantic model for queue options

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#6712]
We are already validating the strings in the config parser, but it would be nice to:

1. Cast values to their proper types (eg numbers as numbers, since we're in Python now they can be implicitly cast to strings when we compose the `bsub` command or whatever)
2. Apply default values in an obvious and maintainable way.
3. Replace the current list of tuples containing the options with a dataclass (say).

Then we can avoid having to do things like this in `JobQueue` in `queue.py`:

```python
def max_running(self) -> int:
    max_running = 0
    if self.driver.has_option("MAX_RUNNING"):
        max_running = int(self.driver.get_option("MAX_RUNNING"))
    if max_running == 0:
        return len(self._realizations)
    return max_running
```

**Comment by pinkwah** [comment]
Blocked by C JobQueue
