### ISSUE TITLE
Create a MVP for treeview in Manage Cases

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6722]
We have experiments under the hood, but they are not visible in the `Manage cases tab`, we should make them visible. One possibility is to use a column view, where we can show some information in the rightmost column.

**Comment by dafeda** [comment]
Something like everyones favourite Finder would work well I think.

![image](https://github.com/equinor/ert/assets/45088507/b17b78e4-fdca-49af-8b62-bdb893b25f41)

We should also consider allowing users to select experiment from the "main" window:

![image](https://github.com/equinor/ert/assets/45088507/2676e095-2325-4e7f-9c27-7fbf3ebceeae)

How high of a priority is this at the moment?

**Comment by frode-aarstad** [comment]
The first step is to add a tree view to the "Manage Cases" >  "Create new case" view.

**Comment by frode-aarstad** [comment]
First iteration. Showing experiments (Name - analysis_module  (uuid)) and its ensembles (name - start_at  (uuid). Dropped showing realizations. 

![image](https://github.com/equinor/ert/assets/30144033/b910d735-c628-4e88-a74a-e5d4df9d99a8)

**Comment by pinkwah** [comment]
If using `QTreeView`, consider having multiple columns. Ie, use `index.column()` number in `QAbstractItemModel.data()` to determine what to return.
