### ISSUE TITLE
Remove HAS_DATA and INITIALIZED from `state_map`

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6736]
`HAS_DATA` means the ensemble has responses loaded, while `INITIALIZED` means the ensemble has parameters. We read this information from the state map currently, but that only holds one state, which means that `HAS_DATA` often replaces `INITIALIZED`. This is a problem, because we would often like to check both, but that is not possible.

One example where we could have data, but not parameters, is cases where `Load results manually` is used. The state_map will then have state: `HAS_DATA´, and we could use it as prior in a manual update, however that is not viable because it does not have parameters.

Instead we can get this information by combining the information in the `ensemble` and the `experiment`, by checking if the expected parameters are present for INITIALIZED and the expected responses are present for HAS_DATA.

To reproduce:
1. Start gui (for example poly.ert)
2. Note that it is not possible to run `Run analysis` due to no ensembles
3. Run ensemble experiment
4. Create a new case
5. Load results manually into the new case
6. Run analysis with the new case as source case

Expectation:
Would expect a validation that said: No parameters for case: my_case (or something to that effect). The error message we get is not too bad, but it is an unknown exception, which is not great:
```Unable to run analysis for case 'my_case'.
The following error occurred: Unknown exception occurred with error: "No dataset 'COEFFS' in storage for realization 0"

**Comment by oyvindeide** [comment]
This means state map becomes a tracker of the run status of the ensemble, which is fine. We could potentially add some more information about what failed.

**Comment by frode-aarstad** [comment]
Are there good arguments for not just deleting the whole state map?
