### ISSUE TITLE
Use async function instead of `RealizationState`

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#6746]
`RealizationState` state machine can (and should) be replaced with a single
coroutine. This coroutine is created as a task for each realization.

## Background

The current states are as follows:

- `NOT_ACTIVE`: (Initial state.) The queue system knows about this and that's
  it.
- `WAITING`: Basically the same as `NOT_ACTIVE`.
- `SUBMITTED`: This forward model has been submitted to the cluster. We await
  confirmation from the cluster.
- `PENDING`: The cluster has received our forward model, but hasn't started yet.
- `RUNNING`: The cluster has begun execution.
- `DONE`: The forward-model has finished successfully, but ERT isn't finished
  with the realisation just yet. It still needs to internalise results.
- `SUCCESS`: (Final state.) The data has been fully internalised by ERT. We are
  done.
- `EXIT`: The forward-model has finished unsuccessfully. ERT needs to do some
  work still.
- `FAILED`: (Final state.) The forward-model has finished unsuccessfully.
- `DO_KILL`: The user has asked to stop the job and we have sent a message to
  the cluster. Pending cluster.
- `IS_KILLED`: (Final state.) Cluster has said that the job has been killed.
- `DO_KILL_NODE_FAILURE`: (Final state.) Could not kill the job. Maybe the
  cluster is down.

This set should be reduced down to:
- `WAITING`: (Initial state.) Nothing has happened yet.
- `SUBMITTING`: We have sent a message to the cluster. Cluster has not responded
  yet.
- `PENDING`: Cluster has responded, but hasn't started execution yet.
- `RUNNING`: Forward model is running.
- `KILLING`: We have asked the cluster to terminal the job.
- `COMPLETED`: (Final state.) Cluster has completed and we have internalised
  results.
- `FAILED`: (Final state.) Job has failed or we haven't been able to internalise
  results.
- `ABORTED`: (Final state.) We have killed the job or there was failure killing
  the job.

```mermaid
stateDiagram-v2
   state Realisation {
     direction LR
	  [*] --> Waiting
	  Waiting --> Submitting : submit
     Submitting --> Pending : pend
     Pending --> Running : run
     Running --> Completed : complete
     Running --> Failed : fail

     Submitting --> Submitting: retry
     Killing --> Killing: retry
 
     Waiting --> Aborted: kill
     Submitting --> Killing: kill
     Pending --> Killing: kill
     Running --> Killing: kill

     Killing --> Aborted : fail

     Aborted --> [*]
     Failed --> [*]
     Completed --> [*]
   }
```

Note that for backward compatibility, we can map the new states to the old ones:
- `WAITING` -> `WAITING` _\[We should ignore `NOT_ACTIVE`\]_
- `SUBMITTING` -> `SUBMITTED`
- `PENDING` -> `PENDING`
- `RUNNING` -> `RUNNING`
- `KILLING` -> `DO_KILL`
- `COMPLETED` -> `SUCCESS`
- `FAILED` -> `FAILED`
- `ABORTED` -> `IS_KILLED`

The other legacy states should never be used.

## Replace `RealizationState` with a few `async` functions

```py
class Scheduler:
    def __init__(self):
        # Start event
        self._start = asyncio.Event()
        self._sem = asyncio.BoundedSemaphore(max_running)

    async def execute(self) -> int:
        # Create one task per realization (irrespective of MAX_RUNNING)
        for real in self._queued_realizations:
            # Create an event for when the queued job has started (or already
            # failed)
            self._submitted[real.iens] = asyncio.Event()

            # Create an event for when the queued job has been killed
            self._killed[real.iens] = asyncio.Event()

            # Create a future for the results of a finished job, whether 
            # successful or not
            self._future[real.iens] = asyncio.Future()

            # Actually add the task to running
            self._running[real.iens] = asyncio.create_task(self._fm(real))

        # This task will check poll the driver and update the above
        # events/futures
        self._driver_poller = asyncio.create_task(self._driver_poll)

        # Wait for all tasks to complete
        await self._start.set()
        successful = 0
        for task in self._running.values():
            try:
                successful += 1 if await task.result() else 0
            except:
                pass
        return successful

    async def _fm(self, real: Realization) -> bool:
        # Ensure that all realisations are started at the same time
        await self._start.wait()
      
        # All N realisations are tasks, but we don't want to run all of
        # them concurrently. Wait for the semaphore to be ready
        await self._sem.acquire()

        # Whether we should inform the driver that we are killing
        should_kill = False
        
        # Add a timeout timer that will cancel us after a while
        cancel_task = asyncio.create_task(
            self._fm_cancel(real.timeout, self._running[real.iens])
        )
        try:
            # We are attempting to submit
            await self._set_state(real.iens, SUBMITTING)

            # Retry loop for submit. The `submit` function will
            # return False if the driver could not submit. Ie, if `bsub` fails.
            for _ in range(NUM_RETRIES):
                if await self._driver.submit(real):
                    break
                asyncio.sleep(1)
            else:
                await self._set_state(real.iens, ABORTED)
                logger.error(f"Could not submit {real}!")
                return False

            # We have successfully submitted. Pending for driver to set this
            # realisation to running.
            should_kill = True
            await self._set_state(real.iens, PENDING)
            await self._submitted[real.iens].wait()

            # We are now running!
            await self._set_state(real.iens, RUNNING)
            if await self._future[real.iens].result() and forward_model_ok():
                await self._set_state(real.iens, COMPLETED)
                return True
            else:
                await self._set_state(real.iens, FAILED)
        except asyncio.CancelledError:
            # We have been notified that we should die!
            
            # We haven't submitted anything yet, so we can exit quickly
            if not should_kill:
                await self._set_state(real.iens, ABORTED)
                return False
                
            # Retry loop for kill. The `kill` function will
            # return False if the driver could not kill. Ie. if `bkill` fails
            for _ in range(NUM_RETRIES):
                if await self._driver.kill(real):
                    break
                asyncio.sleep(1)
            else:
                await self._set_state(real.iens, ABORTED)
                logger.error(f"Could not kill {real}! Aborting")
                return
            self._set_state(real.iens, KILLING)
                
            # Wait for the job to be killed, or timeout
            await self._killed[real.iens].wait(KILL_TIMEOUT)
            self._set_state(real.iens, ABORTED)
        finally:
            # We finished before the cancel task was run. Rejoice!
            await cancel_task.cancel()
            
            await self._sem.release()
        return False
            
    async def _fm_cancel(self, timeout: int, task: asyncio.Future) -> None:
        await asyncio.sleep(timeout)
        await task.cancel()

    async def _set_state(self, iens: int, state: State) -> None:
        """
        We maintain basic states that are implemented with as a simple StrEnum.
        This function also sends a CloudEvent to the monitor (or adds it to a 
        queue for whatever reason.)
        """
        self._states[iens] = state
        await self._send_cloud_event(iens, state)  # send to Monitor directly
        
    async def kill(self, iens: int) -> None:
        await self._running[iens].cancel()
```

The `_fm` async function has the following features:
- Killable via `asyncio.Future`'s `cancel()`
- Supports `MAX_RUNTIME` via the `_fm_cancel` support task
- Supports retrying of submitting and killing
- Supports `MAX_RUNNING`

This has all the features of the state machine, but using a much more
straightforward function. There API is also minimal. The forward model task is
self-sufficient.

The current code handles aspects like `MAX_RUNTIME` and `MAX_RUNTIME` manually,
when this logic can be offloaded to Python. Notice also how we don't have a
`while True` loop here. The only place where this is required is when polling
the driver, and it should be placed there rather in the `execute()` coroutine.

Also notice how we don't need to store variables like the number of retries. We
can use normal Python constructs like `for`-loop or setting a local variable (in
the case of `should_kill`), rather than maintaining this state in a dataclass.

**Comment by jonathan-eq** [comment]
Looks good! Let's try it!

**Comment by berland** [comment]
I also like it!

**Comment by xjules** [comment]
Nice @pinkwah ! On the first glance it looks very good!

**Comment by xjules** [comment]
Is there any reason to keep this open or can we close it since we now have the core async version of RealizationState in main? @pinkwah If there are more issues to be spawned can you please create them and close this one? Please verify that those potential are not already covered in here: https://github.com/equinor/ert/issues/6755
