### ISSUE TITLE
Identify tests that can be run for both queues, eg. using feature toggling

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6756]
We should prioritize those tests that use LOCAL driver.

Goal: the tests that can be run using both queues (ie. feature toggled) shall be moved to `tests/test_integration` module. The name `test_integration` can be replaced by something more descriptive.

**Comment by xjules** [comment]
This issue represents preparation for https://github.com/equinor/ert/issues/6773

**Comment by jonathan-eq** [comment]
Blocked by an outdated pytest snapshot for es-mda tests
