### ISSUE TITLE
FeatureToggling: Toggle Scheduler

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#6760]
We have four drivers: `LOCAL`, `LSF`, `TORQUE` and `SLURM`. We want to be able to make the `LOCAL` driver use the new Scheduler by default in production, while the other drivers still use the legacy `JobQueue`.

We should modify the `FeatureToggling` so that:
- There is a default, force-enable and force-disable.
- `--enable-FEATURE` will force-enable, `--disable-FEATURE` will force-disable.
- Consumers of `FeatureToggling` can determine which of the three states it is.

Bonus points for environment variables, so as to make it easier to run CI. For each feature, look for `ERT_{FEATURE}` environment variable:
- If empty string or unset, use default.
- If `0`, force-disable.
- All other non-zero, non-empty values means force-enable.

The order for something to be enabled or disabled is:
1. Has the user provided explicit command line arguments? (`--enable-scheduler` or `--disable-scheduler`)
2. Does the user have explicit environment variables set? (`ERT_SCHEDULER=1` or `ERT_SCHEDULER=0`)
3. Use the default value for the given toggle.

**Comment by xjules** [comment]
This has been done already.
