### ISSUE TITLE
Implement retry functionality in the LocalDriver

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6770]
![image](https://github.com/equinor/ert/assets/6409506/d7219d56-4f38-4f3d-951e-05b3f4a64966)

The new LocalDriver class should handle retry functionality denoted by loops in `Submitting` and `Killing` states.

**Comment by pinkwah** [comment]
Closing as it does not make sense for LocalDriver to retry submitting or killing. This retry functionality should exist in drivers that face the HPC cluster, where errors such as network may cause temporary failure, and should be retried. Locally, starting a process either works or does not work, so no need for retrying.

Recreate this issue for HPC-facing drivers when we start working on them.
