### ISSUE TITLE
No matching distribution found for equinor-libres==11.0.0b0

### ISSUE THREAD

**Issue by GoFerreira** [equinor/ert#6775]
I tried to install the equinor-libres package, but it seems that don't exist. 

(myenv) C:\Users\gonca>pip install ert
Requirement already satisfied: ert in c:\users\gonca\.conda\envs\myenv\lib\site-packages (0.1.0)
Requirement already satisfied: ansicolors==1.1.8 in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (1.1.8)
Requirement already satisfied: console-progressbar==1.1.2 in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (1.1.2)
Requirement already satisfied: decorator in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (5.1.1)
INFO: pip is looking at multiple versions of ert to determine which version is compatible with other requirements. This could take a while.
Collecting ert
  Using cached ert-2.24.0-py3-none-any.whl (450 kB)
Requirement already satisfied: aiofiles in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (23.2.1)
Requirement already satisfied: aiohttp in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (3.9.1)
Requirement already satisfied: alembic in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (1.13.0)
Requirement already satisfied: cloudevents in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (1.10.1)
Requirement already satisfied: cloudpickle in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (3.0.0)
Requirement already satisfied: cryptography in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (41.0.7)
Requirement already satisfied: dask-jobqueue in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (0.8.2)
Requirement already satisfied: deprecation in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (2.1.0)
Requirement already satisfied: dnspython>=2 in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from ert) (2.4.2)
  Using cached ert-2.23.0-py3-none-any.whl (440 kB)
  Using cached ert-2.22.1-py3-none-any.whl (468 kB)
  Using cached ert-2.21.1-py3-none-any.whl (442 kB)
  Using cached ert-2.21.0-py3-none-any.whl (442 kB)
  Using cached ert-2.20.1-py3-none-any.whl (424 kB)
  Using cached ert-2.20.0-py3-none-any.whl (423 kB)
INFO: pip is still looking at multiple versions of ert to determine which version is compatible with other requirements. This could take a while.
  Using cached ert-2.19.2-py3-none-any.whl (397 kB)
  Using cached ert-2.19.0-py3-none-any.whl (397 kB)
  Using cached ert-2.17.1-py3-none-any.whl (812 kB)
  Using cached ert-0.2.0-py3-none-any.whl (791 kB)
ERROR: Cannot install ert==0.1.0, ert==0.2.0, ert==2.17.1, ert==2.19.0, ert==2.19.2, ert==2.20.0, ert==2.20.1, ert==2.21.0, ert==2.21.1, ert==2.22.1, ert==2.23.0 and ert==2.24.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    ert 0.1.0 depends on equinor-libres
    ert 2.24.0 depends on equinor-libres==11.0.0b0
    ert 2.23.0 depends on equinor-libres<10.1 and >=10.0.rc
    ert 2.22.1 depends on equinor-libres<10 and >=9.1.0rc0
    ert 2.21.1 depends on equinor-libres>=9.0.0rc1
    ert 2.21.0 depends on equinor-libres>=9.0.0rc1
    ert 2.20.1 depends on equinor-libres>=8.0.0b0
    ert 2.20.0 depends on equinor-libres>=8.0.0b0
    ert 2.19.2 depends on equinor-libres>=8.0.0b0
    ert 2.19.0 depends on equinor-libres>=8.0.0b0
    ert 2.17.1 depends on equinor-libres
    ert 0.2.0 depends on equinor-libres

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

(myenv) C:\Users\gonca>pip install equinor-libres==11.0.0b0
ERROR: Could not find a version that satisfies the requirement equinor-libres==11.0.0b0 (from versions: none)
ERROR: No matching distribution found for equinor-libres==11.0.0b0

**Comment by andreas-el** [comment]
Ert is already at version `8.2.0`.
Which python version do you have in your environment?
I've seen similar errors when using the wrong architecture (arm vs x86 on Mac) but also when using python 3.12 which isn't supported for Ert (just yet).

**Comment by GoFerreira** [comment]
Hi, Andreas
I appreciate your message and your assistance.
Currently, I am utilizing Python 3.11.6 on my system.
Throughout this week, I made several attempts to install equinor-libres via git, but encountered difficulties due to the "ecl" module requirement. I believe this module has been renamed to Resdata, and it is installed on my system.
I would be grateful for your guidance in identifying any missing elements for a successful installation 💯 !
Lines from the command prompt:



(myenv) C:\Users\gonca>python --version
Python 3.11.6

(myenv) C:\Users\gonca>pip install equinor-libres
ERROR: Could not find a version that satisfies the requirement equinor-libres (from versions: none)
ERROR: No matching distribution found for equinor-libres

(myenv) C:\Users\gonca>pip install git+https://github.com/equinor/libres.git@master
Collecting git+https://github.com/equinor/libres.git@master
  Cloning https://github.com/equinor/libres.git (to revision master) to c:\users\gonca\appdata\local\temp\pip-req-build-22scrntq
  Running command git clone --filter=blob:none --quiet https://github.com/equinor/libres.git 'C:\Users\gonca\AppData\Local\Temp\pip-req-build-22scrntq'
  Resolved https://github.com/equinor/libres.git to commit 8823060277851eb77324b6b64243c7a2f804a0fc
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Collecting setuptools
        Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting setuptools_scm
        Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
      Collecting wheel
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting scikit-build
        Using cached scikit_build-0.17.6-py3-none-any.whl.metadata (14 kB)
      Collecting cmake
        Using cached cmake-3.28.1-py2.py3-none-win_amd64.whl.metadata (6.5 kB)
      Collecting ninja
        Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
      ERROR: Could not find a version that satisfies the requirement ecl (from versions: none)
      ERROR: No matching distribution found for ecl
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(myenv) C:\Users\gonca>pip install resdata
Requirement already satisfied: resdata in c:\users\gonca\.conda\envs\myenv\lib\site-packages (4.1.1)
Requirement already satisfied: cwrap in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from resdata) (1.6.5)
Requirement already satisfied: numpy in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from resdata) (1.26.2)
Requirement already satisfied: pandas in c:\users\gonca\appdata\roaming\python\python311\site-packages (from resdata) (1.5.3)
Requirement already satisfied: six in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from cwrap->resdata) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from pandas->resdata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\gonca\.conda\envs\myenv\lib\site-packages (from pandas->resdata) (2023.3.post1)

**Comment by pinkwah** [comment]
It seems that you are attempting to run this on Windows, but we don't support Windows. Please use a Linux environment like WSL.

**Comment by GoFerreira** [comment]
Thank you! I will try!

> Feel free to make a new issue if there are problems with WSL: https://learn.microsoft.com/en-us/windows/wsl/install
