### ISSUE TITLE
Resolve overloaded usage of the term Job in new Scheduler vs Snapshot

### ISSUE THREAD

**Issue by berland** [equinor/ert#6779]
https://github.com/equinor/ert/blob/650c5cae21001dc7121528a7826a2c51f5dd807c/src/ert/scheduler/job.py#L43

while we still have 

https://github.com/equinor/ert/blob/35d1984b1fd055ded396a24c0f77bfe9bd585676/src/ert/ensemble_evaluator/snapshot.py#L377

which is a different kind of "Job".

**Comment by berland** [comment]
Suggestion: "ExecutingRealization"

**Comment by pinkwah** [comment]
I don't understand the dislike of the term "job". The `Job` class is a representation of the thing one "submits" and "kills" on the cluster. Per the documentation:
- LSF `bsub` ["Submits a **job** to LSF [..]"](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=SSWRJV_10.1.0/lsf_command_ref/bsub.man_top.1.htm)
- LSF `bkill` ["Sends signals to kill, suspend, or resume unfinished **jobs**"](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=reference-bkill)
- PBS `qsub` ["To submit a script is to create a batch **job** that executes the script."](https://linuxcommandlibrary.com/man/qsub#description)
- PBS `qdel` ["The qdel command deletes **jobs** [..]"](https://manpages.org/qdel)
- SLURM `sbatch` ["Option(s) define multiple **jobs** in a co-scheduled heterogeneous **job**. For more details about heterogeneous **jobs** see the document"](https://slurm.schedmd.com/sbatch.html#SECTION_SYNOPSIS)
- SLURM `scancel` ["Used to signal **jobs** or **job** steps that are under the control of Slurm."](https://slurm.schedmd.com/scancel.html#SECTION_NAME)

LSF is a "workload management platform and **job scheduler** for distributed high performance computing (HPC)." The Wikipedia article is called [Job scheduler](https://en.wikipedia.org/wiki/Job_scheduler). The other common term is "batch processing" I guess. A forward model would be a "batch script"?

I wouldn't be this anal about it if "job" wasn't such a widespread and understood concept within the realm of HPC. We ought really not reinvent terms if there are fitting existing terms for it already, and `Job` is the perfect term for this concept.

**Comment by berland** [comment]
I agree that the usage of Job is warranted inside the Scheduler, so the alternative solution is to remove the concept of Job as the same thing as a ForwardModel (in ERTs definition of forward model) in the ensemble evaluators snapshot.

**Comment by pinkwah** [comment]
Yeah. I agree that 'job' should not be used outside of scheduler. It should be called "forward model step" or similar.
