### ISSUE TITLE
Mismatch between "About" and jobs.json

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#678]
`jobs.json` seems to think `ert_version` in stable is `[2, 5, "1"]` which makes no sense. ECL is `2.5.1`, but ert itself is `2.6.6`.

**Comment by dotfloat** [comment]
https://github.com/equinor/libres/blob/4e90285db47057096d958decb1f76a126d6bbbfb/lib/job_queue/forward_model.cpp#L202-L205

Perhaps it makes more sense if this is res' version instead of ert's? If we want ert's, we can probably pass it in somehow.

**Comment by sondreso** [comment]
Could probably remove this information all together :no_entry_sign:
