### ISSUE TITLE
Create PBS (TORQUE) driver for new Scheduler

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#6780]
MVP for something that uses `qsub`, `qdel`, `qstat` called `PBSDriver`/`TorqueDriver` that is capable of running poly_example on the cluster.

**Comment by pinkwah** [comment]
I'm attempting this. We can maybe use the "open-source" OpenPBS project and that it might also be API-compatible with Torque. I shall attempt to run the JobQueue TorqueDriver tests in CI and locally.

https://hub.docker.com/r/pbspro/pbspro/

**Comment by berland** [comment]
See also https://github.com/equinor/ert/blob/45f42a28e050a4699ef5e55ee79e78b65b7e196d/.github/workflows/test_ert_with_slurm.yml#L85-L94

**Comment by pinkwah** [comment]
Yes. Having looked at the options, using Slurm with the Torque adapter is the best option. OpenPBS is not very open, nor is it TORQUE so we would still be using a program that we are not using in production.
