### ISSUE TITLE
Plotting summary vectors is very slow

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6799]
Users have reported that plotting summary vectors is very slow. Part of the reason is that every time a summary vector is loaded from storage we load all summary vector.

We should reconsider how we save this data, but we could also look into some caching, for example on the dark storage side.

**Comment by yngve-sk** [comment]
Just an idea, for the summary it might be good to have one .nc file per distinct `name` in it the current summary file. 

Now, when we select one `name`, the data is scattered across the `summary.nc` of all realizations. If the data accessing is primarily done based on the `name` there, making `name` the primary dimension of those would at least make us not have to join `|num realizations|` tables and then filter them all based on the `name` attribute.
