### ISSUE TITLE
Test that num_cpu infomation is propagated to drivers

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6808]

**Comment by jonathan-eq** [comment]
This seems like more of a driver unit test

**Comment by berland** [comment]
This issues stems from the existing test_job_queue.py::test_num_cpu_submitted_correctly_lsf

Checking that num_cpu is passed on to the LSF system is a driver unit test yes. If the driver depends on such arguments being passed through the scheduler, there can be a test for the scheduler to let arguments be passed through. As it is now, the driver is initialized independtly of the scheduler, there is no responsibility for the scheduler, and then there will be no need for this test.

**Comment by xjules** [comment]
Complete agree with @berland to skip this test. But not sure if I see through the following:

> If the driver depends on such arguments being passed through the scheduler, there can be a test for the scheduler to let arguments be passed through

**Comment by berland** [comment]
It just means that we can skip this teset :)
