### ISSUE TITLE
Make scheduler default queue for simulation context when using LOCAL driver

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6821]
We should refactor simulation context and batch simulator in order it can cooperate with Scheduler.

**Comment by xjules** [comment]
@berland Shall we close this one? It does not say run everest in this one.

**Comment by berland** [comment]
but have we set scheduler to be default? I think it is based on feature toggling.

**Comment by xjules** [comment]
Superceeded by https://github.com/equinor/ert/issues/6983
