### ISSUE TITLE
Refactor plugin parsing: Use less/no temp files getting plugin workflow jobs into site config

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#6825]
It is currently in the `ErtPluginManager`, but w/ the refactored config, we can streamline this and use less temp files to get the installable jobs into the site config

**Comment by DanSava** [comment]
Tried to take a stab at this issue. Still, after removing the temp site-config file it became a bit confusing to me that this refactoring would improve things. I might be missing some critical context required to make an implementation that actually improves things and not just makes life more complicated for the future.

**Comment by yngve-sk** [comment]
Site config has been heavily refactored and this issue is no longer relevant
