### ISSUE TITLE
Implement MAX_RUNNING properly in Scheduler

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#6828]
Currently we're misusing the `CONCURRENT_INTERNALISATION` as `MAX_RUNNING`. Scheduler should use `max_running` from the config in the semaphore rather than `CONCURRENT_INTERNALIZATION`.

**Comment by jonathan-eq** [comment]
What is internalisation in ert context?

**Comment by berland** [comment]
This and #6850 are duplicates.

Internalisation means to make some of the output from forward models available to ERT for assisted history match, e.g. parsing the summaray data from Eclipse and put it into ERTs storage.
