### ISSUE TITLE
Subprocesses should immediately terminate when parent (ERT) dies on local-driver 

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6844]
This is a deviation from how this behaves on the HPC cluster, where jobs on the cluster continue running even if ERT is non-responding.

**Comment by jonathan-eq** [comment]
This is the same functionality which is in the old local driver. Putting it back as it is not critical for the current milestone.

**Comment by pinkwah** [comment]
Closing as WONTFIX
