### ISSUE TITLE
ert gui: error: argument config: File was not found: poly.ert

### ISSUE THREAD

**Issue by GoFerreira** [equinor/ert#6845]
Hi,
I installed recently ert in my virtual machine (os: Ubuntu), but it does not boot the window.
I would like try to understand what is missing.  
Thank you! :)
(base) goncalo@goncalo-VirtualBox:~/Desktop$ pip install ert
Requirement already satisfied: ert in /home/goncalo/anaconda3/lib/python3.11/site-packages (8.2.1)
Requirement already satisfied: aiohttp in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.8.5)
Requirement already satisfied: beartype>0.11 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.16.4)
Requirement already satisfied: cloudevents>=1.6.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.10.1)
Requirement already satisfied: cloudpickle in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.2.1)
Requirement already satisfied: tqdm>=4.62.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (4.65.0)
Requirement already satisfied: cryptography in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (41.0.3)
Requirement already satisfied: cwrap in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.6.5)
Requirement already satisfied: deprecation in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.1.0)
Requirement already satisfied: dnspython>=2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.4.2)
Requirement already satisfied: resdata in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (4.1.1)
Requirement already satisfied: fastapi in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.105.0)
Requirement already satisfied: filelock in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.9.0)
Requirement already satisfied: iterative-ensemble-smoother==0.2.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.2.0)
Requirement already satisfied: typing-extensions in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (4.9.0)
Requirement already satisfied: jinja2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.1.2)
Requirement already satisfied: lark in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.1.8)
Requirement already satisfied: matplotlib in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.7.2)
Requirement already satisfied: numpy<2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.24.3)
Requirement already satisfied: packaging in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (23.1)
Requirement already satisfied: pandas in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.0.3)
Requirement already satisfied: pluggy>=1.3.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.3.0)
Requirement already satisfied: psutil in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (5.9.0)
Requirement already satisfied: pydantic>2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.5.3)
Requirement already satisfied: PyQt5 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (5.15.10)
Requirement already satisfied: python-dateutil in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.8.2)
Requirement already satisfied: pyyaml in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (6.0)
Requirement already satisfied: qtpy in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.2.0)
Requirement already satisfied: requests in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.31.0)
Requirement already satisfied: resfo in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (4.0.1)
Requirement already satisfied: scipy>=1.10.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.11.1)
Requirement already satisfied: uvicorn>=0.17.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.25.0)
Requirement already satisfied: websockets in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (12.0)
Requirement already satisfied: httpx in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.26.0)
Requirement already satisfied: xarray in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2023.6.0)
Requirement already satisfied: xtgeo>=3.3.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.6.0)
Requirement already satisfied: netCDF4 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (1.6.5)
Requirement already satisfied: sortedcontainers in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (2.4.0)
Requirement already satisfied: python-multipart in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (0.0.6)
Requirement already satisfied: pyarrow in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (11.0.0)
Requirement already satisfied: tables in /home/goncalo/anaconda3/lib/python3.11/site-packages (from ert) (3.8.0)
Requirement already satisfied: annotated-types>=0.4.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from pydantic>2->ert) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from pydantic>2->ert) (2.14.6)
Requirement already satisfied: click>=7.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from uvicorn>=0.17.0->ert) (8.0.4)
Requirement already satisfied: h11>=0.8 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from uvicorn>=0.17.0->ert) (0.14.0)
Requirement already satisfied: h5py>=3 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (3.9.0)
Requirement already satisfied: hdf5plugin>=2.3 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (4.3.0)
Requirement already satisfied: joblib in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (1.2.0)
Requirement already satisfied: roffio>=0.0.2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (1.0.1)
Requirement already satisfied: segyio>1.8.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (1.9.12)
Requirement already satisfied: shapely>=1.6.2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (2.0.2)
Requirement already satisfied: xtgeoviz in /home/goncalo/anaconda3/lib/python3.11/site-packages (from xtgeo>=3.3.0->ert) (0.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (10.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from matplotlib->ert) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from pandas->ert) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from pandas->ert) (2023.3)
Requirement already satisfied: six>=1.5 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from python-dateutil->ert) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from aiohttp->ert) (1.2.0)
Requirement already satisfied: cffi>=1.12 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from cryptography->ert) (1.15.1)
Requirement already satisfied: anyio<4.0.0,>=3.7.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from fastapi->ert) (3.7.1)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from fastapi->ert) (0.27.0)
Requirement already satisfied: certifi in /home/goncalo/anaconda3/lib/python3.11/site-packages (from httpx->ert) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /home/goncalo/anaconda3/lib/python3.11/site-packages (from httpx->ert) (1.0.2)
Requirement already satisfied: idna in /home/goncalo/anaconda3/lib/python3.11/site-packages (from httpx->ert) (3.4)
Requirement already satisfied: sniffio in /home/goncalo/anaconda3/lib/python3.11/site-packages (from httpx->ert) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from jinja2->ert) (2.1.1)
Requirement already satisfied: cftime in /home/goncalo/anaconda3/lib/python3.11/site-packages (from netCDF4->ert) (1.6.3)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from PyQt5->ert) (12.13.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from PyQt5->ert) (5.15.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from requests->ert) (1.26.16)
Requirement already satisfied: cython>=0.29.21 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from tables->ert) (3.0.7)
Requirement already satisfied: numexpr>=2.6.2 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from tables->ert) (2.8.4)
Requirement already satisfied: blosc2~=2.0.0 in /home/goncalo/anaconda3/lib/python3.11/site-packages (from tables->ert) (2.0.0)
Requirement already satisfied: py-cpuinfo in /home/goncalo/anaconda3/lib/python3.11/site-packages (from tables->ert) (8.0.0)
Requirement already satisfied: msgpack in /home/goncalo/anaconda3/lib/python3.11/site-packages (from blosc2~=2.0.0->tables->ert) (1.0.3)
Requirement already satisfied: pycparser in /home/goncalo/anaconda3/lib/python3.11/site-packages (from cffi>=1.12->cryptography->ert) (2.21)
(base) goncalo@goncalo-VirtualBox:~/Desktop$ ert gui poly.ert
usage: ert gui [-h] [--verbose] [--enable-new-storage] [--enable-scheduler]
               config
ert gui: error: argument config: File was not found: poly.ert

**Comment by berland** [comment]
You are missing one command from the README: "`cd  test-data/poly-example`". In there you will find the file `poly.ert`.

**Comment by GoFerreira** [comment]
hi,
Thank you for your message.
I did detected this bug:
/home/goncalo/anaconda3/lib/python3.11/site-packages/ert/gui/main.py:9: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
ERT crashed unexpectedly with "libQt5Gui.so.5: cannot open shared object file: No such file or directory".
See logfile(s) for details:
   /home/goncalo/Desktop/ert/test-data/poly_example/logs/ert-log-poly-ert-2023-12-27T2131.txt
What is the solution for it?

**Comment by berland** [comment]
Ok, that probably means that the GUI (using Qt) is either not working at all under WSL, or there is something wrong with your Qt installation under WSL. 

Instead of running the gui, you might be satisfied with running the cli version of ert, then you do f.ex. `ert ensemble_experiment poly.ert`.
