### ISSUE TITLE
Scheduler does not handle max_running=0 properly

### ISSUE THREAD

**Issue by berland** [equinor/ert#6850]
If max_running is set to zero in the ert configuration, this should mean the same as no limit. The current code seemingly does not support max_running=0.

https://github.com/equinor/ert/blob/508fa719c9340705633b92a1abc0b93c4026ccee/src/ert/scheduler/scheduler.py#L122

**Comment by pinkwah** [comment]
Should we have a Driver-determined default? I reckon a reasonable default for Local is `$(nproc)` lest we let the user DDOS themselves. I don't know what such default would be for the other drivers though, so maybe not.

**Comment by berland** [comment]
I guess we should keep the current behaviour for some time, but changing to `$(nproc)` for local driver could absolutely make sense for the local driver. For the other drivers I guess it should still be `unlimited = len(ensemble)`
