### ISSUE TITLE
RHEL 7: Test setup with RMS

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#686]
@oysteoh did quite some testing of ERT+FMU in https://github.com/equinor/ert/issues/661. Only thing missing is testing a setup with RMS (for instance the FMU tutorial).

This is currently blocked by Cohiba issues...

**Comment by oysteoh** [comment]
Runned ensemble experiment on REEK case with RMS on RHEL7 rgs node and `rhel7` lsf queue with great success!
