### ISSUE TITLE
Experiment name gets overwritten

### ISSUE THREAD

**Issue by aronhoyer** [equinor/ert#6861]
After creating an experiment, the experiment name set through the gui can get overwritten by `LocalExperimentAccessor` if name is not passed to constructor:

https://github.com/equinor/ert/blob/9866742115085bac177954449e7d16669d2ef59f/src/ert/storage/local_experiment.py#L152

**Comment by dafeda** [comment]
What is the reason to not always pass a name to the constructor?

**Comment by frode-aarstad** [comment]
Might be fixed by #7129
