### ISSUE TITLE
test_batch_sim is flaky with Scheduler

### ISSUE THREAD

**Issue by berland** [equinor/ert#6869]
Some failues have been observed, like 
https://github.com/equinor/ert/actions/runs/7384878270/job/20088617825

**Comment by berland** [comment]
test_simulation_context is also flaky with the same error message:

```
FAILED tests/unit_tests/simulator/test_batch_sim.py::test_batch_ctx_status_failing_jobs[True] - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/unit_tests/simulator/test_simulation_context.py::test_simulation_context[True] - RuntimeError: There is no current event loop in thread 'MainThread'.
= 2 failed, 1567 passed, 25 skipped, 1 xfailed, 702 warnings in 251.29s (0:04:11) =
```

and the latter executes quicker for debugging:

`pytest "tests/unit_tests/simulator/test_simulation_context.py::test_simulation_context" -sxv --count=100 -k "[True"`

**Comment by berland** [comment]
Not reproducible locally wih 
`$ nice pytest "tests/unit_tests/simulator/test_simulation_context.py::test_simulation_context" -sxv --count=1000 -k "[True" -n 24`

**Comment by jonathan-eq** [comment]
I might have fixed a similar bug a couple of weeks ago. I will give it a shot!

**Comment by berland** [comment]
Also crashes in Python 3.9 in https://github.com/equinor/ert/actions/runs/7385000040/job/20088989452?pr=6857
