### ISSUE TITLE
Deleting run_path does not update case creation date

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6892]
When running Ert with an existing run_path, you get the option to delete the existing run_path.
I would assume that the newly created run_path would have todays date (2024.01.04), but it retains the creation date.
This can be verified in the manage cases 

Show existing cases:
![Screenshot 2024-01-04 at 09 17 22](https://github.com/equinor/ert/assets/114403625/90b4f133-368d-410d-b516-58169694eebc)

Run Experiment:
![Screenshot 2024-01-04 at 09 17 42](https://github.com/equinor/ert/assets/114403625/957d3bc7-5fb3-49c0-85e3-e3b62a905531)

Check cases again:
![Screenshot 2024-01-04 at 09 31 48](https://github.com/equinor/ert/assets/114403625/9bb70d01-6897-4e31-b1c9-ce6107c4324c)

Files and folders in ensembles:
```
(2023.12.03-py38) [andrli@st-linrgs347 ensembles]$ ll
total 128
drwxrwxr-x 103 andrli andrli 3246 Jan  2 14:53 31dfec79-9cc8-4138-be30-96f2809a7e60
drwxrwxr-x 103 andrli andrli 3246 Jan  2 14:53 48cb389d-e011-4c9c-b661-ff1a65d22267
drwxrwxr-x 103 andrli andrli 3246 Jan  2 14:54 491bc679-1d0b-4d79-8051-4746eb46a04a
drwxrwxr-x 103 andrli andrli 3246 Jan  2 14:53 609a8129-c3c1-4aa9-a394-22fa346b6522

(2023.12.03-py38) [andrli@st-linrgs347 ensembles]$ cat 31dfec79-9cc8-4138-be30-96f2809a7e60/index.json 
{"id":"31dfec79-9cc8-4138-be30-96f2809a7e60","experiment_id":"96865818-7cf6-4771-bea5-474fe939639f","ensemble_size":100,"iteration":0,"name":"default_0","prior_ensemble_id":null,"started_at":"2024-01-02T14:53:06.111162"}

(2023.12.03-py38) [andrli@st-linrgs347 ensembles]$ ll 31dfec79-9cc8-4138-be30-96f2809a7e60/realization-0/
total 48
-rw-rw-r-- 1 andrli andrli 440 Jan  4 09:17 COEFFS.nc
-rw-rw-r-- 1 andrli andrli 440 Jan  4 09:17 POLY_RES.nc
```

**Comment by oyvindeide** [comment]
There are unrelated, as case != run path, so this is expected behavior. As case (from manage cases) is what we store internally, while the run path is the temporary path where the simulations are running.
