### ISSUE TITLE
tests/integration_test/scheduler/test_integration_local_driver.py::test_subprocesses_live_on_after_ert_dies fails on job queue

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#6904]
**Describe the bug**
tests/integration_test/scheduler/test_integration_local_driver.py::test_subprocesses_live_on_after_ert_dies fails on legacy job queue with error. This only occurs when running checks on commits on github.
__________ test_subprocesses_live_on_after_ert_dies[using_job_queue] ___________
Python 3.10.13

    @pytest.mark.scheduler
    @pytest.mark.integration_test
    async def test_subprocesses_live_on_after_ert_dies(tmp_path, try_queue_and_scheduler):
        # Have ERT run a forward model that writes in PID to a file, then sleeps
        # Forcefully terminate ERT and assert that the child process is not terminated
        create_ert_config(tmp_path)
    
        ert_process = subprocess.Popen(["ert", "test_run", "ert_config.ert"], cwd=tmp_path)
        check_path_retry, check_path_max_retries = 0, 50
        expected_path = Path(tmp_path, "test_out/realization-0/iter-0/forward_model_pid")
        while not expected_path.exists() and check_path_retry < check_path_max_retries:
            check_path_retry += 1
            await asyncio.sleep(0.5)
    
        assert expected_path.exists() <-- FAILED ON THIS
E       AssertionError: assert False
E        +  where False = <bound method Path.exists of PosixPath('/private/var/folders/qv/pdh5wsgn0lq3dp77zj602b5c0000gn/T/pytest-of-runner/pytest-0/popen-gw3/test_subprocesses_live_on_afte0/test_out/realization-0/iter-0/forward_model_pid')>()
E        +    where <bound method Path.exists of PosixPath('/private/var/folders/qv/pdh5wsgn0lq3dp77zj602b5c0000gn/T/pytest-of-runner/pytest-0/popen-gw3/test_subprocesses_live_on_afte0/test_out/realization-0/iter-0/forward_model_pid')> = PosixPath('/private/var/folders/qv/pdh5wsgn0lq3dp77zj602b5c0000gn/T/pytest-of-runner/pytest-0/popen-gw3/test_subprocesses_live_on_afte0/test_out/realization-0/iter-0/forward_model_pid').exists

**Comment by jonathan-eq** [comment]
Is this still occuring? I have not seen it for a while..
@berland @xjules

**Comment by xjules** [comment]
I think, this can be closed!
