### ISSUE TITLE
ecl_run depends on Resdata to be able to make summary objects

### ISSUE THREAD

**Issue by berland** [equinor/ert#6928]
This line exposes the Eclipse100 job to bugs in resdata for MPI runs.

https://github.com/equinor/ert/blob/dd3a01de078e91dbda15e9d39c68f22a61f1ffb6/src/ert/shared/share/ert/forward-models/res/script/ecl_run.py#L389

For the user, a crash in this code looks like Eclipse100 itself has crashed, while it hasn't.

**Comment by berland** [comment]
The crash can be reproduced with

`summary.x XXX_PRED-0.UNSMRY`

on the finished file produced in the asset.

**Comment by eivindjahren** [comment]
We looked at this together, and it seems like resdata crashes on the first report step. One unusual thing about the summary file is that the seqhdr is negative and ministeps don't start from 0.

**Comment by berland** [comment]
Underlying bug in resdata: https://github.com/equinor/resdata/issues/945

**Comment by berland** [comment]
> We looked at this together, and it seems like resdata crashes on the first report step. One unusual thing about the summary file is that the seqhdr is negative and ministeps don't start from 0.

Checked a smry file from Eclipse 2021, and it has the same properties with respect to seqhdr and ministeps but there is no crash.
