### ISSUE TITLE
Observations or local analysis steps are missing when running non-adaptive localisation

### ISSUE THREAD

**Issue by oddvarlia** [equinor/ert#6940]
**Describe the bug**
Only the last specified correlation group (ministep/local-analysis-step) is used. The other correlation groups are not applied.
The output/update_log reports now Observed history and Simulated data for all specified correlation groups, but only the last one specified is actually used.

**To reproduce**
Steps to reproduce the behaviour:
1. Run an example with multiple correlation groups using field parameter for non-adaptive localisation
2. Compare the results for a  case without and with localisation. Calculate the difference between updated and initial field for both cases. You will se that without localisation all observations are used. With localisation only the last specified correlation group is used.
3. A test case can be used:   See: https://github.com/equinor/semeio/pull/545

**Expected behaviour**
That all specified correlation groups are used. In the test case specified in step 3 above, we expect that area close to each of the three observations are updated when running with non-adaptive localisation, and not only around observation with name OBS_1_4_1

**Screenshots**
![image](https://github.com/equinor/ert/assets/77153131/14b4d18e-5def-4a72-9257-ac143011d66e)
This is from case A from the above mentioned test case. The lower right plot show the standard deviation over the ensemble of difference between realization that is updated and initial realization with initial values for a case with localisation. The plot in the middle at the bottom row of plots is the standard deviation over the ensemble with difference between updated and initial without localisation. What we see is that without localisation three areas (around three different observations) are updated. This can also be seen in the average over ensemble with differences without localisation to the left in lower row of plots.
The result from non-adaptive localisation has only updated the area around one of the observations, not all three as we should expect. Nothing is reported in the files in update_logs around removing any observations when running with localisation.

![image](https://github.com/equinor/ert/assets/77153131/b4252643-459d-4fbc-9328-4682126bd6d6)
From update_log when not using localisation

![image](https://github.com/equinor/ert/assets/77153131/dfdc9850-1af9-4a39-8207-6c5e80eb9a26)
![image](https://github.com/equinor/ert/assets/77153131/e6c509ac-e3af-454e-be20-a6fae8b64fca)
![image](https://github.com/equinor/ert/assets/77153131/dffde590-f9f4-45f8-acad-c49e8dae9e90)
From update_log when running with localisation. All three correlation groups are present here in the update_log file, but the first two are not used (no effect on the result fields)

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: Both bleeding version and stable version 2023.12.05 (using semeio with above mentioned PR545)
 - Python version 3.8
 - Run from HPRGS

**Additional context**
semeio PR 545 build on top of semeio  PR575 which is necessary to correct for index bug in semeio.
NOTE: In previous stable komodo version before current stable version (2023.12.05) ERT applied all correlation groups specified in non-adaptive localisation, but due to other semeio and ERT updates, I don't think semeio PR 545 can be used together with that ERT version and therefore not possible to use the test scripts in PR545.

**Comment by oyvindeide** [comment]
Closing this, as the update configuration has changed, and we are reevaluating how we are going to do distance based localization. https://github.com/equinor/ert/commit/f26a69942191141f1d29998f2fb4010655096502#diff-ad9fbf176673521dbc0305641af955178ffa4b152b9cd5cc85a2c35dbbcefcbb
