### ISSUE TITLE
Implement async version of ensemble evaluator

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6958]
The goal is the refactor `EnsembleEvaluator` to use async purely. 

On the first glance it might be doable. There a few caveats though represented by `BatchingDispatcher` (using threads for communication) and updating SnaphShots in Ensemble.

~~blocked by #7775~~

**Comment by eivindjahren** [comment]
I think closing this issue should resolve https://github.com/equinor/ert/issues/3124 .
