### ISSUE TITLE
Create and serve observations

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#696]
Have the new data solution be capable of creating a set of observations and serving them afterwards. The observations should consist of multiple observations, each consisting of:

- an observed value
- an error

After creation, the data should be readable without any further knowledge then what can be gained from the data solution.

**Comment by mortalisk** [comment]
Wishes for api

* all definitions need
    * Data type, i.e. float/string (if we intend to support different types)
    * Size
    * Perhaps min and max for values and index (for time series)
        * This would enable incremental plotting, greatly lowering memory usage and time for plotting

**Comment by joakim-hove** [comment]
> index (for time series) 

I would encourage you to consider using "true time" of some sort for temporal localization; fixing the time domain to the Eclipse report steps is in my opinion one of the large design f... ups in ERT.

**Comment by markusdregi** [comment]
What @joakim-hove said ⬆️

**Comment by sondreso** [comment]
Implemented in feature branch
