### ISSUE TITLE
Design first iteration of data model

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#698]
We should make a first iteration of the data model.

**Comment by lars-petter-hauge** [comment]
We should keep in mind that our data model should facilitate different runs - and show the difference between them:

User story:

I would want to easily visualize the difference between runs.

Consider a scenario where I have a basis config which has been run. And then I:
 - remove one parameter
 - add one parameter
 - remove one observation
 - change one observation value
 - Use a different algorithm

Maybe something like this:

```diff
- parameter_one
+ parameter_two
~ observation_one
- observation_two
+<algorithm_name>
```
(Can't color in github appearantly, and the `diff` doesn't cover it.. But I wanted the `observation_one` to be color orange)

**Comment by ManInFez** [comment]
Merged in feature branch
