### ISSUE TITLE
Update inversion types in GUI

### ISSUE THREAD

**Issue by Blunde1** [equinor/ert#6986]
In GUI I see
![image](https://github.com/equinor/ert/assets/13650516/61621f79-dfeb-4712-908c-810198a6c92e)

I believe $R \approx EE^T$ or `E` is not implemented anymore.
It was an active choice to avoid these approximations.

See `analysis_ES()`
https://github.com/equinor/ert/blob/0465891188ae715f7cf6b56e71beaf28241d0ccf/src/ert/analysis/_es_update.py#L588-L603

**Comment by oyvindeide** [comment]
Fixed in: https://github.com/equinor/ert/commit/280aff4bb720643572d2038d65ef511f375e5023
