### ISSUE TITLE
gstools is used in the code but is only in optional dependencies

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6987]
https://github.com/equinor/ert/blob/df4f7738c96f4517e0dc4a8707b08a7baab6cc78/pyproject.toml#L125
https://github.com/equinor/ert/blob/df4f7738c96f4517e0dc4a8707b08a7baab6cc78/tests/unit_tests/analysis/test_es_update.py#L6

It should be under project->dependencies in pyproject.toml

**Comment by dafeda** [comment]
It's only used in tests so should be defined in optional dependencies. Closing.
