### ISSUE TITLE
Create test verifying that queue config parameters are propagated correctly to Scheduler

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7012]
Add a test that confirms that the queue options are propagated correctly down the line to scheduler. Especially if the options are "overwritten" (eg. `MAX_RUNNING`) that if gets the last entry in the config.

**Comment by berland** [comment]
Also solved by #7008

**Comment by berland** [comment]
What is lacking in this PR is perhaps a test for `_evaluate_inner` in `_legacy.py` that it will do the correct thing when initializing Scheduler.

**Comment by berland** [comment]
> What is lacking in this PR is perhaps a test for `_evaluate_inner` in `_legacy.py` that it will do the correct thing when initializing Scheduler.

Added in ece4d9bbbb3d665301c56f7073f76a462829b989
