### ISSUE TITLE
Ert not updating the parameters in global variables when using a distribution list

### ISSUE THREAD

**Issue by kvashchuka** [equinor/ert#7024]
**Describe the bug**
The parameters from distribution list are saved, but not updated when using the same case folder name.

**To reproduce**
1. Run ert (Single realization test-run) with MODE: 0.3 to an output folder called abc on scratch (`DEFINE  <CASE_DIR> abc`). Now the parameter is set to 0.3
2. Update the value MODE to 0 in the distribution list, remove the output folder abc on scratch and run ERT. Now it is still giving 0.3 to the output parameter file on scratch.
3. Keep MODE=0 in the distribution file, but now save it to a new output folder called abcd (`DEFINE  <CASE_DIR> abcd`). This time the parameter is set to 0.

**Expected behaviour**
Parameters should be updated no matter the previous runs.

**Screenshots**
![image 199](https://github.com/equinor/ert/assets/12686827/bce4a66a-f3eb-4454-8021-cfb72f4a1ed4)

**Environment**
 - OS:  RHEL7
 - ERT/Komodo release: 2023.12.06
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by oys-j** [comment]
It is related to constant parameters in the distribution file. Have not tested if it also applies to normal or uniform distributions

**Comment by oys-j** [comment]
my colleague found that the problem is related to the folder ert/output/storage . If I delete this folder manualy and run ERT it works correctly

**Comment by oyvindeide** [comment]
Our main problem is that `Ensemble experiment` is used for multiple, quite different, purposes. One of which is sensitivity. In that context most users wants to overwrite existing ensembles, and by extension, overwrite the existing parameters. In other contexts we just want to evaluate the prior, and not overwrite the existing parameters. This is a duplicate/sub-issue of: [#5656](https://github.com/equinor/ert/issues/5686).
