### ISSUE TITLE
Running `Ensemble experiment` with new `Experiment name` does not create new `Ensemble`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#7027]
**To reproduce**

1. Run Ensemble experiment using default Experiment name (ensemble_experiment).
This creates an experiment and a default ensemble (current case) in erts' internal storage.

 2. Change Experiment name to ensemble_experiment_2 an re-run Ensemble experiment. Note that Current case is still default.
We now have two experiments in storage but only one ensemble that points to the first experiment created.
ert does not create a new ensemble tied to the new experiment.

**Expected behaviour**
A new ensemble should be created and linked to the new experiment.

**Comment by oyvindeide** [comment]
Closing as we will do this as part of #5686
