### ISSUE TITLE
Ert unit_tests/gui/test_main_window.py::test_that_gui_plotter_works_when_no_data fails and seems flaky

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7042]
**Describe the bug**
The unit test often fails with 
```
FAILED unit_tests/gui/test_main_window.py::test_that_gui_plotter_works_when_no_data - assert 5 == 0
 +  where 5 = len([<ert.gui.tools.plot.plot_case_selection_widget.CaseSelectCheckButton object at 0x7f2a819841f0>, <ert.gui.tools.plot.plot_case_selection_widget.CaseSelectCheckButton object at 0x7f2a81984280>, <ert.gui.tools.plot.plot_case_selection_widget.CaseSelectCheckButton object at 0x7f2a81984310>, <ert.gui.tools.plot.plot_case_selection_widget.CaseSelectCheckButton object at 0x7f2a819843a0>, <ert.gui.tools.plot.plot_case_selection_widget.CaseSelectCheckButton object at 0x7f2a81984430>])
```
The test creates a minimal ert config, and attempts plotting it before it is even ran. It should not have any data to plot, but apparently it finds it somewhere. Could it be that the storage fixture is not working correctly, and multiple tests are sharing data?
The test is very short and not complicated, which should help troubleshooting a lot.

**To reproduce**
Steps to reproduce the behaviour:
1. Run nightly build, or we might be able to reproduce it by running on an RGS node. If not, try running it with pytest-repeat.
2. Fails while running with `pytest -x tests/unit_tests/gui/test_main_window.py -k plot -n 12 --count 50`

**Expected behaviour**
Test should not fail

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: Bleeding
 - Python version: 3.8
 - Remote/HPC execution involved: Azure

**Additional context**

**Comment by dafeda** [comment]
Failed on-prem here: https://github.com/equinor/komodo-releases/actions/runs/7737308845/job/21097190440

**Comment by jonathan-eq** [comment]
Found the problem. When it is running alongside unit_tests/gui/test-main_window.py::test_that_the_plot_window_contains_the_expected_elements, it will somehow share storage. That test runs esmda and asserts it finds 5 cases in the result, while the other test is failing because it is finding 5 cases while expecting 0 cases. The next issue is seeing why this it happening.

**Comment by jonathan-eq** [comment]
Solution: PlotApi uses the StorageService.session, which seems to be a singleton across tests when they are running simultaneously. Fixed by mocking the PlotApi._get_all_cases method in the test.
