### ISSUE TITLE
storage can create ensemble with state HAS_DATA when no data present

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7046]
The following fails:

```python
def test_empty_ensemble_should_be_undefined():
    with open_storage("/tmp/storage", mode="w") as storage:
        experiment = storage.create_experiment(
            parameters=[
                GenKwConfig(
                    template_file="//tmp/tmp280u73a6/template_file",
                    transfer_function_definitions=[],
                    name="0",
                    forward_init=False,
                    output_file=None,
                )
            ],
            responses=[
                SummaryConfig(
                    name="A",
                    input_file="D",
                    keys=[],
                    refcase=set(),
                ),
            ],
        )
        ensemble = storage.create_ensemble(ensemble_size=1, experiment=experiment.id)
        assert ensemble.get_ensemble_state() == [RealizationStorageState.UNDEFINED]

```
The same issue reappears when you do create_ensemble with prior: 

```python
def test_creating_ensemble_from_empty_prior_results_in_parent_failure():
    with open_storage("/tmp/storage", mode="w") as storage:
        experiment = storage.create_experiment(
            parameters=[
                GenKwConfig(
                    template_file="//tmp/tmp280u73a6/template_file",
                    transfer_function_definitions=[],
                    name="0",
                    forward_init=False,
                    output_file=None,
                )
            ],
            responses=[
                SummaryConfig(
                    name="A",
                    input_file="D",
                    keys=[],
                    refcase=set(),
                ),
            ],
        )
        ensemble1 = storage.create_ensemble(ensemble_size=1, experiment=experiment.id)
        ensemble2 = storage.create_ensemble(
            ensemble_size=1, experiment=experiment.id, prior_ensemble=ensemble1
        )
        assert ensemble2.get_ensemble_state() == [
            RealizationStorageState.PARENT_FAILURE
        ]
```

This situation can be provoked from a config by setting
```
NUM_REALIZATIONS  100
ECLBASE BASE
```
and then not having any summary observations or history observations.

**Comment by frode-aarstad** [comment]
@eivindjahren are the tests above part of a branch about to be merged - or should I add similar tests to this PR?

**Comment by eivindjahren** [comment]
@frode-aarstad You can just uncomment the lines marked with issue 7046 here:
https://github.com/equinor/ert/blob/1134982596b7066e7c84a726e58be9c95c6aa695/tests/unit_tests/storage/test_local_storage.py#L385-L389

**Comment by frode-aarstad** [comment]
The issue here is if we should allow SummaryConfigs with no keys. When reading summary and this is the case we throw an exception. 

[read_from_file](https://github.com/equinor/ert/blob/6895be5119c0769fdd5899f75d6be571459df206/src/ert/config/summary_config.py)

**Comment by eivindjahren** [comment]
> The issue here is if we should allow construction of `SummaryConfig` with no keys. When reading summary and this is the case we throw an exception.
> 
> (https://github.com/equinor/ert/blob/6895be5119c0769fdd5899f75d6be571459df206/src/ert/config/summary_config.py)

Can the bug be triggered by putting `SUMMARY ""` in the config file?

**Comment by eivindjahren** [comment]
It might be that all we need is to update the documentation of `RealizationStorageState`. I'll have a check.

**Comment by eivindjahren** [comment]
Storage is quite inconsistent with what it considers "HAS_DATA". Usually, a forall quantifier in front of an empty collection is considered True (see https://en.wikipedia.org/wiki/Vacuous_truth). That is why `all([]) == True`. 

However, when `LocalEnsemble.response_configuration` is empty, `_all_responses_exist_for_realization` returns `False`, but if `LocalEnsemble.response_configuration` contains an `SummaryConfig` without keys, you get `True`.

**Comment by eivindjahren** [comment]
Just for conversation, I threw together the following to see if it this is possible: https://github.com/equinor/ert/pull/7150. I still need to check whether this change works correctly everywhere. Perhaps @oyvindeide has more insights on why `_all_responses_exists` is defined the way it is today.

**Comment by eivindjahren** [comment]
After looking a bit closer at it, that solution seems to not be possible as it would break with current behavior that
summary keys from `HISTORY_OBSERVATION` is added to the summary config if missing.

**Comment by eivindjahren** [comment]
It seems like this issue is less problematic than first anticipated so we can lower the severity of the bug at least.
