### ISSUE TITLE
Testing release 2024.02.rc-py38 fails on Drogon 24.0.0 | ES-MDA with Correlation-Based Adaptive Localization

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#7087]
**Describe the bug**
Fails `Update 2` has completed with:

"No dataset 'SWITCHES' in storage for realization 35"

Note that `SWITCHES` consists of all `CONST` variables and was recently added to Drogon.

**To reproduce**
Steps to reproduce the behaviour:
1. Run Testing release 2024.02.rc-py38 fails on Drogon 24.0.0 | ES-MDA with Correlation-Based Adaptive Localization

**Expected behaviour**

**Environment**
 - ERT/Komodo release: 2024.02.rc-py38
 - Remote/HPC execution involved: yes

**Comment by oyvindeide** [comment]
Duplicate of: https://github.com/equinor/ert/issues/7055
