### ISSUE TITLE
flaky: gui tests are hanging on mac

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7099]
Seems to be due to scheduler failing in a fixture which runs poly example

https://github.com/equinor/ert/actions/runs/7758028506/job/21158986503
https://github.com/equinor/ert/actions/runs/7782033887/job/21217747834
https://github.com/equinor/ert/actions/runs/7840085345/job/21394152169

**Comment by eivindjahren** [comment]
Haven't seen this as much any more so I am assuming it is either fixed or: https://github.com/equinor/ert/issues/7123

**Comment by xjules** [comment]
Not spotted since, closing this one!
