### ISSUE TITLE
Cannot edit configurations with non-ascii characters

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#713]
From `#ert-users`:
>  I'm getting this error when trying to edit the config file directly in ERT:
> 
```
Traceback (most recent call last):
   File "/prog/res/komodo/2020.02.01-py27/root/lib/python2.7/site-packages/ert_gui/tools/ide/configuration_panel.py", line 87, in save
     f.write(self.ide_panel.getText())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 33374-33375: ordinal not in range(128)
``` 
> 
> It turns out that this is related to this character in a comment in the config file: Ã. Use of that character is just a typo and will be removed, but there is no obvious error or problem appearing in the GUI, just in the terminal. A pop up box or some GUI indication of problems would be nice.
> We have had this character in the config file for a long time and it has not been a problem before. We don't usually edit the files in ERT, so it's not necessarily in the latest version this has become a problem.

**Comment by markusdregi** [comment]
Was this resolved by #886?

**Comment by sondreso** [comment]
Yes, this is the same problem as that PR solved :slightly_smiling_face: (Interesting that they did not report that this also deleted their config file :thinking:)

**Comment by markusdregi** [comment]
Maybe they did not realise? Anyway, I'm closing this one!
