### ISSUE TITLE
Running poly with Scheduler and mocked Torque queue hangs

### ISSUE THREAD

**Issue by berland** [equinor/ert#7138]
It should be possible to manipulate `$PATH` and then run the poly_example with the new scheduler and the mocked scripts that translates Torque to local queue:

Something like
```
export PATH=<something>/tests/integration_tests/scheduler/bin:$PATH
ert ensemble_experiment --enable-scheduler poly_torque.ert
```

(where `poly_torque.ert` is just `poly.ert` with `QUEUE_SYSTEM TORQUE`)

This currently hangs with realizations just pending.

**Comment by eivindjahren** [comment]
May be related to #7099

**Comment by jonathan-eq** [comment]
I am writing the integration test, I forgot that I had automerge on for the previous PR...

**Comment by jonathan-eq** [comment]
I have written an integration test, but it takes 2.5 minutes to run ensemble experiment. The logs show a lot of:
```
Failed to get torque job id from file: /tmp/enkf-submit-std-cQ853n 
qsub command: qsub 
qsub output:  Unprocessed option ?
```

**Comment by berland** [comment]
"enkf-submit-std" is a proof that you are getting output from the legacy C driver..

**Comment by jonathan-eq** [comment]
Related to #7156
