### ISSUE TITLE
Poly-case with new torque/pbs driver and new scheduler does not work

### ISSUE THREAD

**Issue by berland** [equinor/ert#7143]
Tested on azure:

`(bleeding-py38) [havb@s034-lcatop01:~/projects/ert/test-data/poly_example] main$ ert ensemble_experiment --enable-scheduler poly_torque.ert`

This hangs (the 10 realizations seem to go from pending to running state and then back to pending).

Observe with `watch -n 1 qstat` in another terminal the submission process. 
    

```
$ diff poly.ert poly_torque.ert
3,4c3,4
< QUEUE_SYSTEM LOCAL
< QUEUE_OPTION LOCAL MAX_RUNNING 50
---
> QUEUE_SYSTEM TORQUE
> QUEUE_OPTION TORQUE QUEUE permanent
10c10
< NUM_REALIZATIONS 100
---
> NUM_REALIZATIONS 10
```

**Comment by xjules** [comment]
Tested with poly example and worked. Related fixes:
 - https://github.com/equinor/ert/pull/7178
 - https://github.com/equinor/ert/pull/7165/
 - https://github.com/equinor/ert/pull/7153
