### ISSUE TITLE
CLI workflows bypass WorkflowRunner and generally disjoint from GUI workflows

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#719]
CLI workflows use `Workflow` directly, whereas the GUI uses `WorkflowRunner`.

I think a major refactor is required to satisfy this, since this code is already burdened by technical debt.

- Whether a `Workflow` is running or not, is a state derived from **four** states: the `Thread`, `ThreadPoolExecutor`, `__running` on the `Workflow` and `__running` on the `WorkflowJob`.
- Running an external script via the GUI creates a `Thread` running a `ThreadPoolExecutor` which in turn runs a blocking `Popen`. Instead of using `join` or `wait` in the respective concurrent classes, it polls the workflow's `isRunning` every two seconds, inviting TOCTOU problems like equinor/libres#913.
- Cancelling workflows could be attempted by killing the topmost `Thread`, instead it is propagated to the _current_ workflow using booleans, again inviting TOCTOU issues.
- The `WorkflowRunner.exception` uses `_exception` directly, violating thread safety which is possible with `exception()`.
- https://github.com/equinor/ert/issues/608 is simply impossible to solve in `Workflows` current state
- Signals/Slots is not properly utilized in the GUI. Using a worker-object pattern, the UI code would be greatly simplified, and thread-safe.

**Comment by eivindjahren** [comment]
There has bee a lot of refactoring related to this. Perhaps we can close it?

**Comment by eivindjahren** [comment]
I am closing this now as both gui and cli uses WorkflowRunner.
