### ISSUE TITLE
Deprecate LSF options LSF_LOGIN_SHELL, LSF_SERVER, LSF_RSH_CMD

### ISSUE THREAD

**Issue by berland** [equinor/ert#7203]
The remote shell feature is not meant to be ported to the Python LSF driver.

`ert-configurations` currently set `LSF_SERVER` to some ssh-able machine, and thus this is the dominant code path used in the current C driver.

Some komodo release must change this to activate the local shell before we move to the Python driver (that will only use the local shell). This change should be done with a warning, and for users getting into trouble, it should be possible for them to set LSF_SERVER in their config to reinstate the old behaviour.

Definition of done:
* ERT default is to use local shell for bsub/bjobs/bkill.
* Deprecation warnings are emitted while parsing the config, stating that these keywords have no effect and can safely be removed.
* Removal from documentation

The functionality will be gone from ERT whenever the legacy C LSF driver is purged.

**Comment by berland** [comment]
Test results:

Komodo bleeding as of 2024-02-20 does not set LSF_SERVER, and `ssh` is not part of the jobqueue log (proving the different code path in the driver is employed.

Manual test of poly-case on LSF-cluster without LSF_SERVER set:
* [x] Harstad (No need to test, cluster is decommisioned)
* [x] Rio 
* [ ] Bergen
* [ ] Stavanger
* [ ] Trondheim/Stjørdal
* [ ] StJohn

**Comment by jonathan-eq** [comment]
Should the deprecation warnings inform the user that the options have already been deprecated, or that they will be deprecated in the migration to scheduler? Also, should the old behaviour stay in the C driver, or should we remove it there too?

**Comment by jonathan-eq** [comment]
> > Was some of this already deprecated in [c16c917](https://github.com/equinor/ert/commit/c16c91718d827e6cef24d1632d20c1faa06a8ac7)?
> 
> No

It seemed like LSF_SERVER was a keyword before it was a queue_option. That was the deprecation warning from earlier :)
