### ISSUE TITLE
Evaluate the created API towards the Equinor API strategi

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#721]
Equinor has a API Strategy and we should aline with it. One should evaluate the work done and identify improvements for future work.

https://github.com/equinor/api-strategy

**Comment by sondreso** [comment]
For now the key take away from the API strategy is that we are using the preferred API style in Equinor (REST), and that we are focusing on the [design principles for APIs](https://github.com/equinor/api-strategy/blob/master/docs/strategy.md#design-principles).

However, when we go for a central API we need to consider all the points mentioned under [API Security](https://github.com/equinor/api-strategy/blob/master/docs/strategy.md#api-security).

Closing this for now :)

**Comment by sondreso** [comment]
Also note that the current implementation aims for a higher maturity level of the REST then what the Equinor guidelines specifies (level 2), as  we have some resource discovery that belongs under _the concept of "Hypermedia as the engine of application state" (HATEOAS)._
