### ISSUE TITLE
Fix tests/integration_tests/test_cli.py::test_that_stop_on_fail_workflow_jobs_stop_ert

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7212]
**Describe the bug**
The test checks that the ert workflow fails, but it passes for the incorrect reasons. The script ran is 
```
 
#!/bin/bash
ekho helo wordl
STOP_ON_FAIL=False
```
and the idea seems like it sees misspelled `echo` and fails on that, but it is actually failing on the empty line before the shebang.
```
RuntimeError: Workflow job failjob failed with error: [Errno 8] Exec format error: '/private/var/folders/7h/phfnnlw16x952zg3m4vgct_c0000gp/T/pytest-of-JONAK/pytest-394/poly_example5/test_data/failing_script_w_stop.sh'
  Traceback (most recent call last):
    File "/Users/JONAK/Documents/FMU/SCOUT/ert/src/ert/config/ert_script.py", line 99, in initializeAndRun
      return self.run(*arguments)
    File "/Users/JONAK/Documents/FMU/SCOUT/ert/src/ert/config/external_ert_script.py", line 27, in run
      self.__job = Popen(command, stdout=PIPE, stderr=PIPE)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1863, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 8] Exec format error: '/private/var/folders/7h/phfnnlw16x952zg3m4vgct_c0000gp/T/pytest-of-JONAK/pytest-394/poly_example5/test_data/failing_script_w_stop.sh'
  ```
  Fixing this made 
**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. …

**Expected behaviour**

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by berland** [comment]
Hmm, when I have such a script with this additional newline, I get the correct response from:
```
$ cat failing_script.sh 

#!/bin/bash
ekho helo wordl
STOP_ON_FAIL=TRUE
$ ./failing_script.sh 
./failing_script.sh: line 3: ekho: command not found
```

**Comment by jonathan-eq** [comment]
It seems like the STOP_ON_FAIL keyword found in the executed script should have precedence over the one set in the config.
