### ISSUE TITLE
bjobs parser in Scheduler cannot parse corner-case bjobs output

### ISSUE THREAD

**Issue by berland** [equinor/ert#7221]
The current bjobs parser will split the bjobs lines on `str.split()`. Based on the following example output this might fail at some point:

```
[havb@stjohn-linrgs006 ~]$ bjobs -u all
JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
475819  xxxx    RUN   allcpus    stjohn-grid 2*stjohn-rs *PP_R002_2 Feb  9 21:41
479460  xxxx    RUN   allcpus    stjohn-rst0 3*stjohn-rs DB_44-46   Feb 14 13:07
                                             4*stjohn-rst05-05-10
480219  xxxx    RUN   mr         stjohn-grid 3*stjohn-rs *3 12578 0 Feb 19 15:24
474358  f_lsf   PEND  maintain   stjohn-rst0             *t-t030310 Feb  7 23:30
```

This output indicates that records might span multiple lines, and that empty fields are filled with whitespace, thus field parsing should probably be fixed width instead of `str.split()`. This is probably not an issue for the current driver as it only cares about the three first fields, but support of this format should be asserted in testing.

**Comment by jonathan-eq** [comment]
What does it mean when the new line only has exec_host and job_name? Does it share the JOBID, USER, and other fields with the job above it?

**Comment by berland** [comment]
> What does it mean when the new line only has exec_host and job_name? Does it share the JOBID, USER, and other fields with the job above it?

In this example we see first that EXEC_HOST is split over two lines, and on the subsequent lines that field is not truncated (for job 479460). Then we see that EXEC_HOST is blank for 474358)

**Comment by jonathan-eq** [comment]
By `support of this format should be asserted in testing.`, do you mean we should fix the way we parse the output, or make sure it does not crash our parser? As you said, we only use the first three fields, so it should not affect us

**Comment by berland** [comment]
As in "does not crash". We want to ensure that future changes to the parsing for some future feature will not crash on this particular output.
