### ISSUE TITLE
Failed realization shows as successful (or vice versa?)

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#7225]
**Describe the bug**
A successfully run realization shows up with an error in the GUI. Might be related to restart

<img width="1181" alt="Screenshot 2024-02-21 at 10 29 20" src="https://github.com/equinor/ert/assets/11595637/845d8ad9-485e-427e-a7dc-7a2ad9f7e36c">

**To reproduce**
Steps to reproduce the behaviour:
0. Use this as the main content in `poly_eval.py`:
```
if __name__ == "__main__":
    if random.random() > 0.6:
        sys.exit(2)

    if random.random() > 0.8:
        time.sleep(60)

    coeffs = _load_coeffs("parameters.json")
    output = [_evaluate(coeffs, x) for x in range(10)]
    with open("poly.out", "w", encoding="utf-8") as f:
        f.write("\n".join(map(str, output)))
```
2. Run poly example in gui
3. There will be some realizations that are successful but also show an error.

**Expected behaviour**
It should not show an error if run successfully

**Environment**
 - OS: MacOS 13.4
 - ERT/Komodo release: Bleeding
 - Python version: 3.10
 - Remote/HPC execution involved: no

**Comment by yngve-sk** [comment]
Still happens if running for example snake oil with many realizations on RGS
![Screenshot 2024-04-23 at 13 48 04](https://github.com/equinor/ert/assets/11595637/89f51c34-a693-4a20-ad60-e5521126a0fa)

**Comment by DanSava** [comment]
Can no longer reproduce closing the issue again.
