### ISSUE TITLE
Add support for KEEP_QSUB_OUTPUT in OpenPBS driver

### ISSUE THREAD

**Issue by berland** [equinor/ert#7233]
First, check whether output of job_dispatch.py is logged anywhere. If it is, then don't implement this option.

**Comment by jonathan-eq** [comment]
It is logged to job-runner-log. Can this be closed?

**Comment by berland** [comment]
> First, check whether output of job_dispatch.py is logged anywhere. If it is, then don't implement this option.

We cannot be sure where it is logged (the `logs` directory might not exist on the compute side f.ex). So this option is needed.

`KEEP_QSUB_OUTPUT` means that the stdout and stderr from anything sent to `qsub` is redirected somewhere. In OpenPBS terms, it means the `-k` option sent to `qsub`, and potentially the `-o` and `-e` option. 

Example:
`$ qsub -q permanent -- /bin/echo yayy`
If you run this through, you will not find "yayy" anywhere on disk, it is completely lost. 

If you say that you want to keep stdout, do
`$ qsub -q permanent -k o -- /bin/echo yayy`
then:
```
$ cat $HOME/STDIN.o513684
yayy
```

**Comment by jonathan-eq** [comment]
Commit https://github.com/equinor/ert/commit/e87e86a reverted the meaning of the -k flag. It seems very flaky, and the documentation is self-contradicting. 
```
-k <discard>
               Specifies whether and which of the standard output and standard error streams is left behind on the execution host, or written to their final destination.  Sets the job's Keep_Files attribute to discard.  Overrides default path names for these streams.  Overrides -o and -e options.

               Default: n; neither is retained, and files are not written to their final destinations.

               In the case where output and/or error is retained on the execution host in a job-specific staging and execution directory created by PBS, these files are deleted when PBS deletes the directory.

               The discard argument can take the following values:

               e    The standard error stream is retained on the execution host, in the job's staging and execution directory.  The filename is
                       <job name>.e<sequence number>

               o    The standard output stream is retained on the execution host, in the job's staging and execution directory.  The filename is
                       <job name>.o<sequence number>

               eo, oe
                    Both standard output and standard error streams are retained on the execution host, in the job's staging and execution directory.

               d    Output and/or error are written directly to their final destination.  Overrides action of leaving files on execution host.

               n    Neither stream is retained.
```
On my machine, it kept stdout and stderr with and without the -k flag. How should I go about implementing this?

**Comment by berland** [comment]
Running as `f_scout_ci` I get the same behaviour as `jonak`s user, you get the stdin/stderr files by default.

Adding `-j oe -o /dev/null -e /dev/null` makes them go away.

**Comment by berland** [comment]
Seemingly, `qsub` can make the stdin and stderr files go away, thus the option "KEEP_QSUB_OUTPUT" does not really make sense and should probably be deprecated.

What we want is perhaps to always have PBS write these files, but to a location ERT controls, and then let ERT do cleanup and purge zero-length stdout/stderr files.
