### ISSUE TITLE
Support or deprecate CLUSTER_LABEL and JOB_PREFIX in openpbs-driver

### ISSUE THREAD

**Issue by berland** [equinor/ert#7235]
There are two string options that are quite trivial to add to the OpenPBS driver that the current torque_driver.cpp supports:

* CLUSTER_LABEL (goes into the resource string)
* JOB_PREFIX (prepended to the job name when submitting)

These are not found in the logs for the last three months, but 3 months might not be representative. 

Either implement support, or deprecate them.

**Comment by xjules** [comment]
As both options were ported to openpbs closing this issue.
