### ISSUE TITLE
OpenPBS driver should consider to support C and E states

### ISSUE THREAD

**Issue by berland** [equinor/ert#7255]
The legacy torque_driver.cpp will interpret "C" and "E" from qstat as a finished realization, while the new driver will not.

This might not be OpenPBS specific, as the "F" state was not in the driver prior to testing on the Azure cluster.

**Comment by xjules** [comment]
The `C` output is only produced by TORQUE so this could be ignored for now.
`E` (exiting) can be ignored also as we expect the finished state afterwards when polling.

**Comment by xjules** [comment]
Closing this issue as we decided not to implement those options for now.
