### ISSUE TITLE
Realizations have finished but still reported as running in the GUI

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7262]
**Describe the bug**
A user has run 100 realizations (On LSF) where even after 20 hours some realizations were reported as `running` despite they have completed or were cancelled due to the MAX_RUNTIME.
There were 18 realizations which were killed due to MAX_RUNTIME. They were correctly killed and the status was set to `JOB_QUEUE_IS_KILLED` but was not propagated further to GUI. Side note: All the events in the dispatcher were processed correctly.
There were 27 realizations that failed due to the Eclipse errors, but MIN_REALIZATION was set to `1%`, ergo it should have continued to the next iteration but it didn't.
it failed on iter-0.

**Expected behaviour**
The ert should correctly label those realizations are CANCELLED - `The run is cancelled due to reaching MAX_RUNTIME` and not label them as still running.

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2024.02.01
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Additional context**
The user will rerun and provide more logs and screenshots.

Internal link to report: https://equinor.slack.com/archives/CDPJULWR4/p1708420458814319

**Comment by oyvindeide** [comment]
Have not been able to reproduce this, and no more reports of it happening. Made some changes based on some log files, but no reports of this happening: https://github.com/equinor/ert/commit/5933a64d18503c2b128f8304cb54defade8ef197
