### ISSUE TITLE
Integration tests with --lsf does not work

### ISSUE THREAD

**Issue by berland** [equinor/ert#7317]
This test will not pass if you try to run it towards a real LSF cluster due to `tmp_path` not being a network mounted location.

https://github.com/equinor/ert/blob/983719d049443e0ab959a1472581e9f7954b50ca/tests/integration_tests/scheduler/test_lsf_driver.py#L51

**Comment by pinkwah** [comment]
This is also the case for OpenPBS for the same reason. I can't think of a simple test that proves the script has been executed without touching the filesystem.

Maybe we can introduce a `nfs_tmp_path` fixture that uses the user's home directory?

**Comment by berland** [comment]
The same problem has been solved here:

https://github.com/equinor/komodo-releases/blob/dc4952c3e154030eadfa6ad0064369e88fbac60a/.github/workflows/run_bigpoly.yml#L182-L192

**Comment by berland** [comment]
For this to work on PBS we need a way to set the queue name to "permanent"

**Comment by pinkwah** [comment]
> For this to work on PBS we need a way to set the queue name to "permanent"

I would maybe change it so that the pytest option for PBS takes queue name as argument. Same for LSF. So, `pytest [...] --openpbs=permanent`.
