### ISSUE TITLE
Exiting state in PBS driver must emit a FinishedEvent

### ISSUE THREAD

**Issue by berland** [equinor/ert#7325]
Integration testing has revealed that jobs linger in the "Exiting" state for many minutes before entering "Finished" state. The driver will wait until the Finished state before it deems a realization done.

There is a belief that the Exit_status might not be available in the "Exiting" state, but sample testing reveal that it is. Not sure if that is a timing issue, and that there might be situations where Exit_status is not ready in the Exiting state.

https://github.com/equinor/ert/blob/f26a69942191141f1d29998f2fb4010655096502/src/ert/scheduler/openpbs_driver.py#L48C1-L52C1

**Comment by berland** [comment]
The legacy C driver treats the E state equal to F state.

**Comment by pinkwah** [comment]
I think we can assume that E and F have the same state. I have no good reason for only checking one of them.

**Comment by berland** [comment]
Yes, assume they are the same, and error hard if Exit_status is not present (then fix that problem if it occurs).
