### ISSUE TITLE
AttributeErrors and TypeErros when a CLI run fails

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#733]
__Steps to reproduce:__
1. Modify `poly_normal` or some other simple project to fail (ie, by `sys.exit(1)`)
2. In `testing-py2`, run `ert ensemble_experiment poly.ert`

Observe output:
```
20 active job(s) failed.

    --> Running ensemble experiment...

    1/1 |██████████████████████████████| 100% Running time: 14 seconds

    ■ Finished         0/20
    ■ Failed          20/20
    ■ Running          0/20
    ■ Unknown          0/20
    ■ Pending          0/20
    ■ Waiting          0/20

Simulations failed with the following error: Simulation failed! All realizations failed!
Exception AttributeError: "'NoneType' object has no attribute 'PY2'" in <object repr() failed> ignored
Exception TypeError: 'super() argument 1 must be type, not None' in <bound method EnkfFsManager.__del__ of EnkfFsManager() at 0x2c45040> ignored
Exception AttributeError: "'NoneType' object has no attribute 'PY2'" in <object repr() failed> ignored
```

Similar problems have been fixed in the GUI by calling the following function before exiting the program and letting Python clean itself:
https://github.com/equinor/ert/blob/master/ert_shared/__init__.py#L3-L16

It should be noted that this is a Python 2-only problem. Python 3 fixes how it does cleanup and thus `__del__` behaves correctly.

**Comment by markusdregi** [comment]
I've reproduced this error in the `2020.03`, `2020.02` and `2019.12` release. Hence, although it should be fixed I don't consider this a release blocking error.
