### ISSUE TITLE
Alternatives to flaky?

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#7332]
Using flaky as it is now will require us to pin pytest to `<8.1.0`. Flaky is kind of a stale project and imports from the private namespace of pytest, if there is a less stale alternative we should use that instead. Maybe https://pypi.org/project/pytest-retry ?

Related: https://github.com/box/flaky/issues/198

**Comment by The-Compiler** [comment]
Might want to look at https://github.com/pytest-dev/pytest-rerunfailures
