### ISSUE TITLE
Write a summary of performance between running JobQueue and Scheduler on bigpoly

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7342]
Here is the summary of the big-polycase runs:

---
**Testing pbs: old JobQueue vs the scheduler**

| run  | pbs-old-#events | pbs-old-proc. time | pbs -#events  | pbs-proc. time |
|------|-------|------|------|------|
| 01.03.24 | -- | -- | 3127 | 0.454233 |
| 02.03.24 | 11324 | 4.734553 | 3462 | 0.259707 |
| 03.03.24 | 13906 | 2.924335 | 3078 | 0.288346 |
| 04.03.24 | 14120 | 4.637057 | 3078 | 0.300214 |
| 05.03.24 | 23822 | 8.233750 | 3194 | 0.323301 |
| 06.03.24 | -- | -- | 3161 | 0.351420 |

---
**Testing lsf: old JobQueue vs the scheduler**

| run  | lsf-old-#events  | lsf-old-proc.time | lsf-#events  | lsf-proc.time |
|------|-------|------|------|------|
| 01.03.24 | 2882 | 0.998961 | 1748 | 0.496111 |
| 02.03.24 | 3065 | 0.856666 | 2773 | 0.669724 |
| 03.03.24 | 3064 | 0.823959 | 4108 | 0.625406 |
| 04.03.24 | 3182 | 0.688947 | 4968 | 0.508051 |
| 05.03.24 | 2299 | 0.689068 | 1365 | 0.534092 |
| 06.03.24 | 1519 | 0.557990 | 1642 | 0.565293 |

---
**Average for PBS**
Average of pbs-old-#events: 15,793
Average of pbs-old-proc. time: 5.1324 seconds
Average of pbs-#events: 3,183.33
Average of pbs-proc. time: 0.3295 seconds 

**Average for LSF**
Average of lsf-old-#events: 2,668.5
Average of lsf-old-proc. time: 0.7693 seconds
Average of lsf-#events: 2,767.33
Average of lsf-proc. time: 0.5664 seconds ​

**Comment by berland** [comment]
🥓
