### ISSUE TITLE
Remove invalid characters from OpenPBS job names

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#7349]
In particular, slashes are problematic:
```
qsub -Nfoo/bar -- true  # Fail
qsub -Nfoobar -- true  # Success
```

**Comment by eivindjahren** [comment]
So when we use `ECLBASE` for jobname, we should really use `os.basename(eclbase)`. And `ert.config` should validate the job name.

**Comment by berland** [comment]
The old job_queu_node solves it like this:

https://github.com/equinor/ert/blob/7f656ef2854295a5ebc086e01eee4d721bae6a84/src/ert/job_queue/job_queue_node.py#L98
