### ISSUE TITLE
Summary data saved to storage with ert<8.4 is loaded as float64

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7403]
This can be reproduced by removing the `astype(np.float32)` from the following line:
https://github.com/equinor/ert/blob/0d1b285e0b88c70770ffad820cec1ccf02fe10a0/tests/integration_tests/test_storage_migration.py#L141

**Comment by oyvindeide** [comment]
We need to migrate storages from older versions by converting the summary data from float64 to float32. This problem occured originally because it was read in float32, but converted to float64 by `resdata`, and we just saved what we got.
