### ISSUE TITLE
Make it possible for plugins to subtype ForwardModel

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7409]
Currently, making e.g. [pyscal](https://github.com/equinor/semeio/blob/main/src/semeio/forward_models/scripts/fm_pyscal.py) form [semeio](https://github.com/equinor/semeio) available as a forward model in ert means creating a [config file](https://github.com/equinor/semeio/blob/main/src/semeio/forward_models/config/PYSCAL_CONFIG),  and pointing ert to it with the plugin interface method `installable_jobs()` (done [here](https://github.com/equinor/semeio/blob/c397b16cf5a23879c14f5d8fbea4dd3ace25fda5/src/semeio/hook_implementations/forward_models.py#L41)).

From there, it is inserted into the site config and read here: https://github.com/equinor/ert/blob/006499cff7d98620446c45872d8d92985dd512bb/src/ert/config/ert_config.py#L684-L708

This makes it difficult to add additional validation of the setup such as valid version number etc.

In order to remedy this, the suggestion is that the plugin interface is extended so that e.g. fm_pyscal can be implemented as a subtype of `ForwardModel`. The specifics of a forward model read from a config file would have to also be pushed out into subtype of `ForwardModel` e.g. `ConfigFileForwardModel`, so that `ForwardModel` is an abstract baseclass.

In this way the PYSCAL forward model could be implemented like this:

```python
class Pyscal(ForwardModel):
    def __init__(self):
        super().__init__(
            name="PYSCAL",
            executable="fm_pyscal",
        )

    def create_arguments(self, **parameters:str) -> List[str]:
        ...
```

where create_arguments is responsible for handling default values and validating parameters.

**Comment by sondreso** [comment]
I think this looks like a good approach! I think we can make a draft based on this suggestion and discuss based on that.

One thing that isn't mentioned in the text above is that it is important that there is a good way for plugins to report configuration errors, and that they show up in the GUI the same way as the errors from normal config parsing.

**Comment by sondreso** [comment]
We also need to setup plugin hooks for the plugins to register subtypes of `ForwardModel`

**Comment by eivindjahren** [comment]
@yngve-sk Just got word that the typical use-case is that e.g. the `ECLIPSE100` forward model step would like to check that the version given is installed so that

```
        FORWARD_MODEL ECLIPSE100(<VERSION>=smersion, <NUM_CPU>=42)
```

fails as there is version of the eclipse simulator installed called "smersion".
