### ISSUE TITLE
Differences between CLI and GUI for Ensemble Smoother

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#7415]
Ensemble smoother in CLI accepts `--current-case` and `--target-case` where `--current-case` is set to `default` by default, and `--target-case` is required.

The GUI accepts `Case format` only:

![image](https://github.com/equinor/ert/assets/45088507/661cd66d-8d4a-48d3-b194-a39939197bb7)

By default, running via GUI produces two ensembles; `default_0` and `default_1`.

The CLI does not support "%d" so this will fail:

```
ert ensemble_smoother poly.ert --target-case 'hei_%d'
```

I suggest we replace `Case format` in the GUI with `Prior ensemble` and `Posterior ensemble`, and replace `--current-case` and `--target-case` with `--prior-ensemble` and `--posterior-ensemble` in the CLI.

**Comment by oyvindeide** [comment]
This has been reworked to be aligned between the gui and the cli, and:
```ert ensemble_smoother poly.ert --target-case 'hei_%d'``` now works.
