### ISSUE TITLE
LSF and Torque drivers differ in submit arguments

### ISSUE THREAD

**Issue by berland** [equinor/ert#7422]
The LSF-driver (legacy C version) adds the runpath in 
https://github.com/equinor/ert/blob/main/src/clib/lib/job_queue/lsf_driver.cpp#L305C1-L306C34

while the torque-driver does not:
https://github.com/equinor/ert/blob/main/src/clib/lib/job_queue/torque_driver.cpp#L356C1-L364C17

This discrepancy is not wanted and potentially not intentional.

`job_dispatch.py` will handle the runpath argument if it is provided and `cd` to it (what happens for LSF driver). When the torque driver is in use, the runpath is injected in
https://github.com/equinor/ert/blob/main/src/clib/lib/job_queue/torque_driver.cpp#L497C1-L517C2

**Comment by xjules** [comment]
This has been fixed already #7396
