### ISSUE TITLE
test_lsf_info_file_in_runpath fails in integration test

### ISSUE THREAD

**Issue by berland** [equinor/ert#7425]
This function fails when run on a real LSF cluster. This happens during komodo nightly tests through `ci/testkomodo.sh`, at least on RHEL8

https://github.com/equinor/ert/blob/802375058dbcc08709945c84088133b7375ac935/tests/integration_tests/scheduler/test_lsf_driver.py#L24C1-L28C64

**Comment by JHolba** [comment]
could not find this error in logs for any recent komodo nightly run. closing the issue
