### ISSUE TITLE
Clean up scheduler execute method

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7437]
Continuation of #7421
Scheduler execute method should not rely on cancelling scheduling tasks, but should instead set a flag to have them stop.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. …

**Expected behaviour**

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by xjules** [comment]
Closing this one as this might not be required and also the "clean" solution might too complex.
