### ISSUE TITLE
Flaky test_openpbs_driver_with_poly_example_failing_poll_fails_ert_and_propagates_exception_to_user

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#7453]
tests/integration_tests/scheduler/test_openpbs_driver.py::test_openpbs_driver_with_poly_example_failing_poll_fails_ert_and_propagates_exception_to_user
failed at least once on python3.11

https://github.com/equinor/ert/actions/runs/8278996254/job/22652576712?pr=7450#step:9:668

**Describe the bug**
A test fails

**To reproduce**
Steps to reproduce the behaviour:
It is flaky. Probably need to rerun the test several times to get the error.

**Expected behaviour**
All tests should always pass

**Environment**
 - github action
 - Python version 3.12

**Comment by JHolba** [comment]
this may also be related?
https://github.com/equinor/ert/actions/runs/8278986970/job/22652560955?pr=7452#step:8:4156

**Comment by dafeda** [comment]
Got this one here:
https://github.com/equinor/ert/actions/runs/8340790463/job/22825569442?pr=7476

**Comment by eivindjahren** [comment]
Also here:
https://github.com/equinor/ert/actions/runs/8343330374/job/22833426871

**Comment by jonathan-eq** [comment]
This was blocking PRs, so I marked it with `pytest.mark.skip` in https://github.com/equinor/ert/commit/11f9b15a297e0dae84b96643b28ab8462566b1a6
