### ISSUE TITLE
ERT crashes if result file from forward model is empty

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#7457]
**Describe the bug**
If a GEN_DATA result file exists, but is empty, ert will crash completely.

**To reproduce**
Steps to reproduce the behaviour:
1. Open poly_eval.py
2. Change the last line to for example: pass, so a file is created, but it is empty
3. Run experiment (one that includes an update) and observe that ert crashes with:

```
  File "/Users/OYVEID/projects/ert/ert/src/ert/gui/simulation/run_dialog.py", line 343, in _on_ticker
    @Slot()

  File "/Users/OYVEID/projects/ert/ert/src/_ert/threading.py", line 71, in _handler
    raise current_exception
_ert.threading.ErtThreadError: unsupported operand type(s) for *: 'int' and 'NoneType' in thread 'ert_gui_simulation_thread'
[1]    86463 abort      ert gui poly.ert
```

**Expected behaviour**
Previous behavior was that the realization was marked as a success (maybe because of GENDATA_RFT?), so for now would expect the same, though we might want to change behavior in the future.

**Comment by oyvindeide** [comment]
Checked a bit more into previous behavior, this would always cause an error if the missing response was observed, but ert would not crash, and the error message was more readable. The error came when doing the update step, meaning that the realization was never marked as failed.

**Comment by dafeda** [comment]
Related to this issue created by @eivindjahren :

https://github.com/pydata/xarray/issues/8693

**Comment by oyvindeide** [comment]
Yes, but the difference now is that it crashes all of ert, which may mean that other errors could do the same?

**Comment by dafeda** [comment]
We raise `ValueError` if a summary file is empty:

https://github.com/equinor/ert/blob/cf6005e3eb9abf05a03380e8bfe2a8db7d70b340/src/ert/config/summary_config.py#L20-L47

Is it reasonable to do the same for gen data?

**Comment by oyvindeide** [comment]
I _think_ we used to do that, however if is not observed, that might fail a forward model which did not need to fail, if that makes sense? Will go a bit back in history to check, think we made some changes on this around version 5
