### ISSUE TITLE
Ert JobQueue Lsf Driver not working with LSF_RESOURCE option in example

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7474]
**Describe the bug**
When using the old C lsf driver with the LSF_RESOURCE option provided in ert documentation, it fails on bsub
```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/private/jonak/Documents/ert/src/ert/services/_base_service.py", line 48, in cleanup_service_files
    raise OSError(f"Signal {signum} received.")
OSError: Signal 2 received.
Failed to get lsf job id from file: /tmp/enkf-submit-eEJoJs
bsub command                      : bsub
Error in rusage section. Job not submitted.
```

The option in question:
```
QUEUE_SYSTEM LSF
QUEUE_OPTION LSF LSF_RESOURCE rusage[mem=512MB:swp=1GB]
```

**To reproduce**
Steps to reproduce the behaviour:
1. ``
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. Ert fails on submit.

**Expected behaviour**
Submit works with bsub -

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version py3.8
 - Remote/HPC execution involved: Yes

**Additional context**

**Comment by berland** [comment]
Solved in #7654
