### ISSUE TITLE
Hide RMS error traceback and instruct users to look for logs

### ISSUE THREAD

**Issue by berland** [equinor/ert#7477]
**Is your feature request related to a problem? Please describe.**
A user may get output from ERT like this when RMS fails for whatever reason:
![image](https://github.com/equinor/ert/assets/306834/713d65fb-9a2b-48cc-98cf-e079b059d741)

Since this is many lines of "technical" text, it is easy for a user to think that this text actually contains something usable for support personell.

There is no value in the traceback, only the last line is relevant.

**Describe the solution you'd like**
The traceback should be muted. As a bonus, the users should be instructed to look for more information in the RMS log files.

**Describe alternatives you've considered**

**Additional context**

**Comment by berland** [comment]
Duplicate of #1904

**Comment by eivindjahren** [comment]
The plan is now to remove the RMSRunException and use rms-sys: https://github.com/equinor/ert/issues/7859
