### ISSUE TITLE
Change retry submit in scheduler to run unless user cancelled a realization

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#7500]
Currently we retry submit if return code of a job was >128 (a signal killed the job).
It would be better if we kept information about user cancellation in the driver and stopped retries based on that instead.

**Comment by xjules** [comment]
We should write a test which asserts that the job was resubmitted when there was a signal when the job got a signal.
The desired behaviour is to always resubmit unless the job was killed by the user / ert.
