### ISSUE TITLE
Add observation summary when clicking an ensemble in Experiment manager

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#7509]
When clicking an ensemble in the Experiment manager, we would like to show a summary of the loaded observations, and their coverage, for example like:

![Image](https://github.com/equinor/ert/assets/44577479/e717ed6c-7c5d-4cf4-bdb3-397c388c30e1)

![Image](https://github.com/equinor/ert/assets/44577479/d4386f54-434e-495a-94cc-a4ddfc802734)

**Comment by frode-aarstad** [comment]
Does the plot type drawn above have a name? In other words,  can we find this type in a python library like https://seaborn.pydata.org/examples/horizontal_boxplot.html

**Comment by frode-aarstad** [comment]
Maybe something like this for each observation


![Image](https://github.com/equinor/ert/assets/30144033/682c28cd-290d-477c-a256-e32381249afa)
