### ISSUE TITLE
Issue with reading parameter file

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#7545]
**Describe the bug**
Ert encountered the following issue 

**Expected behaviour**
No issue

**Screenshots**
![image](https://github.com/equinor/ert/assets/4508053/76f4e87a-db23-4ed1-b127-12efcf267fa4)

**Comment by tklov11** [comment]
Hi, note also that I get a warning about an unterminated comment starting at line 254. This cannot be line 254 in the input parameter file and has to be in one of the scripts that ert runs.

**Comment by oyvindeide** [comment]
Blocked because we were not able to reproduce, awaiting feedback from user. If anyone is able to reproduce, please remove the blocked label.

**Comment by oyvindeide** [comment]
Not able to reproduce, and did not hear back from user.
