### ISSUE TITLE
Resource description given to LSF fails in Python driver

### ISSUE THREAD

**Issue by berland** [equinor/ert#7550]
**Describe the bug**
```
E           RuntimeError: Command "/global/bin/bsub -R 'rusage=[mem=20MB]' -J dummy 
/private/f_scout_ci/pytest-tmp/tmp.zneeX4MS45/test_lsf_driver_masks_returnco4/.lsf_submit_b75fhab8.sh /private/f_scout_ci/pytest-tmp/tmp.zneeX4MS45/test_lsf_driver_masks_returnco4"
failed after 10 retries with error Error in select section: Error near "rusage" : incorrect section name, 
resource name, or resource function name. Job not submitted.
```
**To reproduce**
Steps to reproduce the behaviour:
Run LSF integration tests.

**Expected behaviour**
No error

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by jonathan-eq** [comment]
I think this test would also fail on the old queue driver

**Comment by jonathan-eq** [comment]
I was wrong. It worked when using double quotes instead of single quotes

**Comment by jonathan-eq** [comment]
I was wrong again, the resource requirement we are attempting to pass (also the one that is in ert docs) is invalid. See #7474
