### ISSUE TITLE
Instances of storage used outside of storage context

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#7564]
Some tests are using storage outside of its context, example:
https://github.com/equinor/ert/blob/cdc90ba3a1c267254d7bccdc957ffe290c2d379a/tests/integration_tests/storage/test_parameter_sample_types.py#L128

```        with open_storage(tmpdir / "storage") as storage:
            prior = storage.get_ensemble_by_name("prior")
            posterior = storage.get_ensemble_by_name("smoother_update")
           ....
        ....
        assert len(prior.load_parameters("MY_PARAM", 0)["values"].x) == 2
        assert len(prior.load_parameters("MY_PARAM", 0)["values"].y) == 3 # <- Loading stuff from storage outside of context
```

Not supposed to be supported behavior. Perhaps it is done other places too, should be tracked down and fixed

Verbose version: 
Storage is only supposed to be accessed from within the context of `with open(storage)`; for example if you get a reference to an ensemble, you are only supposed to read/write from it within that context. If done outside of it, it is to be considered as unsupported/undefined behavior.

**Comment by jonathan-eq** [comment]
I do not understand this issue 100%. The test is opening storage in its tmpdir. Isn't that the expected behavior?

**Comment by jonathan-eq** [comment]
I am not quite sure how to go about `tests/unit_tests/storage/test_local_storage.py::test_open_storage_write_with empty_directory`. Can we refresh storage after storage has been closed? Wouldnt it be better if storage refreshed itself after closing?
