### ISSUE TITLE
Flaky integration test test_tracking_integration.py::test_tracking[using_job_queue-ee_failing_poly_smoother]

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7588]
**Describe the bug**
`FAILED tests/integration_tests/status/test_tracking_integration.py::test_tracking[using_job_queue-ee_failing_poly_smoother] - Failed: Timeout >360.0s` (https://github.com/equinor/ert/actions/runs/8595749537/job/23551154574?pr=7562)

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. …

**Expected behaviour**

**Screenshots**

**Environment**
 - OS: macos-latest
 - ERT/Komodo release: main
 - Python version: 3.12
 - Remote/HPC execution involved: Github Action Runner

**Additional context**

**Comment by jonathan-eq** [comment]
There seem to be events missing. One of the realizations pass, but the other one is still marked with running when the FinishEvent it sent. 
```FAILED tests/integration_tests/status/test_tracking_integration.py::test_tracking[using_scheduler-ee_poly_smoother-28-40] - AssertionError: Failed too many realizations '[RealizationSnapshot(status='Running', active=True, start_time=datetime.datetime(2024, 4, 8, 12, 19, 48, 488116, tzinfo=tzutc()), end_time=None, forward_models={})]'```

**Comment by jonathan-eq** [comment]
Was able to replicate using `pytest tests/integration_tests/status/test_tracking_integration.py::test_tracking -svv -n logical --count 40`

**Comment by jonathan-eq** [comment]
> There seem to be events missing. One of the realizations pass, but the other one is still marked with running when the FinishEvent it sent. `FAILED tests/integration_tests/status/test_tracking_integration.py::test_tracking[using_scheduler-ee_poly_smoother-28-40] - AssertionError: Failed too many realizations '[RealizationSnapshot(status='Running', active=True, start_time=datetime.datetime(2024, 4, 8, 12, 19, 48, 488116, tzinfo=tzutc()), end_time=None, forward_models={})]'`

This might have been fixed in the meanwhile by 4ababea

**Comment by jonathan-eq** [comment]
Closing this as I can no longer reproduce it, even with `--count 80`

**Comment by xjules** [comment]
This test is still flaky and it is failing on job_queue: https://github.com/equinor/ert/actions/runs/8642045014/job/23693611567

**Comment by jonathan-eq** [comment]
> This test is still flaky and it is failing on job_queue: https://github.com/equinor/ert/actions/runs/8642045014/job/23693611567

I ran the same exact setup with ```pytest tests/integration_tests/status/test_tracking_integration.py::test_tracking -svv -n logical --count 200```. It found 1600 tests and took 2 hours to finish, but no tests failed. Can someone else try replicating it?

**Comment by xjules** [comment]
Also again here: https://github.com/equinor/ert/actions/runs/8631699048/job/23660824100

**Comment by jonathan-eq** [comment]
Yes, that is the one @yngve-sk mentioned. Let's wait and see if it keeps occurring into next week.

**Comment by jonathan-eq** [comment]
Closing this as it has not been seen for a while.
