### ISSUE TITLE
Flaky scheduler integration tests running against real LSF

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7595]
**Describe the bug**
Some of the scheduler integration tests are timing out and failing when running against the real LSF cluster. 
```
FAILED integration_tests/scheduler/test_generic_driver.py::test_submit[LsfDriver] - Failed: Timeout >360.0s
FAILED integration_tests/scheduler/test_lsf_driver.py::test_submit_to_named_queue - Failed: Timeout >360.0s
```
(https://github.com/equinor/komodo-releases/actions/runs/8596028934/job/23554954383)

**Expected behaviour**
Tests not failing.

**Environment**
 - OS: RHEL8
 - ERT/Komodo release: ert-onprem-2024.04.rc0-py3.11-rhel8
 - Python version: 3.11
 - Remote/HPC execution involved: Yes, onprem runner.

**Comment by berland** [comment]
I suggest to increase the timeout to one hour.
