### ISSUE TITLE
Possible to open storages with version higher than what is supported

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#7630]
**Describe the bug**
If we are opening a storage with a higher version than the current version, that will most likely fail.

**To reproduce**
1. Install a version of ert with a storage version lower than what can be found in: https://github.com/equinor/ert/blob/9d4c966443e39a23eca3239602819d793f05d2d4/src/ert/storage/local_storage.py#L44
2. Run an experiment and try to plot, in most cases this will fail, but depending on the versions involved, the error will be different.

**Expected behaviour**
I would not expect ert to start, but give a warning saying something along the lines of:
```
You are trying to open ERT with a storage version that is newer (<version_here>) than the current version (<version_here>), upgrade ERT to continue, or run with a different ENSPATH
```

**Comment by eivindjahren** [comment]
Is this also a problem with ert 9.0.9 ?
