### ISSUE TITLE
Visualize active and inactive observations

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#765]
depends on #1133

**Comment by oysteoh** [comment]
Needs to be checked if this is persisted in the new storage and then exposed through the API.

**Comment by sondreso** [comment]
It is persisted in the new storage: 
https://github.com/equinor/ert/blob/master/ert_shared/storage/extraction_api.py#L163-L199

**Comment by oysteoh** [comment]
from Eivind: we should plot inactive observations with a different color to make the history matcher aware.
