### ISSUE TITLE
Documentation for memory booking on LSF is wrong

### ISSUE THREAD

**Issue by berland** [equinor/ert#7651]
The specification of units in the example in the documentation is only valid for LSF10, which we don't yet facilitate.

https://github.com/equinor/ert/blob/4496033be04dab7622780034a19d7ace9902a514/docs/reference/configuration/queue.rst?plain=1#L189

For LSF9 the unit must be omitted, and the default unit is KB (so the LSF9 docs say)

**Comment by jonathan-eq** [comment]
Is the default unit confirmed by the infrastructure team?

**Comment by berland** [comment]
Default on (our) LSF9 is **MB**
