### ISSUE TITLE
MAX_SUBMIT does not work with LSF driver and --enable-scheduler

### ISSUE THREAD

**Issue by berland** [equinor/ert#7657]
**Describe the bug**
Flaky forward models are not rerun as instructed in the configuration.

**To reproduce**
Steps to reproduce the behaviour:
* Let poly_eval.py fail with some probability, say 10%
* Set MAX_SUBMIT to a number higher than 1, say 10
* Set queue system to LSF
* Remove MIN_REALIZATIONS (if present)
* Run ES_MDA or ensemble_experiement

NB: It works as expected if queue system is LOCAL.

**Expected behaviour**
All (or almost all) realization should eventually finish successfully, and there should be traces of each resubmission in `logs/`.

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: Bleeding at april 12
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Comment by berland** [comment]
This might be related to #7658 , maybe job tasks are being cancelled for some reason.

**Comment by jonathan-eq** [comment]
@berland I will put this back in Todo until #7658 is merged, then see if that changes something.

**Comment by xjules** [comment]
> This bug stems from the lsf_driver setting the returncode to something larger than SIGNAL_OFFSET and then scheduler.py will cancel the task if the returncode is larger than SIGNAL_OFFSET.
> 
> This bug was probably introduced in [795982a5ef6658c06743689](https://github.com/equinor/ert/commit/795982a5ef6658c06743689)
> 
> @JHolba , should we revert or fix ?

Not sure if this fixes the issue as we still set `aborted=True` which prevent resubmitting the job; ie. for `lsf_driver.py` at least.

**Comment by JHolba** [comment]
As far as I can tell there shouldn't be any difference for lsf with or without the PR. It now sets returncode > SIGNAL_OFFSET, but the old code set aborted=True in the same place. And scheduler used to cancel if aborted was set to True
