### ISSUE TITLE
Visualize misfits

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#766]

**Comment by ManInFez** [comment]
I am guessing that the misfit should be calculated on the server side? and the user should request a misfit with a selection of observations?

**Comment by sondreso** [comment]
I was thinking that we would store the misfit that ert calculates and save it in the database (connected to the update step), and then serve as you describe? (disclaimer: i'm not to familiar with how the misfit is calculated and stored now)

**Comment by markusdregi** [comment]
Whether we store it as derived information or utilise a central implementation of misfit to serve it is an implementation detail, but the know-how of how this is done should definitively reside on the server side in my opinion.

**Comment by anders-kiaer** [comment]
Definely agree - this should reside on the API server. Useful information that goes with the returned misfit from the API:

- Observation index and/or group/key (such that it can be joined, perhaps in the frontend, with observation metadata).
- Calculated misfit.
- If the observation point was used at the update step.

Data to consider from the "misfit API" (but which the user potentially also can find/calculate themselves by joining with a "observation file API"?):
- Observed value.
- Simulated value.
- Error
- Normalized misfit

There is a prototype of misfit visualization available [here](https://webviz-subsurface-example.azurewebsites.net/) which could be considered as a starting point (as one way of visualizing the misfits). Future frontend/Dash component improvements include:
- Add a "guided tour" to the plugin (as already added for some other plugins), explaining the user what he/she is looking at (especially the confidence intervals in the background, indicating areas of overfitting/underfitting, might be a difficult concept).
- Move legend out of the plot. Visualize axis ticks better on small screens.
- Option for showing total misfit per group (i.e. contribution in the misfit function), and not only average misfit within a group (as now).
- Observation type aggregation (currently it is one bar per "obs. group/key", e.g. `WOPR:A-1H`... would perhaps be useful to easily be able to aggregate this such that you show average/total normalized misfit for `WOPR:*` as a total, and `Rates` (`WOPR`, `WGPR`, `WWPR` etc.) as a even higher aggregration level).
- When hovering over a misfit bar, it could "dissolve" into the different "realization points" (a technique also used in the Parameter Distribution Plugin) - enabling the user to easily identify realizations with good/bad match wrt. to a given observation type.

**Comment by anders-kiaer** [comment]
Related to #778.

**Comment by sondreso** [comment]
>There is a prototype of misfit visualization available here ("History match" subpage/plugin) which could be considered as a starting point (as one way of visualizing the misfits).

How are these values calculated today?

**Comment by anders-kiaer** [comment]
Currently using [`fmu.ensemble.Observations.mismatch`](https://github.com/equinor/fmu-ensemble/blob/d17e9ec4f443a8995d136ce1c52fd32261162473/src/fmu/ensemble/observations.py#L106).

**Comment by oysteoh** [comment]
resolved by #https://github.com/equinor/webviz-ert/pull/55
