### ISSUE TITLE
LSF driver logs wrong message when killing

### ISSUE THREAD

**Issue by berland** [equinor/ert#7664]
When ctrl-c-ing ("Terminate experiment") is clicked on an ensemble_experiment (add `time.sleep(10)` to poly_eval.py)  on an LSF run, there are messages in the log:

```
LSF kill failed with stdout: Job <8055> is being signaled
 and stderr: 

```

This means that the `bkill` probably gives a nonzero returncode when it is doing the signalling, and we should not claim this is an error. Also `strip()` the stdout and stderr from the process to have this end up on one line.

After the Ert process is done, we get additional output to the terminal:
`Job <8056>: Job has already finished`
which should be muted.

**Comment by jonathan-eq** [comment]
This part should be covered by the PR fixing https://github.com/equinor/ert/issues/7658 (for example https://github.com/equinor/ert/pull/7661)
> After the Ert process is done, we get additional output to the terminal:
Job <8056>: Job has already finished
which should be muted.

**Comment by jonathan-eq** [comment]
Made a seperate issue (https://github.com/equinor/ert/issues/7676) for
> After the Ert process is done, we get additional output to the terminal:
 Job <8056>: Job has already finished
 which should be muted.
