### ISSUE TITLE
Dump output from `bhist -l` <lsfjobid>` to runpath

### ISSUE THREAD

**Issue by berland** [equinor/ert#7694]
**Is your feature request related to a problem? Please describe.**
The output from `bhist -l <jobid>` on finished LSF jobs is too interesting not to leave easily accessible, and should be dumped to the runpath:

```
Job <289263>, User <havb>, Project <default>, Command <sleep 10>
Thu Apr 18 10:00:40: Submitted from host <st-grid03>, to Queue <normal>, CWD <$
                     HOME>;
Thu Apr 18 10:01:28: Dispatched to <st-rst14-03-05>, Effective RES_REQ <select[
                     (cs)&&(type == any )&&(mem>maxmem*1/12)] order[r15s:pg:bjo
                     bs] span[hosts=1] same[model] >;
Thu Apr 18 10:01:28: Starting (Pid 658);
Thu Apr 18 10:01:28: Running with execution home </private/havb>, Execution CWD
                      </private/havb>, Execution Pid <658>;
Thu Apr 18 10:01:38: Done successfully. The CPU time used is 0.1 seconds; 
Thu Apr 18 10:02:01: Post job process done successfully;

MEMORY USAGE:
MAX MEM: 3.9 Gbytes;  AVG MEM: 3.9 Gbytes

Summary of time in seconds spent in various states by  Thu Apr 18 10:02:01
  PEND     PSUSP    RUN      USUSP    SSUSP    UNKWN    TOTAL
  48	   0        10       0        0        0        58

```

**Describe the solution you'd like**
Dump the output to some filename. 

*Describe alternatives you've considered**
Do nothing.

**Comment by berland** [comment]
The LSF stdout might be sufficient though, but must be fixed in #7695. Examine if there are differences when  OOM strikes f.ex.

**Comment by jonathan-eq** [comment]
What should the filename be? @berland 
I have some ideas:
* bhist_job_summary.txt
* lsf_job_summary.txt
* job_summary.txt (would not be created for other queue systems than lsf anyways)

**Comment by jonathan-eq** [comment]
![image](https://github.com/equinor/ert/assets/107626001/e36fec94-faa4-435d-b68b-c8b694a82c29)
The one on the left is lsf stdout while the one on the right is the bhist long format

**Comment by jonathan-eq** [comment]
The one on the left is lsf stdout while the right one is the hist long version. 
![image](https://github.com/equinor/ert/assets/107626001/f9ae9418-7711-49e4-84ce-f0e3b33bc730)

**Comment by berland** [comment]
As for filename, we already have `<JOBNAME>.LSF-out` for stdout, and we might get `<JOBNAME>.LSF-err` for stderr (that is a potential issue to write). To be in line with that system, what about `<JOBNAME>.LSF-bhist-l` ?

**Comment by jonathan-eq** [comment]
Output when cancelled due to OOM:
![Screenshot 2024-05-03 at 08 55 27](https://github.com/equinor/ert/assets/107626001/e869fe12-767b-4348-8a19-d30f2b484bf7)

**Comment by jonathan-eq** [comment]
The lsf stdout already provides all the information found in `bhist -l`, so echoing the output to a file wouldn't give us anything extra.

**Comment by jonathan-eq** [comment]
One field that is not included in lsf stdout is `Dispatched to <cluster_node>, Effective RES_REQ <select[(cs)&&(type==any)>`.
Maybe getting the resource requirement string would be reason enough to keep the output? @berland

**Comment by berland** [comment]
Yes, I think this is sufficient to warrant also outputting this. There might be other corner-case scenarios where this diff is changed too, and that is when it is the most interesting.
