### ISSUE TITLE
Discuss refactoring run_ensemble_evaluator to avoid using websockets to propagate events

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7721]
Based on this 8c16ed9f6455692f9a5e4db2a20b80aa1038ecf1 it should be possible to get the events from the ensemble evaluator directly via the queue instead websockets.

**Comment by jonathan-eq** [comment]
@xjules Should this issue wait for https://github.com/equinor/ert/issues/6958?

**Comment by jonathan-eq** [comment]
Blocked by #6958
