### ISSUE TITLE
Alpha channel is disregarded when plotting

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#7735]
Using 2024.05.rc1-py38-rhel8 on tgx-node:

Creating a custom colour black with no opacity still is rendered fully visible.
The alpha channel should have allowed see-through.

![Screenshot 2024-04-23 at 13 02 44](https://github.com/equinor/ert/assets/114403625/e628ed1c-9e11-47a4-b8ec-c74904ff4674)

![Screenshot 2024-04-23 at 13 01 02](https://github.com/equinor/ert/assets/114403625/31fea329-8cd5-46b0-b9fe-b34bac08bd4a)

**Comment by frode-aarstad** [comment]
Not sure this has ever worked, but I will fix it :)
