### ISSUE TITLE
OpenPBS driver lacks options the documentation claims it has

### ISSUE THREAD

**Issue by berland** [equinor/ert#7747]
The OpenPBS driver that has replaced the Torque driver (unless  `--disable-scheduler` is used on the command line) lacks some settings that the documentation claims are valid:

* `QSUB_CMD` 
* `QSTAT_CMD`
* `QDEL_CMD`
* `QSTAT_OPTIONS`
* `QUEUE_QUERY_TIMEOUT`

The last option is not as relevant to the improved Python driver and should just be provided a deprecation warning for (that it is ignored).

The first four should either be deprecated, or implemented (which will not be difficult, and would make it more in line with LSF driver).

Documentation should be updated accordingly.

**Comment by xjules** [comment]
Are those options relevant / were used before? @berland

**Comment by berland** [comment]
Not sure
