### ISSUE TITLE
Add up-down buttons to move ensembles accordingly

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#7749]
Add up-down buttons to move ensembles accordingly

The arrow icon is suggested to be replaced: https://github.com/equinor/ert/issues/7745

![image (2)](https://github.com/equinor/ert/assets/114403625/e2aa60fa-5968-4db4-8772-bf34dc0e1b40)
![image (1)](https://github.com/equinor/ert/assets/114403625/28d91b27-d33a-444a-8090-222d7c783590)

**Comment by oyvindeide** [comment]
Is this still relevant? There has been changes to this since this issue was create. Will close it, but feel free to reopen if it is still relevant.
