### ISSUE TITLE
Practical information 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#776]
The main branch for the workshop is `ertviz-workshop`, and all changes should come in form of a PR to this branch. Remember to keep commits either targeting changes to visualization or API, that way it will be easier to split after the workshop. (I recommend not creating branches on the equinor fork, as these take up double the amount of test resources compared to a branch on you own fork)

I have checked in populated databases for the `poly_case` and `snake_oil` for convenience in ertviz-workshop branch.

To start the API: (Assuming you have ERT installed)

- From the root folder of the ert repository go to either `test-data/local/poly_example` or `test-data/local/snake_oil`
- run `ert api`
- Now you should see the ensembles if you visit `http://127.0.0.1:5000/ensembles`

To run the dash prototype: (After starting the API either in poly_example or snake_oil)
 - In the folder dash_prototype under the root folder of the ERT repository run `python main_dash.py`

**Comment by asnyv** [comment]
Short summary of steps for setting up based on komodo on rgs unix for those interested:

- sourced komodo/testing-py3
- made virtualenv (`python -m virtualenv ertviz_env --system-site-packages`)
- sourced  ertviz_env
- `git clone git@github.com:equinor/ert.git`
- `git fetch origin ertviz_workshop`
- `git checkout origin/ertviz_workshop`
- step into the new ert repo and `pip install .`
- either follow Sondre's steps above to look at the api for the `test-data` `poly_case` or `snake_oil`
- or if you want to run a (python 3 compatible) ert case yourself with creation of new storage run `ert gui yourertfile.ert --enable-new-storage`  and then run `ert api` when it has finished. Remember that you need the `/ensembles` in the url 😉 If it doesn't work to run with `--enable-new-storage` or `api` try a complete path to your `ertviz_env/bin/ert` (first attempt at installing didn't manage to source that properly even though `which ert` directed to my new env, but second time it worked)

**Comment by sondreso** [comment]
Closing this as the workshop is done, but keeping a link in the milestone description
