### ISSUE TITLE
Verify Scheduler behaviour when websocket connection from the compute node is down

### ISSUE THREAD

**Issue by berland** [equinor/ert#7789]
Ert will function, albeit slowly since it falls back to using the file system, when the compute node (job_dispatch.py) cannot connect to the mother Ert process over a websocket connection.

There is no code in the new scheduler to handle this situation (?). 

It must be verified how well Ert behaves in this scenario with `--disable-scheduler` and then it should be verified that it works just a fine with `--enable-scheduler`. 

This is probably driver-independent, so it might be possible to test by using the local driver and ensure that job_dispath's websocket does not function in any way.

**Comment by xjules** [comment]
Given that the behaviour is the same for both queues closing this issue.
