### ISSUE TITLE
Remove step_id from ert_forward_runner.reporting.message

### ISSUE THREAD

**Issue by berland** [equinor/ert#7805]
This step_id is a forgotten legacy from "ert3" and must be removed since the step concept is being introduced as something else.

https://github.com/equinor/ert/blob/586d6ca2f36536a8f48070096d1be93f621af195/src/_ert_forward_model_runner/reporting/message.py#L63

**Comment by jonathan-eq** [comment]
I think (hope) this should be straight forward.
