### ISSUE TITLE
test_run_and_cancel_legacy_ensemble is flaky

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7829]
https://github.com/equinor/ert/actions/runs/8934392394/job/24541305788

**Comment by berland** [comment]
Reproducible on local Mac hardware with:

`(3.12) [HAVB@AC-Y72WJR4W4M:~/projects/ert] main$ pytest tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py -k run_and_cancel --count 1000 -n 24`

**Comment by berland** [comment]
Also on local Linux workstation with Python 3.11 with the same pytest args.

**Comment by xjules** [comment]
Even more flaky when setting the `MAX_RUNTIME=1` in https://github.com/equinor/ert/blob/56902de5ff705f99fa13cba4ad8e779d5ad6f411/tests/unit_tests/ensemble_evaluator/conftest.py#L64
Apparently, both realizations are killed by MAX_RUNTIME and then monitor signals cancel, wherein either the evaluator or scheduler is already done and thus the cancellation never gets through.

**Comment by eivindjahren** [comment]
Another failure here: https://github.com/equinor/ert/actions/runs/9169996656/job/25211416370
