### ISSUE TITLE
Use dataclasses in `ert.ensemble_evaluator.snapshot`

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#7882]
We use pydantic's BaseModel and dictionaries in `ert.ensemble_evaluator.snapshot`, but BaseModel is heavy and too advanced for our use case, and dictionaries are too basic. 
We should refactor this to use dataclasses instead.

**Comment by eivindjahren** [comment]
This was resolved in https://github.com/equinor/ert/commit/720be68b989b0a86b7b66a14578f566482f7b745
