### ISSUE TITLE
Ensemble name unique validation not working as expected

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#7913]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run `Ensemble experiment`
4. To run another experiment, a unique `Experiment name` and `Ensemble name` is required. `Ensemble name` does not have to be unique when creating a new experiment.

**Expected behaviour**
Only `Experiment name` needs to be unique.

**Screenshots**
![image](https://github.com/equinor/ert/assets/45088507/9ae3f293-42e7-4570-a198-448a09c9e909)

**Comment by oyvindeide** [comment]
In principle I agree with you, but as long as the plotter only shows `Ensemble name` that is the property which is most important that is unique, related to: https://github.com/equinor/ert/issues/7894 and https://github.com/equinor/ert/issues/7892
