### ISSUE TITLE
tests/unit_tests/ensemble_evaluator/test_monitor.py::test_that_monitor_can_emit_heartbeats is flaky

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8006]
`websockets.exceptions.ConnectionClosedError: sent 1000 (OK); then received 1011 (internal error)`
https://github.com/equinor/ert/actions/runs/9280874968/job/25535895978?pr=7997

Seems related to this log message:
```
.../python3.8/site-packages/_pytest/unraisableexception.py:59: RuntimeWarning: coroutine 'WebSocketServer._close' was never awaited
    del self.unraisable
  Enable tracemalloc to get traceback where the object was allocated.
```

**Comment by berland** [comment]
Reproducible with pytest-repeat on local hardware py311.

**Comment by xjules** [comment]
> RuntimeWarning: coroutine 'WebSocketServer._close' was never awaited

It seems that `RuntimeWarning: coroutine 'WebSocketServer._close'` is not related to the failure as this is triggered by the test not finishing.
