### ISSUE TITLE
Convert Ert to use mkdocs rather than sphinx

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#8014]
Ert uses sphinx, which is a very broadly used documentation software. However, there are pain points, like slow build times, no live reload and use of ReStructured Text (subjective).

Instead, I would like to use [mkdocs](https://www.mkdocs.org/), which has the [mkdocstring](https://mkdocstrings.github.io/) plugin that lets one easily document most everything in Python docstrings, with live reload. A notable user is [Pydantic](https://github.com/pydantic/pydantic/tree/main/docs).

One difficulty is implementing documentation from Ert plugins, where it is provided at runtime and in RST format rather than mkdocs' Markdown.

**Comment by dafeda** [comment]
I don't have strong opinions on this but `sphinx-autobuild` can be used to get live reload as explained here:

https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#build-documentation
