### ISSUE TITLE
`Restart` experiment (or realization) from GUI does unexpected things

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#8032]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Modify `poly_eval.py` such that some realizations fail:

```python
#!/usr/bin/env python3
import json
import random

def _load_coeffs(filename):
    with open(filename, encoding="utf-8") as f:
        return json.load(f)["COEFFS"]


def _evaluate(coeffs, x):
    return coeffs["a"] * x**2 + coeffs["b"] * x + coeffs["c"]


if __name__ == "__main__":
    if random.random() > 0.5:
        raise ValueError("Failed realization.")
    coeffs = _load_coeffs("parameters.json")
    output = [_evaluate(coeffs, x) for x in range(10)]
    with open("poly.out", "w", encoding="utf-8") as f:
        f.write("\n".join(map(str, output)))

```
3. Run `Ensemble experiment`
About 50% of realizations should fail:

![image](https://github.com/equinor/ert/assets/45088507/f4e7c5ee-7214-4391-ad69-cb1bdcf292d7)

4. Hit `Restart`
Notice that only the failed realizations remain:

![image](https://github.com/equinor/ert/assets/45088507/d6365ce4-cad9-4da0-a40c-a039b057a05a)

**Expected behaviour**
I expect `Restart` to restart only the failed realizations and keep the successful ones (successful ones should still be visisble in the gui).

**Comment by xjules** [comment]
Let us understand first what `RESTART` actually does.

**Comment by xjules** [comment]
> I expect Restart to restart only the failed realizations and keep the successful ones (successful ones should still be visisble in the gui).

It seems that that was never the case to show the completed realizations when clicking `RESTART`, but might quite handy to display those as well. @sondreso ?

**Comment by sondreso** [comment]
When we are running (or restarting) the same experiment, I would expect the successful realization for that experiment to still be visible in the GUI :slightly_smiling_face:
