### ISSUE TITLE
Progressbar inconsistent with details view

### ISSUE THREAD

**Issue by berland** [equinor/ert#8033]
**Describe the bug**
The progress bar can show inconsistent information that conflicts with the details view for an ensemble.

In the screenshot example experienced by a user, the progress bar says 4 realizations are finished, but looking at the realization, there are not 4 realizations showing up as finished. 

**To reproduce**
?

**Expected behaviour**
The outer frame should be green for exactly four of the realizations, or the progress bar should show zero realizations as finished. It is consistent for the failed realization (41).

**Screenshots**
![image](https://github.com/equinor/ert/assets/306834/41997bf1-9156-4607-a195-96e5c6e57206)

**Environment**
 - OS: RHEL7 RGS, possibly RHEL8 on compute side
 - ERT/Komodo release: 2024.05.03
 - Python version: 3.8
 - Remote/HPC execuiton involved: yes

**Additional context**
Reported in https://engage.cloud.microsoft/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjgyMDA3NDIzMzk0NjExMiJ9

**Comment by xjules** [comment]
Tested on `2024.05.03` on big  bigpoly and no issues:
![image](https://github.com/equinor/ert/assets/6409506/ea1dd8a7-a279-470a-a7bd-6aee74647172)

**Comment by xjules** [comment]
Reproduced on `2024.05.03` and LSF:
bigpoly MAX_RUNNING=200 and 300 reals

![image](https://github.com/equinor/ert/assets/6409506/4f267b64-0e54-4956-be24-c11faaeec94e)

**Comment by jonathan-eq** [comment]
@xjules Could this be related to #8070?

**Comment by xjules** [comment]
We should check the after all the snapshot and GUI related adjustments this issue is still present.
Related upgrades:
 - https://github.com/equinor/ert/pull/8122
 - https://github.com/equinor/ert/pull/8058
 - https://github.com/equinor/ert/pull/8182
 - https://github.com/equinor/ert/pull/8152

**Comment by sondreso** [comment]
The detailed view has been redesigned, so this is no longer an issue
