### ISSUE TITLE
Add Runtime information per realization

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#8046]
**Describe the solution you'd like**
Provide runtime information, specifically when a job has been running on a cluster and distinguish between each submit (i.e. if a job has been resubmitted I would like to know runtime for each submit).

The runtime information is necessary to determine total runtime for the job (i.e. only the time spent when a job has been submitted, not any time spent loading data)

**Additional context**
Will be used to provide more information related to running a job, for instance if there is cost associated.

**Comment by sondreso** [comment]
Will close this for now as this does not have priority. Feel free to re-open!
