### ISSUE TITLE
Tag which forward models run on lsf

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8048]
We would like to enable keeping statistics of which simulator runs on lsf. To do that, if a forward model job is of specific interest (say rms or flow) we would like to put it into the lsf project name (argument `-P`). This can be configured using the `QUEUE_OPTION` keyword like this:

```
QUEUE_OPTION LSF LSF_PROJECT_CODE rms+flow
```

so one way to implement this is to modify the user config in `ert_config.py`

```python
    tags = set(fm[0] for fm in config_dict.get("FORWARD_MODEL", []) if is_interesting(fm[0]))
    config_dict["QUEUE_OTPTION"].append(("LSF", "LSF_PROJECT_CODE", "+".join(tags))
```

**Comment by sondreso** [comment]
This should preferably work similarly on Slurm (https://slurm.schedmd.com/sbatch.html#OPT_account) and OpenPBS (https://www.jlab.org/hpc/PBS/qsub.html -A option) as well.

**Comment by DanSava** [comment]
Should this also be implemented for `JobQueue`

**Comment by eivindjahren** [comment]
No, its fine if this only works for Scheduler.
