### ISSUE TITLE
Have GUI keep state internally instead of piggybacking on snapshots

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#8055]
**The requested improvement**
Currently, the gui uses the snapshot methods to get ensemble state instead of keeping the records internally. Ideally, it should only use the snapshots to update its internal state - not get the entire state from snapshots.

**Comment by dafeda** [comment]
What do you mean by GUI keeping state? Don't we in general want GUI-code to be as stateless as possible?

**Comment by jonathan-eq** [comment]
> What do you mean by GUI keeping state? Don't we in general want GUI-code to be as stateless as possible?

The idea was to have gui use its own structure for storing the data in the snapshots. Currently it is getting everything from snapshot's metadata. Maybe this is fine, or maybe we should have an extra layer between snapshots and the nodes in GUI.

**Comment by jonathan-eq** [comment]
Snapshots already have the functionality to merge in new snapshots as they come in, so I think it is fine to continue using them.
I want to close this issue, what do you think @sondreso?

**Comment by sondreso** [comment]
I think closing this makes sense! 🙂
