### ISSUE TITLE
Improve scheduler tests towards NUM_CPU config key

### ISSUE THREAD

**Issue by xjules** [equinor/ert#8065]
Relates to hot-fix https://github.com/equinor/ert/pull/8061
This PR above just adds a key as `num_cpu` to `LSFDriver`.
Here we need see the other tests that could be affected by this change.

**Comment by xjules** [comment]
We should write a test that the `num_cpu` is read and propagated correctly to each individual driver.

**Comment by berland** [comment]
unit_tests/config/test_num_cpu.py: Verifies that ert_config is correct whether num-cpu-info comes from DATA file or config file.
integration_tests/scheduler/test_lsf_driver.py: Verifies that driver.submit(num_cpu=something) is supplied to LSF.
unit_tests/scheduler/test_lsf_driver.py: Verifies that the bsub command line can contain num_cpu information.

Missing:
* Propagation from Realization object (from ensemble builder) into driver. Belongs in test_job.py.

**Comment by berland** [comment]
For OpenPBS, it is possible to write an integration test submitting a script that does `echo $OMP_NUM_THREADS` which should equal `NUM_CPU`.
