### ISSUE TITLE
Presumably finished realization displayed as pending in joblist view

### ISSUE THREAD

**Issue by xjules** [equinor/ert#8070]
A user has reported the following issue when running ~~scheduler~~ JobQueue.

--- 

Hi.. 

Currently I am experiencing several realizations finished without doing the steps in the configuration and it is labeled as 'finished'.

 

I know sometimes it is common to have some error due to maybe random licensed error, etc. therefore I set max_submit = 3 just to make sure that if something like that happened (failed run), the case will be restarted.

 

However if the label is 'finished' I think the case wont be restarted. in some cases it can be more than 5 realization like that (picture attached)

![Image](https://github.com/equinor/ert/assets/6409506/5405029e-6629-4974-a8a6-1912936b55d1)

**Comment by andreas-el** [comment]
> Not related to scheduler. GUI picture gives away that this is not Ert 10 (missing memory information)

Agree. I'll verify no candidates using this though.

**Comment by sondreso** [comment]
The detailed view has been redesigned, so this is no longer an issue

**Comment by xjules** [comment]
This one is still an issue. Tested on bleeding on big poly running on LSF.
Realizations are completed, but the job list view is still display the jobs as pending.
![image](https://github.com/user-attachments/assets/5549d3fd-aecc-4af9-9828-18fb03614e87)

**Comment by xjules** [comment]
Update:
The fix presented in https://github.com/equinor/ert/pull/8544 solved when running on LSF, but not on LOCAL queue, with the settings described here: https://github.com/equinor/ert/issues/8070#issuecomment-2301336917

![image](https://github.com/user-attachments/assets/365e5b6d-e0ef-47d6-8411-955ac9009b86)

**Comment by xjules** [comment]
While debugging (logging any realizations with ids expected to get the wrong GUI state), I have noticed that all the events are present (see picture)
![image](https://github.com/user-attachments/assets/5ed8f34a-c7b9-4f58-ae7d-c1eb021dbf42)
