### ISSUE TITLE
Success or failure of realization is logged with debug log level

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8071]
**Describe the bug**
Success or failure of realizations are logged with debug log level, meaning they will not propagate to external log collectors if they are installed.

https://github.com/equinor/ert/blob/7fc50c7d1ff401e684a04bb8b8b6cd1f62d08a60/src/ert/scheduler/lsf_driver.py#L401-L413

**To reproduce**
N/A

**Expected behaviour**
Logs propagated to external log collectors if they are installed.

**Screenshots**
N/A

**Environment**
 - OS: N/A
 - ERT/Komodo release: 7fc50c7d1ff401e684a04bb8b8b6cd1f62d08a60
 - Python version: N/A
 - Remote/HPC execution involved: yes

**Additional context**
N/A

**Comment by berland** [comment]
The current debug level was set by intention, to avoid flooding the logs. The strategy chosen was to avoid per-realization messages at level INFO. If log flooding is not an issue, then this is fine to change.

**Comment by sondreso** [comment]
But success or failure should only log once per realization per run? We should be able to handle that :thinking:
