### ISSUE TITLE
Switch to DTO's 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#808]
We should switch to using data transfer objects in the storage_api python module used by the http-server

**Comment by jondequinor** [comment]
- We mostly agreed (some were absent) that if the StorageApi returns dicts, it's difficult to develop this over time (racking up technical debt).
- The data we are working on usually has behaviour. Dicts are unable to have behaviour.

**Comment by jondequinor** [comment]
I suspect this is wildly out of date, and the original problems have probably been dealt with by the sloths.

**Comment by sondreso** [comment]
dealt with by the red-pandas ;)
