### ISSUE TITLE
Deprecate NUM_NODES and NUM_CPUS_PER_NODE in OpenPBS driver

### ISSUE THREAD

**Issue by berland** [equinor/ert#8088]
The OpenPBS driver, having a legacy from the C Torque driver, has its own keywords picked from the config for specifying CPU resources, namely NUM_NODES and NUM_CPUS_PER_NODE. This is not in line with the LSF driver, Python version or legacy version. 

Having jobs span multiple nodes is probably out of scope for what the Ert application is intended for. If so, NUM_NODES should be deprecated, and then NUM_CPUS_PER_NODE becomes a badly named keyword, and should be shortened to NUM_CPU which already exists.

**Comment by xjules** [comment]
Relates to https://github.com/equinor/ert/issues/6054
