### ISSUE TITLE
Investigate frequent bjobs failure

### ISSUE THREAD

**Issue by xjules** [equinor/ert#8091]
In the brief period when the scheduler was enabled by default (in `2024.06.00`), there's more than 1K of log entries:
```
bjobs gave returncode 255 and error ....
``` 
This requires some discussion if this is considered as normal or not.

**Comment by berland** [comment]
This is the FLAKY_SSH_RETURNCODE and is due to infrastructure. We can consider not to log it and just accept it.

**Comment by xjules** [comment]
> This is the FLAKY_SSH_RETURNCODE and is due to infrastructure. We can consider not to log it and just accept it.

Let's keep it logged then.
