### ISSUE TITLE
Terminating jobs fails using jobqueue

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#8101]
Using `2024.06.02` with scheduler set to `False` on RGS.

Also reproducible on `2024.02`, `2024.04` & `2024.05` releases, although these do not yield the error-dialog.

```
QUEUE_SYSTEM LSF
```

Running poly-example Ensemble Experiment, and terminating jobs half-way through.

* The jobs seem to continue running even though terminate was issued
* stdout is filled with `Job has already finished`
* User is presented with error-pane after all jobs have reach a finalised state

![Screenshot 2024-06-07 at 09 42 39](https://github.com/equinor/ert/assets/114403625/34bab332-4f12-40da-8bb2-ef45cefcf182)

```
Job <651004>: Job has already finished
Job <651007>: Job has already finished
Job <651009>: Job has already finished
Job <651011>: Job has already finished
Job <651012>: Job has already finished
Job <651014>: Job has already finished
Job <651013>: Job has already finished
Job <651015>: Job has already finished
Job <651017>: Job has already finished
Job <651018>: Job has already finished
Job <651020>: Job has already finished
Job <651019>: Job has already finished
Job <651021>: Job has already finished
Job <651022>: Job has already finished
Job <651023>: Job has already finished
Job <651024>: Job has already finished
Job <651025>: Job has already finished
Job <651026>: Job has already finished
Job <651027>: Job has already finished
Job <651028>: Job has already finished
Job <651030>: Job has already finished
Job <651031>: Job has already finished
Job <651033>: Job has already finished
Job <651036>: Job has already finished
Job <651039>: Job has already finished
Job <651040>: Job has already finished
Job <651041>: Job has already finished
Job <651044>: Job has already finished
Job <651043>: Job has already finished
Job <651046>: Job has already finished
Job <651047>: Job has already finished
Job <651050>: Job has already finished
Job <651051>: Job has already finished
Job <651052>: Job has already finished
Job <651054>: Job has already finished
Job <651053>: Job has already finished
Job <651055>: Job has already finished
Job <651056>: Job has already finished
Job <651057>: Job has already finished
Job <651058>: Job has already finished
Job <651059>: Job has already finished
Job <651060>: Job has already finished
```

**Comment by andreas-el** [comment]
The jobqueue does not terminate the jobs (seemingly) in earlier versions of komodo either.
`2024.05.04`: UI blocked, jobs continue to run, stdout contains 'Job has already finished'
`2024.05.00`: UI blocked, jobs continue to run, stdout contains 'Job has already finished'
`2024.04.10`: UI blocked, jobs continue to run, stdout contains 'Job has already finished'

But what differs is that the "Experiment failed" dialog does not appear in these versions.

**Comment by andreas-el** [comment]
This might be tied into the `MAX_RUNNING` keyword. Testing was performed using the default value 2 (?), where we expect most users to set a rather high value for this, resulting in all jobs being submitted immediately.

**Comment by andreas-el** [comment]
We should also keep in mind that `LSF10` was introduced not a long time ago.

**Comment by xjules** [comment]
Let's see if the same behaviour happens in scheduler.

**Comment by sondreso** [comment]
This has been a problem in the jobqueue for a long time, and given that it is fixed in the scheduler, we will not prioritize fixing this.
