### ISSUE TITLE
Ert not able to run csh jobs in test_run

### ISSUE THREAD

**Issue by erlid** [equinor/ert#8120]
csh scripts hangs in simulation mode `test_run` - while bash and ksh runs fine.
In `Ensemble_experiments` all runs fine.

Can be tested here:
**/scratch/fmu/erlid/whats_up_with_csh/ert/model/*.ert**

**Comment by oyvindeide** [comment]
The difference between `test-run` and `ensemble_experiment` is largely that `test-run` runs on the local driver, while `ensemble_experiment` runs on what is configured in the ert config. We will look into this right away.

**Comment by sondreso** [comment]
I tried reproducing this by running the setup in `/scratch/fmu/erlid/whats_up_with_csh/ert/model/test_run.ert` both from bash and csh with 2024.06.03-py38 and it works :thinking:

**Comment by erlid** [comment]
Sorry - I thought I was testing in clean csh but I did not - I mixed komodo env's
