### ISSUE TITLE
Move workflow_runner out of job_queue

### ISSUE THREAD

**Issue by berland** [equinor/ert#8170]
The job_queue is scheduled for removal, being replaced by scheduler. Inside the job_queue directory there is a file that should not be removed, thus, it needs to reside somewhere else in the code hiearchy:

https://github.com/equinor/ert/blob/main/src/ert/job_queue/workflow_runner.py

Including test files.

**Comment by eivindjahren** [comment]
Fixed in https://github.com/equinor/ert/pull/8254
