### ISSUE TITLE
Clicking on the observations of an uninitialized ensemble crashes the gu

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8172]
[Screencast from 2024-06-17 15-12-51.webm](https://github.com/equinor/ert/assets/32731672/ec94187c-7fe2-4609-adb2-ddb0c981e5c1)

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui test-data/poly_example/poly.ert`
3. click on manage experiments
4. click on the plus icon to add an uninitialized ensembl
5. expand the newly created experiment in the tree view
6. click on the newly created ensemble
7. click on the corresponding observations tab

```
Traceback (most recent call last):
  File ".../ert/gui/ertwidgets/storage_info_widget.py", line 196, in _curr
entItemChanged
    response_ds = ensemble.load_responses(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ert/storage/local_ensemble.py", line 880, in load_responses
    raise KeyError(
KeyError: 'No response for key POLY_RES, realization: None'
Aborted (core dumped)
```

**Comment by oyvindeide** [comment]
Fixed in: #8166
