### ISSUE TITLE
Closing Ert GUI gives RuntimeError: GUILogHandler has been deleted in terminal

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#8186]
**Describe the bug**
When closing the Ert GUI on macos14 arm with python3.12 you get the following error in the terminal:
```
Exception ignored in atexit callback: <function shutdown at 0x10435c0e0>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 2263, in shutdown
    if getattr(h, 'flushOnClose', True):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type GUILogHandler has been deleted
```
Does not seem to happen with python3.11, but as we run our workflow tests with python3.12 this should be looked into.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Close the ert gui

**Expected behaviour**
Should not get this error, and investigate why this happens.

**Environment**
 - OS: macos14 (arm)
 - ERT/Komodo release: main and (ert 10.1.11)
 - Python version: 3.12
 - Remote/HPC execution involved: [no]

**Comment by eivindjahren** [comment]
This should not be possible as `GuiLogHandler` is created by

https://github.com/equinor/ert/blob/2ce20800e12006202828c3e7e657c13fb96e0c6f/src/ert/gui/tools/event_viewer/panel.py#L56-L69

This doesn't seem to happen with python 3.12 on ubuntu, so I suggest someone with a mac check this out.

**Comment by eivindjahren** [comment]
I'll have another look then :)
