### ISSUE TITLE
How to configure a FLOW forward model simulation and to run the test cases in `ert/test-data/eclipse` ?

### ISSUE THREAD

**Issue by AaronyfDesign** [equinor/ert#8223]
Hi, we are trying to run the couple of test cases of **SPE1** in path `ert/test-data/eclipse` by using **ert** tool, which are `SPE1.DATA`, `SPE1_ERROR.DATA` and `SPE1_PARALLEL.DATA`. However, we have no idea how to configure and run the test cases above in folder `eclipse` just as running the **simple polynomial test** (`poly_example`) in your *Configuration Guide - ERT 10.2* file. 

Do you have any other guidance or examples could help us configure and run the test cases by using **FLOW** as forward model to fit the simulation job？

**Comment by sondreso** [comment]
@AaronyfDesign There is now an example flow setup in here: https://github.com/equinor/ert/tree/main/test-data/flow_example

As long as you have flow installed and added to `PATH`, this should work out of the box (You will need to install ert directly from the repository until this is included in the next release) :slightly_smiling_face: Let us know how it goes!
