### ISSUE TITLE
Issues with alt+tab in Run Dialog

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#8238]
**Describe the bug**
Apparently if you press `alt ` in the run dialog you are prompted if you want to terminate the experiment. If you try to press no ert crashes with following error:
```
Traceback (most recent call last):
  File "/data/komodo_dev/ert/src/ert/gui/simulation/run_dialog.py", line 290, in closeEvent
    QCloseEvent.ignore()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^
TypeError: ignore(self): first argument of unbound method must have type 'QEvent'
Aborted (core dumped)
```
There are other issues here as well. Earlier if you pressed `esc` you were prompted for terminate experiment, but now you close down run dialog immideatly. Enter also seems to prompt terminate experiment. 

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. Press alt, enter or just hammer keyboard.

**Expected behaviour**
We should limit keyboard input to avoid accidentally cancelling run. and gui should not crash.

**Screenshots**

**Environment**
 - OS: [RHEL8]
 - ERT/Komodo release: main]
 - Python version: 3.11
 - Remote/HPC execution involved: [no]

**Comment by andreas-el** [comment]
This was introduced in 839a23ba0ad6796d2985617f2a091adb1f870712
