### ISSUE TITLE
Update plugin documentation & refine plugin interface

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8257]
In https://github.com/equinor/ert/commit/4f363cc0257b658d01c71125118fca6b654a578d & https://github.com/equinor/ert/commit/ceda74fdd18d8df31685288578cfa2b034d839b2 , a new way of handling 

```python
import ert

@ert.plugin
def installable_forward_model_steps():
    ...
```

in such a way that a plugin implementer does not need to import `hook_implementation` & `plugin_response`.

While at it, we could create a replacement for `legacy_ertscript_workflow` so that instead of

```python
@hook_implementation
def legacy_ertscript_workflow(config):
    workflow = config.add_workflow(CsvExport2Job, "CSV_EXPORT2")
    workflow.parser = csv_export_parser
    workflow.description = DESCRIPTION
    workflow.examples = EXAMPLES
    workflow.category = "export"
```

one would have

```python
@ert.plugin
def ertscript():
    return {
        "ertscript": CsvExport2Job,
        "name": "CSV_EXPORT2",
        "parser": csv_export_parser,
        "description": DESCRIPTION,
        "examples": EXAMPLES,
        "category": export
    }
```

**Comment by yngve-sk** [comment]
Some feature creep:

Currently, user-specified configs that go via site config override our builtin ones. So if a user specifies his own RMS forward model step, ERT will choose that over our built-in step. This is preferred. Currently, plugin fm steps are always prioritized under those from `INSTALL_JOB` / `INSTALL_JOB_DIRECTORY` wrt this:
```
       try:
            installed_forward_model_steps = copy.deepcopy(
                cls.PREINSTALLED_FORWARD_MODEL_STEPS
            )

            installed_forward_model_steps.update(
                cls._installed_forward_model_steps_from_dict(config_dict)
            )
```
We need to somehow decide what the prioritization should be. I think it makes sense for custom user-specified forward models to just override existing ones. There are different ways to achieve this (pick one or come up with another)
* Mark all internal ert fm steps as always lowest priority
* Add an importance/priority parameter to the `@ert_plugin` decorator (likely overkill), similar to z-index in css etc

It should also be logged when one forward model step overrides another (currently in `ErtPluginContext` but it might not be the best place for that logic to live).
