### ISSUE TITLE
Plotter segfaults when plotting two cases that are sufficiently different

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#827]
ERT Plotter segfaults when plotting two cases with different set of GEN_KW, and probably also different set of observations. In the below mentioned folder one configuration was run with ES-MDA, and later on another config was run with ES. The add case button in the plotter offers all cases in storage, and when attempting to plot a vector which is not present for both cases ERT segfaults.

Issue triggered with both komodo-testing-py27 and testing-py36. 
Example project: eism@st-linrgs272:/project/fmu/users/eism/ERT_analytical/ert

**Comment by lars-petter-hauge** [comment]
I ran the `poly_example` case twice, where I in the second attempt renamed `COEFFS` to `COEFFS_TWO` and the coefficients from `a`, `b`, `c` to `d`, `e`, and `f` (and handled all necessary consequences for this to run). I got the following exception when trying to plot:

```
Error message: double_vector_assert_index: index:0 invalid. Valid interval: [0,0>.

See file: /tmp/ert_abort_dump.lpha.20200422-130026.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.

Error message: Program received signal:6

See file: /tmp/ert_abort_dump.lpha.20200422-130032.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
Aborted (core dumped)
```
I suppose this isn't entirely the same as you, as I didn't get to choose a case at all (crash the moment I hit *Create Plot*. And even though I'm doing slightly weird stuff, I should not have gotten this kind of feedback.

Could I ask, for the second run, what did you choose as your current case? The updated one from last run?

**Comment by eivindsm** [comment]
Sure, in the directory: eism@st-linrgs272:/project/fmu/users/eism/ERT_analytical/ert
contains the two setups that I used; config_polycase.ert, and config_tenobs_scale.ert

**Comment by lars-petter-hauge** [comment]
Tried running ES-MDA for the first config, followed by ES for the second, as the reporter has done. For the second run I chose `default` as Current Case.

Now, when trying to open the plot, the content of the second run displayed (which is what default shows). The moment I try to access a case from the first run (ES-MDA), plot crashes, same error as above.

Looks like we're onto the same thing. I'll have a look at your case as well.

**Comment by markusdregi** [comment]
What is the current status here @lars-petter-hauge? Do we even believe that the current plotter can handle two cases that are very different? It might very well require a fundamentally different design and if so I suggest closing this issue and remembering to take this with us into the process of building our new plotting solution...

**Comment by markusdregi** [comment]
This is a won't fix due to investment of time and the fact that we are starting to work on a new plotting solution on top of the new storage now.
