### ISSUE TITLE
Example clean up

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#833]
Evaluate all experiments in `test-data/local` and either remove them or move them into `examples`. When moved into examples, the experiment should have:

- a corresponding test verifying that the setup runs,
- a readme documenting the experiment and how to conduct it,
- as clean a structure as possible and
- a meaningful name.

List of experiments in `test-data/local`:
- ~config/gen_data (not a complete example, should be removed)~
- ~custom_kw (should remove custom kw and evaluate)~
- ~example_case (Uses eclipse, with refcase. Port to use OPM?)~
- ~geometry (Not an ERT configuration, but some surface data. Should be removed)~
- poly_example
- ~resopt/config/simple~
- simple_config
- snake_oil
- snake_oil_field
- ~snake_oil_no_data~

In union, we would like the examples to span all input and output data types available in ERT:
- [x] GEN_DATA
- [x] SUMMARY
- [x] GEN_KW
- [x] GEN_PARAM
- [x] SURFACE
- [x] FIELD

We will not make an example based on `CUSTOM_KW` as it never worked as intended and new data types will replace it's initial vision.

In addition, we would like the examples to display the different algorithms in ERT, running forward models as well as workflows.

~~We should also have a discussion with @sondreso regarding the very similar setups in libres.~~ Ert and libres are now merged

**Comment by markusdregi** [comment]
An example using GEN_DATA was made here: https://github.com/equinor/ert/pull/903#event-3420088513

**Comment by sondreso** [comment]
Example with GEN_PARAM you mean? :wink:

**Comment by markusdregi** [comment]
Maybe ;)

**Comment by oyvindeide** [comment]
Moving the `test-data` is probably a monumental task, but would suggest starting with reviewing what `test-data` is not used and removing it.

**Comment by sondreso** [comment]
@oyvindeide Could you update the description to reflect the changes that you have made to the examples?

**Comment by oyvindeide** [comment]
Done, also some additional context: the `row_scaling` case can probably be removed, it contains an example workflow (that for the record is broken, and has been for a while). `config`, `configuration_tests` and `simple_config` should all probably be replaced with writing what is being tested in the tests themselves.

**Comment by oyvindeide** [comment]
Will close this issue now, as it is not very relevant anymore. Will spawn sub issues for the remaining tasks.
