### ISSUE TITLE
Should STD_CUTOFF be used to discard history observations?

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#8353]
Docs say it is used to discard observations pointing to responses with std.dev across all realizations, if the std.dev is below STD_CUTOFF.

However, it is also used to discard to summary observations:
```           
             if error <= std_cutoff:
                ConfigWarning.ert_context_warn(
                    "Too small observation error in observation"
                    f" {summary_key}:{i} - ignored",
                    summary_key,
                )
                continue
```
which isn't described or obvious, but it seems "sensible" that we'd require the same minimum std.dev from a summary history observation as we would from one ensemble response.

Either this should be described in the docs, or if these two things are more disjoint they should perhaps not use the same STD_CUTOFF from the ert config? 

There is already some ways to give an error threshold for history observations:
```
If you do not want the observation error to drop below a given threshold, say 100, you can set ERROR_MODE to RELMIN and the keyword ERROR_MIN:

HISTORY_OBSERVATION GWIR:FIELD
{
   ERROR       = 0.20;
   ERROR_MODE  = RELMIN;
   ERROR_MIN   = 100;
};
This error mode is also relevant for observations that may be zero, for example water production rates.
```
https://ert.readthedocs.io/en/latest/reference/configuration/observations.html#history-observation

Which makes it a bit unclear if this std_cutoff thing makes sense to also apply here

**Comment by dafeda** [comment]
Good question. I think it makes sense to limit how small the error can be of a history observation, but to me it's disjoint from `STD_CUTOFF`.
`STD_CUTOFF` is to remove responses that have "collapsed" which is different from defining a tiny error.
Now, a tiny error does increase the chance of ensemble collapse I think, but that depends on how non-linear the model is.
The simplest and perhaps most pragmatic solution could be to just update the docs.

**Comment by oyvindeide** [comment]
Additionally, it only applies to `HISTORY_OBSERVATION`, which is not used that much. I suggest we remove it, and either do nothing, or we add a std_cutoff for the observations in the outlier detection. That way it would affect all of them, not just `HISTORY_OBSERVATION`, and would also take into account scaling factors.

**Comment by sondreso** [comment]
I think removing the surprising behavior of the `STD_CUTOFF` related to `HISTORY_OBSERVATION` is the right way to go, and keep the functionality only for removing responses that have collapsed.
