### ISSUE TITLE
KeyError for HistogramPlot (LOG keys)

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#839]
The fix in https://github.com/equinor/ert/pull/723 returns a `KeyError` on 
https://github.com/equinor/ert/blob/64e0f3c379e77fe1a082e8a819f88306bec6398f/ert_gui/plottery/plots/histogram.py#L49

The key is modified earlier:
https://github.com/equinor/ert/blob/64e0f3c379e77fe1a082e8a819f88306bec6398f/ert_gui/plottery/plots/histogram.py#L35

The key was not used before (at least not in the current state), so removing the modification should not be an issue.

**Comment by xjules** [comment]
Was wondering too, why the key is modified when not used later on. I will remove it in #828
