### ISSUE TITLE
Rename `ert.shared.port_handler` and its functions  

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#8407]
**Describe the improvement**
The ert.shared.port_handler module is badly named and should renamed to avoid confusion. This module has a lot of helper functions for dealing with sockets and network connections, but none are for only ports. 

Also, the `find_available_port()` function returns not only the port, but also the host address and the socket. Can we rename this to something like `setup_connection()`, and investigate if the port and host are actually being used directly, or if they can be combined to a url right off the bat?

**Comment by muddi900** [comment]
I am interested in contributing. would net_utils be a good contribution?

**Comment by berland** [comment]
It seems the functions `get_family*` are not used anywhere, and can be removed. Then `port_handler.py `only provides two public functions, where `get_machine_name `is already exposed in `__init__.py`. `find_available_ports` can be exposed similarly, and then the name of  the file`port_handler.py` becomes a private matter to `ert.shared`.

**Comment by muddi900** [comment]
So just rename `find_available_ports` and expose it to `__init__`

**Comment by berland** [comment]
The function name `find_available_ports()` is fine I think, but just expose it in` __init__` yes and make the name of the filename (`net_utils` could do) of less importance.
