### ISSUE TITLE
Rename jobqueue log file to scheduler

### ISSUE THREAD

**Issue by berland** [equinor/ert#8464]
https://github.com/equinor/ert/blob/c27d36869bd070706f9aec7d3392e3b0b6d7944f/src/ert/logging/logger.conf#L22-L27

**Comment by jonathan-eq** [comment]
Renaming `jobqueue-log.txt` to `scheduler-log.txt` might require more work. What do you think @berland? Just changing log file name would (should) not break anything for the user.

**Comment by berland** [comment]
I would not call it a breaking change to rename this log file. 

What more work is possibly required? (I have not investigated)

**Comment by jonathan-eq** [comment]
It works locally, but are there any logging plugins that would require updating too?

**Comment by xjules** [comment]
> It works locally, but are there any logging plugins that would require updating too?

You can check https://github.com/equinor/fmu-logging

**Comment by jonathan-eq** [comment]
> > It works locally, but are there any logging plugins that would require updating too?
> 
> You can check https://github.com/equinor/fmu-logging

Yes, it will work 👌
