### ISSUE TITLE
Move to central storage and away from SQLite in new storage

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#847]
We should use a central database and API. Evaluate database technologies to use (probably need two different, relational database for Model, Key-value for data (NoSQL))

**Comment by dotfloat** [comment]
Suggestion: Add tests that use other databases so we are still compatible with alternatives in the long term.

Central database may not be super feasible now (in 2020).

**Comment by jondequinor** [comment]
> Central database may not be super feasible now (in 2020).

Care to expand?

**Comment by markusdregi** [comment]
The issue no longer contains any useful information
