### ISSUE TITLE
Separate ecl and flow simulator logic

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#8476]
**Issue**

When a config file contains the `FLOW` forward model job, running of the simulator is handled by `EclRun` and it's method `runEclipse`.

We would like to have Flow and Eclipse simulator handling code separate. 

eclrun is currently responsible for running both FLOW and Eclipse, and is dependent on environment variables that may or may not be overwritten by `ert-configurations`. This could be split up quite a bit. Suggestion: Without ert-configurations means it is outside the EQN cluster, *with* ert-configurations means it is on the cluster. Further we can split into FLOW and eclipse.

|                | On cluster (has `ert-configurations`) | Outside cluster |
| :---------------- | :------: | ----: |
| Eclipse        |   ecl_run   | ecl_run_custom |
| FLOW           |   flow_run   | flow_run_custom |

It is somewhat clear that this logic needs to be split up, but some decisions in structuring this depend on some questions that are up for discussion:
Q: What should be the responsibility/purpose of eclrun, and what is **not** the responsibility/purpose of eclrun?
Q: Should eclrun be for only EQN / cluster users?
Q: Where should the logic to check for ecl version exist? (If we are to put it inside our ecl forward model, it needs to be within ert). Should it be only for on-cluster, or outside cluster only?
Q: Should all our FLOW/EclipseX00 forward models go through what is now ECLRUN?

**Comment by sondreso** [comment]
There are ongoing discussions on how we integrate with FLOW, I suggest we put this issue to the backlog until that is resolved as some of the answers to the questions above depends on the outcome of this discussion :slightly_smiling_face:

**Comment by berland** [comment]
Superseded by #8925
