### ISSUE TITLE
Weights can be modified on ES MDA restart

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#8491]
### What happened? (You can include a screenshot if it helps explain)

Currently there is nothing stopping you from changing the weights when doing a restart of an ES MDA experiment. Since the weights are normalized for each run this might lead to the overall weights used in the normal run + restart run do not have reciprocal sum of 1 as they should. You are currently also able to add new weights on a restart. 

### What did you expect to happen?

The weights should be locked after you have run an es mda run for an experiment.
Relates to https://github.com/equinor/ert/issues/8447

### steps to reproduce

```Python
ert gui poly.ert
run es_mda with default weights
Click restart run and change weights
```

### Environment where bug has been observed

- [X] python 3.8
- [X] python 3.9
- [X] python 3.10
- [X] python 3.11
- [X] python 3.12
- [X] macosx
- [X] rhel7
- [X] rhel8
- [X] local queue
- [X] lsf queue
- [X] slurm queue
- [X] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by sondreso** [comment]
If it is a restart run we should fetch the weights from the previous experiment, and populate the weights inout field with these values (in addition to disabling it).
