### ISSUE TITLE
Remove redundant information on selected realization

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#8509]
Information marked in red is redundant and can be removed.
The current implementation is also buggy as it does not always show the correct iteration.

![image](https://github.com/user-attachments/assets/0b87ed00-46aa-49ee-abf3-ffa3e26bfd23)

**Comment by andreas-el** [comment]
> I do not agree that is is redundant information, as currently there is no immediate way of seeing which exact realization you have clicked on in the gui. It could be realization 0 from any iteration?

I've made a second attempt to resolve this, where I address the bug where if the same indice is clicked in different tabs, the job_label does not update.
Also moved back the job_label to its original position.

**Comment by andreas-el** [comment]
> > I do not agree that is is redundant information, as currently there is no immediate way of seeing which exact realization you have clicked on in the gui. It could be realization 0 from any iteration?
> 
> Good point! Is this bug specified in a different issue as well @andreas-el or should I repurpose this one?

I've addressed a bug where clicking the same index but in different iterations would _not_ update the labels already, and moved the label back to its original position.
Relates to https://github.com/equinor/ert/pull/8512

Maybe we should close this one as resolved?
