### ISSUE TITLE
Experiment type dropdown is weird for disabled options in dark mode

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#8531]
The disabled options have some "on hover" background colouring that makes them unreadable, while the "selection" stays at the last valid option. If you click on a disabled option, you get the "selected" option instead.

![image](https://github.com/user-attachments/assets/30e547ad-7a45-4ab9-bb35-5470d74cebf7)

**Comment by andreas-el** [comment]
I think the bug is actually worse, since the dropdown does not properly indicate what is deactivated or not.
