### ISSUE TITLE
Load results manually window shows stop sign but gives message: Successfully loaded x iterations

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8533]
### What happened? (You can include a screenshot if it helps explain)

![image](https://github.com/user-attachments/assets/42cbc39a-95a1-447a-a863-b943d143a84f)

### What did you expect to happen?

Reduced dissonance between message an icon, and if something went wrong, would like a report about what went wrong.

### Environment where bug has been observed

- [X] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [X] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by oyvindeide** [comment]
Was not able to fully reproduce, because I thought I observed a failure to load where there was no message, however something similar is reproducible if you:

Run ensemble experiment
Manually delete on `poly.out` file from one of the result folders
Create a new ensemble
Load results manually

![image](https://github.com/user-attachments/assets/0e135846-96e1-4791-a38d-884da285b370)

**Comment by eivindjahren** [comment]
As this issue is described, I cannot reproduce it. If there is something concrete to be fixed here I suggest we try again with explicit steps to reproduce.
