### ISSUE TITLE
Impossible to distinguish between ensembles to restart from in es_mda

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#8614]
### What happened? (You can include a screenshot if it helps explain)

There is nothing stopping you from running two separate experiments where you set the same target ensemble format in both experiments. When doing a restart run in es_mda it will then be impossible to distinguish between the ensembles that stems from different experiments. Note that in the plotter you can see the difference as then the ensembles are prefixed with the experiment name.

<img width="869" alt="image" src="https://github.com/user-attachments/assets/f9dc6090-fde5-4732-934d-84d1d8edabd0">

![image](https://github.com/user-attachments/assets/95db843d-a9b3-485c-b404-f134538d3deb)

### What did you expect to happen?

Would expect to tell the difference across experiments, similar to the plotter.

### steps to reproduce

```Python
ert gui poly.ert
run es_mda
run es_mda again with Target ensemble set to same as before
Check restart run, and press the restart from dropdown
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [X] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [X] rhel8
- [X] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by eivindjahren** [comment]
This seems to be an issue with the dropdown not filtering to the selected experiment.
