### ISSUE TITLE
flaky test: test_full_migration_logging

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8635]
```
FAILED tests/unit_tests/storage/migration/test_block_fs_snake_oil.py::test_full_migration_logging[True] - assert 'Loop <_UnixS...658 is closed' == "Exception oc...onfiguration'"
  
  - Exception occurred during migration of BlockFs case 'default_0': 'The key:SNAKE_OIL_PARAM is not in the ensemble configuration'
```

https://github.com/equinor/ert/actions/runs/10698102146/job/29656742590

**Comment by sondreso** [comment]
Do you have the link to the logs where this failed?

**Comment by eivindjahren** [comment]
Unfortunately lost it. Will try to find it.

**Comment by eivindjahren** [comment]
Added failing run

**Comment by eivindjahren** [comment]
Another failure here:

https://github.com/equinor/ert/actions/runs/10879902957/job/30185560370?pr=8690

**Comment by eivindjahren** [comment]
This is no longer relevant as block storage migration is removed.
