### ISSUE TITLE
Not possible to load results manually from other iteration than "ensemble.iteration"

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#8640]
### What happened? (You can include a screenshot if it helps explain)

Currently no matter what value you set for `iteration` in the load results manually tool, it will only try to load from the iteration that is connected to the ensemble. If you have manually created a new ensemble, this is usually 0.
Reason is the following code which is used to load results from runpath, in `libres_facade.py`:
```
    def load_from_forward_model(
        self,
        ensemble: Ensemble,
        realisations: npt.NDArray[np.bool_],
        iteration: Optional[int] = None,
    ) -> int:
        if iteration is not None:
            warnings.warn(
                "The iteration argument has no effect, iteration is read from ensemble",
                DeprecationWarning,
                stacklevel=1,
            )
```

### What did you expect to happen?

Would expect the tool to load from the iteration specified.

### steps to reproduce

```Python
ert gui poly.ert
run an es_mda run
Create new experiment (and ensemble) in manage experiment
Try to load results manually into new ensemble, with iteration>0
Can see in the plotter that the result is from iteration 0
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [X] python 3.11
- [ ] python 3.12
- [x] macosx
- [ ] rhel7
- [X] rhel8
- [X] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by oyvindeide** [comment]
Had a chat with a couple of users who use this functionality, and we came to the following that would be flexible enough to cover their needs, while keeping the internals consistent:

1. When manually creating an experiment it should be possible to also set the iteration number in addition to the experiment and ensemble name. It should default to 0
2. In the load results manual window the runpath should be editable so they can load from anywhere
3. In the load results manual window we should write what <ITER> will be replaced by when loading results. This should not be editable, the user can get the same results by editing the runpath manually in step 2.
