### ISSUE TITLE
Duplicate plotting of data when experiment names are left empty

### ISSUE THREAD

**Issue by eq-sandkav** [equinor/ert#8653]
### What happened? (You can include a screenshot if it helps explain)

I did the poly example in addition to my own experiment, and since there was a lot of testing, I often just hit "run experiment" without naming the experiments. When I didn't name the experiments, the plotting of results plotted duplicate output data.

By deleting storage, I could run new nameless experiments without this issue.

In the attached photos, I run two examples, one with 2 and one with 40 realizations, where I expected to see two different plots.

I acknowledge this might be a known issue or intended behaviour.
![Screenshot 2024-09-05 at 14 39 12](https://github.com/user-attachments/assets/6c92b55c-1d07-4eb6-a33a-93e206bc7b42)
![Screenshot 2024-09-05 at 14 39 54](https://github.com/user-attachments/assets/d950180b-f71f-4a1a-b9fb-c312a4e8d81d)
![Screenshot 2024-09-05 at 14 39 58](https://github.com/user-attachments/assets/96f8cdbb-7822-4215-bff1-27afa5c719ca)

### What did you expect to happen?

See different results between experiments with different input/output values.

### steps to reproduce

```Python
Run the polyexample without naming the experiment.

Rerun the polyexample without naming that experiment either, and perhaps change number of realizations.

Hit create plot, and compare plotting to see that the results are duplicate.
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [X] python 3.12
- [X] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by oyvindeide** [comment]
Thanks for creating the issue! Solved in: https://github.com/equinor/ert/pull/8643, we will create a backport of this to the stable version.
