### ISSUE TITLE
Publish documentation to Github Pages

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#869]
Just as ecl2df does it: https://equinor.github.io/ecl2df/

We can publish ERT, libres, libecl and semeio pages. This will make it easier to access outside of the internal network.

**Comment by markusdregi** [comment]
The internal ERT documentation will contain documentation of internal jobs etc ASAP. Hence, this does not make sense on an ERT-level. I suggest we open similar issues in the corresponding repositories where this makes sense.
