### ISSUE TITLE
Wells with slashes will not work through Ert

### ISSUE THREAD

**Issue by berland** [equinor/ert#8716]
From the exception logs the message

`Please report this error and try restarting the application.{"detail":"Not Found"} from url: http://127.0.0.1:51820/ensembles/cc00b469-xxxxxxxxxx-caff54ad717a/records/WBHP:46/3-7S.`

can be found (well-name anonymized). 

The reason is most likely the presence of a slash `/` in the well-name. This is valid in Eclipse (though it must be quoted in the DATA file). 

Ert should support well-names that include slashes.

**Comment by berland** [comment]
More context:

![image](https://github.com/user-attachments/assets/c4536d27-1e91-44eb-a967-6c7721055fbc)

**Comment by eivindjahren** [comment]
I guess this means that we have to escape all summary keys, parameter names and response names?

**Comment by xjules** [comment]
>I guess unescape for GUI and CLI. 

What do you mean by this @eivindjahren ?

**Comment by eivindjahren** [comment]
@xjules We do not want to show `WBHP:46%2F3-7S` in the GUI, we want to show `WBHP:46/3-7S`.
