### ISSUE TITLE
Missing validation when using ForwardModelStepPlugin causes ert to hang

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#8729]
### What happened? (You can include a screenshot if it helps explain)

Installed a forward model step using ForwardModelStepPlugin. Tested without having the executable file available. Expected ert to fail:
![Screenshot 2024-09-18 at 09 59 02](https://github.com/user-attachments/assets/b2cdc663-8b26-4576-8e57-334a3dcf1c02)

If I install using INSTALL_JOB in the config file it is checked and ert stops with a "could not find executable".

If I try to run it through the gui the progress stops at Pending (the error message appears in the terminal that starts ert)

### What did you expect to happen?

Ert should stop on failure.

### steps to reproduce

```Python
Create dummy ForwardModelStep hook with a non-existing file as executable and run.
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [x] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by jonathan-eq** [comment]
This can be a corner case where users submit forward models steps where the node has a different environment, and validation passing on the user end might not pass on the job_runner end. Should we have submit the config validation to the job_runner as a forward model step?

**Comment by sondreso** [comment]
I don't think doing the validation on the forward model side is necessary here :thinking: `/prog/pflotran/bin/_runcirrus` should be available both places, so think there is some different reason why the executable is not validated.

**Comment by jonathan-eq** [comment]
![image](https://github.com/user-attachments/assets/5d2008b9-f046-4193-ae53-042cb5eee70b)

**Comment by lars-petter-hauge** [comment]
> I don't think doing the validation on the forward model side is necessary here :thinking: `/prog/pflotran/bin/_runcirrus` should be available both places, so think there is some different reason why the executable is not validated. 

Note that my issue concerns a scenario where path is incorrect, leading to a non-existing executable.
