### ISSUE TITLE
Exceptions in forward_model_runner will cause it to hang

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8738]
Related to https://github.com/equinor/ert/issues/8729

Uncaught exceptions in the `forward_model_runner` will cause it to hang. This is most likely due to some of the reporters running in a separate thread that will never get the event signaling that they should exit.

**Comment by emadellaloggia** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
