### ISSUE TITLE
Use EnsembleEvaluator in Everest

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8754]
**Issue**
Currently Everest is using the legacy way of communicating statues from Ert, we should upgrade it to also use the EnsembleEvaluator, like Ert.

**Comment by oyvindeide** [comment]
This is probably a large issue, so a first step is to evaluate the code, and see if this can be split into smaller issues. If that is possible, we should use this issue as a tracker for the other issues.

**Comment by frode-aarstad** [comment]
#8905 
#8906

**Comment by oyvindeide** [comment]
Closed as we are now using the EE in Everest 🎉 #9308
