### ISSUE TITLE
Warning if the simulation folder is not empty

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#8759]
**Issue**
Users should receive a warning that the simulation folder used for the optimization is not empty. And should be given a choice to delete it via a dialog or checkbox in the GUI. In the CLI a warning should be given and delete the folder before the run starts.

**Comment by oyvindeide** [comment]
Also be aware that ert already has functionality for this, so if we can align the two, that is beneficial.

**Comment by yngve-sk** [comment]
For this we could override the `check_if_runpath_exists()` in the `EverestRunModel`, then in the everest execution flow, create an everest baserunmodel right after the everest config is initialized, and invoke `check_if_runpath_exists()`. I'm assuming there is no existing logic for checking if the runpath exists in Everest. 

If you can get to know the range of GEO_ID and REALIZATION, you can do a more thorough check, but I think it would also be fine to start with something simple, like just checking if the simulation output directory exists.

**Comment by yngve-sk** [comment]
Open question/edge case this: Will a terminal prompt mess up someones workflow? If they have a bash script they expect to just run, and `everest run` is part of that, the prompt would halt it forever
