### ISSUE TITLE
Error reporting for users when the max_runtime limit is reached.

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#8760]
**Issue**

When the `max_runtime` limit is reached for the simulation, it is difficult to identify what happened. The user needs to comb through the logs of the `everest_server` to see. The optimization fails with the message `Optimization failed: not enough successful realizations to proceed.` and no reason for this. 

No `ERROR` file is generated in the runpath and at a glance the `eclipse` error and log files look ok. 

**Definition of done**
A clear error message is provided to the user that the `max_runtime` was reached and the forward model run was interrupted.

**Comment by oyvindeide** [comment]
This is somewhat related to the ensemble evaluator, as that has seen significant upgrades related to this. That means this issue might be blocked for now, but not 100% sure.

**Comment by oyvindeide** [comment]
Blocked by: #8754
