### ISSUE TITLE
Passing multiple, space-separated args to single forward model kwarg doesnt work

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#8763]
### What happened? (You can include a screenshot if it helps explain)

User tried using the `DELETE_FILE` forward model and delete multiple files in one invocation. This is expected to delete the file, but does not.  Problem is that in the lark grammar parsing step, this will just concatenate the space-separated words into one.

### What did you expect to happen?

It should delete the files, the lark parse step should parse a list of args instead of concatenation of the args.

### steps to reproduce

Use this test:

```Python

def test_that_multiarg_fm_is_parsed_correctly(
    tmp_path,
):
    (tmp_path / "test.ert").write_text(
        dedent(
            """
        NUM_REALIZATIONS  1
        FORWARD_MODEL DELETE_FILE(<FILES>=one two three)
        """
        )
    )

    config = ErtConfig.with_plugins().from_file(
        tmp_path / "test.ert"
    )
```

to create a config and see how the arglist comes out as `['FORWARD_MODEL', 'DELETE_FILE', [('<FILES>', 'onetwothree')]]`, we want `[('<FILES>', ['one','two','three'])]`

Can be verified to work by (1) running poly example, (2) manually creating some files in the runpath, (3) add `DELETE_FILE` forward model to ert config and expect those (multiple) files to be deleted.

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by eivindjahren** [comment]
For backwards compatability reasons subsequent strings means concat:
```
FORWARD_MODEL JOB(<JOB_NAME>= "MY" "JOB")
```
will result in the `<JOB_NAME>` being `"MYJOB"` just like in python. However, we also have unquoted strings which consists of non space alphanumerical characters, so the following all mean the same thing:

```
FORWARD_MODEL JOB(<JOB_NAME>=MYJOB)
FORWARD_MODEL JOB(<JOB_NAME>="MYJOB")
FORWARD_MODEL JOB(<JOB_NAME>="MY"JOB)
FORWARD_MODEL JOB(<JOB_NAME>="MY"  JOB)
FORWARD_MODEL JOB(<JOB_NAME>=M"YJ"OB)
```

this is all for backwards compatibility reasons and is not compatible with the proposed change.

The desired behavior for DELETE_FILE can be gotten from
```
FORWARD_MODEL DELETE_FILE(<FILES>="one two three")
```
