### ISSUE TITLE
Ert release 11.0.0-rc0 not getting deployed to pypi

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#8764]
### What happened? (You can include a screenshot if it helps explain)

I created a new tag 11.0.0-rc0, and it is failing tests in the pipeline, so it is not getting deployed to pypi. 
The tests have sometimes been a bit flaky, but now after four reruns - it seems to be completely locked.
All tests except macos py3.12 x86 pass, and this is the one we dont run on PRs, so it could be a bad commit causing the problems. (https://github.com/equinor/ert/actions/runs/10958740100/job/30434829615)
Currently, we have a release on github that is not available on pypi, and this discrepancy should be closed. 

### What did you expect to happen?

Ert 11.0.0-rc0 available on pypi, and preferably increased testing on PRs so this can be caught earlier (if this is the case).

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [X] python 3.12
- [X] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by eivindjahren** [comment]
Seems like this is the problem: https://github.com/equinor/ert/actions/runs/10958740100/job/30434829615#step:8:3122
