### ISSUE TITLE
Run everest tests in komodo

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8783]
Currently only the ert tests are run in the nightly tests, we should also include the everest tests there: 

https://github.com/equinor/ert/blob/b9b23de63990b357248f631f95815a09fc44e7ec/ci/testkomodo.sh#L14,

we can take inspiration from: https://github.com/equinor/everest/blob/main/ci/testkomodo.sh#L9-L24, but should review that to make sure as many tests as possible run, and if there are exceptions, we should review why the exception exist and see if the can start running them.

**Comment by DanSava** [comment]
Should we also disable the Everest komodo tests?
