### ISSUE TITLE
flaky tests/ert/unit_tests/forward_model_runner/test_job.py::test_memory_usage_counts_grandchildren

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8788]
https://github.com/equinor/ert/actions/runs/11014347030/job/30584774919?pr=8785

**Comment by yngve-sk** [comment]
Seems to be expected flaky but has
```
@pytest.mark.flaky(reruns=5)
```
maybe just increase the reruns if the authors of the test (@berland , @JHolba ) agree with this?

**Comment by eivindjahren** [comment]
I think the problem is that the monitoring thread polls in arbitrary intervals so you are not guaranteed to observe anything in particular.

**Comment by JHolba** [comment]
we can try to increase the sleep in the script. that should make it less flaky
