### ISSUE TITLE
Fix read the docs build for everest

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8806]
### What happened? (You can include a screenshot if it helps explain)

Documentation is not built for everest: 
https://readthedocs.org/projects/everest/builds/

### What did you expect to happen?

The documentation to be built

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by DanSava** [comment]
Found this link that explains how to setup  `.readthedocs.yaml` file in a sub-folder https://docs.readthedocs.io/en/stable/guides/setup/monorepo.html 

It requires access to admin settings.
