### ISSUE TITLE
Ensure open api schema testing gets positive responses

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#883]
for all http endpoints the schema thesis testing is randomly trying different parameters. Ensure that some of them actually exist in the `populated_db`, either confirm examples are being used or create specific tests.

**Comment by oysteoh** [comment]
this task depends on FastAPI on the endpoints - tests should be executed towards that one when it is ready.

**Comment by jondequinor** [comment]
Depends on https://github.com/equinor/ert/pull/1105
