### ISSUE TITLE
Use plugin functionality to document forward models in Everest

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8835]
Ert uses the plugin system to document forward model jobs: https://github.com/equinor/ert/blob/e92f558cf14e9c9823b557b3df05caefef49576f/src/ert/shared/_doc_utils/ert_jobs.py#L17, while in Everest this is hard coded: https://github.com/equinor/ert/blob/e92f558cf14e9c9823b557b3df05caefef49576f/docs/everest/forward_model_jobs.rst?plain=1#L4.

Everest already has functionality to supply schemas from the forward model, we should be able to use that for documentation, and possibly extend from that.

We should also align this between Everest and ert so there is less duplication. For example ert now configures the forward models programmatically: https://github.com/equinor/ert/blob/9f8d73a6b4809a0384bda60632350d2123df7c0c/src/ert/plugins/hook_implementations/forward_model_steps.py#L20

**Comment by oyvindeide** [comment]
The definition of done here is that the forward model documentation is removed from everest, and all the forward models document themselves though the plugin system so that all the arguments, the schemas and examples are available to users.

**Comment by frode-aarstad** [comment]
We need to decide what to do with: https://fmu-docs.equinor.com/docs/everest/forward_model_jobs.html#eclipse-simulator.
