### ISSUE TITLE
Check expected behaviour of resource classes RdbApi, BlobApi, StorageApi

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#890]
In RdbApi and BlobApi the context manager code looks like this:

`    def __init__(self, connection):
        self._session = Session(bind=connection)

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self.close()
`

The interface makes it seem as if the object is a reusable context manager. But since the constructor is the one acquiring the actual resource and the exit method closes it, the enter method will return a useless state the second time it is called. The session will then have been closed, and no new one will be made. I guess the connection will also be closed?

The StorageApi class keeps instances of these classes as members, and itself exposes a context manager api. It also uses the RdbApi and BlobApi objects in a "with" statement in each of its public methods. This seems bound to fail if anyone does any of the following:

 * Changes StorageApi to use two with statements in the course of it's lifetime
 * Calls two methods on one StorageApi instance
 * Not sure what happens if one has two StorageApi instances

I propose we at least move the session initiation to the __enter__ method. Perhaps we don't need to use a with statement in the StorageApi at all, since it is also a context manager, and should just close the RdbApi and BlobApi when it is closed.

Perhaps the only class that should be used in a with statement is the connection object, or session object, and then we pass this to the other classes?

**Comment by oysteoh** [comment]
This will be investigated and a walkthrough of the code is necessary - thus i'm closing this issue. The design of these classes was necessary to do like this to make it fly. It is tested and seems to work. `I guess the connection will also be closed?` - No i don't think so. We initialize the connection up front and passes these down to the implementation classes which uses the connection to create a session. When done - the session is closed, but the connection is still alive and will be reused on next usage. I propose if you have any concrete issues - make a test which proves the failure and then we have that as an issue. But i agree - the design is not optimal - and will probably be rewritten 👍

**Comment by oysteoh** [comment]
This one hit me earlier than expected - thus reopened and made a PR with an attempt to address the session problem.
