### ISSUE TITLE
Remove the iEverest GUI

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#8907]
With the work integrating the ensemble evaluator with everest it will become more and more work keeping the everest gui working as before. We need to decide if its worth the effort. Eventually it would be nice to create a web-type gui as a replacement

**Comment by oyvindeide** [comment]
We muust check the logs for the percentage of users, will also check with users to see if their usage is, and if it can be covered by the cli.

**Comment by oyvindeide** [comment]
Let us remove this, there are very few if any users. If a user runs the `gui`command, they should get a message saying this is removed, and the equivalent `run` commend they need to paste in their terminal.
