### ISSUE TITLE
Documentation - poor description of kw

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#891]
Docs of kw ENKF_ALPHA refers to UPDATE_SETTINGS and OVERLAP_LIMIT, but neither of these are mentioned further in the docs. Suggestion is to write a proper description of ENKF_ALPHA, the assess what to do with the others.

**Comment by oysteoh** [comment]
Duplicate of #958

**Comment by oysteoh** [comment]
Related to #958

**Comment by oysteoh** [comment]
Duplicate of #958
