### ISSUE TITLE
Unclear error message from "load results manually" tool

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8995]
### What happened? (You can include a screenshot if it helps explain)

When all (or some) realizations are missing from the runpath you get a bad error message.

![Image](https://github.com/user-attachments/assets/cf933e02-db9f-4c75-bec6-99001797bb89)

### What did you expect to happen?

You get a clear and concise warning whenever a realization cannot be loaded manually and the corresponding realization is marked as failed.

### steps to reproduce

from a clean ert git repo (`git clean -f test-data` to remove remnants of previous runs)
```
mkdir test-data/ert/poly_example/poly_out
ert gui test-data/ert/poly_example/poly.ert
```
Then in the gui:
* Click on "manage experiments";
* Click on the "+" button;
* Click on "ok";
* Close the "manage experiments" dialog;
* click on "load results manually";
* click on "ok".

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by jonathan-eq** [comment]
It seems to have been fixed
![Image](https://github.com/user-attachments/assets/f882ec21-4241-48b6-8991-b515fbc27903)
