### ISSUE TITLE
BUILD_ERT_GUI on request only

### ISSUE THREAD

**Issue by agchitu** [equinor/ert#9]
Adding back the possibility to only build the command line applications.
 
Building the GUI requires qt libraries for python among other ones and that makes it too heavy for instance for cases when the only thing you want is integration testing in a CI/CD workflow.
Also there are already other ert applications that one might want to use in a command line on a daily basis.
Using ert in a batch mode is useful in workflows that do not require user interaction.

**Comment by jondequinor** [comment]
The `ert` binary can now be run with the `cli` argument, which allows you e.g. run realizations inside a docker container, like I did:

```bash
docker run -it ubuntu:16.04 bash
[build libecl, libres]
root@cc310668da79:~/ert# ert cli test-data/local/poly_example/poly.ert --mode ensemble_experiment --target-case default
100 of the realizations were successful
```

I.e. no qt nor pyqt required.
