### ISSUE TITLE
Number of threads used when starting ERT in batch mode from ERT

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#900]
ERT explicitly sets the number of threads to 1 when running RMS. Users wants this to be picked up from the project settings or possibly to specify it in ERT.

**Comment by markusdregi** [comment]
I don't think this is the issue. The problem is that RMS does not always respect the threads command line argument (that is always 1) from ERT and hence sometimes runs with multiple threads instead of a single one on the cluster.

**Comment by sondreso** [comment]
Email sent with the command line arguments that ERT uses when starting RMS

**Comment by sondreso** [comment]
This is a problem with RMS, closing
