### ISSUE TITLE
RuntimeError upon submission of forward model to SLURM with  MAX_RUNTIME

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/ert#9000]
### What happened? (You can include a screenshot if it helps explain)

An error upon submission of forward model to SLURM when option MAX_RUNTIME is used:

```
QUEUE_OPTION SLURM MAX_RUNTIME 3600
```

Returns:
```
RuntimeError: Command "sbatch --job-name=MODEL_0 --chdir=/ert/output/simulations/realisation-0/iter-0 --parsable --output=MODEL_0.stdout --error=MODEL_0.stderr --ntasks=1 --mem=11G --time=3600.0 --partition=longq /ert/output/simulations/realisation-0/iter-0/.slurm_submit_u73vwnk2.sh" failed with exit code 255, output: "<empty>", and error: "sbatch: error: Invalid --time specification"
```

As per documentation https://slurm.schedmd.com/sbatch.html:

>A time limit of zero requests that no time limit be imposed. Acceptable time formats include "minutes", "minutes:seconds", "hours:minutes:seconds", "days-hours", "days-hours:minutes" and "days-hours:minutes:seconds".

It seems float format `3600.0` is not allowed. I manually run the command with correction to `3600` and it worked fine. 

### What did you expect to happen?

No error.

### steps to reproduce

Use option:

```
QUEUE_OPTION SLURM MAX_RUNTIME 3600
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by berland** [comment]
Thanks for the report, we will pick this up.
