### ISSUE TITLE
Improved logging of data and parameters used in updates

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#907]
There is a need for improved logging of data and parameters used in update/analysis steps. In particular when applying localization, the user has a need to confirm what has been included in each update.

**Comment by markusdregi** [comment]
So an overview of the parameters, simulated responses and observations used when running an update step? I vote for this as well to be made available through the new storage...

**Comment by jondequinor** [comment]
I think this should be a part of a larger _provenance_ theme. All data produced by ERT (updates, run forward models) should have its provenance traceable "[…] to provide contextual and circumstantial evidence for its original production or discovery, by establishing, as far as practicable, its later history, especially the sequences of its formal ownership, custody and places of storage".

I think this work should be dealt with in many ways simultaneously:

- Make all changes to data, and new data to exhibit a transactional nature. This way, ERT does not simply change data left and right, but has to submit transactions to some system that eventually could also tackle the problem of provenance.
- Extend the Storage API to be able to write [PROV](https://www.w3.org/TR/prov-overview/) triplets to some graph database.
- Identify the agents, entities and activities that would make sense to produce provenance.

I strongly favor the general provenance approach as described by W3C as a basis for the functionality described by @eivindsm, such that ERT does not invent its own vocabulary to express provenance.

**Comment by oyvindeide** [comment]
There is the update snapshot, this is also covered in: #4156
