### ISSUE TITLE
Problems related to everest with torque

### ISSUE THREAD

**Issue by AugustoMagalhaes** [equinor/ert#9082]
Greetings,

I've been facing some issues when running everest in a hpc cluster with torque. I'm not sure exactly what's happening but I wanted to check with you guys if the following error could be related to not having an stdout/stderr file for torque's output. The error happens when the everserver is being started in the login node, which I can't completely debug inside the site-packages files due to permission issues. 

This first image is regarding the error itself when trying to start the everserver:
![Image](https://github.com/user-attachments/assets/09923d73-aa54-430c-9aa0-5cf1aee0de4c)

The next one is the output of the pbs job log (qstat -x -f <num_job>):
![Image](https://github.com/user-attachments/assets/22e762be-b9e0-48cc-b658-585716c92c8e)

Any suggestions would be very helpful! :)

**Comment by yngve-sk** [comment]
Hey Augusto, a "fix" for this was merged in yesterday, https://github.com/equinor/ert/pull/8898 , the [issue text](https://github.com/equinor/ert/issues/8896) matches up very closely to what you describe. Was the ERT version you were running up-to-date with this? If not I would suggest trying to re-run and report back if it still happens.

**Comment by AugustoMagalhaes** [comment]
> Hey Augusto, a "fix" for this was merged in yesterday, [#8898](https://github.com/equinor/ert/pull/8898) , the [issue text](https://github.com/equinor/ert/issues/8896) matches up very closely to what you describe. Was the ERT version you were running up-to-date with this? If not I would suggest trying to re-run and report back if it still happens.

This actually happened on friday, Yngve. Thanks a lot! :)
