### ISSUE TITLE
Make it possible to restart ES-MDA

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#910]
It should be possible to run ES MDA and if it crashes, rerun from an already ran iteration. This should be solvable by allowing the user to specify which iteration should be the first iteration.

**Comment by markusdregi** [comment]
A consequence of this should be that it is possible to run your prior as an ensemble experiment and then run the rest of the iterations as an ES-MDA run on top of this.

**Comment by markusdregi** [comment]
We should at least investigate whether this is feasible to solve within a reasonable amount of time.

**Comment by eivindsm** [comment]
We should also implement a corresponding magic string, enabling advanced users to access the iteration in eg the config file.

**Comment by sondreso** [comment]
@eivindsm There is already a keyword for getting the iteration (<ITER>), which can be used on the forward model jobs. I'm not sure it works together with workflows. Maybe we should create a separate issue for investigating the keyword and documenting it?

**Comment by eivindsm** [comment]
Yes, that is a good solution. My comment was motivated by the question posted in the #ert-users channel at equinor.slack.com regarding accessing ITER in a workflow.

**Comment by sondreso** [comment]
Created https://github.com/equinor/ert/issues/979
