### ISSUE TITLE
Investigate initiate batch dispatch on ensemble finish

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#9136]
Have the dispatcher dispatch immediately when it knows there will no more messages, instead of waiting the default batch period to send messages

**Comment by xjules** [comment]
> Have the dispatcher dispatch immediately when it knows there will no more messages, instead of waiting the default batch period to send messages

For running tests, we can just adjust `evaluator._batching_interval` if we don't want to wait for the batch to complete.
See here: https://github.com/equinor/ert/blob/70e85a76a6a27f5716c45c1ec4b8b276daf4f808/tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py#L138

**Comment by JHolba** [comment]
adjusting the batching interval will increase the workload for the evaluator, monitor and gui though

**Comment by xjules** [comment]
> adjusting the batching interval will increase the workload for the evaluator, monitor and gui though

Yes, but this can be changed based on the test requirements, so no biggy...
