### ISSUE TITLE
Remove CASE_NAME concept from Everest?

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#9159]
`<CASE_NAME>` is not possible to set from outside of Everest, and it is currently always mapped to the ensemble name, i.e., `batch_N` where `N` is the batch#. We could maybe remove this concept from Everest alltogether.

**Comment by verveerpj** [comment]
There is a need for some substitution internally to construct the path using batch_N, so an substitution is needed while creating the runpaths in the everest run model. Therefore I suggest leaving it as is.
