### ISSUE TITLE
Remove dependencies on (mocked and unmocked) SEBA snapshots in tests

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#9172]
Currently, for example `tests/everest/test_api.py` and `tests/everest/test_export.py` are depending a lot on seba snapshots and mocking of seba snapshots. In order to migrate over to a new storage solution, we need tests like these that can be applied to different storage solutions (without depending on seba / mocked SebaSnapshot functionality). 

Use of seba snapshot should also be removed from other files, ideally create one sub-issue per logical file/group and do a PR related to that.

Definition of done:
No use of seba or mocking of related classes within all Everest tests.

**Comment by oyvindeide** [comment]
All sub issues fixed, so till close this now 🎉
