### ISSUE TITLE
Deprecate Torque option MEMORY_PER_JOB

### ISSUE THREAD

**Issue by berland** [equinor/ert#9176]
Following #8215 this option should be deprecated.

**Comment by berland** [comment]
There are likely few users of this option implying the deprecation period before removal can be short, say 2 months.

**Comment by jonathan-eq** [comment]
An entry for this queue_option already exists in `config_schema_deprecations`. It seems it was already added six months ago in 8cba19d21bfa058b4769aa1663c5014685f21e7e.
Can this issue be marked as completed, or do we have to deprecate it in the docs as well first?

**Comment by berland** [comment]
Can be marked completed, and start actual removal.
