### ISSUE TITLE
Set ClientIP when logging to Azure

### ISSUE THREAD

**Issue by berland** [equinor/ert#9187]
The field `ClientIP` is always `0.0.0.0` in the logs. It would be nice to know which IP/hostname actually submitted a log, so this is something we should fix.

**Comment by HakonSohoel** [comment]
I see that https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete#client-ip-address

**Comment by sondreso** [comment]
BTW: the cloud_RoleInstance seems to be set to the hostname

 ![Image](https://github.com/user-attachments/assets/8e6d0456-19cc-4302-acee-4e42b8590854)

**Comment by HakonSohoel** [comment]
Conclusion: The Role Instance host name is what we need. So we leave the IP collection as disabled
