### ISSUE TITLE
Resolve NFS sync issues when the .lsf_submit file is not present yet

### ISSUE THREAD

**Issue by berland** [equinor/ert#9197]
An error is observed in the logs:

```
File "/prog/res.../ert/scheduler/lsf_driver.py", line 301, in submit
    with tempfile.NamedTemporaryFile(
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
Unexpected exception in ensemble: 
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/bauxxxxxxxxxxxxxxxxxxxxx/realization-5/iter-0/.lsf_submit__1erjqds.sh'
```

which is most likely a NFS sync issue. This should be possible to workaround.

**Comment by eivindjahren** [comment]
Should be possible to have a simple retry mechanism in the bsub.

**Comment by berland** [comment]
This cannot be an NFS sync issue, as everything happens inside the Ert process, and not on the compute side.

A potential cause could be the user doing `rm -rf ` on the runpath while Ert is firing up.

**Comment by eivindjahren** [comment]
Seeing as we don't know what happened here, I think we will have to work on getting more observability until we are able to resolve issues like this.
