### ISSUE TITLE
Clean up math func folder

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9210]
The math func folder (test-data/everest/math_func) has a number of config files, most are just slight variations of the same one, used for testing.

We should clean this up by deleting most of the config files, and only keep enough to serve as a minimal example. The others should be edited in the tests that require them, and not checked in as text files.

**Comment by frode-aarstad** [comment]
> [@oyvindeide](https://github.com/oyvindeide) [@frode-aarstad](https://github.com/frode-aarstad) Is this related to [#9211](https://github.com/equinor/ert/issues/9211)? Or can I safely pick this up and work on this in parallel?

It should be safe to pick up

**Comment by StephanDeHoop** [comment]
> > [@oyvindeide](https://github.com/oyvindeide) [@frode-aarstad](https://github.com/frode-aarstad) Is this related to [#9211](https://github.com/equinor/ert/issues/9211)? Or can I safely pick this up and work on this in parallel?
> 
> It should be safe to pick up

Thanks, will do :)!
