### ISSUE TITLE
timeout from LocalStorage.acquire_lock can result in an unhandled exception

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9223]
Do not have any reproducing steps yet, but one can seemly get an unhandled exception from acquire_lock timeing out. This has been observed using ert-11.0.7.

https://github.com/equinor/ert/blob/9819a5b03255355abd69d16667bd95ae69e0afbc/src/ert/storage/local_storage.py#L277-L287

**Comment by sondreso** [comment]
The first step is to not make this an unhandled exception.
