### ISSUE TITLE
Progress bar shows finished status for non existing realizations

### ISSUE THREAD

**Issue by kjetilbjorke** [equinor/ert#9230]
### What happened? (You can include a screenshot if it helps explain)

Started only 3 realizations on/of an ensemble experiment. Progress bar shows 247 finished realizations which does not exist. 
![Image](https://github.com/user-attachments/assets/2dad19d0-303e-46c6-898f-f039e98b6895)

### What did you expect to happen?

Progress bar and status only to include the 3 realizations.

### steps to reproduce

```Python

```

### Environment where bug has been observed

- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [ ] local queue
- [x] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by jonathan-eq** [comment]
Relates to https://github.com/equinor/ert/issues/9455
