### ISSUE TITLE
ecl_run not able to parse errors from MPI runs

### ISSUE THREAD

**Issue by berland** [equinor/ert#9237]
The pattern for detecting error messages from the Eclipse output

https://github.com/equinor/ert/blob/cc33a48341d019c88b1b5e414e99b85317f762ca/src/ert/resources/forward_models/res/script/ecl_run.py#L50

will not catch errors when Eclipse uses multiple CPUs which can look like this:

```
@--  ERROR FROM PROCESSOR 1 AT TIME        0.0   DAYS    (21-DEC-2002):
@           LICENSE FAILURE: ERROR NUMBER IS -4
```

**Comment by berland** [comment]
Due to this bug, the message:

`Warning, mismatch between stated Error count (1) and number of ERROR messages found in PRT (0).
`
is logged (and it also logs the tail of the PRT file)

**Comment by HakonSohoel** [comment]
Do we have an example of how such an Error message  looks on E300, or it is assumed to only be an issue with E100?

**Comment by berland** [comment]
> Do we have an example of how such an Error message looks on E300, or it is assumed to only be an issue with E100?

We don´t have that example, that is probably a another small issue..
