### ISSUE TITLE
Kill Eclipse simulation on the local node when MAX_RUNTIME is reached

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#924]
Issue from Yammer (June 12th 2020):
- Single Realisation Test Run
- FORWARD MODEL ECLIPSE100(<VERSION>=2018.2)
- ERT max runtime: status 'failed' from the ERT window, but it continued until the last forward model in ERT config file.

**Comment by markusdregi** [comment]
I tested this earlier using the poly case; having the forward model sleep for a long time and that appeared to work fine. I would suggest trying to setup a similar setup, but where it is an Eclipse job that runs instead. If this is really an Eclipse problem it could also be the wrapper script in libres that is at fault.

**Comment by ManInFez** [comment]
This might have something to do with eclipse is not exiting with SIGTERM, which is what we are using to terminate remaining jobs.
