### ISSUE TITLE
ecl100 fails when a case already exists on disk

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9277]
### What happened? (You can include a screenshot if it helps explain)

ECL100 seems to fail if it runs in an existing runpath, or if running with NOSIM. In the NOSIM case, no summary files are created.

With NOSIM:
```
Traceback (most recent call last):
  File "/path/to/ert/resources/forward_models/res/script/ecl100.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/path/to/ert/resources/forward_models/res/script/ecl_run.py", line 560, in run
    run.runEclipse(eclrun_config=eclrun_config)
  File "/path/to/ert/resources/forward_models/res/script/ecl_run.py", line 454, in runEclipse
    find_unsmry(Path(self.run_path) / self.base_name)
  File "/path/to/ert/resources/forward_models/res/script/ecl_run.py", line 174, in find_unsmry
    raise ValueError(f"Could not find any unsmry matching case path {basepath}")
ValueError: Could not find any unsmry matching case path /scratch/somepath/realization-0/iter-0/eclipse/model/SOME_ECL_FILE-0
```

Might be related to: https://github.com/equinor/ert/blob/57e6b70db861f019241a999010b09279469527f9/src/ert/resources/forward_models/res/script/ecl_run.py#L165C22-L168C10, which maybe should be:

```python
return splitted[-2] == base
```

### steps to reproduce

```Python
Run ECL100 with NOSIM or run ECL100 in an existing runpath.
```

### Environment where bug has been observed

- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by andreas-el** [comment]
Also reported on viva:
https://engage.cloud.microsoft/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMzA3NDA1MzY1Mjk3MTUyMCJ9?trk_copy_link=V2
