### ISSUE TITLE
Excessive memory usage when opening plotter with large storage

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9289]
In an model seen in real use, storage had two ensembles, each 20gb, 200 realizations and 100mb of summary.parquet. The summary had 60,000 columns. This caused opening the plotter to run out of memory on beefy tgx nodes.

**Comment by eivindjahren** [comment]
@oyvindeide The old issue was about a timeout while this is excessive memory usage.

**Comment by DanSava** [comment]
Should we look into downsampling strategies for response data? 
https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html

**Comment by oyvindeide** [comment]
This has been fixed now, though the responsiveness could still see some improvements.
