### ISSUE TITLE
Remove RSH queue driver

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#930]
The RSH driver has been [deprecated for quite some time](https://github.com/equinor/ert/pull/640), so we can delete it now.

**Comment by markusdregi** [comment]
This could be tested by similar means as introduced in https://github.com/equinor/ert/pull/1849 for LSF.

**Comment by dafeda** [comment]
`RSH` is deprecated [according to our documentation.](https://ert.readthedocs.io/en/latest/reference/queue.html#available-queue-systems)

Should we still test it?

**Comment by sondreso** [comment]
No, the RSH driver has been deprecated for quite some time, so we can delete it now. I have updated the title and description to reflect this.
