### ISSUE TITLE
ERT fails in update step if AUTO_SCALE cannot match any observations

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#9339]
### What happened? (You can include a screenshot if it helps explain)

User report where there was a mismatch in the name of the observations and the string given to AUTO_SCALE, e.g. observations was named `obs_*` whereas the input for AUTO_SCALE was `OBS_*` . This caused ERT to fail with the following message:
EndEvent(failed=True, msg="cannot concat empty list\nopening handshake failed\nopening handshake failed\nNo observations active for group: ['OBS_*']")

### What did you expect to happen?

I would except ert to not crash in this case, and ideally we should give a warning that there are no matches during the config parsing to avoid typos and such?

### steps to reproduce

```Python
Add following line to poly.ert: ANALYSIS_SET_VAR OBSERVATIONS AUTO_SCALE OBS_*
run es_mda
```

### Environment where bug has been observed

- [ ] python 3.10
- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by berland** [comment]
The corresponding error in Ert 11.0 is:
`Experiment failed with the following error: No objects to concatenate
`
