### ISSUE TITLE
Histogram plotting calls logarithm of zero

### ISSUE THREAD

**Issue by berland** [equinor/ert#935]
User report:  "ERT gui plotting window to visualize the convergence of uncertain parameters.
... not able to plot the parameters with LOGUNIF distribution":

![image](https://user-images.githubusercontent.com/306834/86226050-60f8fc80-bb8b-11ea-84f2-854ff7f929c8.png)

There should probably be a check for zero values and do something better than crash.

**Comment by markusdregi** [comment]
Thanks for the report. We'll have a look!
