### ISSUE TITLE
Eclipse forward model does not work in Everest

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9378]
### What happened? (You can include a screenshot if it helps explain)

Running everest with eclipse does not work, the forward model fails, and get:

```
Traceback (most recent call last):
  File "/path/to/ert/resources/forward_models/res/script/ecl100.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/path/to/ert/resources/forward_models/res/script/ecl_run.py", line 566, in run
    sim = config.sim(version=options.version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/ert/resources/forward_models/res/script/ecl_config.py", line 154, in sim
    return self._get_sim(version, Keys.scalar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/ert/resources/forward_models/res/script/ecl_config.py", line 137, in _get_sim
    binaries: Dict[str, str] = self._config[Keys.versions][version][exe_type]
                               ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'versions'
```

### steps to reproduce

```Python
Run the Everest egg case:

everest run config.yml
```

### Environment where bug has been observed

- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by berland** [comment]
Everest only sees the dummy ecl100_config.yml:

`{'eclrun_env': {'SLBSLS_LICENSE_FILE': 'something@yourcompany.com', 'ECLPATH': '/path/to/ecl', 'PATH': '/path/to/ecl/macros', 'LSB_JOBID': None}}
`
