### ISSUE TITLE
Everest fails to submit job using OpenPBS driver

### ISSUE THREAD

**Issue by cmrqs** [equinor/ert#9430]
### What happened? (You can include a screenshot if it helps explain)

When using `queue_system: torque`, the `everserver` job fails to submit:

```
$ everest run --debug --new-run config.yml

...

DEBUG:ert.scheduler.openpbs_driver:Submitting to PBS with command /usr/local/bin/qsub -rn -Ndummy -o /dev/null -e /dev/null -l select=1
ERROR:ert.scheduler.openpbs_driver:Command "/usr/local/bin/qsub -rn -Ndummy -o /dev/null -e /dev/null -l select=1" failed with exit code 188, output: "<empty>", and error: "qsub: Job violates queue and/or server resource limits"
```

**config.yml**:
```
simulator:
  name: opm
  queue_system: torque
  keep_qsub_output: 1
```

As we can see, the `qsub` command is not sending the job to the correct queue (`name: opm`) and thus fails to execute.
Also, `keep_qsub_output` doesn't work and no output file is created.

### What did you expect to happen?

The `qsub` command should have the argument `-q opm`:

```
DEBUG:ert.scheduler.openpbs_driver:Submitting to PBS with command /usr/local/bin/qsub -rn -Ndummy -q opm -l select=1
DEBUG:ert.scheduler.openpbs_driver:Command "/usr/local/bin/qsub -rn -Ndummy -q opm -l select=1" succeeded with exit code 0, output: "1232635.pbs", and error: "<empty>"
DEBUG:ert.scheduler.openpbs_driver:Realization 0 accepted by PBS, got id 1232635.pbs
DEBUG:ert.scheduler.openpbs_driver:Realization 0 is running
Waiting for server ...
```

And the files `dummy.o1232635` and `dummy.e1232635` should've been created.

### steps to reproduce

```Python
Execute any project using `queue_system: torque` as described above.
```

### Environment where bug has been observed

- [ ] python 3.10
- [ ] python 3.11
- [x] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [x] openPBS queue

**Comment by AugustoMagalhaes** [comment]
We've been struggling with this at UNICAMP for a while, thanks for solving it mate!
