### ISSUE TITLE
test_res_initialization.py::test_everest_to_ert_queue_config fails when a site config specifies `REALIZATION_MEMORY`

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9465]
This test will fail if there is a site_config which sets `REALIZATION_MEMORY` and the user has specified the `SLURM` option: `MEMORY`. Fixing this means making sure that the user specified `MEMORY` will overwrite the site config specified `REALIZATION_MEMORY`. If the user has specified both and none come from the site config the current error is ok.

To reproduce with the poly example, add:

```bash
QUEUE_OPTION SLURM MEMORY
``` 

and modify the site config by adding:

```python
"REALIZATION_MEMORY 100"
```

![Image](https://github.com/user-attachments/assets/0f4a03ef-ca63-40e5-8c41-9db86df1aeea)

**Comment by jonathan-eq** [comment]
This can probably be done pretty easily in `ErtConfig._merge_user_and_site_config`

**Comment by sondreso** [comment]
> Fixing this means making sure that the user specified MEMORY will overwrite the site config specified REALIZATION_MEMORY

Why are we doing this when using the MEMORY keyword with SLURM is deprecated? Think we should rather use REALIZATION_MEMORY and then remove MEMORY.
