### ISSUE TITLE
Total progress bar exceeds 100

### ISSUE THREAD

**Issue by berland** [equinor/ert#9467]
In logs it is observed:

`2024-12-06 09:40:37.416 ￼level=warning msg=Total progress bar exceeds [0-100] range: 119
`

coming from the line:

https://github.com/equinor/ert/blob/b903bb03be7e401622f604442691b36e5addbde4/src/ert/gui/simulation/run_dialog.py#L508

OperationId: dbe177e6f0cdc458ec87042bdb8883af (Komodo 2024.11.09)

**Comment by jonathan-eq** [comment]
I suspect this bug occurs in the grey area when we press `Rerun failed` on an esmda run, which should be disabled.
