### ISSUE TITLE
Progress bar incorrectly shows status for realizations

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#9473]
Reproducible with `2024.11.10` or by fetching the `ert 11.1.8` tag.
Experienced running (local) MDA on TGX and local MDA on Mac.

Steps to reproduce:
- Use stable/2024.11.10 or `11.1.8` tag
- Add random failure in poly_eval.py (poly example)
- Run MDA

Example to trigger fails:
```diff
diff --git a/test-data/ert/poly_example/poly_eval.py b/test-data/ert/poly_example/poly_eval.py
index 33c67d8a1..c14e9018a 100755
--- a/test-data/ert/poly_example/poly_eval.py
+++ b/test-data/ert/poly_example/poly_eval.py
@@ -8,6 +8,10 @@ def _load_coeffs(filename):


 def _evaluate(coeffs, x):
+    import random
+    r = random.random()
+    if r > 0.9:
+        raise ValueError()
     return coeffs["a"] * x**2 + coeffs["b"] * x + coeffs["c"]
```

When experiencing failing realizations the progress bar does not seem to reflect the correct status for the realizations.
Given that the progress bar label shows `iteration 3`, I'd expect the progress bar to show the end result status for that iteration.

What is the correct number of realization (total) count to show in the labels?
Do we assume that finished count is finished = all - failed ?
How come the two progress bars screenshotted below show wildly different colours?

Running locally on Mac
![Image](https://github.com/user-attachments/assets/e55a6c1d-d6ad-4421-be21-45df5e0e76e1)

Running on TGX
![Image](https://github.com/user-attachments/assets/c2b6a1a6-cf09-4006-9407-6cfa7a7bb091)

Screen recording
https://github.com/user-attachments/assets/56b61d89-5d90-45f0-8919-99a7545916d3

**Comment by jonathan-eq** [comment]
This might be related to https://github.com/equinor/ert/issues/9455

**Comment by andreas-el** [comment]
Not reproducible on main, so closing as resolved. 👍
