### ISSUE TITLE
ValueError: FOPR is not a response from manage_experiments

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9549]
### What happened?

When clicking around after creating an experiment manually, you can get a ValueError

### steps to reproduce

ert gui test-data/ert/snake_oil/snake_oil.ert
add a new ensemble through "manage experiments"
click on the newly created ensemble and then on observations

https://github.com/user-attachments/assets/751ceb85-42e2-403d-859a-8db59a3f7b7a

### Environment where bug has been observed

- [ ] python 3.11
- [x] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by yngve-sk** [comment]
Previous behavior: 
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/869f94c3-2863-4562-8c8a-87a13284a49c" />

Though it is strictly speaking an empty ensemble with no responses, and this view is supposed to show observations and accompanying responses at the ensemble level, if there are no responses to compare the observations to, I'm not sure the view has any purpose other than seeing observations one by one, plotted on a 1d axis. 

Quickfix for this is to just return an empty dataset in `load_responses` if requested for 0 realizations.

If `ensemble.get_realizations_list_with_responses()` resolves to `[]`:
```
       response_ds = self._ensemble.load_responses(
            response_name,
            tuple(self._ensemble.get_realization_list_with_responses()),
        )
``` would return an empty dataset as done before.

Would opt for only having that view enabled if the ensemble is non-empty for edge cases.
