### ISSUE TITLE
Replace data export functionality

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#956]
This issue is regarding the functionality implemented for the `Export Data`-button. It will dump the data in storage into a folder structure representing the ensemble. However, the code is not in good shape and will currently crash under various usage.

Hence, a decision has been made to remove that functionality and instead let the `Export Data`-button expose the possibility of exporting a CSV-file. A first implementation could be backed by the same functionality as implemented in the `CSV_EXPORT2` job.

**Comment by ManInFez** [comment]
@markusdregi To be clear, we should utilize the actual CSV_EXPORT2 job or make an export function with the same functionality?

**Comment by markusdregi** [comment]
It is a bit up in the air 🤷 

**Summary**
Currently we have `CSV_EXPORT2` based on exporting from scratch using `fmu-ensemble` that exports into a csv-format that has received some care from @berland. Then, we have the `Export Data`-button that currently is broken (have been so for some time) and in addition exports to a format for which we believe is not used by any users.

The immediate conclusion is that we should remove the current `Export Data` functionality. On the other hand, it makes sense that ERT is capable to export some of its data to a CSV-file. This easily enables further data analysis in other tools (like Spotfire).

**In the "long" run**
In the long run we would like to get away from the architectural short cut the above solution presents; namely loading data directly from scratch. Hence, when the new storage is always used we should reimplement the exporting of data, both in workflows and in the UI, using the data API instead. At that point it makes sense to simultaneously reevaluate the layout of the CSV-files produced. I think this is an exercise that should be carried out by the storage squad in the not so distant future to mature the data API.

**Right now**
It is unacceptable to have a button that is almost guaranteed to crash the application. I suggest that we either:
- remove the button altogether for now,
- implement something similar to the `CSV_EXPORT2` using `fmu-ensemble` independently of `semeio` or
- back the button by the same code as `CSV_EXPORT2`; either by
    - optionally depending on `semeio` and display a pop-up saying that data export is not available if semeio is not installed or similar
    - move the code backing `CSV_EXPORT2` into `ert` (making `ert` depend on `fmu-ensemble` until further) and use that implementation in `CSV_EXPORT2` also (`semeio` already depends on `ert`, so that dependency is already there).

I'm leaning towards 3a or 3b, but I'm more than willing to listen ;)

**Comment by ManInFez** [comment]
I am thinking we should invest minimal effort into this, which is leaning at 3a, since the new storage solution will open up a much more sane method for exporting data. Basically, solution I am suggesting is just executing the CSV_EXPORT2 job if it is available.

**Comment by markusdregi** [comment]
That is compatible both with the list and my own leaning above. So if that is where the planets are guiding you, feel free to initiate ⭐
