### ISSUE TITLE
Fix tests/everest/test_detached.py::test_https_requests

### ISSUE THREAD

**Issue by xjules** [equinor/ert#9620]
### What happened? (You can include a screenshot if it helps explain)

This test fails at the moment on komodo (https://github.com/equinor/komodo-releases/actions/runs/12459362337/job/34776499584). Locally it passes, but tbh not sure why since all the realizations fail (fail_simulation) immediately, when I check the status file in `everest_output/detached_node_output/.session`
```json
  1 {"status": {"__enum__": "ServerStatus.failed"}, "message": "Optimization failed: not enough successful realizations to proceed."}
```
and as such this should fail regardless.

Moreover, when the test passes, it seems that there is a lingering task:
```
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<LocalDriver._run() running at /data/workspace/ert/src/ert/scheduler/local_driver.py:89> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

### What did you expect to happen?

The test should pass.

### steps to reproduce

```Python
Login to any rgx node, source komodo/bleeding, komodoenv and execute 
` pytest tests/everest/test_detached.py::test_https_requests`
```

### Environment where bug has been observed

- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [x] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by DanSava** [comment]
With https://github.com/equinor/ert/pull/9434 some of the testing functionality has been altered leading to the observed failures
