### ISSUE TITLE
Reduce running time of the HM tutorial test pipeline

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#963]
We should spend some effort reducing the running time of the HM tutorial version used in the test pipeline. Reducing the disk usage by having the forward model clean up after itself would also be beneficial.

**Comment by jondequinor** [comment]
We've opted to adding _short_ HM cases. The HM tutorial is likely not going to be reduced in runtime, but maybe only run for some releases (stable, bleeding).

See https://github.com/equinor/komodo-releases/pull/937 and is resolved by https://github.com/equinor/scout/issues/289
