### ISSUE TITLE
Test more forward models and workflows

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#964]
We should compare the list of forward models and workflows we deploy to the ones currently used in our integration tests. Including more of them in the test pipeline would be nice!

**Comment by eivindjahren** [comment]
I have compiled a list of forward models/workflows, and where they are tested. By "we" I have taken the developers generally involved in developing ert so I have included semeio, pyscal & res2df, but excluded e.g. grid3d_maps & subscript (although my impression is that there is in general good coverage by running drogon).  There should be nightly (and per pr in some cases) tests for all listed tests.

Those both tested in some full setup and with some test in the repo where it is defined:

* `MAKE_DIRECTORY`: drogon, reek_hm, ert/tests
* `COPY_FILE`:  drogon, reek_hm, ert/tests/unit_tests
* `COPY_DIRECTORY`: drogon, reek_hm, ert/tests
* `DESIGN_KW`: semeio/tests, drogon
* `RES2CSV`: res2df/tests, drogon
* `SYMLINK`: is an alias for `MAKE_SYMLINK` so indirectly tested
* `MOVE_FILE`: reek_hm, ert/tests
* `DESIGN2PARAMS`:  semeio/tests, drogon
* `RMS`: ert/tests, drogon
* `ECLIPSE100`:  ert/tests, reek_hm, drogon
* `PYSCAL`: pyscal/tests, semeio/tests, 
* `DESIGN_KW`: semeio/tests, drogon, reek_hm
* `GENDATA_RFT`: semeio/tests, reek_hm, (is in drogon but not in a config we run regularly)
* `RMS`: ert/tests, fmu-drogon
* `MISFIT_PREPROCESSOR`: ert/tests, drogon

Those with just one kind of test:

* `OTS`: semeio/tests
* `CAREFUL_COPY_FILE`: ert/tests
* `MAKE_SYMLINK`:  drogon
* `REPLACE_STRING`: semeio/tests
* `REMOVE_NOSIM`: semeio/tests
* `DELETE_DIRECTORY`: ert/tests (is in drogon but not in a config we run regularly)
* `INSERT_NOSIM`: semeio/tests, (commented out in drogon)
* `DELETE_FILE`: ert/tests, (is commented out in drogon)
* `ECLIPSE300`: ert/tests (not directly, but through common ecl_run.py)
* `FLOW`: ert/ci/testkomodo.sh
* `CSV_EXPORT`: ert/tests
* `CSV_EXPORT2`: semeio/tests
* `CSV2RES`: res2df/tests
* `AHM_ANALYSIS`: semeio/tests
* `LOCALISATION_JOB`: semeio/tests

Those with no tests:

* `TEMPLATE_RENDER`
* `GEN_DATA_RFT_CSV_EXPORT`

**Comment by eivindjahren** [comment]
Closing this as there are tests for all forward_models/workflows we can find and we are generally increasing test coverage as we go.
