### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#965]
We should announce, both in the repository and internally that we are dropping Python 2 support for new development.

Leave Python 2 development after the PCA and komodoenv has been finished.

We should announce a last release soon.

- [x] Annoucement in slack, last Python 2 supported version is komodo stable 2020.09
- [x] Annoucement in yammer, last Python 2 supported version is komodo stable 2020.09
- [x] Create tag for last python 2 compatible version
- [x] Update readme

**Comment by markusdregi** [comment]
An announcement should also be made on slack.

**Comment by oysteoh** [comment]
Announcement`s has been made on slack and yammer. I guess we should wait until we actually stop supporting python2 to adjust the readme in the repo?

**Comment by markusdregi** [comment]
Sounds like a good idea 👍 I think we should also create tags for the last Python 2 compatible versions in case of needed later when we update the readme...
