### ISSUE TITLE
Dropping RHEL 6 support

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#973]
Announce abandonment of RHEL 6 support on slack, yammer and GitHub.

**Comment by jondequinor** [comment]
Did we decide on a date?

**Comment by markusdregi** [comment]
We are leaning towards the September release being the last one with Python 2 support 🎉 Less then a year too late 💣

**Comment by oysteoh** [comment]
Annoucements has been made on slack and yammer. Is there really a need for updating the repo with the lack of RHEL6 support?

**Comment by markusdregi** [comment]
Nope, this can be closed. ERT still runs on RHEL6, we just stopped deploying it for that platform internally...
