### ISSUE TITLE
Extend tests with spe1 to multi core (parallel simulation)

### ISSUE THREAD

**Issue by hnformentin** [equinor/ert#985]
Make a new test (e.g. in Jenkins) to run simulations in parallel (refer to NUM_CPU keyword).

**Comment by eivindjahren** [comment]
Nobody is working on this, and I think we are extending our test-suite continously as we need it. Not sure if this should be a priority. What do you think @oyvindeide and @sondreso ?

**Comment by oyvindeide** [comment]
Did you look into the tests currently dealing with NUM_CPU? I know they were extended, but not sure if enough. There are a lot of assumptions in that part of the code, so _might_ be worth implementing something more.

**Comment by eivindjahren** [comment]
I only know about the unit tests regarding NUM_CPU. Perhaps @berland or @xjules know more about what is ran nightly.

**Comment by berland** [comment]
SPE1 is run in webviz-ert's komodo testing. ERT spends 40 seconds running the config file involving SPE1, using a local queue. Running in parallel would steal resources from other runners, so using parallel runs has both an upside and a downside. Closing as won't-fix.
